import React,{useEffect,useRef,useState} from 'react';
import {ShieldCheck,KeyRound,ArrowRight} from 'lucide-react';
import {api as defaultApi} from '../api.js';

export default function AccountSecurity({api=defaultApi,user,notify,onReauthenticate,onDirty,required=false,issuer='Wimblo'}){
 const [status,setStatus]=useState(null),[password,setPassword]=useState(''),[code,setCode]=useState(''),[pending,setPending]=useState(null),[recoveryCodes,setRecoveryCodes]=useState(null),[savedCodes,setSavedCodes]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const revoked=useRef(false),mandatory=required||status?.required===true;
 useEffect(()=>{if(revoked.current)return;let active=true;api('/auth/mfa/status').then(r=>active&&setStatus(r)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[api,user?.id]);
 useEffect(()=>()=>{onDirty?.(false);},[onDirty]);
 const work=async action=>{setBusy(true);setError('');try{await action();}catch(e){setError(e.message);}finally{setPassword('');setBusy(false);}};
 const begin=()=>work(async()=>{const entered=password;setPassword('');const r=await api('/auth/mfa/enroll',{method:'POST',body:{password:entered}});setPending(r);setCode('');onDirty?.(true);});
 const confirm=()=>work(async()=>{const entered=code;setCode('');const r=await api('/auth/mfa/confirm',{method:'POST',body:{code:entered}});revoked.current=true;setPending(null);setPassword('');setRecoveryCodes(r.recoveryCodes);setStatus(s=>({...s,enabled:true}));onDirty?.(true);notify?.('Multi-factor authentication enabled. Save your recovery codes before signing in again.');});
 const disable=()=>work(async()=>{const enteredPassword=password,enteredCode=code;setPassword('');setCode('');await api('/auth/mfa/disable',{method:'POST',body:{password:enteredPassword,code:enteredCode}});revoked.current=true;onDirty?.(false);notify?.('Multi-factor authentication disabled. Sign in again.');onReauthenticate?.();});
 const continueSignIn=()=>{setRecoveryCodes(null);setPending(null);setCode('');setPassword('');onDirty?.(false);onReauthenticate?.();};
 return <><div className="page-header"><div><h1>Account security</h1><p>Protect your Wimblo sign-in with an authenticator app.</p></div><ShieldCheck size={24} aria-hidden="true"/></div>
 {error&&<div className="error-banner" role="alert">{error}</div>}
 {recoveryCodes?<section className="panel"><div className="section-title"><div><h2>Save your recovery codes</h2><p>MFA is enabled. Your previous sessions have ended.</p></div></div><p>Store these codes somewhere safe outside Wimblo. Each code works once if you cannot access your authenticator. These codes are shown only now.</p><div className="form-grid" aria-label="One-time recovery codes">{recoveryCodes.map(value=><code key={value}>{value}</code>)}</div><p className="table-note">Do not share your setup key, authenticator codes, or recovery codes with anyone.</p><label><input type="checkbox" checked={savedCodes} onChange={e=>setSavedCodes(e.target.checked)}/> I have saved my recovery codes.</label><div className="form-actions"><button type="button" className="btn btn-primary" disabled={!savedCodes} onClick={continueSignIn}>Continue to sign in<ArrowRight size={15}/></button></div></section>:
 !status?<section className="panel"><p>{error?'Account security could not load. Reopen this screen to try again.':'Loading account security…'}</p></section>:
 !status.available?<section className="panel"><div className="section-title"><div><h2>MFA is unavailable</h2><p>An administrator must configure a protected encryption key on the server.</p></div></div><p>{status.enabled?'MFA remains enabled for your account. Contact your organization administrator to restore account security before signing in again.':mandatory?'MFA is required for your account. Business records remain locked until your organization administrator restores setup and you complete enrollment.':'Setup is unavailable until the server is configured. Your password remains required for sign-in.'}</p></section>:
 pending?<section className="panel"><div className="section-title"><div><h2>Connect your authenticator</h2><p>Finish setup before {new Date(pending.expiresAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}.</p></div></div><ol><li>In your authenticator app, add an account manually.</li><li>Use account <strong>{user?.email}</strong>, issuer <strong>{issuer}</strong>, and this setup key.</li><li>Choose time-based codes with SHA-1, six digits, and a 30-second interval.</li></ol><label className="field">Setup key<input readOnly value={pending.secret} autoComplete="off" spellCheck={false}/></label><p className="table-note">This key is shown for setup only. It stays on this screen; Wimblo does not send it to a QR service.</p><form onSubmit={e=>{e.preventDefault();confirm();}}><div className="form-grid"><label className="field">Six-digit authenticator code<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)}/><span className="subtle">Enabling MFA ends your current sessions. Save the recovery codes on the next screen, then sign in again.</span></label></div><div className="form-actions"><button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>{setPending(null);setCode('');onDirty?.(false);}}>Cancel setup</button><button type="submit" className="btn btn-primary" disabled={busy}>{busy?'Verifying…':'Enable MFA'}<ShieldCheck size={15}/></button></div></form></section>:
 <section className="panel"><div className="section-title"><div><h2>{status.enabled?'Multi-factor authentication is on':'Add a second sign-in factor'}</h2><p>{status.enabled?`${status.recoveryCodesRemaining} unused recovery codes remain. Your authenticator is required when you sign in.`:'After your password, enter a six-digit code from your authenticator app.'}</p></div></div>
 {mandatory&&<p className="table-note">Your account requires MFA for every sign-in. This applies to staff, viewers and event helpers as well as administrators. MFA cannot be disabled. Use an unused recovery code when your authenticator is unavailable; contact your organization administrator if you have no remaining codes.</p>}
 <p>{status.enabled&&mandatory?'Sign in with your password and an authenticator code or one unused recovery code.':status.enabled?'To turn MFA off, confirm your password and an unused authenticator or recovery code. This ends your existing sessions.':'Start with your current password. Wimblo will provide a unique setup key and ask you to verify a code before MFA is enabled.'}</p>
 {(!status.enabled||!mandatory)&&<form onSubmit={e=>{e.preventDefault();status.enabled?disable():begin();}}><div className="form-grid"><label className="field">Current password<input required type="password" disabled={busy} maxLength={200} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/><span className="subtle">The password field clears when you submit.</span></label>{status.enabled&&<label className="field">Authenticator or recovery code<input required maxLength={17} autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)}/><span className="subtle">Use a fresh six-digit code, or an unused recovery code exactly as saved.</span></label>}</div><div className="form-actions"><button type="submit" className={status.enabled?'btn btn-secondary':'btn btn-primary'} disabled={busy}><KeyRound size={15}/>{busy?'Working…':status.enabled?'Disable MFA':'Set up authenticator'}</button></div></form>}</section>}
 </>;
}
