import React,{useEffect,useRef,useState} from 'react';
import {Plus,Save,RefreshCw,ChevronRight} from 'lucide-react';
const TYPES=['Individual','Business','Foundation','Alumni','Employee','Staff','Community partner'];
const PREFERENCES=['Email','Phone','Post','Do not contact'];
const fresh=()=>({name:'',filters:{segmentTokens:[],segmentMatch:'Any',types:[],preferences:[]}});
const tokens=value=>value.split(',').map(s=>s.trim()).filter(Boolean);
export default function Audiences({api,user,onDirty,onSelection,channel='Print',disabled=false}){
 const editable=['admin','staff'].includes(user?.role),selecting=typeof onSelection==='function';
 const [definitions,setDefinitions]=useState([]),[definition,setDefinition]=useState(null),[draft,setDraft]=useState(fresh),[segmentText,setSegmentText]=useState(''),[dirty,setDirty]=useState(false),[preview,setPreview]=useState(null),[selected,setSelected]=useState([]),[format,setFormat]=useState(channel),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reason,setReason]=useState(''),[pendingId,setPendingId]=useState(null);
 const generation=useRef(0),alive=useRef(true);
 useEffect(()=>{alive.current=true;api('/audiences').then(r=>alive.current&&setDefinitions(r.audiences)).catch(e=>alive.current&&setError(e.message));return()=>{alive.current=false;generation.current++;};},[api]);
 useEffect(()=>{onDirty?.(dirty);},[dirty,onDirty,selecting]);
 useEffect(()=>()=>onDirty?.(false),[onDirty]);
 const invalidate=()=>{generation.current++;setPreview(null);setSelected([]);onSelection?.(null);};
 useEffect(()=>{setFormat(channel);invalidate();},[channel]);
 const perform=async action=>{setBusy(true);setError('');setNotice('');try{await action();}catch(e){if(alive.current){invalidate();setError(e.message);}}finally{if(alive.current)setBusy(false);}};
 const choose=id=>{if(dirty){setPendingId(id);return;}loadDefinition(id);};
 const loadDefinition=id=>{invalidate();setReason('');setError('');setNotice('');setDirty(false);if(!id){setDefinition(null);setDraft(fresh());setSegmentText('');return;}perform(async()=>{const r=await api('/audiences/'+id);if(!alive.current)return;setDefinition(r.audience);setDraft({name:r.audience.name,filters:r.audience.filters});setSegmentText(r.audience.filters.segmentTokens.join(', '));});};
 const edit=patch=>{invalidate();setDraft(d=>({...d,...patch}));setDirty(true);};
 const filter=(key,value)=>edit({filters:{...draft.filters,[key]:value}});
 const toggle=(key,value,checked)=>filter(key,checked?[...draft.filters[key],value]:draft.filters[key].filter(x=>x!==value));
 const save=()=>perform(async()=>{const body={name:draft.name,filters:{...draft.filters,segmentTokens:tokens(segmentText)}};const r=await api(definition?'/audiences/'+definition.id:'/audiences',{method:definition?'PATCH':'POST',body:definition?{...body,version:definition.version,status:'Active'}:body});if(!alive.current)return;invalidate();setDefinition(r.audience);setDraft({name:r.audience.name,filters:r.audience.filters});setSegmentText(r.audience.filters.segmentTokens.join(', '));setDefinitions(ds=>[r.audience,...ds.filter(d=>d.id!==r.audience.id)]);setDirty(false);setNotice('Audience saved. Review current eligibility before choosing recipients.');});
 const retire=()=>perform(async()=>{const r=await api('/audiences/'+definition.id,{method:'PATCH',body:{version:definition.version,name:definition.name,filters:definition.filters,status:'Retired',reason:reason.trim()}});if(!alive.current)return;invalidate();setDefinition(r.audience);setDefinitions(ds=>ds.map(d=>d.id===r.audience.id?r.audience:d));setDirty(false);setReason('');setNotice('Audience retired. Its definition and preparation history remain retained.');});
 const review=(after=null)=>perform(async()=>{const request=++generation.current;setSelected([]);onSelection?.(null);setPreview(null);const q=new URLSearchParams({version:String(definition.version),channel:format,limit:'100',...(after?{after}:{})});const r=await api('/audiences/'+definition.id+'/preview?'+q);if(!alive.current||request!==generation.current)return;setPreview(r);});
 const select=(id,checked)=>{const next=checked?[...selected,id]:selected.filter(x=>x!==id);setSelected(next);onSelection?.(next.length?{constituentIds:next,audience:{id:definition.id,version:definition.version,sourceDigest:preview.sourceDigest}}:null);};
 const page=preview?.recipients||[];
 return <>
 {!selecting&&<div className="page-header"><div><h1>Audiences</h1><p>Build reusable groups, then review who may receive a prepared message.</p></div></div>}
 <section className="panel audience-workspace"><div className="section-title"><div><h2>{selecting?'Use a saved audience':'Saved groups'}</h2><p>Criteria find matching profiles. Contact preferences still decide eligibility.</p></div>{editable&&<button type="button" className="btn btn-secondary" disabled={busy||disabled} onClick={()=>choose('')}><Plus size={15}/>New audience</button>}</div>
 {pendingId!==null&&<section className="discard-decision" role="alertdialog" aria-label="Unsaved group criteria"><h3>Keep your criteria edits?</h3><p>Saved definitions and preparations remain retained. Only unsaved criteria are discarded.</p><div className="form-actions"><button type="button" className="btn btn-primary" onClick={()=>setPendingId(null)}>Keep editing criteria</button><button type="button" className="btn btn-secondary" onClick={()=>{const id=pendingId;setPendingId(null);loadDefinition(id);}}>Discard criteria changes</button></div></section>}
 {error&&<p className="error-banner" role="alert">{error}</p>}{notice&&<p role="status" className="subtle">{notice}</p>}
 <label className="field">Saved audience<select disabled={busy||disabled} value={definition?.id||''} onChange={e=>choose(e.target.value)}><option value="">Choose or create an audience</option>{definitions.map(d=><option key={d.id} value={d.id}>{d.name} · v{d.version} · {d.status}</option>)}</select></label>
 {(definition||editable)&&<form onSubmit={e=>{e.preventDefault();save();}}><fieldset disabled={busy||disabled||!editable||definition?.status==='Retired'}><div className="form-grid">
 <label className="field">Audience name<input required maxLength={250} value={draft.name} onChange={e=>edit({name:e.target.value})}/></label>
 <label className="field">Exact segment tokens<input maxLength={2000} placeholder="Annual donor, Volunteer" value={segmentText} onChange={e=>{setSegmentText(e.target.value);edit({});}}/><small>Separate tokens with commas. Case and complete tokens matter; “VIP” does not match “NotVIP”.</small></label>
 <label className="field">Segment match<select value={draft.filters.segmentMatch} onChange={e=>filter('segmentMatch',e.target.value)}><option>Any</option><option>All</option></select><small>No tokens means no segment restriction.</small></label>
 <div className="field"><span>Constituent types</span><div className="audience-options">{TYPES.map(t=><label key={t}><input type="checkbox" checked={draft.filters.types.includes(t)} onChange={e=>toggle('types',t,e.target.checked)}/>{t}</label>)}</div><small>None selected means all types.</small></div>
 <div className="field"><span>Recorded contact preferences</span><div className="audience-options">{PREFERENCES.map(p=><label key={p}><input type="checkbox" checked={draft.filters.preferences.includes(p)} onChange={e=>toggle('preferences',p,e.target.checked)}/>{p}</label>)}</div><small>A filter never overrides “Do not contact” or grants consent.</small></div>
 </div>{editable&&<div className="form-actions"><span className="subtle">{dirty?'Unsaved criteria':definition?'Saved v'+definition.version:'Save criteria before reviewing recipients.'}</span><button className="btn btn-primary" disabled={busy||disabled||!draft.name.trim()||definition?.status==='Retired'}><Save size={15}/>Save audience</button></div>}</fieldset></form>}
 {definition?.status==='Active'&&<><div className="toolbar"><label className="field">Eligibility format<select disabled={busy||disabled||selecting} value={format} onChange={e=>{setFormat(e.target.value);invalidate();}}><option>Print</option><option>Email draft</option></select></label><button type="button" className="btn btn-secondary" disabled={busy||disabled||dirty} onClick={()=>review()}><RefreshCw size={15}/>{busy?'Reviewing…':'Review current eligibility'}</button></div><p className="subtle">Print excludes do-not-contact profiles. Email drafts additionally require Email preference and a valid primary email. Secondary contacts are never added. No message is sent.</p></>}
 {definition?.status==='Retired'&&<p className="scope-banner">This audience is retired. Its retained definition can be reviewed, but cannot prepare new correspondence or be reactivated.</p>}
 {preview&&<div className="audience-review"><div className="audience-counts" aria-label="Audience eligibility"><div><strong>{preview.matchedCount}</strong><span>Matching profiles</span></div><div><strong>{preview.eligibleCount}</strong><span>Eligible for {format}</span></div><div><strong>{preview.excludedCount}</strong><span>Excluded profiles</span></div></div><p className="subtle">Source profiles reviewed: {preview.totalCount}. {Object.entries(preview.reasonCounts||{}).map(([k,v])=>k+': '+v).join(' · ')||'No eligibility exclusions.'} Each excluded profile has one primary reason.</p><p className="scope-banner">This review pins current source records and audience v{definition.version}. Changed profiles or criteria require a fresh review. Only explicitly selected recipients are prepared.</p>
 {page.length?<div className="table-wrap"><table aria-label="Eligible audience recipients"><thead><tr>{selecting&&<th>Select</th>}<th>Recipient</th><th>Preference</th><th>Source revision</th></tr></thead><tbody>{page.map(p=><tr key={p.id}>{selecting&&<td><input type="checkbox" aria-label={'Select audience recipient '+p.name} checked={selected.includes(p.id)} disabled={busy||disabled||!selected.includes(p.id)&&selected.length>=100} onChange={e=>select(p.id,e.target.checked)}/></td>}<td>{p.name}<small className="subtle audience-reference">{p.id}</small></td><td>{p.preference}</td><td className="numeric">{p.version}</td></tr>)}</tbody></table></div>:<p className="empty-state">No eligible recipients on this page. Review your criteria and current contact preferences.</p>}
 <div className="form-actions"><span className="subtle">{selecting?selected.length+'/100 explicitly selected · ':''}{page.length} recipients on this page. Changing pages clears the selection.</span><button type="button" className="btn btn-secondary" disabled={busy||disabled||!preview.nextCursor} onClick={()=>review(preview.nextCursor)}>Next recipients<ChevronRight size={15}/></button></div>
 </div>}
 {editable&&definition?.status==='Active'&&!selecting&&<details><summary>Retire this audience</summary><p className="subtle">Retirement is permanent for this definition. It stops new preparations and retains history.</p><label className="field">Retirement reason<input maxLength={500} value={reason} disabled={busy||disabled} onChange={e=>setReason(e.target.value)}/></label><button type="button" className="btn btn-secondary" disabled={busy||disabled||dirty||!reason.trim()} onClick={retire}>Retire audience</button></details>}
 {!editable&&<p className="subtle">Your role can review audiences and eligibility. Creating, editing and preparation require staff access.</p>}
 </section></>;
}
