import React,{useEffect,useRef,useState} from 'react';
import {RefreshCw,Play,Square} from 'lucide-react';
const empty=()=>({name:'',audienceId:'',templateId:'',channel:'Print'});
export default function CommunicationWorkflows({api,user,data,onDirty,onOpen}){
 const writable=['admin','staff'].includes(user?.role);
 const [rules,setRules]=useState([]),[audiences,setAudiences]=useState([]),[templates,setTemplates]=useState([]),[draft,setDraft]=useState(empty),[preview,setPreview]=useState(null),[confirmed,setConfirmed]=useState(false),[detail,setDetail]=useState(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const alive=useRef(true),generation=useRef(0),mutating=useRef(false);
 const dirty=Boolean(draft.name||draft.audienceId||draft.templateId||reason);
 useEffect(()=>{onDirty?.(dirty);},[dirty,onDirty]);
 useEffect(()=>()=>onDirty?.(false),[onDirty]);
 const invalidate=()=>{generation.current++;setPreview(null);setConfirmed(false);};
 useEffect(()=>{invalidate();},[data?.constituents]);
 async function reload(){const epoch=++generation.current;setPreview(null);setConfirmed(false);const [r,a,t]=await Promise.all([api('/communication-workflows'),api('/audiences'),api('/correspondence/templates')]);if(!alive.current||epoch!==generation.current)return;setRules(r.workflows);setAudiences(a.audiences.filter(x=>x.status==='Active'));setTemplates(t.templates.filter(x=>x.kind==='Messaging'));setDetail(null);}
 useEffect(()=>{alive.current=true;setBusy(true);reload().catch(e=>alive.current&&setError(e.message)).finally(()=>alive.current&&setBusy(false));return()=>{alive.current=false;generation.current++;};},[api]);
 async function perform(fn){if(mutating.current)return;mutating.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){if(alive.current){invalidate();setError(e.message);}}finally{mutating.current=false;if(alive.current)setBusy(false);}}
 const change=patch=>{invalidate();setDraft(p=>({...p,...patch}));};
 const audience=audiences.find(x=>x.id===draft.audienceId),template=templates.find(x=>x.id===draft.templateId);
 async function review(){await perform(async()=>{invalidate();const epoch=generation.current;const result=await api('/audiences/'+audience.id+'/preview?'+new URLSearchParams({version:String(audience.version),channel:draft.channel,limit:'100'}));if(alive.current&&epoch===generation.current)setPreview(result);});}
 async function activate(){await perform(async()=>{const result=await api('/communication-workflows',{method:'POST',body:{name:draft.name.trim(),audienceId:audience.id,audienceVersion:audience.version,sourceDigest:preview.sourceDigest,templateId:template.id,templateVersion:template.version,channel:draft.channel,confirmed:true}});if(!alive.current)return;setDraft(empty());setReason('');invalidate();await reload();if(alive.current){setDetail({workflow:result.workflow,outcomes:[],outcomeCount:1});setNotice('Workflow activated. Existing eligible profiles are a baseline; no historical drafts were created.');}});}
 async function inspect(id){await perform(async()=>{const epoch=++generation.current;setPreview(null);setConfirmed(false);const result=await api('/communication-workflows/'+id);if(alive.current&&epoch===generation.current){setDetail(result);setReason('');}});}
 async function retire(){await perform(async()=>{const result=await api('/communication-workflows/'+detail.workflow.id+'/retire',{method:'POST',body:{version:detail.workflow.version,reason:reason.trim()}});if(!alive.current)return;setReason('');await reload();if(alive.current){setDetail({workflow:result.workflow,outcomes:[],outcomeCount:null});setNotice('Workflow retired. Saved drafts and execution history remain retained.');}});}
 const ready=writable&&!busy&&draft.name.trim()&&audience&&template&&preview&&preview.totalCount<=1000&&confirmed;
 return <div className="communication-workflows"><div className="page-header"><div><p className="eyebrow">Communications</p><h1>Draft workflows</h1><p>Review a group. Activate once. Inspect every draft before taking action.</p></div><button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>perform(reload)}><RefreshCw size={16}/>Refresh workflows</button></div>
 <p className="scope-banner">New audience entries can create one Messaging draft per observed entry. Nothing is sent. Existing eligible profiles are recorded as a baseline, with no historical backfill.</p>
 {error&&<p role="alert" className="error-banner">{error}</p>}{notice&&<p role="status" className="scope-banner">{notice}</p>}
 {writable&&<section className="panel"><div className="section-title"><div><h2>Activate a prospective workflow</h2><p>Choose saved criteria and wording, then review the current starting group.</p></div></div><form onSubmit={e=>{e.preventDefault();if(ready)activate();}}><fieldset disabled={busy}><div className="form-grid">
 <label className="field">Workflow name<input required maxLength={250} value={draft.name} onChange={e=>change({name:e.target.value})} placeholder="Welcome new community partners"/></label>
 <label className="field">Audience<select required value={draft.audienceId} onChange={e=>change({audienceId:e.target.value})}><option value="">Choose an active audience</option>{audiences.map(a=><option key={a.id} value={a.id}>{a.name} · v{a.version}</option>)}</select><small>Saved criteria never override recorded contact preferences.</small></label>
 <label className="field">Messaging template<select required value={draft.templateId} onChange={e=>change({templateId:e.target.value})}><option value="">Choose saved wording</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name} · v{t.version}</option>)}</select></label>
 <label className="field">Draft format<select value={draft.channel} onChange={e=>change({channel:e.target.value})}><option>Print</option><option>Email draft</option></select><small>Email drafts require Email preference and a valid primary email.</small></label>
 </div>{template&&<details><summary>Review selected wording · v{template.version}</summary><h3>{template.subject}</h3><p className="preserve-space">{template.body}</p></details>}
 <div className="form-actions"><button type="button" className="btn btn-secondary" disabled={busy||!audience||!template} onClick={review}>Review activation baseline</button><button type="button" className="text-btn" disabled={busy||!dirty} onClick={()=>{setDraft(empty());invalidate();setReason('');}}>Clear unsaved activation</button></div>
 {preview&&<div className="audience-review"><div className="audience-counts" aria-label="Workflow activation baseline"><div><strong>{preview.eligibleCount}</strong><span>Existing eligible profiles · no drafts</span></div><div><strong>{preview.matchedCount}</strong><span>Matching profiles</span></div><div><strong>{preview.excludedCount}</strong><span>Excluded profiles</span></div></div><p className="subtle">{preview.totalCount} source profiles reviewed. Future observed eligible entries create reviewable drafts. Changes to selected criteria, wording or your account close this activation.</p>{preview.totalCount>1000&&<p role="alert" className="error-banner">This local workflow supports at most 1,000 current profiles. It is not ready for your full historical audience.</p>}<label className="workflow-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this baseline and wording, and authorize future draft creation only.</label></div>}
 <div className="form-actions"><span className="subtle">{preview?'Review and confirm before activating.':'A fresh baseline review is required.'}</span><button type="submit" className="btn btn-primary" disabled={!ready}><Play size={16}/>Activate draft workflow</button></div></fieldset></form></section>}
 <section className="panel"><div className="section-title"><h2>Activation register</h2><span className="subtle">Latest 100 · maximum 20 active</span></div>{rules.length?<div className="table-wrap"><table aria-label="Draft workflow activations"><thead><tr><th scope="col">Workflow</th><th scope="col">Status</th><th scope="col">Format</th><th scope="col" className="numeric">Baseline</th><th scope="col">Latest outcome</th></tr></thead><tbody>{rules.map(r=><tr key={r.id}><td><button type="button" className="record-link" disabled={busy} onClick={()=>inspect(r.id)}>{r.name}</button><small className="cell-detail">v{r.version}</small></td><td>{r.status}{r.status==='Active'&&!r.sourceCurrent&&<small className="cell-detail">Source changed · closure pending</small>}</td><td>{r.channel}</td><td className="numeric">{r.baselineCount}</td><td>{r.lastOutcome?.status||'—'}</td></tr>)}</tbody></table></div>:<p className="empty-state">No activations yet. Save an audience and a Messaging template, then review their baseline above.</p>}</section>
 {detail&&<section className="panel"><div className="section-title"><div><h2>{detail.workflow.name}</h2><p>{detail.workflow.status} · v{detail.workflow.version} · Not sent</p></div><button type="button" className="text-btn" disabled={busy} onClick={()=>inspect(detail.workflow.id)}>Refresh this history</button></div>{detail.outcomes?.length?<div className="table-wrap"><table aria-label="Workflow execution history"><thead><tr><th scope="col">Time</th><th scope="col">Outcome</th><th scope="col">Explanation</th></tr></thead><tbody>{detail.outcomes.map(o=><tr key={o.id}><td><time dateTime={o.at}>{o.at}</time></td><td>{o.status}</td><td>{o.reason}{o.communicationId&&<button type="button" className="record-link" disabled={busy} onClick={()=>perform(()=>onOpen?.('communications',o.communicationId))}>Open draft</button>}</td></tr>)}</tbody></table></div>:<p className="subtle">Refresh this history to inspect retained outcomes.</p>}<p className="table-note">{detail.outcomeCount==null?'Refresh this history to see its retained outcome count.':'Latest 100 outcomes of '+detail.outcomeCount+'.'} Drafts remain in Communications; source changes require human review.</p>{writable&&detail.workflow.status==='Active'&&(user.role==='admin'||detail.workflow.ownerId===user.id)&&<details><summary>Retire this activation</summary><p>Retirement stops future drafts. Retained history and saved drafts remain. A new activation requires a new baseline review.</p><label className="field">Retirement reason<input maxLength={500} disabled={busy} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" className="btn btn-secondary" disabled={busy||!reason.trim()} onClick={retire}><Square size={16}/>Retire workflow</button></details>}</section>}
 <p className="table-note">The server checks observed membership every 30 seconds. This local capability has bounded retries, 1,000 retained profile watermarks and 1,000 entry episodes per activation. Provider delivery, recurring sequences and historical campaign automation remain pending.</p>
 </div>;
}
