import React,{useEffect,useState,useRef} from 'react';
import {Play,Save,Plus,Download,X} from 'lucide-react';
import {api as defaultApi} from '../api.js';
import {money,dateLabel,download,toCSV} from '../lib.js';

const blank=()=>({name:'Untitled report',entity:'gifts',columns:['date','donorName','amount'],filters:[],groupBy:[],aggregates:[],includeVoided:false});
const ops={eq:'equals',ne:'does not equal',contains:'contains',startsWith:'starts with',gt:'greater than',gte:'at least',lt:'less than',lte:'at most',empty:'is empty',notEmpty:'is not empty',in:'is one of'};
const show=(value,column)=>value==null?'—':column.type==='money'?money(value):column.type==='date'&&Number.isFinite(Date.parse(value))?dateLabel(value):String(value);
const definition=report=>{const {id,version,createdAt,updatedAt,...body}=report;return body;};
const filterDollars=value=>{if(!Number.isSafeInteger(value))throw new Error('Saved money filter is not exact integer cents. Review the definition.');const n=BigInt(value),absolute=n<0n?-n:n;return (n<0n?'-':'')+String(absolute/100n)+'.'+String(absolute%100n).padStart(2,'0');};
const filterCents=value=>{const match=/^(-?)(\d+)(?:\.(\d{1,2}))?$/.exec(String(value).trim());if(!match)throw new Error('Enter a signed amount with no more than two decimal places.');const amount=(BigInt(match[2])*100n+BigInt((match[3]||'').padEnd(2,'0')))*(match[1]?-1n:1n);if(amount>BigInt(Number.MAX_SAFE_INTEGER)||amount<BigInt(Number.MIN_SAFE_INTEGER))throw new Error('This report filter amount is too large.');return Number(amount);};
export default function CustomReports({user,api=defaultApi,onOpen,notify,onDirty}){
 const [catalog,setCatalog]=useState(null),[reports,setReports]=useState([]),[draft,setDraft]=useState(blank),[saved,setSaved]=useState(null),[result,setResult]=useState(null),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[fieldQuery,setFieldQuery]=useState(''),[pageOffsets,setPageOffsets]=useState([0]);
 const requestGeneration=useRef(0),busyGeneration=useRef(0),accessKey=String(user?.id||'')+':'+String(user?.role||''),[loadedAccess,setLoadedAccess]=useState(null);
 const authority=useRef(null);authority.current={api,key:accessKey};
 const editable=['admin','staff'].includes(user?.role);
 useEffect(()=>{const generation=++requestGeneration.current;setCatalog(null);setReports([]);setResult(null);setPageOffsets([0]);setSaved(null);setDraft(blank());setError('');setStatus('');setBusy(false);busyGeneration.current=0;setLoadedAccess({api,key:accessKey});Promise.all([api('/custom-reports/catalog'),api('/custom-reports')]).then(([c,r])=>{if(generation===requestGeneration.current){setCatalog(c);setReports(r.reports);}}).catch(e=>generation===requestGeneration.current&&setError(e.message));return()=>{requestGeneration.current++;};},[api,accessKey]);
 const currentAccess=loadedAccess?.api===api&&loadedAccess?.key===accessKey;
 const entity=catalog?.entities.find(e=>e.id===draft.entity),fields=entity?.fields||[],field=key=>fields.find(f=>f.key===key),numeric=fields.filter(f=>f.aggregateable),groupable=fields.filter(f=>f.groupable),unreviewedFilters=draft.filters.some(f=>!field(f.field));
 const displayDefinition=report=>{const body=definition(report),reportFields=catalog?.entities.find(e=>e.id===body.entity)?.fields||[];return {...body,filters:body.filters.map(f=>{const type=reportFields.find(x=>x.key===f.field)?.type;if(!type&&f.value!==undefined)return {...f,_savedValue:f.value};return type==='money'&&f.value!==undefined?{...f,value:Array.isArray(f.value)?f.value.map(filterDollars).join(', '):filterDollars(f.value)}:f;})};};
 const change=patch=>{requestGeneration.current++;setDraft(d=>({...d,...patch}));setResult(null);setPageOffsets([0]);setStatus('');onDirty?.(true);};
 const load=id=>{requestGeneration.current++;const report=reports.find(r=>r.id===id);setSaved(report||null);setDraft(report?displayDefinition(report):blank());setResult(null);setPageOffsets([0]);setError('');setStatus('');onDirty?.(false);};
 const payload=()=>({...draft,filters:draft.filters.map(filter=>{const {_savedValue,...f}=filter;if(!field(f.field))throw new Error('Review all source fields to resolve each saved filter before running or saving.');if(['empty','notEmpty'].includes(f.op))return {field:f.field,op:f.op};if(f.value===undefined||String(f.value).trim()==='')throw new Error('Enter a value for each filter.');const type=field(f.field)?.type;const convert=value=>type==='money'?filterCents(value):type==='number'?Number(value):value;return {...f,value:f.op==='in'?String(f.value).split(',').map(v=>convert(v.trim())):convert(f.value)};})});
 const perform=async action=>{const generation=++requestGeneration.current,current=()=>generation===requestGeneration.current&&authority.current.api===api&&authority.current.key===accessKey;busyGeneration.current=generation;setBusy(true);setError('');setStatus('');try{await action(current);}catch(e){if(current()){setError(e.message);if(e.status===409)setResult(null);}}finally{if(busyGeneration.current===generation)setBusy(false);}};
 const run=()=>perform(async current=>{const r=await api('/custom-reports/run',{method:'POST',body:payload()});if(!current())return;setResult(r);setPageOffsets([0]);setStatus('Report ran against current workspace records.');});
 const page=(offset,previous=false)=>perform(async current=>{const r=await api(`/custom-reports/run?offset=${offset}&limit=${result.page.limit}&fingerprint=${result.sourceFingerprint}`,{method:'POST',body:result.definition});if(!current())return;setResult(r);setPageOffsets(offsets=>previous?offsets.slice(0,-1):[...offsets,offset]);setStatus('Report page verified against the same source facts and definition.');});
 const exportAll=()=>perform(async current=>{const reviewed=result,r=await api(`/custom-reports/export?fingerprint=${encodeURIComponent(reviewed.sourceFingerprint)}`,{method:'POST',body:reviewed.definition});if(!current())return;if(r.complete!==true||r.sourceFingerprint!==reviewed.sourceFingerprint||r.rowCount!==reviewed.totalResultRows||typeof r.csv!=='string'||typeof r.filename!=='string')throw new Error('The complete export could not be verified. Rerun the report before downloading.');download(r.filename,r.csv,'text/csv;charset=utf-8');setStatus(`Complete CSV downloaded · ${r.rowCount} result rows · source verified. Excel-compatible CSV; not a native workbook.`);});
 const inspectFields=()=>perform(async current=>{const selected=draft.entity,r=await api(`/custom-reports/catalog?entity=${encodeURIComponent(selected)}`);if(!current())return;const inspected=r.entities?.[0];if(r.entities?.length!==1||inspected?.id!==selected||!Array.isArray(inspected.fields)||r.inspection?.entity!==selected||!Number.isSafeInteger(r.inspection.sourceRowsInspected)||r.inspection.sourceRowsInspected<0)throw new Error('Source field inspection could not be verified. Try again before changing your report.');const refreshedDraft={...draft,filters:draft.filters.map(f=>{const type=inspected.fields.find(x=>x.key===f.field)?.type;if(!Object.hasOwn(f,'_savedValue')||!type)return f;const {_savedValue,...resolved}=f;return {...resolved,value:type==='money'?(Array.isArray(_savedValue)?_savedValue.map(filterDollars).join(', '):filterDollars(_savedValue)):_savedValue};})};setCatalog(c=>({...c,entities:c.entities.map(e=>e.id===selected?inspected:e)}));setDraft(refreshedDraft);setResult(null);setPageOffsets([0]);setStatus(`Source fields reviewed · ${r.inspection.sourceRowsInspected} visible source rows inspected.${r.inspection.includesVoidedGiftRows?' Field review includes authorized voided gifts; your report filters are unchanged.':''} Check your selected fields and rerun the report. Nested discovery remains limited to four levels and 100 items per array.`);});
 const save=()=>perform(async current=>{const body=payload(),r=await api(saved?`/custom-reports/${saved.id}`:'/custom-reports',{method:saved?'PATCH':'POST',body:saved?{...body,version:saved.version}:body});if(!current())return;setSaved(r.report);setReports(rs=>[r.report,...rs.filter(x=>x.id!==r.report.id)]);setDraft(displayDefinition(r.report));setResult(null);setStatus(`Definition saved · version ${r.report.version}. Rerun to see current records.`);onDirty?.(false);notify?.('Report definition saved');});
 const filterChange=(index,patch)=>change({filters:draft.filters.map((f,i)=>{if(i!==index)return f;const {_savedValue,...edited}=f;return Object.hasOwn(patch,'field')||Object.hasOwn(patch,'value')?{...edited,...patch}:{...f,...patch};})});
 const calculationChange=(index,patch)=>change({aggregates:draft.aggregates.map((a,i)=>i===index?{...a,...patch}:a)});
 const renderTable=(columns,rows,references)=>rows.length?<div className="table-wrap"><table><thead><tr>{columns.map((c,i)=><th scope="col" key={c.key||i} className={['money','number'].includes(c.type)?'money':''}>{c.label}{c.unit==='cents'?' · USD':''}</th>)}{onOpen&&<th scope="col">Source</th>}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((v,i)=><td key={i} className={['money','number'].includes(columns[i].type)?'money':''}>{show(v,columns[i])}</td>)}{onOpen&&<td>{references?.[index]?<button type="button" className="text-btn" onClick={()=>onOpen(references[index].collection,references[index].id)}>Open record</button>:'Grouped total'}</td>}</tr>)}</tbody></table></div>:<div className="empty-state">No records match these filters.</div>;
 return <><div className="page-header"><div><h1>Custom reports</h1><p>Choose saved fields, narrow the records, and calculate a result you can trace.</p></div><button type="button" className="btn btn-secondary" onClick={()=>load('')} disabled={busy||!catalog||!currentAccess}><Plus size={15}/>New report</button></div>
 {error&&<div className="error-banner" role="alert">{error}</div>}{status&&<p className="subtle" role="status">{status}</p>}
 {!catalog||!currentAccess?<section className="panel"><p>Loading report fields…</p></section>:<section className="panel"><div className="section-title"><div><h2>Build a report</h2><p>Save the definition, then rerun it whenever the records change.</p></div></div>
 <form onSubmit={e=>{e.preventDefault();run();}}><div className="form-grid">
 <label className="field">Saved definition<select value={saved?.id||''} onChange={e=>load(e.target.value)} disabled={busy}><option value="">New unsaved report</option>{reports.map(r=><option key={r.id} value={r.id}>{r.name} · v{r.version}</option>)}</select></label>
 <label className="field">Report name<input maxLength={120} required value={draft.name} onChange={e=>change({name:e.target.value})}/></label>
 <label className="field">Report from<select value={draft.entity} onChange={e=>{const selected=catalog.entities.find(x=>x.id===e.target.value);change({entity:selected.id,columns:selected.fields.slice(0,3).map(f=>f.key),filters:[],groupBy:[],aggregates:[],includeVoided:false});}}>{catalog.entities.map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select><span className="subtle">{entity?.description}</span></label>{['gifts','giftAllocations'].includes(draft.entity)&&<p className="table-note">Unfiltered gift values include future-dated records, fees and in-kind support. To report currently raised money, keep voided gifts excluded and filter by the cutoff date and monetary gift types. Saved date filters stay fixed when scheduled; they do not automatically move to today.</p>}
 <div className="field"><label>Find a field<input type="search" placeholder="Search field names" value={fieldQuery} onChange={e=>setFieldQuery(e.target.value)}/></label><span className="subtle">{draft.columns.length}/20 selected · money is stored in exact USD cents.</span><button type="button" className="btn btn-secondary" disabled={busy||!currentAccess} onClick={inspectFields} title="Review fields across all visible rows of this source, including optional fields beyond the initial metadata sample. Protected fields remain excluded; bounded inspection can be refused.">Review all source fields</button></div>
 <fieldset className="field field-wide"><legend>Source columns</legend><div className="form-grid">{fields.filter(f=>f.label.toLowerCase().includes(fieldQuery.toLowerCase())).map(f=><label key={f.key}><input type="checkbox" checked={draft.columns.includes(f.key)} disabled={!draft.columns.includes(f.key)&&draft.columns.length>=20} onChange={e=>change({columns:e.target.checked?[...draft.columns,f.key]:draft.columns.filter(k=>k!==f.key)})}/> {f.label} <span className="subtle">{f.type==='money'?'USD':f.type}</span></label>)}</div></fieldset>
 </div>
 <div className="section-title"><div><h3>Filters</h3><p>Every filter must match. Enter money in dollars, such as 125.50.</p></div><button type="button" className="btn btn-secondary" disabled={draft.filters.length>=12||!fields.length} onClick={()=>change({filters:[...draft.filters,{field:fields[0].key,op:'eq',value:''}]})}><Plus size={14}/>Add filter</button></div>
 {draft.filters.map((f,i)=><div className="toolbar" key={i}><label className="field">Field<select value={f.field} onChange={e=>filterChange(i,{field:e.target.value,op:'eq',value:''})}>{!field(f.field)&&<option value={f.field} disabled>{f.field} · field not reviewed</option>}{fields.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label><label className="field">Match<select value={f.op} onChange={e=>filterChange(i,{op:e.target.value})}>{['eq','ne','in',...(field(f.field)?.type==='text'?['contains','startsWith']:['gt','gte','lt','lte']),'empty','notEmpty'].map(op=><option key={op} value={op}>{ops[op]}</option>)}</select></label>{!['empty','notEmpty'].includes(f.op)&&<label className="field">Value{field(f.field)?.type==='money'?' · USD':!field(f.field)?' · field not reviewed':''}<input required type={f.op==='in'?'text':field(f.field)?.type==='date'?'date':field(f.field)?.type==='number'?'number':'text'} step="any" placeholder={f.op==='in'?'Separate values with commas':undefined} value={Array.isArray(f.value)?f.value.join(', '):f.value??''} onChange={e=>filterChange(i,{value:e.target.value})}/>{!field(f.field)&&<span className="subtle">Saved values retain their stored units. Review all source fields before editing or running this filter.</span>}</label>}<button type="button" className="btn btn-secondary" aria-label={`Remove filter ${i+1}`} onClick={()=>change({filters:draft.filters.filter((_,n)=>n!==i)})}><X size={14}/></button></div>)}
 <div className="section-title"><div><h3>Group and calculate</h3><p>Leave calculations empty for one row per source record. Totals use all matching records.</p></div><button type="button" className="btn btn-secondary" disabled={draft.aggregates.length>=8} onClick={()=>change({aggregates:[...draft.aggregates,{op:'count'}]})}><Plus size={14}/>Add calculation</button></div>
 <div className="form-grid">{[0,1,2].map(i=><label className="field" key={i}>Group {i+1}<select value={draft.groupBy[i]||''} onChange={e=>{const groups=[...draft.groupBy];groups[i]=e.target.value;change({groupBy:groups.filter(Boolean)});}}><option value="">No grouping</option>{groupable.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label>)}</div>
 {draft.aggregates.map((a,i)=><div className="toolbar" key={i}><label className="field">Calculation<select value={a.op} onChange={e=>{const op=e.target.value;change({aggregates:draft.aggregates.map((v,n)=>n!==i?v:op==='count'?{op}:{op,field:numeric[0]?.key})});}}>{['count','sum','min','max','avg'].map(op=><option key={op} value={op}>{op==='count'?'Count source rows':op==='avg'?'Average (non-money)':ops[op]||op[0].toUpperCase()+op.slice(1)}</option>)}</select></label>{a.op!=='count'&&<label className="field">Numeric field<select required value={a.field||''} onChange={e=>calculationChange(i,{field:e.target.value})}><option value="">Choose field</option>{numeric.filter(f=>a.op!=='avg'||f.type!=='money').map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label>}<button type="button" className="btn btn-secondary" aria-label={`Remove calculation ${i+1}`} onClick={()=>change({aggregates:draft.aggregates.filter((_,n)=>n!==i)})}><X size={14}/></button></div>)}
 {['gifts','giftAllocations'].includes(draft.entity)&&<label><input type="checkbox" checked={draft.includeVoided} onChange={e=>change({includeVoided:e.target.checked})}/> Include voided gifts</label>}
 <div className="form-actions"><span className="subtle">{saved?`Saved version ${saved.version}`:'Not saved'}{unreviewedFilters?' · Review source fields before running or saving.':''}{!editable?' · Your role can run reports; saving requires staff access.':''}</span><button type="button" className="btn btn-secondary" disabled={busy||!editable||unreviewedFilters} onClick={save}><Save size={15}/>{saved?'Save changes':'Save definition'}</button><button type="submit" className="btn btn-primary" disabled={busy||!draft.columns.length||unreviewedFilters}><Play size={15}/>{busy?'Working…':'Run report'}</button></div></form></section>}
 {result&&currentAccess&&<section className="panel"><div className="section-title"><div><h2>{result.definition.name}</h2><p>{result.matchedRows} matching source rows · {result.totalResultRows} result rows · {result.executedAt?new Date(result.executedAt).toLocaleString():''}</p></div><div className="toolbar"><button type="button" className="btn btn-secondary" disabled={busy||!result.sourceFingerprint} onClick={exportAll} title="Verify current source facts and download every result row, including full saved text. Exports over 8 MB are refused; narrow the report."><Download size={15}/>Export complete CSV</button><button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>download(`${result.definition.name.replace(/[^a-z0-9_-]/gi,'-')}.csv`,toCSV(result.columns.map(c=>c.label+(c.type==='money'?' (USD)':'')),result.rows.map(r=>r.map((v,i)=>v==null?'':result.columns[i].type==='money'?money(v):String(v)))),'text/csv;charset=utf-8')}><Download size={15}/>Export visible CSV</button></div></div><p className="table-note">{result.scope}</p><p className="table-note">Review the scope and filters above before using financial values for reconciliation. Calculations use all matching source rows. Visible CSV exports only the displayed page. Complete CSV rechecks the source and includes every result row with full saved text, up to 8 MB. Narrow the report if it exceeds the limit.{result.textTruncated?' Long text is shortened in this display and visible CSV.':''}</p>{result.page&&<div className="toolbar"><p className="subtle">{result.rows.length?`Rows ${result.page.offset+1}–${result.page.offset+result.rows.length} of ${result.totalResultRows}`:`0 of ${result.totalResultRows} rows`}</p><button type="button" className="btn btn-secondary" disabled={busy||result.page.offset===0} onClick={()=>page(pageOffsets[pageOffsets.length-2]??0,true)}>Previous page</button><button type="button" className="btn btn-secondary" disabled={busy||result.page.nextOffset===null} onClick={()=>page(result.page.nextOffset)}>Next page</button></div>}{renderTable(result.columns,result.rows,result.recordReferences)}<details><summary>Inspect source records · first {result.sourcePreview.rows.length} matches</summary><p className="table-note">Selected source columns help you check the filters and calculations. Open a record to inspect its complete saved values.</p>{renderTable(result.sourcePreview.columns,result.sourcePreview.rows,result.sourcePreview.recordReferences)}</details></section>}
 </>;
}
