import React,{useEffect,useState} from 'react';
import {Play,Save,Plus,Download,X} from 'lucide-react';
import {api as defaultApi} from '../api.js';
import {money,cents,dateLabel,download,toCSV} from '../lib.js';

const blank=()=>({name:'Untitled report',entity:'gifts',columns:['date','donorName','amount'],filters:[],groupBy:[],aggregates:[],includeVoided:false});
const ops={eq:'equals',ne:'does not equal',contains:'contains',startsWith:'starts with',gt:'greater than',gte:'at least',lt:'less than',lte:'at most',empty:'is empty',notEmpty:'is not empty',in:'is one of'};
const show=(value,column)=>value==null?'—':column.type==='money'?money(value):column.type==='date'&&Number.isFinite(Date.parse(value))?dateLabel(value):String(value);
const definition=report=>{const {id,version,createdAt,updatedAt,...body}=report;return body;};
export default function CustomReports({user,api=defaultApi,onOpen,notify,onDirty}){
 const [catalog,setCatalog]=useState(null),[reports,setReports]=useState([]),[draft,setDraft]=useState(blank),[saved,setSaved]=useState(null),[result,setResult]=useState(null),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[fieldQuery,setFieldQuery]=useState('');
 const editable=['admin','staff'].includes(user?.role);
 useEffect(()=>{let active=true;Promise.all([api('/custom-reports/catalog'),api('/custom-reports')]).then(([c,r])=>{if(active){setCatalog(c);setReports(r.reports);}}).catch(e=>active&&setError(e.message));return()=>{active=false;};},[api]);
 const entity=catalog?.entities.find(e=>e.id===draft.entity),fields=entity?.fields||[],field=key=>fields.find(f=>f.key===key),numeric=fields.filter(f=>f.aggregateable),groupable=fields.filter(f=>f.groupable);
 const displayDefinition=report=>{const body=definition(report),reportFields=catalog?.entities.find(e=>e.id===body.entity)?.fields||[];return {...body,filters:body.filters.map(f=>reportFields.find(x=>x.key===f.field)?.type==='money'&&f.value!==undefined?{...f,value:Array.isArray(f.value)?f.value.map(v=>(v/100).toFixed(2)).join(', '):(f.value/100).toFixed(2)}:f)};};
 const change=patch=>{setDraft(d=>({...d,...patch}));setResult(null);setStatus('');onDirty?.(true);};
 const load=id=>{const report=reports.find(r=>r.id===id);setSaved(report||null);setDraft(report?displayDefinition(report):blank());setResult(null);setError('');setStatus('');onDirty?.(false);};
 const payload=()=>({...draft,filters:draft.filters.map(f=>{if(['empty','notEmpty'].includes(f.op))return {field:f.field,op:f.op};if(f.value===undefined||String(f.value).trim()==='')throw new Error('Enter a value for each filter.');const type=field(f.field)?.type;const convert=value=>type==='money'?cents(value):type==='number'?Number(value):value;return {...f,value:f.op==='in'?String(f.value).split(',').map(v=>convert(v.trim())):convert(f.value)};})});
 const perform=async action=>{setBusy(true);setError('');setStatus('');try{await action();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const run=()=>perform(async()=>{const r=await api('/custom-reports/run',{method:'POST',body:payload()});setResult(r);setStatus('Report ran against current workspace records.');});
 const save=()=>perform(async()=>{const body=payload(),r=await api(saved?`/custom-reports/${saved.id}`:'/custom-reports',{method:saved?'PATCH':'POST',body:saved?{...body,version:saved.version}:body});setSaved(r.report);setReports(rs=>[r.report,...rs.filter(x=>x.id!==r.report.id)]);setDraft(displayDefinition(r.report));setStatus(`Definition saved · version ${r.report.version}. Rerun to see current records.`);onDirty?.(false);notify?.('Report definition saved');});
 const filterChange=(index,patch)=>change({filters:draft.filters.map((f,i)=>i===index?{...f,...patch}:f)});
 const calculationChange=(index,patch)=>change({aggregates:draft.aggregates.map((a,i)=>i===index?{...a,...patch}:a)});
 const renderTable=(columns,rows,references)=>rows.length?<div className="table-wrap"><table><thead><tr>{columns.map((c,i)=><th key={c.key||i} className={['money','number'].includes(c.type)?'money':''}>{c.label}{c.unit==='cents'?' · USD':''}</th>)}{onOpen&&<th>Source</th>}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((v,i)=><td key={i} className={['money','number'].includes(columns[i].type)?'money':''}>{show(v,columns[i])}</td>)}{onOpen&&<td>{references?.[index]?<button type="button" className="text-btn" onClick={()=>onOpen(references[index].collection,references[index].id)}>Open record</button>:'Grouped total'}</td>}</tr>)}</tbody></table></div>:<div className="empty-state">No records match these filters.</div>;
 return <><div className="page-header"><div><h1>Custom reports</h1><p>Choose saved fields, narrow the records, and calculate a result you can trace.</p></div><button className="btn btn-secondary" onClick={()=>load('')} disabled={busy}><Plus size={15}/>New report</button></div>
 {error&&<div className="error-banner" role="alert">{error}</div>}{status&&<p className="subtle" role="status">{status}</p>}
 {!catalog?<section className="panel"><p>Loading report fields…</p></section>:<section className="panel"><div className="section-title"><div><h2>Build a report</h2><p>Save the definition, then rerun it whenever the records change.</p></div></div>
 <form onSubmit={e=>{e.preventDefault();run();}}><div className="form-grid">
 <label className="field">Saved definition<select value={saved?.id||''} onChange={e=>load(e.target.value)} disabled={busy}><option value="">New unsaved report</option>{reports.map(r=><option key={r.id} value={r.id}>{r.name} · v{r.version}</option>)}</select></label>
 <label className="field">Report name<input maxLength={120} required value={draft.name} onChange={e=>change({name:e.target.value})}/></label>
 <label className="field">Report from<select value={draft.entity} onChange={e=>{const selected=catalog.entities.find(x=>x.id===e.target.value);change({entity:selected.id,columns:selected.fields.slice(0,3).map(f=>f.key),filters:[],groupBy:[],aggregates:[],includeVoided:false});}}>{catalog.entities.map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select><span className="subtle">{entity?.description}</span></label>{['gifts','giftAllocations'].includes(draft.entity)&&<p className="table-note">Unfiltered gift values include future-dated records, fees and in-kind support. To report currently raised money, keep voided gifts excluded and filter by the cutoff date and monetary gift types. Saved date filters stay fixed when scheduled; they do not automatically move to today.</p>}
 <label className="field">Find a field<input type="search" placeholder="Search field names" value={fieldQuery} onChange={e=>setFieldQuery(e.target.value)}/><span className="subtle">{draft.columns.length}/20 selected · money is stored in exact USD cents.</span></label>
 <fieldset className="field field-wide"><legend>Source columns</legend><div className="form-grid">{fields.filter(f=>f.label.toLowerCase().includes(fieldQuery.toLowerCase())).map(f=><label key={f.key}><input type="checkbox" checked={draft.columns.includes(f.key)} disabled={!draft.columns.includes(f.key)&&draft.columns.length>=20} onChange={e=>change({columns:e.target.checked?[...draft.columns,f.key]:draft.columns.filter(k=>k!==f.key)})}/> {f.label} <span className="subtle">{f.type==='money'?'USD':f.type}</span></label>)}</div></fieldset>
 </div>
 <div className="section-title"><div><h3>Filters</h3><p>Every filter must match. Enter money in dollars, such as 125.50.</p></div><button type="button" className="btn btn-secondary" disabled={draft.filters.length>=12||!fields.length} onClick={()=>change({filters:[...draft.filters,{field:fields[0].key,op:'eq',value:''}]})}><Plus size={14}/>Add filter</button></div>
 {draft.filters.map((f,i)=><div className="toolbar" key={i}><label className="field">Field<select value={f.field} onChange={e=>filterChange(i,{field:e.target.value,op:'eq',value:''})}>{fields.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label><label className="field">Match<select value={f.op} onChange={e=>filterChange(i,{op:e.target.value})}>{['eq','ne','in',...(field(f.field)?.type==='text'?['contains','startsWith']:['gt','gte','lt','lte']),'empty','notEmpty'].map(op=><option key={op} value={op}>{ops[op]}</option>)}</select></label>{!['empty','notEmpty'].includes(f.op)&&<label className="field">Value{field(f.field)?.type==='money'?' · USD':''}<input required type={f.op==='in'?'text':field(f.field)?.type==='date'?'date':field(f.field)?.type==='number'?'number':'text'} step="any" placeholder={f.op==='in'?'Separate values with commas':undefined} value={Array.isArray(f.value)?f.value.join(', '):f.value??''} onChange={e=>filterChange(i,{value:e.target.value})}/></label>}<button type="button" className="btn btn-secondary" aria-label={`Remove filter ${i+1}`} onClick={()=>change({filters:draft.filters.filter((_,n)=>n!==i)})}><X size={14}/></button></div>)}
 <div className="section-title"><div><h3>Group and calculate</h3><p>Leave calculations empty for one row per source record. Totals use all matching records.</p></div><button type="button" className="btn btn-secondary" disabled={draft.aggregates.length>=8} onClick={()=>change({aggregates:[...draft.aggregates,{op:'count'}]})}><Plus size={14}/>Add calculation</button></div>
 <div className="form-grid">{[0,1,2].map(i=><label className="field" key={i}>Group {i+1}<select value={draft.groupBy[i]||''} onChange={e=>{const groups=[...draft.groupBy];groups[i]=e.target.value;change({groupBy:groups.filter(Boolean)});}}><option value="">No grouping</option>{groupable.map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label>)}</div>
 {draft.aggregates.map((a,i)=><div className="toolbar" key={i}><label className="field">Calculation<select value={a.op} onChange={e=>{const op=e.target.value;change({aggregates:draft.aggregates.map((v,n)=>n!==i?v:op==='count'?{op}:{op,field:numeric[0]?.key})});}}>{['count','sum','min','max','avg'].map(op=><option key={op} value={op}>{op==='count'?'Count source rows':op==='avg'?'Average (non-money)':ops[op]||op[0].toUpperCase()+op.slice(1)}</option>)}</select></label>{a.op!=='count'&&<label className="field">Numeric field<select required value={a.field||''} onChange={e=>calculationChange(i,{field:e.target.value})}><option value="">Choose field</option>{numeric.filter(f=>a.op!=='avg'||f.type!=='money').map(f=><option key={f.key} value={f.key}>{f.label}</option>)}</select></label>}<button type="button" className="btn btn-secondary" aria-label={`Remove calculation ${i+1}`} onClick={()=>change({aggregates:draft.aggregates.filter((_,n)=>n!==i)})}><X size={14}/></button></div>)}
 {['gifts','giftAllocations'].includes(draft.entity)&&<label><input type="checkbox" checked={draft.includeVoided} onChange={e=>change({includeVoided:e.target.checked})}/> Include voided gifts</label>}
 <div className="form-actions"><span className="subtle">{saved?`Saved version ${saved.version}`:'Not saved'}{!editable?' · Your role can run reports; saving requires staff access.':''}</span><button type="button" className="btn btn-secondary" disabled={busy||!editable} onClick={save}><Save size={15}/>{saved?'Save changes':'Save definition'}</button><button type="submit" className="btn btn-primary" disabled={busy||!draft.columns.length}><Play size={15}/>{busy?'Working…':'Run report'}</button></div></form></section>}
 {result&&<section className="panel"><div className="section-title"><div><h2>{result.definition.name}</h2><p>{result.matchedRows} matching source rows · {result.totalResultRows} result rows · {result.executedAt?new Date(result.executedAt).toLocaleString():''}</p></div><button className="btn btn-secondary" onClick={()=>download(`${result.definition.name.replace(/[^a-z0-9_-]/gi,'-')}.csv`,toCSV(result.columns.map(c=>c.label+(c.type==='money'?' (USD)':'')),result.rows.map(r=>r.map((v,i)=>v==null?'':result.columns[i].type==='money'?money(v):String(v)))),'text/csv;charset=utf-8')}><Download size={15}/>Export visible CSV</button></div><p className="table-note">{result.scope}</p>{(result.truncated||result.textTruncated)&&<p className="scope-banner">The displayed export is bounded to 250 rows and available text space. Totals include all matching source rows.</p>}{renderTable(result.columns,result.rows,result.recordReferences)}<details><summary>Inspect source records · first {result.sourcePreview.rows.length} matches</summary><p className="table-note">Selected source columns help you check the filters and calculations. Open a record to inspect its complete saved values.</p>{renderTable(result.sourcePreview.columns,result.sourcePreview.rows,result.sourcePreview.recordReferences)}</details></section>}
 </>;
}
