import {MODULES} from '../schema';
import {useEffect,useRef,useState} from 'react';
import {FileText,Upload,Download,History,Archive,ArrowUpRight} from 'lucide-react';
import {dateLabel,download,nameOf} from '../lib';

const fresh={title:'',category:'Attachment',visibility:'Workspace',status:'Draft',evidenceDate:'',collection:'constituents',recordId:''};
export default function Documents({api,data,user,onOpen,notify,context=null,onDirty}){
 const [documents,setDocuments]=useState([]),[limits,setLimits]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[archived,setArchived]=useState(false),[editor,setEditor]=useState(null),[draft,setDraft]=useState({...fresh,...context}),[file,setFile]=useState(null),[history,setHistory]=useState(null),[archiveReason,setArchiveReason]=useState(''),[archiving,setArchiving]=useState(null);
 const field=useRef(null);const canWrite=['admin','staff'].includes(user.role);
 async function load(){const q=new URLSearchParams({...context,...(archived?{archived:'true'}:{})});const result=await api('/documents'+(q.size?'?'+q:''));setDocuments(result.documents);setLimits(result.limits);}
 useEffect(()=>{let live=true;setLoading(true);load().catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false;};},[api,context?.collection,context?.recordId,archived]);
 useEffect(()=>{if(editor)field.current?.focus();},[editor?.id]);
 function begin(document){setError('');setEditor(document||{id:null});setDraft(document?{title:document.title,category:document.category,visibility:document.visibility,status:document.status,evidenceDate:document.evidenceDate||'',collection:document.collection,recordId:document.recordId}:{...fresh,...context});setFile(null);onDirty?.(false);}
 function change(key,value){setDraft(p=>({...p,[key]:value,...(key==='collection'?{recordId:''}:{})}));onDirty?.(true);}
 async function save(e){e.preventDefault();setError('');if(!file){setError('Choose the file for this document revision.');return;}if(file.size>(limits?.maxBytes||1048576)){setError('File exceeds 1 MiB. Choose a smaller supported document.');return;}setBusy(true);try{const contentBase64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(new Error('File could not be read. Choose it again.'));reader.readAsDataURL(file);});const metadata={title:draft.title,category:draft.category,visibility:draft.visibility,status:draft.status,evidenceDate:draft.evidenceDate||null,filename:file.name,contentBase64};await api(editor.id?'/documents/'+editor.id+'/revisions':'/documents',{method:'POST',body:editor.id?{...metadata,version:editor.version}:{...metadata,collection:draft.collection,recordId:draft.recordId}});setEditor(null);setFile(null);onDirty?.(false);await load();notify?.('Document revision saved. Previous versions remain in history.');}catch(e){setError(e.message+' Check document history before retrying an uncertain upload.');}finally{setBusy(false);}}
 async function retrieve(document,revision){setBusy(true);setError('');try{const result=await api('/documents/'+document.id+'/revisions/'+revision+'/content');const bytes=Uint8Array.from(atob(result.contentBase64),c=>c.charCodeAt(0));download(result.filename,bytes,'application/octet-stream');notify?.('Document downloaded.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function archive(e){e.preventDefault();setBusy(true);setError('');try{await api('/documents/'+archiving.id+'/archive',{method:'POST',body:{version:archiving.version,reason:archiveReason}});setArchiving(null);setArchiveReason('');await load();notify?.('Document archived. Retained revisions remain available.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 const collections=Object.keys(data).filter(k=>!['evaluations','reportViews','volunteerTime','shiftReservations','retainedConstituents'].includes(k));
 return <section className="documents-workspace"><div className={context?'section-title':'page-header'}><div>{context?<h2>Documents and evidence</h2>:<h1>Documents</h1>}<p className="subtle">Keep files connected to their record, with retained revisions and access controls.</p></div>{canWrite&&<button type="button" className="btn btn-primary" disabled={busy} onClick={()=>begin()}><Upload size={16}/>Attach document</button>}</div>{error&&<p className="error-banner" role="alert">{error}</p>}
 {editor&&<section className="panel inline-editor"><h2>{editor.id?'Add document revision':'Attach a document'}</h2><form onSubmit={save}><fieldset disabled={busy}><div className="form-grid"><label className="field">Document title<input ref={field} required maxLength={250} value={draft.title} onChange={e=>change('title',e.target.value)}/></label><label className="field">Document category<select value={draft.category} onChange={e=>change('category',e.target.value)}>{['Attachment','Proposal','Agreement','Report'].map(v=><option key={v}>{v}</option>)}</select></label>{!context&&!editor.id&&<><label className="field">Record type<select value={draft.collection} onChange={e=>change('collection',e.target.value)}>{collections.map(c=><option key={c} value={c}>{MODULES[c]?.title||(c==='volunteerShifts'?'Volunteer shifts':c)}</option>)}</select></label><label className="field">Connected record<select required value={draft.recordId} onChange={e=>change('recordId',e.target.value)}><option value="">Choose the supporting record</option>{(data[draft.collection]||[]).map(r=><option key={r.id} value={r.id}>{r.name||r.title||r.subject||nameOf(data,'constituents',r.constituentId)+' · '+r.date}</option>)}</select></label></>}<label className="field">Document status<select value={draft.status} onChange={e=>change('status',e.target.value)}>{['Draft','Final','Submitted'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field">Actual evidence date<input type="date" required={draft.status==='Submitted'} max={new Date().toISOString().slice(0,10)} value={draft.evidenceDate} onChange={e=>change('evidenceDate',e.target.value)}/><small>Submission requires its actual date. Uploading does not submit a proposal.</small></label><label className="field">File<input type="file" required accept=".pdf,.png,.jpg,.jpeg,.txt,.csv" onChange={e=>{setFile(e.target.files[0]||null);onDirty?.(true);}}/><small>PDF, PNG, JPEG, UTF-8 TXT or CSV. Maximum 1 MiB. Files download; they are not executed or previewed.</small></label>{user.role==='admin'&&<label className="field">Document access<select value={draft.visibility} onChange={e=>change('visibility',e.target.value)}><option>Workspace</option><option>Administrators</option></select><small>Administrator-only files are hidden from staff and viewers.</small></label>}</div><div className="form-actions"><button className="btn btn-primary" type="submit">{busy?'Saving document…':'Save document revision'}</button><button className="btn btn-secondary" type="button" onClick={()=>{setEditor(null);setFile(null);onDirty?.(false);}}>Cancel upload</button></div></fieldset></form></section>}
 <div className="panel"><div className="section-title"><h2>{context?'Attached files':'Connected files'}</h2><label className="check-field"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Include archived</label></div>{loading?<p role="status">Loading document history…</p>:documents.length?<div className="table-wrap"><table aria-label="Connected document files"><thead><tr><th scope="col">Document</th>{!context&&<th scope="col">Connected record</th>}<th scope="col">Status</th><th scope="col">Latest revision</th><th scope="col">Actions</th></tr></thead><tbody>{documents.map(d=><tr key={d.id}><td><strong>{d.title}</strong><small className="cell-detail">{d.category} · {d.visibility}{d.archived?' · Archived':''}</small></td>{!context&&<td><button type="button" className="text-btn" onClick={()=>onOpen(d.collection,d.recordId)}>{nameOf(data,d.collection,d.recordId)}<ArrowUpRight size={14}/></button></td>}<td>{d.status}{d.evidenceDate&&<small className="cell-detail">{dateLabel(d.evidenceDate)}</small>}</td><td>{d.revisions[0]?.filename}<small className="cell-detail">Revision {d.revisions[0]?.revision} · {dateLabel(d.updatedAt)}</small></td><td><div className="row-buttons"><button type="button" className="icon-btn" disabled={busy} aria-label={'Download '+d.title} title="Download latest revision" onClick={()=>retrieve(d,d.revisions[0].revision)}><Download size={16}/></button><button type="button" className="icon-btn" disabled={busy} aria-label={'History of '+d.title} title="Inspect retained revisions" onClick={()=>setHistory(d)}><History size={16}/></button>{canWrite&&!d.archived&&<><button type="button" className="text-btn" disabled={busy} onClick={()=>begin(d)}>Revise</button><button type="button" className="icon-btn" disabled={busy} aria-label={'Archive '+d.title} title="Archive without deleting history" onClick={()=>{setArchiving(d);setArchiveReason('');}}><Archive size={16}/></button></>}</div></td></tr>)}</tbody></table></div>:<div className="empty-state"><FileText size={24}/><h3>No files attached</h3><p>Attach an agreement, proposal, report or supporting document to its record.</p></div>}<p className="table-note">Revisions are immutable through this application and retained for at least ten years from upload. Archiving hides a document from the active list; it does not dispose of it. Malware scanning and institutional disposal remain separate operational controls.</p></div>
 {history&&<section className="panel"><div className="section-title"><h2>Revision history · {history.title}</h2><button type="button" className="text-btn" onClick={()=>setHistory(null)}>Close history</button></div><div className="table-wrap"><table aria-label="Document revision history"><thead><tr><th scope="col">Revision</th><th scope="col">File and evidence</th><th scope="col">Date</th><th scope="col">Integrity</th><th scope="col">Download</th></tr></thead><tbody>{history.revisions.map(r=><tr key={r.revision}><td>{r.revision}</td><td>{r.filename}<small className="cell-detail">{r.metadata.status} · {r.metadata.category}{r.metadata.evidenceDate?' · '+r.metadata.evidenceDate:''}</small></td><td>{dateLabel(r.at)}</td><td title={r.sha256}>{r.sha256.slice(0,12)}…</td><td><button type="button" className="text-btn" disabled={busy} onClick={()=>retrieve(history,r.revision)}>Download revision {r.revision}</button></td></tr>)}</tbody></table></div></section>}
 {archiving&&<section className="panel"><h2>Archive {archiving.title}</h2><form onSubmit={archive}><label className="field">Reason for archiving<textarea required maxLength={1000} value={archiveReason} onChange={e=>setArchiveReason(e.target.value)}/></label><div className="form-actions"><button className="btn btn-secondary" type="submit" disabled={busy}>Archive and retain history</button><button className="text-btn" type="button" disabled={busy} onClick={()=>setArchiving(null)}>Cancel archive</button></div></form></section>}
 </section>;
}
