import React,{useEffect,useRef,useState} from 'react';
import {FileCheck,RefreshCw,ArrowUpRight} from 'lucide-react';
import {MODULES} from '../schema';
const initial={namespace:'',documentId:'',revisionId:'',sourceVisibility:'Administrators',originalDate:'',title:'',status:'Draft',visibility:'Administrators',evidenceDate:'',collection:'constituents',recordId:'',targetDocumentId:''};
export default function DocumentMigration({api,user,data,onDirty,onCommitted,onOpen}){
 const allowed=user?.role==='admin',[draft,setDraft]=useState(initial),[file,setFile]=useState(null),[documents,setDocuments]=useState([]),[collections,setCollections]=useState([]),[history,setHistory]=useState([]),[next,setNext]=useState(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[preview,setPreview]=useState(null),[confirmed,setConfirmed]=useState(false),[result,setResult]=useState(null),[dirty,setDirty]=useState(false);
 const alive=useRef(true),reads=useRef(0),fileField=useRef(null);
 useEffect(()=>{onDirty?.(dirty);},[dirty,onDirty]);
 useEffect(()=>{alive.current=true;if(allowed)load();else setLoading(false);return()=>{alive.current=false;reads.current++;};},[api,allowed]);
 async function load(after=null){const generation=++reads.current;setLoading(true);try{const [d,h]=await Promise.all([api('/documents'),api('/document-migration/history?limit=20'+(after?'&after='+encodeURIComponent(after):''))]);if(!alive.current||generation!==reads.current)return;setDocuments(d.documents);setCollections(d.collections);setHistory(old=>after?[...old,...h.reconciliations]:h.reconciliations);setNext(h.nextCursor);}catch(e){if(alive.current&&generation===reads.current){setHistory([]);setDocuments([]);setError(e.message);}}finally{if(alive.current&&generation===reads.current)setLoading(false);}}
 function invalidate(){setPreview(null);setConfirmed(false);setResult(null);setDirty(true);}
 function change(key,value){setDraft(old=>({...old,[key]:value,...(key==='collection'?{recordId:'',targetDocumentId:''}:{}),...(key==='recordId'?{targetDocumentId:''}:{}),...(key==='sourceVisibility'&&value==='Administrators'?{visibility:'Administrators'}:{})}));invalidate();}
 function target(value){const d=documents.find(d=>d.id===value);setDraft(old=>({...old,targetDocumentId:value,...(d?{title:d.title,status:d.status,evidenceDate:d.evidenceDate||'',visibility:old.sourceVisibility==='Administrators'?'Administrators':d.visibility}:{})}));invalidate();}
 async function chooseFile(event){const selected=event.target.files?.[0];invalidate();setFile(null);setError('');if(!selected)return;setBusy(true);try{if(!selected.size||selected.size>1048576)throw new Error('Choose one supported, nonempty file no larger than 1 MiB.');const bytes=new Uint8Array(await selected.arrayBuffer());const sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');let text='';for(let start=0;start<bytes.length;start+=8192)text+=String.fromCharCode(...bytes.subarray(start,start+8192));if(alive.current)setFile({filename:selected.name,contentBase64:btoa(text),sha256:sha,size:bytes.length});}catch(e){if(alive.current){setError(e.message);if(fileField.current)fileField.current.value='';}}finally{if(alive.current)setBusy(false);}}
 const record=(data?.[draft.collection]||[]).find(r=>r.id===draft.recordId),targetDocument=documents.find(d=>d.id===draft.targetDocumentId);
 const payload={source:{namespace:draft.namespace.trim(),documentId:draft.documentId.trim(),revisionId:draft.revisionId.trim(),visibility:draft.sourceVisibility,originalDate:draft.originalDate||null},document:{title:draft.title.trim(),category:'Agreement',status:draft.status,visibility:draft.visibility,evidenceDate:draft.evidenceDate||null,filename:file?.filename,contentBase64:file?.contentBase64,collection:draft.collection,recordId:draft.recordId,recordVersion:record?.version,...(draft.targetDocumentId?{targetDocumentId:draft.targetDocumentId,targetVersion:targetDocument?.version}:{})},sha256:file?.sha256,size:file?.size};
 const signature=JSON.stringify(payload),reviewCurrent=preview?.signature===signature;
 async function review(event){event.preventDefault();setBusy(true);setError('');setPreview(null);setConfirmed(false);setResult(null);try{if(!file||!record)throw new Error('Choose exact source bytes and an existing connected record.');const r=await api('/document-migration/preview',{method:'POST',body:payload});if(alive.current)setPreview({...r,signature});}catch(e){if(alive.current)setError(e.message);}finally{if(alive.current)setBusy(false);}}
 async function commit(){if(!preview?.valid||!confirmed||!reviewCurrent)return;setBusy(true);setError('');try{const r=await api('/document-migration/commit',{method:'POST',body:{...payload,proof:preview.proof}});if(!alive.current)return;setResult(r);setPreview(null);setConfirmed(false);setDirty(false);await load();await onCommitted?.();}catch(e){if(alive.current){setPreview(null);setConfirmed(false);setError(e.message+' Inspect conversion history before retrying an uncertain save, then preview the original source again.');await load();}}finally{if(alive.current)setBusy(false);}}
 if(!allowed)return <section className="panel"><h1>Contract conversion requires administrator access</h1><p>Only administrators can review source custody and import contract revisions.</p></section>;
 return <section className="document-conversion"><div className="page-header"><div><h1>Contract conversion</h1><p>Preserve original files, their source identity and the record they support.</p></div><button type="button" className="btn btn-secondary" disabled={busy||loading} onClick={()=>load()}><RefreshCw size={16}/>Refresh history</button></div>
 <p className="scope-banner">Import one reviewed Agreement revision at a time. Original source dates remain source metadata; Wimblo records the actual import time and administrator. Uploading does not execute, submit or complete a contract, grant or financial transaction.</p>
 {error&&<p className="error-banner" role="alert">{error}</p>}
 <section className="panel"><h2>1. Identify the original revision</h2><p>Keep source identifiers stable across retries. A changed original revision needs its own revision identifier.</p><form onSubmit={review}><fieldset disabled={busy||loading}><div className="form-grid">
 {[['namespace','Source system / namespace'],['documentId','Original contract identifier'],['revisionId','Original revision identifier']].map(([key,label])=><label className="field" key={key}>{label}<input required maxLength={100} value={draft[key]} onChange={e=>change(key,e.target.value)}/></label>)}
 <label className="field">Original source date<input type="date" value={draft.originalDate} onChange={e=>change('originalDate',e.target.value)}/><small>Optional documented calendar date; never an invented Wimblo upload or execution date.</small></label>
 <label className="field">Original source access<select value={draft.sourceVisibility} onChange={e=>change('sourceVisibility',e.target.value)}><option>Administrators</option><option>Workspace</option></select><small>Private original files cannot become workspace-visible during conversion.</small></label>
 <label className="field">Original file<input ref={fileField} required type="file" accept=".pdf,.png,.jpg,.jpeg,.txt,.csv" onChange={chooseFile}/><small>PDF, PNG, JPEG, UTF-8 TXT or CSV; maximum 1 MiB. Office files and archives are not converted.</small></label></div>
 {file&&<p className="conversion-integrity"><strong>{file.filename}</strong> · {file.size.toLocaleString()} exact bytes<small>SHA-256 {file.sha256}</small></p>}
 <h2>2. Connect and classify</h2><div className="form-grid"><label className="field">Record type<select value={draft.collection} onChange={e=>change('collection',e.target.value)}>{collections.map(c=><option key={c} value={c}>{MODULES[c]?.title||(c==='volunteerShifts'?'Volunteer shifts':c)}</option>)}</select></label>
 <label className="field">Connected record<select required value={draft.recordId} onChange={e=>change('recordId',e.target.value)}><option value="">Choose an existing record</option>{(data?.[draft.collection]||[]).map(r=><option key={r.id} value={r.id}>{r.name||r.title||r.subject||r.id} · v{r.version}</option>)}</select></label>
 <label className="field">Saved document destination<select value={draft.targetDocumentId} onChange={e=>target(e.target.value)}><option value="">Create a new connected document</option>{documents.filter(d=>d.collection===draft.collection&&d.recordId===draft.recordId&&!d.archived).map(d=><option key={d.id} value={d.id}>{d.title} · v{d.version}</option>)}</select><small>For later original revisions, select the same linked document. Never overwrite retained bytes.</small></label>
 <label className="field">Contract title<input required maxLength={250} value={draft.title} onChange={e=>change('title',e.target.value)}/></label>
 <label className="field">Recorded document status<select value={draft.status} onChange={e=>change('status',e.target.value)}>{['Draft','Final','Submitted'].map(v=><option key={v}>{v}</option>)}</select></label>
 <label className="field">Actual submission / evidence date<input required={draft.status==='Submitted'} type="date" max={new Date().toISOString().slice(0,10)} value={draft.evidenceDate} onChange={e=>change('evidenceDate',e.target.value)}/><small>Submitted status requires the actual supported date; importing does not submit anything.</small></label>
 <label className="field">Wimblo document access<select value={draft.visibility} onChange={e=>change('visibility',e.target.value)}><option>Administrators</option><option disabled={draft.sourceVisibility==='Administrators'}>Workspace</option></select></label></div>
 <div className="form-actions"><span className="subtle">{record?'Linked record v'+record.version:'Select the source record before review.'}</span><button type="submit" className="btn btn-primary" disabled={!file||!record||busy}>Preview exact revision<FileCheck size={16}/></button></div></fieldset></form></section>
 {preview&&<section className="panel"><h2>3. Review before saving</h2><p>{preview.operation} · {preview.metadata?.visibility} access · {preview.file?.size.toLocaleString()} exact bytes</p><p className="subtle">One source revision; {preview.reconciliation?.nativeRevisions} new saved revisions and {preview.reconciliation?.nativeBytes.toLocaleString()} new saved bytes expected. Replay verifies retained evidence and creates no duplicate revision.</p>{!reviewCurrent&&<p className="error-banner" role="alert">The linked record or selected document changed. Preview the current sources again before saving.</p>}<label className="check-field"><input type="checkbox" disabled={busy||!reviewCurrent} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the original identity, exact bytes, source date, destination and privacy.</label><div className="form-actions"><button type="button" className="btn btn-primary" disabled={busy||!confirmed||!reviewCurrent||!preview.valid} onClick={commit}>{busy?'Saving verified revision…':'Save reviewed revision'}</button></div></section>}
 {result&&<section className="panel" role="status"><h2>{result.replayed?'Original revision verified; no duplicate created':'Verified contract revision saved'}</h2><p>Document {result.document?.title} · v{result.document?.version}. Inspect retained source reconciliation below.</p><button type="button" className="btn btn-secondary" onClick={()=>onOpen?.(result.document.collection,result.document.recordId)}>Open connected record<ArrowUpRight size={16}/></button></section>}
 <section className="panel"><h2>Retained conversion history</h2><p>Successful exact reconciliations are evidence of this supported slice, not full source custody or buyer acceptance.</p>{loading?<p role="status">Loading conversion history…</p>:history.length?<div className="conversion-history">{history.map(r=><article key={r.id}><strong>{r.requestedDocumentVersion?'Appended original revision':'Created connected document'}</strong><p>{r.source?.namespace||r.namespace} · {r.source?.documentId||r.sourceDocumentId} · {r.source?.revisionId||r.sourceRevisionId}</p><p className="subtle">{r.source?.originalDate?'Original source date '+r.source.originalDate+' · ':''}Imported {r.at||r.createdAt} · {r.reconciliation?.sourceBytes??'—'} source bytes · {r.reconciliation?.nativeBytes??'—'} saved bytes verified</p></article>)}</div>:<p className="empty-state">No successful contract conversions yet. Start with one original file and its existing connected record.</p>}{next&&<button type="button" className="btn btn-secondary" disabled={busy||loading} onClick={()=>load(next)}>Load earlier conversions</button>}</section></section>;
}
