import {useEffect,useState} from 'react';
import {Ticket,Armchair,Gavel,Handshake,Plus,ArrowUpRight} from 'lucide-react';
import {cents,money,nameOf,today,dateLabel} from '../lib';

const amountText=value=>`${Math.floor(value/100)}.${String(value%100).padStart(2,'0')}`;
export default function EventOperations({api,user,data,onCommitted,notify,onOpen,onDirty}){
 const [eventId,setEventId]=useState(data.events?.[0]?.id||''),[asOf,setAsOf]=useState(today()),[state,setState]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editor,setEditor]=useState(null),[draft,setDraft]=useState({}),[dirty,setDirty]=useState(false);
 const canWrite=['admin','staff'].includes(user.role),people=(data.constituents||[]).filter(c=>!c.mergedInto),organizations=people.filter(c=>['Business','Foundation','Community partner'].includes(c.type));
 async function fetchState(){if(!eventId)return null;return api('/event-operations?'+new URLSearchParams({eventId,asOf}));}
 async function load(){setState(await fetchState());}
 async function reload(){setBusy(true);setError('');try{await load();await onCommitted?.();}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{let live=true;setLoading(true);fetchState().then(r=>live&&setState(r)).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false;};},[api,eventId,asOf]);
 const event=state?.events?.[0],attendees=(event?.registrations||[]).map(r=>people.find(c=>c.id===r.constituentId)).filter(Boolean),ticketAttendees=(event?.registrations||[]).filter(r=>!r.checkedIn&&!state.tickets.some(t=>t.constituentId===r.constituentId&&t.status==='Issued')).map(r=>people.find(c=>c.id===r.constituentId)).filter(Boolean);
 function cancelChanges(){if(dirty&&!window.confirm('Discard these unsaved event operation changes?'))return;setEditor(null);setDraft({});setDirty(false);onDirty?.(false);}
 function change(key,value){setDirty(true);setDraft(p=>({...p,[key]:value}));onDirty?.(true);}
 function begin(type,record=null){setError('');setEditor({type,record});setDraft(type==='table'?{name:record?.name||'',seats:record?.seats||Math.min(8,event?.capacity||8)}:type==='assign'?{constituentId:'',seatNumber:''}:type==='ticket'?{constituentId:''}:type==='sponsorship'?{name:record?.name||'',sponsorId:record?.sponsorId||'',amount:record?amountText(record.amount):'',benefits:(record?.benefits||[]).map(b=>b.name).join('\n')}:type==='auction'?{name:record?.name||'',startingBid:record?amountText(record.startingBid):'',minIncrement:record?amountText(record.minIncrement):'',description:record?.description||''}:type==='bid'?{bidderId:'',amount:amountText(record.bids[0]?record.bids[0].amount+record.minIncrement:record.startingBid)}:type==='close'?{confirmed:false}:type==='payment'?{giftId:'',revenueCase:record.ownerType==='sponsorship'?'Sponsorship':'Fee payment'}:{reason:''});setDirty(false);onDirty?.(false);}
 async function perform(path,body,message,method='POST'){setBusy(true);setError('');let saved=false;try{await api('/event-operations'+path,{method,body});saved=true;setEditor(null);setDraft({});setDirty(false);onDirty?.(false);await load();await onCommitted?.();notify?.(message);}catch(e){setError(saved?'Saved, but the view could not refresh. Reload event operations and check its retained history.':e.message+' Reload event operations before retrying an uncertain change.');}finally{setBusy(false);}}
 async function submit(e){e.preventDefault();if(!event||!editor)return;const {type,record}=editor;try{
  if(type==='table')return await perform(record?'/seating/'+record.id:`/events/${event.id}/seating`,{name:draft.name,seats:Number(draft.seats),...(record?{version:record.version}:{eventVersion:event.version})},'Seating inventory saved.',record?'PATCH':'POST');
  if(type==='assign')return await perform('/seating/'+record.id+'/assign',{tableVersion:record.version,eventVersion:event.version,constituentId:draft.constituentId,seatNumber:Number(draft.seatNumber)},'Seat assigned to the registered attendee.');
  if(type==='ticket')return await perform(`/events/${event.id}/tickets`,{eventVersion:event.version,constituentId:draft.constituentId},'Ticket issued. No payment was collected.');
  if(type==='sponsorship'){const checklist=draft.benefits.split('\n').map(n=>n.trim()).filter(Boolean).map(name=>({name,completed:record?.benefits.find(b=>b.name===name)?.completed||false}));return await perform('/sponsorships'+(record?'/'+record.id:''),{name:draft.name,sponsorId:draft.sponsorId,amount:cents(draft.amount),benefits:checklist,...(record?{version:record.version}:{eventId:event.id,eventVersion:event.version})},'Sponsorship agreement saved as a commitment.',record?'PATCH':'POST');}
  if(type==='auction')return await perform('/auction-items'+(record?'/'+record.id:''),{name:draft.name,startingBid:cents(draft.startingBid),minIncrement:cents(draft.minIncrement),description:draft.description,...(record?{version:record.version}:{eventId:event.id,eventVersion:event.version})},'Auction inventory saved.',record?'PATCH':'POST');
  if(type==='bid')return await perform('/auction-items/'+record.id+'/bids',{version:record.version,bidderId:draft.bidderId,amount:cents(draft.amount)},'Staff-entered bid retained in auction history.');
  if(type==='close')return await perform('/auction-items/'+record.id+'/close',{version:record.version,winningBidId:record.bids[0].id,confirmed:draft.confirmed},'Winning bid confirmed. Payment remains separate.');
  if(type==='payment'){const gift=data.gifts.find(g=>g.id===draft.giftId);if(!gift)throw new Error('Choose the existing recorded payment.');return await perform('/payments',{ownerType:record.ownerType,ownerId:record.id,version:record.version,giftId:gift.id,giftVersion:gift.version,revenueCase:draft.revenueCase},'Existing receipt linked. No additional gift or payment was created.');}
  return await perform('/'+(type==='cancel-ticket'?'tickets':'seat-assignments')+'/'+record.id+'/cancel',{version:record.version,reason:draft.reason},'Cancellation retained with its reason.');
 }catch(e){setError(e.message);}}
 const label=id=>nameOf(data,'constituents',id),blocked=busy||Boolean(editor),linkedGiftIds=new Set([...(state?.tickets||[]),...(state?.sponsorships||[]),...(state?.auctionItems||[])].flatMap(r=>r.payments.map(p=>p.giftId)));
 const paymentOwner=editor?.type==='payment'?editor.record:null,paymentDonor=paymentOwner?(paymentOwner.ownerType==='ticket'?paymentOwner.constituentId:paymentOwner.ownerType==='sponsorship'?paymentOwner.sponsorId:paymentOwner.winner?.bidderId):null;
 const paymentMaximum=paymentOwner?(paymentOwner.ownerType==='ticket'?paymentOwner.price:paymentOwner.ownerType==='sponsorship'?paymentOwner.amount-paymentOwner.payments.filter(p=>p.status==='Posted').reduce((n,p)=>n+p.amount,0):paymentOwner.winner.amount):0;
 const candidates=paymentOwner?(data.gifts||[]).filter(g=>g.status==='Posted'&&g.constituentId===paymentDonor&&g.type===draft.revenueCase&&g.giftKind==='One-time'&&!g.pledgeId&&!g.grantId&&!linkedGiftIds.has(g.id)&&(paymentOwner.ownerType==='sponsorship'?g.amount<=paymentMaximum:g.amount===paymentMaximum)):[];
 function receiptHistory(record){return record.payments.length?<details><summary>{record.payments.length} retained receipt link{record.payments.length===1?'':'s'}</summary>{record.payments.map(p=><p key={p.id}><button className="text-btn" disabled={blocked} onClick={()=>onOpen?.('gifts',p.giftId)}>Open recorded receipt<ArrowUpRight size={14}/></button> · {money(p.amount)} · {p.type} · {p.status}{p.futureDated?' · Outside the as-of period':''}</p>)}</details>:<small className="cell-detail">No recorded receipt linked</small>;}
 return <section><div className="page-header"><div><h1>Event operations</h1><p className="subtle">Offline seating, ticket history, sponsorship commitments and staff-entered auctions.</p></div></div>{error&&<p className="error-banner" role="alert">{error}</p>}<div className="toolbar"><label className="field">Event<select value={eventId} disabled={blocked} onChange={e=>{setEventId(e.target.value);setState(null);setError('');}}><option value="">Choose an event</option>{(data.events||[]).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label className="field">Received balances as of<input type="date" max={today()} required value={asOf} disabled={blocked} onChange={e=>setAsOf(e.target.value||today())}/></label><button className="btn btn-secondary" disabled={blocked||!eventId} onClick={reload}>Reload event operations</button>{event&&<button className="text-btn" disabled={blocked} onClick={()=>onOpen?.('events',event.id)}>Open event and registrations<ArrowUpRight size={14}/></button>}</div>
 {loading?<p role="status">Loading event operations…</p>:!event?<div className="empty-state"><Ticket size={24}/><h2>Choose the event to manage</h2><p>Register attendees on the event before assigning seats or issuing tickets.</p></div>:<><p className="scope-banner">{event.registrations.length}/{event.capacity} registered · {money(event.ticketPrice)} recorded ticket price · Commitments are separate from received revenue. Payments link to existing gifts; online checkout is not connected.</p>
 {editor&&<section className="panel inline-editor"><h2>{editor.type==='table'?'Seating inventory':editor.type==='assign'?'Assign a registered attendee':editor.type==='ticket'?'Issue an offline ticket':editor.type==='sponsorship'?'Sponsorship agreement':editor.type==='auction'?'Auction inventory':editor.type==='bid'?'Record an auction bid':editor.type==='close'?'Confirm the auction winner':editor.type==='payment'?'Link an existing recorded payment':'Retain a cancellation'}</h2><form onSubmit={submit}><fieldset disabled={busy}><div className="form-grid">
 {editor.type==='table'&&<><label className="field">Table name<input autoFocus required maxLength={250} value={draft.name} onChange={e=>change('name',e.target.value)}/></label><label className="field">Seats<input type="number" required min={1} max={Math.min(10000,event.capacity)} step={1} value={draft.seats} onChange={e=>change('seats',e.target.value)}/></label></>}
 {['assign','ticket'].includes(editor.type)&&<label className="field">Registered attendee<select autoFocus required value={draft.constituentId} onChange={e=>change('constituentId',e.target.value)}><option value="">Choose a registered attendee</option>{(editor.type==='ticket'?ticketAttendees:attendees).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{editor.type==='ticket'&&!ticketAttendees.length&&<small>No eligible attendees. Cancel this form, then open the event and registrations to register an attendee who has not checked in and has no active ticket.</small>}</label>}
 {editor.type==='assign'&&<label className="field">Seat number<input type="number" required min={1} max={editor.record.seats} step={1} value={draft.seatNumber} onChange={e=>change('seatNumber',e.target.value)}/><small>{editor.record.name} · occupied seats: {(state.seatAssignments||[]).filter(a=>a.tableId===editor.record.id&&a.status==='Assigned').map(a=>a.seatNumber).join(', ')||'none'}</small></label>}
 {editor.type==='sponsorship'&&<><label className="field">Agreement name<input autoFocus required maxLength={250} value={draft.name} onChange={e=>change('name',e.target.value)}/></label><label className="field">Sponsor organization<select required disabled={Boolean(editor.record?.payments.length)} value={draft.sponsorId} onChange={e=>change('sponsorId',e.target.value)}><option value="">Choose an organization</option>{organizations.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field">Commitment amount · USD<input required inputMode="decimal" disabled={Boolean(editor.record?.payments.length)} value={draft.amount} onChange={e=>change('amount',e.target.value)}/><small>The agreement is a commitment. Linked posted receipts establish received revenue.</small></label><label className="field">Benefits checklist<textarea maxLength={8000} value={draft.benefits} onChange={e=>change('benefits',e.target.value)}/><small>One benefit per line. Existing completion states remain associated with the same benefit name.</small></label></>}
 {editor.type==='auction'&&<><label className="field">Item name<input autoFocus required maxLength={250} value={draft.name} onChange={e=>change('name',e.target.value)}/></label><label className="field">Starting bid · USD<input required inputMode="decimal" value={draft.startingBid} onChange={e=>change('startingBid',e.target.value)}/></label><label className="field">Minimum increment · USD<input required inputMode="decimal" value={draft.minIncrement} onChange={e=>change('minIncrement',e.target.value)}/></label><label className="field">Item description<textarea maxLength={8000} value={draft.description} onChange={e=>change('description',e.target.value)}/></label></>}
 {editor.type==='bid'&&<><label className="field">Bidder<select autoFocus required value={draft.bidderId} onChange={e=>change('bidderId',e.target.value)}><option value="">Choose the bidder</option>{people.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field">Staff-entered bid · USD<input required inputMode="decimal" value={draft.amount} onChange={e=>change('amount',e.target.value)}/><small>Minimum next bid: {money(editor.record.bids[0]?editor.record.bids[0].amount+editor.record.minIncrement:editor.record.startingBid)}.</small></label></>}
 {editor.type==='close'&&<div className="field field-wide"><p>Current highest bid: <strong>{label(editor.record.bids[0].bidderId)} · {money(editor.record.bids[0].amount)}</strong>. Closing confirms the winning commitment and locks further bids.</p><label className="check-field"><input type="checkbox" required checked={draft.confirmed} onChange={e=>change('confirmed',e.target.checked)}/>I reviewed and confirm this current highest bid as the winning bid.</label></div>}
 {editor.type==='payment'&&<><div className="field field-wide"><p>Recorded payer: <strong>{label(paymentDonor)}</strong>. {paymentOwner.ownerType==='sponsorship'?'Remaining capacity for actual receipt links':'Exact required recorded amount'}: <strong>{money(paymentMaximum)}</strong>.</p><small>Create and verify the payment in Gifts first. This action links that existing record; it does not collect money or determine tax treatment.</small></div><label className="field">Actual recorded revenue case<select value={draft.revenueCase} onChange={e=>change('revenueCase',e.target.value)}>{(paymentOwner.ownerType==='sponsorship'?['Sponsorship']:['Fee payment','Cash']).map(v=><option key={v}>{v}</option>)}</select></label><label className="field">Existing posted receipt<select required value={draft.giftId} onChange={e=>change('giftId',e.target.value)}><option value="">Choose the matching receipt</option>{candidates.map(g=><option key={g.id} value={g.id}>{dateLabel(g.date)} · {money(g.amount)} · {g.externalRef||g.method}</option>)}</select><small>Only matching one-time receipts without another commitment appear. A receipt can link once across event operations. Future-dated records remain outside received balances until their date.</small></label></>}
 {editor.type.startsWith('cancel-')&&<label className="field field-wide">Cancellation reason<textarea autoFocus required maxLength={2000} value={draft.reason} onChange={e=>change('reason',e.target.value)}/><small>Issue and assignment histories remain retained. Checked-in history requires a separate attendance correction policy.</small></label>}
 </div><div className="form-actions"><button className="btn btn-primary" type="submit" disabled={(editor.type==='close'&&!draft.confirmed)||(editor.type==='ticket'&&!ticketAttendees.length)}>{busy?'Saving…':editor.type==='close'?'Confirm and close auction':editor.type==='payment'?'Link the verified receipt':'Save event operation'}</button><button className="btn btn-secondary" type="button" onClick={()=>{setEditor(null);setDraft({});setDirty(false);onDirty?.(false);}}>Cancel changes</button></div></fieldset></form></section>}
 <section className="panel"><div className="section-title"><h2><Armchair size={18}/>Seating</h2>{canWrite&&<button className="btn btn-secondary" disabled={blocked} onClick={()=>begin('table')}><Plus size={14}/>Create table</button>}</div><div className="table-wrap"><table aria-label="Event seating inventory"><thead><tr><th>Table</th><th>Seats</th><th>Assigned</th>{canWrite&&<th>Manage</th>}</tr></thead><tbody>{state.seating.map(t=><tr key={t.id}><td>{t.name}</td><td>{t.seats}</td><td>{state.seatAssignments.filter(a=>a.tableId===t.id&&a.status==='Assigned').length}</td>{canWrite&&<td><div className="row-buttons"><button className="text-btn" disabled={blocked} onClick={()=>begin('assign',t)}>Assign attendee</button>{!state.seatAssignments.some(a=>a.tableId===t.id)&&<button className="text-btn" disabled={blocked} onClick={()=>begin('table',t)}>Edit unused inventory</button>}</div></td>}</tr>)}</tbody></table></div>{!state.seating.length&&<p>No seating inventory entered.</p>}{state.seatAssignments.length>0&&<details><summary>Retained seating assignments · {state.seatAssignments.length}</summary><div className="table-wrap"><table aria-label="Retained seating assignment history"><thead><tr><th>Attendee</th><th>Table and seat</th><th>Status</th>{canWrite&&<th>Action</th>}</tr></thead><tbody>{state.seatAssignments.map(a=><tr key={a.id}><td><button className="text-btn" disabled={blocked} onClick={()=>onOpen?.('constituents',a.constituentId)}>{label(a.constituentId)}</button></td><td>{state.seating.find(t=>t.id===a.tableId)?.name} · {a.seatNumber}</td><td>{a.status}{a.cancelReason&&<small className="cell-detail">{a.cancelReason}</small>}</td>{canWrite&&<td>{a.status==='Assigned'&&<button className="text-btn" disabled={blocked} onClick={()=>begin('cancel-seat',a)}>Cancel assignment</button>}</td>}</tr>)}</tbody></table></div></details>}</section>
 <section className="panel"><div className="section-title"><h2><Ticket size={18}/>Tickets and check-in</h2>{canWrite&&<button className="btn btn-secondary" disabled={blocked} onClick={()=>begin('ticket')}><Plus size={14}/>Issue ticket</button>}</div><div className="table-wrap"><table aria-label="Offline tickets and check-in history"><thead><tr><th>Attendee</th><th>Ticket state</th><th>Recorded price</th><th>Received / balance</th>{canWrite&&<th>Manage</th>}</tr></thead><tbody>{state.tickets.map(t=><tr key={t.id}><td>{label(t.constituentId)}<small className="cell-detail">Issued {dateLabel(t.issuedAt)}</small></td><td>{t.status}{t.checkedIn&&<small className="cell-detail">Checked in {dateLabel(t.checkedInAt)}</small>}{t.cancelReason&&<small className="cell-detail">{t.cancelReason}</small>}</td><td>{money(t.price)}</td><td>{money(t.received)} / {money(t.balance)}{receiptHistory(t)}</td>{canWrite&&<td>{t.status==='Issued'&&<div className="row-buttons">{!t.checkedIn&&<button className="text-btn" disabled={blocked} onClick={()=>perform('/tickets/'+t.id+'/checkin',{version:t.version,eventVersion:event.version},'Ticket check-in retained.')}>Check in ticket</button>}{t.price>0&&!t.payments.some(p=>p.status==='Posted')&&<button className="text-btn" disabled={blocked} onClick={()=>begin('payment',{...t,ownerType:'ticket'})}>Link receipt</button>}{!t.checkedIn&&!t.payments.some(p=>p.status==='Posted')&&<button className="text-btn" disabled={blocked} onClick={()=>begin('cancel-ticket',t)}>Cancel ticket</button>}</div>}</td>}</tr>)}</tbody></table></div>{!state.tickets.length&&<p>No ticket issues recorded. Registered attendees remain managed on the event.</p>}</section>
 <section className="panel"><div className="section-title"><h2><Handshake size={18}/>Sponsorship agreements</h2>{canWrite&&<button className="btn btn-secondary" disabled={blocked} onClick={()=>begin('sponsorship')}><Plus size={14}/>Record agreement</button>}</div>{state.sponsorships.map(s=><div className="inline-editor" key={s.id}><div className="section-title"><h3>{s.name} · {label(s.sponsorId)}</h3>{canWrite&&<div className="row-buttons"><button className="text-btn" disabled={blocked} onClick={()=>begin('sponsorship',s)}>Maintain agreement</button>{s.payments.filter(p=>p.status==='Posted').reduce((n,p)=>n+p.amount,0)<s.amount&&<button className="text-btn" disabled={blocked} onClick={()=>begin('payment',{...s,ownerType:'sponsorship'})}>Link actual receipt</button>}</div>}</div><p>Commitment {money(s.amount)} · received {money(s.received)} · balance {money(s.balance)}</p>{s.benefits.map((b,i)=><label className="check-field" key={b.name}><input type="checkbox" checked={b.completed} disabled={!canWrite||blocked} onChange={e=>perform('/sponsorships/'+s.id,{version:s.version,benefits:s.benefits.map((v,n)=>n===i?{...v,completed:e.target.checked}:v)},'Staff benefit completion recorded.','PATCH')}/>{b.name}</label>)}{receiptHistory(s)}</div>)}{!state.sponsorships.length&&<p>No sponsorship agreements recorded.</p>}</section>
 <section className="panel"><div className="section-title"><h2><Gavel size={18}/>Staff-entered auctions</h2>{canWrite&&<button className="btn btn-secondary" disabled={blocked} onClick={()=>begin('auction')}><Plus size={14}/>Create auction item</button>}</div>{state.auctionItems.map(item=><div className="inline-editor" key={item.id}><div className="section-title"><h3>{item.name} · {item.status}</h3>{canWrite&&<div className="row-buttons">{item.status==='Open'&&<><button className="text-btn" disabled={blocked} onClick={()=>begin('bid',item)}>Record bid</button>{item.bids.length?<button className="text-btn" disabled={blocked} onClick={()=>begin('close',item)}>Review winner</button>:<button className="text-btn" disabled={blocked} onClick={()=>begin('auction',item)}>Edit unused item</button>}</>}{item.status==='Closed'&&!item.payments.some(p=>p.status==='Posted')&&<button className="text-btn" disabled={blocked} onClick={()=>begin('payment',{...item,ownerType:'auction'})}>Link winner’s recorded payment</button>}</div>}</div><p>{item.description}</p><p>Starting bid {money(item.startingBid)} · increment {money(item.minIncrement)}{item.bids[0]?' · current highest '+money(item.bids[0].amount):''}</p>{item.winner&&<p>Confirmed winner: {label(item.winner.bidderId)} · {money(item.winner.amount)} commitment · received {money(item.received)} · balance {money(item.balance)}</p>}{item.bids.length>0&&<details><summary>Immutable bid history · {item.bids.length}</summary><div className="table-wrap"><table aria-label={'Bid history for '+item.name}><thead><tr><th>Bidder</th><th>Recorded bid</th><th>Entered</th></tr></thead><tbody>{item.bids.map(b=><tr key={b.id}><td><button className="text-btn" disabled={blocked} onClick={()=>onOpen?.('constituents',b.bidderId)}>{label(b.bidderId)}</button></td><td>{money(b.amount)}</td><td>{dateLabel(b.at)}</td></tr>)}</tbody></table></div></details>}{receiptHistory(item)}</div>)}{!state.auctionItems.length&&<p>No auction inventory or bids entered.</p>}</section>
 <p className="table-note">Retained tickets, seating, bids and receipt links protect connected identities and event history. Cancel supported operations with a reason; completed attendance needs a separate correction policy. Agreements and auction commitments do not add gifts or received income.</p>
 </>}
 </section>;
}
