import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Download,ArrowUpRight,BarChart3} from 'lucide-react';
import {computeFundraisingAnalytics} from '../fundraisingAnalytics.js';
import {today,money,dateLabel,download,toCSV} from '../lib.js';

const percent=value=>value==null?'Unavailable':`${value.toLocaleString('en-US',{maximumFractionDigits:1})}%`;
export default function FundraisingAnalytics({data,settings,onOpen,onNavigate,notify}){
 const [asOf,setAsOf]=useState(today),[year,setYear]=useState(''),[inspection,setInspection]=useState(null);
 const evidenceRef=useRef(null);
 useEffect(()=>{if(inspection&&evidenceRef.current){evidenceRef.current.focus({preventScroll:true});evidenceRef.current.scrollIntoView({block:'start'});}},[inspection]);
 const startMonth=settings?.fiscalStartMonth||7;
 const calculation=useMemo(()=>{try{const base=computeFundraisingAnalytics(data,{fiscalStartMonth:startMonth,asOf});return {result:year&&base.years.includes(year)?computeFundraisingAnalytics(data,{fiscalStartMonth:startMonth,asOf,schoolYear:year}):base};}catch(error){return {error:error.message};}},[data,startMonth,asOf,year]);
 const r=calculation.result,source=inspection&&r?r.sourceGifts.filter(g=>inspection.giftIds.includes(g.id)):[];
 const exportSources=(rows,label)=>{download(`fundraising-${label}-${asOf}.csv`,toCSV(['Period','School year','Original gift date','Donor','Donor ID','Campaign','Gift ID','Amount (USD cents)','Revenue type'],rows.map(g=>[g.period,g.schoolYear,g.date,g.donorName,g.donorId,g.campaignName,g.id,g.amountCents,g.type])),'text/csv;charset=utf-8');notify?.('Source CSV prepared from saved gift records.');};
 const inspect=(label,values)=>setInspection({label,giftIds:[...new Set(values.giftIds)],donorIds:values.donorIds||[]});
 const cohortInspect=cohort=>inspect(cohort.label,{giftIds:[...cohort.current.giftIds,...cohort.prior.giftIds,...cohort.historyGiftIds],donorIds:cohort.donorIds});
 const scale=r?Math.max(...r.campaignPerformance.flatMap(c=>[c.current.amountCents,c.prior.amountCents]),1):1;
 const bar=(value,label,current)=> <div className="progress" role="img" aria-label={`${label}: ${money(value)}`}><span style={{width:`${value/scale*100}%`,background:current?'var(--accent)':'var(--chart-neutral)'}}/></div>;
 return <><div className="page-header"><div><h1>Fundraising analytics</h1><p>Compare received contributions and the people behind them.</p></div><div className="header-actions">{onNavigate&&<button type="button" className="btn btn-secondary" onClick={()=>onNavigate('gifts')}>Gift ledger<ArrowUpRight size={15}/></button>}<button type="button" className="btn btn-secondary" disabled={!r?.sourceGifts.length} onClick={()=>exportSources(r.sourceGifts,'comparison')}><Download size={15}/>Export source CSV</button></div></div>
 <section className="panel"><div className="form-grid"><label className="field">School year<select value={r?.schoolYear||''} disabled={!r} onChange={e=>{setYear(e.target.value);setInspection(null);}}>{r?.years.map(y=><option key={y} value={y}>{y}</option>)}</select></label><label className="field">As of<input type="date" required max={today()} value={asOf} onChange={e=>{setAsOf(e.target.value);setInspection(null);}}/></label></div>{r&&<p className="table-note">Current: {r.periods.current.schoolYear} through {dateLabel(r.periods.current.cutoff)} · Prior: {r.periods.prior.schoolYear} through {dateLabel(r.periods.prior.cutoff)} · Fiscal year begins in month {startMonth}.</p>}</section>
 {calculation.error&&<div className="error-banner" role="alert">{calculation.error}</div>}
 {r&&<><section className="panel"><div className="section-title"><div><p className="subtle">Received monetary contributions · {r.schoolYear}</p><h2 style={{fontSize:'28px',fontVariantNumeric:'tabular-nums'}}>{money(r.current.amountCents)}</h2><p>{r.current.giftCount} gifts from {r.current.donorCount} donors · Prior comparison: {money(r.prior.amountCents)}</p></div><BarChart3 size={24} aria-hidden="true"/></div><div className="summary-strip"><div><span>Retained prior donors</span><strong>{r.retention.retainedDonors} / {r.retention.priorDonors}</strong></div><div><span>Retention</span><strong>{percent(r.retention.ratePercent)}</strong></div><div><span>First recorded donors</span><strong>{r.cohorts.new.donorIds.length}</strong></div><div><span>Existing donors returned</span><strong>{r.cohorts.reactivated.donorIds.length}</strong></div></div><p className="table-note">{r.scope}</p><button type="button" className="text-btn" disabled={!r.current.giftCount} onClick={()=>inspect('Current contributions',r.current)}>Inspect current source gifts<ArrowUpRight size={14}/></button>{!r.current.giftCount&&<p className="empty-state">No eligible contributions are assigned to this year through the selected cutoff. Choose another year or inspect the gift ledger.</p>}
 {(r.offCalendar.current.giftCount>0||r.offCalendar.prior.giftCount>0)&&<p className="scope-banner">Explicit assignments include {r.offCalendar.current.giftCount} current and {r.offCalendar.prior.giftCount} prior gifts outside their assigned year’s calendar dates. Original dates still control the cutoff. <button type="button" className="text-btn" onClick={()=>inspect('Gifts assigned outside their calendar year',{giftIds:[...r.offCalendar.current.giftIds,...r.offCalendar.prior.giftIds]})}>Inspect assigned gifts</button></p>}{r.unattributed.giftCount>0&&<p className="scope-banner">{r.unattributed.giftCount} gifts have no donor ID. Their value is included; they are excluded from donor counts and frequency cohorts.</p>}</section>
 <section className="panel"><div className="section-title"><div><h2>Donor retention</h2><p>Retained, first-ever, and returning donors partition the current donor count.</p></div></div><div className="table-wrap"><table aria-label="Donor cohorts"><thead><tr><th scope="col">Cohort</th><th scope="col" className="money">Donors</th><th scope="col" className="money">Current received</th><th scope="col" className="money">Prior received</th><th scope="col">Evidence</th></tr></thead><tbody>{Object.entries(r.cohorts).map(([key,c])=><tr key={key}><td>{key==='retained'?'Retained':key==='new'?'First recorded':key==='reactivated'?'Reactivated / returning':'Not yet returned'}</td><td className="money">{c.donorIds.length}</td><td className="money">{money(c.current.amountCents)}</td><td className="money">{money(c.prior.amountCents)}</td><td><button type="button" className="text-btn" disabled={!c.donorIds.length} onClick={()=>cohortInspect(c)}>Inspect donors and gifts</button></td></tr>)}</tbody></table></div><p className="table-note">First recorded donors have their first saved eligible monetary gift in the selected scope. Reactivated donors have older support outside the matched prior period. “Not yet returned” means no current contribution through this cutoff; it does not predict attrition. Retention is unavailable when the prior donor cohort is empty.</p></section>
 <section className="panel"><div className="section-title"><div><h2>Campaign performance</h2><p>Indigo is current received support; gray is prior. Bars share one scale.</p></div></div><div className="table-wrap"><table aria-label="Campaign received contributions comparison"><thead><tr><th scope="col">Campaign</th><th scope="col" className="money">Current received</th><th scope="col" className="money">Prior received</th><th scope="col" className="money">Current donors</th><th scope="col">Evidence</th></tr></thead><tbody>{r.campaignPerformance.map((c,i)=><tr key={c.id||`none-${i}`}><td>{c.known&&onOpen?<button type="button" className="record-link" onClick={()=>onOpen('campaigns',c.id)}>{c.label}</button>:c.label}</td><td className="money">{money(c.current.amountCents)}{bar(c.current.amountCents,c.label+' current',true)}</td><td className="money">{money(c.prior.amountCents)}{bar(c.prior.amountCents,c.label+' prior',false)}</td><td className="money">{c.current.donorCount}</td><td><button type="button" className="text-btn" disabled={!c.current.giftCount&&!c.prior.giftCount} onClick={()=>inspect(c.label,{giftIds:[...c.current.giftIds,...c.prior.giftIds],donorIds:[...new Set([...c.current.donorIds,...c.prior.donorIds])]})}>Inspect gifts</button></td></tr>)}</tbody></table></div>{!r.campaignPerformance.length&&<p className="empty-state">No campaigns or campaign-linked eligible gifts are saved.</p>}<p className="table-note">Unlinked gifts and unavailable campaign references remain visible. Campaign goals are not treated as money received.</p></section>
 <section className="panel"><div className="section-title"><div><h2>Gift size and donation frequency</h2><p>Current-period gifts by value, then donors by the number of contributions recorded.</p></div></div><h3>Gift size</h3><div className="table-wrap"><table aria-label="Gift size distribution"><thead><tr><th scope="col">Saved gift value</th><th scope="col" className="money">Gifts</th><th scope="col" className="money">Donors</th><th scope="col" className="money">Received</th><th scope="col">Evidence</th></tr></thead><tbody>{r.giftSize.map(b=><tr key={b.label}><td>{b.label}</td><td className="money">{b.giftCount}</td><td className="money">{b.donorCount}</td><td className="money">{money(b.amountCents)}</td><td><button type="button" className="text-btn" disabled={!b.giftCount} onClick={()=>inspect(b.label,b)}>Inspect gifts</button></td></tr>)}</tbody></table></div><p className="table-note">A donor can appear in several gift-size bands. Gift counts and received values reconcile across bands.</p><h3>Donation frequency</h3><div className="table-wrap"><table aria-label="Donation frequency distribution"><thead><tr><th scope="col">Gifts per donor</th><th scope="col" className="money">Donors</th><th scope="col" className="money">Gifts</th><th scope="col" className="money">Received</th><th scope="col">Evidence</th></tr></thead><tbody>{r.frequency.map(b=><tr key={b.label}><td>{b.label}</td><td className="money">{b.donorCount}</td><td className="money">{b.giftCount}</td><td className="money">{money(b.amountCents)}</td><td><button type="button" className="text-btn" disabled={!b.donorCount} onClick={()=>inspect(b.label,b)}>Inspect donors and gifts</button></td></tr>)}</tbody></table></div><p className="table-note">Each identified donor belongs to one frequency band. These are recorded gift counts, not recurring-gift commitments.</p></section>
 {inspection&&<section className="panel" aria-label="Supporting records" tabIndex={-1} ref={evidenceRef}><div className="section-title"><div><h2>{inspection.label}</h2><p>{source.length} supporting gifts · includes earliest recorded history when relevant.</p></div><div className="header-actions"><button type="button" className="btn btn-secondary" disabled={!source.length} onClick={()=>exportSources(source,'supporting-records')}><Download size={15}/>Export these sources</button><button type="button" className="btn btn-secondary" onClick={()=>setInspection(null)}>Close evidence</button></div></div>{inspection.donorIds.length>0&&<details><summary>Supporting donor records · {inspection.donorIds.length}</summary><div className="form-grid">{inspection.donorIds.map(id=><button type="button" className="text-btn" key={id} disabled={!onOpen} onClick={()=>onOpen?.('constituents',id)}>{data.constituents?.find(p=>p.id===id)?.name||'Unavailable donor'}<ArrowUpRight size={13}/></button>)}</div></details>}<div className="table-wrap"><table aria-label="Supporting source gifts"><thead><tr><th scope="col">Donor</th><th scope="col">Date</th><th scope="col">Assigned year</th><th scope="col">Comparison</th><th scope="col" className="money">Received</th><th scope="col">Source</th></tr></thead><tbody>{source.slice(0,100).map(g=><tr key={g.id}><td>{g.donorName}</td><td>{dateLabel(g.date)}</td><td>{g.schoolYear}</td><td>{g.period}</td><td className="money">{money(g.amountCents)}</td><td><button type="button" className="text-btn" disabled={!onOpen} onClick={()=>onOpen?.('gifts',g.id)}>Open gift</button></td></tr>)}</tbody></table></div>{source.length>100&&<p className="table-note">First 100 source gifts shown. The source CSV includes all {source.length} matching records.</p>}</section>}
 </>}
 </>;
}
