import { useId } from 'react';
import { ArrowUpRight, FileCheck2, Plus } from 'lucide-react';
import { dateLabel, money, nameOf, today } from '../lib';
import { grantReconciliation } from '../phaseThree';
import { Status } from '../components/Fields';

export default function GrantDetail({ grant, data, onOpen, onCreateGift, canWrite }) {
  const prefix = useId();
  const reconciliation = grantReconciliation(grant, data.gifts, today());
  const linked = (data.gifts || []).filter(gift => gift.grantId === grant.id).sort((a, b) => b.date.localeCompare(a.date));
  return <section className="panel grant-lifecycle" aria-labelledby={`${prefix}-title`}>
    <div className="section-title"><div><h2 id={`${prefix}-title`}>Funding lifecycle</h2><p className="subtle">Recorded request, award and receipts are separate values.</p></div>{canWrite && grant.funderId && onCreateGift && reconciliation.awarded > 0 && reconciliation.balance > 0 && <button type="button" className="btn btn-secondary" onClick={onCreateGift}><Plus size={15} aria-hidden="true" /> Record grant receipt</button>}</div>
    {reconciliation.awardUnknown && <p className="error-banner grant-unknown-award" role="status">This legacy record is marked {grant.stage} but has no recorded award amount. The request has not been treated as an award. Record the verified award before linking grant receipts.</p>}
    <div className="summary-strip grant-financials"><div><span>Requested funding</span><strong>{money(reconciliation.requested)}</strong><small>Application value</small></div><div><span>Recorded award</span><strong>{reconciliation.awardUnknown ? 'Unknown' : money(reconciliation.awarded)}</strong><small>Commitment, not income</small></div><div><span>Received through today</span><strong>{money(reconciliation.received)}</strong><small>{reconciliation.receiptCount} posted linked {reconciliation.receiptCount === 1 ? 'gift' : 'gifts'}</small></div><div><span>Known award balance</span><strong>{reconciliation.awardUnknown ? 'Unknown' : money(reconciliation.balance)}</strong><small>Award less posted receipts</small></div></div>
    <dl className="facts-grid"><div><dt>Funder</dt><dd>{grant.funderId ? <button type="button" className="record-link" onClick={() => onOpen('constituents', grant.funderId)}>{nameOf(data, 'constituents', grant.funderId)} <ArrowUpRight size={12} aria-hidden="true" /></button> : 'Not recorded; no funder inferred'}</dd></div><div><dt>Award date</dt><dd>{dateLabel(grant.awardDate)}</dd></div><div><dt>Application deadline</dt><dd>{dateLabel(grant.deadline)}</dd></div><div><dt>Reporting deadline</dt><dd>{dateLabel(grant.reportDue)}</dd></div></dl>
    <p className="table-note grant-reconciliation-note">Only explicitly linked, posted Grant gifts through today count as receipts. They must match the known funder and cannot also fulfill a pledge. Voiding a receipt releases the award balance. Recorded awards and receipts are not combined as income, and this is not bank reconciliation.</p>
    <div className="allocation-section grant-receipts"><h3 className="section-title"><FileCheck2 size={16} aria-hidden="true" /> Linked receipt history</h3>{linked.length ? <div className="table-wrap"><table><caption>All linked gifts, including voided records and gifts dated after today. Received totals above include only qualifying gifts through today.</caption><thead><tr><th scope="col">Gift date</th><th scope="col">Funder / donor</th><th scope="col">Recorded method</th><th scope="col">Reference</th><th scope="col" className="money">Value</th><th scope="col">Status</th><th scope="col">Record</th></tr></thead><tbody>{linked.map(gift => <tr key={gift.id}><td>{dateLabel(gift.date)}</td><td>{nameOf(data, 'constituents', gift.constituentId)}</td><td>{gift.method}</td><td>{gift.externalRef || '—'}</td><td className="money">{money(gift.amount)}</td><td><Status value={gift.status} />{gift.date > today() && <small className="cell-detail">After current as-of date</small>}</td><td><button type="button" className="text-btn" onClick={() => onOpen('gifts', gift.id)}>Open gift <ArrowUpRight size={12} aria-hidden="true" /></button></td></tr>)}</tbody></table></div> : <div className="empty-state"><FileCheck2 size={27} aria-hidden="true" /><h3>No linked receipts yet</h3><p>{reconciliation.awarded > 0 ? 'Record a Grant gift and link this grant when funds are received.' : 'Verify and record the award amount first. The requested amount does not create a receipt.'}</p></div>}</div>
  </section>;
}
