import {useEffect,useState} from 'react';
import {CalendarDays,Plus,ArrowUpRight,Download} from 'lucide-react';
import {today,dateLabel,download,money} from '../lib';
const category={Application:'Proposal',Report:'Report',Agreement:'Agreement'};
export default function GrantOperations({api,user,onCommitted,notify,onOpen,onDirty}){
 const [state,setState]=useState({milestones:[],owners:[],grants:[],documents:[]}),[filters,setFilters]=useState({grantId:'',status:'',kind:'',from:'',to:''}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editor,setEditor]=useState(null),[draft,setDraft]=useState({}),[dirty,setDirty]=useState(false);
 const canWrite=['admin','staff'].includes(user.role),blocked=busy||loading||Boolean(editor);
 const path='/grant-operations?'+new URLSearchParams(Object.entries(filters).filter(([,v])=>v));
 async function load(){const next=await api(path);setState(next);}
 async function reload(){setBusy(true);setError('');try{await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{let live=true;setLoading(true);setError('');api(path).then(r=>live&&setState(r)).catch(e=>{if(live){setError(e.message);setState(s=>({...s,milestones:[],documents:[]}));}}).finally(()=>live&&setLoading(false));return()=>{live=false;};},[api,path]);
 function begin(type,m=null){setError('');setDirty(false);onDirty?.(false);setEditor({type,m});setDraft(type==='complete'?{documentId:'',revision:'',completedDate:today(),reference:'',confirmed:false}:type==='reopen'?{reason:''}:{grantId:m?.grantId||filters.grantId||'',name:m?.name||'',kind:m?.kind||'Application',dueDate:m?.dueDate||today(),ownerId:m?.owner.id||''});}
 function change(k,v){setDirty(true);setDraft(p=>({...p,[k]:v}));onDirty?.(true);}
 function cancel(){if(dirty&&!window.confirm('Discard unsaved grant milestone changes?'))return;setEditor(null);setDraft({});setDirty(false);onDirty?.(false);}
 const activeGrant=state.grants.find(g=>g.id===(editor?.m?.grantId||draft.grantId)),selectedDocument=state.documents.find(d=>d.id===draft.documentId),options=editor?.type==='complete'?state.documents.filter(d=>d.grantId===editor.m.grantId&&d.revisions.some(r=>r.metadata.category===category[editor.m.kind]&&['Final','Submitted'].includes(r.metadata.status))):[];
 async function submit(e){e.preventDefault();setBusy(true);setError('');let saved=false;try{const {type,m}=editor;let body,url='/grant-operations',method='POST';if(type==='reopen'){url+='/'+m.id+'/reopen';body={version:m.version,reason:draft.reason};}else if(type==='complete'){const u=state.owners.find(o=>o.id===m.owner.id);if(!u||!activeGrant||!selectedDocument)throw new Error('Select current grant, active owner and documentary evidence. Reload if an owner is unavailable.');url+='/'+m.id+'/complete';body={version:m.version,grantVersion:activeGrant.version,ownerVersion:u.version,documentId:selectedDocument.id,documentVersion:selectedDocument.version,revision:Number(draft.revision),completedDate:draft.completedDate,reference:draft.reference,confirmed:draft.confirmed};}else{const u=state.owners.find(o=>o.id===draft.ownerId);if(!u||!activeGrant)throw new Error('Choose a grant and an active staff owner.');body={name:draft.name,kind:draft.kind,dueDate:draft.dueDate,ownerId:u.id,ownerVersion:u.version,grantVersion:activeGrant.version,...(m?{version:m.version}:{grantId:activeGrant.id})};if(m){url+='/'+m.id;method='PATCH';}}await api(url,{method,body});saved=true;setEditor(null);setDirty(false);onDirty?.(false);await load();await onCommitted?.();notify?.('Grant milestone history saved.');}catch(e){setError(saved?'Saved, but refresh failed. Reload milestones to review retained history.':e.message);}finally{setBusy(false);}}
 async function evidenceFile(d){setBusy(true);setError('');try{const r=await api('/documents/'+d.id+'/revisions/'+d.revision+'/content');download(r.filename,Uint8Array.from(atob(r.contentBase64),c=>c.charCodeAt(0)),r.mime);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section><div className="page-header"><div><h1>Grant milestones</h1><p>Staff-owned application, agreement and reporting dates with documented completion.</p></div>{canWrite&&<button className="btn btn-primary" disabled={blocked} onClick={()=>begin('create')}><Plus size={16}/>Create milestone</button>}</div><p className="scope-banner">Completion records human confirmation of a linked final/submitted document revision. This does not submit proposals, deliver reports, send reminders, change awards or record revenue.</p>{error&&<p className="error-banner" role="alert">{error}</p>}
 <div className="toolbar">{[['grantId','Grant'],['status','Status'],['kind','Milestone type']].map(([key,label])=><label className="field" key={key}>{label}<select disabled={blocked} value={filters[key]} onChange={e=>setFilters(p=>({...p,[key]:e.target.value}))}><option value="">All</option>{(key==='grantId'?state.grants:key==='status'?['Open','Completed']:Object.keys(category)).map(v=><option key={v.id||v} value={v.id||v}>{v.name||v}</option>)}</select></label>)}{[['from','Due from'],['to','Due through']].map(([k,label])=><label className="field" key={k}>{label}<input type="date" disabled={blocked} value={filters[k]} onChange={e=>setFilters(p=>({...p,[k]:e.target.value}))}/></label>)}<button className="btn btn-secondary" disabled={blocked} onClick={reload}>Reload milestones</button></div>
 {editor&&<section className="panel inline-editor"><h2>{editor.type==='complete'?'Confirm documented completion':editor.type==='reopen'?'Reopen with retained history':'Milestone ownership and due date'}</h2><form onSubmit={submit}><fieldset disabled={busy}><div className="form-grid">{['create','edit'].includes(editor.type)&&<><label className="field">Grant<select required disabled={Boolean(editor.m)} value={draft.grantId} onChange={e=>change('grantId',e.target.value)}><option value="">Choose grant</option>{state.grants.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label className="field">Name<input required maxLength={250} value={draft.name} onChange={e=>change('name',e.target.value)}/></label><label className="field">Type<select value={draft.kind} onChange={e=>change('kind',e.target.value)}>{Object.keys(category).map(k=><option key={k}>{k}</option>)}</select></label><label className="field">Due date<input type="date" required value={draft.dueDate} onChange={e=>change('dueDate',e.target.value)}/></label><label className="field">Active owner<select required value={draft.ownerId} onChange={e=>change('ownerId',e.target.value)}><option value="">Choose active staff owner</option>{state.owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label></>}
 {editor.type==='complete'&&<><label className="field">Linked final/submitted {category[editor.m.kind].toLowerCase()}<select required value={draft.documentId} onChange={e=>{change('documentId',e.target.value);change('revision','');}}><option value="">Choose evidence</option>{options.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select>{!options.length&&<small>No eligible document. Cancel this form, then open the grant to upload final evidence.</small>}</label><label className="field">Immutable revision<select required value={draft.revision} onChange={e=>change('revision',e.target.value)}><option value="">Choose revision</option>{(selectedDocument?.revisions||[]).filter(r=>r.metadata.category===category[editor.m.kind]&&['Final','Submitted'].includes(r.metadata.status)).map(r=><option key={r.revision} value={r.revision}>v{r.revision} · {r.filename} · {r.metadata.status}</option>)}</select></label><label className="field">Actual completion date<input type="date" required max={today()} value={draft.completedDate} onChange={e=>change('completedDate',e.target.value)}/></label><label className="field">Actual reference / verification note<textarea required maxLength={2000} value={draft.reference} onChange={e=>change('reference',e.target.value)}/></label><label className="check-field"><input type="checkbox" required checked={draft.confirmed} onChange={e=>change('confirmed',e.target.checked)}/>I reviewed this exact revision and confirm the recorded completion date and reference.</label></>}
 {editor.type==='reopen'&&<label className="field field-wide">Reason for reopening<textarea required maxLength={2000} value={draft.reason} onChange={e=>change('reason',e.target.value)}/><small>Prior completion, original document revision and owner/source versions remain in history.</small></label>}</div><div className="form-actions"><button className="btn btn-primary" disabled={editor.type==='complete'&&(!draft.confirmed||!options.length)}>{busy?'Saving…':editor.type==='complete'?'Confirm completion':'Save milestone'}</button><button type="button" className="btn btn-secondary" onClick={cancel}>Cancel changes</button></div></fieldset></form></section>}
 <section className="panel"><h2><CalendarDays size={18}/>Dated milestone calendar</h2>{loading?<p role="status">Loading milestones…</p>:!state.milestones.length?<p>No milestones match these filters.</p>:<div className="table-wrap"><table className="grant-calendar" aria-label="Grant milestone calendar"><thead><tr><th>Due</th><th>Grant / milestone</th><th>Owner</th><th>Status / evidence</th><th>Manage</th></tr></thead><tbody>{[...state.milestones].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).map(m=><tr key={m.id}><td data-label="Due">{dateLabel(m.dueDate)}{m.status==='Open'&&m.dueDate<today()&&<small className="cell-detail">Overdue</small>}</td><td data-label="Grant / milestone"><button className="text-btn" disabled={blocked} onClick={()=>onOpen?.('grants',m.grantId)}>{m.source.name}<ArrowUpRight size={13}/></button><small className="cell-detail">{m.kind} · {m.name}</small></td><td data-label="Owner">{m.owner.name}<small className="cell-detail">Recorded account version {m.owner.version}</small></td><td data-label="Status / evidence">{m.status}{m.completion&&<small className="cell-detail">{dateLabel(m.completion.completedDate)} · {m.completion.reference} · document v{m.completion.document.revision}</small>}<details><summary>Retained history · {m.history.length}</summary>{m.history.map(h=><div key={h.version}><p>v{h.version} · {h.action} · {dateLabel(h.at)} · {h.snapshot.owner.name}{h.reason?' · '+h.reason:''}</p><small>Source grant v{h.snapshot.source.version}; request {money(h.snapshot.source.requestedCents)}, award {h.snapshot.source.awardedCents===null?'unverified':money(h.snapshot.source.awardedCents)}. These are saved source facts, not milestone income.</small>{h.snapshot.completion&&<p>{h.snapshot.completion.reference} · {h.snapshot.completion.document.filename} v{h.snapshot.completion.document.revision}{h.documentArchived?' · Archived evidence retained':''} <button className="text-btn" disabled={blocked} onClick={()=>evidenceFile(h.snapshot.completion.document)}><Download size={13}/>Download exact evidence</button></p>}</div>)}</details></td><td data-label="Actions">{canWrite&&<div className="row-buttons">{m.status==='Open'?<><button className="text-btn" disabled={blocked} onClick={()=>begin('edit',m)}>Edit</button><button className="text-btn" disabled={blocked} onClick={()=>begin('complete',m)}>Complete with evidence</button></>:<button className="text-btn" disabled={blocked} onClick={()=>begin('reopen',m)}>Reopen</button>}</div>}</td></tr>)}</tbody></table></div>}</section></section>;
}
