import {useEffect,useRef,useState} from 'react';
import {dateLabel} from '../lib';

export default function HelperEventAccess({account,events=[],api,onSaved,onCancel,onBusy}){
 const [access,setAccess]=useState(null),[selected,setSelected]=useState([]),[reason,setReason]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const alive=useRef(true);
 useEffect(()=>{onBusy?.(busy);return()=>onBusy?.(false);},[busy,onBusy]);
 useEffect(()=>{alive.current=true;setLoading(true);setAccess(null);setError('');api('/users/'+encodeURIComponent(account.id)+'/event-access').then(result=>{if(alive.current){setAccess(result);setSelected(result.eventIds);}}).catch(e=>{if(alive.current)setError(e.message);}).finally(()=>{if(alive.current)setLoading(false);});return()=>{alive.current=false;};},[api,account.id]);
 async function save(e){e.preventDefault();if(!access||busy)return;setBusy(true);setError('');try{const result=await api('/users/'+encodeURIComponent(account.id)+'/event-access',{method:'PATCH',body:{version:access.version,eventIds:selected,reason:reason.trim()}});if(!alive.current)return;await onSaved(result);}catch(e){if(alive.current)setError(e.status===409?'Access changed since this form opened. Close and reopen it to review current assignments.':e.message);}finally{if(alive.current)setBusy(false);}}
 const choices=[...events,...selected.filter(id=>!events.some(event=>event.id===id)).map(id=>({id,name:'Unavailable event · '+id,date:null}))];
 return <form className="inline-editor" onSubmit={save} aria-label={'Assigned events for '+account.name}><h3>Assigned events · {account.name}</h3><p className="table-note">This helper can view issued ticket names and record check-in for selected events only. New helpers start with no assignments. Saving changes ends their sessions and requires a fresh sign-in; previous grant history is retained.</p>{error&&<p className="error-banner" role="alert">{error}</p>}{loading?<p role="status">Loading current event access…</p>:access&&<><fieldset disabled={busy} className="field field-wide"><legend>Choose events · {selected.length}/100 assigned</legend><div className="form-grid">{choices.map(event=><label key={event.id}><input type="checkbox" checked={selected.includes(event.id)} disabled={!selected.includes(event.id)&&selected.length>=100} onChange={e=>setSelected(current=>e.target.checked?[...current,event.id]:current.filter(id=>id!==event.id))}/>{event.name}{event.date&&<span className="subtle"> · {dateLabel(event.date)}</span>}</label>)}</div>{!choices.length&&<p>No events exist yet. Create an event before assigning helper access.</p>}</fieldset><label className="field">Reason for this access decision<textarea required minLength={1} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} disabled={busy} placeholder="Explain the assigned duty or why access is being removed."/></label><p className="subtle">Clear every selection to revoke all event access. This does not remove their account or retained attendance history.</p></>}<div className="form-actions"><button className="btn btn-primary" type="submit" disabled={loading||busy||!access||!reason.trim()}>{busy?'Saving…':'Save event assignments'}</button><button className="btn btn-secondary" type="button" disabled={busy} onClick={onCancel}>Close event assignments</button></div></form>;
}
