import {useEffect,useRef,useState} from 'react';
import {Users,Plus,ArrowUpRight,GitMerge} from 'lucide-react';
import {nameOf} from '../lib';

const emptyHousehold={name:'',address:'',memberIds:[]};
const emptyMerge={targetId:'',sourceId:'',reason:'',parentChoice:'keep'};
export default function Identity({api,user,data,onCommitted,onOpen,notify,onDirty}){
 const [households,setHouseholds]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editor,setEditor]=useState(null),[household,setHousehold]=useState(emptyHousehold),[search,setSearch]=useState(''),[merge,setMerge]=useState(emptyMerge),[preview,setPreview]=useState(null),[confirmed,setConfirmed]=useState(false),[result,setResult]=useState(null);
 const firstInput=useRef(null),canAdmin=user.role==='admin';
 const active=(data.constituents||[]).filter(c=>!c.mergedInto),people=active.filter(c=>['Individual','Alumni','Employee','Staff'].includes(c.type));
 async function load(){const r=await api('/households');setHouseholds(r.households);}
 useEffect(()=>{let live=true;load().catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false;};},[api]);
 useEffect(()=>{if(editor)firstInput.current?.focus();},[editor?.id]);
 useEffect(()=>{setPreview(null);setConfirmed(false);},[data]);
 function begin(h){setEditor(h||{id:null});setHousehold(h?{name:h.name,address:h.address,memberIds:[...h.memberIds]}:{...emptyHousehold,memberIds:[]});setSearch('');setError('');onDirty?.(false);}
 function changeHousehold(k,v){setHousehold(p=>({...p,[k]:v}));onDirty?.(true);}
 function changeMerge(k,v){setMerge(p=>({...p,[k]:v}));setPreview(null);setConfirmed(false);setResult(null);onDirty?.(true);}
 function cancelHousehold(){setEditor(null);onDirty?.(Boolean(merge.targetId||merge.sourceId||merge.reason));}
 async function saveHousehold(e){e.preventDefault();setBusy(true);setError('');try{await api('/households'+(editor.id?'/'+editor.id:''),{method:editor.id?'PATCH':'POST',body:{...household,...(editor.id?{version:editor.version}:{})}});setEditor(null);onDirty?.(Boolean(merge.targetId||merge.sourceId||merge.reason));await load();await onCommitted?.();notify?.('Household membership saved. Giving records were preserved.');}catch(e){setError(e.message+' Reload households before retrying a version conflict.');}finally{setBusy(false);}}
 function mergeBody(){const target=active.find(c=>c.id===merge.targetId),source=active.find(c=>c.id===merge.sourceId);if(!target||!source)throw new Error('Choose two current constituents.');return {targetId:target.id,sourceId:source.id,targetVersion:target.version,sourceVersion:source.version,reason:merge.reason,...(merge.parentChoice!=='keep'?{parentId:merge.parentChoice||null}:{})};}
 async function reviewMerge(e){e.preventDefault();setBusy(true);setError('');setPreview(null);setConfirmed(false);try{const body=mergeBody(),r=await api('/identity/merge/preview',{method:'POST',body});setPreview({...r.preview,input:body});}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function commitMerge(){if(!preview||preview.blockers.length||!confirmed)return;setBusy(true);setError('');try{const r=await api('/identity/merge',{method:'POST',body:{...preview.input,previewDigest:preview.previewDigest}});setResult(r);setPreview(null);setConfirmed(false);setMerge(emptyMerge);onDirty?.(Boolean(editor));await load();await onCommitted?.();notify?.('Duplicate resolved. Original identity and audit history remain retained.');}catch(e){setPreview(null);setConfirmed(false);setError(e.message+' Review a fresh preview. Check constituent history before retrying an uncertain merge.');}finally{setBusy(false);}}
 const owner=id=>households.find(h=>h.memberIds.includes(id));
 return <section><div className="page-header"><div><h1>Identity and households</h1><p className="subtle">Maintain shared households and resolve eligible duplicate constituents with a reviewed history.</p></div>{canAdmin&&<button className="btn btn-primary" disabled={busy||Boolean(editor)} onClick={()=>begin()}><Plus size={16}/>Create household</button>}</div>
 {error&&<p className="error-banner" role="alert">{error}</p>}
 {editor&&<section className="panel inline-editor"><h2>{editor.id?'Maintain household':'Create household'}</h2><p>Each person can belong to one managed household. Removing a member clears their shared household label and preserves their gifts.</p><form onSubmit={saveHousehold}><fieldset disabled={busy}><div className="form-grid"><label className="field">Household name<input ref={firstInput} required maxLength={250} value={household.name} onChange={e=>changeHousehold('name',e.target.value)}/></label><label className="field">Shared address<textarea maxLength={2000} value={household.address} onChange={e=>changeHousehold('address',e.target.value)}/></label><label className="field">Find a household member<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search people by name or email"/></label></div><div className="table-wrap"><table aria-label="Household member selection"><thead><tr><th>Member</th><th>Contact</th><th>Current household</th></tr></thead><tbody>{people.filter(c=>!search||[c.name,c.email].join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(c=>{const other=owner(c.id),disabled=Boolean(other&&other.id!==editor.id);return <tr key={c.id}><td><label className="check-field"><input type="checkbox" checked={household.memberIds.includes(c.id)} disabled={disabled} onChange={e=>changeHousehold('memberIds',e.target.checked?[...household.memberIds,c.id]:household.memberIds.filter(id=>id!==c.id))}/>{c.name}</label></td><td>{c.email||'—'}</td><td>{other?.name||c.household||'—'}{disabled&&<small className="cell-detail">Remove from the other household before assigning here.</small>}</td></tr>;})}</tbody></table></div><p className="table-note">Legacy household labels must be reconciled before switching families. Businesses and foundations remain organization relationships.</p><div className="form-actions"><button className="btn btn-primary" type="submit">{busy?'Saving…':'Save household membership'}</button><button className="btn btn-secondary" type="button" onClick={cancelHousehold}>Cancel household changes</button></div></fieldset></form></section>}
 <section className="panel"><div className="section-title"><h2>Managed households</h2><button className="text-btn" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Reload households</button></div>{loading?<p role="status">Loading households…</p>:households.length?<div className="table-wrap"><table aria-label="Managed households"><thead><tr><th>Household</th><th>Shared address</th><th>Members</th>{canAdmin&&<th>Maintain</th>}</tr></thead><tbody>{households.map(h=><tr key={h.id}><td><strong>{h.name}</strong><small className="cell-detail">Version {h.version}</small></td><td>{h.address||'—'}</td><td>{h.memberIds.length?h.memberIds.map(id=><div key={id}><button className="text-btn" onClick={()=>onOpen?.('constituents',id)}>{nameOf(data,'constituents',id)}<ArrowUpRight size={14}/></button></div>):'No current members'}</td>{canAdmin&&<td><button className="btn btn-secondary btn-small" disabled={busy||Boolean(editor)} onClick={()=>begin(h)}>Maintain household</button></td>}</tr>)}</tbody></table></div>:<div className="empty-state"><Users size={24}/><h3>No managed households yet</h3><p>Existing household labels remain available. An administrator can create a managed family with matching members.</p></div>}</section>
 {canAdmin?<section className="panel"><div className="section-title"><h2><GitMerge size={18}/>Review a duplicate</h2></div><p>Choose the surviving record and the duplicate to retain as source history. This workflow resolves eligible current links; protected historical identities can block consolidation.</p><form onSubmit={reviewMerge}><fieldset disabled={busy||Boolean(editor)}><div className="form-grid"><label className="field">Surviving constituent<select required value={merge.targetId} onChange={e=>changeMerge('targetId',e.target.value)}><option value="">Choose the record to keep</option>{active.map(c=><option key={c.id} value={c.id} disabled={c.id===merge.sourceId}>{c.name} · {c.email||c.type}</option>)}</select></label><label className="field">Duplicate constituent<select required value={merge.sourceId} onChange={e=>changeMerge('sourceId',e.target.value)}><option value="">Choose the source duplicate</option>{active.map(c=><option key={c.id} value={c.id} disabled={c.id===merge.targetId}>{c.name} · {c.email||c.type}</option>)}</select></label><label className="field">Organization parent resolution<select value={merge.parentChoice} onChange={e=>changeMerge('parentChoice',e.target.value)}><option value="keep">Keep surviving parent; flag any conflict</option><option value="">Explicitly remove organization parent</option>{active.filter(c=>![merge.targetId,merge.sourceId].includes(c.id)).map(c=><option key={c.id} value={c.id}>Use {c.name}</option>)}</select></label><label className="field">Reason and identity verification<textarea required maxLength={2000} value={merge.reason} onChange={e=>changeMerge('reason',e.target.value)} placeholder="Explain the evidence that these are the same constituent and why this record survives."/></label></div><div className="form-actions"><button className="btn btn-secondary" type="submit">{busy?'Reviewing…':'Preview duplicate resolution'}</button><button className="text-btn" type="button" onClick={()=>{setMerge(emptyMerge);setPreview(null);setConfirmed(false);onDirty?.(false);}}>Clear duplicate review</button></div></fieldset></form>
 {preview&&<section><h3>Merge review · {preview.source.name} into {preview.target.name}</h3><p>The surviving name stays <strong>{preview.mergedTarget.name}</strong>. Contact preference: <strong>{preview.mergedTarget.preference}</strong>. Contacts and segments combine; empty email or phone may be filled from the source. {preview.changes.length-1} linked records would be reassigned. The source identity and original snapshot remain retained.</p>{preview.blockers.length?<div className="error-banner" role="alert"><strong>This merge cannot proceed.</strong><ul>{preview.blockers.map((b,i)=><li key={i}>{b.reason}{b.recordId&&<button className="text-btn" onClick={()=>onOpen?.(b.collection,b.recordId)}>Open connected record</button>}</li>)}</ul><p>Resolve the named relationships, then request a new preview. Retained histories cannot be forced through this merge.</p></div>:<><div className="table-wrap"><table aria-label="Duplicate merge affected links"><thead><tr><th>Record type</th><th>Connected record</th></tr></thead><tbody>{preview.changes.slice(1).map(c=><tr key={c.collection+c.recordId}><td>{c.collection}</td><td><button className="text-btn" onClick={()=>onOpen?.(c.collection,c.recordId)}>{nameOf(data,c.collection,c.recordId)}<ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div><label className="check-field"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I verified these identities, reviewed the affected links and approve retaining the source as history.</label><div className="form-actions"><button className="btn btn-primary" disabled={busy||!confirmed} onClick={commitMerge}>Commit reviewed merge</button></div></>}</section>}
 {result&&<p className="success-banner" role="status">Duplicate resolved into {result.target.name}. {result.rewired} linked records were reassigned; the original source identity remains retained.</p>}
 </section>:<p className="table-note">Administrators maintain household membership and review duplicate resolution. You can inspect connected household members above.</p>}
 </section>;
}
