import {useEffect,useState} from 'react';
import {ArrowUpRight,Sparkles,RefreshCw} from 'lucide-react';
import {api as defaultApi} from '../api';
import {dateLabel,money} from '../lib';

const fallbackTasks=[{id:'help',label:'Workflow help'},{id:'constituent-summary',label:'Constituent summary',recordCollection:'constituents'},{id:'thank-you-draft',label:'Thank-you draft',recordCollection:'gifts'}];

export default function Intelligence({data,user,onNavigate,onOpen,onCreateDraft,api=defaultApi}){
 const [context,setContext]=useState(null);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState('');const [task,setTask]=useState('help');const [recordId,setRecordId]=useState('');const [question,setQuestion]=useState('How do I record a gift with split allocations?');const [busy,setBusy]=useState(false);const [saving,setSaving]=useState(false);const [saveStatus,setSaveStatus]=useState('');const [saveAttempted,setSaveAttempted]=useState(false);const [error,setError]=useState('');const [answer,setAnswer]=useState(null);const [draft,setDraft]=useState('');
 const canAssist=['admin','staff'].includes(user?.role);
 useEffect(()=>{let live=true;setLoading(true);setLoadError('');api('/intelligence').then(payload=>{if(live)setContext(payload);}).catch(e=>{if(live)setLoadError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[api,data]);
 const tasks=context?.tasks||fallbackTasks;
 const selectedTask=tasks.find(t=>t.id===task)||tasks[0];
 const records=task==='thank-you-draft'?(data.gifts||[]).filter(g=>g.status!=='Voided'&&g.date<=new Date().toISOString().slice(0,10)&&!['Fee payment','In-kind'].includes(g.type)&&data.constituents?.find(p=>p.id===g.constituentId)?.preference!=='Do not contact'):data.constituents||[];
 const ready=Boolean(context?.provider.configured&&context.policy.enabled&&context.policy.dataMode==='synthetic'&&canAssist);
 function chooseTask(value){setSaveStatus('');setSaveAttempted(false);setTask(value);setRecordId('');setAnswer(null);setDraft('');setError('');}
 async function generate(e){e.preventDefault();setSaveStatus('');setSaveAttempted(false);setBusy(true);setError('');setAnswer(null);setDraft('');try{const result=await api('/intelligence/assist',{method:'POST',body:{task,...(task==='help'?{question}:{recordId})}});setAnswer(result);setDraft(result.text);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function saveDraft(){const gift=(data.gifts||[]).find(g=>g.id===answer?.recordId);if(!gift||!draft.trim()||!onCreateDraft||saving)return;setSaving(true);setSaveAttempted(true);setError('');setSaveStatus('');try{await onCreateDraft({constituentId:gift.constituentId,subject:'Thank you for your support',channel:'Email',status:'Draft',body:draft.trim(),notes:'AI-assisted draft reviewed by staff; no message sent.'});setAnswer(null);setDraft('');setSaveStatus('Draft saved. No message sent.');}catch(e){setError(e.message+' The draft save could not be confirmed. Check Communications before retrying.');}finally{setSaving(false);}}
 const giftLabel=g=>(data.constituents||[]).find(p=>p.id===g.constituentId)?.name+' · '+money(g.amount)+' · '+dateLabel(g.date);
 return <>
  <div className="page-header"><div><h1>Intelligence</h1><p>Review saved priorities, understand a workflow, or prepare text for review.</p></div><button type="button" className="btn btn-secondary" onClick={()=>onNavigate('operations')}>Open work queue<ArrowUpRight size={16}/></button></div>
  <section className="panel" aria-labelledby="intelligence-priorities"><div className="section-title"><div><h2 id="intelligence-priorities">Priorities from saved records</h2><p className="subtle">Rule-based facts, independent of the model. Review the supporting record before acting.</p></div></div>
   {loading&&<p role="status">Loading priorities…</p>}{loadError&&<p className="error-banner" role="alert">{loadError}</p>}
   {!loading&&context&&(context.priorities.length?context.priorities.map((p,i)=><button type="button" className="operations-work-row" key={p.kind+'-'+p.recordId+'-'+i} onClick={()=>p.view?onNavigate(p.view):onOpen(p.collection,p.recordId)}><span><strong>{p.title}</strong><small>{p.detail}</small></span><ArrowUpRight size={16}/></button>):<div className="operations-empty"><h3>No priorities match the current rules</h3><p>These rules check due tasks, grant dates and open major follow-ups, eligible unacknowledged gifts, and active volunteer clocks. This is not a guarantee that every workflow is complete.</p></div>)}
  </section>
  <section className="panel" aria-labelledby="intelligence-assistance"><div className="section-title"><div><h2 id="intelligence-assistance">Assistance for review</h2><p className="subtle">Model responses are suggestions. They do not change records, send messages or issue receipts.</p></div><Sparkles size={18}/></div>
   {context&&<p className="scope-banner">{context.provider.processing==='cloud'?'Configured processing uses a cloud model, including cloud models reached through a local Ollama service.':'The configured endpoint uses a local Ollama model.'} Only workspaces explicitly enabled with a synthetic data policy can request assistance. Record prompts omit private notes, contact details and message history.</p>}
   {!ready&&<p role="status" className="error-banner">{!canAssist?'Model assistance is available to administrators and staff. Saved priorities remain readable.':context&&!context.policy.enabled?'Model assistance is disabled for this workspace.':context?.policy.dataMode==='restricted'?'Restricted workspace records are not sent to a model. Approved data scopes are required before enabling assistance.':context?.provider.reason||'Model assistance is unavailable until the server provider is configured. Priorities remain available.'}</p>}
   {ready&&<p className="table-note">{context.provider.reason} A stopped service, missing model or provider timeout will return an error rather than a generated result.</p>}
   <form onSubmit={generate} aria-label="Request model assistance"><fieldset disabled={busy||saving||!ready}><div className="form-grid">
    <label className="field">Task<select value={task} onChange={e=>chooseTask(e.target.value)}>{tasks.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label>
    {task==='help'?<label className="field field-wide">Workflow question<textarea required maxLength={1200} value={question} onChange={e=>setQuestion(e.target.value)} aria-describedby="intelligence-question-help"/><small id="intelligence-question-help">Ask about using Wimblo. Use synthetic information; do not paste personal information or notes.</small></label>:<label className="field">{selectedTask?.recordCollection==='gifts'?'Saved gift':'Constituent'}<select required value={recordId} onChange={e=>{setRecordId(e.target.value);setAnswer(null);setDraft('');}}><option value="">Choose a record</option>{records.map(r=><option key={r.id} value={r.id}>{task==='thank-you-draft'?giftLabel(r):r.name}</option>)}</select><small>Only the selected record's minimal facts are provided. Contact opt-outs block thank-you drafting.</small></label>}
   </div><div className="form-actions"><button className="btn btn-primary" type="submit"><RefreshCw size={16}/>{busy?'Requesting assistance…':'Generate for review'}</button></div></fieldset></form>
   {error&&<p role="alert" className="error-banner">{error}</p>}{saveStatus&&<p role="status">{saveStatus}</p>}
   {answer&&<section aria-labelledby="intelligence-response"><div className="section-title"><h3 id="intelligence-response">{answer.task==='thank-you-draft'?'Unsent thank-you draft':'Generated response'}</h3></div><p className="table-note">Generated by {answer.provider}. Check every factual statement against saved records before using it.</p><label className="field">Review and edit<textarea disabled={saving} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={6000} rows={10}/></label>{answer.sources.length>0&&<div className="header-actions">{answer.sources.map(s=><button className="text-btn" type="button" key={s.collection+s.id} onClick={()=>onOpen(s.collection,s.id)}>Open supporting {s.collection==='constituents'?'constituent':'gift'}<ArrowUpRight size={14}/></button>)}</div>}{answer.task==='thank-you-draft'&&onCreateDraft&&<div className="form-actions"><button className="btn btn-secondary" type="button" disabled={!draft.trim()||busy||saving} onClick={saveDraft}>{saving?'Saving draft…':'Save reviewed draft'}<ArrowUpRight size={16}/></button></div>}<p className="table-note">{saveAttempted?'Saving a draft does not send a message. Check Communications for its saved status.':'Nothing has been saved or sent. Saving a reviewed draft is a separate explicit action.'}</p></section>}
  </section>
 </>;
}
