import React,{useEffect,useRef,useState} from 'react';
export default function MailchimpContactSync({api,user,binding,person,onDirty,onBindingChanged,blocked=false}){
 const [provider,setProvider]=useState(null),[items,setItems]=useState([]),[cursor,setCursor]=useState(null),[detail,setDetail]=useState(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[uncertain,setUncertain]=useState(false),[loadedContext,setLoadedContext]=useState(null),[runnerStopped,setRunnerStopped]=useState(false);
 const generation=useRef(0),working=useRef(false),requestId=useRef(null);
 const context=String(user?.id)+':'+String(user?.role)+':'+binding.id+':'+binding.version+':'+person?.version+':'+binding.sourceCurrent+':'+binding.status+':'+binding.constituentId+':'+binding.constituentVersion+':'+person?.id;
 useEffect(()=>{onDirty?.(Boolean(reason||confirmed||uncertain||runnerStopped));},[reason,confirmed,uncertain,runnerStopped,onDirty]);
 useEffect(()=>{const epoch=++generation.current;setLoadedContext({api,context});setProvider(null);setItems([]);setCursor(null);setDetail(null);setRunnerStopped(false);setReason('');setConfirmed(false);setUncertain(false);requestId.current=null;working.current=false;setBusy(false);setError('');
 if(user?.role==='admin')Promise.all([api('/mailchimp-contact-sync/status'),api('/mailchimp-contact-sync/intents?limit=100&constituentId='+encodeURIComponent(binding.constituentId))]).then(([p,r])=>{if(epoch===generation.current){setProvider(p);setItems(r.intents);setCursor(r.nextCursor);}}).catch(e=>epoch===generation.current&&setError(e.message));
 return()=>{generation.current++;onDirty?.(false);};},[api,context]);
 const ready=loadedContext?.api===api&&loadedContext?.context===context&&user?.role==='admin'&&person?.id===binding.constituentId&&provider?.enabled===true&&provider.mode==='TEST_ONLY'&&!blocked&&binding.status==='Current'&&binding.sourceCurrent&&person?.version===binding.constituentVersion;
 const intent=detail?.intent,sourceCurrent=intent?.sourceCurrent===true;
 const adminControls=loadedContext?.api===api&&loadedContext?.context===context&&user?.role==='admin'&&provider?.enabled===true&&provider.mode==='TEST_ONLY'&&!blocked;
 const canClose=adminControls&&intent?.closeAllowed===true&&!intent?.writeAttempted&&['Ready','Unknown','ReviewRequired'].includes(intent?.status);
 async function task(fn){if(working.current)return;working.current=true;setBusy(true);setError('');const epoch=generation.current,current=()=>epoch===generation.current;try{await fn(current);}catch(e){if(current()){setError(e.message);setConfirmed(false);if([401,403].includes(e.status)){setProvider(null);setDetail(null);setItems([]);}}}finally{if(current()){working.current=false;setBusy(false);}}}
 async function reload(current,after=null){const r=await api('/mailchimp-contact-sync/intents?limit=100&constituentId='+encodeURIComponent(binding.constituentId)+(after?'&after='+encodeURIComponent(after):''));if(!current())return;setItems(old=>after?[...old,...r.intents.filter(x=>!old.some(y=>x.id===y.id))]:r.intents);setCursor(r.nextCursor);const key=intent?.id||r.intents.find(x=>x.requestId===requestId.current)?.id;if(key){const d=await api('/mailchimp-contact-sync/intents/'+key);if(current()){setDetail(d);setReason('');setConfirmed(false);setRunnerStopped(false);setUncertain(false);requestId.current=null;}}}
 const prepare=()=>task(async current=>{if(!ready||!reason.trim()||!confirmed||uncertain)return;requestId.current??=globalThis.crypto.randomUUID();try{const r=await api('/mailchimp-contact-sync/intents',{method:'POST',body:{requestId:requestId.current,constituentId:person.id,constituentVersion:person.version,bindingId:binding.id,bindingVersion:binding.version,reason:reason.trim(),confirmed:true}});if(current()){setDetail({intent:r.intent,history:[]});setConfirmed(false);setUncertain(false);onBindingChanged?.();}}catch(e){if(current())setUncertain(true);throw e;}});
 const action=kind=>task(async current=>{if(!confirmed||!reason.trim()||uncertain||(kind==='close-without-write'?(!canClose||!runnerStopped):(!ready||!sourceCurrent)))return;try{const r=await api('/mailchimp-contact-sync/intents/'+intent.id+'/'+kind,{method:'POST',body:{version:intent.version,reason:reason.trim(),confirmed:true,...(kind==='close-without-write'?{runnerStoppedConfirmed:true}:{})}});if(current()){setDetail({intent:r.intent,history:[]});setConfirmed(false);setReason('');setRunnerStopped(false);onBindingChanged?.();}}catch(e){if(current())setUncertain(true);throw e;}});
 if(user?.role!=='admin')return <section className="panel"><h2>Contact synchronization requires administrator access</h2></section>;
 if(loadedContext?.api!==api||loadedContext?.context!==context)return <section className="panel"><p role="status">Loading current contact synchronization…</p></section>;
 return <section className="panel" aria-label="Existing contact synchronization"><h2>Existing contact synchronization</h2><p className="table-note">{provider?.enabled?'TEST ONLY · Reviewed existing-member fields and unsubscribe actions. Synthetic provider checks are separate from the read-only member observations above.':'Outbound contact synchronization is disabled. Approved live setup and production acceptance remain pending.'} This workflow does not create contacts or send campaigns.</p>{error&&<p className="error-banner" role="alert">{error}</p>}{uncertain&&<p role="status">Completion is uncertain. Reload retained intents and inspect this request before another action. No update is retried automatically.</p>}
 <div className="toolbar"><button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>task(current=>reload(current))}>Reload contact intents</button>{cursor&&<button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>task(current=>reload(current,cursor))}>Load older contact intents</button>}</div><p className="table-note">Latest 100 intents per page for this constituent, including earlier bindings. Older active intents also prevent a new update on the server.</p>
 {items.filter(x=>x.constituentId===binding.constituentId).map(x=><button type="button" className="text-btn" key={x.id} disabled={busy} onClick={()=>task(async current=>{const d=await api('/mailchimp-contact-sync/intents/'+x.id);if(current()){setDetail(d);setReason('');setConfirmed(false);setRunnerStopped(false);setUncertain(false);requestId.current=null;}})}>{x.operation} · {x.status} · v{x.version} · {x.id}</button>)}
 <label className="field">Contact synchronization reason<textarea maxLength={500} value={reason} disabled={busy||uncertain||(!ready&&!canClose)||['Reconciled','ClosedWithoutWrite'].includes(intent?.status)} onChange={e=>{setReason(e.target.value);requestId.current=null;setConfirmed(false);}}/></label>
 {intent?.status==='ClosedWithoutWrite'&&!binding.sourceCurrent&&<p className="table-note">The original source changed. Review or retire the prior member binding, then observe a new binding before preparing current contact fields.</p>}
 {intent&&<><dl className="reconciliation-summary">{[['Intent',intent.id],['Status',intent.status],['Operation',intent.operation],['Version',intent.version],['Last observed membership',intent.providerStatus],['Source authority',intent.sourceCurrent?'Current':'Changed — review required'],['Provider write reserved',intent.writeAttempted?'Yes':'No'],['Retained suppression',intent.suppressed?'Yes':'No']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{intent.changes&&<details open><summary>Exact reviewed provider fields</summary><pre>{JSON.stringify(intent.changes,null,2)}</pre></details>}<p className="table-note">{intent.scope}</p></>}

 <label><input type="checkbox" checked={confirmed} disabled={busy||uncertain||(!canClose&&(!ready||Boolean(intent&&!sourceCurrent)))} onChange={e=>setConfirmed(e.target.checked)}/>{intent?'I reviewed this exact intent and authorize the displayed action.':'I reviewed the current source and approve preparing an existing-member update.'}</label> {canClose&&<div className="marketing-review"><p className="table-note">No provider write was reserved for this intent. Closure preserves its original source and history; it never certifies remote delivery or releases an attempted update.</p><label><input type="checkbox" checked={runnerStopped} disabled={busy||uncertain} onChange={e=>{setRunnerStopped(e.target.checked);setConfirmed(false);}}/>I verified the original update runner has stopped.</label></div>}<div className="form-actions">{canClose&&<button type="button" className="btn btn-secondary" disabled={busy||!confirmed||!runnerStopped||!reason.trim()||uncertain} onClick={()=>action('close-without-write')}>Close without provider write</button>}{['Reconciled','ClosedWithoutWrite'].includes(intent?.status)&&<button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>{setDetail(null);setReason('');setConfirmed(false);setRunnerStopped(false);requestId.current=null;}}>Review another update</button>}{!intent&&<button type="button" className="btn btn-primary" disabled={busy||!ready||!confirmed||!reason.trim()||uncertain} onClick={prepare}>Prepare reviewed contact update</button>}{intent?.status==='Ready'&&<button type="button" className="btn btn-primary" disabled={busy||!ready||!sourceCurrent||!confirmed||!reason.trim()||uncertain} onClick={()=>action('execute')}>Apply reviewed contact update once</button>}{['Unknown','Executing','ReviewRequired'].includes(intent?.status)&&<button type="button" className="btn btn-secondary" disabled={busy||!ready||!sourceCurrent||!confirmed||!reason.trim()||uncertain} onClick={()=>action('reconcile')}>Read back uncertain update</button>}</div>
 {detail?.history?.length>0&&<ol className="marketing-history">{detail.history.map(h=><li key={h.id}><strong>{h.action} · {h.status} · v{h.version}</strong><p>{h.reason}</p><small>{h.at}</small></li>)}</ol>}</section>;
}
