import {useState} from 'react';
import {Download} from 'lucide-react';
import {download,money,toCSV} from '../lib';

const PAGE_SIZE=50;
export function ValidationResults({rows=[]}) {
 const [filter,setFilter]=useState('all'),[page,setPage]=useState(0);
 const errors=rows.filter(row=>row.status==='Error');
 const visible=filter==='errors'?errors:rows;
 const lastPage=Math.max(0,Math.ceil(visible.length/PAGE_SIZE)-1),current=Math.min(page,lastPage);
 const start=current*PAGE_SIZE,shown=visible.slice(start,start+PAGE_SIZE);
 function exportErrors(){download('wimblo-migration-errors.csv',toCSV(['File number','Record type','Data row','Source ID','Problem'],errors.map(r=>[r.file,r.collection,r.row,r.sourceId,r.error])),'text/csv;charset=utf-8');}
 return <div className="migration-review"><div className="toolbar"><label className="field">Review rows<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="all">All rows ({rows.length})</option><option value="errors">Errors only ({errors.length})</option></select></label><button type="button" className="btn btn-secondary" disabled={!errors.length} onClick={exportErrors}><Download size={16}/>Download error checklist</button></div><p className="table-note">Data row 1 is the first record after the CSV header. Correct the prepared conversion copy, preserve the original export, upload the copy again, then preview. The checklist contains identifiers and problems, not a replacement import file.</p><div className="table-wrap"><table aria-label="Migration validation results"><thead><tr><th>File / type</th><th className="money">Data row</th><th>Source ID</th><th>Result</th></tr></thead><tbody>{shown.map((r,i)=><tr key={start+i}><td>{r.file??'—'} / {r.collection}</td><td className="money">{r.row}</td><td className="migration-identifier" title={r.sourceId}>{r.sourceId||'—'}</td><td>{r.error||r.status}</td></tr>)}</tbody></table></div>{!visible.length&&<p role="status" className="subtle">{filter==='errors'?'No validation errors. Review the totals before confirming.':'No source rows to review.'}</p>}<div className="migration-pagination"><p role="status">{visible.length?`${start+1}–${Math.min(start+PAGE_SIZE,visible.length)} of ${visible.length} rows`:'0 rows'}</p><button type="button" className="btn btn-secondary" disabled={current===0} onClick={()=>setPage(current-1)}>Previous rows</button><button type="button" className="btn btn-secondary" disabled={current===lastPage} onClick={()=>setPage(current+1)}>Next rows</button></div></div>;
}

export function ControlTotals({controls}) {
 const [scope,setScope]=useState('new');
 if(!controls)return <p className="subtle">Grouped control totals were not captured for this older batch.</p>;
 const selected=controls[scope];
 return <details className="migration-control-totals"><summary>Review revenue, payment methods and account codes</summary><label className="field">Totals scope<select value={scope} onChange={e=>setScope(e.target.value)}><option value="new">New records in this batch</option><option value="reused">Previously mapped records</option><option value="all">All validated gift rows</option></select></label><p className="table-note">These are source-row values, including future-dated posted gifts, not amounts currently raised. Previously mapped amounts are retained for comparison and do not add revenue again. In-kind value and fee payments are separate from monetary contributions.</p>{[['byType','Revenue type'],['byMethod','Payment method'],['byDesignation','Designation source ID']].map(([group,label])=><div className="table-wrap" key={group}><table aria-label={`Migration totals by ${label.toLowerCase()}`}><thead><tr><th>{label}</th>{group==='byDesignation'&&<th>Account code</th>}<th className="money">{group==='byDesignation'?'Allocations':'Gifts'}</th><th className="money">Value</th></tr></thead><tbody>{(selected?.[group]||[]).map((r,i)=><tr key={i}><td className="migration-identifier" title={r.sourceId||r.key}>{r.sourceId||r.key}</td>{group==='byDesignation'&&<td>{r.accountCode||'—'}</td>}<td className="money">{r.giftCount??r.allocationCount}</td><td className="money">{money(r.totalCents)}</td></tr>)}{!selected?.[group]?.length&&<tr><td colSpan={group==='byDesignation'?4:3}>No gifts in this scope.</td></tr>}</tbody></table></div>)}</details>;
}

export function BatchLineage({detail,onOpenRecord}) {
 const {batch,lineage=[],integrity={},lineageCoverage}=detail;
 const [page,setPage]=useState(0);
 const lastPage=Math.max(0,Math.ceil(lineage.length/PAGE_SIZE)-1),current=Math.min(page,lastPage),start=current*PAGE_SIZE;
 function exportLineage(){download('wimblo-migration-lineage.csv',toCSV(['Source system','Batch key','Record type','Source ID','Wimblo record ID','Previously mapped','Current status','Original batch ID'],lineage.map(r=>[batch.source,batch.fileKey,r.collection,r.sourceId,r.recordId,r.reused?'Yes':'No',r.status,r.originalBatchId||''])),'text/csv;charset=utf-8');}
 return <div className="migration-lineage"><h3>Source lineage</h3><p>Current records: {integrity.unchanged??0} unchanged · {integrity.changed??0} changed · {integrity.missing??0} missing.</p><p className="subtle">This compares current records with their original imported snapshot. Later edits do not change the saved batch totals. Coverage: {lineageCoverage}.</p><button className="btn btn-secondary" type="button" onClick={exportLineage} disabled={!lineage.length}><Download size={16}/>Download source lineage</button><details><summary>Inspect source files and mappings</summary>{(batch.sourceFiles||[]).map(f=><div key={f.file}><h4>File {f.file}: {f.collection} · {f.rowCount} rows</h4><dl className="reconciliation-summary">{Object.entries(f.mapping||{}).map(([field,column])=><div key={field}><dt>{field}</dt><dd className="migration-identifier" title={column}>{column}</dd></div>)}</dl></div>)}{!batch.sourceFiles?.length&&<p className="subtle">File mappings were not captured for this older batch.</p>}</details><div className="table-wrap"><table className="migration-lineage-desktop" aria-label="Migration source lineage"><thead><tr><th>Record type</th><th>Source ID</th><th>Wimblo record ID</th><th>Current status</th></tr></thead><tbody>{lineage.slice(start,start+PAGE_SIZE).map((r,i)=><tr key={start+i}><td>{r.collection}</td><td className="migration-identifier" title={r.sourceId}>{r.sourceId||'—'}</td><td className="migration-identifier" title={r.recordId}>{onOpenRecord&&r.status!=='Missing'?<button type="button" className="text-btn migration-record-link" title={r.recordId} onClick={()=>onOpenRecord(r.collection,r.recordId)} aria-label={'Open '+r.collection+' source '+r.sourceId}>{r.recordId}</button>:r.recordId||'—'}</td><td>{r.status}</td></tr>)}</tbody></table></div><div className="migration-lineage-mobile" aria-label="Source records">{lineage.slice(start,start+PAGE_SIZE).map((r,i)=><article key={start+i}><h4>{r.sourceId||'—'}</h4><dl><div><dt>Record type</dt><dd>{r.collection}</dd></div><div><dt>Current status</dt><dd>{r.status}</dd></div><div><dt>Wimblo record</dt><dd>{onOpenRecord&&r.status!=='Missing'?<button type="button" className="text-btn migration-record-link" onClick={()=>onOpenRecord(r.collection,r.recordId)} aria-label={'Open '+r.collection+' source '+r.sourceId}>{r.recordId}</button>:r.recordId||'—'}</dd></div></dl></article>)}</div><div className="migration-pagination"><p role="status">{lineage.length?`${start+1}–${Math.min(start+PAGE_SIZE,lineage.length)} of ${lineage.length} source records`:'No source lineage was captured.'}</p><button type="button" className="btn btn-secondary" disabled={current===0} onClick={()=>setPage(current-1)}>Previous sources</button><button type="button" className="btn btn-secondary" disabled={current===lastPage} onClick={()=>setPage(current+1)}>Next sources</button></div></div>;
}
