import {useEffect,useState} from 'react';
import {Upload,Download,CheckCircle2,ArrowRight,RefreshCw,X} from 'lucide-react';
import {download,money,parseCSV,toCSV,dateLabel} from '../lib';

const fields={constituents:['sourceId','name','type','email','phone','household','parentSourceId','segments','preference','notes'],designations:['sourceId','name','accountCode','school','parentSourceId','description'],gifts:['sourceId','donorSourceId','amount','type','method','date','designationSourceId','allocations','externalRef','notes','tribute','softCreditSourceId','giftKind']};
const required={constituents:['sourceId','name','type'],designations:['sourceId','name','accountCode'],gifts:['sourceId','donorSourceId','amount','type','method','date']};
const samples={constituents:[['sample-donor-1','Alex Sample','Individual','alex@example.test','','','','Email','Email','Synthetic demonstration donor']],designations:[['sample-fund-1','Community learning','SAMPLE-100','Sample school','','Synthetic demonstration fund']],gifts:[['sample-gift-1','sample-donor-1','123.45','Cash','Check','2026-09-13','sample-fund-1','','SAMPLE-GIFT-1','Synthetic demonstration gift','','','One-time']]};
export default function Migration({api,user,onCommitted,notify,onDirty}){
 const [source,setSource]=useState('CRM export'),[fileKey,setFileKey]=useState(''),[collection,setCollection]=useState('constituents'),[files,setFiles]=useState([]),[preview,setPreview]=useState(null),[batches,setBatches]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[confirmed,setConfirmed]=useState(false);
 const canImport=user.role==='admin';
 const summary=s=><dl className="reconciliation-summary">{[['Constituent rows',s.constituents],['Designation rows',s.designations],['Gift rows',s.gifts],['New monetary contributions',s.monetaryContributionCents!==undefined?money(s.monetaryContributionCents):undefined],['In-kind noncash value',s.noncashValueCents!==undefined?money(s.noncashValueCents):undefined],['Fee payment value',s.feePaymentCents!==undefined?money(s.feePaymentCents):undefined],['All gift value',s.giftTotalCents!==undefined?money(s.giftTotalCents):undefined],['Allocated value',s.allocationTotalCents!==undefined?money(s.allocationTotalCents):undefined],['Account codes',s.accountCodeCount],['Previously mapped rows',s.reusedRows]].filter(([,v])=>v!==undefined).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>;
 const reconciled=r=><div className="table-wrap"><table aria-label="Committed migration reconciliation"><thead><tr><th>Record type</th><th className="money">Expected new</th><th className="money">Saved new</th></tr></thead><tbody>{['constituents','designations','gifts'].map(c=><tr key={c}><td>{c}</td><td className="money">{r.expectedCreateCounts?.[c]??'—'}</td><td className="money">{r.actualCreateCounts?.[c]??'—'}</td></tr>)}<tr><td>New gift value</td><td className="money">{money(r.expectedNewGiftCents)}</td><td className="money">{money(r.actualNewGiftCents)}</td></tr></tbody></table></div>;
 async function history(){const r=await api('/migration/batches');setBatches(r.batches||[]);}
 useEffect(()=>{if(canImport)history().catch(e=>setError(e.message));},[api,canImport]);
 function invalidate(){setPreview(null);setResult(null);setConfirmed(false);onDirty?.(true);}
 async function addFile(e){const file=e.target.files[0];e.target.value='';if(!file)return;setError('');try{if(file.size>500000)throw new Error('Use CSV files smaller than 500 KB; split larger exports into stable batches.');const rows=parseCSV(await file.text());if(!rows.length||Object.keys(rows[0]).some(h=>!h.trim()))throw new Error('Every CSV column needs a nonempty header.');const headers=Object.keys(rows[0]);const mapping=Object.fromEntries(fields[collection].filter(k=>headers.includes(k)).map(k=>[k,k]));const staged={collection,filename:file.name,headers,mapping,rows};setFiles(p=>p.some(f=>f.collection===collection)?p.map(f=>f.collection===collection?staged:f):[...p,staged]);if(!fileKey)setFileKey(file.name);invalidate();}catch(e){setError(e.message);}}
 function mapField(index,field,value){setFiles(p=>p.map((f,i)=>i===index?{...f,mapping:Object.fromEntries([...Object.entries(f.mapping).filter(([key])=>key!==field),...(value?[[field,value]]:[])])}:f));invalidate();}
 const payload={source:source.trim(),fileKey:fileKey.trim(),files:files.map(({collection,mapping,rows})=>({collection,mapping,rows}))};
 async function validate(e){e.preventDefault();setBusy(true);setError('');setResult(null);setConfirmed(false);try{setPreview(await api('/migration/preview',{method:'POST',body:payload}));}catch(e){setPreview(null);setError(e.message);}finally{setBusy(false);}}
 async function commit(){if(!preview?.valid||!confirmed)return;setBusy(true);setError('');try{const r=await api('/migration/commit',{method:'POST',body:{...payload,previewDigest:preview.previewDigest}});setResult(r);setPreview(null);setConfirmed(false);onDirty?.(false);await history();await onCommitted?.();notify?.('Migration batch saved. Review its reconciliation before continuing.');}catch(e){setPreview(null);setConfirmed(false);setError(e.message+' Preview again. Check batch history before retrying an uncertain commit.');}finally{setBusy(false);}}
 function template(type){download('wimblo-synthetic-'+type+'.csv',toCSV(fields[type],samples[type]),'text/csv;charset=utf-8');}
 if(!canImport)return <section className="panel"><h1>Migration requires administrator access</h1><p>Source mapping and committing conversion batches are restricted to administrators.</p></section>;
 return <section className="migration-workspace"><div className="page-header"><div><h1>Migration</h1><p>Map source records, validate every row, then commit one reconciled batch.</p></div></div>{error&&<p className="error-banner" role="alert">{error}</p>}<div className="workflow-steps" aria-label="Migration workflow"><span><Upload size={16}/>1. Source and mapping</span><ArrowRight size={16}/><span><CheckCircle2 size={16}/>2. Validate and reconcile</span><ArrowRight size={16}/><span>3. Confirm and import</span></div>
 <section className="panel"><h2>Source files</h2><p className="subtle">This release converts constituent, designation and posted-gift CSV records. Historical voids, files, interaction history and provider-specific exports need separate conversion mapping. It does not connect bank or payment accounts.</p><form onSubmit={validate}><fieldset disabled={busy}><div className="form-grid"><label className="field">Source system<input required maxLength={80} value={source} onChange={e=>{setSource(e.target.value);invalidate();}}/><small>Keep this name stable so source IDs resolve across batches.</small></label><label className="field">Stable batch file key<input required maxLength={150} value={fileKey} onChange={e=>{setFileKey(e.target.value);invalidate();}}/><small>Replaying the same file is recognized. Changed content needs a new key.</small></label><label className="field">Record type for the next file<select value={collection} onChange={e=>setCollection(e.target.value)}><option value="constituents">Constituents</option><option value="designations">Designations and account codes</option><option value="gifts">Posted gifts</option></select></label><label className="field">Add or replace CSV file<input type="file" accept=".csv,text/csv" onChange={addFile}/><small>Uploading the same record type replaces its staged file. One file per type, maximum 500 total rows per batch. Amounts are decimal dollars, not cents. IDs must be explicit source IDs.</small></label></div>
 {files.map((f,i)=><div className="migration-file" key={f.collection}><div className="section-title"><h3>{f.filename}</h3><button className="text-btn" type="button" onClick={()=>{setFiles(p=>p.filter((_,j)=>j!==i));invalidate();}}><X size={14}/>Remove file</button></div><p className="subtle">{f.collection} · {f.rows.length} rows. Review every suggested column mapping.</p><div className="mapping-grid">{fields[f.collection].map(field=><label className="field" key={field}>{field}{required[f.collection].includes(field)?' *':''}<select required={required[f.collection].includes(field)} value={f.mapping[field]||''} onChange={e=>mapField(i,field,e.target.value)}><option value="">Not provided</option>{f.headers.map(h=><option key={h}>{h}</option>)}</select></label>)}</div>{f.collection==='gifts'&&<p className="table-note">Map designationSourceId for one allocation, or allocations containing JSON objects with designationSourceId and decimal amount. Allocations must equal the gift amount.</p>}</div>)}
 <div className="form-actions"><button className="btn btn-primary" type="submit" disabled={!files.length}>{busy?'Validating…':'Preview and validate batch'}<ArrowRight size={16}/></button></div></fieldset></form><details className="migration-templates"><summary>Download synthetic CSV examples</summary><p>These examples are fictional. Import all three together using a synthetic source system name; never mix them with customer exports.</p><div className="toolbar">{Object.keys(fields).map(type=><button key={type} className="btn btn-secondary" onClick={()=>template(type)}><Download size={16}/>{type} example</button>)}</div></details></section>
 {preview&&<section className="panel"><h2>Validation and reconciliation</h2><p role="status">{preview.replayed?'This exact batch was already committed. Confirming returns its saved reconciliation without creating duplicates.':preview.valid?'All rows validated. No records have been written.':'This batch has validation errors. Correct the source or mapping before importing.'}</p>{preview.replayed&&<p className="subtle">The totals below describe the original committed batch, not additional revenue.</p>}{summary(preview.summary||{})}<div className="table-wrap"><table aria-label="Migration validation results"><thead><tr><th>Record type</th><th>Source row</th><th>Source ID</th><th>Result</th></tr></thead><tbody>{(preview.rows||[]).map((r,i)=><tr key={i}><td>{r.collection}</td><td className="money">{r.row}</td><td>{r.sourceId||'—'}</td><td>{r.error||r.status}</td></tr>)}</tbody></table></div>{preview.valid&&<><label className="check-field migration-confirm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>I verified source identity mappings, counts, amounts and allocation totals.</label><button className="btn btn-primary" disabled={busy||!confirmed} onClick={commit}>{busy?'Committing…':'Commit validated batch'}</button></>}</section>}
 {result&&<section className="panel"><h2>Batch reconciliation saved</h2><p role="status">{result.replayed?'This exact batch was already committed; no duplicate records were created.':'Records and source mappings were saved atomically.'}</p>{reconciled(result.reconciliation||{})}</section>}
 <section className="panel"><div className="section-title"><h2>Committed batch history</h2><button className="text-btn" disabled={busy} onClick={()=>history().catch(e=>setError(e.message))}><RefreshCw size={16}/>Refresh history</button></div>{batches.length?<div className="table-wrap"><table aria-label="Migration batch history"><thead><tr><th>Source</th><th>File key</th><th>Date</th><th>Reconciliation</th></tr></thead><tbody>{batches.map(b=><tr key={b.id||b.batchId}><td>{b.source}</td><td>{b.fileKey||b.file_key}</td><td>{dateLabel(b.committedAt||b.at||b.createdAt||b.created_at)}</td><td><details><summary>Inspect batch totals</summary>{reconciled(b.reconciliation||{})}</details></td></tr>)}</tbody></table></div>:<p className="subtle">No batches committed. Start with source files above.</p>}</section>
 </section>;
}
