import {useEffect,useState} from 'react';
import {ArrowRight,Plus,CalendarDays,Users,CheckCircle2,ChevronLeft,Download} from 'lucide-react';
import {today,dateLabel,download,toCSV} from '../lib';
import {shiftCounts,duplicateGroups,operationsQueue} from '../phaseFour';
import {Status,Field} from '../components/Fields';
import HelpHint from '../components/HelpHint';
const blank=()=>({name:'',date:today(),startTime:'09:00',endTime:'11:00',location:'',capacity:10,eventId:null,status:'Open',notes:''});
const fields=[{key:'name',label:'Shift name',type:'text',required:true},{key:'date',label:'Shift date',type:'date',required:true},{key:'startTime',label:'Start time',type:'time',required:true},{key:'endTime',label:'End time',type:'time',required:true},{key:'location',label:'Location',type:'text'},{key:'capacity',label:'Places',type:'number',required:true,min:1,max:100000,step:1},{key:'eventId',label:'Related event',type:'reference',collection:'events'},{key:'status',label:'Shift status',type:'select',options:['Open','Closed']},{key:'notes',label:'Shift notes',type:'textarea'}];
export default function Operations({data,onOpen,onNavigate,onAction,onDirty,canWrite,notify}){
 const [tab,setTab]=useState('queue');const [filter,setFilter]=useState('All');const [query,setQuery]=useState('');const [selected,setSelected]=useState(null);const [editor,setEditor]=useState(null);const [draft,setDraft]=useState(blank);const [person,setPerson]=useState('');const [reservationStatus,setReservationStatus]=useState('Reserved');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(editor)document.getElementById('field-name')?.focus();else if(selected)document.getElementById('shift-heading')?.focus();},[editor,selected]);
 const shifts=data.volunteerShifts||[];const reservations=data.shiftReservations||[];const shift=shifts.find(s=>s.id===selected);const counts=shift?shiftCounts(shift,reservations):null;const people=new Map(data.constituents.map(p=>[p.id,p]));const queue=operationsQueue(data);const duplicates=duplicateGroups(data.constituents);
 function startEdit(record=null){if(person&&!window.confirm('Discard the unsaved reservation selection?'))return;setPerson('');setEditor(record||'new');setDraft(record?Object.fromEntries(fields.map(f=>[f.key,record[f.key]])):blank());setError('');setSelected(null);onDirty(false);}
 async function perform(path,body){if(busy)return;setBusy(true);setError('');try{await onAction(path,{method:body.version?'PATCH':'POST',body});notify('Workspace updated.');return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 async function saveShift(e){e.preventDefault();const ok=await perform('/records/volunteerShifts'+(editor==='new'?'':'/'+editor.id),{...draft,...(editor==='new'?{}:{version:editor.version})});if(ok){setEditor(null);onDirty(false);}}
 function changeTab(next){if(busy)return;if((editor||person)&&!window.confirm('Discard unsaved shift changes?'))return;setEditor(null);setPerson('');onDirty(false);setTab(next);setSelected(null);setError('');}
 function showShift(s){setSelected(s.id);setPerson('');setError('');onDirty(false);}
 function openItem(i){i.view?onNavigate(i.view):onOpen(i.collection,i.recordId);}
 const visible=queue.filter(i=>(filter==='All'||i.kind===filter)&&(!query||[i.title,i.reason,i.kind].join(' ').toLowerCase().includes(query.toLowerCase())));
 return <div className="operations-page"><div className="page-header"><div><h1>Operations</h1><p>Find the next action. Keep commitments, people and deadlines connected.</p></div><button className="btn btn-secondary" onClick={()=>onNavigate('testing')}>Test a journey<ArrowRight size={16}/></button></div>
 {!selected&&!editor&&<div className="operations-overview"><div><strong>{queue.filter(i=>i.date<=today()).length}</strong><span>Items through today</span></div><div><strong>{shifts.filter(s=>s.status==='Open'&&s.date>=today()).length}</strong><span>Open upcoming shifts</span></div><div><strong>{duplicates.length}</strong><span>Shared-email groups to review</span></div><HelpHint label="Operations totals" text="These are recorded work items, not automated reminders. A past grant reporting date asks for review because report completion is not tracked. Shared email does not establish a duplicate person."/></div>}
 <div className="operations-tabs" role="tablist" aria-label="Operations workspaces">{[['queue','Work queue'],['shifts','Volunteer shifts'],['quality','Data quality']].map(([key,label])=><button role="tab" id={'ops-tab-'+key} aria-selected={tab===key} tabIndex={tab===key?0:-1} onKeyDown={e=>{const keys=['queue','shifts','quality'];if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=keys[e.key==='Home'?0:e.key==='End'?2:(keys.indexOf(tab)+(e.key==='ArrowRight'?1:2))%3];changeTab(next);document.getElementById('ops-tab-'+next)?.focus();}}} aria-controls={'ops-panel-'+key} key={key} onClick={()=>changeTab(key)}>{label}</button>)}</div>
 {error&&<p className="error-banner" role="alert">{error} Your change has not been saved.</p>}
 <section role="tabpanel" id={'ops-panel-'+tab} aria-labelledby={'ops-tab-'+tab}>
 {tab==='queue'?<section className="panel operations-queue"><div className="toolbar"><label className="field">Find work<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="A task, grant or donor commitment"/></label><label className="field">Work type<select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Task','Grant application','Grant reporting','Pledge','Acknowledgments'].map(v=><option key={v}>{v}</option>)}</select></label><span className="subtle">{visible.length} items</span></div>{visible.length?visible.map(i=><button className="operations-work-row" key={i.id} onClick={()=>openItem(i)}><span><small>{i.kind}</small><strong>{i.title}</strong><span>{i.reason}</span></span><span className="operations-work-date"><strong>{dateLabel(i.date)}</strong><small>{i.timing}</small></span><span className="operations-row-action">{i.action}<ArrowRight size={16}/></span></button>):<div className="operations-empty"><CheckCircle2 size={24}/><h2>No matching work</h2><p>Choose All or clear your search to see other recorded items.</p><button className="btn btn-secondary" onClick={()=>{setFilter('All');setQuery('');}}>Clear filters</button></div>}<p className="table-note">Review source records before acting. This queue does not send messages, confirm submission or collect payments.</p></section>
 :tab==='quality'?<section className="panel"><div className="section-title"><div><h2>Review identity carefully</h2><p className="subtle">Shared email addresses are suggestions for review. People are never merged automatically.</p></div><Users size={20}/></div>{duplicates.length?duplicates.map(g=><div className="quality-group" key={g.email}><strong>{g.email}</strong><span className="subtle">{g.people.length} constituents share this address</span>{g.people.map(p=><button className="operations-work-row" key={p.id} onClick={()=>onOpen('constituents',p.id)}><span><strong>{p.name}</strong><small>{p.type} · {p.household||'No household recorded'}</small></span><span>Review constituent<ArrowRight size={16}/></span></button>)}</div>):<div className="operations-empty"><CheckCircle2 size={24}/><h3>No shared-email groups</h3><p>This exact-email check does not detect all duplicates. Review names, relationships and transaction history before migration.</p><button className="btn btn-secondary" onClick={()=>onNavigate('constituents')}>Review constituents<ArrowRight size={16}/></button></div>}</section>
 :editor?<section className="panel inline-editor"><div className="section-title"><div><h2>{editor==='new'?'Plan a volunteer shift':'Edit volunteer shift'}</h2><p className="subtle">All shifts use the foundation’s shared local scheduling time. Same-day shifts only.</p></div><button className="btn btn-secondary" disabled={busy} onClick={()=>{if(window.confirm('Discard unsaved shift changes?')){setEditor(null);onDirty(false);}}}>Cancel</button></div><form onSubmit={saveShift}><fieldset disabled={busy}><div className="form-grid">{fields.map(f=><Field key={f.key} field={{...f,disabled:editor!=='new'&&reservations.some(r=>r.shiftId===editor.id)&&['date','startTime','endTime','eventId'].includes(f.key),...(f.key==='capacity'&&editor!=='new'?{min:Math.max(1,reservations.filter(r=>r.shiftId===editor.id&&r.status==='Reserved').length)}:{})}} data={data} value={draft[f.key]} onChange={v=>{setDraft(d=>({...d,[f.key]:v}));onDirty(true);}}/>)}</div><p className="subtle">Closing a shift stops new bookings. Existing reservations stay recorded. Date, times and event are protected once reservation history exists.</p><div className="form-actions"><button className="btn btn-primary" type="submit">{busy?'Saving…':'Save shift'}<kbd>⌘ / Ctrl ↵</kbd></button></div></fieldset></form></section>
 :shift?<section className="panel shift-detail"><div className="section-title"><div><button className="text-btn" onClick={()=>{if(person&&!window.confirm('Discard the unsaved reservation selection?'))return;setSelected(null);setPerson('');onDirty(false);setError('');}}><ChevronLeft size={16}/>All shifts</button><h2 id="shift-heading" tabIndex={-1}>{shift.name}</h2><p className="subtle">{dateLabel(shift.date)} · {shift.startTime}–{shift.endTime} · {shift.location||'Venue not recorded'} · foundation local time</p></div>{canWrite&&<button className="btn btn-secondary" disabled={busy} onClick={()=>startEdit(shift)}>Edit shift</button>}</div><div className="shift-capacity"><div><strong>{counts.reserved} / {shift.capacity}</strong><span>Reserved places</span></div><div><strong>{counts.available}</strong><span>Places available</span></div><div><strong>{counts.waitlisted}</strong><span>Waitlisted</span></div><Status value={shift.status}/></div>{shift.eventId&&<button className="text-btn" onClick={()=>onOpen('events',shift.eventId)}>Open related event<ArrowRight size={16}/></button>}{canWrite&&shift.status==='Open'&&<form className="shift-booking" onSubmit={async e=>{e.preventDefault();if(await perform('/records/shiftReservations',{shiftId:shift.id,constituentId:person,status:reservationStatus,notes:''})){setPerson('');onDirty(false);}}}><h3>Add a person</h3><p className="subtle">Reserve a place or add to the waitlist. Reservation does not create attendance or volunteer hours.</p><fieldset disabled={busy}><label className="field">Constituent<select value={person} onChange={e=>{setPerson(e.target.value);onDirty(!!e.target.value);}} required><option value="">Choose a person</option>{data.constituents.filter(p=>['Individual','Alumni','Employee'].includes(p.type)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field">Place type<select value={reservationStatus} onChange={e=>setReservationStatus(e.target.value)}><option>Reserved</option><option>Waitlisted</option></select></label><button className="btn btn-primary" type="submit">{busy?'Saving…':'Add reservation'}</button></fieldset></form>}
 <div className="section-title"><h3>Reservation history</h3><button className="btn btn-secondary btn-small" onClick={()=>download('kinflect-shift-roster-'+today()+'.csv',toCSV(['Shift','Date','Start local','End local','Person','Status'],counts.rows.map(r=>[shift.name,shift.date,shift.startTime,shift.endTime,people.get(r.constituentId)?.name||'Unknown constituent',r.status])),'text/csv;charset=utf-8')}><Download size={16}/>Roster CSV</button></div>{counts.rows.length?counts.rows.map(r=><div className="reservation-row" key={r.id}><button className="record-link" onClick={()=>onOpen('constituents',r.constituentId)}>{people.get(r.constituentId)?.name||'Unknown constituent'}</button><Status value={r.status}/><div>{canWrite&&r.status==='Waitlisted'&&shift.status==='Open'&&<button className="btn btn-secondary btn-small" disabled={busy||counts.available===0} onClick={()=>perform('/records/shiftReservations/'+r.id,{version:r.version,status:'Reserved'})}>Reserve available place</button>}{canWrite&&r.status!=='Cancelled'&&<button className="btn btn-secondary btn-small" disabled={busy} onClick={()=>perform('/records/shiftReservations/'+r.id,{version:r.version,status:'Cancelled'})}>Cancel reservation</button>}</div></div>):<div className="operations-empty"><Users size={24}/><h3>No reservations yet</h3><p>{canWrite?'Choose a person above to reserve the first place.':'Staff can reserve places and manage this roster.'}</p></div>}<p className="table-note">Cancellation retains history and releases capacity. Waitlisted people are promoted only by an explicit staff action. Bookings do not send reminders, create clock entries or change event guest registration.</p></section>
 :<section className="panel"><div className="section-title"><div><h2>Volunteer shifts</h2><p className="subtle">Plan a venue, time and capacity. Then build a roster.</p></div>{canWrite&&<button className="btn btn-primary" onClick={()=>startEdit()}><Plus size={16}/>Plan a shift</button>}</div>{shifts.length?[...shifts].sort((a,b)=>a.date.localeCompare(b.date)||a.startTime.localeCompare(b.startTime)).map(s=>{const n=shiftCounts(s,reservations);return <button className="operations-work-row" key={s.id} onClick={()=>showShift(s)}><span><strong>{s.name}</strong><small>{dateLabel(s.date)} · {s.startTime}–{s.endTime} · {s.location||'Venue not recorded'}</small></span><span className="shift-list-count"><strong>{n.reserved} / {s.capacity}</strong><small>{n.available} places available · {n.waitlisted} waitlisted</small></span><Status value={s.status}/><ArrowRight size={16}/></button>}):<div className="operations-empty"><CalendarDays size={28}/><h3>Start with one well-planned shift</h3><p>Set the local times and number of places. Staff can reserve volunteers, manage a waitlist and open connected constituent history.</p>{canWrite&&<button className="btn btn-primary" onClick={()=>startEdit()}>Plan the first shift<ArrowRight size={16}/></button>}</div>}</section>}
 </section></div>;
}
