import React,{useEffect,useRef,useState} from 'react';
import {RefreshCw,ArrowUpRight,Plus} from 'lucide-react';
import {money,cents,dateLabel} from '../lib.js';
const none=[];
const initial=()=>({title:'',campaignId:'',constituentId:'',coordinatorId:'',goal:'',visibility:'Workspace'});
const utc=value=>value?new Date(value).toISOString().replace('T',' ').replace('Z',' UTC'):'—';
const dollars=value=>(BigInt(value??0)/100n).toString()+'.'+String(BigInt(value??0)%100n).padStart(2,'0');
export default function PeerFundraising({api,user,data,onDirty,onOpen,onCommitted,onRefreshSources}){
 const allowed=['admin','staff','viewer'].includes(user?.role),writable=['admin','staff'].includes(user?.role);
 const campaigns=data?.campaigns||none,people=data?.constituents||none,gifts=data?.gifts||none,owners=data?.taskOwners||none;
 const [records,setRecords]=useState([]),[next,setNext]=useState(null),[detail,setDetail]=useState(null),[draft,setDraft]=useState(initial),[editing,setEditing]=useState(false),[review,setReview]=useState(null),[confirmed,setConfirmed]=useState(false),[giftId,setGiftId]=useState(''),[reason,setReason]=useState(''),[operation,setOperation]=useState(null),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const alive=useRef(true),generation=useRef(0),working=useRef(false),loaded=useRef(false),job=useRef(0),sourceBaseline=useRef(null);
 const selected=detail?.fundraiser&&(user?.role==='admin'||detail.fundraiser.visibility==='Workspace')?detail.fundraiser:null;
 const visibleRecords=records.filter(r=>user?.role==='admin'||r.visibility==='Workspace');
 const dirty=Boolean(draft.title||draft.campaignId||draft.constituentId||draft.coordinatorId||draft.goal||giftId||reason||operation);
 useEffect(()=>{onDirty?.(dirty);},[dirty,onDirty]);useEffect(()=>()=>onDirty?.(false),[onDirty]);
 const invalidate=()=>{setReview(null);setConfirmed(false);};
 const clear=()=>{setDraft(initial());setEditing(false);setGiftId('');setReason('');setOperation(null);invalidate();};
 useEffect(()=>{const signature=JSON.stringify([campaigns,people,gifts,owners].map(records=>records.map(r=>[r.id,r.version]).sort((a,b)=>String(a[0]).localeCompare(String(b[0])))));if(signature===sourceBaseline.current)return;sourceBaseline.current=signature;generation.current++;invalidate();if(loaded.current){setBlocked(true);setNotice('Source records changed. Save or discard inputs, refresh workspace sources, reopen the plan, then inspect current history.');}},[campaigns,people,gifts,owners]);
 const current=epoch=>alive.current&&epoch===generation.current;
 async function read(path,epoch){try{const result=await api(path);return current(epoch)?result:null;}catch(e){if(current(epoch)&&[401,403,404].includes(e.status)){setDetail(null);setRecords([]);setBlocked(true);}throw e;}}
 async function load(id=selected?.id,after=null){const epoch=++generation.current;const [list,saved]=await Promise.all([read('/peer-fundraisers?limit=100'+(after?'&after='+encodeURIComponent(after):''),epoch),id?read('/peer-fundraisers/'+id+'?limit=100',epoch):Promise.resolve(null)]);if(!current(epoch)||!list)return;setRecords(old=>after?[...old,...list.fundraisers.filter(r=>!old.some(x=>x.id===r.id))]:list.fundraisers);setNext(list.nextCursor);setDetail(saved);setBlocked(false);loaded.current=true;return true;}
 async function perform(fn){if(working.current)return;const task=++job.current;working.current=true;setBusy(true);setError('');let epoch=generation.current;try{const pending=fn();epoch=generation.current;await pending;}catch(e){if(current(epoch)){setError(e.message);invalidate();}}finally{if(task===job.current){working.current=false;if(alive.current)setBusy(false);}}}
 useEffect(()=>{alive.current=true;working.current=false;clear();setDetail(null);setRecords([]);loaded.current=false;if(allowed)perform(()=>load(null));return()=>{alive.current=false;generation.current++;job.current++;working.current=false;};},[api,allowed,user?.id,user?.role]);
 const change=patch=>{setDraft(old=>({...old,...patch}));invalidate();};
 const campaign=campaigns.find(c=>c.id===(editing?selected?.campaignId:draft.campaignId)),person=people.find(p=>p.id===(editing?selected?.constituentId:draft.constituentId)),coordinator=owners.find(o=>o.id===draft.coordinatorId),sourceOwner=owners.find(o=>o.id===selected?.coordinatorId);
 function reviewPlan(){setError('');try{if(!campaign||!person||!coordinator||campaign.type!=='Peer-to-peer'||campaign.status!=='Active')throw new Error('Choose an active peer-to-peer campaign, existing fundraiser and active staff coordinator.');const goalCents=cents(draft.goal);if(!draft.title.trim())throw new Error('Give this fundraiser plan a title.');setReview(editing?{version:selected.version,title:draft.title.trim(),goalCents,visibility:draft.visibility,coordinatorId:coordinator.id,coordinatorVersion:coordinator.version,reason:reason.trim()}:{campaignId:campaign.id,campaignVersion:campaign.version,constituentId:person.id,constituentVersion:person.version,coordinatorId:coordinator.id,coordinatorVersion:coordinator.version,title:draft.title.trim(),goalCents,visibility:draft.visibility});setConfirmed(false);}catch(e){setError(e.message);invalidate();}}
 async function commit(path,body,message){if(working.current)return;const task=++job.current;working.current=true;setBusy(true);setError('');setNotice('');const epoch=generation.current;let saved=false;try{const result=await api(path,{method:editing&&path==='/peer-fundraisers/'+selected?.id?'PATCH':'POST',body});saved=true;if(!current(epoch))return;clear();setDetail({fundraiser:result.fundraiser,attributions:[],history:[],revisions:[],attributionCount:null,historyCount:null,revisionCount:null});setRecords(old=>[result.fundraiser,...old.filter(r=>r.id!==result.fundraiser.id)]);setNotice(message);const syncEpoch=generation.current+1;let refreshed=false;try{refreshed=await load(result.fundraiser.id);}catch{if(current(syncEpoch)){setBlocked(true);setError('Your change was saved, but history could not refresh. Reload saved history before further changes.');}}if(refreshed&&current(syncEpoch))Promise.resolve(onCommitted?.()).catch(()=>{if(current(syncEpoch)){setBlocked(true);setError('Your change was saved, but workspace records could not refresh. Reload before further changes.');}});}catch(e){if(current(epoch)){invalidate();setBlocked(true);setError(saved?'Your change was saved. Reload saved history before further changes.':e.status?'The change was not accepted: '+e.message+' Reload saved history before retrying. If source versions changed, discard inputs and refresh workspace sources, then reopen the plan.':'The response was not confirmed. Inspect saved history before retrying; this screen will not repeat the change automatically.');}}finally{if(task===job.current){working.current=false;if(alive.current)setBusy(false);}}}
 async function inspect(id){await perform(async()=>{const epoch=++generation.current;const result=await read('/peer-fundraisers/'+id+'?limit=100',epoch);if(result){setDetail(result);clear();setBlocked(false);setNotice('');}});}
 async function moreAttributions(){await perform(async()=>{const epoch=++generation.current,result=await read('/peer-fundraisers/'+selected.id+'?limit=100&after='+encodeURIComponent(detail.nextCursor),epoch);if(result){if(result.fundraiser.version!==selected.version){setBlocked(true);setError('This fundraiser changed between pages. Reload saved history to inspect one current version.');return;}setDetail(old=>({...result,attributions:[...old.attributions,...result.attributions.filter(a=>!old.attributions.some(x=>x.id===a.id))]}));}});}
 const existing=new Set((detail?.attributions||[]).filter(a=>a.status==='Active').map(a=>a.giftId));
 const candidates=gifts.filter(g=>g.status==='Posted'&&g.type==='Cash'&&g.method!=='In-kind'&&g.giftKind==='One-time'&&g.date<=new Date().toISOString().slice(0,10)&&g.campaignId===selected?.campaignId&&!g.pledgeId&&!g.grantId&&!existing.has(g.id));
 const gift=gifts.find(g=>g.id===giftId),attribution=detail?.attributions.find(a=>a.id===operation?.id),unlinkGift=gifts.find(g=>g.id===attribution?.giftId);
 const active=selected?.status==='Active'&&selected.campaignStatus==='Active'&&selected.coordinatorAvailable;
 function openSource(collection,id,version){if(!onOpen)return;perform(async()=>{await onOpen(collection,id,version);});}
 if(!allowed)return <section className="panel"><h1>Peer fundraising</h1><p>Your role cannot access fundraiser plans.</p></section>;
 return <div className="peer-fundraising"><div className="page-header"><div><h1>Peer fundraising</h1><p>Give each fundraiser a clear plan. Credit existing gifts without changing the donor or recording them twice.</p></div><div className="header-actions"><button type="button" className="btn btn-secondary" disabled={busy||dirty||!onRefreshSources} onClick={()=>{if(!busy&&!dirty)onRefreshSources?.();}}>Refresh workspace sources</button><button type="button" className="btn btn-secondary" disabled={busy||dirty} onClick={()=>perform(()=>load())}><RefreshCw size={16}/>Refresh saved history</button></div></div>
 <p className="scope-banner">Fundraisers introduce support; donors make gifts. Goals are aspirations. Progress uses compatible existing posted cash contributions through today, including all fiscal years. Attribution creates no income, receipt, public fundraising page or payment collection.</p>
 {error&&<div className="error-banner" role="alert"><p>{error}</p>{blocked&&<button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>{clear();perform(()=>load());}}>Discard inputs and reload saved history</button>}</div>}{notice&&<p role="status" className="table-note">{notice}</p>}{blocked&&!error&&<button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>{clear();perform(()=>load());}}>Discard inputs and reload saved history</button>}
 <section className="panel"><div className="section-title"><div><h2>Fundraiser register</h2><p>Open a plan to inspect its source gifts, responsibilities and retained history.</p></div>{writable&&<button type="button" className="btn btn-secondary" disabled={busy||dirty||blocked} onClick={()=>{setDetail(null);clear();}}><Plus size={16}/>New fundraiser plan</button>}</div>{visibleRecords.length?<div className="table-wrap"><table className="peer-register" aria-label="Peer fundraiser plans"><thead><tr><th scope="col">Plan / fundraiser</th><th scope="col">Campaign</th><th scope="col">Coordinator</th><th scope="col">Status</th><th scope="col" className="money">Goal</th><th scope="col" className="money">Posted cash</th></tr></thead><tbody>{visibleRecords.map(r=><tr key={r.id}><td><button type="button" className="record-link peer-plan-title" title={r.title} disabled={busy||dirty} onClick={()=>inspect(r.id)}>{r.title}</button><small className="cell-detail peer-fundraiser-name" title={r.fundraiserName}>{r.fundraiserName} · v{r.version}</small></td><td>{r.campaignName}</td><td>{r.coordinatorName}{!r.coordinatorAvailable&&<small className="cell-detail">Needs staff reassignment</small>}</td><td>{r.status}</td><td className="money">{money(r.goalCents)}</td><td className="money">{money(r.progress.postedCashCents)}</td></tr>)}</tbody></table></div>:<div className="empty-state"><h3>No fundraiser plans yet</h3><p>{writable?'Start with an existing Active Peer-to-peer campaign and a known constituent. Create those records first if they are not available.':'Staff can create a plan. Private administrator plans are omitted from your register.'}</p></div>}{next&&<button type="button" className="btn btn-secondary" disabled={busy||dirty} onClick={()=>perform(()=>load(selected?.id,next))}>Load more fundraiser plans</button>}</section>
 {writable&&(!selected||editing)&&<section className="panel"><div className="section-title"><div><h2>{editing?'Revise fundraiser plan':'Create fundraiser plan'}</h2><p>{editing?'Campaign and fundraiser stay fixed. Every revision retains its reason.':'Choose the campaign and person, then review the goal and responsibility before saving.'}</p></div></div><form onSubmit={e=>{e.preventDefault();if(review&&confirmed&&!blocked)return commit(editing?'/peer-fundraisers/'+selected.id:'/peer-fundraisers',review,'Fundraiser plan saved. No gift or payment was created.');}}><fieldset disabled={busy||blocked}><div className="form-grid">
 <label className="field">Plan title<input required maxLength={250} value={draft.title} onChange={e=>change({title:e.target.value})} placeholder="Community champion plan"/></label>
 <label className="field">Peer-to-peer campaign<select required disabled={editing} value={editing?selected.campaignId:draft.campaignId} onChange={e=>change({campaignId:e.target.value})}><option value="">Choose an active campaign</option>{campaigns.filter(c=>c.type==='Peer-to-peer'&&c.status==='Active'||editing&&c.id===selected.campaignId).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><small>Only Active Peer-to-peer campaigns accept new plans.</small></label>
 <label className="field">Fundraiser constituent<select required disabled={editing} value={editing?selected.constituentId:draft.constituentId} onChange={e=>change({constituentId:e.target.value})}><option value="">Choose an existing constituent</option>{people.filter(p=>!p.mergedInto).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><small>The fundraiser introduces support and is not necessarily the gift’s actual donor.</small></label>
 <label className="field">Staff coordinator<select required value={draft.coordinatorId} onChange={e=>change({coordinatorId:e.target.value})}><option value="">Choose active staff</option>{owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><small>This assigns responsibility, not account access or notifications.</small></label>
 <label className="field">Fundraiser goal · USD<input required inputMode="decimal" value={draft.goal} onChange={e=>change({goal:e.target.value})} placeholder="2500.00"/><small>A goal is not money received or an amount owed.</small></label>
 <label className="field">Plan visibility<select value={draft.visibility} onChange={e=>change({visibility:e.target.value})}><option disabled={editing&&selected?.visibility==='Administrators'}>Workspace</option>{user.role==='admin'&&<option>Administrators</option>}</select><small>Workspace plans can be read by board viewers. Administrator-only history stays private; it cannot later become Workspace-visible.</small></label>
 {editing&&<label className="field field-wide">Reason for plan revision<textarea required maxLength={2000} rows={2} value={reason} onChange={e=>{setReason(e.target.value);invalidate();}}/></label>}</div>
 <div className="form-actions"><button type="button" className="btn btn-secondary" disabled={busy||editing&&!reason.trim()} onClick={reviewPlan}>Review fundraiser plan</button><button type="button" className="text-btn" onClick={clear}>Cancel plan inputs</button></div>
 {review&&<div className="peer-review"><h3>Confirm this plan</h3><dl><div><dt>Fundraiser</dt><dd>{person?.name}</dd></div><div><dt>Campaign</dt><dd>{campaign?.name} · v{campaign?.version}</dd></div><div><dt>Coordinator</dt><dd>{coordinator?.name} · v{coordinator?.version}</dd></div><div><dt>Goal</dt><dd>{money(review.goalCents)} · {review.visibility}</dd></div></dl><label className="peer-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the source records, goal and visibility. This saves a plan, not a payment.</label></div>}
 <div className="form-actions"><span className="subtle">{review?'Confirm the reviewed plan before saving.':'Review is required before saving.'}</span><button type="submit" className="btn btn-primary" disabled={busy||!review||!confirmed||blocked}>{editing?'Save reasoned revision':'Save fundraiser plan'}</button></div></fieldset></form></section>}
 {selected&&<><section className="panel"><div className="section-title"><div><h2>{selected.title}</h2><p>{selected.fundraiserName} · {selected.campaignName} · {selected.visibility} · {selected.status} · v{selected.version}</p></div>{writable&&selected.status==='Active'&&<button type="button" className="btn btn-secondary" disabled={busy||dirty||blocked} onClick={()=>{setEditing(true);setDraft({title:selected.title,campaignId:selected.campaignId,constituentId:selected.constituentId,coordinatorId:selected.coordinatorId,goal:dollars(selected.goalCents),visibility:selected.visibility});invalidate();}}>Revise plan</button>}</div><dl className="peer-progress"><div><dt>Posted cash through {dateLabel(selected.progress.asOf)}</dt><dd>{money(selected.progress.postedCashCents)}</dd></div><div><dt>Fundraiser goal</dt><dd>{money(selected.goalCents)}</dd></div><div><dt>Contributing gifts</dt><dd>{selected.progress.attributedGiftCount}</dd></div></dl><p className="table-note">Coordinator: {selected.coordinatorName}{selected.coordinatorAvailable?'':' · unavailable; staff reassignment required'}. {selected.progress.sourceChangedCount} source changes to review · {selected.progress.voidedGiftCount} voided gifts · {selected.progress.unlinkedCount} unlinked. Compatible source changes can still contribute; history never counts as a second receipt.</p><div className="form-actions"><button type="button" className="text-btn" disabled={busy||dirty||!onOpen} onClick={()=>openSource('constituents',selected.constituentId,selected.constituentVersion)}>Open fundraiser<ArrowUpRight size={16}/></button><button type="button" className="text-btn" disabled={busy||dirty||!onOpen} onClick={()=>openSource('campaigns',selected.campaignId,selected.campaignVersion)}>Open campaign<ArrowUpRight size={16}/></button></div></section>
 <section className="panel"><div className="section-title"><div><h2>Attributed source gifts</h2><p>Actual donors stay on their original gifts. Attribution credits introduction, not additional revenue.</p></div><span className="subtle">{detail.attributionCount==null?'Saved history awaiting refresh':(detail.attributions?.length||0)+' of '+detail.attributionCount}</span></div>{detail.attributions?.length?<div className="table-wrap"><table aria-label="Fundraiser gift attribution history"><thead><tr><th scope="col">Actual donor / gift</th><th scope="col">Attribution</th><th scope="col">Current source</th><th scope="col" className="money">Original gift value</th><th scope="col" className="money">Current value</th><th scope="col">Action / reason</th></tr></thead><tbody>{detail.attributions.map(a=><tr key={a.id}><td><button type="button" className="record-link" disabled={busy||dirty||!onOpen} onClick={()=>openSource('gifts',a.giftId,a.currentSource?.giftVersion)}>{a.currentSource?.donorName||'Source unavailable'}</button><small className="cell-detail">{a.giftId} · original v{a.giftVersion}</small></td><td>{a.status} · v{a.version}</td><td>{a.currentSource?.status||'Unavailable'}{a.currentSource?.sourceCurrent===false?' · source changed':''}<small className="cell-detail">{a.currentSource?.date?dateLabel(a.currentSource.date):'—'} · current v{a.currentSource?.giftVersion??'—'}</small></td><td className="money">{money(a.originalSource.amountCents)}</td><td className="money">{a.currentSource?money(a.currentSource.amountCents):'—'}</td><td>{a.status==='Active'&&writable?<button type="button" className="text-btn" disabled={busy||dirty||blocked} onClick={()=>{setOperation({type:'unlink',id:a.id});setReason('');setConfirmed(false);}}>Unlink with reason</button>:a.unlinkReason||'—'}</td></tr>)}</tbody></table></div>:<p className="empty-state">{detail.attributionCount==null?'Reload saved history to verify attributed gifts.':'No source gifts are attributed. The goal alone contributes no received money.'}</p>}{detail.nextCursor&&<button type="button" className="btn btn-secondary" disabled={busy||dirty||blocked} onClick={moreAttributions}>Load more source gifts</button>}
 {writable&&active&&!editing&&!operation&&<form onSubmit={e=>{e.preventDefault();if(gift&&reason.trim()&&confirmed&&sourceOwner)return commit('/peer-fundraisers/'+selected.id+'/attributions',{version:selected.version,giftId:gift.id,giftVersion:gift.version,campaignVersion:campaigns.find(c=>c.id===selected.campaignId)?.version,coordinatorVersion:sourceOwner.version,reason:reason.trim()},'Existing gift attributed. The donor, allocations and received income were unchanged.');}}><fieldset disabled={busy||blocked}><div className="form-grid"><label className="field">Candidate existing gift<select required value={giftId} onChange={e=>{setGiftId(e.target.value);setConfirmed(false);}}><option value="">Choose posted cash contribution</option>{candidates.map(g=><option value={g.id} key={g.id}>{people.find(p=>p.id===g.constituentId)?.name||'Donor'} · {g.date} · {money(g.amount)} · {g.id}</option>)}</select><small>One-time cash, matching campaign, through today. Saving also verifies allocations, attribution conflicts and event exchange classifications.</small></label><label className="field">Reason for fundraiser attribution<textarea required maxLength={2000} rows={2} value={reason} onChange={e=>{setReason(e.target.value);setConfirmed(false);}}/></label></div>{gift&&<p className="peer-source-review">Actual donor: <strong>{people.find(p=>p.id===gift.constituentId)?.name||'Donor'}</strong> · {money(gift.amount)} · source v{gift.version}. Fundraiser credit: <strong>{selected.fundraiserName}</strong>. This does not change who gave the gift.</p>}<label className="peer-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this existing gift and the attribution reason. No new income is recorded.</label><div className="form-actions"><button type="button" className="text-btn" onClick={()=>{setGiftId('');setReason('');setConfirmed(false);}}>Cancel attribution inputs</button><button type="submit" className="btn btn-primary" disabled={!gift||!reason.trim()||!confirmed||!sourceOwner||busy||blocked}>Attribute existing gift</button></div></fieldset></form>}
 {writable&&!active&&selected.status==='Active'&&<p className="scope-banner">New attribution is unavailable while the campaign or staff coordinator is inactive. Existing source history remains retained.</p>}
 {writable&&operation&&<form onSubmit={e=>{e.preventDefault();if(!confirmed||!reason.trim()||blocked)return;if(operation.type==='unlink'&&unlinkGift)return commit('/peer-fundraisers/'+selected.id+'/attributions/'+attribution.id+'/unlink',{version:selected.version,attributionVersion:attribution.version,giftVersion:unlinkGift.version,reason:reason.trim()},'Attribution unlinked. Its source and reason remain in history; no gift was voided.');if(operation.type==='retire')return commit('/peer-fundraisers/'+selected.id+'/retire',{version:selected.version,reason:reason.trim()},'Fundraiser plan retired. Existing attributed gifts and history remain retained.');}}><fieldset disabled={busy||blocked}><h3>{operation.type==='unlink'?'Unlink this attribution':'Retire fundraiser plan'}</h3><p>{operation.type==='unlink'?'Only this fundraiser credit is removed. The original gift and donor remain unchanged.':'Retirement stops new attribution. It does not erase historical gifts or progress.'}</p><label className="field">Reason for {operation.type==='unlink'?'unlinking':'retirement'}<textarea required rows={2} maxLength={2000} value={reason} onChange={e=>{setReason(e.target.value);setConfirmed(false);}}/></label><label className="peer-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the retained source history and this reason.</label><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={()=>{setOperation(null);setReason('');setConfirmed(false);}}>Cancel reasoned change</button><button type="submit" className="btn btn-primary" disabled={!confirmed||!reason.trim()||busy||blocked||operation.type==='unlink'&&!unlinkGift}>{operation.type==='unlink'?'Unlink and retain history':'Retire and retain history'}</button></div></fieldset></form>}</section>
 <section className="panel"><div className="section-title"><div><h2>Retained plan history</h2><p>Latest {detail.historyLimit||100} actions and revisions. Dates describe recorded changes, not delivery or receipts.</p></div>{writable&&selected.status==='Active'&&<button type="button" className="btn btn-secondary" disabled={busy||dirty||blocked} onClick={()=>{setOperation({type:'retire'});setReason('');setConfirmed(false);}}>Retire with reason</button>}</div>{detail.history?.length?<ol className="peer-history">{detail.history.map(h=><li key={h.id}><strong>{h.action||h.status||'Recorded change'}</strong><p>{h.reason||'Initial recorded plan'}</p><small>{utc(h.at)} · {h.actorName||h.actorId||(typeof h.actor==='string'?h.actor:h.actor?.name)||'Recorded staff'} · attribution v{h.attributionVersion??h.version??'—'}</small></li>)}</ol>:<p className="empty-state">{detail.historyCount==null?'Reload saved history to verify recorded actions.':'No attribution action history returned.'}</p>}<details className="peer-revisions"><summary>Inspect retained plan revisions · {detail.revisionCount==null?'awaiting refresh':(detail.revisions?.length||0)+' of '+detail.revisionCount}</summary>{detail.revisions?.map(r=><div key={r.version}><h3>Version {r.version} · {r.title}</h3><p>{r.reason}</p><p className="table-note">{r.status} · {r.visibility} · goal {money(r.goalCents)} · coordinator {owners.find(o=>o.id===r.coordinatorId)?.name||r.coordinatorId} · saved {utc(r.at)}</p><p className="table-note">Source revisions: {(r.sourceVersions||[]).map(ref=>ref.collection+' '+ref.id+' v'+ref.version).join(' · ')||'—'}</p></div>)}</details><p className="table-note">{detail.historyCount==null||detail.revisionCount==null?'Reload saved history to verify counts.':detail.historyCount+' retained attribution actions · '+detail.revisionCount+' retained plan revisions.'}</p></section></>}
 </div>;
}
