import React,{useEffect,useRef,useState} from 'react';
import {Building2,Plus,ArrowLeft,LogOut,ShieldCheck} from 'lucide-react';
import Brand from '../components/Brand';

const emptyTenant={name:'',slug:'',plan:'trial',dataMode:'restricted',admin:{name:'',email:'',password:''}};
export default function PlatformAdmin(){
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tenants,setTenants]=useState([]),[audit,setAudit]=useState([]),[showCreate,setShowCreate]=useState(false),[draft,setDraft]=useState(emptyTenant),[editing,setEditing]=useState(null),[login,setLogin]=useState({email:'',password:''});
 const token=useRef('');const createInput=useRef(null);const editSelect=useRef(null);
 async function request(path,{method='GET',body}={}){const response=await fetch('/api/platform'+path,{method,credentials:'same-origin',headers:{...(body?{'Content-Type':'application/json'}:{}),...(method!=='GET'?{'X-CSRF-Token':token.current}:{})},...(body?{body:JSON.stringify(body)}:{})});const payload=await response.json().catch(()=>({error:'The platform service returned an unreadable response.'}));if(!response.ok){const e=new Error(payload.error||'This platform action could not be completed.');e.status=response.status;if(e.status===401&&session){setSession(null);token.current='';setTenants([]);setAudit([]);}throw e;}if(payload.csrfToken)token.current=payload.csrfToken;return payload;}
 async function load(){const result=await request('/tenants');setTenants(result.tenants||[]);setAudit(result.audit||[]);}
 useEffect(()=>{document.title='Platform administration · Wimblo';request('/auth/me').then(async result=>{setSession(result.user);await load();}).catch(e=>{if(e.status!==401)setError(e.message);}).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(showCreate)createInput.current?.focus();},[showCreate]);useEffect(()=>{if(editing)editSelect.current?.focus();},[editing?.id]);
 async function signIn(e){e.preventDefault();setError('');setBusy(true);try{const result=await request('/auth/login',{method:'POST',body:login});setSession(result.user);setLogin({email:'',password:''});await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function create(e){e.preventDefault();setError('');setNotice('');setBusy(true);try{await request('/tenants',{method:'POST',body:draft});setDraft(emptyTenant);setShowCreate(false);await load();setNotice('Organization created. Its administrator can sign in using the workspace ID.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(e){e.preventDefault();setError('');setNotice('');setBusy(true);try{await request('/tenants/'+editing.id,{method:'PATCH',body:{version:editing.version,status:editing.status,plan:editing.plan,aiEnabled:editing.aiEnabled}});setEditing(null);await load();setNotice('Organization controls saved. Access and AI policy take effect immediately.');}catch(e){if(e.status===409)await load().catch(()=>{});setError(e.message);}finally{setBusy(false);}}
 async function signOut(){setBusy(true);setError('');try{await request('/auth/logout',{method:'POST'});setSession(null);setTenants([]);setAudit([]);token.current='';setEditing(null);setShowCreate(false);setNotice('');}catch(e){setError(e.message);}finally{setBusy(false);}}
 const alerts=<>{error&&<div className="error-banner" role="alert">{error}</div>}{notice&&<p className="platform-notice" role="status">{notice}</p>}</>;
 if(loading)return <main className="fatal-state" role="status"><h1>Opening platform administration…</h1></main>;
 if(!session)return <main className="platform-login"><div className="platform-brand"><Brand/></div><section className="panel"><h1>Platform administration</h1><p>Manage organization accounts and subscription access. Organization staff sign in to their own workspace.</p>{alerts}<form onSubmit={signIn}><label className="field">Platform administrator email<input type="email" autoComplete="username" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label className="field">Password<input type="password" autoComplete="current-password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><button className="btn btn-primary" disabled={busy}>{busy?'Signing in…':'Sign in to platform'}</button></form><p className="table-note">Platform accounts are configured separately. Workspace administrator credentials do not grant platform access.</p><a className="platform-back" href="/"><ArrowLeft size={16}/>Open Wimblo workspace</a></section></main>;
 return <main className="platform-console"><header className="platform-header"><div className="platform-brand"><Brand/></div><div><span>{session.name}</span><button className="btn btn-secondary" disabled={busy} onClick={signOut}><LogOut size={16}/>Sign out of platform</button></div></header><div className="page-header"><div><h1>Organization accounts</h1><p>Control workspace access, plan classification and AI availability.</p></div><button className="btn btn-primary" disabled={busy} onClick={()=>{setShowCreate(v=>!v);setError('');}}><Plus size={16}/>{showCreate?'Close new organization':'Create organization'}</button></div>{alerts}<section className="platform-scope"><ShieldCheck size={16}/><p>Platform administration controls accounts. It does not grant access to donor records or impersonate organization users.</p></section><div className="platform-metrics"><div><span>Organizations</span><strong>{tenants.length}</strong></div><div><span>Active</span><strong>{tenants.filter(t=>t.status==='active').length}</strong></div><div><span>Suspended</span><strong>{tenants.filter(t=>t.status==='suspended').length}</strong></div></div>
 {showCreate&&<section className="panel platform-editor"><h2>Create organization</h2><p className="subtle">Create an isolated workspace and its initial administrator. Share credentials through your approved secure process.</p><form onSubmit={create}><fieldset disabled={busy}><div className="form-grid"><label className="field">Organization name<input ref={createInput} required maxLength={250} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="field">Workspace ID<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" minLength={3} maxLength={63} value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value})}/><small>Lowercase letters, numbers and hyphens. Users enter this ID at sign-in.</small></label><label className="field">Plan<select value={draft.plan} onChange={e=>setDraft({...draft,plan:e.target.value})}><option value="trial">Trial</option><option value="subscription">Subscription</option><option value="dedicated">Dedicated</option></select></label><label className="field">Data environment<select value={draft.dataMode} onChange={e=>setDraft({...draft,dataMode:e.target.value})}><option value="restricted">Restricted records</option><option value="synthetic">Synthetic testing only</option></select><small>AI record assistance is available only for explicitly synthetic workspaces in this release.</small></label><label className="field">Initial administrator name<input required maxLength={250} value={draft.admin.name} onChange={e=>setDraft({...draft,admin:{...draft.admin,name:e.target.value}})}/></label><label className="field">Initial administrator email<input type="email" required autoComplete="off" maxLength={254} value={draft.admin.email} onChange={e=>setDraft({...draft,admin:{...draft.admin,email:e.target.value}})}/></label><label className="field field-wide">Initial administrator password<input type="password" required minLength={16} maxLength={200} autoComplete="new-password" value={draft.admin.password} onChange={e=>setDraft({...draft,admin:{...draft.admin,password:e.target.value}})}/><small>At least 16 characters, including uppercase, lowercase, a number and a symbol.</small></label></div><div className="form-actions"><button className="btn btn-primary" type="submit">{busy?'Creating…':'Create isolated workspace'}</button><button className="btn btn-secondary" type="button" onClick={()=>{setShowCreate(false);setDraft(emptyTenant);}}>Cancel</button></div></fieldset></form></section>}
 <section className="panel"><div className="section-title"><h2>Workspaces</h2><button className="btn btn-secondary" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh organizations</button></div><div className="table-wrap"><table className="platform-table"><thead><tr><th>Organization</th><th>Workspace ID</th><th>Plan</th><th>Status</th><th>AI</th><th>Controls</th></tr></thead><tbody>{tenants.map(t=><tr key={t.id}><td><strong>{t.name}</strong><small className="cell-detail">{t.dataMode==='synthetic'?'Synthetic testing':'Restricted records'}</small></td><td>{t.slug}</td><td>{t.plan}</td><td>{t.status}</td><td>{t.aiEnabled?'Enabled':'Disabled'}</td><td><button className="btn btn-secondary btn-small" disabled={busy} onClick={()=>{setEditing({...t});setError('');}} aria-label={'Manage '+t.name}>Manage</button></td></tr>)}</tbody></table></div>{!tenants.length&&<div className="empty-state"><Building2 size={24}/><h3>No organizations yet</h3><p>Create the first isolated workspace above.</p></div>}<p className="table-note">Plan classifications are administrative labels. Automatic billing, invoices, payment collection and subscription renewals are not connected.</p></section>
 {editing&&<section className="panel platform-editor"><h2>Manage {editing.name}</h2><p>Suspension blocks workspace access immediately and retains its records. AI access is controlled separately from user roles.</p><form onSubmit={save}><fieldset disabled={busy}><div className="form-grid"><label className="field">Workspace status<select ref={editSelect} value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option value="active">Active</option><option value="suspended">Suspended</option></select></label><label className="field">Workspace plan<select value={editing.plan} onChange={e=>setEditing({...editing,plan:e.target.value})}><option value="trial">Trial</option><option value="subscription">Subscription</option><option value="dedicated">Dedicated</option></select></label><label className="field">AI access<select value={String(!!editing.aiEnabled)} onChange={e=>setEditing({...editing,aiEnabled:e.target.value==='true'})}><option value="false">Disabled</option><option value="true">Enabled</option></select><small>Restricted-record assistance remains blocked pending privacy and permission controls.</small></label></div><div className="form-actions"><button className="btn btn-primary" type="submit">{busy?'Saving…':'Save organization controls'}</button><button className="btn btn-secondary" type="button" onClick={()=>setEditing(null)}>Cancel</button></div></fieldset></form></section>}
 {audit.length>0&&<section className="panel"><div className="section-title"><h2>Platform activity</h2></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Action</th><th>Organization</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{new Date(a.at).toLocaleString()}</td><td>{a.action.replaceAll('_',' ')}</td><td>{tenants.find(t=>t.id===(a.tenantId||a.tenant_id))?.name||'Platform'}</td></tr>)}</tbody></table></div></section>}<footer className="platform-footer"><a href="/">Open Wimblo workspace</a><span>Wimblo · Platform administration</span></footer></main>;
}
