import { useId, useMemo, useState } from 'react';
import { CalendarDays, Plus, Search } from 'lucide-react';
import { dateLabel, money, nameOf, today } from '../lib';
import { pledgeSchedule } from '../phaseTwo';

export default function Pledges({ data, onCreate, onOpen, canWrite }) {
  const prefix = useId();
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('All');
  const pledges = useMemo(() => (data.pledges || []).map(pledge => ({ pledge, schedule: pledgeSchedule(pledge, data.gifts, today()), donor: nameOf(data, 'constituents', pledge.constituentId) })), [data]);
  const rows = pledges.filter(({ pledge, donor }) => (status === 'All' || pledge.status === status) && `${pledge.name} ${donor} ${pledge.notes}`.toLowerCase().includes(query.trim().toLowerCase()));
  const active = pledges.filter(({ pledge }) => pledge.status === 'Active');
  return <section aria-labelledby={`${prefix}-title`}>
    <div className="page-header"><div><h1 id={`${prefix}-title`}>Pledges</h1><p>Track commitments, installment schedules and actual gifts received.</p></div>{canWrite && <button className="btn btn-primary" onClick={onCreate}><Plus size={16} aria-hidden="true" /> New pledge</button>}</div>
    <div className="summary-strip"><div><span>Active commitments</span><strong>{money(active.reduce((total, row) => total + row.pledge.amount, 0))}</strong></div><div><span>Received against active pledges</span><strong>{money(active.reduce((total, row) => total + row.schedule.received, 0))}</strong></div><div><span>Outstanding active balance</span><strong>{money(active.reduce((total, row) => total + row.schedule.balance, 0))}</strong></div><div><span>Overdue through {dateLabel(today())}</span><strong>{money(active.reduce((total, row) => total + row.schedule.overdue, 0))}</strong></div></div>
    <div className="panel"><div className="toolbar"><label className="search-control" htmlFor={`${prefix}-search`}><Search size={16} aria-hidden="true" /><span className="sr-only">Search pledges or donors</span><input id={`${prefix}-search`} type="search" placeholder="Search pledges or donors" value={query} onChange={event => setQuery(event.target.value)} /></label><div className="filter-control"><label className="sr-only" htmlFor={`${prefix}-status`}>Pledge status</label><select id={`${prefix}-status`} value={status} onChange={event => setStatus(event.target.value)}>{['All', 'Active', 'Paused', 'Cancelled'].map(value => <option key={value} value={value}>{value === 'All' ? 'All statuses' : value}</option>)}</select></div><span className="record-count" role="status">{rows.length} {rows.length === 1 ? 'pledge' : 'pledges'}</span></div>
      {rows.length ? <div className="table-wrap"><table><caption>Scheduled commitments are separate from received income. Open a pledge for its installment schedule.</caption><thead><tr>{['Pledge', 'Donor', 'Commitment', 'Received', 'Balance', 'Overdue', 'Schedule', 'Status'].map(header => <th key={header} scope="col" className={['Commitment', 'Received', 'Balance', 'Overdue'].includes(header) ? 'money' : undefined}>{header}</th>)}</tr></thead><tbody>{rows.map(({ pledge, schedule, donor }) => <tr key={pledge.id}><td><button className="record-link" onClick={() => onOpen(pledge)}>{pledge.name}</button></td><td>{donor}</td><td className="money">{money(pledge.amount)}</td><td className="money">{money(schedule.received)}</td><td className="money">{money(schedule.balance)}</td><td className="money">{money(schedule.overdue)}</td><td>{pledge.installments} {pledge.frequency.toLowerCase()}<br /><span className="subtle">From {dateLabel(pledge.startDate)}</span></td><td><span className={`badge ${pledge.status === 'Active' ? 'badge-positive' : 'badge-muted'}`}>{pledge.status}</span></td></tr>)}</tbody></table></div> : <div className="empty-state"><CalendarDays size={30} aria-hidden="true" /><h3>{pledges.length ? 'No matching pledges' : 'Record your first commitment'}</h3><p>{pledges.length ? 'Try another donor name or status.' : 'Create a pledge schedule, then link actual monetary gifts as they are received.'}</p></div>}
      <p className="table-note">Only posted monetary gifts linked to a pledge reduce its balance. Voided gifts, in-kind value and fees do not fulfill commitments.</p>
    </div>
  </section>;
}
