import React,{useState} from 'react';
import {Search,Plus,Download,Upload,Users,Target,ArrowUpRight} from 'lucide-react';
import {MODULES} from '../schema';
import {effectiveSchoolYear,money,dateLabel,nameOf,designationPath,postedGifts,contributedGifts,sum,download,toCSV,match} from '../lib';
import {Status,Progress} from '../components/Fields';
import DataTable from '../components/DataTable';
import ImportGifts from './ImportGifts';
import {matchesGiftScope} from '../dashboardData';
import {campaignProgress} from '../campaignData';
export function columnsFor(collection,data,{asOf=new Date().toISOString().slice(0,10)}={}){
 const nameColumn={key:'name',label:'Name',render:r=>r.name};
 const dateColumn=(key,label)=>({key,label,mobilePriority:2,render:r=>dateLabel(r[key])});
 const amountColumn=(key,label)=>({key,label,money:true,mobilePriority:1,render:r=>money(r[key])});
 const statusColumn=(key,label)=>({key,label,render:r=><Status value={r[key]}/>});
 const constituentColumn={key:'constituentId',label:'Constituent',mobilePriority:0,sort:r=>nameOf(data,'constituents',r.constituentId),render:r=>nameOf(data,'constituents',r.constituentId)};
 if(collection==='constituents')return [nameColumn,{key:'type',label:'Type'},{key:'email',label:'Email'},{key:'segments',label:'Segments'},statusColumn('preference','Contact preference')];
 if(collection==='gifts')return [{...constituentColumn,label:'Donor'},{key:'allocations',label:'Designation',sort:r=>r.allocations.length,render:r=>r.allocations.length>1?`${r.allocations.length} funds · split gift`:nameOf(data,'designations',r.allocations[0]?.designationId)},statusColumn('type','Revenue type'),dateColumn('date','Gift date'),amountColumn('amount','Value'),statusColumn('status','Status')];
 if(collection==='campaigns'){const progress=new Map(data.campaigns.map(r=>[r.id,campaignProgress(data.gifts,{campaignId:r.id,goalCents:r.goal,asOf})]));return [nameColumn,{key:'type',label:'Type'},amountColumn('goal','Goal'),{key:'progress',label:'Progress',sort:r=>progress.get(r.id).currentAmountCents,render:r=>{const p=progress.get(r.id);return <div><div className="table-progress"><Progress value={p.progressPercent} label={r.name}/><span>{Math.round(p.progressPercent)}%</span></div><small className="cell-detail">{money(p.currentAmountCents)} recorded through {dateLabel(asOf)}</small>{p.futureGifts.length>0&&<small className="cell-detail">{money(p.futureAmountCents)} future-dated · not raised</small>}</div>;}},dateColumn('endDate','End date'),statusColumn('status','Status')];}
 if(collection==='grants')return [nameColumn,{key:'funderId',label:'Funder',render:r=>nameOf(data,'constituents',r.funderId)},statusColumn('stage','Stage'),dateColumn('deadline','Application due'),dateColumn('reportDue','Report due'),amountColumn('amount','Value')];
 if(collection==='volunteers')return [constituentColumn,{key:'skills',label:'Skills'},{key:'shift',label:'Shift'},{key:'eventId',label:'Event',render:r=>nameOf(data,'events',r.eventId)},{key:'hours',label:'Hours',money:true,mobilePriority:1,render:r=>Number(r.hours||0).toFixed(2)},{key:'clockIn',label:'Time status',render:r=><Status value={r.clockIn?'Clocked in':'Not clocked in'}/>}];
 if(collection==='events')return [nameColumn,dateColumn('date','Event date'),{key:'location',label:'Location'},{key:'capacity',label:'Registration',render:r=>`${r.registrations.length} / ${r.capacity}`},amountColumn('ticketPrice','Ticket price'),{key:'checkedIn',label:'Checked in',money:true,render:r=>r.registrations.filter(a=>a.checkedIn).length}];
 if(collection==='tasks')return [{key:'title',label:'Task'},dateColumn('dueDate','Due date'),{key:'owner',label:'Assigned to',render:r=><span>{r.owner||'Unassigned'}<small className="cell-detail">{r.ownerStatus||(!r.ownerId&&r.owner?'Legacy label':'')}</small></span>},statusColumn('priority','Priority'),statusColumn('status','Status')];
 if(collection==='communications')return [{key:'subject',label:'Subject'},constituentColumn,{key:'channel',label:'Channel'},dateColumn('date','Date'),statusColumn('status','Status')];
 return [nameColumn,{key:'school',label:'School / department'},{key:'parentId',label:'Parent designation',render:r=>nameOf(data,'designations',r.parentId)},{key:'accountCode',label:'Account code'},{key:'value',label:'Posted gift value',money:true,render:r=>money(sum(postedGifts(data.gifts).flatMap(g=>g.allocations).filter(a=>a.designationId===r.id)))}];
}
export default function Records({collection,data,onCreate,onOpen,onImport,canWrite,notify,scope,onClearScope}){
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('All');const [showImport,setShowImport]=useState(false);
 const schema=MODULES[collection];const filterKey=collection==='gifts'?'type':collection==='constituents'?'type':collection==='grants'?'stage':['campaigns','tasks','communications'].includes(collection)?'status':null;
 const filterOptions=filterKey?[...new Set(data[collection].map(r=>r[filterKey]))]:[];
 const rows=data[collection].filter(r=>(collection!=='gifts'||matchesGiftScope(r,scope||{}))&&match({...r,relatedName:nameOf(data,'constituents',r.constituentId),designation:collection==='gifts'?r.allocations.map(a=>designationPath(data,a.designationId)).join(' '):''},query)&&(filter==='All'||r[filterKey]===filter));
 const asOf=new Date().toISOString().slice(0,10);
 const columns=columnsFor(collection,data,{asOf});
 function exportRecords(){const headers=columns.filter(c=>!['progress','clockIn','value','checkedIn'].includes(c.key));const values=rows.map(r=>headers.map(c=>{const key=c.key;if(['constituentId','funderId','parentId','eventId'].includes(key))return nameOf(data,key==='eventId'?'events':key==='parentId'&&collection==='designations'?'designations':'constituents',r[key]);if(key==='allocations')return r.allocations.map(a=>`${designationPath(data,a.designationId)} (${money(a.amount)})`).join('; ');if(c.money)return money(r[key]);return r[key]??'';}));download(`${collection}-export.csv`,toCSV(headers.map(c=>c.label),values),'text/csv;charset=utf-8');notify('Exported '+rows.length+' records.');}
 return <><div className="page-header"><div><h1>{schema.title}</h1><p>{schema.description}</p></div><div className="header-actions"><button className="btn btn-secondary" onClick={exportRecords} disabled={!rows.length}><Download size={16}/>Export CSV</button>{collection==='gifts'&&canWrite&&<button className="btn btn-secondary" onClick={()=>setShowImport(!showImport)}><Upload size={16}/>Import gifts</button>}{canWrite&&<button className="btn btn-primary" onClick={()=>onCreate(collection)}><Plus size={16}/>{collection==='gifts'?'Record a gift':'New '+schema.singular}<kbd>C</kbd></button>}</div></div>{collection==='gifts'&&<div className="summary-strip"><div><span>Monetary contributions</span><strong>{money(sum(contributedGifts(rows)))}</strong></div><div><span>In-kind support</span><strong>{money(sum(postedGifts(rows).filter(g=>g.type==='In-kind')))}</strong></div><div><span>Fee payments</span><strong>{money(sum(postedGifts(rows).filter(g=>g.type==='Fee payment')))}</strong></div><div><span>Voided records</span><strong>{rows.filter(g=>g.status==='Voided').length}</strong></div></div>}{showImport&&<ImportGifts data={data} onImport={onImport} onClose={()=>setShowImport(false)}/>}<section className="panel records-panel">{collection==='campaigns'&&<p className="table-note">Progress includes lifetime posted monetary contributions through {dateLabel(asOf)}, across all school years. Future-dated gifts, fees, in-kind support and voids are excluded. Campaign dates describe the plan; source gift dates and history remain unchanged.</p>}{(scope?.month||scope?.schoolYear)&&<div className="scope-banner"><span>Dashboard selection{scope.schoolYear?' · Assigned year '+scope.schoolYear:''}{scope.month?' · Transaction month '+scope.month:''}{scope.asOf?' · Through '+dateLabel(scope.asOf):''}{scope.futureAfter?' · Future dates after '+dateLabel(scope.futureAfter):''}{scope.contributionsOnly?' · Monetary contributions only':''}</span><button className="text-btn" onClick={onClearScope}>Clear dashboard filters</button></div>}<div className="toolbar"><label className="search-control"><Search size={17}/><span className="sr-only">Search {schema.title.toLowerCase()}</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={'Search '+schema.title.toLowerCase()}/></label>{filterKey&&<label className="filter-control"><span className="sr-only">Filter {schema.title.toLowerCase()}</span><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option>{filterOptions.map(o=><option key={o}>{o}</option>)}</select></label>}<span className="record-count">{rows.length} {schema.title.toLowerCase()}</span></div><DataTable key={collection} columns={columns} rows={rows} label={schema.title} onOpen={r=>onOpen(collection,r.id)}/></section>{collection==='communications'&&<div className="workspace-footnote">Drafts and interaction logs only. No email or text messages are sent from this workspace.</div>}</>;
}
