import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Bell,RefreshCw,Clock,ArrowUpRight} from 'lucide-react';
import {localReminderInput,reminderUtc} from '../reminderTime.js';
const time=value=>value?new Date(value).toLocaleString():'—';
export default function Reminders({api,user,data,taskOwners=[],onDirty,onOpen,onCommitted}){
 const editable=['admin','staff'].includes(user?.role),owner=taskOwners.find(o=>o.id===user?.id);
 const tasks=useMemo(()=>(data?.tasks||[]).filter(t=>t.ownerId===user?.id&&t.status!=='Completed'),[data?.tasks,user?.id]);
 const [taskId,setTaskId]=useState(''),[when,setWhen]=useState(()=>localReminderInput(new Date(Date.now()+15*60000))),[reminders,setReminders]=useState([]),[items,setItems]=useState([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dirty,setDirty]=useState(false),[cancelId,setCancelId]=useState(null),[reason,setReason]=useState(''),[detail,setDetail]=useState(null);
 const alive=useRef(true),generation=useRef(0),task=tasks.find(t=>t.id===taskId);
 useEffect(()=>{onDirty?.(dirty||Boolean(reason));},[dirty,reason,onDirty]);
 useEffect(()=>{alive.current=true;if(editable)reload();else setLoading(false);return()=>{alive.current=false;generation.current++;};},[api,editable]);
 async function reload(){const request=++generation.current;setLoading(true);try{const [r,i]=await Promise.all([api('/task-reminders'),api('/reminder-inbox')]);if(!alive.current||request!==generation.current)return;setReminders(r.reminders);setItems(i.items);}catch(e){if(alive.current&&request===generation.current){setReminders([]);setItems([]);setError(e.message);}}finally{if(alive.current&&request===generation.current)setLoading(false);}}
 const perform=async action=>{setBusy(true);setError('');setNotice('');try{await action();}catch(e){if(alive.current){setError(e.message+' Refresh reminders and current task ownership before retrying.');await reload();}}finally{if(alive.current)setBusy(false);}};
 const schedule=()=>perform(async()=>{if(!task||!owner)throw new Error('Choose a task currently assigned to your active staff account.');const remindAt=reminderUtc(when);const r=await api('/tasks/'+task.id+'/reminders',{method:'POST',body:{taskVersion:task.version,ownerVersion:owner.version,remindAt}});if(!alive.current)return;setDirty(false);setNotice('Reminder saved for '+time(r.reminder.remindAt)+'. It appears in your internal inbox only while its source remains valid.');await reload();await onCommitted?.();});
 const readHistory=reminder=>perform(async()=>{const r=await api('/task-reminders/'+reminder.id);if(alive.current)setDetail(r);});
 const cancel=reminder=>perform(async()=>{await api('/task-reminders/'+reminder.id+'/cancel',{method:'POST',body:{version:reminder.version,reason:reason.trim()}});if(!alive.current)return;setCancelId(null);setReason('');setNotice('Reminder cancelled. Its dated history remains retained.');await reload();});
 let utc='';try{utc=reminderUtc(when);}catch{}
 const zone=Intl.DateTimeFormat().resolvedOptions().timeZone,activeReminder=reminders.find(r=>r.taskId===taskId&&r.status==='Active');
 return <><div className="page-header"><div><h1>My reminders</h1><p>A personal inbox for work assigned to you.</p></div>{editable&&<button className="btn btn-secondary" type="button" disabled={busy||loading} onClick={reload}><RefreshCw size={15}/>Refresh reminders</button>}</div>
 <p className="scope-banner">One-shot internal reminders run while the workspace server is running. No email, push notification or external message is sent. Completed, reassigned or changed source tasks and changed account access suppress stale reminders; restored access never reactivates them.</p>
 {error&&<p className="error-banner" role="alert">{error}</p>}{notice&&<p className="subtle" role="status">{notice}</p>}
 {!editable?<section className="panel"><h2>Staff-owned work</h2><p>Reminders belong to active staff task owners. Your current role can review ordinary tasks but cannot schedule or inspect a staff member’s personal inbox.</p></section>:<>
 <section className="panel"><div className="section-title"><div><h2>Your inbox</h2><p>Current-source reminders appear here after their saved time. Refresh to inspect new items.</p></div><Bell size={18}/></div>{loading?<p role="status">Loading your reminders…</p>:items.length?<div className="reminder-inbox">{items.map(item=><article key={item.id} className="reminder-inbox-item"><div><h3>{item.taskTitle||'Assigned task'}</h3><p className="subtle">Produced {time(item.deliveredAt)}</p></div><button className="btn btn-secondary" type="button" disabled={busy} onClick={()=>onOpen?.('tasks',item.taskId)}>Open task<ArrowUpRight size={15}/></button></article>)}</div>:<p className="empty-state">No current reminders in your inbox. Schedule one below for a task you own.</p>}</section>
 <section className="panel"><div className="section-title"><div><h2>Set a reminder</h2><p>Choose your task and confirm its exact time before saving.</p></div><Clock size={18}/></div><form onSubmit={e=>{e.preventDefault();schedule();}}><fieldset disabled={busy||loading||!owner}><div className="form-grid"><label className="field">Your active task<select required value={taskId} onChange={e=>{setTaskId(e.target.value);setDirty(true);}}><option value="">Choose an assigned task</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title} · v{t.version}</option>)}</select><small>Only your noncompleted tasks are available. Legacy owner labels need an explicit staff assignment.</small></label><label className="field">Reminder time · {zone}<input required type="datetime-local" value={when} onChange={e=>{setWhen(e.target.value);setDirty(true);}}/><small>{utc?'Saved UTC instant: '+utc:'Choose a valid local calendar time.'}</small></label></div><div className="toolbar" aria-label="Reminder time shortcuts">{[[1,'In 1 minute'],[15,'In 15 minutes'],[60,'In 1 hour']].map(([minutes,label])=><button key={minutes} type="button" className="btn btn-secondary btn-small" onClick={()=>{setWhen(localReminderInput(new Date(Date.now()+minutes*60000)));setDirty(true);}}>{label}</button>)}</div><p className="subtle">One active reminder per task. To change its time, cancel it with a reason and create another. Changes to the captured task or account revision require a new reminder.</p>{activeReminder&&<p className="scope-banner" role="status">This task already has an active reminder. Inspect or cancel it in Saved reminders before choosing a new time.</p>}<div className="form-actions"><span className="subtle">{task?'Task v'+task.version+' · Your account v'+owner?.version:'No recipients are selected automatically.'}</span><button type="submit" className="btn btn-primary" disabled={!task||!utc||busy||!owner||Boolean(activeReminder)}>Save my reminder</button></div></fieldset></form>{!tasks.length&&<p className="scope-banner">No active tasks are assigned to you. Open Tasks to create work with an explicit staff owner.</p>}</section>
 <section className="panel"><div className="section-title"><div><h2>Saved reminders and outcomes</h2><p>Retained status explains delivery, suppression, cancellation and retries. Historical entries are not additional notifications.</p></div></div>{loading?<p role="status">Loading retained history…</p>:reminders.length?<div className="table-wrap"><table className="reminder-history" aria-label="My saved task reminders"><thead><tr><th scope="col">Task / source</th><th scope="col">Saved time</th><th scope="col">Status</th><th scope="col">Outcome</th><th scope="col">Action</th></tr></thead><tbody>{reminders.map(r=><tr key={r.id}><td data-label="Task / source"><button type="button" className="record-link" disabled={busy} onClick={()=>readHistory(r)}>{r.taskTitle||'Retained task reference'}</button><small className="subtle reminder-reference">{r.taskId}</small></td><td data-label="Saved time">{time(r.remindAt)}</td><td data-label="Status">{r.status}</td><td data-label="Outcome">{r.lastOutcome?r.lastOutcome.status+' · '+r.lastOutcome.reason:'Pending'}</td><td data-label="Action">{r.status==='Active'?<button type="button" className="text-btn" disabled={busy||dirty||Boolean(reason)} onClick={()=>{setCancelId(r.id);setReason('');}}>Cancel reminder</button>:'—'}</td></tr>)}</tbody></table></div>:<p className="empty-state">You have no saved reminders yet.</p>}
 {detail&&<section className="reminder-detail"><h3>Reminder outcome history</h3><p className="subtle">{detail.reminder.taskId} · {detail.outcomeCount} retained outcomes; showing up to {detail.outcomeLimit}.</p>{detail.outcomes.map(o=><p key={o.id}><strong>{o.status}</strong> · {time(o.at)} · {o.reason}{o.retryAt?' · Retry '+time(o.retryAt):''}</p>)}<button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>setDetail(null)}>Close outcome history</button></section>}
 {cancelId&&<form onSubmit={e=>{e.preventDefault();const r=reminders.find(r=>r.id===cancelId);if(r)cancel(r);}}><fieldset disabled={busy}><label className="field">Cancellation reason<input required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="form-actions"><button className="btn btn-secondary" type="button" onClick={()=>{setCancelId(null);setReason('');}}>Keep reminder</button><button type="submit" className="btn btn-primary" disabled={!reason.trim()||busy}>Confirm reminder cancellation</button></div></fieldset></form>}
 <p className="table-note">Your inbox is private to your current task-owner access. Administrators do not automatically gain another user’s inbox. Suspension terminally suppresses pending schedules, including future ones.</p></section></>}
 </>;
}
