import {useEffect,useState} from 'react';
import {CalendarClock,RefreshCw,Download,ArrowUpRight} from 'lucide-react';
import {download,toCSV,money} from '../lib';
const utc=v=>new Date(v).toLocaleString('en-US',{timeZone:'UTC'})+' UTC';
const firstRun=()=>{const d=new Date(Date.now()+300000);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);};
export default function ReportSchedules({api,user,notify,onNavigate,onDirty}){
 const [schedules,setSchedules]=useState([]),[deliveries,setDeliveries]=useState([]),[reports,setReports]=useState([]),[draft,setDraft]=useState({name:'',reportId:'',cadence:'Daily',startAt:firstRun()}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[loading,setLoading]=useState(true);
 const [retiring,setRetiring]=useState(null),[retirementReason,setRetirementReason]=useState('');
 const canWrite=['admin','staff'].includes(user.role);
 async function load(){const results=await Promise.all([api('/report-schedules'),api('/report-deliveries'),api('/custom-reports')]);setSchedules(results[0].schedules);setDeliveries(results[1].deliveries);setReports(results[2].reports);}
 useEffect(()=>{let live=true;load().catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false;};},[api]);
 function change(k,v){setDraft(p=>({...p,[k]:v}));onDirty?.(true);}
 async function create(e){e.preventDefault();setBusy(true);setError('');try{await api('/report-schedules',{method:'POST',body:{...draft,startAt:new Date(draft.startAt).toISOString()}});setDraft({name:'',reportId:'',cadence:'Daily',startAt:firstRun()});onDirty?.(false);await load();notify?.('Internal report schedule saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function toggle(s){setBusy(true);setError('');try{await api('/report-schedules/'+s.id,{method:'PATCH',body:{version:s.version,status:s.status==='Active'?'Paused':'Active'}});await load();notify?.('Report schedule updated.');}catch(e){setError(e.message);await load().catch(()=>{});}finally{setBusy(false);}}
 function beginRetirement(s){setRetiring(s);setRetirementReason('');setError('');onDirty?.(true);}
 function cancelRetirement(){setRetiring(null);setRetirementReason('');onDirty?.(Boolean(draft.name||draft.reportId));}
 async function retire(e){e.preventDefault();setBusy(true);setError('');try{await api('/report-schedules/'+retiring.id,{method:'PATCH',body:{version:retiring.version,status:'Retired',reason:retirementReason.trim()}});cancelRetirement();notify?.('Schedule retired. Saved deliveries remain available.');try{await load();}catch(e){setError('Schedule retired, but the list could not refresh. Use Refresh deliveries. '+e.message);}}catch(e){setError(e.message+' If the schedule changed, choose Keep schedule and reopen retirement from the refreshed list.');await load().catch(()=>{});}finally{setBusy(false);}}
 async function open(d){setBusy(true);setError('');try{setResult((await api('/report-deliveries/'+d.id)).delivery);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const cell=(v,c)=>v===null||v===undefined?'—':c.unit==='cents'?money(v):typeof v==='object'?JSON.stringify(v):String(v);
 function exportResult(){const r=result.result;download('wimblo-scheduled-report.csv',toCSV(r.columns.map(c=>c.label),r.rows.map(row=>r.columns.map((c,i)=>cell(Array.isArray(row)?row[i]:row[c.key],c)))),'text/csv;charset=utf-8');}
 return <section><div className="page-header"><div><h1>Scheduled reports</h1><p>Produce saved reports into the workspace on an hourly, daily or weekly schedule.</p></div><button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}><RefreshCw size={16}/>Refresh deliveries</button></div>{error&&<p className="error-banner" role="alert">{error}</p>}<p className="scope-banner">Delivery is internal. The workspace server checks every 30 seconds while running. A missed schedule produces one catch-up result after restart; this does not send email. Paused organizations do not generate scheduled reports.</p>
 {canWrite&&<section className="panel"><h2>Create an internal schedule</h2>{!reports.length&&!loading?<div className="empty-state"><CalendarClock size={24}/><h3>Save a report first</h3><p>A schedule reruns a saved report definition against current records.</p><button type="button" className="btn btn-primary" onClick={()=>onNavigate('custom-reports')}>Open report builder<ArrowUpRight size={16}/></button></div>:<form onSubmit={create}><fieldset disabled={busy||Boolean(retiring)||!reports.length}><div className="form-grid"><label className="field">Schedule name<input required maxLength={250} value={draft.name} onChange={e=>change('name',e.target.value)}/></label><label className="field">Saved report<select required value={draft.reportId} onChange={e=>change('reportId',e.target.value)}><option value="">Choose a saved report</option>{reports.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="field">Frequency<select value={draft.cadence} onChange={e=>change('cadence',e.target.value)}>{['Hourly','Daily','Weekly'].map(c=><option key={c}>{c}</option>)}</select></label><label className="field">First run, your local time<input type="datetime-local" required value={draft.startAt} onChange={e=>change('startAt',e.target.value)}/><small>Stored in UTC; daily cadence is every 24 hours. Review daylight-saving changes.</small></label></div><div className="form-actions"><button className="btn btn-primary" type="submit">{busy?'Saving…':'Save report schedule'}</button></div></fieldset></form>}</section>}
 {retiring&&<section className="panel" aria-labelledby="retirement-heading"><h2 id="retirement-heading">Retire {retiring.name}</h2><p className="subtle" id="retirement-guide">This permanently stops this schedule and frees a schedule slot. Saved deliveries remain available with their existing access controls. To schedule this report again, create a new schedule.</p><form onSubmit={retire}><fieldset disabled={busy}><label className="field">Reason for retiring<textarea required maxLength={500} autoFocus aria-describedby="retirement-guide" value={retirementReason} onChange={e=>setRetirementReason(e.target.value)}/></label><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={cancelRetirement}>Keep schedule</button><button type="submit" className="btn btn-primary" disabled={!retirementReason.trim()}>{busy?'Retiring…':'Confirm retirement'}</button></div></fieldset></form></section>}
 <section className="panel"><h2>Report schedules</h2><p className="subtle">Up to 100 active or paused schedules. Pause to resume later; retire to stop permanently and retain delivery history.</p>{loading?<p role="status">Loading schedules…</p>:schedules.length?<div className="table-wrap"><table aria-label="Saved report schedules"><thead><tr><th scope="col">Schedule</th><th scope="col">Owner</th><th scope="col">Frequency</th><th scope="col">Next run</th><th scope="col">Status</th><th scope="col">Control</th></tr></thead><tbody>{schedules.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.ownerName}</td><td>{s.cadence}</td><td>{s.status==='Retired'?'—':utc(s.nextRun)}</td><td>{s.status}</td><td>{canWrite&&(user.role==='admin'||s.ownerId===user.id)?s.status==='Retired'?<span className="subtle">History retained</span>:<><button type="button" className="text-btn" disabled={busy||Boolean(retiring)} title={s.status==='Active'?'Stop new deliveries until you resume. Saved deliveries stay available.':'Resume internal deliveries; a missed run produces one catch-up result.'} onClick={()=>toggle(s)}>{s.status==='Active'?'Pause':'Resume'} schedule</button>{' '}<button type="button" className="text-btn" disabled={busy||Boolean(retiring)} title="Permanently stop this schedule and free its slot. Saved deliveries stay available." onClick={()=>beginRetirement(s)}>Retire schedule</button></>:'—'}</td></tr>)}</tbody></table></div>:<p className="subtle">No schedules created.</p>}</section>
 <section className="panel"><h2>Internal deliveries</h2>{deliveries.length?<div className="table-wrap"><table aria-label="Produced report deliveries"><thead><tr><th scope="col">Report</th><th scope="col">Scheduled</th><th scope="col">Produced</th><th scope="col">Result</th><th scope="col">Open</th></tr></thead><tbody>{deliveries.map(d=><tr key={d.id}><td>{d.name}<small className="cell-detail">Report definition version {d.reportVersion??'—'}</small></td><td>{utc(d.scheduledAt)}</td><td>{utc(d.executedAt)}</td><td>{d.status}{d.error&&<small className="cell-detail">{d.error}</small>}</td><td><button type="button" className="text-btn" disabled={busy} onClick={()=>open(d)}>Inspect delivery</button></td></tr>)}</tbody></table></div>:<p className="subtle">No results produced yet. Due schedules run while the server is available.</p>}</section>
 {result&&<section className="panel"><div className="section-title"><div><h2>{result.name}</h2><p className="subtle">Saved result produced {utc(result.executedAt)}. This snapshot does not change when the source records change.</p></div><button type="button" className="text-btn" onClick={()=>setResult(null)}>Close result</button></div>{result.error&&<p className="error-banner" role="alert">{result.error}</p>}{result.result&&<><button type="button" className="btn btn-secondary" onClick={exportResult}><Download size={16}/>Export saved CSV</button><p className="table-note">{result.result.matchedRows} source rows matched{result.result.truncated?' · Result truncated; narrow the report before relying on totals.':''}.</p><div className="table-wrap"><table aria-label="Scheduled report result"><thead><tr>{result.result.columns.map(c=><th scope="col" key={c.key} className={c.unit==='cents'?'money':undefined}>{c.label}</th>)}</tr></thead><tbody>{result.result.rows.map((r,i)=><tr key={i}>{result.result.columns.map((c,j)=><td key={c.key} className={c.unit==='cents'?'money':undefined}>{cell(Array.isArray(r)?r[j]:r[c.key],c)}</td>)}</tr>)}</tbody></table></div></>}</section>}
 </section>;
}
