import React,{useEffect,useMemo,useState} from 'react';
import {Plus,Save,CheckCircle2,Download} from 'lucide-react';
import {api as defaultApi} from '../api.js';
import {download,money,today} from '../lib.js';

const empty=()=>({giftId:'',type:'Honor',honoreeName:'',honoreeId:null,notificationRecipientId:null,message:'',notes:'',visibility:'Team',donorDisclosureApproved:false});
const fields=['giftId','type','honoreeName','honoreeId','notificationRecipientId','message','notes','visibility','donorDisclosureApproved'];
const editableRecord=r=>Object.fromEntries(fields.map(k=>[k,r[k]]));
const date=v=>new Date(v).toLocaleString();

export default function Tributes({api=defaultApi,user,data,onDirty,notify,onOpen}){
 const writable=['admin','staff'].includes(user?.role),people=data?.constituents||[],gifts=data?.gifts||[];
 const names=useMemo(()=>new Map(people.map(p=>[p.id,p])),[people]);
 const [records,setRecords]=useState([]),[draft,setDraft]=useState(empty),[saved,setSaved]=useState(null),[revisions,setRevisions]=useState([]),[history,setHistory]=useState([]),[notification,setNotification]=useState(null),[channel,setChannel]=useState('Print'),[reviewed,setReviewed]=useState(false),[dirty,setDirty]=useState(false),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;Promise.all([api('/tributes'),api('/tribute-notifications')]).then(([r,n])=>{if(active){setRecords(r.tributes);setHistory(n.notifications);}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[api]);
 const mark=value=>{setDirty(value);onDirty?.(value);};
 const change=patch=>{setDraft(d=>({...d,...patch}));mark(true);setNotification(null);setReviewed(false);};
 const perform=async action=>{setBusy(true);setError('');setStatus('');try{await action();}catch(e){setError(e.message);}finally{setBusy(false);}};
 const load=id=>perform(async()=>{setNotification(null);setReviewed(false);if(!id){setDraft(empty());setSaved(null);setRevisions([]);mark(false);return;}const r=await api('/tributes/'+id);setSaved(r.tribute);setDraft(editableRecord(r.tribute));setRevisions(r.revisions);mark(false);});
 const save=()=>perform(async()=>{const r=await api(saved?'/tributes/'+saved.id:'/tributes',{method:saved?'PATCH':'POST',body:saved?{...draft,version:saved.version}:draft});setSaved(r.tribute);setDraft(editableRecord(r.tribute));setRecords(rs=>[r.tribute,...rs.filter(x=>x.id!==r.tribute.id)]);setRevisions([]);mark(false);setNotification(null);setReviewed(false);setStatus(`Tribute saved, version ${r.tribute.version}.`);notify?.('Tribute saved');});
 const prepare=()=>perform(async()=>{const r=await api('/tributes/'+saved.id+'/notifications/prepare',{method:'POST',body:{version:saved.version,channel}});setNotification(r.notification);setHistory(h=>[r.notification,...h].slice(0,100));setReviewed(false);setStatus('Notification draft saved. Review the donor, recipient and wording; nothing has been sent.');notify?.('Tribute notification prepared; not sent');});
 const finalize=()=>perform(async()=>{const r=await api('/tribute-notifications/'+notification.id+'/finalize',{method:'POST',body:{version:1,preparationDigest:notification.preparationDigest,confirmed:reviewed}});setNotification(r.notification);setHistory(h=>h.map(n=>n.id===r.notification.id?r.notification:n));setReviewed(false);setStatus('Reviewed notification retained. Not sent.');notify?.('Tribute notification finalized; not sent');});
 const readNotification=id=>perform(async()=>{const r=await api('/tribute-notifications/'+id);setNotification(r.notification);setReviewed(false);});
 const search=()=>perform(async()=>{const r=await api('/tributes'+(query.trim()?'?q='+encodeURIComponent(query.trim()):''));setRecords(r.tributes);});
 const candidates=people.filter(p=>!p.mergedInto),sourceGifts=gifts.filter(g=>g.status==='Posted'&&g.type!=='Fee payment'&&g.date<=today()&&!names.get(g.constituentId)?.mergedInto),selectedGift=gifts.find(g=>g.id===draft.giftId);
 const recipientOptions=candidates.filter(p=>p.preference!=='Do not contact'),name=r=>r.honoreeName||names.get(r.honoreeId)?.name||'Linked honoree';
 return <><div className="page-header"><div><h1>Honor & memorial</h1><p>Recognize a gift in someone’s honor or memory and retain personal notification drafts.</p></div><span className="badge badge-neutral">Not sent</span></div>
 <p className="scope-banner">Honorees and notification recipients receive no donor or soft-credit income. Drafts and finalization keep reviewed text; they do not send email, confirm delivery or issue receipts.</p>
 {error&&<div className="error-banner" role="alert">{error}</div>}{status&&<p className="subtle" role="status">{status}</p>}
 {loading?<section className="panel"><p>Loading tributes…</p></section>:<>
 <section className="panel"><div className="section-title"><h2>{saved?'Tribute details':'New tribute'}</h2><button className="btn btn-secondary" type="button" disabled={busy||dirty||!writable} onClick={()=>load('')}><Plus size={15}/>New tribute</button></div>
 <form onSubmit={e=>{e.preventDefault();save();}}><div className="form-grid">
 <label className="field">Gift<select required value={draft.giftId} disabled={busy||!writable||!!saved} onChange={e=>change({giftId:e.target.value})}><option value="">Select a recorded gift</option>{[...sourceGifts,...(selectedGift&&!sourceGifts.some(g=>g.id===selectedGift.id)?[selectedGift]:[])].map(g=><option key={g.id} value={g.id}>{names.get(g.constituentId)?.name||'Donor'} · {g.date} · {money(g.amount)} · {g.type}</option>)}</select></label>
 <label className="field">Recognition<select value={draft.type} disabled={busy||!writable} onChange={e=>change({type:e.target.value})}><option value="Honor">In honor of</option><option value="Memory">In memory of</option></select></label>
 <label className="field">Honoree name<input maxLength={250} value={draft.honoreeName} disabled={busy||!writable} onChange={e=>change({honoreeName:e.target.value})} placeholder="Name, or choose a linked honoree"/></label>
 <label className="field">Linked honoree (optional)<select value={draft.honoreeId||''} disabled={busy||!writable} onChange={e=>change({honoreeId:e.target.value||null})}><option value="">Use the entered name</option>{candidates.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <label className="field">Notification recipient (optional)<select value={draft.notificationRecipientId||''} disabled={busy||!writable} onChange={e=>change({notificationRecipientId:e.target.value||null})}><option value="">No notification</option>{recipientOptions.map(p=><option key={p.id} value={p.id}>{p.name} · {p.preference}</option>)}</select></label>
 <label className="field">Visibility<select value={draft.visibility} disabled={busy||!writable} onChange={e=>change({visibility:e.target.value})}><option>Team</option><option>Staff only</option></select></label>
 <label className="field field-wide">Personal notification message<textarea rows={4} maxLength={8000} value={draft.message} disabled={busy||!writable} onChange={e=>change({message:e.target.value})}/></label>
 <label className="field field-wide">Record notes<textarea rows={3} maxLength={8000} value={draft.notes} disabled={busy||!writable} onChange={e=>change({notes:e.target.value})}/></label>
 </div><label><input type="checkbox" checked={draft.donorDisclosureApproved} disabled={busy||!writable} onChange={e=>change({donorDisclosureApproved:e.target.checked})}/> Staff have approved sharing the donor’s identity with this selected recipient. This confirmation records our review.</label>
 <p className="subtle">Notification text names the donor and honoree and omits gift values and soft-credit recipients. “Do not contact” donor or recipient preferences block preparation. Staff-only records and their private history are hidden from viewers.</p>
 <div className="form-actions"><span className="subtle">{saved?`Version ${saved.version}${dirty?' · Unsaved changes':''}`:'Save the tribute before preparing a notification.'}</span>{dirty&&<button className="btn btn-secondary" type="button" disabled={busy} onClick={()=>{setDraft(saved?editableRecord(saved):empty());mark(false);setNotification(null);setReviewed(false);}}>Cancel changes</button>}<button className="btn btn-primary" disabled={busy||!writable||!draft.giftId||!draft.honoreeName.trim()&&!draft.honoreeId}><Save size={15}/>Save tribute</button></div></form>
 {revisions.length>0&&<details><summary>Retained tribute history · {revisions.length} versions</summary>{revisions.map(r=><div key={r.version}><h3>Version {r.version} · {date(r.at)}</h3><p>{r.definition.type==='Memory'?'In memory of':'In honor of'} {r.definition.honoreeName||r.source.honoree?.name} · Original donor: {r.source.donor.name} · {r.source.gift.date}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{r.definition.message}</pre><p>{r.definition.notes}</p></div>)}</details>}
 </section>
 {saved&&writable&&<section className="panel"><h2>Prepare a notification</h2><label className="field">Format<select value={channel} disabled={busy} onChange={e=>{setChannel(e.target.value);setNotification(null);setReviewed(false);}}><option>Print</option><option>Email draft</option></select></label><p className="subtle">Print requires the recipient’s Post preference. Email drafts require Email preference and a primary email. Finalization checks current consent, tribute and source versions again.</p><button className="btn btn-primary" type="button" disabled={busy||dirty||!saved.notificationRecipientId||!saved.donorDisclosureApproved} onClick={prepare}>Prepare notification draft</button></section>}
 {notification&&<section className="panel"><div className="section-title"><div><h2>{notification.subject}</h2><p>{notification.status} · Not sent · {notification.visibility}</p></div>{notification.status==='Finalized'&&<button className="btn btn-secondary" type="button" onClick={()=>download('tribute-notification-'+notification.id+'.txt',`NOT SENT\n${notification.subject}\nRecipient: ${notification.recipient.name}\n${notification.recipient.email?`Primary email: ${notification.recipient.email}\n`:''}\n${notification.body}`,'text/plain;charset=utf-8')}><Download size={15}/>Export reviewed text</button>}</div><p>Recipient: {notification.recipient.name}{notification.recipient.email?' · '+notification.recipient.email:''}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontFamily:'inherit'}}>{notification.body}</pre><p className="subtle">Prepared {date(notification.createdAt)}{notification.finalizedAt?' · Reviewed '+date(notification.finalizedAt):''} · Source gift date {notification.source.giftDate} · source version {notification.references.find(r=>r.collection==='gifts')?.version} · tribute version {notification.tributeVersion}</p>{onOpen&&<button className="text-btn" type="button" onClick={()=>onOpen('gifts',notification.source.giftId)}>Open source gift</button>}
 {notification.status==='Draft'&&writable&&<><label><input type="checkbox" checked={reviewed} disabled={busy} onChange={e=>setReviewed(e.target.checked)}/> I reviewed the donor disclosure, recipient, honoree and wording. I understand nothing is sent.</label><div className="form-actions"><button className="btn btn-primary" type="button" disabled={busy||!reviewed} onClick={finalize}><CheckCircle2 size={15}/>Finalize reviewed notification</button></div></>}
 </section>}
 <section className="panel"><h2>Tribute records</h2><form className="toolbar" onSubmit={e=>{e.preventDefault();search();}}><label className="field">Find a tribute<input type="search" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="btn btn-secondary" disabled={busy}>Search</button></form>{records.length?<div className="table-wrap"><table aria-label="Tribute records"><thead><tr><th>Recognition</th><th>Honoree</th><th>Donor</th><th>Visibility</th><th>Version</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td><button className="record-link" type="button" disabled={busy||dirty} onClick={()=>load(r.id)}>{r.type==='Memory'?'In memory of':'In honor of'}</button></td><td>{name(r)}</td><td>{names.get(gifts.find(g=>g.id===r.giftId)?.constituentId)?.name||'Recorded donor'}</td><td>{r.visibility}</td><td>{r.version}</td></tr>)}</tbody></table></div>:<div className="empty-state">No tributes match this search.</div>}<p className="table-note">Showing up to 100 records.</p></section>
 <section className="panel"><h2>Notification history</h2>{history.length?<div className="table-wrap"><table aria-label="Tribute notification history"><thead><tr><th>Notification</th><th>Recipient</th><th>Status</th><th>Prepared</th><th>Delivery</th></tr></thead><tbody>{history.map(n=><tr key={n.id}><td><button className="record-link" type="button" disabled={busy||dirty} onClick={()=>readNotification(n.id)}>{n.subject}</button></td><td>{n.recipient.name}</td><td>{n.status}</td><td>{date(n.createdAt)}</td><td>Not sent</td></tr>)}</tbody></table></div>:<div className="empty-state">No notification drafts have been saved.</div>}<p className="table-note">Showing up to 100 retained drafts and reviewed notifications.</p></section>
 </>}
 </>;
}
