import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
function harness(){let index=0,state=[],effects=[],keys=[];globalThis.window={confirm:()=>true};const mock={...React,useState(initial){const i=index++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return[state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){return state[index++]??=({current:initial});},useEffect(effect,deps){const i=index++;if(!keys[i]||deps.some((d,j)=>d!==keys[i][j])){keys[i]=deps;effects.push(effect);}}};const module={exports:{}},require=id=>id==='react'?mock:new Proxy({},{get:()=>()=>null});new Function('React','require','module','exports',transformSync(readFileSync(new URL('../src/features/Audiences.jsx',import.meta.url),'utf8'),{loader:'jsx',format:'cjs'}).code)(React,require,module,module.exports);return props=>{index=0;const tree=module.exports.default(props),pending=effects;effects=[];pending.forEach(e=>e());return tree;};}
function find(tree,predicate){if(!tree||typeof tree!=='object')return null;if(predicate(tree))return tree;for(const c of React.Children.toArray(tree.props?.children)){const r=find(c,predicate);if(r)return r;}return null;}
const flush=async()=>{for(let i=0;i<6;i++)await Promise.resolve();};
const definition={id:'11111111-1111-4111-8111-111111111111',version:2,name:'Annual volunteers',status:'Active',filters:{segmentTokens:['Annual donor'],segmentMatch:'Any',types:[],preferences:[]}};
const preview={audience:{id:definition.id,version:2,name:definition.name},sourceDigest:'a'.repeat(64),channel:'Print',totalCount:7,matchedCount:5,eligibleCount:3,excludedCount:4,reasonCounts:{'Outside saved criteria':2,'Do not contact':2},recipients:[{id:'person-1',name:'Casey Synthetic',version:3,preference:'Post'}],nextCursor:'22222222-2222-4222-8222-222222222222'};
async function ready(extra={}){const calls=[],render=harness(),props={user:{role:'staff'},api:async(path,options)=>{calls.push([path,options]);return path==='/audiences'?{audiences:[definition]}:path.includes('/preview?')?preview:{audience:definition,revisions:[]};},...extra};render(props);await flush();let tree=render(props);find(tree,e=>e.type==='select'&&React.Children.toArray(e.props.children).some(c=>c.props?.value===definition.id)).props.onChange({target:{value:definition.id}});await flush();tree=render(props);await find(tree,e=>e.type==='button'&&React.Children.toArray(e.props.children).includes('Review current eligibility')).props.onClick();return{render,props,calls,tree:render(props)};}
test('audience preview distinguishes matching, eligible and globally excluded profiles',async()=>{const {tree}=await ready();const html=renderToStaticMarkup(tree);assert.match(html,/5<\/strong><span>Matching profiles/);assert.match(html,/3<\/strong><span>Eligible for Print/);assert.match(html,/4<\/strong><span>Excluded profiles/);assert.match(html,/Source profiles reviewed: 7/);assert.match(html,/one primary reason/);assert.doesNotMatch(html,/Exclusion reasons may overlap/);});
test('audience explicit selection pins digest and clears when changing pages',async()=>{const selections=[],s=await ready({onSelection:v=>selections.push(v)});find(s.tree,e=>e.type==='input'&&e.props['aria-label']==='Select audience recipient Casey Synthetic').props.onChange({target:{checked:true}});assert.deepEqual(selections.at(-1),{constituentIds:['person-1'],audience:{id:definition.id,version:2,sourceDigest:'a'.repeat(64)}});let tree=s.render(s.props);await find(tree,e=>e.type==='button'&&React.Children.toArray(e.props.children).includes('Next recipients')).props.onClick();assert.equal(selections.at(-1),null);assert.match(s.calls.at(-1)[0],/after=22222222/);tree=s.render(s.props);assert.equal(find(tree,e=>e.type==='input'&&e.props['aria-label']==='Select audience recipient Casey Synthetic').props.checked,false);});
test('audience selection and criteria lock during parent preparation',async()=>{const s=await ready({onSelection:()=>{}}),tree=s.render({...s.props,disabled:true});assert.equal(find(tree,e=>e.type==='input'&&e.props['aria-label']==='Select audience recipient Casey Synthetic').props.disabled,true);assert.equal(find(tree,e=>e.type==='fieldset').props.disabled,true);assert.equal(find(tree,e=>e.type==='button'&&React.Children.toArray(e.props.children).includes('Review current eligibility')).props.disabled,true);});
test('changing an edited audience uses an inline keep or discard decision',async()=>{const s=await ready();find(s.tree,e=>e.type==='input'&&e.props.value===definition.name).props.onChange({target:{value:'Unsaved criteria QA'}});let tree=s.render(s.props);find(tree,e=>e.type==='button'&&React.Children.toArray(e.props.children).includes('New audience')).props.onClick();tree=s.render(s.props);assert.ok(find(tree,e=>e.props?.role==='alertdialog'));find(tree,e=>e.type==='button'&&React.Children.toArray(e.props.children).includes('Keep editing criteria')).props.onClick();tree=s.render(s.props);assert.equal(find(tree,e=>e.props?.role==='alertdialog'),null);assert.ok(find(tree,e=>e.type==='input'&&e.props.value==='Unsaved criteria QA'));find(tree,e=>e.type==='button'&&React.Children.toArray(e.props.children).includes('New audience')).props.onClick();tree=s.render(s.props);find(tree,e=>e.type==='button'&&React.Children.toArray(e.props.children).includes('Discard criteria changes')).props.onClick();tree=s.render(s.props);assert.equal(find(tree,e=>e.props?.role==='alertdialog'),null);assert.equal(find(tree,e=>e.type==='input'&&e.props.value==='Unsaved criteria QA'),null);assert.equal(find(tree,e=>e.type==='button'&&React.Children.toArray(e.props.children).includes('Review current eligibility')),null);});
