import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {Readable} from 'node:stream';
import {createS3BackupStorage,createBackupStorageFromEnv} from '../server/backupStorage.js';
const OWNER='ba32533b-5f2d-41e8-9765-5ee2ed5bca95',OTHER='f3f80b13-6ed9-49ae-a99e-576c245eec16';
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
function fixture(){const objects=new Map(),calls=[];let publicBucket=false,tamper=null;const client={async send(command){const i=command.input,type=command.constructor.name;calls.push({type,input:i});if(type==='GetBucketLocationCommand')return {LocationConstraint:null};if(type==='GetBucketAclCommand')return {Owner:{ID:'synthetic-owner'},Grants:[{Grantee:{ID:'synthetic-owner'},Permission:'FULL_CONTROL'}]};if(type==='GetPublicAccessBlockCommand')return {PublicAccessBlockConfiguration:{BlockPublicAcls:true,IgnorePublicAcls:true,BlockPublicPolicy:true,RestrictPublicBuckets:true}};if(type==='GetBucketPolicyStatusCommand')return {PolicyStatus:{IsPublic:publicBucket}};if(type==='GetBucketEncryptionCommand')return {ServerSideEncryptionConfiguration:{Rules:[{ApplyServerSideEncryptionByDefault:{SSEAlgorithm:'AES256'}}]}};if(type==='GetBucketVersioningCommand')return {Status:'Enabled'};if(type==='PutObjectCommand'){if(objects.has(i.Key))throw new Error('Immutable collision');objects.set(i.Key,{bytes:Buffer.from(i.Body),metadata:i.Metadata,version:'exact-version'});return {VersionId:'exact-version',ServerSideEncryption:'AES256'};}if(type==='DeleteObjectCommand'){objects.delete(i.Key);return {};}if(['HeadObjectCommand','GetObjectCommand'].includes(type)){const o=objects.get(i.Key);if(!o)throw new Error('Missing exact object');return {ServerSideEncryption:'AES256',ContentLength:o.bytes.length,VersionId:o.version,Metadata:o.metadata,...(type==='GetObjectCommand'?{Body:Readable.from([o.bytes])}:{}),...(tamper||{})};}throw new Error(type);}};const store=createS3BackupStorage({bucket:'synthetic-private-backups',namespace:'release-a',region:'us-east-1',privateConfirmed:true,client});return {store,objects,calls,setPublic:v=>publicBucket=v,setTamper:v=>tamper=v};}
test('native recovery store separates tenant and full-root identities with exact encrypted archive versions and hashes',async()=>{const f=fixture();for(const platform of [false,true]){const identity=platform?{recoveryId:OWNER}:{tenantId:OWNER},bytes=Buffer.from((platform?'WIMBLO-PLATFORM-RECOVERY\n':'WIMBLO-BACKUP\n')+'synthetic ciphertext only'),ref=await f.store.putImmutable({...identity,bytes,sha256:hash(bytes)});assert.match(ref.key,new RegExp('namespaces/release-a/'+(platform?'platform-backups':'backups')+'/'+OWNER+'/'));assert.equal(ref.versionId,'exact-version');assert.equal(ref.url,undefined);assert.deepEqual(await f.store.readVersion({...identity,...ref,maxBytes:bytes.length}),bytes);await assert.rejects(f.store.readVersion({...ref,...(platform?{recoveryId:OTHER}:{tenantId:OTHER})}),/outside/);await assert.rejects(f.store.readVersion({...ref,tenantId:OWNER,recoveryId:OWNER}),/exactly one/);await assert.rejects(f.store.readVersion({...ref,...identity,maxBytes:bytes.length-1}),/exceeds/);await assert.rejects(f.store.readVersion({...ref,...identity,versionId:'wrong-version'}),/verification failed/);f.setTamper({Body:Readable.from([Buffer.alloc(bytes.length)])});await assert.rejects(f.store.readVersion({...ref,...identity}),/checksum verification failed/);f.setTamper(null);const otherIdentity=platform?{tenantId:OWNER}:{recoveryId:OWNER};const {tenantId,recoveryId,...neutral}=ref;await assert.rejects(f.store.readVersion({...neutral,...otherIdentity}),/outside/);}assert.equal(f.objects.size,2);assert.ok(f.calls.filter(c=>c.type==='PutObjectCommand').every(c=>c.input.IfNoneMatch==='*'&&c.input.ServerSideEncryption==='AES256'));});
test('native recovery refuses public buckets, ambiguous identities and wrong ciphertext headers before successful publication',async()=>{const f=fixture(),bytes=Buffer.from('WIMBLO-BACKUP\nsynthetic ciphertext');await assert.rejects(f.store.putImmutable({tenantId:OWNER,recoveryId:OTHER,bytes,sha256:hash(bytes)}),/exactly one/);await assert.rejects(f.store.putImmutable({recoveryId:OWNER,bytes,sha256:hash(bytes)}),/encrypted archives/);await assert.rejects(f.store.putImmutable({tenantId:OWNER,bytes,sha256:'0'.repeat(64)}),/checksum/);f.setPublic(true);await assert.rejects(f.store.putImmutable({tenantId:OWNER,bytes,sha256:hash(bytes)}),/verification failed/);assert.equal(f.objects.size,0);});
test('backup-only server credentials configure recovery independently of document credentials',()=>{assert.equal(createBackupStorageFromEnv({}),null);const env={BACKUP_STORAGE_BUCKET:'synthetic-private-backups',BACKUP_STORAGE_NAMESPACE:'release-a',BACKUP_AWS_REGION:'us-east-1',BACKUP_STORAGE_PRIVATE_CONFIRMED:'true',BACKUP_AWS_ACCESS_KEY_ID:'synthetic',BACKUP_AWS_SECRET_ACCESS_KEY:'not-live',BACKUP_AWS_SESSION_TOKEN:'synthetic-session'};assert.equal(createBackupStorageFromEnv(env).private,true);assert.throws(()=>createBackupStorageFromEnv({...env,BACKUP_AWS_SECRET_ACCESS_KEY:''}),/credentials/);assert.throws(()=>createBackupStorageFromEnv({...env,BACKUP_STORAGE_PRIVATE_CONFIRMED:'false'}),/private/);});


test('production recovery residency uses effective backup region and refuses endpoint overrides',()=>{const env={NODE_ENV:'production',BACKUP_STORAGE_BUCKET:'private-backups',BACKUP_STORAGE_NAMESPACE:'release-a',BACKUP_STORAGE_PRIVATE_CONFIRMED:'true',BACKUP_AWS_REGION:'ca-central-1',AWS_REGION:'eu-west-1',BACKUP_AWS_ACCESS_KEY_ID:'synthetic',BACKUP_AWS_SECRET_ACCESS_KEY:'not-live'};assert.equal(createBackupStorageFromEnv(env).private,true);assert.throws(()=>createBackupStorageFromEnv({...env,BACKUP_AWS_REGION:'eu-west-1'}),/US or Canada/);for(const field of ['BACKUP_AWS_ENDPOINT_URL_S3','AWS_ENDPOINT_URL_S3','BACKUP_AWS_ENDPOINT_URL','AWS_ENDPOINT_URL'])assert.throws(()=>createBackupStorageFromEnv({...env,[field]:'https://foreign-storage.example'}),/custom (?:AWS )?endpoint/);});
