import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,writeFile,stat,readdir,lstat,symlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {randomBytes,randomUUID,createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {spawn} from 'node:child_process';
import {createApp} from '../server/app.js';
import {totp} from '../server/mfa.js';
import {backupWorkspace,restoreWorkspace,publishOffHostBackup,parseBackupKey,BACKUP_LIMITS} from '../server/backup.js';
import {createDocumentRecoveryAdapter} from '../server/documentRecovery.js';

const mfaKey='4'.repeat(64),sha=b=>createHash('sha256').update(b).digest('hex');
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'wimblo-full-backup-')),dbPath=join(dir,'original.sqlite'),tenantId=randomUUID(),key=randomBytes(32).toString('hex'),archivePath=join(dir,'archive.wbackup');let app=createApp({dbPath,seed:true,tenantId,mfaKey}),server=app.listen(0,'127.0.0.1');await once(server,'listening');let base=`http://127.0.0.1:${server.address().port}`;
 async function close(){if(server)await new Promise(r=>server.close(r));server=null;app?.locals.close();app=null;}
 t.after(async()=>{await close();await rm(dir,{recursive:true,force:true});});
 async function request(path,{method='GET',body,session,csrf=true}={}){const headers={};if(body!==undefined)headers['Content-Type']='application/json';if(session){headers.Cookie=session.cookie;if(csrf)headers['X-CSRF-Token']=session.csrfToken;}const r=await fetch(base+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,json:await r.json(),headers:r.headers};}
 async function login(email='alex@foundation.example'){const r=await request('/api/auth/login',{method:'POST',body:{email,password:'FoundationDemo!2026'}});assert.equal(r.status,200);return {...r.json,cookie:r.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ')};}
 const admin=await login(),staff=await login('staff@foundation.example'),viewer=await login('board@foundation.example');
 async function create(path,body){const r=await request(path,{method:'POST',session:admin,body});assert.equal(r.status,201,JSON.stringify(r.json));return r.json;}
 const donor=(await create('/api/records/constituents',{name:'Recovery only donor',type:'Employee',email:'recovery@example.test'})).record,fund=(await create('/api/records/designations',{name:'Recovery only fund',accountCode:'BACKUP-4100'})).record,gift=(await create('/api/records/gifts',{constituentId:donor.id,amount:10001,type:'Employee giving',method:'Payroll',date:'2025-12-31',allocations:[{designationId:fund.id,amount:10001}]})).record;
 const documentBytes=Buffer.from('Retained evidence café\nExact receipt value: $100.01\n');const document=(await create('/api/documents',{collection:'constituents',recordId:donor.id,title:'Retained recovery evidence',category:'Agreement',visibility:'Administrators',status:'Final',evidenceDate:null,filename:'agreement.txt',contentBase64:documentBytes.toString('base64')})).document;
 const revisionBytes=Buffer.from('Second immutable revision\n');const revision=await request(`/api/documents/${document.id}/revisions`,{method:'POST',session:admin,body:{version:1,title:'Retained recovery evidence revised',category:'Agreement',visibility:'Administrators',status:'Submitted',evidenceDate:'2025-12-31',filename:'agreement-v2.txt',contentBase64:revisionBytes.toString('base64')}});assert.equal(revision.status,200);
 const prof=await request('/api/receipt-profile',{method:'PUT',session:admin,body:{version:0,organizationName:'Recovery test organization',address:'123 Test Avenue',taxIdentifier:'TEST-ONLY-RECOVERY',signatureLabel:'Authorized test signer',customFooter:'Human client tax approval pending.',approved:true}});assert.equal(prof.status,200);
 const receipt=(await create('/api/receipts/prepare',{kind:'Annual employee',constituentId:donor.id,year:2025,profileVersion:1})).receipt;const issue=await request(`/api/receipts/${receipt.id}/issue`,{method:'POST',session:admin,body:{version:1,preparationDigest:receipt.preparationDigest,channel:'Print',printed:true,handSigned:true,issueDate:'2026-09-13'}});assert.equal(issue.status,200);
 const template=(await create('/api/correspondence/templates',{name:'Recovery message',kind:'Messaging',subject:'Hello {{recipientName}}',body:'Retained message {{organizationName}}'})).template;const correspondence=(await create('/api/correspondence/prepare',{templateId:template.id,templateVersion:1,channel:'Print',constituentIds:[donor.id]})).correspondence;const finalized=await request(`/api/correspondence/${correspondence.id}/finalize`,{method:'POST',session:admin,body:{version:1,preparationDigest:correspondence.preparationDigest,confirmed:true}});assert.equal(finalized.status,200);
 const enrollment=await request('/api/auth/mfa/enroll',{method:'POST',session:staff,body:{password:'FoundationDemo!2026'}});assert.equal(enrollment.status,200);const confirm=await request('/api/auth/mfa/confirm',{method:'POST',session:staff,body:{code:totp(enrollment.json.secret)}});assert.equal(confirm.status,200);const challenge=await login('staff@foundation.example');assert.equal(challenge.mfaRequired,true);const pending=await request('/api/auth/mfa/enroll',{method:'POST',session:viewer,body:{password:'FoundationDemo!2026'}});assert.equal(pending.status,200);
 const originalEnabled=app.locals.db.prepare('SELECT * FROM mfa_settings WHERE user_id=?').get(staff.user.id);
 async function backup(changes={}){return backupWorkspace({db:app.locals.db,outputPath:archivePath,tenantId,encryptionKey:key,...changes});}
 async function restore(changes={}){return restoreWorkspace({archivePath,destinationPath:join(dir,'restored.sqlite'),expectedTenantId:tenantId,encryptionKey:key,...changes});}
 async function openRestored(path,key=mfaKey){await close();app=createApp({dbPath:path,seed:false,tenantId,mfaKey:key});server=app.listen(0,'127.0.0.1');await once(server,'listening');base=`http://127.0.0.1:${server.address().port}`;}
 return {dir,dbPath,tenantId,key,archivePath,admin,staff,viewer,donor,gift,document,documentBytes,revisionBytes,receipt,template,correspondence,originalEnabled,recoveryCode:confirm.json.recoveryCodes[0],authenticatorSecret:enrollment.json.secret,backup,restore,request,login,close,openRestored,get db(){return app.locals.db;}};
}

test('encrypted full live-connection backup restores all installed tables, document bytes, exact money, receipt/templates/history and retention',async t=>{
 const f=await fixture(t);const sourceAudit=f.db.prepare('SELECT count(*) n FROM audit').get().n;const result=await f.backup();assert.ok(result.tableCount>20);assert.ok(result.tables.some(t=>t.name==='document_revisions'));assert.ok(result.tables.some(t=>t.name==='receipt_issues'));assert.ok(result.tables.some(t=>t.name==='correspondence_templates'));assert.equal(f.db.prepare('SELECT count(*) n FROM audit').get().n,sourceAudit);
 const restored=await f.restore();assert.equal(restored.sourceSha256,result.sourceSha256);assert.deepEqual(restored.verifiedSourceInventory.tables,result.tables);assert.ok(restored.cleared.sessions>0);assert.equal(restored.cleared.mfaChallenges,1);assert.equal(restored.cleared.pendingMfaEnrollments,1);
 const copy=new DatabaseSync(restored.destinationPath,{readOnly:true});try{const money=JSON.parse(copy.prepare('SELECT data FROM records WHERE collection=? AND id=?').get('gifts',f.gift.id).data);assert.equal(money.amount,10001);const files=copy.prepare('SELECT revision,bytes,sha256 FROM document_revisions WHERE document_id=? ORDER BY revision').all(f.document.id);assert.deepEqual(Buffer.from(files[0].bytes),f.documentBytes);assert.deepEqual(Buffer.from(files[1].bytes),f.revisionBytes);assert.equal(files[0].sha256,sha(f.documentBytes));const retention=copy.prepare('SELECT retention_until FROM documents WHERE id=?').get(f.document.id).retention_until;assert.ok(Date.parse(retention)>Date.now()+9*365*86400000);assert.equal(copy.prepare('SELECT number FROM receipt_issues WHERE receipt_id=?').get(f.receipt.id).number,'R-00000001');assert.equal(copy.prepare('SELECT count(*) n FROM correspondence_finalizations').get().n,1);assert.equal(copy.prepare('SELECT count(*) n FROM audit').get().n,sourceAudit);assert.equal(copy.prepare('SELECT count(*) n FROM sessions').get().n,0);assert.equal(copy.prepare('SELECT count(*) n FROM mfa_challenges').get().n,0);const enabled=copy.prepare('SELECT * FROM mfa_settings WHERE user_id=?').get(f.staff.user.id);assert.equal(enabled.enabled,1);assert.equal(enabled.encrypted_secret,f.originalEnabled.encrypted_secret);assert.equal(enabled.last_step,f.originalEnabled.last_step);assert.equal(copy.prepare('SELECT count(*) n FROM mfa_recovery').get().n,8);}finally{copy.close();}
 assert.equal((await stat(f.archivePath)).mode&0o777,0o600);assert.equal((await stat(restored.destinationPath)).mode&0o777,0o600);assert.equal((await readdir(f.dir)).filter(n=>n.startsWith('.wimblo-backup-')).length,0);
});

test('restored copy rejects prebackup sessions, preserves active MFA with separate key and provides usable login recovery',async t=>{
 const f=await fixture(t);await f.backup();const restored=await f.restore();await f.openRestored(restored.destinationPath);assert.equal((await f.request('/api/workspace',{session:f.admin})).status,401);const challenge=await f.login('staff@foundation.example');assert.equal(challenge.mfaRequired,true);const verified=await f.request('/api/auth/mfa/verify',{method:'POST',body:{challengeToken:challenge.challengeToken,code:f.recoveryCode}});assert.equal(verified.status,200);const admin=await f.login();assert.equal((await f.request(`/api/documents/${f.document.id}/revisions/1/content`,{session:admin})).json.sha256,sha(f.documentBytes));assert.equal((await f.request(`/api/receipts/${f.receipt.id}`,{session:admin})).json.receipt.monetaryCents,10001);
});

test('wrong key, ciphertext tampering and tenant mismatch fail without publishing a destination',async t=>{
 const f=await fixture(t);await f.backup();await assert.rejects(f.restore({encryptionKey:randomBytes(32).toString('base64')}),/authentication failed/);await assert.rejects(f.restore({expectedTenantId:randomUUID()}),/expected tenant/);await assert.rejects(lstat(join(f.dir,'restored.sqlite')),e=>e.code==='ENOENT');const bytes=await readFile(f.archivePath);bytes[bytes.length-100]^=1;const tampered=join(f.dir,'tampered.wbackup');await writeFile(tampered,bytes);await assert.rejects(f.restore({archivePath:tampered}),/authentication failed/);await assert.rejects(lstat(join(f.dir,'restored.sqlite')),e=>e.code==='ENOENT');assert.equal((await readdir(f.dir)).filter(n=>n.startsWith('.wimblo-backup-')).length,0);
});

test('authenticated tenant binding rejects changing plaintext tenant header even when caller expects the forged tenant',async t=>{
 const f=await fixture(t);await f.backup();const bytes=await readFile(f.archivePath),magicLength=Buffer.byteLength('WIMBLO-BACKUP\n'),length=bytes.readUInt32BE(magicLength),start=magicLength+4,header=JSON.parse(bytes.subarray(start,start+length)),forged=randomUUID();header.tenantId=forged;const replacement=Buffer.from(JSON.stringify(header));assert.equal(replacement.length,length);replacement.copy(bytes,start);const path=join(f.dir,'forged.wbackup');await writeFile(path,bytes);await assert.rejects(f.restore({archivePath:path,expectedTenantId:forged}),/authentication failed/);
});

test('existing archives, database destinations and symlinks are never overwritten, including simultaneous publication',async t=>{
 const f=await fixture(t);const results=await Promise.allSettled([f.backup(),f.backup()]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.match(results.find(r=>r.status==='rejected').reason.message,/already exists/);const before=sha(await readFile(f.archivePath));await assert.rejects(f.backup(),/already exists/);assert.equal(sha(await readFile(f.archivePath)),before);
 await assert.rejects(f.restore({destinationPath:f.dbPath}),/already exists/);const existing=join(f.dir,'existing.sqlite');await writeFile(existing,'Existing bytes');await assert.rejects(f.restore({destinationPath:existing}),/already exists/);assert.equal(await readFile(existing,'utf8'),'Existing bytes');const alias=join(f.dir,'symlink.sqlite');await symlink(existing,alias);await assert.rejects(f.restore({destinationPath:alias}),/already exists/);assert.equal(await readFile(existing,'utf8'),'Existing bytes');
});

test('archive plaintext header and normal result metadata expose no credentials, user records, document text or environment keys',async t=>{
 const f=await fixture(t);const result=await f.backup(),bytes=await readFile(f.archivePath),magicLength=Buffer.byteLength('WIMBLO-BACKUP\n'),length=bytes.readUInt32BE(magicLength),header=JSON.parse(bytes.subarray(magicLength+4,magicLength+4+length));assert.deepEqual(Object.keys(header).sort(),['format','nonce','tag','tenantId','version']);const passwordHash=f.db.prepare('SELECT password_hash FROM users LIMIT 1').get().password_hash;
 for(const value of ['Recovery only donor','Retained evidence café','TEST-ONLY-RECOVERY',passwordHash,f.authenticatorSecret,f.key,mfaKey])assert.equal(bytes.includes(Buffer.from(value)),false);const metadata=JSON.stringify(result);assert.doesNotMatch(metadata,/password_hash|csrfToken|challengeToken|encrypted_secret|Retained evidence café|TEST-ONLY-RECOVERY/);assert.ok(!metadata.includes(f.key));
});

test('strict key/tenant/size limits and malformed archives reject; no plaintext staging files remain after failure',async t=>{
 for(const key of [undefined,'','secret','0'.repeat(62),'='.repeat(44)])assert.throws(()=>parseBackupKey(key),/32-byte/);assert.equal(parseBackupKey(randomBytes(32).toString('base64')).length,32);assert.equal(parseBackupKey(randomBytes(32).toString('hex')).length,32);
 const f=await fixture(t);await assert.rejects(f.backup({tenantId:'workspace'}),/tenant UUID/);await assert.rejects(f.backup({maxBytes:1024}),/byte limit/);assert.equal((await readdir(f.dir)).filter(n=>n.startsWith('.wimblo-backup-')).length,0);await assert.rejects(f.backup({maxBytes:BACKUP_LIMITS.maxArchiveBytes+1}),/Archive limit/);
 const malformed=join(f.dir,'malformed.wbackup');await writeFile(malformed,'not an archive');await assert.rejects(f.restore({archivePath:malformed}),/invalid/);const oversized=join(f.dir,'oversized.wbackup');await writeFile(oversized,Buffer.alloc(2048));await assert.rejects(f.restore({archivePath:oversized,maxBytes:1024}),/byte limit/);
});

async function cli(args,env={}){return new Promise(resolve=>{const child=spawn(process.execPath,['scripts/backup.mjs',...args],{cwd:new URL('..',import.meta.url).pathname,env:{...process.env,...env},stdio:['ignore','pipe','pipe']});let out='';child.stdout.on('data',b=>out+=b);child.stderr.on('data',b=>out+=b);child.on('close',code=>resolve({code,out}));});}
test('CLI operates on offline read-only source, requires environment-only key, rejects secret arguments and documents separate MFA dependency',async t=>{
 const f=await fixture(t);await f.close();const help=await cli(['--help']);assert.equal(help.code,0);assert.match(help.out,/SAME MFA_ENCRYPTION_KEY/);assert.match(help.out,/No default key/);const invalid=await cli(['backup','--key',f.key]);assert.equal(invalid.code,1);assert.ok(!invalid.out.includes(f.key));const missing=await cli(['backup','--db',f.dbPath,'--out',f.archivePath,'--tenant',f.tenantId],{BACKUP_ENCRYPTION_KEY:''});assert.equal(missing.code,1);const created=await cli(['backup','--db',f.dbPath,'--out',f.archivePath,'--tenant',f.tenantId],{BACKUP_ENCRYPTION_KEY:f.key});assert.equal(created.code,0,created.out);assert.ok(!created.out.includes(f.key));const restored=await cli(['restore','--archive',f.archivePath,'--dest',join(f.dir,'cli-restored.sqlite'),'--tenant',f.tenantId],{BACKUP_ENCRYPTION_KEY:f.key});assert.equal(restored.code,0,restored.out);assert.match(restored.out,/restored and verified/);
});

test('live database writes after VACUUM snapshot do not enter snapshot counts or cause a partial restored workspace',async t=>{
 const f=await fixture(t),originalCount=f.db.prepare('SELECT count(*) n FROM records').get().n,id=randomUUID();
 const liveConnection={prepare(sql){const statement=f.db.prepare(sql);return sql==='VACUUM INTO ?'?{run(path){const result=statement.run(path);f.db.prepare('INSERT INTO records VALUES(?,?,?)').run('tasks',id,JSON.stringify({id,version:1,title:'After snapshot task',dueDate:'2026-09-13',status:'Open'}));return result;}}:statement;}};
 const result=await f.backup({db:liveConnection});assert.equal(f.db.prepare('SELECT count(*) n FROM records').get().n,originalCount+1);assert.equal(result.tables.find(t=>t.name==='records').count,originalCount);const restored=await f.restore(),db=new DatabaseSync(restored.destinationPath,{readOnly:true});try{assert.equal(db.prepare('SELECT count(*) n FROM records').get().n,originalCount);assert.equal(db.prepare('SELECT data FROM records WHERE id=?').get(id),undefined);assert.equal(JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(f.gift.id).data).amount,10001);}finally{db.close();}
});

test('off-host upload requires exact immutable-version encrypted readback and rejects wrong tenant or corrupt providers',async t=>{
 const f=await fixture(t);await f.backup();let saved,versionRead;
 const store={offHost:true,private:true,putImmutable:async({tenantId,bytes})=>{assert.equal(tenantId,f.tenantId);saved=Buffer.from(bytes);return {key:'private/encrypted-backup',versionId:'immutable-1'};},readVersion:async ref=>{versionRead=ref.versionId;return saved;}};
 const result=await publishOffHostBackup({archivePath:f.archivePath,encryptionKey:f.key,tenantId:f.tenantId,store});assert.equal(result.verified,true);assert.equal(result.offHost,true);assert.equal(versionRead,'immutable-1');assert.equal(result.archiveSha256,sha(await readFile(f.archivePath)));
 await assert.rejects(publishOffHostBackup({archivePath:f.archivePath,encryptionKey:f.key,tenantId:randomUUID(),store}),/tenant/);
 await assert.rejects(publishOffHostBackup({archivePath:f.archivePath,encryptionKey:f.key,tenantId:f.tenantId,store:{...store,readVersion:async()=>Buffer.from('wrong bytes')}}),/readback verification failed/);
 await assert.rejects(publishOffHostBackup({archivePath:f.archivePath,encryptionKey:f.key,tenantId:f.tenantId,store:{...store,putImmutable:async()=>({key:'object'})}}),/immutable object version/);
 await assert.rejects(publishOffHostBackup({archivePath:f.archivePath,encryptionKey:f.key,tenantId:f.tenantId,store:{...store,offHost:false}}),/private off-host/);
 const tampered=join(f.dir,'fake-encrypted.wbackup'),bytes=await readFile(f.archivePath);bytes[bytes.length-1]^=1;await writeFile(tampered,bytes);let uploaded=false;await assert.rejects(publishOffHostBackup({archivePath:tampered,tenantId:f.tenantId,encryptionKey:f.key,store:{...store,putImmutable:async()=>{uploaded=true;return {key:'bad',versionId:'bad'};}}}),/authentication failed/);assert.equal(uploaded,false);
});

function externalize(f){
 f.db.exec('CREATE TABLE IF NOT EXISTS document_revision_storage(document_id TEXT,revision INTEGER,tenant_id TEXT,provider TEXT,bucket TEXT,namespace TEXT,object_key TEXT,object_version TEXT,sha256 TEXT,size INTEGER,created_at TEXT,PRIMARY KEY(document_id,revision));');
 const reference={document_id:f.document.id,revision:1,tenant_id:f.tenantId,provider:'S3',bucket:'private-test-bucket',namespace:'tenant-test',object_key:'immutable/revision-1',object_version:'version-original',sha256:sha(f.documentBytes),size:f.documentBytes.length,created_at:new Date().toISOString()};
 const existing=f.db.prepare('SELECT * FROM document_revision_storage WHERE document_id=? AND revision=?').get(f.document.id,1);if(!existing)f.db.prepare('INSERT INTO document_revision_storage VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(...Object.values(reference));
 const guard=f.db.prepare("SELECT sql FROM sqlite_schema WHERE name='document_revision_no_update'").get().sql;f.db.exec('DROP TRIGGER document_revision_no_update');f.db.prepare('UPDATE document_revisions SET bytes=? WHERE document_id=? AND revision=1').run(Buffer.alloc(0),f.document.id);f.db.exec(guard);return reference;
}
test('external document versions are bundled from the snapshot and recover offline as verified inline bytes with original provenance and immutable guards',async t=>{
 const f=await fixture(t),reference=externalize(f);let fetched;
 const result=await f.backup({documentStorage:{exportStoredRevision:async row=>{fetched=row;return {bytes:f.documentBytes};}}});assert.equal(result.externalDocumentRevisions,1);assert.equal(fetched.object_version,reference.object_version);
 const restored=await f.restore();assert.equal(restored.materializedDocumentRevisions,1);const db=new DatabaseSync(restored.destinationPath);try{assert.deepEqual(Buffer.from(db.prepare('SELECT bytes FROM document_revisions WHERE document_id=? AND revision=1').get(f.document.id).bytes),f.documentBytes);assert.deepEqual({...db.prepare('SELECT * FROM document_revision_storage WHERE document_id=? AND revision=1').get(f.document.id)},reference);assert.throws(()=>db.prepare('UPDATE document_revisions SET bytes=? WHERE document_id=? AND revision=1').run(Buffer.from('rewrite'),f.document.id),/immutable/);assert.equal(restored.verifiedSourceInventory.schemaFingerprint,restored.restoredInventory.schemaFingerprint);}finally{db.close();}
 assert.equal((await readFile(f.archivePath)).includes(f.documentBytes),false);
});
test('missing, corrupted and wrong-tenant external document versions never publish a successful archive',async t=>{
 const f=await fixture(t);externalize(f);await assert.rejects(f.backup(),/recovery adapter/);await assert.rejects(f.backup({documentStorage:{exportStoredRevision:async()=>({bytes:Buffer.from('corrupt')})}}),/checksum or size/);await assert.rejects(lstat(f.archivePath),e=>e.code==='ENOENT');
 const storageGuard=f.db.prepare("SELECT sql FROM sqlite_schema WHERE name='document_storage_no_update'").get()?.sql;if(storageGuard)f.db.exec('DROP TRIGGER document_storage_no_update');f.db.prepare('UPDATE document_revision_storage SET tenant_id=? WHERE document_id=?').run(randomUUID(),f.document.id);if(storageGuard)f.db.exec(storageGuard);await assert.rejects(f.backup({documentStorage:{exportStoredRevision:async()=>({bytes:f.documentBytes})}}),/tenant/);assert.equal((await readdir(f.dir)).filter(n=>n.startsWith('.wimblo-backup-')).length,0);
});
test('an empty external revision without its retained mapping cannot be called a successful full backup',async t=>{const f=await fixture(t),guard=f.db.prepare("SELECT sql FROM sqlite_schema WHERE name='document_revision_no_update'").get().sql;f.db.exec('DROP TRIGGER document_revision_no_update');f.db.prepare('UPDATE document_revisions SET bytes=? WHERE document_id=? AND revision=1').run(Buffer.alloc(0),f.document.id);f.db.exec(guard);await assert.rejects(f.backup(),/mapping is missing/);await assert.rejects(lstat(f.archivePath),e=>e.code==='ENOENT');});
test('selected-tenant recovery adapter passes exact immutable document and provider identity into byte verification',async t=>{const f=await fixture(t),reference=externalize(f);let requested;const objectStorage={scope:{provider:reference.provider,bucket:reference.bucket,namespace:reference.namespace},get:async ref=>{requested=ref;assert.equal(ref.documentId,f.document.id);assert.equal(ref.revision,1);assert.equal(ref.version,reference.object_version);assert.equal(ref.tenantId,f.tenantId);return f.documentBytes;}};const documentStorage=createDocumentRecoveryAdapter({db:f.db,tenantId:f.tenantId,objectStorage});assert.equal((await f.backup({documentStorage})).externalDocumentRevisions,1);assert.equal(requested.sha256,sha(f.documentBytes));});
