import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {transformSync} from 'esbuild';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
function harness(){let index=0,state=[],effects=[],keys=[];const mock={...React,useState(initial){const i=index++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return[state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){return state[index++]??=({current:initial});},useEffect(effect,deps){const i=index++;if(!keys[i]||!deps||deps.some((d,j)=>d!==keys[i][j])){keys[i]=deps;effects.push(effect);}}};const module={exports:{}},require=id=>id==='react'?mock:new Proxy({},{get:()=>()=>null});new Function('React','require','module','exports',transformSync(readFileSync(new URL('../src/features/CommunicationWorkflows.jsx',import.meta.url),'utf8'),{loader:'jsx',format:'cjs'}).code)(React,require,module,module.exports);return props=>{index=0;const tree=module.exports.default(props),pending=effects;effects=[];pending.forEach(e=>e());return tree;};}
function find(tree,p){if(!tree||typeof tree!=='object')return null;if(p(tree))return tree;for(const c of React.Children.toArray(tree.props?.children)){const r=find(c,p);if(r)return r;}return null;}
const button=(t,text)=>find(t,e=>e.type==='button'&&React.Children.toArray(e.props.children).includes(text)),flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
const a={id:'a1',name:'Community partners',version:2,status:'Active'},t={id:'t1',name:'Welcome',kind:'Messaging',version:3,subject:'Hello {{recipientName}}',body:'Welcome aboard.'},p={audience:a,sourceDigest:'a'.repeat(64),totalCount:8,matchedCount:5,eligibleCount:3,excludedCount:5};
async function ready(extra={}){const calls=[],render=harness(),props={api:async(path,options)=>{calls.push([path,options]);return path==='/communication-workflows'&&options?.method==='POST'?{workflow:{id:'w1',name:'Welcome flow',status:'Active',version:1,ownerId:'u1'},historicalBackfill:false}:path==='/communication-workflows'?{workflows:[]}:path==='/audiences'?{audiences:[a]}:path==='/correspondence/templates'?{templates:[t]}:path.includes('/preview?')?p:{workflow:{id:'w1',name:'Welcome flow',status:'Active',version:1,ownerId:'u1'},historicalBackfill:false};},user:{id:'u1',role:'staff'},data:{constituents:[]},...extra};render(props);await flush();let tree=render(props);find(tree,e=>e.type==='input'&&e.props.placeholder==='Welcome new community partners').props.onChange({target:{value:'Welcome flow'}});tree=render(props);const selects=[];function collect(e){if(!e||typeof e!=='object')return;if(e.type==='select')selects.push(e);React.Children.toArray(e.props?.children).forEach(collect);}collect(tree);selects[0].props.onChange({target:{value:a.id}});selects[1].props.onChange({target:{value:t.id}});tree=render(props);return {render,props,calls,tree};}
test('workflow activation requires explicit baseline review and confirms no historical backfill; format changes invalidate it',async()=>{const s=await ready();assert.ok(button(s.tree,'Activate draft workflow').props.disabled);await button(s.tree,'Review activation baseline').props.onClick();let tree=s.render(s.props);let html=renderToStaticMarkup(tree);assert.match(html,/3<\/strong><span>Existing eligible profiles · no drafts/);assert.match(html,/Nothing is sent/);find(tree,e=>e.type==='input'&&e.props.type==='checkbox').props.onChange({target:{checked:true}});tree=s.render(s.props);assert.equal(Boolean(button(tree,'Activate draft workflow').props.disabled),false);find(tree,e=>e.type==='select'&&e.props.value==='Print').props.onChange({target:{value:'Email draft'}});tree=s.render(s.props);assert.ok(button(tree,'Activate draft workflow').props.disabled);assert.equal(find(tree,e=>e.type==='input'&&e.props.type==='checkbox'),null);});
test('current workspace changes reject a late baseline review without activating a stale rule',async()=>{let resolve;const s=await ready();const normal=s.props.api;s.props.api=(path,o)=>path.includes('/preview?')?new Promise(r=>resolve=r):normal(path,o);let tree=s.render(s.props);await flush();tree=s.render(s.props);const pending=button(tree,'Review activation baseline').props.onClick();s.props.data={constituents:[]};s.render(s.props);resolve(p);await pending;tree=s.render(s.props);assert.ok(button(tree,'Activate draft workflow').props.disabled);assert.equal(find(tree,e=>e.type==='input'&&e.props.type==='checkbox'),null);assert.equal(s.calls.filter(([path,o])=>path==='/communication-workflows'&&o?.method==='POST').length,0);});
test('double submission makes one strictly reviewed activation and resets the confirmed baseline',async()=>{const s=await ready();await button(s.tree,'Review activation baseline').props.onClick();let tree=s.render(s.props);find(tree,e=>e.type==='input'&&e.props.type==='checkbox').props.onChange({target:{checked:true}});tree=s.render(s.props);const form=find(tree,e=>e.type==='form'),preventDefault=()=>{};await Promise.all([form.props.onSubmit({preventDefault}),form.props.onSubmit({preventDefault})]);await flush();const posts=s.calls.filter(([path,o])=>path==='/communication-workflows'&&o?.method==='POST');assert.equal(posts.length,1);assert.deepEqual(posts[0][1].body,{name:'Welcome flow',audienceId:'a1',audienceVersion:2,sourceDigest:'a'.repeat(64),templateId:'t1',templateVersion:3,channel:'Print',confirmed:true});tree=s.render(s.props);assert.match(renderToStaticMarkup(tree),/no historical drafts were created/);});
test('viewers see operational history without an activation form',async()=>{const s=await readyViewer();assert.equal(find(s.tree,e=>e.type==='form'),null);assert.match(renderToStaticMarkup(s.tree),/Activation register/);});
async function readyViewer(){const render=harness(),props={user:{role:'viewer'},data:{},api:async path=>path==='/communication-workflows'?{workflows:[]}:path==='/audiences'?{audiences:[]}:{templates:[]}};render(props);await flush();return{tree:render(props)};}

test('ordinary parent UI rerenders preserve reviewed source authorization when the constituent corpus is unchanged',async()=>{const s=await ready();await button(s.tree,'Review activation baseline').props.onClick();let tree=s.render(s.props);find(tree,e=>e.type==='input'&&e.props.type==='checkbox').props.onChange({target:{checked:true}});s.props.data={...s.props.data,taskOwners:[]};tree=s.render(s.props);tree=s.render(s.props);assert.equal(Boolean(button(tree,'Activate draft workflow').props.disabled),false);});

test('failed activation retains reviewed inputs but removes stale confirmation and never retries the POST automatically',async()=>{let posts=0;const s=await ready({api:async(path,o)=>{if(o?.method==='POST'){posts++;throw Object.assign(new Error('Audience source changed. Review again.'),{status:409});}return path==='/communication-workflows'?{workflows:[]}:path==='/audiences'?{audiences:[a]}:path==='/correspondence/templates'?{templates:[t]}:p;}});await button(s.tree,'Review activation baseline').props.onClick();let tree=s.render(s.props);find(tree,e=>e.type==='input'&&e.props.type==='checkbox').props.onChange({target:{checked:true}});tree=s.render(s.props);await find(tree,e=>e.type==='form').props.onSubmit({preventDefault(){}});await flush();tree=s.render(s.props);assert.equal(posts,1);assert.equal(find(tree,e=>e.type==='input'&&e.props.placeholder==='Welcome new community partners').props.value,'Welcome flow');assert.equal(find(tree,e=>e.type==='input'&&e.props.type==='checkbox'),null);assert.ok(button(tree,'Activate draft workflow').props.disabled);assert.match(renderToStaticMarkup(tree),/Audience source changed/);});
