import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createApp} from '../server/app.js';

const password='SyntheticProspectiveWorkflow!2026';
async function fixture(t,{subject='Hello {{recipientName}}'}={}){
 const dir=await mkdtemp(join(tmpdir(),'wimblo-prospective-workflow-')),tenantId=randomUUID();let time=Date.parse('2026-09-13T12:00:00.000Z');const app=createApp({dbPath:join(dir,'workspace.sqlite'),seed:false,tenantId,initialAdmin:{name:'Workflow administrator',email:'admin.workflows@example.test',password},mfaKey:'',reminderWorker:false,workflowClock:()=>time,workflowWorker:false}),db=app.locals.db,server=app.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{await new Promise(r=>server.close(r));app.locals.close();await rm(dir,{recursive:true,force:true});});const base=`http://127.0.0.1:${server.address().port}/api`;
 async function login(){const r=await fetch(base+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'admin.workflows@example.test',password})});assert.equal(r.status,200);return {...await r.json(),cookie:r.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ')};}const admin=await login();
 async function request(path,{method='GET',body,session=admin,csrf=true}={}){const r=await fetch(base+path,{method,headers:{...(body!==undefined?{'Content-Type':'application/json'}:{}),...(session?{Cookie:session.cookie,...(csrf?{'X-CSRF-Token':session.csrfToken}:{})}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});const text=await r.text();let json;try{json=JSON.parse(text);}catch{}return {status:r.status,json,text};}
 async function create(collection,body){const r=await request('/records/'+collection,{method:'POST',body});assert.equal(r.status,201,r.text);return r.json.record;}async function person(name,changes={}){return create('constituents',{name,type:'Individual',preference:'Email',email:name.toLowerCase().replaceAll(' ','')+'@example.test',segments:'Welcome',...changes});}
 const baseline=await person('Baseline person'),a=await request('/audiences',{method:'POST',body:{name:'Prospective welcome audience',filters:{segmentTokens:['Welcome'],segmentMatch:'Any',types:[],preferences:[]}}});assert.equal(a.status,201,a.text);const audience=a.json.audience,templateResponse=await request('/correspondence/templates',{method:'POST',body:{name:'Prospective greeting',kind:'Messaging',subject,body:'Welcome to {{organizationName}}, {{recipientName}}.'}});assert.equal(templateResponse.status,201,templateResponse.text);const template=templateResponse.json.template;
 async function arm(channel='Email draft'){const p=await request(`/audiences/${audience.id}/preview?version=1&channel=${encodeURIComponent(channel)}`);assert.equal(p.status,200,p.text);const r=await request('/communication-workflows',{method:'POST',body:{name:'Reviewed prospective draft rule',audienceId:audience.id,audienceVersion:1,sourceDigest:p.json.sourceDigest,templateId:template.id,templateVersion:1,channel,confirmed:true}});assert.equal(r.status,201,r.text);return r.json.workflow;}
 const rows=table=>db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all();const communications=()=>db.prepare("SELECT * FROM records WHERE collection='communications' ORDER BY id").all();const evidence=()=>db.prepare("SELECT * FROM records WHERE collection IN ('gifts','grants') ORDER BY collection,id").all();
 return {app,db,admin,request,create,person,baseline,audience,template,arm,rows,communications,evidence,run:(at=time)=>app.locals.runCommunicationWorkflows(at),get time(){return time;},advance:delta=>time+=delta};
}

test('reviewed prospective membership produces only one native plain-text Messaging Draft and never financial/receipt actions',async t=>{
 const f=await fixture(t),fund=await f.create('designations',{name:'Existing fund'});await f.create('gifts',{constituentId:f.baseline.id,amount:10001,type:'Cash',method:'Check',date:'2026-09-13',allocations:[{designationId:fund.id,amount:10001}]});const before=f.evidence(),workflow=await f.arm();assert.equal(workflow.baselineCount,1);assert.equal(workflow.sourceCurrent,true);assert.equal(f.communications().length,0);assert.equal(f.run().drafted,0);
 const entrant=await f.person('New eligible person'),result=f.run();assert.equal(result.queued,1);assert.equal(result.drafted,1);const native=JSON.parse(f.communications()[0].data);assert.equal(native.constituentId,entrant.id);assert.equal(native.status,'Draft');assert.equal(native.channel,'Email');assert.equal(native.subject,'Hello New eligible person');assert.match(native.body,/Prepared correspondence only; no message has been sent\./);assert.equal(f.rows('correspondence_preparations').length,0);assert.equal(f.rows('correspondence_finalizations').length,0);assert.equal(f.rows('correspondence_fulfillments').length,0);assert.deepEqual(f.evidence(),before);assert.equal(f.run().drafted,0);assert.equal(f.rows('communication_workflow_executions').length,1);const history=await f.request('/communication-workflows/'+workflow.id),drafted=history.json.outcomes.find(row=>row.status==='Drafted');assert.equal(drafted.communicationId,native.id);assert.equal(drafted.communicationVersion,1);assert.ok(!history.json.outcomes.find(row=>row.status==='Armed').communicationId);
});

test('eligible profile edits and baseline membership do not backfill; observed leave/re-entry creates exactly one new episode',async t=>{
 const f=await fixture(t),workflow=await f.arm();assert.equal((await f.request('/records/constituents/'+f.baseline.id,{method:'PATCH',body:{version:1,name:'Unrelated baseline name correction'}})).status,200);assert.equal(f.run().drafted,0);const entrant=await f.person('Episode person');assert.equal(f.run().drafted,1);assert.equal((await f.request('/records/constituents/'+entrant.id,{method:'PATCH',body:{version:1,notes:'Unrelated eligible profile edit'}})).status,200);assert.equal(f.run().drafted,0);
 assert.equal((await f.request('/records/constituents/'+entrant.id,{method:'PATCH',body:{version:2,segments:'Other'}})).status,200);assert.equal(f.run().drafted,0);assert.equal((await f.request('/records/constituents/'+entrant.id,{method:'PATCH',body:{version:3,segments:'Welcome'}})).status,200);assert.equal(f.run().drafted,1);assert.deepEqual(f.rows('communication_workflow_executions').map(row=>row.episode).sort(),[1,2]);assert.equal(f.rows('communication_workflow_entries').length,2);assert.equal((await f.request('/communication-workflows/'+workflow.id)).json.workflow.baselineCount,1);
});

test('native subject limits fail safely with durable timed retries and terminal membership suppression',async t=>{
 const f=await fixture(t,{subject:'X'.repeat(250)+' {{recipientName}}'});await f.arm();await f.person('Long subject entrant');const first=f.run();assert.equal(first.drafted,0);assert.equal(first.failed,1);assert.equal(f.communications().length,0);assert.equal(f.rows('communication_workflow_executions').length,0);assert.equal(f.rows('communication_workflow_entries')[0].attempt_count,1);assert.ok(f.rows('communication_workflow_outcomes').some(row=>row.status==='Failed'&&row.retry_at===new Date(f.time+60000).toISOString()));
 f.advance(59999);assert.equal(f.run().failed,0);f.advance(1);assert.equal(f.run().failed,1);for(let n=0;n<3;n++){f.advance(60000);assert.equal(f.run().failed,1);}assert.equal(f.rows('communication_workflow_entries')[0].status,'Suppressed');assert.equal(f.communications().length,0);assert.equal(f.rows('communication_workflow_executions').length,0);assert.equal(f.run().drafted,0);
});

test('after-insert native draft corruption and source changes cannot leave a false successful execution',async t=>{
 const f=await fixture(t);await f.arm();await f.person('Persistence entrant');f.db.exec("CREATE TRIGGER synthetic_workflow_draft_fault AFTER INSERT ON records WHEN NEW.collection='communications' BEGIN UPDATE records SET data=json_set(data,'$.subject','Corrupted persisted native wording') WHERE collection=NEW.collection AND id=NEW.id; END;");const first=f.run();assert.equal(first.drafted,0);assert.equal(first.failed,1);assert.equal(f.communications().length,0);assert.equal(f.rows('communication_workflow_executions').length,0);f.db.exec('DROP TRIGGER synthetic_workflow_draft_fault');f.advance(60000);assert.equal(f.run().drafted,1);assert.equal(f.rows('communication_workflow_executions').length,1);assert.equal(f.rows('communication_workflow_entries')[0].attempt_count,2);
 const another=await f.person('Guarded source entrant');f.db.exec("CREATE TRIGGER synthetic_workflow_source_fault AFTER INSERT ON audit WHEN NEW.action='draft_communication_workflow' BEGIN UPDATE records SET data=json_set(data,'$.preference','Do not contact','$.version',2) WHERE collection='constituents' AND id='"+another.id+"'; END;");const failed=f.run();assert.equal(failed.drafted,0);assert.equal(failed.failed,1);assert.equal(f.communications().length,1);assert.equal(f.rows('communication_workflow_executions').length,1);assert.equal(JSON.parse(f.db.prepare("SELECT data FROM records WHERE collection='constituents' AND id=?").get(another.id).data).preference,'Email');
});

test('Print preserves actual non-DNC contact rules and current origin stays truthful after source exclusion',async t=>{
 const f=await fixture(t),workflow=await f.arm('Print'),entrant=await f.person('Postal entrant',{preference:'Phone',email:''});assert.equal(f.run().drafted,1);const native=JSON.parse(f.communications()[0].data);assert.equal(native.channel,'Post');const current=await f.request('/workspace');assert.equal(current.status,200);const currentRecord=current.json.data.communications.find(record=>record.id===native.id);assert.equal(currentRecord.workflowOrigin.sourceCurrent,true);assert.equal(currentRecord.workflowOrigin.delivery,'Not sent');assert.equal(currentRecord.workflowOrigin.reviewRequired,true);
 assert.equal((await f.request('/records/constituents/'+entrant.id,{method:'PATCH',body:{version:1,preference:'Do not contact'}})).status,200);const retained=await f.request('/workspace');assert.equal(retained.status,200);const retainedRecord=retained.json.data.communications.find(record=>record.id===native.id);assert.equal(retainedRecord.workflowOrigin.sourceCurrent,false);assert.equal(retainedRecord.body,native.body);assert.equal((await f.request('/records/communications/'+native.id,{method:'DELETE',body:{version:1}})).status,409);assert.equal(f.run().drafted,0);
 const detail=await f.request('/communication-workflows/'+workflow.id);assert.equal(detail.status,200);assert.doesNotMatch(detail.text,/owner_binding|security_binding|encrypted_secret|wording_digest/);for(const table of ['communication_workflow_executions','communication_workflow_outcomes']){assert.throws(()=>f.db.exec('DELETE FROM '+table),/retained/);assert.throws(()=>f.db.exec('UPDATE '+table+" SET at='corrupt'"),/immutable/);}
});

test('oversized current corpus terminally suppresses the bounded activation without partial watermark/backfill effects',async t=>{
 const f=await fixture(t),workflow=await f.arm(),baseline=JSON.parse(f.db.prepare("SELECT data FROM records WHERE collection='constituents' AND id=?").get(f.baseline.id).data),insert=f.db.prepare('INSERT INTO records(collection,id,data) VALUES(?,?,?)');
 f.db.exec('BEGIN IMMEDIATE');try{for(let i=0;i<1000;i++){const key=randomUUID();insert.run('constituents',key,JSON.stringify({...baseline,id:key,name:'Bounded fixture profile '+i,email:'bounded'+i+'@example.test'}));}f.db.exec('COMMIT');}catch(e){f.db.exec('ROLLBACK');throw e;}
 const result=f.run();assert.equal(result.drafted,0);assert.equal(result.suppressed,1);assert.equal(f.communications().length,0);assert.equal(f.rows('communication_workflow_entries').length,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM communication_workflow_memberships WHERE workflow_id=?').get(workflow.id).n,1);const closed=await f.request('/communication-workflows/'+workflow.id);assert.equal(closed.status,200);assert.equal(closed.json.workflow.status,'Suppressed');assert.equal(closed.json.workflow.sourceCurrent,false);assert.equal((await f.request('/communication-workflows/'+workflow.id+'/retire',{method:'POST',body:{version:2,reason:'Cannot revive a closed activation'}})).status,409);assert.throws(()=>f.db.prepare("UPDATE communication_workflows SET status='Active' WHERE id=?").run(workflow.id),/cannot resume/);
});
