import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../server/app.js';
import {backupWorkspace,restoreWorkspace} from '../server/backup.js';
import {toCSV} from '../src/lib.js';

const password='SyntheticWorkflowReporting!2026';
const sources=['communicationWorkflows','communicationWorkflowMemberships','communicationWorkflowEntries','communicationWorkflowExecutions','communicationWorkflowOutcomes'];
async function fixture(t){
 const dir=await mkdtemp(join(tmpdir(),'wimblo-workflow-reporting-')),dbPath=join(dir,'workspace.sqlite'),tenantId=randomUUID(),time=Date.now(),initialAdmin={name:'Synthetic workflow reporting administrator',email:'admin.workflow.reporting@example.test',password};
 let app,server,base,sessions={};
 async function close(){if(server)await new Promise(resolve=>server.close(resolve));server=null;app?.locals.close();app=null;}
 async function request(path,{method='GET',body,session=sessions.admin}={}){const r=await fetch(base+'/api'+path,{method,headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrfToken}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const text=await r.text();let json;try{json=JSON.parse(text);}catch{json=null;}return {status:r.status,json,text,headers:r.headers};}
 async function login(email=initialAdmin.email){const r=await request('/auth/login',{method:'POST',body:{email,password},session:null});assert.equal(r.status,200,r.text);return {...r.json,cookie:r.headers.getSetCookie().map(value=>value.split(';')[0]).join('; ')};}
 async function open(path=dbPath){app=createApp({dbPath:path,seed:false,tenantId,initialAdmin,mfaKey:'',workflowClock:()=>time,workflowWorker:false,reminderWorker:false});server=app.listen(0,'127.0.0.1');await once(server,'listening');base='http://127.0.0.1:'+server.address().port;sessions.admin=await login();}
 await open();t.after(async()=>{await close();await rm(dir,{recursive:true,force:true});});
 for(const role of ['staff','viewer','event-helper']){const email=role+'.workflow.reporting@example.test';assert.equal((await request('/users',{method:'POST',body:{name:'Synthetic reporting '+role,email,password,role}})).status,201);sessions[role]=await login(email);}
 async function create(collection,body){const r=await request('/records/'+collection,{method:'POST',body});assert.equal(r.status,201,r.text);return r.json.record;}
 const baseline=await create('constituents',{name:'Baseline eligible recipient',type:'Individual',preference:'Email',email:'PRIVATE_BASELINE_EMAIL@example.test',segments:'Welcome'}),entrant=await create('constituents',{name:'Prospective recipient',type:'Individual',preference:'Email',email:'PRIVATE_RECIPIENT_EMAIL@example.test',segments:'Other',notes:'PRIVATE_SOURCE_NOTES'}),fund=await create('designations',{name:'Existing fund'});
 await create('gifts',{constituentId:baseline.id,amount:10001,type:'Cash',method:'Check',date:new Date(time).toISOString().slice(0,10),allocations:[{designationId:fund.id,amount:10001}]});
 const financial=()=>app.locals.db.prepare("SELECT * FROM records WHERE collection IN ('gifts','pledges','grants') ORDER BY collection,id").all(),beforeFinance=financial();
 const audience=await request('/audiences',{method:'POST',body:{name:'Prospective reviewed audience',filters:{segmentTokens:['Welcome'],segmentMatch:'Any',types:[],preferences:[]}}});assert.equal(audience.status,201,audience.text);
 const template=await request('/correspondence/templates',{method:'POST',body:{name:'Reviewed Messaging template',kind:'Messaging',subject:'Welcome {{recipientName}}',body:'PRIVATE_MESSAGE_BODY Hello {{recipientName}} from {{organizationName}}.'}});assert.equal(template.status,201,template.text);
 const preview=await request('/audiences/'+audience.json.audience.id+'/preview?version=1&channel=Email%20draft');assert.equal(preview.status,200,preview.text);
 const armed=await request('/communication-workflows',{method:'POST',body:{name:'Prospective Messaging activation',audienceId:audience.json.audience.id,audienceVersion:1,sourceDigest:preview.json.sourceDigest,templateId:template.json.template.id,templateVersion:1,channel:'Email draft',confirmed:true}});assert.equal(armed.status,201,armed.text);
 assert.equal(app.locals.runCommunicationWorkflows(time).drafted,0);
 const update=await request('/records/constituents/'+entrant.id,{method:'PATCH',body:{version:entrant.version,segments:'Welcome'}});assert.equal(update.status,200,update.text);
 const worked=app.locals.runCommunicationWorkflows(time);assert.equal(worked.drafted,1);assert.deepEqual(financial(),beforeFinance);
 const execution=app.locals.db.prepare('SELECT * FROM communication_workflow_executions').get(),entry=app.locals.db.prepare('SELECT * FROM communication_workflow_entries').get();assert.ok(execution);
 const report=(entity,columns,session=sessions.admin,extra={})=>request('/custom-reports/run',{method:'POST',session,body:{name:'Curated prospective workflow report',entity,columns,...extra}});
 return {dir,tenantId,time,baseline,entrant:update.json.record,workflow:armed.json.workflow,audience:audience.json.audience,template:template.json.template,execution,entry,request,report,financial,beforeFinance,login,close,open,get sessions(){return sessions;},get db(){return app.locals.db;},get app(){return app;}};
}

test('curated workflow reports distinguish prospective baselines, observed episodes and native unsent drafts',async t=>{
 const f=await fixture(t),rule=await f.report('communicationWorkflows',['id','revision','audienceRevision','templateRevision','baselineCount','status','delivery']);assert.equal(rule.status,200,rule.text);assert.equal(rule.json.requiredRole,'admin');assert.deepEqual(rule.json.rows,[[f.workflow.id,1,1,1,1,'Active','Not sent']]);
 const members=await f.report('communicationWorkflowMemberships',['constituentId','eligible','episode','sourceRevision']);assert.equal(members.status,200,members.text);assert.deepEqual(members.json.rows.map(row=>JSON.stringify(row)).sort(),[[f.baseline.id,true,0,1],[f.entrant.id,true,1,2]].map(JSON.stringify).sort());
 const entry=await f.report('communicationWorkflowEntries',['id','workflowId','episode','sourceRevision','status','revision','attemptCount','nextAttempt']);assert.equal(entry.status,200,entry.text);assert.deepEqual(entry.json.rows,[[f.entry.id,f.workflow.id,1,2,'Drafted',2,1,null]]);
 const executions=await f.report('communicationWorkflowExecutions',['entryId','workflowId','constituentId','episode','sourceRevision','audienceRevision','templateRevision','communicationId','communicationRevision','at','sourceCurrent','reviewRequired','delivery']);assert.equal(executions.status,200,executions.text);assert.deepEqual(executions.json.rows,[[f.entry.id,f.workflow.id,f.entrant.id,1,2,1,1,f.execution.communication_id,1,new Date(f.time).toISOString(),true,true,'Not sent']]);assert.deepEqual(executions.json.recordReferences,[{collection:'communications',id:f.execution.communication_id}]);
 const outcomes=await f.report('communicationWorkflowOutcomes',['status'],undefined,{groupBy:['status'],aggregates:[{op:'count'}]});assert.equal(outcomes.status,200,outcomes.text);assert.deepEqual(outcomes.json.rows.map(row=>JSON.stringify(row)).sort(),[['Armed',1],['Drafted',1]].map(JSON.stringify).sort());
 assert.equal(f.app.locals.runCommunicationWorkflows(f.time).drafted,0);assert.equal(f.db.prepare('SELECT count(*) n FROM communication_workflow_executions').get().n,1);assert.deepEqual(f.financial(),f.beforeFinance);
 const catalog=await f.request('/custom-reports/catalog');for(const source of sources){const entity=catalog.json.entities.find(e=>e.id===source);assert.ok(entity,source);assert.equal(entity.requiredRole,'admin');assert.match(entity.description,/not.*sent|delivery is Not sent/);assert.ok(!entity.fields.some(field=>/binding|digest|snapshot|body|subject|email|proof|provider/i.test(field.key)));for(const forbidden of ['body','subject','email','owner_binding','security_binding','source_digest','wording_digest','snapshot','providerReference','proof'])assert.equal((await f.report(source,[forbidden])).status,400,source+':'+forbidden);const safe=await f.report(source,entity.fields.map(field=>field.key).slice(0,20));assert.equal(safe.status,200,safe.text);assert.doesNotMatch(safe.text,/PRIVATE_MESSAGE_BODY|PRIVATE_RECIPIENT_EMAIL|PRIVATE_BASELINE_EMAIL|PRIVATE_SOURCE_NOTES|security_binding|source_digest/);}
});

test('current recipient consent changes mark execution history stale without manufacturing sends or income',async t=>{
 const f=await fixture(t),before=await f.report('communicationWorkflowExecutions',['sourceRevision','communicationRevision','at','sourceCurrent','delivery']);assert.equal(before.status,200,before.text);assert.equal(before.json.rows[0][3],true);
 const optedOut=await f.request('/records/constituents/'+f.entrant.id,{method:'PATCH',body:{version:f.entrant.version,preference:'Do not contact'}});assert.equal(optedOut.status,200,optedOut.text);
 const after=await f.report('communicationWorkflowExecutions',['sourceRevision','communicationRevision','at','sourceCurrent','delivery']);assert.equal(after.status,200,after.text);assert.deepEqual(after.json.rows,[[2,1,new Date(f.time).toISOString(),false,'Not sent']]);
 const retained=await f.request('/workspace',{session:f.sessions.viewer});assert.equal(retained.status,200,retained.text);const draft=retained.json.data.communications.find(record=>record.id===f.execution.communication_id);assert.equal(draft.status,'Draft');assert.match(draft.body,/PRIVATE_MESSAGE_BODY/);assert.equal(draft.workflowOrigin.sourceCurrent,false);assert.equal(draft.workflowOrigin.reviewRequired,true);assert.equal(draft.workflowOrigin.delivery,'Not sent');assert.equal(f.app.locals.runCommunicationWorkflows(f.time).drafted,0);assert.deepEqual(f.financial(),f.beforeFinance);assert.equal(f.db.prepare('SELECT count(*) n FROM communication_workflow_executions').get().n,1);
});

test('workflow sources and retained scheduled results deny staff, viewer, helpers and downgraded administrators',async t=>{
 const f=await fixture(t);for(const role of ['staff','viewer','event-helper']){const session=f.sessions[role],catalog=await f.request('/custom-reports/catalog',{session});assert.equal(catalog.status,role==='event-helper'?403:200);if(catalog.status===200)assert.ok(!catalog.json.entities.some(e=>sources.includes(e.id)));for(const source of sources)assert.equal((await f.report(source,['id'],session)).status,403);}
 assert.equal((await f.report('communicationWorkflowExecutions',['id'],null)).status,401);
 const saved=await f.request('/custom-reports',{method:'POST',body:{name:'Retained workflow draft facts',entity:'communicationWorkflowExecutions',columns:['communicationId','sourceRevision','sourceCurrent','delivery']}});assert.equal(saved.status,201,saved.text);
 const startAt=new Date(Date.now()+30000).toISOString(),schedule=await f.request('/report-schedules',{method:'POST',body:{name:'Retained workflow draft facts',reportId:saved.json.report.id,cadence:'Daily',startAt}});assert.equal(schedule.status,201,schedule.text);assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1).produced,1);
 const delivery=f.db.prepare('SELECT id,result FROM report_deliveries WHERE schedule_id=?').get(schedule.json.schedule.id);assert.equal(JSON.parse(delivery.result).requiredRole,'admin');for(const role of ['staff','viewer','event-helper'])assert.equal((await f.request('/report-deliveries/'+delivery.id,{session:f.sessions[role]})).status,403);
 assert.equal((await f.request('/users',{method:'POST',body:{name:'Second synthetic administrator',email:'second.workflow.reporting@example.test',password,role:'admin'}})).status,201);assert.equal((await f.request('/users/'+f.sessions.admin.user.id,{method:'PATCH',body:{version:1,role:'staff',active:true}})).status,200);
 const downgraded=await f.login();assert.equal((await f.request('/report-deliveries/'+delivery.id,{session:downgraded})).status,403);assert.equal((await f.request('/custom-reports/'+saved.json.report.id+'/run',{session:downgraded})).status,403);assert.ok(!(await f.request('/custom-reports',{session:downgraded})).json.reports.some(report=>report.id===saved.json.report.id));
});

test('encrypted offline recovery keeps exact workflow source history and triggers, clears sessions and closes restored activation',async t=>{
 const f=await fixture(t),tables=['communication_workflows','communication_workflow_memberships','communication_workflow_entries','communication_workflow_executions','communication_workflow_outcomes'],before=Object.fromEntries(tables.map(table=>[table,f.db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all()])),triggers=f.db.prepare("SELECT name,sql FROM sqlite_schema WHERE type='trigger' AND name LIKE 'communication_workflow%' ORDER BY name").all();
 const key=randomBytes(32).toString('hex'),archivePath=join(f.dir,'workflow.wbackup'),destinationPath=join(f.dir,'restored.sqlite'),backup=await backupWorkspace({db:f.db,tenantId:f.tenantId,encryptionKey:key,outputPath:archivePath});for(const table of tables)assert.equal(backup.tables.find(row=>row.name===table).count,before[table].length);assert.ok(!(await readFile(archivePath)).includes(Buffer.from('PRIVATE_MESSAGE_BODY')));
 await assert.rejects(restoreWorkspace({archivePath,destinationPath:join(f.dir,'wrong-tenant.sqlite'),expectedTenantId:randomUUID(),encryptionKey:key}),/expected tenant/);
 const recovered=await restoreWorkspace({archivePath,destinationPath,expectedTenantId:f.tenantId,encryptionKey:key});assert.equal(recovered.sourceSha256,backup.sourceSha256);assert.ok(recovered.cleared.sessions>0);assert.ok(recovered.automationRecoveryMarker.id);
 const copy=new DatabaseSync(destinationPath);try{for(const table of tables)assert.deepEqual(copy.prepare('SELECT * FROM '+table+' ORDER BY rowid').all(),before[table]);assert.deepEqual(copy.prepare("SELECT name,sql FROM sqlite_schema WHERE type='trigger' AND name LIKE 'communication_workflow%' ORDER BY name").all(),triggers);assert.throws(()=>copy.exec('DELETE FROM communication_workflow_executions'),/retained/);assert.throws(()=>copy.exec("UPDATE communication_workflow_outcomes SET reason='tampered'"),/immutable/);assert.equal(copy.prepare('SELECT count(*) n FROM sessions').get().n,0);assert.equal(copy.prepare('SELECT count(*) n FROM mfa_challenges').get().n,0);assert.deepEqual(copy.prepare("SELECT * FROM records WHERE collection IN ('gifts','pledges','grants') ORDER BY collection,id").all(),f.beforeFinance);}finally{copy.close();}
 const old=f.sessions.admin;await f.close();await f.open(destinationPath);assert.equal((await f.request('/custom-reports/catalog',{session:old})).status,401);
 const beforeRun=await f.report('communicationWorkflowExecutions',['communicationId','sourceRevision','audienceRevision','templateRevision','episode','at','sourceCurrent','delivery']);assert.equal(beforeRun.status,200,beforeRun.text);assert.deepEqual(beforeRun.json.rows,[[f.execution.communication_id,2,1,1,1,new Date(f.time).toISOString(),false,'Not sent']]);
 const run=f.app.locals.runCommunicationWorkflows(f.time);assert.equal(run.drafted,0);assert.equal(run.suppressed,1);assert.equal(f.db.prepare('SELECT status FROM communication_workflows').get().status,'Suppressed');assert.deepEqual(f.db.prepare('SELECT * FROM communication_workflow_executions ORDER BY rowid').all(),before.communication_workflow_executions);assert.deepEqual(f.db.prepare('SELECT * FROM communication_workflow_outcomes ORDER BY rowid LIMIT 2').all(),before.communication_workflow_outcomes);const suppressed=await f.report('communicationWorkflowOutcomes',['status','reason'],undefined,{filters:[{field:'status',op:'eq',value:'Suppressed'}]});assert.equal(suppressed.status,200,suppressed.text);assert.equal(suppressed.json.rows.length,1);assert.match(suppressed.json.rows[0][1],/Workspace restored/);assert.deepEqual(f.financial(),f.beforeFinance);
});

test('broken retained execution linkage fails closed rather than disappearing from workflow counts',async t=>{
 const f=await fixture(t),guard=f.db.prepare("SELECT sql FROM sqlite_schema WHERE name='communication_workflow_execution_no_update'").get().sql;
 f.db.exec('PRAGMA foreign_keys=OFF; DROP TRIGGER communication_workflow_execution_no_update');f.db.prepare('UPDATE communication_workflow_executions SET entry_id=? WHERE id=?').run(randomUUID(),f.execution.id);
 const report=await f.report('communicationWorkflowExecutions',['id'],undefined,{aggregates:[{op:'count'}]});assert.equal(report.status,503,report.text);assert.doesNotMatch(report.text,/PRIVATE_MESSAGE_BODY|PRIVATE_RECIPIENT_EMAIL|source_digest|security_binding/);assert.equal((await f.report('communicationWorkflowExecutions',['id'],f.sessions.staff)).status,403);
 f.db.prepare('UPDATE communication_workflow_executions SET entry_id=? WHERE id=?').run(f.entry.id,f.execution.id);f.db.exec(guard);f.db.exec('PRAGMA foreign_keys=ON');const valid=await f.report('communicationWorkflowExecutions',['id'],undefined,{aggregates:[{op:'count'}]});assert.equal(valid.status,200,valid.text);assert.deepEqual(valid.json.rows,[[1]]);assert.deepEqual(f.financial(),f.beforeFinance);
});


test('saved native Draft reports and visible CSV exports retain truthful current-source and Not sent origin after opt-out',async t=>{
 const f=await fixture(t),columns=['body','status','workflowOrigin.sourceCurrent','workflowOrigin.delivery','workflowOrigin.reviewRequired','workflowOrigin.producedAt'];
 const catalog=await f.request('/custom-reports/catalog',{session:f.sessions.viewer}),entity=catalog.json.entities.find(e=>e.id==='communications');assert.match(entity.description,/authorized history/);for(const key of columns)assert.ok(entity.fields.some(field=>field.key===key),key);assert.equal(entity.fields.find(field=>field.key==='workflowOrigin.producedAt').type,'date');
 const saved=await f.request('/custom-reports',{method:'POST',session:f.sessions.staff,body:{name:'Native draft origin review',entity:'communications',columns}});assert.equal(saved.status,201,saved.text);
 const current=await f.request('/custom-reports/'+saved.json.report.id+'/run',{session:f.sessions.viewer});assert.equal(current.status,200,current.text);assert.equal(current.json.rows[0][2],true);assert.deepEqual(current.json.rows[0].slice(1),['Draft',true,'Not sent',true,new Date(f.time).toISOString()]);
 const changed=await f.request('/records/constituents/'+f.entrant.id,{method:'PATCH',body:{version:f.entrant.version,preference:'Do not contact'}});assert.equal(changed.status,200,changed.text);
 const historical=await f.request('/custom-reports/'+saved.json.report.id+'/run',{session:f.sessions.viewer});assert.equal(historical.status,200,historical.text);assert.match(historical.json.rows[0][0],/PRIVATE_MESSAGE_BODY/);assert.deepEqual(historical.json.rows[0].slice(1),['Draft',false,'Not sent',true,new Date(f.time).toISOString()]);assert.doesNotMatch(historical.text,/PRIVATE_RECIPIENT_EMAIL|PRIVATE_SOURCE_NOTES|security_binding|source_digest|communication_digest/);
 const csv=toCSV(historical.json.columns.map(c=>c.label),historical.json.rows.map(row=>row.map(value=>value==null?'':String(value))));assert.match(csv,/Workflow Origin · source Current/i);assert.match(csv,/"false","Not sent","true"/);assert.match(csv,/PRIVATE_MESSAGE_BODY/);assert.deepEqual(f.financial(),f.beforeFinance);
});
