import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {createApp} from '../server/app.js';
import {CONSTITUENT_TYPES,PERSON_TYPES,normalizeAdditionalTypes,getConstituentTypes,hasConstituentType,isPersonConstituent} from '../shared/constituentTypes.js';

async function fixture(t){
 const dir=await mkdtemp(join(tmpdir(),'wimblo-multitype-'));let app,server,base,time=Date.parse('2026-09-13T12:00:00Z');
 async function open(){app=createApp({dbPath:join(dir,'workspace.sqlite'),seed:true,mfaKey:'',reminderWorker:false,workflowWorker:false,workflowClock:()=>time});server=app.listen(0,'127.0.0.1');await once(server,'listening');base=`http://127.0.0.1:${server.address().port}/api`;}
 async function close(){if(server)await new Promise(resolve=>server.close(resolve));server=null;app?.locals.close();app=null;}
 await open();t.after(async()=>{await close();await rm(dir,{recursive:true,force:true});});
 async function request(path,{method='GET',body,session,csrf=true}={}){const response=await fetch(base+path,{method,headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...(session?{Cookie:session.cookie,...(csrf?{'X-CSRF-Token':session.csrfToken}:{})}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:response.status,json:await response.json(),headers:response.headers};}
 async function login(email='alex@foundation.example'){const response=await request('/auth/login',{method:'POST',body:{email,password:'FoundationDemo!2026'}});assert.equal(response.status,200,JSON.stringify(response.json));return {...response.json,cookie:response.headers.getSetCookie().map(value=>value.split(';')[0]).join('; ')};}
 const admin=await login(),staff=await login('staff@foundation.example'),viewer=await login('board@foundation.example');
 async function create(collection,body){const response=await request('/records/'+collection,{method:'POST',body,session:staff});assert.equal(response.status,201,JSON.stringify(response.json));return response.json.record;}
 async function person(name,patch={}){return create('constituents',{name,type:'Individual',email:name.toLowerCase().replace(/[^a-z]/g,'')+'@example.test',preference:'Email',segments:'MultitypeTest',...patch});}
 async function edit(person,patch){const response=await request('/records/constituents/'+person.id,{method:'PATCH',body:{version:person.version,...patch},session:staff});assert.equal(response.status,200,JSON.stringify(response.json));return response.json.record;}
 const fund=await create('designations',{name:'Multitype payroll fund',accountCode:'MULTITYPE-4100'});
 async function gift(person,amount=10001,patch={}){return create('gifts',{constituentId:person.id,amount,type:'Employee giving',method:'Payroll',date:'2025-09-13',allocations:[{designationId:fund.id,amount}],...patch});}
 async function receiptProfile(){const response=await request('/receipt-profile',{method:'PUT',session:admin,body:{version:0,organizationName:'Synthetic Wimblo organization',address:'123 Test Street',taxIdentifier:'TEST-ONLY-ID',signatureLabel:'Authorized signer',customFooter:'Synthetic records only',approved:true}});assert.equal(response.status,200);return response.json.profile;}
 async function annual(person){const response=await request('/receipts/prepare',{method:'POST',session:staff,body:{kind:'Annual employee',constituentId:person.id,year:2025,profileVersion:1}});assert.equal(response.status,201,JSON.stringify(response.json));return response.json.receipt;}
 async function issue(receipt){return request('/receipts/'+receipt.id+'/issue',{method:'POST',session:staff,body:{version:1,preparationDigest:receipt.preparationDigest,channel:'Print',printed:true,handSigned:true,issueDate:'2026-09-13'}});}
 async function template(kind='Annual employee'){const response=await request('/correspondence/templates',{method:'POST',session:staff,body:{name:'Multitype '+kind,kind,subject:'Hello {{recipientName}}',body:kind==='Annual employee'?'Your {{calendarYear}} payroll support is {{annualEmployeeAmount}} across {{giftCount}} records.':'A reviewed message for {{recipientName}}.'}});assert.equal(response.status,201,JSON.stringify(response.json));return response.json.template;}
 async function statement(person,tpl){const response=await request('/correspondence/prepare',{method:'POST',session:staff,body:{templateId:tpl.id,templateVersion:tpl.version,channel:'Print',constituentIds:[person.id],year:2025}});assert.equal(response.status,201,JSON.stringify(response.json));return response.json.correspondence;}
 async function finalize(correspondence){return request('/correspondence/'+correspondence.id+'/finalize',{method:'POST',session:staff,body:{version:1,preparationDigest:correspondence.preparationDigest,confirmed:true}});}
 const record=(collection,id)=>JSON.parse(app.locals.db.prepare('SELECT data FROM records WHERE collection=? AND id=?').get(collection,id).data),financial=()=>app.locals.db.prepare("SELECT * FROM records WHERE collection IN ('gifts','grants','pledges') ORDER BY collection,id").all();
 return {request,login,admin,staff,viewer,create,person,edit,gift,receiptProfile,annual,issue,template,statement,finalize,record,financial,runWorkflow:()=>app.locals.runCommunicationWorkflows(time),restart:async()=>{await close();await open();},get db(){return app.locals.db;}};
}

test('shared category contract is canonical, backward compatible and explicit about physical family',()=>{
 assert.deepEqual(CONSTITUENT_TYPES,['Individual','Business','Foundation','Alumni','Employee','Staff','Community partner']);assert.deepEqual(PERSON_TYPES,['Individual','Alumni','Employee','Staff']);assert.ok(Object.isFrozen(CONSTITUENT_TYPES));assert.deepEqual(normalizeAdditionalTypes('Individual',['Staff','Employee','Alumni']),['Alumni','Employee','Staff']);assert.deepEqual(normalizeAdditionalTypes('Business',['Community partner','Foundation']),['Foundation','Community partner']);assert.deepEqual(getConstituentTypes({type:'Employee'}),['Employee']);assert.ok(hasConstituentType({type:'Individual',additionalTypes:['Employee']},'Employee'));assert.ok(isPersonConstituent({type:'Staff',additionalTypes:['Employee']}));assert.equal(isPersonConstituent({type:'Business',additionalTypes:['Foundation']}),false);
 for(const extras of [['Employee','Employee'],['Individual'],['Business'],['Unknown'],null,'Employee'])assert.throws(()=>normalizeAdditionalTypes('Individual',extras),error=>error.status===400);
 for(const record of [{type:'Business',additionalTypes:['Employee']},{type:'Individual',additionalTypes:['Foundation']},{type:'Staff',additionalTypes:['Staff']},{type:'Unknown'},{type:'Individual',additionalTypes:null}])assert.throws(()=>getConstituentTypes(record),error=>error.status===503);
});

test('one Individual identity can also be Employee and Staff across exact payroll receipts, volunteer history and reservations',async t=>{
 const f=await fixture(t),usersBefore=f.db.prepare('SELECT id,role FROM users ORDER BY id').all(),count=f.db.prepare("SELECT COUNT(*) n FROM records WHERE collection='constituents'").get().n,p=await f.person('Multirole donor',{additionalTypes:['Staff','Employee','Alumni']});assert.equal(p.type,'Individual');assert.deepEqual(p.additionalTypes,['Alumni','Employee','Staff']);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM records WHERE collection='constituents'").get().n,count+1);
 await f.receiptProfile();const payroll=await f.gift(p),cash=await f.gift(p,500,{type:'Cash',method:'Check'});await f.gift(p,200,{type:'Fee payment'});await f.gift(p,100,{date:'2026-01-01'});const before=f.financial(),receipt=await f.annual(p);assert.equal(receipt.recipient.id,p.id);assert.equal(receipt.giftCount,1);assert.equal(receipt.monetaryCents,10001);assert.deepEqual(receipt.gifts.map(gift=>gift.id),[payroll.id]);assert.equal((await f.issue(receipt)).status,200);
 const volunteer=await f.create('volunteers',{constituentId:p.id,skills:'Setup',hours:2}),shift=await f.create('volunteerShifts',{name:'Same identity volunteer shift',date:'2026-10-13',startTime:'09:00',endTime:'10:00',capacity:2}),reservation=await f.create('shiftReservations',{shiftId:shift.id,constituentId:p.id,status:'Reserved'});assert.equal(volunteer.constituentId,p.id);assert.equal(reservation.constituentId,p.id);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM records WHERE collection='volunteerTime' AND json_extract(data,'$.constituentId')=?").get(p.id).n,1);assert.deepEqual(f.financial(),before);assert.equal(f.record('gifts',cash.id).amount,500);assert.deepEqual(f.db.prepare('SELECT id,role FROM users ORDER BY id').all(),usersBefore);
 const login=await f.request('/auth/login',{method:'POST',body:{email:p.email,password:'FoundationDemo!2026'}});assert.equal(login.status,401);
 const changeFamily=await f.request('/records/constituents/'+p.id,{method:'PATCH',session:f.staff,body:{version:p.version,type:'Business',additionalTypes:[]}});assert.equal(changeFamily.status,409);assert.equal(f.record('constituents',p.id).type,'Individual');
});

test('native category creation and edits reject duplicates, unknown and mixed families atomically and preserve omitted extras',async t=>{
 const f=await fixture(t),p=await f.person('Canonical personal identity',{additionalTypes:['Employee','Staff']}),before=f.db.prepare("SELECT data FROM records WHERE collection='constituents' AND id=?").get(p.id).data;
 for(const patch of [{additionalTypes:['Employee','Employee']},{additionalTypes:['Individual']},{additionalTypes:['Business']},{additionalTypes:['Unknown']},{additionalTypes:null},{type:'Business'}]){const response=await f.request('/records/constituents/'+p.id,{method:'PATCH',session:f.staff,body:{version:1,...patch}});assert.equal(response.status,400,JSON.stringify(response.json));assert.equal(f.db.prepare("SELECT data FROM records WHERE collection='constituents' AND id=?").get(p.id).data,before);}
 const notes=await f.edit(p,{notes:'Same primary and secondary categories retained'});assert.deepEqual(notes.additionalTypes,['Employee','Staff']);const swap=await f.edit(notes,{type:'Staff',additionalTypes:['Employee','Individual']});assert.equal(swap.type,'Staff');assert.deepEqual(swap.additionalTypes,['Individual','Employee']);
 const organization=await f.person('Canonical organization',{type:'Business',additionalTypes:['Community partner','Foundation']});assert.deepEqual(organization.additionalTypes,['Foundation','Community partner']);for(const collection of ['volunteers','shiftReservations']){const body=collection==='volunteers'?{constituentId:organization.id,skills:'Setup'}:{constituentId:organization.id,shiftId:(await f.create('volunteerShifts',{name:'Organization not eligible',date:'2026-11-13',startTime:'11:00',endTime:'12:00',capacity:1})).id,status:'Reserved'};assert.equal((await f.request('/records/'+collection,{method:'POST',session:f.staff,body})).status,400);}
});

test('Employee category removal blocks stale preparations and preserves issued receipt, gift protection and original correspondence history',async t=>{
 const f=await fixture(t),p=await f.person('Employee membership changes',{additionalTypes:['Employee','Staff']});await f.gift(p);await f.receiptProfile();const issuedPreparation=await f.annual(p),pending=await f.annual(p),wording=await f.statement(p,await f.template()),issued=await f.issue(issuedPreparation);assert.equal(issued.status,200);const before=f.financial(),originalReceipt=f.db.prepare('SELECT snapshot,digest FROM receipt_preparations WHERE id=?').get(pending.id),originalWords=f.db.prepare('SELECT snapshot,digest FROM correspondence_preparations WHERE id=?').get(wording.id),updated=await f.edit(p,{additionalTypes:['Staff']});assert.equal(updated.type,'Individual');assert.equal((await f.issue(pending)).status,409);assert.equal((await f.finalize(wording)).status,409);
 assert.deepEqual(f.db.prepare('SELECT snapshot,digest FROM receipt_preparations WHERE id=?').get(pending.id),originalReceipt);assert.deepEqual(f.db.prepare('SELECT snapshot,digest FROM correspondence_preparations WHERE id=?').get(wording.id),originalWords);assert.deepEqual(f.financial(),before);const retained=await f.request('/receipts/'+issuedPreparation.id,{session:f.viewer});assert.equal(retained.status,200);assert.equal(retained.json.receipt.status,'Issued');assert.equal(retained.json.receipt.monetaryCents,10001);assert.equal(retained.json.receipt.number,issued.json.receipt.number);
 assert.equal((await f.request('/receipts/prepare',{method:'POST',session:f.staff,body:{kind:'Annual employee',constituentId:p.id,year:2025,profileVersion:1}})).status,400);const sourceGift=JSON.parse(before.find(row=>row.collection==='gifts'&&JSON.parse(row.data).constituentId===p.id).data);assert.equal((await f.request('/gifts/'+sourceGift.id+'/void',{method:'POST',session:f.staff,body:{version:sourceGift.version,reason:'Protected receipt source'}})).status,409);
});

test('saved type filters match category membership once and pin source changes without consent or permission grants',async t=>{
 const f=await fixture(t),p=await f.person('Audience category member',{additionalTypes:['Staff','Employee']}),suppressed=await f.person('Audience suppressed member',{additionalTypes:['Employee'],preference:'Do not contact'}),response=await f.request('/audiences',{method:'POST',session:f.staff,body:{name:'Employee or Staff membership',filters:{segmentTokens:['MultitypeTest'],segmentMatch:'All',types:['Employee','Staff'],preferences:[]}}});assert.equal(response.status,201);const audience=response.json.audience,path='/audiences/'+audience.id+'/preview?version=1&channel=Email%20draft',preview=await f.request(path,{session:f.viewer});assert.equal(preview.status,200);assert.equal(preview.json.matchedCount,2);assert.equal(preview.json.eligibleCount,1);assert.deepEqual(preview.json.recipients.map(person=>person.id),[p.id]);assert.equal(preview.json.reasonCounts['Do not contact'],1);
 const tpl=await f.template('Messaging'),body={templateId:tpl.id,templateVersion:tpl.version,channel:'Email draft',constituentIds:[p.id],audience:{id:audience.id,version:1,sourceDigest:preview.json.sourceDigest}},prepared=await f.request('/correspondence/prepare',{method:'POST',session:f.staff,body});assert.equal(prepared.status,201);await f.edit(p,{additionalTypes:[]});assert.equal((await f.request('/correspondence/prepare',{method:'POST',session:f.staff,body})).status,409);assert.equal((await f.finalize(prepared.json.correspondence)).status,409);const refreshed=await f.request(path,{session:f.viewer});assert.equal(refreshed.json.eligibleCount,0);assert.notEqual(refreshed.json.sourceDigest,preview.json.sourceDigest);
 assert.equal((await f.request('/records/constituents/'+suppressed.id,{method:'PATCH',session:f.viewer,body:{version:1,additionalTypes:['Staff','Employee']}})).status,403);assert.equal((await f.request('/records/constituents/'+suppressed.id,{method:'PATCH',session:f.staff,csrf:false,body:{version:1,additionalTypes:['Staff','Employee']}})).status,403);
});

test('prospective Employee membership workflows retain drafts and lose current authority after category removal',async t=>{
 const f=await fixture(t),base=await f.person('Baseline category member',{additionalTypes:['Employee']}),a=await f.request('/audiences',{method:'POST',session:f.staff,body:{name:'Prospective Employee category',filters:{segmentTokens:['MultitypeTest'],segmentMatch:'All',types:['Employee'],preferences:[]}}});assert.equal(a.status,201);const tpl=await f.template('Messaging'),preview=await f.request('/audiences/'+a.json.audience.id+'/preview?version=1&channel=Email%20draft',{session:f.staff}),arm=await f.request('/communication-workflows',{method:'POST',session:f.staff,body:{name:'Prospective category rule',audienceId:a.json.audience.id,audienceVersion:1,sourceDigest:preview.json.sourceDigest,templateId:tpl.id,templateVersion:1,channel:'Email draft',confirmed:true}});assert.equal(arm.status,201,JSON.stringify(arm.json));assert.equal(arm.json.workflow.baselineCount,1);assert.equal(f.runWorkflow().drafted,0);
 const entrant=await f.person('New Employee category entrant',{additionalTypes:['Employee']});const before=f.financial(),result=f.runWorkflow();assert.equal(result.drafted,1);const native=f.db.prepare("SELECT id,data FROM records WHERE collection='communications' AND json_extract(data,'$.constituentId')=?").get(entrant.id),original=JSON.parse(native.data);assert.equal(original.status,'Draft');await f.edit(entrant,{additionalTypes:[]});const workspace=await f.request('/workspace',{session:f.staff}),retained=workspace.json.data.communications.find(record=>record.id===native.id);assert.equal(retained.body,original.body);assert.equal(retained.workflowOrigin.sourceCurrent,false);assert.equal(retained.workflowOrigin.delivery,'Not sent');assert.equal(f.runWorkflow().drafted,0);assert.deepEqual(f.financial(),before);assert.equal(f.record('constituents',base.id).type,'Individual');
});

test('legacy primary-only identities remain effective single categories and canonical membership persists across restart',async t=>{
 const f=await fixture(t),legacy=await f.person('Legacy employee',{type:'Employee'});f.db.prepare("UPDATE records SET data=json_remove(data,'$.additionalTypes') WHERE collection='constituents' AND id=?").run(legacy.id);assert.deepEqual(getConstituentTypes(f.record('constituents',legacy.id)),['Employee']);await f.gift(legacy);await f.receiptProfile();const receipt=await f.annual(legacy);assert.equal(receipt.monetaryCents,10001);assert.equal((await f.issue(receipt)).status,200);
 const canonical=await f.person('Persisted canonical member',{additionalTypes:['Staff','Alumni','Employee']});await f.restart();const fresh=await f.login('staff@foundation.example'),workspace=await f.request('/workspace',{session:fresh});assert.equal(workspace.status,200);assert.deepEqual(workspace.json.data.constituents.find(record=>record.id===canonical.id).additionalTypes,['Alumni','Employee','Staff']);assert.equal(workspace.json.data.constituents.find(record=>record.id===legacy.id).additionalTypes,undefined);const edit=await f.request('/records/constituents/'+legacy.id,{method:'PATCH',session:fresh,body:{version:1,notes:'Legacy form remains editable'}});assert.equal(edit.status,200);assert.deepEqual(edit.json.record.additionalTypes,[]);
});

test('corrupt persisted category memberships fail closed rather than grant payroll or general source access',async t=>{
 const f=await fixture(t),p=await f.person('Corrupt categories',{additionalTypes:['Employee']}),payroll=await f.gift(p);await f.receiptProfile();const before=f.financial();f.db.prepare("UPDATE records SET data=json_set(data,'$.additionalTypes',json('[\"Business\"]')) WHERE collection='constituents' AND id=?").run(p.id);
 const receipt=await f.request('/receipts/prepare',{method:'POST',session:f.staff,body:{kind:'Annual employee',constituentId:p.id,year:2025,profileVersion:1}});assert.equal(receipt.status,503);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM receipt_preparations').get().n,0);assert.equal((await f.request('/workspace',{session:f.staff})).status,503);assert.deepEqual(f.financial(),before);assert.equal(f.record('gifts',payroll.id).amount,10001);
});
