import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {DatabaseSync} from 'node:sqlite';
import {once} from 'node:events';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createApp} from '../server/app.js';
import {installConstituentTimelineRoutes} from '../server/constituentTimeline.js';
const today=()=>new Date().toISOString().slice(0,10);
async function fixture(t){
 const dir=await mkdtemp(join(tmpdir(),'wimblo-timeline-')),dbPath=join(dir,'workspace.sqlite');let app,server,base;
 async function open(){app=createApp({dbPath,seed:true,mfaKey:''});server=app.listen(0,'127.0.0.1');await once(server,'listening');base=`http://127.0.0.1:${server.address().port}`;}
 async function close(){await new Promise(r=>server.close(r));app.locals.close();}
 await open();t.after(async()=>{await close();await rm(dir,{recursive:true,force:true});});
 const request=async(path,{method='GET',body,session}={})=>{const response=await fetch(base+'/api'+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrfToken}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,json:await response.json(),headers:response.headers};};
 const login=async(email='alex@foundation.example')=>{const r=await request('/auth/login',{method:'POST',body:{email,password:'FoundationDemo!2026'}});assert.equal(r.status,200);return {...r.json,cookie:r.headers.get('set-cookie').split(';')[0]};};
 const admin=await login(),viewer=await login('board@foundation.example');
 const create=async(collection,body)=>{const r=await request('/records/'+collection,{method:'POST',body,session:admin});assert.equal(r.status,201,JSON.stringify(r.json));return r.json.record;};
 const donor=await create('constituents',{name:'Synthetic Timeline Donor',type:'Individual',email:'synthetic.timeline@example.test',preference:'Email'}),other=await create('constituents',{name:'Unrelated Private Marker',type:'Individual'}),designation=(await request('/workspace',{session:admin})).json.data.designations[0].id;
 const gift=async(amount=10001,changes={})=>create('gifts',{constituentId:donor.id,amount,type:'Cash',method:'Check',date:today(),allocations:[{designationId:designation,amount}],...changes});
 return {request,login,admin,viewer,create,donor,other,gift,designation,get db(){return app.locals.db;},restart:async()=>{await close();await open();}};
}

test('mounted constituent timeline links current gifts and retained correction/follow-up/manual wording sources without duplicated income or inferred delivery',async t=>{
 const f=await fixture(t),first=await f.gift(),correction=await f.request(`/records/gifts/${first.id}`,{method:'PATCH',session:f.admin,body:{version:first.version,amount:10502,allocations:[{designationId:f.designation,amount:10502}],correctionReason:'Synthetic source amount correction'}});assert.equal(correction.status,200);const g=correction.json.record;
 const majorBody={kind:'major',name:'Synthetic timeline ask',donorId:f.donor.id,ownerId:f.admin.user.id,expectedAmount:20000,stage:'Asked',nextActionDate:today(),campaignId:null},created=await f.request('/fundraising',{method:'POST',session:f.admin,body:majorBody});assert.equal(created.status,201);const committed=await f.request(`/fundraising/${created.json.record.id}`,{method:'PATCH',session:f.admin,body:{...majorBody,version:1,stage:'Committed',transitionReason:'Synthetic donor commitment; not received income'}});assert.equal(committed.status,200);const major=committed.json.record,followed=await f.request(`/fundraising/${major.id}/follow-up`,{method:'POST',session:f.admin,body:{version:major.version,date:today(),outcome:'Completed',note:'Synthetic actual donor conversation',reason:'Staff recorded actual response'}});assert.equal(followed.status,200);
 const template=await f.request('/correspondence/templates',{method:'POST',session:f.admin,body:{name:'Synthetic timeline acknowledgment',kind:'Acknowledgment',subject:'Thanks {{recipientName}}',body:'PRIVATE-WORDING-NOT-INDEXED {{recipientName}} {{monetaryAmount}}'}});assert.equal(template.status,201);const prepared=await f.request('/correspondence/prepare',{method:'POST',session:f.admin,body:{templateId:template.json.template.id,templateVersion:1,channel:'Print',giftIds:[g.id]}});assert.equal(prepared.status,201);const c=prepared.json.correspondence;assert.equal((await f.request(`/correspondence/${c.id}/finalize`,{method:'POST',session:f.admin,body:{version:1,preparationDigest:c.preparationDigest,confirmed:true}})).status,200);const done=await f.request(`/gifts/${g.id}/acknowledge`,{method:'POST',session:f.admin,body:{version:g.version,date:today(),channel:'Post',notes:'Synthetic actual manual fulfillment',correspondence:{preparationId:c.id,preparationDigest:c.preparationDigest,confirmed:true,reason:'Synthetic staff confirmed the exact reviewed wording'}}});assert.equal(done.status,200);
 const task=await f.create('tasks',{title:'Synthetic donor follow-up task',constituentId:f.donor.id,ownerId:f.admin.user.id,dueDate:today(),status:'Open'}),event=await f.create('events',{name:'Synthetic timeline event',date:today(),capacity:3});assert.equal((await f.request(`/events/${event.id}/register`,{method:'POST',session:f.admin,body:{constituentId:f.donor.id,seating:''}})).status,200);
 const unrelated=await f.gift(500,{constituentId:f.other.id}),beforeGift=JSON.stringify(done.json.record),timeline=await f.request(`/constituents/${f.donor.id}/timeline?limit=50`,{session:f.viewer});assert.equal(timeline.status,200,JSON.stringify(timeline.json));const entries=timeline.json.entries;assert.equal(entries.filter(e=>e.kind==='Gift source').length,1);assert.equal(entries.find(e=>e.kind==='Gift source').amountCents,10502);assert.equal(entries.find(e=>e.kind==='Gift source').source.version,3);assert.equal(Object.hasOwn(entries.find(e=>e.kind==='Gift source').source,'endpoint'),false);assert.equal(entries.find(e=>e.kind==='Financial correction').changes.beforeAmountCents,10001);assert.equal(entries.find(e=>e.kind==='Financial correction').changes.afterAmountCents,10502);assert.equal(entries.find(e=>e.kind==='Financial correction').source.currentVersion,3);assert.equal(entries.filter(e=>e.kind==='Gift acknowledgment').length,1);assert.equal(entries.filter(e=>e.kind==='Interaction').length,0);assert.equal(entries.filter(e=>e.kind==='Reviewed wording fulfilled manually').length,1);assert.equal(entries.find(e=>e.kind==='Reviewed wording fulfilled manually').relatedSources.find(s=>s.collection==='gifts').version,2);assert.equal(entries.find(e=>e.kind==='Reviewed wording fulfilled manually').relatedSources.find(s=>s.collection==='gifts').currentVersion,3);assert.ok(entries.some(e=>e.kind==='Actual follow-up disposition'));assert.ok(entries.some(e=>e.source.id===task.id&&e.kind==='Responsibility change'));assert.ok(entries.some(e=>e.kind==='Event registration'));assert.ok(entries.some(e=>e.kind==='Reviewed correspondence'&&e.source.id===c.id));assert.equal(entries.some(e=>e.source.id===unrelated.id),false);assert.doesNotMatch(JSON.stringify(timeline.json),/PRIVATE-WORDING-NOT-INDEXED|Unrelated Private Marker|password|csrf|cookie/);assert.match(timeline.json.scope,/Tribute history, private documents/);assert.equal(JSON.stringify(JSON.parse(f.db.prepare("SELECT data FROM records WHERE collection='gifts' AND id=?").get(g.id).data)),beforeGift);
});

test('timeline pagination remains deterministic across restart but rejects changed source, changed account and malformed cursor',async t=>{
 const f=await fixture(t);await f.gift();await f.gift(500);const first=await f.request(`/constituents/${f.donor.id}/timeline?limit=1`,{session:f.admin});assert.equal(first.status,200);assert.equal(first.json.entries.length,1);assert.ok(first.json.nextCursor);const next=await f.request(`/constituents/${f.donor.id}/timeline?limit=1&cursor=${first.json.nextCursor}`,{session:f.admin});assert.equal(next.status,200);assert.notEqual(next.json.entries[0].id,first.json.entries[0].id);
 await f.restart();const admin=await f.login(),reopened=await f.request(`/constituents/${f.donor.id}/timeline?limit=1&cursor=${first.json.nextCursor}`,{session:admin});assert.equal(reopened.status,200);assert.deepEqual(reopened.json.entries,next.json.entries);
 assert.equal((await f.request(`/constituents/${f.donor.id}/timeline?cursor=${first.json.nextCursor}`,{session:f.viewer})).status,409);
 await f.create('communications',{constituentId:f.donor.id,subject:'Actual later conversation',date:today(),channel:'Phone',status:'Logged',body:'Synthetic recorded conversation'});assert.equal((await f.request(`/constituents/${f.donor.id}/timeline?cursor=${first.json.nextCursor}`,{session:admin})).status,409);
 for(const q of ['limit=0','limit=51','cursor=invalid','q=not-allowed'])assert.equal((await f.request(`/constituents/${f.donor.id}/timeline?${q}`,{session:admin})).status,400);
 assert.equal((await f.request(`/constituents/${f.donor.id}/timeline`)).status,401);assert.equal((await f.request('/constituents/missing/timeline',{session:admin})).status,404);
});

test('future, void and soft-credit sources remain explicitly separate and task responsibility reflects current inactive accounts',async t=>{
 const f=await fixture(t),future=await f.gift(100,{date:'2999-01-01'}),voided=await f.gift(200),soft=await f.gift(300,{constituentId:f.other.id,softCreditId:f.donor.id});assert.equal((await f.request(`/gifts/${voided.id}/void`,{method:'POST',session:f.admin,body:{version:1,reason:'Synthetic reversal'}})).status,200);const task=await f.create('tasks',{title:'Assigned current responsibility',constituentId:f.donor.id,ownerId:f.admin.user.id,dueDate:today(),status:'Open'});f.db.prepare('UPDATE users SET active=0 WHERE id=?').run(f.admin.user.id);const timeline=await f.request(`/constituents/${f.donor.id}/timeline`,{session:f.viewer});assert.equal(timeline.status,200);assert.match(timeline.json.entries.find(e=>e.source.id===future.id).status,/Future-dated.*excluded/);assert.match(timeline.json.entries.find(e=>e.source.id===voided.id).status,/Voided.*excluded/);const recognition=timeline.json.entries.find(e=>e.source.id===soft.id);assert.equal(recognition.category,'Recognition');assert.equal(recognition.amountMeaning,'Recognition source value');assert.match(recognition.summary,/not additional received income/);assert.match(timeline.json.entries.find(e=>e.source.id===task.id&&e.kind==='Task').summary,/Needs reassignment/);
});

async function visibilityFixture(t){
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE users(id TEXT,name TEXT,active INTEGER,role TEXT);CREATE TABLE gift_financial_corrections(id TEXT,gift_id TEXT,from_version INTEGER,to_version INTEGER,before_json TEXT,after_json TEXT,changed_fields TEXT,reason TEXT,actor_json TEXT,at TEXT);');
 const donor={id:'donor',name:'Visible donor',version:1},privateDonor={id:'private',name:'PRIVATE-DONOR-NAME',version:1},g={id:'gift',version:2,constituentId:donor.id,amount:200,status:'Posted',date:today(),type:'Cash',createdAt:today()},data={constituents:[donor,privateDonor],gifts:[g],communications:[],tasks:[],events:[],grants:[]};
 db.prepare('INSERT INTO gift_financial_corrections VALUES(?,?,?,?,?,?,?,?,?,?)').run('correction',g.id,1,2,JSON.stringify({...g,version:1,amount:100}),JSON.stringify(g),'["amount"]','PRIVATE-CORRECTION-REASON','{"id":"staff","name":"Saved staff"}',today());let hideGift=false,hideDonor=false;
 const app=express();app.use((req,res,next)=>{req.user={id:'test',role:req.get('X-Role')||'viewer'};next();});installConstituentTimelineRoutes(app,{db,list:(collection,req)=>(data[collection]||[]).filter(r=>collection!=='gifts'||!hideGift).filter(r=>collection!=='constituents'||!hideDonor||r.id!==privateDonor.id),get:(collection,id,req)=>{const r=data[collection]?.find(r=>r.id===id);if(!r)throw Object.assign(new Error('Not found'),{status:404});return r;}});app.use((e,req,res,next)=>res.status(e.status||400).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{await new Promise(r=>server.close(r));db.close();});const request=async(role='viewer')=>{const r=await fetch(`http://127.0.0.1:${server.address().port}/api/constituents/donor/timeline`,{headers:{'X-Role':role}});return {status:r.status,json:await r.json()};};return {db,data,request,setHiddenGift:v=>{hideGift=v;},setHiddenDonor:v=>{hideDonor=v;}};
}

test('timeline fails closed when historical correction source or historical donor loses visibility; unsupported roles are denied',async t=>{
 const f=await visibilityFixture(t),visible=await f.request();assert.ok(visible.json.entries.some(e=>e.kind==='Financial correction'));f.setHiddenGift(true);const hidden=await f.request();assert.equal(hidden.status,200);assert.equal(hidden.json.entries.length,0);assert.doesNotMatch(JSON.stringify(hidden.json),/PRIVATE-CORRECTION-REASON/);f.setHiddenGift(false);f.db.prepare('UPDATE gift_financial_corrections SET before_json=?').run(JSON.stringify({...f.data.gifts[0],version:1,constituentId:'private',amount:100}));f.setHiddenDonor(true);const deniedHistory=await f.request();assert.equal(deniedHistory.json.entries.some(e=>e.kind==='Financial correction'),false);assert.doesNotMatch(JSON.stringify(deniedHistory.json),/PRIVATE-DONOR-NAME|PRIVATE-CORRECTION-REASON/);assert.equal((await f.request('platform_admin')).status,403);f.data.gifts=[];const deleted=await f.request();assert.equal(deleted.json.entries.length,0);
});

test('admin-only retained grant history stays out of the timeline, including names, dates and source IDs, while admins retain authorized context',async t=>{
 const f=await fixture(t),funder=await f.create('constituents',{name:'Synthetic grant funder',type:'Foundation'}),grant=await f.create('grants',{name:'Synthetic grant',funderId:funder.id,amount:10000,stage:'Awarded',deadline:today(),reportDue:today()}),milestone=await f.request('/grant-operations',{method:'POST',session:f.admin,body:{grantId:grant.id,grantVersion:grant.version,name:'PRIVATE-GRANT-MILESTONE-NAME',kind:'Report',dueDate:today(),ownerId:f.admin.user.id,ownerVersion:f.db.prepare('SELECT version FROM users WHERE id=?').get(f.admin.user.id).version}});assert.equal(milestone.status,201,JSON.stringify(milestone.json));const m=milestone.json.milestone;
 // A retained admin-only revision is a fixture of existing historical access;
 // the timeline must consume the established grant service projection.
 const history=f.db.prepare('SELECT snapshot FROM grant_milestone_history WHERE milestone_id=? AND version=1').get(m.id);const snapshot=JSON.parse(history.snapshot);snapshot.requiredRole='admin';f.db.exec('DROP TRIGGER grant_history_no_update');f.db.prepare('UPDATE grant_milestone_history SET snapshot=? WHERE milestone_id=?').run(JSON.stringify(snapshot),m.id);
 const viewer=await f.request(`/constituents/${funder.id}/timeline`,{session:f.viewer});assert.equal(viewer.status,200);assert.equal(viewer.json.entries.length,0);assert.doesNotMatch(JSON.stringify(viewer.json),new RegExp('PRIVATE-GRANT-MILESTONE-NAME|'+m.id));const admin=await f.request(`/constituents/${funder.id}/timeline`,{session:f.admin});assert.equal(admin.status,200);assert.equal(admin.json.entries[0].source.id,grant.id);assert.equal(admin.json.entries[0].relatedSources[0].view,'grant-operations');assert.equal(admin.json.entries[0].relatedSources[0].version,null);assert.equal(admin.json.entries[0].relatedSources[0].endpoint,'/api/grant-operations/'+m.id);
});
