import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID, randomBytes } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { Worker } from 'node:worker_threads';
import Stripe from 'stripe';
import { createApp } from '../server/app.js';
import { backupWorkspace, restoreWorkspace } from '../server/backup.js';

const password='SyntheticHostedGivingAcceptance!2026', webhookSecret='whsec_SYNTHETICintegrityNoProviderCalls';
const sdk=new Stripe('sk_test_FAKE_QA');
async function fixture(t) {
 const dir=await mkdtemp(join(tmpdir(),'wimblo-hosted-integrity-')),dbPath=join(dir,'workspace.sqlite'),tenantId=randomUUID(),initialAdmin={name:'Synthetic giving administrator',email:'giving.admin@example.test',password},sessions={},remote=new Map(),calls=[];let app,server,base,active=true,createHook=null,retrieveHook=null;
 const adapter={async createSession(params,options){calls.push({params:structuredClone(params),options:structuredClone(options)});if(createHook)return createHook(params,options);const id='cs_test_'+randomUUID().replaceAll('-',''),amount=params.line_items[0].price_data.unit_amount,s={id,object:'checkout.session',url:'https://checkout.stripe.com/c/pay/'+id,mode:'payment',livemode:false,status:'open',payment_status:'unpaid',amount_total:amount,amount_subtotal:amount,currency:'usd',metadata:structuredClone(params.metadata),client_reference_id:params.client_reference_id,payment_intent:null};remote.set(id,s);return structuredClone(s);},async retrieveSession(id){if(retrieveHook)return retrieveHook(id);assert.ok(remote.has(id),'Only simulated sessions may be retrieved');return structuredClone(remote.get(id));}};
 const hostedGiving={mode:'TEST_ONLY',secretKey:'sk_test_FAKE_QA',webhookSecret,origin:'https://synthetic.example.test',adapter};
 async function close(){if(server)await new Promise(resolve=>server.close(resolve));server=null;app?.locals.close();app=null;}
 async function request(path,{method='GET',body,session=sessions.admin,csrf=true,raw,signature}={}){const r=await fetch(base+'/api'+path,{method,headers:{...(body===undefined&&raw===undefined?{}:{'Content-Type':'application/json'}),...(session?{Cookie:session.cookie,...(csrf?{'X-CSRF-Token':session.csrfToken}:{})}:{}),...(signature?{'Stripe-Signature':signature}:{})},...(raw!==undefined?{body:raw}:body===undefined?{}:{body:JSON.stringify(body)})});const text=await r.text();let json;try{json=JSON.parse(text);}catch{json=null;}return{status:r.status,json,text,headers:r.headers};}
 async function login(email=initialAdmin.email){const r=await request('/auth/login',{method:'POST',session:null,body:{email,password}});assert.equal(r.status,200,r.text);return{...r.json,cookie:r.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ')};}
 async function open(path=dbPath){app=createApp({dbPath:path,seed:false,tenantId,initialAdmin,isTenantActive:()=>active,workflowWorker:false,reminderWorker:false,hostedGiving,hostedGivingClock:Date.now});server=app.listen(0,'127.0.0.1');await once(server,'listening');base='http://127.0.0.1:'+server.address().port;sessions.admin=await login();}
 await open();t.after(async()=>{await close();await rm(dir,{recursive:true,force:true});});
 for(const role of ['staff','viewer','event-helper']){const r=await request('/users',{method:'POST',body:{name:'Synthetic giving '+role,email:role+'.giving@example.test',role,password}});assert.equal(r.status,201,r.text);sessions[role]=await login(role+'.giving@example.test');}
 async function create(collection,body){const r=await request('/records/'+collection,{method:'POST',body});assert.equal(r.status,201,r.text);return r.json.record;}
 const donor=await create('constituents',{name:'Actual simulated donor',type:'Individual',email:'actual.giving@example.test',preference:'Do not contact'}),campaign=await create('campaigns',{name:'Synthetic annual giving',type:'Annual',goal:999999,startDate:'2026-01-01',endDate:'2027-12-31',status:'Active'}),fund=await create('designations',{name:'Actual simulated fund',accountCode:'GIVING-100'});
 const row=(collection,id)=>JSON.parse(app.locals.db.prepare('SELECT data FROM records WHERE collection=? AND id=?').get(collection,id).data);
 const tables=()=>app.locals.db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name LIKE 'hosted_%' ORDER BY name").all().map(x=>x.name);
 const snapshot=(audit=true)=>Object.fromEntries(['records',...tables(),...(audit?['audit']:[])].map(name=>[name,app.locals.db.prepare('SELECT * FROM '+name+' ORDER BY rowid').all()]));
 const financial=()=>Object.fromEntries(['records','receipt_preparations','receipt_issues','receipt_voids','correspondence_preparations','correspondence_finalizations','correspondence_fulfillments'].map(name=>[name,name==='records'?app.locals.db.prepare("SELECT * FROM records WHERE collection IN ('gifts','campaigns','pledges','grants','communications') ORDER BY rowid").all():app.locals.db.prepare('SELECT * FROM '+name+' ORDER BY rowid').all()]));
 const payload=(changes={})=>({requestId:randomUUID(),donorId:donor.id,donorVersion:row('constituents',donor.id).version,campaignId:campaign.id,campaignVersion:row('campaigns',campaign.id).version,designationId:fund.id,designationVersion:row('designations',fund.id).version,amountCents:10001,currency:'usd',reason:'Synthetic reviewed existing donor and fund',testModeConfirmed:true,...changes});
 async function intent(changes={}){const r=await request('/hosted-giving/intents',{method:'POST',body:payload(changes)});assert.equal(r.status,201,r.text);return r.json.intent;}
 async function detail(id,session){return request('/hosted-giving/intents/'+id,{session});}
 function event(session,type='checkout.session.completed',changes={}){return{id:'evt_'+randomUUID().replaceAll('-',''),object:'event',api_version:'2026-04-22.dahlia',created:Math.floor(Date.now()/1000),livemode:false,type,data:{object:structuredClone(session)},...changes};}
 async function webhook(e,{secret=webhookSecret,timestamp=Math.floor(Date.now()/1000),raw=JSON.stringify(e,null,2)}={}){return request('/hosted-giving/webhook',{method:'POST',session:null,raw,signature:sdk.webhooks.generateTestHeaderString({payload:raw,secret,timestamp})});}
 function paid(session,{method='card',changes={}}={}){const pi='pi_'+randomUUID().replaceAll('-',''),charge='ch_'+randomUUID().replaceAll('-','');const value={...structuredClone(session),status:'complete',payment_status:'paid',payment_intent:{id:pi,object:'payment_intent',livemode:false,status:'succeeded',amount:session.amount_total,amount_received:session.amount_total,currency:'usd',metadata:structuredClone(session.metadata),latest_charge:{id:charge,object:'charge',livemode:false,amount:session.amount_total,amount_refunded:0,currency:'usd',paid:true,captured:true,status:'succeeded',refunded:false,disputed:false,payment_intent:pi,payment_method_details:{type:method}}},...changes};remote.set(session.id,value);return value;}
 async function verify(i,changes={}){return request('/hosted-giving/intents/'+i.id+'/verify',{method:'POST',body:{version:i.version,reason:'Retrieved simulated provider evidence, not bank settlement',...changes}});}
 async function post(i,changes={},options={}){return request('/hosted-giving/intents/'+i.id+'/record-gift',{method:'POST',body:{version:i.version,donorVersion:row('constituents',donor.id).version,campaignVersion:row('campaigns',campaign.id).version,designationVersion:row('designations',fund.id).version,reason:'Explicit administrator review of test-only verified payment',testModeConfirmed:true,...changes},...options});}
 return{dir,dbPath,tenantId,initialAdmin,sessions,remote,calls,adapter,hostedGiving,request,login,open,close,donor,campaign,fund,create,row,tables,snapshot,financial,payload,intent,detail,event,webhook,paid,verify,post,get db(){return app.locals.db;},get app(){return app;},set active(v){active=v;},set createHook(v){createHook=v;},set retrieveHook(v){retrieveHook=v;},restart:async()=>{await close();await open();}};
}

async function pendingPaid(f,{method='card'}={}){const i=await f.intent(),s=[...f.remote.values()].at(-1),paid=f.paid(s,{method}),event=f.event(paid);const accepted=await f.webhook(event);assert.ok([200,202].includes(accepted.status),accepted.text);const current=await f.detail(i.id);assert.equal(current.status,200,current.text);assert.equal(current.json.intent.status,'PaymentPending');return{intent:current.json.intent,session:paid,event};}
async function verified(f,options){const p=await pendingPaid(f,options),r=await f.verify(p.intent);assert.equal(r.status,200,r.text);assert.equal(r.json.intent.status,'PaymentVerified');return{...p,intent:r.json.intent};}

test('signed unpaid asynchronous checkout creates no income; actual retrieved ACH verification requires explicit admin posting once',async t=>{
 const f=await fixture(t),finance=f.financial(),i=await f.intent(),s=[...f.remote.values()].at(-1);assert.equal(i.status,'CheckoutReady');
 assert.equal(f.calls[0].params.metadata.tenantId,f.tenantId);assert.equal(f.calls[0].params.metadata.intentId,i.id);assert.deepEqual(f.calls[0].params.payment_intent_data.metadata,f.calls[0].params.metadata);assert.ok(f.calls[0].options.idempotencyKey);
 s.status='complete';const unpaid=await f.webhook(f.event(s));assert.ok([200,202].includes(unpaid.status),unpaid.text);assert.deepEqual(f.financial(),finance);const waiting=(await f.detail(i.id)).json.intent;assert.notEqual(waiting.status,'PaymentVerified');assert.ok([409,400].includes((await f.post(waiting)).status));
 const success=f.paid(s,{method:'us_bank_account'}),e=f.event(success,'checkout.session.async_payment_succeeded');assert.ok([200,202].includes((await f.webhook(e)).status));const before=(await f.detail(i.id)).json.intent;assert.equal(before.status,'PaymentPending');assert.deepEqual(f.financial(),finance);
 const v=await f.verify(before);assert.equal(v.status,200,v.text);assert.equal(v.json.intent.status,'PaymentVerified');assert.deepEqual(f.financial(),finance);const posted=await f.post(v.json.intent);assert.equal(posted.status,201,posted.text);const gifts=f.db.prepare("SELECT data FROM records WHERE collection='gifts'").all().map(r=>JSON.parse(r.data));assert.equal(gifts.length,1);const gift=gifts[0];assert.equal(gift.constituentId,f.donor.id);assert.equal(gift.campaignId,f.campaign.id);assert.deepEqual(gift.allocations,[{designationId:f.fund.id,amount:10001}]);assert.equal(gift.amount,10001);assert.equal(gift.status,'Posted');assert.equal(gift.type,'Cash');assert.equal(gift.giftKind,'One-time');assert.equal(gift.softCreditId,null);assert.ok(!gift.acknowledgment);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM receipt_issues').get().n,0);
 const full=f.snapshot();const duplicate=await f.webhook(e);assert.ok([200,202].includes(duplicate.status),duplicate.text);const again=await f.post((await f.detail(i.id)).json.intent);assert.ok([200,409].includes(again.status),again.text);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM records WHERE collection='gifts'").get().n,1);assert.deepEqual(f.financial().records.filter(r=>r.collection!=='gifts'),finance.records);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM hosted_giving_gift_links').get().n,1);assert.deepEqual(f.snapshot().records,full.records);
});

test('official raw-body signature fails wrong secret/stale timestamp/body alteration and enforces raw body size',async t=>{
 const f=await fixture(t),i=await f.intent(),s=[...f.remote.values()].at(-1),e=f.event(f.paid(s)),before=f.snapshot();
 for(const options of [{secret:'whsec_wrong_synthetic'},{timestamp:Math.floor(Date.now()/1000)-3600}]){const r=await f.webhook(e,options);assert.equal(r.status,400,r.text);assert.deepEqual(f.snapshot(),before);}
 const raw=JSON.stringify(e,null,2),sig=sdk.webhooks.generateTestHeaderString({payload:raw,secret:webhookSecret,timestamp:Math.floor(Date.now()/1000)});const altered=await f.request('/hosted-giving/webhook',{method:'POST',session:null,raw:raw+' ',signature:sig});assert.equal(altered.status,400,altered.text);assert.deepEqual(f.snapshot(),before);
 const oversized=await f.webhook(e,{raw:JSON.stringify({...e,syntheticPadding:'x'.repeat(270000)})});assert.equal(oversized.status,413,oversized.text);assert.deepEqual(f.snapshot(),before);
 const accepted=await f.webhook(e,{raw});assert.ok([200,202].includes(accepted.status),accepted.text);assert.equal((await f.detail(i.id)).json.intent.status,'PaymentPending');assert.equal(f.db.prepare("SELECT COUNT(*) n FROM records WHERE collection='gifts'").get().n,0);
});

test('signed live/Connect/foreign/mixed amount-currency-source fixtures never gain payment authority; altered duplicate event IDs conflict',async t=>{
 const f=await fixture(t),i=await f.intent(),s=[...f.remote.values()].at(-1),base=f.paid(s),finance=f.financial();
 const mutations=[e=>{e.livemode=true;},e=>{e.account='acct_foreign';},e=>{e.data.object.livemode=true;},e=>{e.data.object.amount_total++;},e=>{e.data.object.currency='eur';},e=>{e.data.object.metadata.tenantId=randomUUID();},e=>{e.data.object.metadata.intentId=randomUUID();},e=>{e.data.object.client_reference_id=randomUUID();},e=>{e.data.object.metadata.intentRevision='2';},e=>{e.data.object.id='cs_live_unrelated';}];
 for(const mutate of mutations){const e=f.event(base);mutate(e);await f.webhook(e);const current=(await f.detail(i.id)).json.intent;assert.notEqual(current.status,'PaymentVerified');assert.notEqual(current.status,'GiftRecorded');assert.deepEqual(f.financial(),finance);}
 const accepted=f.event(base);const r=await f.webhook(accepted);assert.ok([200,202].includes(r.status),r.text);const retained=f.snapshot();const altered=structuredClone(accepted);altered.data.object.amount_total++;const a=await f.webhook(altered);assert.ok([400,409].includes(a.status),a.text);assert.deepEqual(f.snapshot(),retained);
});

test('hosted financial intents default-deny staff/viewer/helpers, CSRF and foreign source IDs',async t=>{
 const f=await fixture(t),i=await f.intent(),before=f.snapshot();
 for(const role of ['staff','viewer','event-helper']){for(const path of ['/hosted-giving/status','/hosted-giving/intents','/hosted-giving/intents/'+i.id])assert.equal((await f.request(path,{session:f.sessions[role]})).status,403);for(const [path,body] of [['/hosted-giving/intents',f.payload()],['/hosted-giving/intents/'+i.id+'/verify',{version:i.version,reason:'Unauthorized'}],['/hosted-giving/intents/'+i.id+'/record-gift',{...f.payload(),version:i.version}]])assert.equal((await f.request(path,{method:'POST',body,session:f.sessions[role]})).status,403);}
 assert.equal((await f.request('/hosted-giving/intents',{method:'POST',body:f.payload(),csrf:false})).status,403);assert.deepEqual(f.snapshot(),before);const other=await fixture(t);assert.ok([404,400].includes((await f.request('/hosted-giving/intents',{method:'POST',body:f.payload({donorId:other.donor.id})})).status));assert.equal((await f.detail(randomUUID())).status,404);assert.deepEqual(f.snapshot(),before);
});

test('retrieved payment evidence rejects amount/method/refund/dispute/Connect/source mismatch rather than trusting callback paid',async t=>{
 const f=await fixture(t),finance=f.financial();const changes=[s=>{s.payment_intent.amount_received--;},s=>{s.payment_intent.currency='eur';},s=>{s.payment_intent.metadata.intentId=randomUUID();},s=>{s.payment_intent.latest_charge.payment_method_details.type='crypto';},s=>{s.payment_intent.latest_charge.amount_refunded=1;},s=>{s.payment_intent.latest_charge.disputed=true;},s=>{s.payment_intent.latest_charge.payment_intent='pi_foreign';},s=>{s.payment_intent.transfer_data={destination:'acct_foreign'};},s=>{s.status='open';},s=>{s.amount_subtotal--; }];
 for(const mutate of changes){const p=await pendingPaid(f),bad=structuredClone(p.session);mutate(bad);f.remote.set(bad.id,bad);const r=await f.verify(p.intent);assert.equal(r.status,200,r.text);assert.equal(r.json.intent.status,'ReviewRequired');assert.equal((await f.detail(p.intent.id)).json.intent.status,'ReviewRequired');assert.deepEqual(f.financial(),finance);}
});

test('current source/tenant/account changes during provider retrieval cannot commit verified authority',async t=>{
 const f=await fixture(t);
 for(const [collection,id,field] of [['constituents',f.donor.id,'name'],['campaigns',f.campaign.id,'name'],['designations',f.fund.id,'name']]){const p=await pendingPaid(f),before=f.financial();f.retrieveHook=async()=>{f.db.prepare("UPDATE records SET data=json_set(data,'$.version',json_extract(data,'$.version')+1,'$."+field+"','Changed during retrieval') WHERE collection=? AND id=?").run(collection,id);return structuredClone(p.session);};const r=await f.verify(p.intent);assert.ok([400,409].includes(r.status),r.text);assert.notEqual((await f.detail(p.intent.id)).json.intent.status,'PaymentVerified');assert.equal(f.db.prepare("SELECT COUNT(*) n FROM records WHERE collection='gifts'").get().n,0);assert.equal(f.financial().receipt_issues.length,before.receipt_issues.length);f.retrieveHook=null;}
 const p=await pendingPaid(f);f.retrieveHook=async()=>{f.active=false;return structuredClone(p.session);};const blocked=await f.verify(p.intent);assert.equal(blocked.status,503,blocked.text);f.active=true;f.retrieveHook=null;assert.notEqual((await f.detail(p.intent.id)).json.intent.status,'PaymentVerified');
 const account=await pendingPaid(f);f.retrieveHook=async()=>{f.db.prepare('UPDATE users SET version=version+1 WHERE id=?').run(f.sessions.admin.user.id);return structuredClone(account.session);};const changed=await f.verify(account.intent);assert.ok([401,403,409].includes(changed.status),changed.text);f.retrieveHook=null;f.sessions.admin=await f.login();assert.notEqual((await f.detail(account.intent.id)).json.intent.status,'PaymentVerified');
});

test('explicit posting requires current donor/campaign/designation revisions and tested tenant authority',async t=>{
 const f=await fixture(t),p=await verified(f),before=f.snapshot();
 for(const change of [{donorVersion:99},{campaignVersion:99},{designationVersion:99},{testModeConfirmed:false}]){const r=await f.post(p.intent,change);assert.ok([400,409].includes(r.status),r.text);assert.deepEqual(f.snapshot(),before);}
 f.active=false;assert.equal((await f.post(p.intent)).status,503);f.active=true;assert.deepEqual(f.snapshot(),before);assert.equal((await f.post(p.intent,{}, {csrf:false})).status,403);assert.deepEqual(f.snapshot(),before);
});

test('native whole-row poison, source mutation, audit failure and deferred COMMIT roll back gift/provider/history together',async t=>{
 const f=await fixture(t),p=await verified(f),before=f.snapshot();const faults=[
 "CREATE TRIGGER synthetic_hosted_fault AFTER INSERT ON records WHEN NEW.collection='gifts' BEGIN UPDATE records SET data=json_set(data,'$.amount',10002,'$.allocations[0].amount',10002) WHERE id=NEW.id; END",
 "CREATE TRIGGER synthetic_hosted_fault AFTER INSERT ON records WHEN NEW.collection='gifts' BEGIN UPDATE records SET data=json_set(data,'$.unexpectedProviderFlag','Paid') WHERE id=NEW.id; END",
 "CREATE TRIGGER synthetic_hosted_fault AFTER INSERT ON audit WHEN NEW.action='record_hosted_giving_gift' BEGIN UPDATE records SET data=json_set(data,'$.name','Wrong fund after audit') WHERE collection='designations'; END",
 "CREATE TRIGGER synthetic_hosted_fault BEFORE INSERT ON audit WHEN NEW.action='record_hosted_giving_gift' BEGIN SELECT RAISE(ABORT,'Synthetic financial audit unavailable'); END"
 ];for(const sql of faults){f.db.exec(sql);const r=await f.post(p.intent);assert.ok([409,500,503].includes(r.status),r.text);assert.deepEqual(f.snapshot(),before);f.db.exec('DROP TRIGGER synthetic_hosted_fault');}
 f.db.exec("CREATE TABLE synthetic_hosted_commit_fault(owner_id TEXT REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED); CREATE TRIGGER synthetic_hosted_fault AFTER INSERT ON hosted_giving_gift_links BEGIN INSERT INTO synthetic_hosted_commit_fault VALUES('no-such-native-owner'); END");const r=await f.post(p.intent);assert.equal(r.status,500,r.text);assert.deepEqual(f.snapshot(),before);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM synthetic_hosted_commit_fault').get().n,0);f.db.exec('DROP TRIGGER synthetic_hosted_fault');assert.equal((await f.post(p.intent)).status,201);
});

test('restart and authenticated encrypted new-path recovery retain once-only provider lineage and retire pending authority',async t=>{
 const f=await fixture(t),recorded=await verified(f);assert.equal((await f.post(recorded.intent)).status,201);const pending=await verified(f),before=f.snapshot(),finance=f.financial();await f.restart();assert.deepEqual(f.snapshot(),before);const current=(await f.detail(recorded.intent.id)).json.intent;assert.equal(current.status,'GiftRecorded');assert.ok([200,409].includes((await f.post(current)).status));assert.deepEqual(f.financial(),finance);
 assert.deepEqual(f.tables(),['hosted_giving_events','hosted_giving_gift_links','hosted_giving_history','hosted_giving_intents','hosted_giving_requests']);assert.equal(before.hosted_giving_intents.length,2);assert.equal(before.hosted_giving_requests.length,2);assert.equal(before.hosted_giving_gift_links.length,1);const archivePath=join(f.dir,'giving.backup'),destinationPath=join(f.dir,'restored-workspace.sqlite'),encryptionKey=randomBytes(32).toString('base64'),oldSession=f.sessions.admin;await backupWorkspace({db:f.db,outputPath:archivePath,tenantId:f.tenantId,encryptionKey});const restore=await restoreWorkspace({archivePath,destinationPath,expectedTenantId:f.tenantId,encryptionKey});assert.ok(restore.cleared.sessions>0);const copy=new DatabaseSync(destinationPath);try{for(const [table,rows]of Object.entries(before))assert.deepEqual(copy.prepare('SELECT * FROM '+table+' ORDER BY rowid').all(),rows,table);assert.equal(copy.prepare('SELECT COUNT(*) n FROM sessions').get().n,0);}finally{copy.close();}
 await f.close();await f.open(destinationPath);assert.equal((await f.detail(recorded.intent.id,oldSession)).status,401);const stale=(await f.detail(pending.intent.id)).json.intent;const v=await f.verify(stale);assert.ok([400,409].includes(v.status),v.text);const post=await f.post(stale);assert.ok([400,409].includes(post.status),post.text);const retry=await f.request('/hosted-giving/intents/'+stale.id+'/retry',{method:'POST',body:{version:stale.version,reason:'Must not reuse old restored authority',testModeConfirmed:true}});assert.ok([400,409].includes(retry.status),retry.text);assert.deepEqual(f.financial(),finance);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM hosted_giving_gift_links').get().n,1);
});

test('two independent SQLite app writers record a verified provider identity as one actual native gift',async t=>{
 const f=await fixture(t),p=await verified(f),body={version:p.intent.version,donorVersion:1,campaignVersion:1,designationVersion:1,reason:'Concurrent explicit financial review',testModeConfirmed:true};
 const code=`const {parentPort,workerData}=require('node:worker_threads');(async()=>{const {createApp}=await import(workerData.appUrl);const app=createApp({dbPath:workerData.dbPath,seed:false,tenantId:workerData.tenantId,initialAdmin:workerData.initialAdmin,workflowWorker:false,reminderWorker:false,hostedGiving:{...workerData.hostedGiving,adapter:{createSession:async()=>{throw Error('Unexpected provider create');},retrieveSession:async(id)=>{if(id!==workerData.providerSession.id)throw Error('Foreign simulated provider session');return structuredClone(workerData.providerSession);}}}});app.locals.db.exec('PRAGMA busy_timeout=5000');const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port+'/api',auth=await fetch(base+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:workerData.initialAdmin.email,password:workerData.initialAdmin.password})}),session=await auth.json(),cookie=auth.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');if(auth.status!==200)throw Error('Synthetic financial reviewer login failed');parentPort.postMessage({ready:true});parentPort.once('message',async()=>{try{const r=await fetch(base+'/hosted-giving/intents/'+workerData.intentId+'/record-gift',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie,'X-CSRF-Token':session.csrfToken},body:JSON.stringify(workerData.body)}),result={status:r.status,json:await r.json()};await new Promise(resolve=>server.close(resolve));app.locals.close();parentPort.postMessage({result});}catch(error){server.close();app.locals.close();parentPort.postMessage({error:error.message});}});})().catch(error=>parentPort.postMessage({error:error.message}));`;
 async function start(){const {adapter,...configuration}=f.hostedGiving;const w=new Worker(code,{eval:true,workerData:{appUrl:new URL('../server/app.js',import.meta.url).href,dbPath:f.dbPath,tenantId:f.tenantId,initialAdmin:f.initialAdmin,hostedGiving:configuration,intentId:p.intent.id,providerSession:p.session,body}});t.after(()=>w.terminate());await new Promise((resolve,reject)=>{w.once('error',reject);w.once('message',m=>m.ready?resolve():reject(Error(m.error)));});return w;}
 const workers=[await start(),await start()],promises=workers.map(w=>new Promise((resolve,reject)=>{w.once('error',reject);w.once('message',m=>m.error?reject(Error(m.error)):resolve(m.result));}));for(const w of workers)w.postMessage('record');const results=await Promise.all(promises);assert.equal(results.filter(r=>r.status===201).length,1,JSON.stringify(results));assert.ok(results.every(r=>[201,409].includes(r.status)),JSON.stringify(results));assert.equal(f.db.prepare("SELECT COUNT(*) n FROM records WHERE collection='gifts'").get().n,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM hosted_giving_gift_links').get().n,1);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM audit WHERE action='record_hosted_giving_gift'").get().n,1);
});

test('refund or dispute learned after verification prevents explicit posting and preserves review evidence without a native gift',async t=>{
 const f=await fixture(t),finance=f.financial();for(const mutate of [s=>{s.payment_intent.latest_charge.amount_refunded=1;},s=>{s.payment_intent.latest_charge.disputed=true;}]){const p=await verified(f),changed=structuredClone(p.session);mutate(changed);f.remote.set(changed.id,changed);const r=await f.post(p.intent);assert.equal(r.status,409,r.text);assert.ok(!r.json.giftId);assert.equal((await f.detail(p.intent.id)).json.intent.status,'ReviewRequired');assert.deepEqual(f.financial(),finance);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM hosted_giving_gift_links').get().n,0);}
});

test('signed partial-refund or dispute after gift recording retains review evidence without guessing a native refund or void',async t=>{
 const f=await fixture(t);for(const type of ['charge.refunded','charge.dispute.created']){const p=await verified(f),recorded=await f.post(p.intent);assert.equal(recorded.status,201,recorded.text);const before=f.financial(),charge=p.session.payment_intent.latest_charge,object={...structuredClone(charge),amount_refunded:1};const e=f.event(object,type);const r=await f.webhook(e);assert.equal(r.status,200,r.text);assert.equal((await f.detail(p.intent.id)).json.intent.status,'ReviewRequired');assert.deepEqual(f.financial(),before);assert.equal(f.row('gifts',recorded.json.giftId).status,'Posted');const retained=f.snapshot();assert.equal((await f.webhook(e)).status,200);assert.deepEqual(f.snapshot(),retained);}
});

test('initial logical request replay preserves original provider session and terminal gift; source/body drift never creates another key',async t=>{
 const f=await fixture(t),body=f.payload(),first=await f.request('/hosted-giving/intents',{method:'POST',body});assert.equal(first.status,201,first.text);const initial=first.json.intent;assert.equal(f.calls.length,1);const reserved=f.snapshot();
 const repeat=await f.request('/hosted-giving/intents',{method:'POST',body});assert.equal(repeat.status,201,repeat.text);assert.equal(repeat.json.intent.id,initial.id);assert.equal(repeat.json.intent.checkoutSessionId,initial.checkoutSessionId);assert.equal(f.calls.length,1);assert.deepEqual(f.snapshot(),reserved);
 for(const change of [{amountCents:10002},{donorVersion:2},{designationVersion:2},{reason:'Altered source request under retained original identity'}]){const drift=await f.request('/hosted-giving/intents',{method:'POST',body:{...body,...change}});assert.equal(drift.status,409,drift.text);assert.equal(f.calls.length,1);assert.deepEqual(f.snapshot(),reserved);}
 const s=[...f.remote.values()].at(-1),paid=f.paid(s),e=f.event(paid);assert.equal((await f.webhook(e)).status,200);const v=await f.verify((await f.detail(initial.id)).json.intent);assert.equal(v.status,200,v.text);const posted=await f.post(v.json.intent);assert.equal(posted.status,201,posted.text);const terminal=f.snapshot();
 const closed=await f.request('/hosted-giving/intents',{method:'POST',body});assert.equal(closed.status,201,closed.text);assert.equal(closed.json.intent.status,'GiftRecorded');assert.equal(closed.json.intent.giftId,posted.json.giftId);assert.equal(closed.json.intent.checkoutSessionId,initial.checkoutSessionId);assert.equal(f.calls.length,1);assert.deepEqual(f.snapshot(),terminal);
 const change=await f.request('/records/constituents/'+f.donor.id,{method:'PATCH',body:{version:1,name:'Corrected actual donor name'}});assert.equal(change.status,200,change.text);const corrected=f.snapshot(),correctedFinancial=f.financial();const staleExact=await f.request('/hosted-giving/intents',{method:'POST',body});assert.equal(staleExact.status,409,staleExact.text);assert.deepEqual(f.financial(),correctedFinancial);assert.deepEqual(f.snapshot().hosted_giving_requests,corrected.hosted_giving_requests);assert.deepEqual(f.snapshot().hosted_giving_gift_links,corrected.hosted_giving_gift_links);const reviewed=(await f.detail(initial.id)).json.intent;assert.equal(reviewed.status,'ReviewRequired');assert.equal(reviewed.giftId,posted.json.giftId);assert.equal(reviewed.checkoutSessionId,initial.checkoutSessionId);const retainedReview=f.snapshot();const changedBody=await f.request('/hosted-giving/intents',{method:'POST',body:{...body,donorVersion:2}});assert.equal(changedBody.status,409,changedBody.text);assert.equal(f.calls.length,1);assert.deepEqual(f.snapshot(),retainedReview);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM records WHERE collection='gifts'").get().n,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM hosted_giving_intents').get().n,1);
});
