import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {randomUUID} from 'node:crypto';
import Stripe from 'stripe';
import {createApp} from '../server/app.js';
import {hostedGivingConfigFromEnv} from '../server/hostedGiving.js';

async function fixture(t){
 const tenantId=randomUUID(),secret='whsec_SYNTHETICunitOnly',sdk=new Stripe('sk_test_SYNTHETICunitOnly'),sessions=new Map(),keys=new Map(),calls=[];let failAfterCreate=false;
 const adapter={async createSession(params,options){calls.push(structuredClone({params,options}));let s=keys.get(options.idempotencyKey);if(!s){const id='cs_test_'+randomUUID().replaceAll('-',''),amount=params.line_items[0].price_data.unit_amount;s={id,object:'checkout.session',livemode:false,mode:'payment',status:'open',payment_status:'unpaid',amount_total:amount,amount_subtotal:amount,currency:'usd',metadata:structuredClone(params.metadata),client_reference_id:params.client_reference_id,payment_intent:null,url:'https://checkout.stripe.com/c/pay/'+id};keys.set(options.idempotencyKey,s);sessions.set(id,s);}if(failAfterCreate){failAfterCreate=false;throw new Error('Synthetic connection lost after accepted create');}return structuredClone(s);},async retrieveSession(id){assert.ok(sessions.has(id));return structuredClone(sessions.get(id));}};
 const password='SyntheticNativeGiving!2026',app=createApp({seed:false,tenantId,initialAdmin:{name:'Synthetic administrator',email:'hosted.unit@example.test',password},workflowWorker:false,reminderWorker:false,hostedGiving:{mode:'TEST_ONLY',secretKey:'sk_test_SYNTHETICunitOnly',webhookSecret:secret,origin:'https://synthetic.example.test',adapter}}),server=app.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{await new Promise(resolve=>server.close(resolve));app.locals.close();});const base='http://127.0.0.1:'+server.address().port;
 const auth=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'hosted.unit@example.test',password})});assert.equal(auth.status,200);const session={...await auth.json(),cookie:auth.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ')};
 async function request(path,{method='GET',body,raw,signature}={}){const r=await fetch(base+'/api'+path,{method,headers:{...(body!==undefined||raw!==undefined?{'Content-Type':'application/json'}:{}),...(raw!==undefined?{'Stripe-Signature':signature}:{Cookie:session.cookie,'X-CSRF-Token':session.csrfToken})},...(raw!==undefined?{body:raw}:body!==undefined?{body:JSON.stringify(body)}:{})});const text=await r.text();return {status:r.status,json:JSON.parse(text),text};}
 async function create(c,body){const r=await request('/records/'+c,{method:'POST',body});assert.equal(r.status,201,r.text);return r.json.record;}
 const donor=await create('constituents',{name:'Actual donor',type:'Individual',preference:'Do not contact'}),campaign=await create('campaigns',{name:'Existing campaign',type:'Annual',goal:999999,startDate:'2026-01-01',endDate:'2027-12-31',status:'Active'}),designation=await create('designations',{name:'Actual allocation source',accountCode:'SYN-HG'}),payload={requestId:randomUUID(),donorId:donor.id,donorVersion:1,campaignId:campaign.id,campaignVersion:1,designationId:designation.id,designationVersion:1,amountCents:10001,currency:'usd',reason:'Synthetic explicit test-mode source review',testModeConfirmed:true};
 async function reserve(){return request('/hosted-giving/intents',{method:'POST',body:payload});}
 async function detail(id){return (await request('/hosted-giving/intents/'+id)).json.intent;}
 async function paid(id,method='card',created=Math.floor(Date.now()/1000)){const s=sessions.get(id),pi='pi_'+randomUUID().replaceAll('-',''),ch='ch_'+randomUUID().replaceAll('-','');s.status='complete';s.payment_status='paid';s.payment_intent={id:pi,livemode:false,status:'succeeded',currency:'usd',amount:10001,amount_received:10001,metadata:structuredClone(s.metadata),latest_charge:{id:ch,livemode:false,status:'succeeded',paid:true,captured:true,currency:'usd',amount:10001,amount_refunded:0,disputed:false,payment_intent:pi,payment_method_details:{type:method}}};const event={id:'evt_'+randomUUID().replaceAll('-',''),created,livemode:false,type:'checkout.session.completed',data:{object:structuredClone(s)}};const raw=JSON.stringify(event,null,2),r=await request('/hosted-giving/webhook',{method:'POST',raw,signature:sdk.webhooks.generateTestHeaderString({payload:raw,secret})});assert.equal(r.status,200,r.text);return s;}
 async function verify(intent){const r=await request('/hosted-giving/intents/'+intent.id+'/verify',{method:'POST',body:{version:intent.version,reason:'Synthetic server-retrieved payment evidence'}});assert.equal(r.status,200,r.text);assert.equal(r.json.intent.status,'PaymentVerified');return r.json.intent;}
 async function record(intent){return request('/hosted-giving/intents/'+intent.id+'/record-gift',{method:'POST',body:{version:intent.version,donorVersion:1,campaignVersion:1,designationVersion:1,reason:'Explicit native test-only recording',testModeConfirmed:true}});}
 return {app,adapter,request,reserve,detail,paid,verify,record,payload,calls,sessions,donor,campaign,designation,sdk,set failAfterCreate(v){failAfterCreate=v;}};
}

test('official latest SDK and test workspace config reject production, live credentials and implicit routing',()=>{
 assert.equal(new Stripe('sk_test_SYNTHETIC').getApiField('version'),'2026-08-26.dahlia');
 assert.equal(hostedGivingConfigFromEnv({}),null);
 assert.throws(()=>hostedGivingConfigFromEnv({NODE_ENV:'production',HOSTED_GIVING_MODE:'TEST_ONLY'}),/outside production/);
 assert.throws(()=>hostedGivingConfigFromEnv({HOSTED_GIVING_MODE:'LIVE'}),/TEST_ONLY/);
 assert.throws(()=>hostedGivingConfigFromEnv({HOSTED_GIVING_MODE:'TEST_ONLY'}),/explicit test workspace/);
 assert.throws(()=>createApp({seed:false,tenantId:randomUUID(),workflowWorker:false,reminderWorker:false,hostedGiving:{mode:'TEST_ONLY',secretKey:'sk_live_SYNTHETIC',webhookSecret:'whsec_SYNTHETIC',origin:'https://synthetic.example.test'}}),/test-only Stripe credentials/);
});

test('lost Checkout response leaves durable intent and exact initial replay cannot reserve a second charge before explicit original retry',async t=>{
 const f=await fixture(t);f.failAfterCreate=true;const unknown=await f.reserve();assert.equal(unknown.status,502,unknown.text);const list=await f.request('/hosted-giving/intents');assert.equal(list.json.intents.length,1);const intent=list.json.intents[0];assert.equal(intent.status,'CheckoutUnknown');assert.equal(f.app.locals.db.prepare("SELECT count(*) n FROM records WHERE collection='gifts'").get().n,0);
 const initialReplay=await f.reserve();assert.equal(initialReplay.status,201,initialReplay.text);assert.equal(initialReplay.json.intent.id,intent.id);assert.equal(initialReplay.json.intent.requestId,f.payload.requestId);assert.equal(initialReplay.json.intent.status,'CheckoutUnknown');assert.equal(f.calls.length,1);assert.equal(f.app.locals.db.prepare('SELECT count(*) n FROM hosted_giving_intents').get().n,1);
 const drift=await f.request('/hosted-giving/intents',{method:'POST',body:{...f.payload,amountCents:20002}});assert.equal(drift.status,409,drift.text);assert.equal(f.calls.length,1);
 const retry=await f.request('/hosted-giving/intents/'+intent.id+'/retry',{method:'POST',body:{version:intent.version,reason:'Refresh inspected history and reuse original request',testModeConfirmed:true}});assert.equal(retry.status,200,retry.text);assert.equal(retry.json.intent.status,'CheckoutReady');assert.equal(f.sessions.size,1);assert.equal(f.calls.length,2);assert.deepEqual(f.calls[0],f.calls[1]);assert.equal(f.calls[0].params.ui_mode,'hosted_page');assert.equal(f.calls[0].params.success_url.startsWith('https://synthetic.example.test/'),true);assert.equal(f.calls[0].params.line_items[0].price_data.unit_amount,10001);
});

test('native gift preserves signed payment evidence date rather than verification date and never creates a tax receipt',async t=>{
 const f=await fixture(t),reserved=await f.reserve();assert.equal(reserved.status,201,reserved.text);const original=reserved.json.intent,paidAt=Math.floor(Date.now()/1000)-2*86400;await f.paid(original.checkoutSessionId,'us_bank_account',paidAt);const verified=await f.verify(await f.detail(original.id)),posted=await f.record(verified);assert.equal(posted.status,201,posted.text);const gift=JSON.parse(f.app.locals.db.prepare("SELECT data FROM records WHERE collection='gifts' AND id=?").get(posted.json.giftId).data);assert.equal(gift.date,new Date(paidAt*1000).toISOString().slice(0,10));assert.equal(gift.amount,10001);assert.equal(gift.method,'ACH');assert.equal(gift.constituentId,f.donor.id);assert.equal(gift.campaignId,f.campaign.id);assert.deepEqual(gift.allocations,[{designationId:f.designation.id,amount:10001}]);assert.equal(f.app.locals.db.prepare('SELECT count(*) n FROM receipt_issues').get().n,0);assert.equal(f.app.locals.db.prepare('SELECT count(*) n FROM hosted_giving_gift_links').get().n,1);assert.equal((await f.record(posted.json.intent)).status,409);
});

test('current partial refund after verification closes native recording without inventing a gift or full refund',async t=>{
 const f=await fixture(t),reserved=await f.reserve(),i=reserved.json.intent,s=await f.paid(i.checkoutSessionId),verified=await f.verify(await f.detail(i.id));s.payment_intent.latest_charge.amount_refunded=5000;const before=f.app.locals.db.prepare('SELECT * FROM records ORDER BY rowid').all(),denied=await f.record(verified);assert.equal(denied.status,409,denied.text);assert.deepEqual(f.app.locals.db.prepare('SELECT * FROM records ORDER BY rowid').all(),before);assert.equal(f.app.locals.db.prepare('SELECT count(*) n FROM hosted_giving_gift_links').get().n,0);const review=await f.detail(i.id);assert.equal(review.status,'ReviewRequired');assert.equal(review.lastErrorCode,'PAYMENT_RECHECK_REVIEW_REQUIRED');assert.equal((await f.record(review)).status,409);assert.throws(()=>f.app.locals.db.prepare("UPDATE hosted_giving_intents SET status='PaymentVerified' WHERE id=?").run(i.id),/cannot resume/);
});

test('concurrent initial request replay sees the one durable reservation before external completion and source drift cannot create another Checkout',async t=>{
 const f=await fixture(t),original=f.adapter.createSession;let release,entered,createCount=0;const waiting=new Promise(resolve=>{release=resolve;}),started=new Promise(resolve=>{entered=resolve;});
 f.adapter.createSession=async(...args)=>{createCount++;entered();await waiting;return original(...args);};
 const pending=f.reserve();await started;const replay=await f.reserve();assert.equal(replay.status,201,replay.text);assert.equal(replay.json.intent.status,'Reserved');assert.equal(replay.json.intent.requestId,f.payload.requestId);assert.equal(createCount,1);assert.equal(f.app.locals.db.prepare('SELECT count(*) n FROM hosted_giving_intents').get().n,1);assert.equal(f.app.locals.db.prepare('SELECT count(*) n FROM hosted_giving_requests').get().n,1);release();const completed=await pending;assert.equal(completed.status,201,completed.text);assert.equal(completed.json.intent.id,replay.json.intent.id);assert.equal(completed.json.intent.status,'CheckoutReady');assert.equal(f.calls.length,1);
 const changed=await f.request('/records/constituents/'+f.donor.id,{method:'PATCH',body:{version:1,notes:'Current approved source changed after reservation'}});assert.equal(changed.status,200,changed.text);const stale=await f.reserve();assert.equal(stale.status,409,stale.text);assert.equal(createCount,1);assert.equal(f.app.locals.db.prepare('SELECT count(*) n FROM hosted_giving_intents').get().n,1);const review=await f.detail(completed.json.intent.id);assert.equal(review.status,'ReviewRequired');assert.equal(review.lastErrorCode,'SOURCE_CHANGED');
});
