import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import * as lib from '../src/lib.js';
function harness(){let index=0,state=[],effects=[],keys=[],cleanups=[];const mock={...React,useState(initial){const i=index++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return[state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){return state[index++]??=({current:initial});},useEffect(effect,deps){const i=index++;if(!keys[i]||!deps||deps.some((d,j)=>d!==keys[i][j])){keys[i]=deps;effects.push(()=>{cleanups[i]?.();cleanups[i]=effect();});}}};const module={exports:{}},require=id=>id==='react'?mock:id.includes('lib')?lib:new Proxy({},{get:()=>()=>null});new Function('React','require','module','exports',transformSync(readFileSync(new URL('../src/features/HostedGiving.jsx',import.meta.url),'utf8'),{loader:'jsx',format:'cjs'}).code)(React,require,module,module.exports);const render=props=>{index=0;const tree=module.exports.default(props),pending=effects;effects=[];pending.forEach(e=>e());return tree;};render.unmount=()=>cleanups.forEach(c=>c?.());return render;}
function find(tree,p){if(!tree||typeof tree!=='object')return null;if(p(tree))return tree;for(const c of React.Children.toArray(tree.props?.children)){const result=find(c,p);if(result)return result;}return null;}
const text=e=>React.Children.toArray(e.props.children).filter(c=>typeof c==='string').join(''),button=(tree,label)=>find(tree,e=>e.type==='button'&&text(e)===label),field=(tree,label)=>find(find(tree,e=>e.type==='label'&&text(e)===label),e=>['input','select','textarea'].includes(e.type)),flush=async()=>{for(let i=0;i<16;i++)await Promise.resolve();};
const donor={id:'d1',version:2,name:'Synthetic donor'},campaign={id:'c1',version:4,name:'Active giving',status:'Active'},fund={id:'f1',version:3,name:'Education fund'};
const intent={id:'i1',version:2,mode:'TEST_ONLY',status:'CheckoutReady',donorId:'d1',donorName:donor.name,campaignId:'c1',campaignName:campaign.name,designationId:'f1',designationName:fund.name,sourceVersions:{donor:2,campaign:4,designation:3},sourceCurrent:true,amountCents:10001,currency:'usd',checkoutSessionId:'cs_test_123',checkoutUrl:'https://checkout.stripe.com/c/pay/cs_test_123',createdAt:'2026-09-13T12:00:00Z',updatedAt:'2026-09-13T12:00:00Z'};
const status={enabled:true,ready:true,mode:'TEST_ONLY'},details=(i=intent)=>({intent:i,history:[{id:'h1',version:i.version,action:'CheckoutReady',status:i.status,actor:'admin1',at:i.updatedAt,reason:'Reviewed synthetic test checkout'}],historyCount:1,historyLimit:100});
async function ready({list=[],saved=details(),api:custom,provider=status,...extra}={}){const calls=[],render=harness(),props={user:{id:'admin1',role:'admin'},data:{constituents:[donor,{id:'merged',version:1,name:'Merged',mergedInto:'d1'}],campaigns:[campaign,{id:'closed',version:1,name:'Closed campaign',status:'Completed'}],designations:[fund]},onDirty:()=>{},api:async(path,o)=>{calls.push([path,o]);return custom?custom(path,o):o?{intent}:path.endsWith('/status')?provider:path.includes('?')?{intents:list,nextCursor:null}:saved;},...extra};render(props);await flush();return{calls,render,props,tree:render(props)};}
const html=s=>renderToStaticMarkup(s.render(s.props));
function confirm(tree){find(tree,e=>e.type==='input'&&e.props.type==='checkbox').props.onChange({target:{checked:true}});}
async function fill(s){for(const[label,value]of [['Existing donor','d1'],['Existing campaign','c1'],['Existing designation','f1'],['Test amount · USD','100.01'],['Preparation reason','Reviewed synthetic test sources']])field(s.render(s.props),label).props.onChange({target:{value}});button(s.render(s.props),'Review test checkout').props.onClick();confirm(s.render(s.props));}
async function select(s){await button(s.render(s.props),'Synthetic donor').props.onClick();await flush();return s.render(s.props);}
const submit=tree=>find(tree,e=>e.type==='form').props.onSubmit({preventDefault(){}});
function reviewAction(s,label){button(s.render(s.props),label).props.onClick();field(s.render(s.props),'Reason for reviewed intent action').props.onChange({target:{value:'Reviewed exact test intent and current facts'}});confirm(s.render(s.props));}

test('reviewed exact USD preparation pins existing source versions and one submission reserves once',async()=>{const s=await ready();await fill(s);let tree=s.render(s.props);assert.equal(button(tree,'Prepare reviewed test checkout').props.disabled,false);assert.equal(find(tree,e=>e.type==='option'&&e.props.value==='merged'),null);assert.equal(find(tree,e=>e.type==='option'&&e.props.value==='closed'),null);await Promise.all([submit(tree),submit(tree)]);const posts=s.calls.filter(([,o])=>o);assert.equal(posts.length,1);assert.match(posts[0][1].body.requestId,/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/);assert.deepEqual(posts[0][1].body,{requestId:posts[0][1].body.requestId,donorId:'d1',donorVersion:2,campaignId:'c1',campaignVersion:4,designationId:'f1',designationVersion:3,amountCents:10001,currency:'usd',reason:'Reviewed synthetic test sources',testModeConfirmed:true});assert.match(html(s),/CheckoutReady/);assert.doesNotMatch(html(s),/PaymentVerified|GiftRecorded/);});

test('disabled provider retains history but no preparation, retry, verification, gift recording or checkout handoff',async()=>{let opens=0;const s=await ready({provider:{enabled:false,ready:false,mode:'Disabled',reasonCode:'TEST_PROVIDER_NOT_CONFIGURED'},list:[intent],onOpenCheckout:()=>opens++});assert.match(html(s),/Test checkout is unavailable|no simulated payment/);assert.ok(find(s.tree,e=>e.type==='fieldset').props.disabled);let tree=await select(s);assert.ok(button(tree,'Open Stripe test checkout').props.disabled);button(tree,'Open Stripe test checkout').props.onClick();assert.equal(opens,0);assert.match(html(s),/Reviewed synthetic test checkout/);assert.equal(s.calls.filter(([,o])=>o).length,0);});

test('staff, viewers and event helpers request no private operations and role downgrade immediately hides cached records',async()=>{for(const role of ['staff','viewer','event-helper']){const s=await ready({user:{id:'u1',role}});assert.deepEqual(s.calls,[]);assert.match(html(s),/require administrator/);}const s=await ready({list:[intent]});await select(s);s.props.user={id:'admin1',role:'viewer'};assert.doesNotMatch(renderToStaticMarkup(s.render(s.props)),/Synthetic donor|Reviewed synthetic test checkout/);});

test('same source ID/revision arrays preserve review; actual source revision changes invalidate it',async()=>{const s=await ready();await fill(s);s.props.data=JSON.parse(JSON.stringify(s.props.data));assert.equal(button(s.render(s.props),'Prepare reviewed test checkout').props.disabled,false);s.props.data={...s.props.data,campaigns:[{...campaign,version:5}]};s.render(s.props);assert.ok(button(s.render(s.props),'Prepare reviewed test checkout').props.disabled);assert.match(html(s),/Source records changed/);assert.equal(s.calls.filter(([,o])=>o).length,0);});

test('checkout handoff requires explicit allowed exact session URL and never verifies payment on return',async()=>{const opened=[],s=await ready({list:[intent],onOpenCheckout:url=>opened.push(url)});await select(s);assert.equal(opened.length,0);button(s.render(s.props),'Open Stripe test checkout').props.onClick();assert.deepEqual(opened,[intent.checkoutUrl]);assert.match(html(s),/Returning here does not verify payment|Returning from checkout never marks/);assert.equal(button(s.render(s.props),'Review provider verification'),null);assert.equal(s.calls.filter(([,o])=>o).length,0);for(const url of ['https://checkout.stripe.com.evil.example/c/pay/cs_test_123','https://checkout.stripe.com/c/pay/cs_test_other','https://user@checkout.stripe.com/c/pay/cs_test_123','https://checkout.stripe.com:8443/c/pay/cs_test_123','http://checkout.stripe.com/c/pay/cs_test_123']){const q=await ready({list:[{...intent,checkoutUrl:url}],saved:details({...intent,checkoutUrl:url}),onOpenCheckout:()=>assert.fail('Unsafe handoff')});await select(q);assert.equal(button(q.render(q.props),'Open Stripe test checkout'),null);assert.match(html(q),/Checkout address is not permitted/);}});

test('provider verification and reviewed native recording are separate versioned actions; recorded gift opens its saved revision',async()=>{let currentIntent={...intent,status:'PaymentPending',version:3},opened=[],commits=0;const s=await ready({list:[currentIntent],onOpen:async(...args)=>opened.push(args),onCommitted:async()=>{commits++;s.props.data=JSON.parse(JSON.stringify(s.props.data));s.render(s.props);},api:async(path,o)=>{if(o){currentIntent={...currentIntent,version:currentIntent.version+1,status:path.endsWith('/verify')?'PaymentVerified':'GiftRecorded',paymentMethod:'Credit card',...(path.endsWith('/record-gift')?{giftId:'g1',giftVersion:7}:{})};return{intent:currentIntent};}return path.endsWith('/status')?status:path.includes('?')?{intents:[currentIntent],nextCursor:null}:details(currentIntent);}});await select(s);assert.equal(button(s.render(s.props),'Review native gift recording'),null);reviewAction(s,'Review provider verification');await submit(s.render(s.props));assert.match(html(s),/PaymentVerified/);assert.equal(s.calls.filter(([,o])=>o).length,1);reviewAction(s,'Review native gift recording');await submit(s.render(s.props));await flush();const posts=s.calls.filter(([,o])=>o);assert.deepEqual(posts[0][1].body,{version:3,reason:'Reviewed exact test intent and current facts'});assert.deepEqual(posts[1][1].body,{version:4,donorVersion:2,campaignVersion:4,designationVersion:3,reason:'Reviewed exact test intent and current facts',testModeConfirmed:true});assert.equal(commits,1);assert.doesNotMatch(html(s),/Source records changed/);await button(s.render(s.props),'Open recorded gift').props.onClick();assert.deepEqual(opened,[['gifts','g1',7]]);});

test('uncertain preparation never automatically reposts and blocks new intents until explicit saved-history inspection',async()=>{const s=await ready({api:async(path,o)=>{if(o)throw new Error('Connection lost after reservation');return path.endsWith('/status')?status:{intents:[{...intent,status:'CheckoutUnknown'}],nextCursor:null};}});await fill(s);await submit(s.render(s.props));assert.match(html(s),/response was not confirmed/);assert.ok(button(s.render(s.props),'New test intent').props.disabled);assert.ok(button(s.render(s.props),'Prepare reviewed test checkout').props.disabled);assert.equal(field(s.render(s.props),'Test amount · USD').props.value,'100.01');await flush();assert.equal(s.calls.filter(([,o])=>o).length,1);await button(s.render(s.props),'Discard inputs and inspect saved history').props.onClick();await flush();assert.equal(s.calls.filter(([,o])=>o).length,1);assert.match(html(s),/CheckoutUnknown/);});

test('known saved mutation with unavailable history reports unknown counts and blocks subsequent actions',async()=>{let saved=false;const s=await ready({api:async(path,o)=>{if(o){saved=true;return{intent};}if(path.endsWith('/status'))return status;if(path.includes('?'))return{intents:[],nextCursor:null};if(saved)throw new Error('History unavailable');return details();}});await fill(s);await submit(s.render(s.props));assert.match(html(s),/intent change was saved, but history could not refresh/);assert.match(html(s),/Reload saved intent history to verify action counts/);assert.doesNotMatch(html(s),/0 of 0|No history actions returned/);assert.ok(button(s.render(s.props),'Open Stripe test checkout').props.disabled);assert.equal(s.calls.filter(([,o])=>o).length,1);});

test('retry is explicit only for retained Reserved or CheckoutUnknown with original intent version and test confirmation',async()=>{const i={...intent,status:'CheckoutUnknown',version:3,checkoutUrl:null},s=await ready({list:[i],saved:details(i)});await select(s);reviewAction(s,'Review original checkout retry');assert.match(html(s),/original reserved request|20-hour window/);await submit(s.render(s.props));const post=s.calls.find(([,o])=>o);assert.equal(post[0],'/hosted-giving/intents/i1/retry');assert.deepEqual(post[1].body,{version:3,reason:'Reviewed exact test intent and current facts',testModeConfirmed:true});});

test('current-source failure blocks retained intent mutation and privacy denial removes retained content',async()=>{let deny=false;const i={...intent,status:'PaymentVerified',sourceCurrent:false},s=await ready({list:[i],api:async path=>{if(path.endsWith('/status'))return status;if(path.includes('?'))return{intents:[i],nextCursor:null};if(deny)throw Object.assign(new Error('Account access changed'),{status:401});return details(i);}});await select(s);assert.ok(button(s.render(s.props),'Review native gift recording').props.disabled);deny=true;await button(s.render(s.props),'Refresh saved intents').props.onClick();assert.doesNotMatch(html(s),/Synthetic donor|Reviewed synthetic test checkout/);assert.equal(s.calls.filter(([,o])=>o).length,0);});

test('older detail cannot publish after request identity changes and source-refresh is disabled for dirty inputs',async()=>{let resolve;const s=await ready({list:[intent],api:async path=>path.endsWith('/status')?status:path.includes('?')?{intents:[intent],nextCursor:null}:new Promise(r=>resolve=r)});const pending=button(s.tree,'Synthetic donor').props.onClick();s.props.api=async path=>path.endsWith('/status')?status:{intents:[],nextCursor:null};s.render(s.props);await flush();resolve(details());await pending;assert.doesNotMatch(html(s),/Reviewed synthetic test checkout|<h2>Synthetic donor/);let reloads=0;const q=await ready({onRefreshSources:()=>reloads++});button(q.tree,'Refresh workspace sources').props.onClick();assert.equal(reloads,1);field(q.render(q.props),'Preparation reason').props.onChange({target:{value:'Unsaved reason'}});const tree=q.render(q.props);assert.ok(button(tree,'Refresh workspace sources').props.disabled);button(tree,'Refresh workspace sources').props.onClick();assert.equal(reloads,1);});


test('an intent changed between history/register pages is not silently merged into earlier version facts',async()=>{const s=await ready({api:async path=>path.endsWith('/status')?status:path.includes('after=')?{intents:[{...intent,version:3}],nextCursor:null}:path.includes('?')?{intents:[intent],nextCursor:'i1'}:details()});await select(s);await button(s.render(s.props),'Load more test intents').props.onClick();assert.match(html(s),/Saved intents changed between pages/);assert.match(html(s),/intent v2/);assert.doesNotMatch(html(s),/intent v3/);assert.ok(button(s.render(s.props),'Open Stripe test checkout').props.disabled);});

test('initial register failure is unknown rather than falsely empty, and late unmounted detail never publishes',async()=>{const failed=await ready({api:async()=>{throw new Error('Database temporarily unavailable');}});assert.match(html(failed),/Saved intent register is unavailable/);assert.doesNotMatch(html(failed),/No test intents returned/);let resolve;const s=await ready({list:[intent],api:async path=>path.endsWith('/status')?status:path.includes('?')?{intents:[intent],nextCursor:null}:new Promise(r=>resolve=r)});const pending=button(s.tree,'Synthetic donor').props.onClick();s.render.unmount();resolve(details());await pending;assert.equal(s.calls.filter(([,o])=>o).length,0);});


test('already verified payment preserves original proof and offers only separate recording with fresh provider recheck',async()=>{const i={...intent,status:'PaymentVerified',version:4,paymentMethod:'Credit card'},s=await ready({list:[i],saved:details(i)});await select(s);assert.equal(button(s.render(s.props),'Review provider verification'),null);assert.equal(button(s.render(s.props),'Review native gift recording').props.disabled,false);reviewAction(s,'Review native gift recording');assert.match(html(s),/checks current provider payment facts again/);assert.match(html(s),/refunded or disputed facts require review/);assert.equal(s.calls.filter(([,o])=>o).length,0);});


test('initial creation request UUID stays pinned after uncertain response; only inspected history permits a deliberately new review key',async()=>{let fail=true;const s=await ready({api:async(path,o)=>{if(o&&fail)throw new Error('Lost reservation response');if(o)return{intent};return path.endsWith('/status')?status:path.includes('?')?{intents:[],nextCursor:null}:details();}});await fill(s);const reviewedTree=s.render(s.props);await submit(reviewedTree);const first=s.calls.find(([,o])=>o)[1].body.requestId;assert.match(first,/^[a-f0-9-]{36}$/);assert.ok(html(s).includes(first));assert.ok(button(s.render(s.props),'Prepare reviewed test checkout').props.disabled);await submit(reviewedTree);assert.equal(s.calls.filter(([,o])=>o).length,1);await flush();assert.equal(s.calls.filter(([,o])=>o).length,1);await button(s.render(s.props),'Discard inputs and inspect saved history').props.onClick();await flush();fail=false;await fill(s);await submit(s.render(s.props));const requests=s.calls.filter(([,o])=>o);assert.equal(requests.length,2);assert.notEqual(requests[1][1].body.requestId,first);});
