import test from 'node:test';import assert from 'node:assert/strict';import {once} from 'node:events';import {randomUUID} from 'node:crypto';import Stripe from 'stripe';import {createApp} from '../server/app.js';
const entities=['hostedGivingIntents','hostedGivingEvents','hostedGivingHistory'];
async function fixture(t){
 const password='SyntheticGivingReportsOnly!2026',initialAdmin={name:'Synthetic giving report administrator',email:'giving.reports@example.test',password},tenantId=randomUUID(),sessions={},remote=new Map(),secret='whsec_SYNTHETIC_reports_only',sdk=new Stripe('sk_test_SYNTHETIC_reports_only');
 const adapter={async createSession(params){const id='cs_test_'+randomUUID().replaceAll('-',''),s={id,object:'checkout.session',url:'https://checkout.stripe.com/c/pay/'+id,livemode:false,mode:'payment',status:'open',payment_status:'unpaid',amount_total:params.line_items[0].price_data.unit_amount,amount_subtotal:params.line_items[0].price_data.unit_amount,currency:'usd',metadata:structuredClone(params.metadata),client_reference_id:params.client_reference_id,payment_intent:null};remote.set(id,s);return structuredClone(s);},async retrieveSession(id){return structuredClone(remote.get(id));}};
 const app=createApp({seed:false,tenantId,initialAdmin,mfaKey:'',workflowWorker:false,reminderWorker:false,hostedGiving:{mode:'TEST_ONLY',secretKey:'sk_test_SYNTHETIC_reports_only',webhookSecret:secret,origin:'https://synthetic.example.test',adapter}}),server=app.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{await new Promise(r=>server.close(r));app.locals.close();});const base='http://127.0.0.1:'+server.address().port;
 async function request(path,{method='GET',body,role='admin',raw,signature}={}){const s=sessions[role],r=await fetch(base+'/api'+path,{method,headers:{...(body!==undefined||raw?{'Content-Type':'application/json'}:{}),...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrfToken}:{}),...(signature?{'Stripe-Signature':signature}:{})},...(raw?{body:raw}:body!==undefined?{body:JSON.stringify(body)}:{})});const text=await r.text();let json;try{json=JSON.parse(text);}catch{}return{status:r.status,json,text,headers:r.headers};}
 async function login(email){const r=await request('/auth/login',{method:'POST',role:'anonymous',body:{email,password}});assert.equal(r.status,200,r.text);return{...r.json,cookie:r.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ')};}
 sessions.admin=await login(initialAdmin.email);for(const role of ['staff','viewer']){assert.equal((await request('/users',{method:'POST',body:{name:'Synthetic giving report '+role,email:role+'.giving.reports@example.test',password,role}})).status,201);sessions[role]=await login(role+'.giving.reports@example.test');}
 async function create(c,body){const r=await request('/records/'+c,{method:'POST',body});assert.equal(r.status,201,r.text);return r.json.record;}
 const donor=await create('constituents',{name:'Synthetic real donor source',type:'Individual',preference:'Do not contact'}),campaign=await create('campaigns',{name:'Synthetic giving source',type:'Annual',goal:20000,startDate:'2026-01-01',endDate:'2027-12-31',status:'Active'}),fund=await create('designations',{name:'Synthetic fund source',accountCode:'SYNTHETIC-GIVING'});
 const r=await request('/hosted-giving/intents',{method:'POST',body:{requestId:randomUUID(),donorId:donor.id,donorVersion:donor.version,campaignId:campaign.id,campaignVersion:campaign.version,designationId:fund.id,designationVersion:fund.version,amountCents:10001,currency:'usd',reason:'Synthetic prepared intent source review',testModeConfirmed:true}});assert.equal(r.status,201,r.text);const intent=r.json.intent;
 async function verifyAndRecord(){const s=[...remote.values()][0],pi='pi_'+randomUUID().replaceAll('-',''),charge='ch_'+randomUUID().replaceAll('-','');s.status='complete';s.payment_status='paid';s.payment_intent={id:pi,object:'payment_intent',livemode:false,status:'succeeded',amount:10001,amount_received:10001,currency:'usd',metadata:structuredClone(s.metadata),latest_charge:{id:charge,object:'charge',livemode:false,amount:10001,amount_refunded:0,currency:'usd',paid:true,captured:true,status:'succeeded',refunded:false,disputed:false,payment_intent:pi,payment_method_details:{type:'card'}}};const event={id:'evt_'+randomUUID().replaceAll('-',''),object:'event',created:Math.floor(Date.now()/1000),livemode:false,type:'checkout.session.completed',data:{object:structuredClone(s)}},raw=JSON.stringify(event,null,2);const w=await request('/hosted-giving/webhook',{method:'POST',role:'anonymous',raw,signature:sdk.webhooks.generateTestHeaderString({payload:raw,secret})});assert.ok([200,202].includes(w.status),w.text);const detail=await request('/hosted-giving/intents/'+intent.id);const v=await request('/hosted-giving/intents/'+intent.id+'/verify',{method:'POST',body:{version:detail.json.intent.version,reason:'Synthetic retrieved signed provider evidence'}});assert.equal(v.status,200,v.text);assert.equal(v.json.intent.status,'PaymentVerified');const post=await request('/hosted-giving/intents/'+intent.id+'/record-gift',{method:'POST',body:{version:v.json.intent.version,donorVersion:donor.version,campaignVersion:campaign.version,designationVersion:fund.version,reason:'Synthetic explicit test-only financial source review',testModeConfirmed:true}});assert.equal(post.status,201,post.text);return post.json;}
 const report=(entity,columns,role='admin')=>request('/custom-reports/run',{method:'POST',role,body:{name:'Synthetic giving evidence',entity,columns,filters:[],groupBy:[],aggregates:[],includeVoided:false}});
 return{app,request,login,sessions,password,initialAdmin,donor,campaign,fund,intent,report,verifyAndRecord,remote,secret,sdk,gifts:()=>app.locals.db.prepare("SELECT data FROM records WHERE collection='gifts' ORDER BY id").all().map(r=>JSON.parse(r.data))};
}
test('hosted giving reports exclude provider secrets and require current administrator access for catalogs and saved execution',async t=>{
 const f=await fixture(t),catalog=await f.request('/custom-reports/catalog');assert.equal(catalog.status,200,catalog.text);
 for(const entity of entities){const source=catalog.json.entities.find(e=>e.id===entity);assert.equal(source?.requiredRole,'admin',entity);assert.match(source.description,/not new income/);assert.equal((await f.report(entity,['id'])).status,200);for(const role of ['staff','viewer']){assert.equal((await f.report(entity,['id'],role)).status,403);const other=await f.request('/custom-reports/catalog',{role});assert.equal(other.json.entities.some(e=>e.id===entity),false);}for(const key of ['checkoutUrl','raw','payload','signature','idempotencyKey','binding','email','secret'])assert.equal((await f.report(entity,[key])).status,400,entity+':'+key);}
 const saved=await f.request('/custom-reports',{method:'POST',body:{name:'Private giving evidence',entity:'hostedGivingIntents',columns:['id','amountCents','recordedCashCents']}});assert.equal(saved.status,201,saved.text);for(const role of ['staff','viewer'])assert.equal((await f.request('/custom-reports/'+saved.json.report.id+'/run',{role})).status,403);assert.equal(f.gifts().length,0);
});
test('prepared and provider history amounts remain distinct from exactly one current native recorded gift',async t=>{
 const f=await fixture(t),before=await f.report('hostedGivingIntents',['id','amountCents','recordedCashCents']);assert.equal(before.status,200,before.text);assert.deepEqual(before.json.rows,[[f.intent.id,10001,0]]);assert.equal(f.gifts().length,0);
 await f.verifyAndRecord();const gifts=f.gifts();assert.equal(gifts.length,1);const g=gifts[0];assert.equal(g.constituentId,f.donor.id);assert.equal(g.amount,10001);assert.equal(g.method,'Credit card');assert.equal(g.status,'Posted');
 const after=await f.report('hostedGivingIntents',['id','amountCents','recordedCashCents','giftId','donorId']);assert.equal(after.status,200,after.text);assert.deepEqual(after.json.rows,[[f.intent.id,10001,10001,g.id,f.donor.id]]);assert.deepEqual(after.json.recordReferences,[{collection:'gifts',id:g.id}]);assert.equal(after.json.columns.find(x=>x.key==='recordedCashCents').type,'money');
 const history=await f.report('hostedGivingHistory',['id']);assert.equal(history.status,200,history.text);assert.ok(history.json.rows.length>=3);assert.deepEqual(f.gifts(),gifts);
});
test('scheduled hosted-giving evidence retains private access after owner downgrade without changing financial records',async t=>{
 const f=await fixture(t);await f.verifyAndRecord();const gifts=f.gifts(),saved=await f.request('/custom-reports',{method:'POST',body:{name:'Private giving snapshot',entity:'hostedGivingIntents',columns:['id','amountCents','recordedCashCents']}});assert.equal(saved.status,201,saved.text);const startAt=new Date(Date.now()+30000).toISOString(),schedule=await f.request('/report-schedules',{method:'POST',body:{name:'Private giving snapshot',reportId:saved.json.report.id,cadence:'Daily',startAt}});assert.equal(schedule.status,201,schedule.text);assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1).produced,1);
 const d=f.app.locals.db.prepare('SELECT id,result FROM report_deliveries WHERE schedule_id=?').get(schedule.json.schedule.id);assert.equal(JSON.parse(d.result).requiredRole,'admin');for(const role of ['staff','viewer'])assert.equal((await f.request('/report-deliveries/'+d.id,{role})).status,403);
 assert.equal((await f.request('/users',{method:'POST',body:{name:'Second synthetic giving administrator',email:'second.giving.reports@example.test',password:f.password,role:'admin'}})).status,201);const original=f.sessions.admin.user;assert.equal((await f.request('/users/'+original.id,{method:'PATCH',body:{version:1,role:'staff',active:true}})).status,200);f.sessions.admin=await f.login(f.initialAdmin.email);assert.equal((await f.request('/report-deliveries/'+d.id)).status,403);assert.equal((await f.request('/custom-reports/'+saved.json.report.id+'/run')).status,403);assert.deepEqual(f.gifts(),gifts);
});

test('signed refund review appears in curated evidence while original native income and history remain unchanged',async t=>{
 const f=await fixture(t);await f.verifyAndRecord();const gifts=f.gifts(),s=[...f.remote.values()][0],event={id:'evt_'+randomUUID().replaceAll('-',''),object:'event',created:Math.floor(Date.now()/1000),livemode:false,type:'charge.refunded',data:{object:{...structuredClone(s.payment_intent.latest_charge),amount_refunded:1,refunded:false}}},raw=JSON.stringify(event,null,2);
 const w=await f.request('/hosted-giving/webhook',{method:'POST',role:'anonymous',raw,signature:f.sdk.webhooks.generateTestHeaderString({payload:raw,secret:f.secret})});assert.equal(w.status,200,w.text);
 const current=await f.report('hostedGivingIntents',['id','status','recordedCashCents','giftId']);assert.equal(current.status,200,current.text);assert.deepEqual(current.json.rows,[[f.intent.id,'ReviewRequired',10001,gifts[0].id]]);
 const events=await f.report('hostedGivingEvents',['eventType','paymentStatus']);assert.equal(events.status,200,events.text);assert.ok(events.json.rows.some(r=>r[0]==='charge.refunded'&&r[1]==='review_required'));
 const history=await f.report('hostedGivingHistory',['status','giftId']);assert.equal(history.status,200,history.text);assert.ok(history.json.rows.some(r=>r[0]==='GiftRecorded'));assert.ok(history.json.rows.some(r=>r[0]==='ReviewRequired'));assert.deepEqual(f.gifts(),gifts);
});
