import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { randomUUID, randomBytes, createHash } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../server/app.js';
import { createMailchimpContactAdapter, validateMailchimpContactSyncConfig } from '../server/mailchimpContactSync.js';
import { backupWorkspace, restoreWorkspace } from '../server/backup.js';
const password='SyntheticContactSync!2026',listId='list123',md5=email=>createHash('md5').update(email.toLowerCase()).digest('hex');
const ownerPolicy={approved:true,reference:'Synthetic owner-approved mapping — no live adoption',version:1,purpose:'Existing contact synchronization',existingMemberUpdates:true,mergeFields:[{tag:'CONTACT',field:'name',type:'text'},{tag:'PHONE',field:'phone',type:'text'},{tag:'KIND',field:'type',type:'text'}]};
const config=adapter=>({mode:'TEST_ONLY',access:'EXISTING_MEMBER_UPDATE',serverPrefix:'us1',apiKey:'a'.repeat(32)+'-us1',listId,ownerPolicy,adapter});
async function fixture(t){
 const dir=await mkdtemp(join(tmpdir(),'wimblo-contact-sync-')),dbPath=join(dir,'workspace.sqlite'),tenantId=randomUUID(),mfaKey=randomBytes(32).toString('base64'),initialAdmin={name:'Synthetic sync admin',email:'sync.admin@example.test',password},members=new Map(),calls=[],sessions={};let app,server,base,active=true,getHook=null,patchHook=null;
 const adapter={async getMember(id){calls.push({method:'GET',id});if(getHook)return getHook(id);assert.ok(members.has(id));return structuredClone(members.get(id));},async updateMember(id,payload){calls.push({method:'PATCH',id,payload:structuredClone(payload)});if(patchHook)return patchHook(id,payload);const m=members.get(id);if(payload.status)m.status=payload.status;if(payload.merge_fields)Object.assign(m.merge_fields,payload.merge_fields);return structuredClone(m);}};
 const readonly={mode:'TEST_ONLY',access:'READ_ONLY',serverPrefix:'us1',apiKey:'a'.repeat(32)+'-us1',listId,webhookSecret:'SyntheticInboundPolicySecretNotReal2026',adapter:{getMember:adapter.getMember,getCampaignReport:async()=>{throw Error('No reports requested');}}};
 async function request(path,{method='GET',body,session=sessions.admin,csrf=true}={}){const r=await fetch(base+'/api'+path,{method,headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...(session?{Cookie:session.cookie,...(csrf?{'X-CSRF-Token':session.csrfToken}:{})}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const text=await r.text();let json;try{json=JSON.parse(text);}catch{}return {status:r.status,json,text,headers:r.headers};}
 async function login(email=initialAdmin.email){const r=await request('/auth/login',{method:'POST',session:null,body:{email,password}});assert.equal(r.status,200,r.text);return {...r.json,cookie:r.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ')};}
 async function close(){if(server)await new Promise(resolve=>server.close(resolve));server=null;app?.locals.close();app=null;}
 async function open(path=dbPath){app=createApp({dbPath:path,seed:false,tenantId,initialAdmin,mfaKey,isTenantActive:()=>active,workflowWorker:false,reminderWorker:false,marketingResponses:readonly,mailchimpContactSync:config(adapter)});server=app.listen(0,'127.0.0.1');await once(server,'listening');base='http://127.0.0.1:'+server.address().port;sessions.admin=await login();}
 await open();t.after(async()=>{await close();await rm(dir,{recursive:true,force:true});});
 for(const role of ['staff','viewer','event-helper']){const r=await request('/users',{method:'POST',body:{name:'Synthetic '+role,email:role+'.sync@example.test',role,password}});assert.equal(r.status,201,r.text);sessions[role]=await login(role+'.sync@example.test');}
 async function create(collection,body){const r=await request('/records/'+collection,{method:'POST',body});assert.equal(r.status,201,r.text);return r.json.record;}
 const donor=await create('constituents',{name:'Warm Full Contact Name',type:'Individual',email:'actual.sync@example.test',phone:'555-0100',preference:'Email',contacts:[{name:'Secondary contact',email:'secondary.sync@example.test',role:'Friend'}]}),fund=await create('designations',{name:'Synthetic fund',accountCode:'SYNC-100'}),gift=await create('gifts',{constituentId:donor.id,amount:12345,type:'Cash',method:'Check',date:'2026-09-01',giftKind:'One-time',allocations:[{designationId:fund.id,amount:12345}]});
 const member={id:md5(donor.email),email_address:donor.email,list_id:listId,status:'subscribed',last_changed:'2026-09-01T12:00:00+00:00',unique_email_id:'opaque1234',merge_fields:{CONTACT:'Old external contact',PHONE:'',KIND:'',UNAPPROVED:'Never overwritten'}};members.set(member.id,member);
 const bindingResponse=await request('/marketing-responses/bindings',{method:'POST',body:{requestId:randomUUID(),constituentId:donor.id,constituentVersion:donor.version,listId,memberId:member.id,reason:'Verify existing primary member',readOnlyConfirmed:true}});assert.equal(bindingResponse.status,201,bindingResponse.text);const binding=bindingResponse.json.binding;
 const tables=['mailchimp_contact_sync_intents','mailchimp_contact_sync_history','mailchimp_contact_sync_suppressions'];
 const snapshot=()=>Object.fromEntries(['records',...tables].map(n=>[n,app.locals.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));
 const body=(overrides={})=>({requestId:randomUUID(),constituentId:donor.id,constituentVersion:donor.version,bindingId:binding.id,bindingVersion:binding.version,reason:'Reviewed approved text fields on existing member',confirmed:true,...overrides});
 const prepare=(payload=body())=>request('/mailchimp-contact-sync/intents',{method:'POST',body:payload});
 const action=(intent,name='execute',overrides={})=>request('/mailchimp-contact-sync/intents/'+intent.id+'/'+name,{method:'POST',body:{version:intent.version,reason:'Explicit reviewed '+name,confirmed:true,...overrides}});
 const detail=id=>request('/mailchimp-contact-sync/intents/'+id);
 return {dir,dbPath,tenantId,initialAdmin,mfaKey,readonly,adapter,donor,fund,gift,binding,member,members,calls,sessions,tables,snapshot,body,prepare,action,detail,request,create,close,open,get db(){return app.locals.db;},get service(){return app.locals.mailchimpContactSync;},get active(){return active;},set active(v){active=v;},set getHook(fn){getHook=fn;},set patchHook(fn){patchHook=fn;}};
}
const okIntent=r=>{assert.equal(r.status,201,r.text);return r.json.intent;};
const patchCount=f=>f.calls.filter(c=>c.method==='PATCH').length;

test('explicit existing-member text update is readback verified, exact request replay is terminal and no native financial/contact state changes',async t=>{
 const f=await fixture(t),native=f.snapshot().records,payload=f.body(),intent=okIntent(await f.prepare(payload));assert.equal(intent.operation,'UpdateFields');assert.deepEqual(intent.changes,{merge_fields:{CONTACT:f.donor.name,PHONE:f.donor.phone,KIND:f.donor.type}});assert.equal(patchCount(f),0);
 const executed=await f.action(intent);assert.equal(executed.status,200,executed.text);assert.equal(executed.json.intent.status,'Reconciled');assert.equal(executed.json.intent.writeAttempted,true);assert.equal(patchCount(f),1);assert.equal(f.member.merge_fields.UNAPPROVED,'Never overwritten');assert.equal(f.member.status,'subscribed');assert.deepEqual(f.snapshot().records,native);
 const count=f.calls.length,replay=await f.prepare(payload);assert.equal(replay.status,201,replay.text);assert.equal(replay.json.replayed,true);assert.equal(replay.json.intent.id,intent.id);assert.equal(replay.json.intent.status,'Reconciled');assert.equal(f.calls.length,count);assert.equal((await f.action(executed.json.intent)).status,409);assert.equal(patchCount(f),1);assert.equal((await f.prepare({...payload,reason:'Alter original approved intent'})).status,409);
 const detail=await f.detail(intent.id);assert.deepEqual(detail.json.history.map(x=>x.action),['reconcile','reserve','prepare']);const text=JSON.stringify(detail.json);for(const secret of [f.donor.email,'UNAPPROVED','source_json','actor_binding',f.readonly.apiKey])assert.ok(!text.includes(secret));assert.equal((await f.request('/mailchimp-contact-sync/status')).json.productionReady,false);
});

test('verified provider opt-out remains sticky in BOTH sync and legacy eligibility, even after stale subscribed refresh and new request',async t=>{
 const f=await fixture(t),native=f.snapshot().records;f.member.status='unsubscribed';const intent=okIntent(await f.prepare());assert.equal(intent.operation,'NoChange');assert.equal(intent.suppressed,true);const old=await f.request('/marketing-responses/bindings/'+f.binding.id);assert.equal(old.json.binding.marketingEligible,false);assert.equal(old.json.binding.suppressed,true);assert.equal(old.json.binding.providerStatus,'subscribed');
 const done=await f.action(intent);assert.equal(done.status,200,done.text);assert.equal(patchCount(f),0);f.member.status='subscribed';const refresh=await f.request('/marketing-responses/bindings/'+f.binding.id+'/refresh',{method:'POST',body:{version:f.binding.version,reason:'Stale subscribed provider read',readOnlyConfirmed:true}});assert.equal(refresh.status,200,refresh.text);assert.equal(refresh.json.binding.marketingEligible,false);f.binding.version=refresh.json.binding.version;
 const next=okIntent(await f.prepare(f.body({bindingVersion:f.binding.version})));assert.equal(next.operation,'Unsubscribe');assert.deepEqual(next.changes,{status:'unsubscribed'});const denied=await f.action(next);assert.equal(denied.status,200,denied.text);assert.equal(f.member.status,'unsubscribed');assert.equal(patchCount(f),1);assert.deepEqual(f.snapshot().records,native);
});

test('native DNC causes only unsubscribe, and pending/transactional/cleaned provider members never become subscribed',async t=>{
 const f=await fixture(t);f.db.prepare("UPDATE records SET data=json_set(data,'$.preference','Do not contact','$.version',2) WHERE collection='constituents' AND id=?").run(f.donor.id);const stale=await f.prepare();assert.equal(stale.status,409,stale.text);
 // A new explicit native source + verified binding is necessary; never reuse stale custody.
 const retired=await f.request('/marketing-responses/bindings/'+f.binding.id+'/retire',{method:'POST',body:{version:f.binding.version,reason:'Source changed; reverify denied preference'}});assert.equal(retired.status,200,retired.text);
 const b=await f.request('/marketing-responses/bindings',{method:'POST',body:{requestId:randomUUID(),constituentId:f.donor.id,constituentVersion:2,listId,memberId:f.member.id,reason:'Explicit DNC source',readOnlyConfirmed:true}});assert.equal(b.status,201,b.text);const intent=okIntent(await f.prepare(f.body({constituentVersion:2,bindingId:b.json.binding.id,bindingVersion:b.json.binding.version})));assert.equal(intent.operation,'Unsubscribe');assert.deepEqual(intent.changes,{status:'unsubscribed'});assert.equal((await f.action(intent)).status,200);assert.equal(f.member.status,'unsubscribed');
 for(const status of ['pending','transactional','cleaned']){const other=await fixture(t);other.member.status=status;const p=okIntent(await other.prepare());assert.equal(p.operation,'NoChange');assert.equal((await other.action(p)).status,200);assert.equal(other.member.status,status);assert.equal(patchCount(other),0);}
});

test('staff/viewer/helper and missing CSRF are denied, strict fields reject subscribe/new-member/foreign binding and bad pagination',async t=>{
 const f=await fixture(t),before=f.snapshot();for(const role of ['staff','viewer','event-helper']){for(const path of ['/mailchimp-contact-sync/status','/mailchimp-contact-sync/intents','/mailchimp-contact-sync/intents/'+randomUUID()])assert.equal((await f.request(path,{session:f.sessions[role]})).status,403);assert.equal((await f.request('/mailchimp-contact-sync/intents',{method:'POST',body:f.body(),session:f.sessions[role]})).status,403);}
 assert.equal((await f.request('/mailchimp-contact-sync/intents',{method:'POST',body:f.body(),csrf:false})).status,403);for(const extra of [{status:'subscribed'},{email:'new@example.test'},{confirmed:false},{bindingId:randomUUID()},{constituentId:randomUUID()}])assert.ok([400,404,409].includes((await f.prepare(f.body(extra))).status));for(const q of ['?limit=101','?after=invalid','?unsupported=true'])assert.equal((await f.request('/mailchimp-contact-sync/intents'+q)).status,400);assert.deepEqual(f.snapshot(),before);assert.equal(patchCount(f),0);
});

test('primary email/version/source drift invalidates reviewed sync and secondary contacts cannot supply provider identity',async t=>{
 const f=await fixture(t),p=okIntent(await f.prepare());f.db.prepare("UPDATE records SET data=json_set(data,'$.email','secondary.sync@example.test','$.version',2) WHERE collection='constituents' AND id=?").run(f.donor.id);const before=f.snapshot();assert.equal((await f.action(p)).status,409);assert.equal((await f.detail(p.id)).json.intent.sourceCurrent,false);assert.deepEqual(f.snapshot(),before);assert.equal(patchCount(f),0);
});

test('source/account/factor/tenant changes during reviewed async GET prevent intent authority without native side effects',async t=>{
 for(const kind of ['source','account','factor','tenant']){const f=await fixture(t),native=f.snapshot().records;f.getHook=async()=>{if(kind==='source')f.db.prepare("UPDATE records SET data=json_set(data,'$.name','Changed during provider read') WHERE collection='constituents' AND id=?").run(f.donor.id);if(kind==='account')f.db.prepare('UPDATE users SET version=version+1 WHERE id=?').run(f.sessions.admin.user.id);if(kind==='factor')f.db.prepare('INSERT INTO mfa_settings(user_id,enabled,encrypted_secret,last_step,updated_at) VALUES(?,0,NULL,-1,?) ON CONFLICT(user_id) DO UPDATE SET encrypted_secret=?').run(f.sessions.admin.user.id,new Date().toISOString(),'Unavailable changed factor');if(kind==='tenant')f.active=false;return structuredClone(f.member);};const r=await f.prepare();assert.ok([401,409,503].includes(r.status),kind+': '+r.text);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM mailchimp_contact_sync_intents').get().n,0);assert.equal(patchCount(f),0);if(kind!=='source')assert.deepEqual(f.snapshot().records,native);}
});

test('ambiguous applied PATCH is durable Unknown; neither execute nor a new UUID retries, explicit readback reconciles once',async t=>{
 const f=await fixture(t),p=okIntent(await f.prepare()),native=f.snapshot().records;f.patchHook=async(id,payload)=>{Object.assign(f.member.merge_fields,payload.merge_fields);throw Error('Synthetic secret provider error '+f.readonly.apiKey);};const uncertain=await f.action(p);assert.equal(uncertain.status,409,uncertain.text);assert.ok(!uncertain.text.includes(f.readonly.apiKey));const current=(await f.detail(p.id)).json.intent;assert.equal(current.status,'Unknown');assert.equal(current.writeAttempted,true);assert.equal(patchCount(f),1);assert.equal((await f.action(current)).status,409);assert.equal((await f.prepare()).status,409);f.patchHook=null;const reconciled=await f.action(current,'reconcile');assert.equal(reconciled.status,200,reconciled.text);assert.equal(reconciled.json.intent.status,'Reconciled');assert.equal(patchCount(f),1);assert.deepEqual(f.snapshot().records,native);
});

test('remote unsubscribe during approved field PATCH is retained, never resubscribed and suppresses stale legacy eligibility',async t=>{
 const f=await fixture(t),p=okIntent(await f.prepare());f.patchHook=async(id,payload)=>{assert.deepEqual(Object.keys(payload),['merge_fields']);Object.assign(f.member.merge_fields,payload.merge_fields);f.member.status='unsubscribed';return f.member;};const r=await f.action(p);assert.equal(r.status,200,r.text);assert.equal(r.json.intent.status,'ReviewRequired');assert.equal(r.json.intent.suppressed,true);assert.equal(f.member.status,'unsubscribed');assert.equal((await f.request('/marketing-responses/bindings/'+f.binding.id)).json.binding.marketingEligible,false);assert.equal((await f.prepare()).status,409);assert.equal(patchCount(f),1);
});

test('audit and deferred COMMIT faults never claim provider completion and cannot automatically repeat remote update',async t=>{
 for(const kind of ['audit','commit','poison']){const f=await fixture(t),p=okIntent(await f.prepare()),native=f.snapshot().records;const predicate="NEW.action='mailchimp_contact_sync_reconcile'";if(kind==='audit')f.db.exec("CREATE TRIGGER sync_fault BEFORE INSERT ON audit WHEN "+predicate+" BEGIN SELECT RAISE(ABORT,'Synthetic final audit unavailable'); END");if(kind==='poison')f.db.exec("CREATE TRIGGER sync_fault AFTER INSERT ON audit WHEN "+predicate+" BEGIN UPDATE mailchimp_contact_sync_intents SET version=version+1; END");if(kind==='commit')f.db.exec("CREATE TABLE sync_commit_fault(owner_id TEXT REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED); CREATE TRIGGER sync_fault AFTER INSERT ON audit WHEN "+predicate+" BEGIN INSERT INTO sync_commit_fault VALUES('missing-owner'); END");const r=await f.action(p);assert.equal(r.status,409,r.text);const current=(await f.detail(p.id)).json.intent;assert.equal(current.status,'Unknown');assert.equal(patchCount(f),1);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM mailchimp_contact_sync_history WHERE status='Reconciled'").get().n,0);assert.deepEqual(f.snapshot().records,native);f.db.exec('DROP TRIGGER sync_fault');const finish=await f.action(current,'reconcile');assert.equal(finish.status,200,finish.text);assert.equal(finish.json.intent.status,'Reconciled');assert.equal(patchCount(f),1);}
});

test('two concurrent prepared UUIDs retain one active intent; executing reservation blocks concurrent repeated write',async t=>{
 const f=await fixture(t);let release,entered;const gate=new Promise(r=>release=r),started=new Promise(r=>entered=r);let reads=0;f.getHook=async()=>{if(++reads===1){entered();await gate;}return structuredClone(f.member);};const slow=f.prepare();await started;const fast=await f.prepare();release();const late=await slow;assert.equal(fast.status,201,fast.text);assert.equal(late.status,409,late.text);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM mailchimp_contact_sync_intents').get().n,1);f.getHook=null;
 const p=fast.json.intent;let done,called;const wait=new Promise(r=>done=r),invoked=new Promise(r=>called=r);f.patchHook=async(id,payload)=>{called();await wait;Object.assign(f.member.merge_fields,payload.merge_fields);return f.member;};const running=f.action(p);await invoked;const current=(await f.detail(p.id)).json.intent;assert.equal(current.status,'Executing');assert.equal(current.writeAttempted,true);const duplicate=await f.action(current);assert.equal(duplicate.status,409,duplicate.text);done();assert.equal((await running).status,200);assert.equal(patchCount(f),1);
});

test('restart and authenticated encrypted new-path recovery retain three sync ledgers; restored prior authority cannot rearm or PATCH',async t=>{
 const f=await fixture(t),payload=f.body(),p=okIntent(await f.prepare(payload));f.patchHook=async()=>{throw Error('Ambiguous synthetic transport');};assert.equal((await f.action(p)).status,409);const before=f.snapshot(),calls=f.calls.length;await f.close();await f.open();const unknown=(await f.detail(p.id)).json.intent;assert.equal(unknown.status,'Unknown');assert.equal((await f.prepare(payload)).json.intent.id,p.id);assert.equal(f.calls.length,calls);assert.deepEqual(f.snapshot(),before);
 const archivePath=join(f.dir,'sync.wbackup'),destinationPath=join(f.dir,'restored.sqlite'),encryptionKey=randomBytes(32).toString('base64'),backup=await backupWorkspace({db:f.db,outputPath:archivePath,tenantId:f.tenantId,encryptionKey});for(const table of f.tables)assert.equal(backup.tables.find(x=>x.name===table).count,before[table].length);await f.close();await restoreWorkspace({archivePath,destinationPath,expectedTenantId:f.tenantId,encryptionKey});await f.open(destinationPath);const restored=(await f.detail(p.id)).json.intent;assert.equal(restored.sourceCurrent,false);assert.equal(restored.status,'Unknown');assert.equal((await f.action(restored,'reconcile')).status,409);assert.equal((await f.prepare(payload)).status,409);assert.equal(f.calls.length,calls);for(const table of f.tables)assert.deepEqual(f.snapshot()[table],before[table]);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM sessions').get().n,1);
});

test('owner-approved fixed-host adapter only permits bounded approved existing-member PATCH; disabled/test/production configs cannot grant live authority',async()=>{
 assert.equal(validateMailchimpContactSyncConfig(null),null);assert.throws(()=>validateMailchimpContactSyncConfig(config(null)));assert.throws(()=>validateMailchimpContactSyncConfig(config({getMember(){},updateMember(){}}),{production:true}));assert.throws(()=>createMailchimpContactAdapter(config({getMember(){},updateMember(){}})));
 const approved={...config(undefined),mode:'OWNER_APPROVED'};delete approved.adapter;const requests=[],adapter=createMailchimpContactAdapter(approved,{fetchImpl:async(url,options)=>{requests.push({url,options});return new Response(JSON.stringify({verified:'synthetic'}),{status:200});}}),member='b'.repeat(32);await adapter.getMember(member);await adapter.updateMember(member,{merge_fields:{CONTACT:'Exact full name'}});await adapter.updateMember(member,{status:'unsubscribed'});assert.ok(requests.every(x=>x.url==='https://us1.api.mailchimp.com/3.0/lists/list123/members/'+member&&x.options.redirect==='error'));assert.deepEqual(requests.map(x=>x.options.method),['GET','PATCH','PATCH']);assert.deepEqual(JSON.parse(requests[1].options.body),{merge_fields:{CONTACT:'Exact full name'}});
 for(const payload of [{status:'subscribed'},{email_address:'new@example.test'},{merge_fields:{FNAME:'Unapproved'}},{merge_fields:{CONTACT:'x'.repeat(256)}},{merge_fields:[]},{},{merge_fields:{CONTACT:'Name'},status:'unsubscribed'}])await assert.rejects(adapter.updateMember(member,payload));assert.equal(requests.length,3);await assert.rejects(adapter.getMember('../foreign'));
 const errors=createMailchimpContactAdapter(approved,{fetchImpl:async()=>new Response('SECRET='+approved.apiKey,{status:403})});await assert.rejects(errors.getMember(member),e=>e.status===502&&!e.message.includes(approved.apiKey));
});

test('final write-reservation suppression injection denies field PATCH before invocation and rolls back fabricated deny row',async t=>{
 const f=await fixture(t),p=okIntent(await f.prepare()),native=f.snapshot().records;f.db.exec(`CREATE TRIGGER sync_reservation_fault AFTER UPDATE OF write_attempted ON mailchimp_contact_sync_intents WHEN NEW.write_attempted=1 AND OLD.write_attempted=0 BEGIN INSERT INTO marketing_suppressions VALUES('synthetic-valid-deny',NEW.tenant_id,NEW.list_id,NEW.member_id,NEW.binding_id,'Unsubscribed','Reviewed observation',NEW.id,NEW.updated_at); END`);const r=await f.action(p);assert.equal(r.status,409,r.text);assert.equal(patchCount(f),0);const current=(await f.detail(p.id)).json.intent;assert.equal(current.status,'Unknown');assert.equal(current.writeAttempted,false);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM marketing_suppressions WHERE id='synthetic-valid-deny'").get().n,0);assert.deepEqual(f.snapshot().records,native);f.db.exec('DROP TRIGGER sync_reservation_fault');
});

test('account/factor/tenant/source drift during applied PATCH prevents completion and never grants another mutation',async t=>{
 for(const kind of ['source','account','factor','tenant']){const f=await fixture(t),p=okIntent(await f.prepare());f.patchHook=async(id,payload)=>{Object.assign(f.member.merge_fields,payload.merge_fields);if(kind==='source')f.db.prepare("UPDATE records SET data=json_set(data,'$.notes','Changed while external update pending') WHERE collection='constituents' AND id=?").run(f.donor.id);if(kind==='account')f.db.prepare('UPDATE users SET version=version+1 WHERE id=?').run(f.sessions.admin.user.id);if(kind==='factor')f.db.prepare('INSERT INTO mfa_settings(user_id,enabled,encrypted_secret,last_step,updated_at) VALUES(?,0,NULL,-1,?)').run(f.sessions.admin.user.id,new Date().toISOString());if(kind==='tenant')f.active=false;return f.member;};const r=await f.action(p);assert.ok([401,409,503].includes(r.status),kind+': '+r.text);assert.equal(patchCount(f),1);assert.equal(f.db.prepare('SELECT status FROM mailchimp_contact_sync_intents WHERE id=?').get(p.id).status,'Unknown');assert.equal(f.db.prepare("SELECT COUNT(*) n FROM mailchimp_contact_sync_history WHERE status='Reconciled'").get().n,0);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM records WHERE collection='gifts'").get().n,1);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM records WHERE collection='communications'").get().n,0);}
});

test('provider success return is insufficient: unchanged readback requires review, and reviewed text is never truncated',async t=>{
 const f=await fixture(t),p=okIntent(await f.prepare());f.patchHook=async()=>({status:'subscribed',merge_fields:{CONTACT:f.donor.name}});const r=await f.action(p);assert.equal(r.status,200,r.text);assert.equal(r.json.intent.status,'ReviewRequired');assert.equal(r.json.intent.lastErrorCode,'READBACK_MISMATCH');assert.equal(patchCount(f),1);assert.equal((await f.prepare()).status,409);
 const big=await fixture(t);big.member.merge_fields.CONTACT='é'.repeat(128);const badProvider=await big.prepare();assert.equal(badProvider.status,502,badProvider.text);assert.equal(big.db.prepare('SELECT COUNT(*) n FROM mailchimp_contact_sync_intents').get().n,0);assert.equal(patchCount(big),0);
});
