import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { randomUUID, randomBytes, createHash } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../server/app.js';
import { createMailchimpContactAdapter, validateMailchimpContactSyncConfig } from '../server/mailchimpContactSync.js';
import { backupWorkspace, restoreWorkspace } from '../server/backup.js';
const password='SyntheticContactSync!2026',listId='list123',md5=email=>createHash('md5').update(email.toLowerCase()).digest('hex');
const ownerPolicy={approved:true,reference:'Synthetic owner-approved mapping — no live adoption',version:1,purpose:'Existing contact synchronization',existingMemberUpdates:true,mergeFields:[{tag:'CONTACT',field:'name',type:'text'},{tag:'PHONE',field:'phone',type:'text'},{tag:'KIND',field:'type',type:'text'}]};
const config=adapter=>({mode:'TEST_ONLY',access:'EXISTING_MEMBER_UPDATE',serverPrefix:'us1',apiKey:'a'.repeat(32)+'-us1',listId,ownerPolicy,adapter});
async function fixture(t){
 const dir=await mkdtemp(join(tmpdir(),'wimblo-contact-sync-')),dbPath=join(dir,'workspace.sqlite'),tenantId=randomUUID(),mfaKey=randomBytes(32).toString('base64'),initialAdmin={name:'Synthetic sync admin',email:'sync.admin@example.test',password},members=new Map(),calls=[],sessions={};let app,server,base,active=true,getHook=null,patchHook=null;
 const adapter={async getMember(id){calls.push({method:'GET',id});if(getHook)return getHook(id);assert.ok(members.has(id));return structuredClone(members.get(id));},async updateMember(id,payload){calls.push({method:'PATCH',id,payload:structuredClone(payload)});if(patchHook)return patchHook(id,payload);const m=members.get(id);if(payload.status)m.status=payload.status;if(payload.merge_fields)Object.assign(m.merge_fields,payload.merge_fields);return structuredClone(m);}};
 const readonly={mode:'TEST_ONLY',access:'READ_ONLY',serverPrefix:'us1',apiKey:'a'.repeat(32)+'-us1',listId,webhookSecret:'SyntheticInboundPolicySecretNotReal2026',adapter:{getMember:adapter.getMember,getCampaignReport:async()=>{throw Error('No reports requested');}}};
 async function request(path,{method='GET',body,session=sessions.admin,csrf=true}={}){const r=await fetch(base+'/api'+path,{method,headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...(session?{Cookie:session.cookie,...(csrf?{'X-CSRF-Token':session.csrfToken}:{})}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const text=await r.text();let json;try{json=JSON.parse(text);}catch{}return {status:r.status,json,text,headers:r.headers};}
 async function login(email=initialAdmin.email){const r=await request('/auth/login',{method:'POST',session:null,body:{email,password}});assert.equal(r.status,200,r.text);return {...r.json,cookie:r.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ')};}
 async function close(){if(server)await new Promise(resolve=>server.close(resolve));server=null;app?.locals.close();app=null;}
 async function open(path=dbPath){app=createApp({dbPath:path,seed:false,tenantId,initialAdmin,mfaKey,isTenantActive:()=>active,workflowWorker:false,reminderWorker:false,marketingResponses:readonly,mailchimpContactSync:config(adapter)});server=app.listen(0,'127.0.0.1');await once(server,'listening');base='http://127.0.0.1:'+server.address().port;sessions.admin=await login();}
 await open();t.after(async()=>{await close();await rm(dir,{recursive:true,force:true});});
 for(const role of ['staff','viewer','event-helper']){const r=await request('/users',{method:'POST',body:{name:'Synthetic '+role,email:role+'.sync@example.test',role,password}});assert.equal(r.status,201,r.text);sessions[role]=await login(role+'.sync@example.test');}
 async function create(collection,body){const r=await request('/records/'+collection,{method:'POST',body});assert.equal(r.status,201,r.text);return r.json.record;}
 const donor=await create('constituents',{name:'Warm Full Contact Name',type:'Individual',email:'actual.sync@example.test',phone:'555-0100',preference:'Email',contacts:[{name:'Secondary contact',email:'secondary.sync@example.test',role:'Friend'}]}),fund=await create('designations',{name:'Synthetic fund',accountCode:'SYNC-100'}),gift=await create('gifts',{constituentId:donor.id,amount:12345,type:'Cash',method:'Check',date:'2026-09-01',giftKind:'One-time',allocations:[{designationId:fund.id,amount:12345}]});
 const member={id:md5(donor.email),email_address:donor.email,list_id:listId,status:'subscribed',last_changed:'2026-09-01T12:00:00+00:00',unique_email_id:'opaque1234',merge_fields:{CONTACT:'Old external contact',PHONE:'',KIND:'',UNAPPROVED:'Never overwritten'}};members.set(member.id,member);
 const bindingResponse=await request('/marketing-responses/bindings',{method:'POST',body:{requestId:randomUUID(),constituentId:donor.id,constituentVersion:donor.version,listId,memberId:member.id,reason:'Verify existing primary member',readOnlyConfirmed:true}});assert.equal(bindingResponse.status,201,bindingResponse.text);const binding=bindingResponse.json.binding;
 const tables=['mailchimp_contact_sync_intents','mailchimp_contact_sync_history','mailchimp_contact_sync_suppressions','mailchimp_contact_sync_dispositions'];
 const snapshot=()=>Object.fromEntries(['records',...tables].map(n=>[n,app.locals.db.prepare('SELECT * FROM '+n+' ORDER BY rowid').all()]));
 const body=(overrides={})=>({requestId:randomUUID(),constituentId:donor.id,constituentVersion:donor.version,bindingId:binding.id,bindingVersion:binding.version,reason:'Reviewed approved text fields on existing member',confirmed:true,...overrides});
 const prepare=(payload=body())=>request('/mailchimp-contact-sync/intents',{method:'POST',body:payload});
 const action=(intent,name='execute',overrides={})=>request('/mailchimp-contact-sync/intents/'+intent.id+'/'+name,{method:'POST',body:{version:intent.version,reason:'Explicit reviewed '+name,confirmed:true,...overrides}});
 const detail=id=>request('/mailchimp-contact-sync/intents/'+id);
 return {dir,dbPath,tenantId,initialAdmin,mfaKey,readonly,adapter,donor,fund,gift,binding,member,members,calls,sessions,tables,snapshot,body,prepare,action,detail,request,create,close,open,get db(){return app.locals.db;},get service(){return app.locals.mailchimpContactSync;},get active(){return active;},set active(v){active=v;},set getHook(fn){getHook=fn;},set patchHook(fn){patchHook=fn;}};
}
const okIntent=r=>{assert.equal(r.status,201,r.text);return r.json.intent;};
const patchCount=f=>f.calls.filter(c=>c.method==='PATCH').length;

const close=(f,intent,overrides={},options={})=>f.request('/mailchimp-contact-sync/intents/'+intent.id+'/close-without-write',{method:'POST',body:{version:intent.version,reason:'Runner stopped; retain review without any attempted provider write',confirmed:true,runnerStoppedConfirmed:true,...overrides},...options});

test('Ready review closes without provider calls, exact replay stays terminal, retains full original custody and permits a fresh logical review',async t=>{
 const f=await fixture(t),payload=f.body(),p=okIntent(await f.prepare(payload)),original=f.db.prepare('SELECT * FROM mailchimp_contact_sync_intents WHERE id=?').get(p.id),native=f.snapshot().records,calls=f.calls.length;assert.equal(p.closeAllowed,true);const closed=await close(f,p);assert.equal(closed.status,200,closed.text);assert.equal(closed.json.intent.status,'ClosedWithoutWrite');assert.equal(closed.json.intent.closeAllowed,false);assert.equal(closed.json.intent.changes,null);assert.equal(closed.json.intent.disposition.runnerStoppedConfirmed,true);assert.equal(f.calls.length,calls);assert.equal(patchCount(f),0);
 const saved=f.db.prepare('SELECT * FROM mailchimp_contact_sync_intents WHERE id=?').get(p.id);for(const field of ['request_id','request_json','request_digest','source_json','source_digest','binding_id','binding_digest','actor_id','actor_binding','actor_factor','payload_json','before_json','created_at'])assert.equal(saved[field],original[field]);assert.equal(saved.status,'ReviewRequired');assert.equal(saved.write_attempted,0);const replay=await f.prepare(payload);assert.equal(replay.status,201,replay.text);assert.equal(replay.json.intent.status,'ClosedWithoutWrite');assert.equal(replay.json.replayed,true);assert.equal(f.calls.length,calls);assert.equal((await f.action(closed.json.intent)).status,409);assert.equal((await f.action(closed.json.intent,'reconcile')).status,409);assert.equal((await close(f,closed.json.intent)).status,409);
 const fresh=okIntent(await f.prepare());assert.notEqual(fresh.id,p.id);assert.equal(fresh.status,'Ready');assert.deepEqual(f.snapshot().records,native);const detail=(await f.detail(p.id)).json;assert.equal(detail.history[0].action,'close_without_write');assert.equal(detail.disposition,undefined);assert.equal(detail.intent.disposition.status,'ClosedWithoutWrite');for(const sensitive of [f.donor.email,'intent_hash','actor_binding','source_json'])assert.ok(!JSON.stringify(detail).includes(sensitive));
 assert.throws(()=>f.db.prepare('UPDATE mailchimp_contact_sync_dispositions SET reason=?').run('Overwrite retained reason'));assert.throws(()=>f.db.prepare('DELETE FROM mailchimp_contact_sync_dispositions').run());assert.throws(()=>f.db.prepare('UPDATE mailchimp_contact_sync_intents SET status=? WHERE id=?').run('Ready',p.id));
});

test('fresh different administrator can govern stale source/preparer without authorizing stale PII, then new source binding is reviewed separately',async t=>{
 const f=await fixture(t),p=okIntent(await f.prepare());const user=await f.request('/users',{method:'POST',body:{name:'Independent governing admin',email:'govern.sync@example.test',role:'admin',password}});assert.equal(user.status,201,user.text);const login=await f.request('/auth/login',{method:'POST',session:null,body:{email:'govern.sync@example.test',password}});assert.equal(login.status,200,login.text);const governor={...login.json,cookie:login.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ')};
 f.db.prepare("UPDATE records SET data=json_set(data,'$.name','Corrected current contact','$.version',2) WHERE collection='constituents' AND id=?").run(f.donor.id);f.db.prepare('UPDATE users SET version=version+1 WHERE id=?').run(f.sessions.admin.user.id);const before=f.snapshot().records,calls=f.calls.length;assert.equal((await close(f,p)).status,401);const governed=await close(f,p,{}, {session:governor});assert.equal(governed.status,200,governed.text);assert.equal(governed.json.intent.sourceCurrent,false);assert.equal(governed.json.intent.changes,null);assert.equal(governed.json.intent.disposition.actorId,governor.user.id);assert.equal(f.calls.length,calls);assert.deepEqual(f.snapshot().records,before);
 f.sessions.admin=governor;const retired=await f.request('/marketing-responses/bindings/'+f.binding.id+'/retire',{method:'POST',body:{version:f.binding.version,reason:'Reverify corrected source'}});assert.equal(retired.status,200,retired.text);const bound=await f.request('/marketing-responses/bindings',{method:'POST',body:{requestId:randomUUID(),constituentId:f.donor.id,constituentVersion:2,listId,memberId:f.member.id,reason:'Current corrected contact independently approved',readOnlyConfirmed:true}});assert.equal(bound.status,201,bound.text);const next=okIntent(await f.prepare(f.body({constituentVersion:2,bindingId:bound.json.binding.id,bindingVersion:bound.json.binding.version})));assert.equal(next.status,'Ready');assert.equal(next.changes.merge_fields.CONTACT,'Corrected current contact');const history=await f.request('/mailchimp-contact-sync/intents?constituentId='+f.donor.id);assert.equal(history.json.intents.length,2);assert.ok(history.json.intents.some(x=>x.id===p.id&&x.status==='ClosedWithoutWrite'));assert.equal(patchCount(f),0);
});

test('Unknown before any PATCH and no-write ReviewRequired can close only with explicit stopped confirmation',async t=>{
 const f=await fixture(t),p=okIntent(await f.prepare());f.member.last_changed='2026-09-02T12:00:00+00:00';assert.equal((await f.action(p)).status,409);const unknown=(await f.detail(p.id)).json.intent;assert.equal(unknown.status,'Unknown');assert.equal(unknown.writeAttempted,false);assert.equal(unknown.closeAllowed,true);assert.equal((await close(f,unknown,{runnerStoppedConfirmed:false})).status,400);assert.equal((await f.prepare()).status,409);assert.equal((await close(f,unknown)).status,200);assert.equal(okIntent(await f.prepare()).status,'Ready');assert.equal(patchCount(f),0);
 const other=await fixture(t);other.member.status='pending';const q=okIntent(await other.prepare());let gets=0;other.getHook=async()=>{const m=structuredClone(other.member);if(++gets===2)m.status='transactional';return m;};const mismatch=await other.action(q);assert.equal(mismatch.status,200,mismatch.text);const review=mismatch.json.intent;assert.equal(review.status,'ReviewRequired');assert.equal(review.writeAttempted,false);assert.equal((await other.prepare()).status,409);assert.equal((await close(other,review)).status,200);assert.equal(patchCount(other),0);
});

test('attempted Unknown/ReviewRequired and in-flight Executing NoChange never close despite runner confirmation or stale source',async t=>{
 for(const applied of [false,true]){const f=await fixture(t),p=okIntent(await f.prepare());f.patchHook=async(id,payload)=>{if(!applied)throw Error('Uncertain remote transport');return {};};const attempted=await f.action(p);assert.ok([200,409].includes(attempted.status),attempted.text);const state=(await f.detail(p.id)).json.intent;assert.equal(state.writeAttempted,true);assert.equal(state.closeAllowed,false);assert.throws(()=>f.db.prepare('UPDATE mailchimp_contact_sync_intents SET write_attempted=0 WHERE id=?').run(p.id));const before=f.snapshot(),calls=f.calls.length;assert.equal((await close(f,state)).status,409);f.db.prepare("UPDATE records SET data=json_set(data,'$.notes','Changed source after attempted update') WHERE collection='constituents' AND id=?").run(f.donor.id);assert.equal((await close(f,state)).status,409);assert.equal(f.calls.length,calls);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM mailchimp_contact_sync_dispositions').get().n,0);assert.deepEqual(f.snapshot().mailchimp_contact_sync_intents,before.mailchimp_contact_sync_intents);assert.equal(patchCount(f),1);}
 const busy=await fixture(t);busy.member.status='pending';const p=okIntent(await busy.prepare());let release,entered;const gate=new Promise(r=>release=r),started=new Promise(r=>entered=r);busy.getHook=async()=>{entered();await gate;return structuredClone(busy.member);};const running=busy.action(p);await started;const pending=(await busy.detail(p.id)).json.intent;assert.equal(pending.status,'Executing');assert.equal(pending.writeAttempted,false);assert.equal(pending.closeAllowed,false);assert.equal((await close(busy,pending)).status,409);release();assert.equal((await running).status,200);assert.equal(patchCount(busy),0);
});

test('strict versions/confirmation/reason/CSRF, roles and suspended tenant deny disposition without changing retained reviews',async t=>{
 const f=await fixture(t),p=okIntent(await f.prepare()),before=f.snapshot();for(const override of [{version:p.version+1},{confirmed:false},{runnerStoppedConfirmed:false},{reason:' '},{unsafe:true}])assert.ok([400,409].includes((await close(f,p,override)).status));assert.equal((await close(f,p,{}, {csrf:false})).status,403);for(const role of ['staff','viewer','event-helper'])assert.equal((await close(f,p,{}, {session:f.sessions[role]})).status,403);f.active=false;assert.equal((await close(f,p)).status,503);f.active=true;assert.deepEqual(f.snapshot(),before);
});

test('disposition audit/row/source-authority and deferred COMMIT faults roll back closure and preserve the active guard',async t=>{
 for(const kind of ['audit','row','actor','commit']){const f=await fixture(t),p=okIntent(await f.prepare()),before=f.snapshot();if(kind==='audit')f.db.exec("CREATE TRIGGER close_fault BEFORE INSERT ON audit WHEN NEW.action='mailchimp_contact_sync_disposition' BEGIN SELECT RAISE(ABORT,'Synthetic disposition audit outage'); END");if(kind==='row')f.db.exec("CREATE TRIGGER close_fault AFTER INSERT ON audit WHEN NEW.action='mailchimp_contact_sync_close_without_write' BEGIN UPDATE mailchimp_contact_sync_intents SET version=version+1; END");if(kind==='actor')f.db.exec("CREATE TRIGGER close_fault AFTER INSERT ON audit WHEN NEW.action='mailchimp_contact_sync_disposition' BEGIN UPDATE users SET role='viewer' WHERE id=NEW.actor; END");if(kind==='commit')f.db.exec("CREATE TABLE close_commit_fault(owner_id TEXT REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED); CREATE TRIGGER close_fault AFTER INSERT ON mailchimp_contact_sync_dispositions BEGIN INSERT INTO close_commit_fault VALUES('missing-owner'); END");const r=await close(f,p);assert.ok([401,409,500,503].includes(r.status),kind+': '+r.text);assert.deepEqual(f.snapshot(),before);assert.equal((await f.prepare()).status,409);f.db.exec('DROP TRIGGER close_fault');assert.equal((await close(f,p)).status,200);assert.equal(patchCount(f),0);}
});

test('constituent-filtered history preserves old bindings and stable cursor pages; foreign cursor or corrupted disposition cannot bypass protection',async t=>{
 const f=await fixture(t),ids=[];for(let n=0;n<3;n++){const p=okIntent(await f.prepare());ids.push(p.id);assert.equal((await close(f,p)).status,200);}
 const current=okIntent(await f.prepare());ids.push(current.id);let after,seen=[];do{const r=await f.request('/mailchimp-contact-sync/intents?limit=1&constituentId='+f.donor.id+(after?'&after='+after:''));assert.equal(r.status,200,r.text);seen.push(...r.json.intents.map(x=>x.id));after=r.json.nextCursor;}while(after);assert.equal(new Set(seen).size,4);assert.deepEqual([...seen].sort(),ids.sort());assert.equal((await f.request('/mailchimp-contact-sync/intents?constituentId=other&after='+current.id)).status,400);assert.equal((await f.request('/mailchimp-contact-sync/intents?constituentId='+encodeURIComponent('x'.repeat(101)))).status,400);
 // Native immutable ledger guards remain; an operator corruption fixture deliberately removes one guard.
 assert.equal((await close(f,current)).status,200);f.db.exec('DROP TRIGGER mailchimp_contact_sync_dispositions_no_update');f.db.prepare("UPDATE mailchimp_contact_sync_dispositions SET intent_hash=? WHERE intent_id=?").run('0'.repeat(64),current.id);const calls=f.calls.length;assert.equal((await f.detail(current.id)).status,503);assert.equal((await f.prepare()).status,503);assert.equal(f.calls.length,calls);assert.equal(patchCount(f),0);
});

test('restart and encrypted NEW-path recovery retain immutable no-write disposition, cannot replay/rearm old review, and preserve native income',async t=>{
 const f=await fixture(t),payload=f.body(),p=okIntent(await f.prepare(payload));assert.equal((await close(f,p)).status,200);const before=f.snapshot(),calls=f.calls.length;await f.close();await f.open();const closed=(await f.detail(p.id)).json.intent;assert.equal(closed.status,'ClosedWithoutWrite');assert.equal((await f.prepare(payload)).json.intent.status,'ClosedWithoutWrite');assert.equal(f.calls.length,calls);assert.deepEqual(f.snapshot(),before);
 const encryptionKey=randomBytes(32).toString('base64'),archivePath=join(f.dir,'disposition.wbackup'),destinationPath=join(f.dir,'restored.sqlite'),backup=await backupWorkspace({db:f.db,outputPath:archivePath,tenantId:f.tenantId,encryptionKey});assert.equal(backup.tables.find(x=>x.name==='mailchimp_contact_sync_dispositions').count,1);await f.close();await restoreWorkspace({archivePath,destinationPath,expectedTenantId:f.tenantId,encryptionKey});await f.open(destinationPath);const restored=(await f.detail(p.id)).json.intent;assert.equal(restored.status,'ClosedWithoutWrite');assert.equal(restored.sourceCurrent,false);assert.equal(restored.closeAllowed,false);assert.equal((await f.action(restored)).status,409);assert.equal((await f.prepare(payload)).status,409);assert.equal(f.calls.length,calls);assert.deepEqual(f.snapshot(),before);assert.equal(patchCount(f),0);
});
