import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';

function harness(){let index=0,state=[],effects=[],keys=[],cleanups=[];const hooks={...React,useState(initial){const i=index++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return [state[i],value=>state[i]=typeof value==='function'?value(state[i]):value];},useRef(initial){return state[index++]??=({current:initial});},useEffect(effect,deps){const i=index++;if(!keys[i]||!deps||deps.some((d,j)=>d!==keys[i][j])){keys[i]=deps;effects.push(()=>{cleanups[i]?.();cleanups[i]=effect();});}}};const module={exports:{}},require=id=>id==='react'?hooks:new Proxy({},{get:()=>()=>null});new Function('React','require','module','exports',transformSync(readFileSync(new URL('../src/features/MailchimpContactSync.jsx',import.meta.url),'utf8'),{loader:'jsx',format:'cjs'}).code)(React,require,module,module.exports);const render=props=>{index=0;const tree=module.exports.default(props),pending=effects;effects=[];pending.forEach(effect=>effect());return tree;};render.unmount=()=>cleanups.forEach(cleanup=>cleanup?.());return render;}
function find(tree,predicate){if(!tree||typeof tree!=='object')return null;if(predicate(tree))return tree;for(const child of React.Children.toArray(tree.props?.children)){const result=find(child,predicate);if(result)return result;}return null;}
const text=e=>React.Children.toArray(e.props?.children).filter(c=>typeof c==='string').join(''),button=(tree,label)=>find(tree,e=>e.type==='button'&&text(e)===label),field=tree=>find(tree,e=>e.type==='textarea'),confirm=tree=>find(tree,e=>e.type==='input'&&e.props.type==='checkbox').props.onChange({target:{checked:true}}),flush=async()=>{for(let i=0;i<24;i++)await Promise.resolve();},html=tree=>renderToStaticMarkup(tree);
const person={id:'native-person',version:3,name:'Synthetic current contact',email:'synthetic@example.test'},binding={id:'native-binding',version:2,status:'Current',sourceCurrent:true,constituentId:person.id,constituentVersion:person.version,listId:'list123'},provider={enabled:true,mode:'TEST_ONLY',access:'EXISTING_MEMBER_UPDATE',productionReady:false},scope='TEST ONLY. Existing-member fields and unsubscribe review; no contact creation or campaign sending.';
const intent=extra=>({id:'retained-intent',requestId:'00000000-0000-4000-8000-000000000001',version:1,status:'Ready',constituentId:person.id,bindingId:binding.id,bindingVersion:binding.version,operation:'UpdateFields',changes:{merge_fields:{FNAME:'Synthetic'}},providerStatus:'subscribed',sourceCurrent:true,writeAttempted:false,suppressed:false,mode:'TEST_ONLY',scope,...extra});
const detail=i=>({intent:i,history:[{id:'saved-history',version:i.version,action:'Prepare',status:i.status,reason:'Retained native review reason',at:'2026-09-13T12:00:00.000Z'}]});
async function ready({status=provider,intents=[],custom,...extra}={}){const calls=[],dirty=[],render=harness(),props={user:{id:'admin',role:'admin'},binding,person,onDirty:value=>dirty.push(value),api:async(path,options)=>{calls.push([path,options]);if(custom)return custom(path,options);if(path.endsWith('/status'))return status;if(path.includes('/intents?'))return {intents,nextCursor:null};if(options)return {intent:intent()};return detail(intents[0]||intent());},...extra};render(props);await flush();return {calls,dirty,render,props};}
function input(s,reason='Reviewed current contact fields'){field(s.render(s.props)).props.onChange({target:{value:reason}});confirm(s.render(s.props));}
async function open(s,id='retained-intent'){await find(s.render(s.props),e=>e.type==='button'&&text(e).includes(id)).props.onClick();await flush();return s.render(s.props);}
const posts=s=>s.calls.filter(([,options])=>options?.method==='POST');

test('prepare requires explicit review, pins source versions/request UUID and duplicate concurrent activation posts once',async()=>{
 const s=await ready();let tree=s.render(s.props);assert.equal(button(tree,'Prepare reviewed contact update').props.disabled,true);field(tree).props.onChange({target:{value:'  Reviewed current contact fields  '}});tree=s.render(s.props);assert.equal(button(tree,'Prepare reviewed contact update').props.disabled,true);confirm(tree);tree=s.render(s.props);assert.equal(button(tree,'Prepare reviewed contact update').props.disabled,false);await Promise.all([button(tree,'Prepare reviewed contact update').props.onClick(),button(tree,'Prepare reviewed contact update').props.onClick()]);await flush();assert.equal(posts(s).length,1);const payload=posts(s)[0][1].body;assert.match(payload.requestId,/^[a-f0-9-]{36}$/);assert.deepEqual(payload,{requestId:payload.requestId,constituentId:person.id,constituentVersion:3,bindingId:binding.id,bindingVersion:2,reason:'Reviewed current contact fields',confirmed:true});tree=s.render(s.props);assert.match(html(tree),/Exact reviewed provider fields/);assert.equal(button(tree,'Apply reviewed contact update once').props.disabled,true);assert.equal(posts(s).some(([path])=>path.endsWith('/execute')),false);
});

test('loaded intent action uses its current status/version and requires a fresh reason/confirmation',async()=>{
 const s=await ready({intents:[intent({version:7})],custom:async(path,options)=>path.endsWith('/status')?provider:path.includes('/intents?')?{intents:[intent({version:7})],nextCursor:null}:options?{intent:intent({version:8,status:'Reconciled',writeAttempted:true})}:detail(intent({version:7}))});let tree=await open(s);assert.equal(field(tree).props.disabled,false);assert.equal(button(tree,'Apply reviewed contact update once').props.disabled,true);input(s,'Inspected exact retained provider changes');tree=s.render(s.props);assert.equal(button(tree,'Apply reviewed contact update once').props.disabled,false);await button(tree,'Apply reviewed contact update once').props.onClick();await flush();assert.deepEqual(posts(s)[0],[`/mailchimp-contact-sync/intents/retained-intent/execute`,{method:'POST',body:{version:7,reason:'Inspected exact retained provider changes',confirmed:true}}]);tree=s.render(s.props);assert.equal(button(tree,'Apply reviewed contact update once'),null);assert.equal(button(tree,'Read back uncertain update'),null);assert.match(html(tree),/Reconciled/);assert.equal(posts(s).length,1);
});

test('changed binding/source authority and terminal intent statuses block mutation controls',async()=>{
 for(const source of [{binding:{...binding,sourceCurrent:false}},{binding:{...binding,status:'ReviewRequired'}},{binding:{...binding,constituentVersion:4}},{person:{...person,version:4}},{blocked:true}]){const s=await ready(source);assert.equal(button(s.render(s.props),'Prepare reviewed contact update').props.disabled,true);input(s);await button(s.render(s.props),'Prepare reviewed contact update').props.onClick();assert.equal(posts(s).length,0);}
 const unavailable=await ready({intents:[intent({sourceCurrent:false,changes:null})]});let tree=await open(unavailable);assert.match(html(tree),/Changed — review required/);assert.equal(button(tree,'Apply reviewed contact update once').props.disabled,true);assert.equal(find(tree,e=>e.type==='input'&&e.props.type==='checkbox').props.disabled,true);
 for(const status of ['Reconciled','Unknown','Executing','ReviewRequired']){const s=await ready({intents:[intent({status})]});tree=await open(s);assert.equal(button(tree,'Apply reviewed contact update once'),null);if(status!=='Reconciled')assert.ok(button(tree,'Read back uncertain update'));}
});

test('uncertain execute never repeats a write and requires saved-history reload then explicit read-back reconciliation request',async()=>{
 let saved=intent(),lost=false;const s=await ready({custom:async(path,options)=>{if(path.endsWith('/status'))return provider;if(path.includes('/intents?'))return {intents:[saved],nextCursor:null};if(options){if(path.endsWith('/execute')){saved=intent({version:3,status:'Unknown',writeAttempted:true});lost=true;throw new Error('Connection ended after provider request');}assert.ok(path.endsWith('/reconcile'));saved=intent({version:4,status:'Reconciled',writeAttempted:true});return {intent:saved};}return detail(saved);}});await open(s);input(s);await button(s.render(s.props),'Apply reviewed contact update once').props.onClick();await flush();let tree=s.render(s.props);assert.equal(lost,true);assert.match(html(tree),/Completion is uncertain/);assert.equal(button(tree,'Apply reviewed contact update once').props.disabled,true);assert.equal(field(tree).props.disabled,true);assert.equal(posts(s).length,1);await flush();assert.equal(posts(s).length,1);await button(tree,'Reload contact intents').props.onClick();await flush();tree=s.render(s.props);assert.doesNotMatch(html(tree),/Completion is uncertain/);assert.match(html(tree),/Retained native review reason/);assert.equal(button(tree,'Apply reviewed contact update once'),null);assert.equal(button(tree,'Read back uncertain update').props.disabled,true);input(s,'Read back the retained uncertain request only');await button(s.render(s.props),'Read back uncertain update').props.onClick();await flush();assert.equal(posts(s).filter(([path])=>path.endsWith('/execute')).length,1);const reconciliation=posts(s).find(([path])=>path.endsWith('/reconcile'));assert.deepEqual(reconciliation[1].body,{version:3,reason:'Read back the retained uncertain request only',confirmed:true});assert.match(html(s.render(s.props)),/Reconciled/);
});

test('uncertain prepare retains request identity and cannot prepare anew until the matching retained intent is inspected',async()=>{
 let saved=null;const s=await ready({custom:async(path,options)=>{if(path.endsWith('/status'))return provider;if(path.includes('/intents?'))return {intents:saved?[saved]:[],nextCursor:null};if(options){saved=intent({requestId:options.body.requestId});throw new Error('Prepare result unreadable');}return detail(saved);}});input(s);await button(s.render(s.props),'Prepare reviewed contact update').props.onClick();await flush();let tree=s.render(s.props);assert.match(html(tree),/Completion is uncertain/);assert.equal(button(tree,'Prepare reviewed contact update').props.disabled,true);assert.equal(posts(s).length,1);await button(tree,'Reload contact intents').props.onClick();await flush();tree=s.render(s.props);assert.equal(button(tree,'Prepare reviewed contact update'),null);assert.ok(button(tree,'Apply reviewed contact update once'));assert.equal(s.calls.filter(([path])=>path==='/mailchimp-contact-sync/intents/retained-intent').length,1);assert.equal(posts(s).length,1);
});

test('failed retained-history reload does not clear uncertainty or enable another outbound action',async()=>{
 let failed=false;const s=await ready({custom:async(path,options)=>{if(path.endsWith('/status'))return provider;if(path.includes('/intents?')){if(failed)throw new Error('Retained history unavailable');return {intents:[intent()],nextCursor:null};}if(options){failed=true;throw new Error('Unconfirmed update');}return detail(intent());}});await open(s);input(s);await button(s.render(s.props),'Apply reviewed contact update once').props.onClick();await button(s.render(s.props),'Reload contact intents').props.onClick();await flush();const tree=s.render(s.props);assert.match(html(tree),/Retained history unavailable/);assert.match(html(tree),/Completion is uncertain/);assert.equal(button(tree,'Apply reviewed contact update once').props.disabled,true);assert.equal(posts(s).length,1);
});

test('pending old account/API/source reads cannot replace new context or publish after unmount',async()=>{
 for(const change of ['account','api','source','binding']){let resolve;const s=await ready({intents:[intent()],custom:async path=>path.endsWith('/status')?provider:path.includes('/intents?')?{intents:[intent()],nextCursor:null}:new Promise(r=>resolve=r)});const pending=find(s.render(s.props),e=>e.type==='button'&&text(e).includes('retained-intent')).props.onClick();if(change==='account')s.props.user={id:'another-admin',role:'admin'};if(change==='api')s.props.api=async path=>path.endsWith('/status')?provider:{intents:[],nextCursor:null};if(change==='source')s.props.person={...person,version:4};if(change==='binding')s.props.binding={...binding,version:3};s.render(s.props);await flush();resolve(detail(intent({changes:{merge_fields:{FNAME:'STALE_PRIVATE_RESPONSE'}}})));await pending;await flush();assert.doesNotMatch(html(s.render(s.props)),/STALE_PRIVATE_RESPONSE/);assert.equal(posts(s).length,0);}
 let resolve;const s=await ready({intents:[intent()],custom:async path=>path.endsWith('/status')?provider:path.includes('/intents?')?{intents:[intent()],nextCursor:null}:new Promise(r=>resolve=r)});const pending=find(s.render(s.props),e=>e.type==='button'&&text(e).includes('retained-intent')).props.onClick();s.render.unmount();resolve(detail(intent({changes:{merge_fields:{FNAME:'UNMOUNTED_RESPONSE'}}})));await pending;assert.doesNotMatch(html(s.render(s.props)),/UNMOUNTED_RESPONSE/);assert.equal(posts(s).length,0);
});

test('equivalent parent source objects preserve review without generating new provider actions',async()=>{
 const s=await ready();input(s);s.props.binding=JSON.parse(JSON.stringify(binding));s.props.person=JSON.parse(JSON.stringify(person));const tree=s.render(s.props);assert.equal(button(tree,'Prepare reviewed contact update').props.disabled,false);assert.equal(field(tree).props.value,'Reviewed current contact fields');assert.equal(posts(s).length,0);assert.equal(s.calls.filter(([path])=>path.endsWith('/status')).length,1);
});

test('disabled and nonadministrator contexts cannot prepare or execute provider actions',async()=>{
 const disabled=await ready({status:{enabled:false,mode:'Disabled',access:'EXISTING_MEMBER_UPDATE',productionReady:false},intents:[intent()]});let tree=await open(disabled);assert.match(html(tree),/Outbound contact synchronization is disabled/);assert.equal(button(tree,'Apply reviewed contact update once').props.disabled,true);input(disabled);await button(disabled.render(disabled.props),'Apply reviewed contact update once').props.onClick();assert.equal(posts(disabled).length,0);
 for(const role of ['staff','viewer','event-helper']){const s=await ready({user:{id:role,role}});assert.deepEqual(s.calls,[]);tree=s.render(s.props);const prepare=button(tree,'Prepare reviewed contact update');if(prepare){assert.equal(prepare.props.disabled,true);await prepare.props.onClick();}assert.equal(posts(s).length,0);}
});

test('same-version different source identity is fenced and current binding identity must agree with the selected native source',async()=>{
 const mismatch=await ready({person:{...person,id:'different-person'}});assert.equal(button(mismatch.render(mismatch.props),'Prepare reviewed contact update').props.disabled,true);input(mismatch);await button(mismatch.render(mismatch.props),'Prepare reviewed contact update').props.onClick();assert.equal(posts(mismatch).length,0);
 let resolve;const s=await ready({intents:[intent()],custom:async path=>path.endsWith('/status')?provider:path.includes('/intents?')?{intents:[intent()],nextCursor:null}:new Promise(r=>resolve=r)});const pending=find(s.render(s.props),e=>e.type==='button'&&text(e).includes('retained-intent')).props.onClick();s.props.person={...person,id:'different-person'};s.render(s.props);resolve(detail(intent({changes:{merge_fields:{FNAME:'WRONG_SOURCE_RESPONSE'}}})));await pending;assert.doesNotMatch(html(s.render(s.props)),/WRONG_SOURCE_RESPONSE/);
});


test('cached exact changes are hidden immediately when API identity, role or same-version binding status changes',async()=>{
 for(const change of ['api','role','status']){const s=await ready({intents:[intent({changes:{merge_fields:{FNAME:'PRIVATE_CACHED_CONTACT'}}})]});await open(s);input(s);assert.match(html(s.render(s.props)),/PRIVATE_CACHED_CONTACT/);if(change==='api')s.props.api=async path=>path.endsWith('/status')?provider:{intents:[],nextCursor:null};if(change==='role')s.props.user={id:'admin',role:'staff'};if(change==='status')s.props.binding={...binding,status:'ReviewRequired'};const first=s.render(s.props);assert.doesNotMatch(html(first),/PRIVATE_CACHED_CONTACT/);assert.equal(button(first,'Apply reviewed contact update once'),null);await flush();assert.equal(posts(s).length,0);}
});

test('stale no-write intent closure requires stopped-runner confirmation and fresh action review without publishing original fields',async()=>{
 const stale=intent({status:'Unknown',sourceCurrent:false,changes:null,writeAttempted:false,closeAllowed:true,bindingId:'earlier-binding',version:9});
 const s=await ready({binding:{...binding,sourceCurrent:false,status:'ReviewRequired'},custom:async(path,options)=>path.endsWith('/status')?provider:path.includes('/intents?')?{intents:[stale],nextCursor:null}:options?{intent:intent({...stale,status:'ClosedWithoutWrite',closeAllowed:false,version:10})}:detail(stale)});
 let tree=await open(s);assert.equal(field(tree).props.disabled,false);assert.equal(button(tree,'Apply reviewed contact update once'),null);input(s,'Verified abandoned no-write preparation');
 tree=s.render(s.props);assert.equal(button(tree,'Close without provider write').props.disabled,true);
 const runner=find(tree,e=>e.type==='input'&&e.props.type==='checkbox'&&e.props.checked===false);runner.props.onChange({target:{checked:true}});tree=s.render(s.props);assert.equal(button(tree,'Close without provider write').props.disabled,true);confirm(tree);tree=s.render(s.props);assert.equal(button(tree,'Close without provider write').props.disabled,false);
 await button(tree,'Close without provider write').props.onClick();await flush();assert.deepEqual(posts(s)[0],[`/mailchimp-contact-sync/intents/retained-intent/close-without-write`,{method:'POST',body:{version:9,reason:'Verified abandoned no-write preparation',confirmed:true,runnerStoppedConfirmed:true}}]);
 tree=s.render(s.props);assert.match(html(tree),/ClosedWithoutWrite/);assert.equal(button(tree,'Close without provider write'),null);assert.equal(button(tree,'Apply reviewed contact update once'),null);assert.equal(button(tree,'Read back uncertain update'),null);assert.doesNotMatch(html(tree),/Exact reviewed provider fields/);assert.equal(s.dirty.at(-1),false);
 assert.ok(s.calls.find(([path])=>path.includes('constituentId=native-person')));
});
test('attempted and executing intents cannot show no-write closure even when source authority has changed',async()=>{
 for(const state of [{status:'Unknown',writeAttempted:true},{status:'Executing',writeAttempted:false},{status:'ReviewRequired',writeAttempted:true}]){
 const stale=intent({...state,closeAllowed:true,sourceCurrent:false,changes:null});const s=await ready({intents:[stale]});const tree=await open(s);assert.equal(button(tree,'Close without provider write'),null);assert.equal(button(tree,'Read back uncertain update').props.disabled,true);assert.equal(posts(s).length,0);
 }
});
test('terminal completion can start a fresh reviewed update without repeating its old action',async()=>{
 const s=await ready({intents:[intent({status:'ClosedWithoutWrite',closeAllowed:false,changes:null})]});let tree=await open(s);assert.ok(button(tree,'Review another update'));await button(tree,'Review another update').props.onClick();tree=s.render(s.props);assert.ok(button(tree,'Prepare reviewed contact update'));assert.equal(button(tree,'Prepare reviewed contact update').props.disabled,true);assert.equal(posts(s).length,0);input(s,'New explicit current-source preparation');await button(s.render(s.props),'Prepare reviewed contact update').props.onClick();assert.equal(posts(s).length,1);assert.equal(posts(s)[0][0],'/mailchimp-contact-sync/intents');
});
test('runner-specific closure confirmation cannot carry into another intent or a reloaded revision',async()=>{
 const a=intent({id:'review-A',closeAllowed:true}),b=intent({id:'review-B',closeAllowed:true,version:5});
 const s=await ready({custom:async path=>path.endsWith('/status')?provider:path.includes('/intents?')?{intents:[a,b],nextCursor:null}:detail(path.endsWith('review-A')?a:b)});
 await open(s,'review-A');let tree=s.render(s.props);const runner=t=>find(find(t,e=>e.type==='label'&&text(e)==='I verified the original update runner has stopped.'),e=>e.type==='input');runner(tree).props.onChange({target:{checked:true}});input(s,'Exact no-write review A');tree=s.render(s.props);assert.equal(button(tree,'Close without provider write').props.disabled,false);
 await open(s,'review-B');assert.equal(field(s.render(s.props)).props.value,'');input(s,'Exact no-write review B');tree=s.render(s.props);assert.equal(runner(tree).props.checked,false);assert.equal(button(tree,'Close without provider write').props.disabled,true);runner(tree).props.onChange({target:{checked:true}});confirm(s.render(s.props));assert.equal(button(s.render(s.props),'Close without provider write').props.disabled,false);
 await button(s.render(s.props),'Reload contact intents').props.onClick();tree=s.render(s.props);assert.equal(runner(tree).props.checked,false);assert.equal(button(tree,'Close without provider write').props.disabled,true);assert.equal(posts(s).length,0);
});
