import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import * as lib from '../src/lib.js';
function harness(){let index=0,state=[],effects=[],keys=[],cleanups=[];const mock={...React,useState(initial){const i=index++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return[state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){return state[index++]??=({current:initial});},useEffect(effect,deps){const i=index++;if(!keys[i]||!deps||deps.some((d,j)=>d!==keys[i][j])){keys[i]=deps;effects.push(()=>{cleanups[i]?.();cleanups[i]=effect();});}}};const module={exports:{}},require=id=>id==='react'?mock:id==='./MailchimpContactSync.jsx'?{__esModule:true,default:()=>null}:id.includes('lib')?lib:new Proxy({},{get:()=>()=>null});new Function('React','require','module','exports',transformSync(readFileSync(new URL('../src/features/MarketingConnections.jsx',import.meta.url),'utf8'),{loader:'jsx',format:'cjs'}).code)(React,require,module,module.exports);const render=props=>{index=0;const tree=module.exports.default(props),pending=effects;effects=[];pending.forEach(e=>e());return tree;};render.unmount=()=>cleanups.forEach(c=>c?.());return render;}
function find(tree,p){if(!tree||typeof tree!=='object')return null;if(p(tree))return tree;for(const c of React.Children.toArray(tree.props?.children)){const result=find(c,p);if(result)return result;}return null;}
const text=e=>React.Children.toArray(e.props.children).filter(c=>typeof c==='string').join(''),button=(tree,label)=>find(tree,e=>e.type==='button'&&text(e)===label),field=(tree,label)=>find(find(tree,e=>e.type==='label'&&text(e)===label),e=>['input','select','textarea'].includes(e.type)),flush=async()=>{for(let i=0;i<16;i++)await Promise.resolve();};
const person={id:'p1',version:3,name:'Existing constituent',email:'synthetic@example.test',preference:'Email'},memberId='0123456789abcdef0123456789abcdef',provider={enabled:true,ready:true,mode:'TEST_ONLY',access:'READ_ONLY',listId:'list123'};
const binding={id:'b1',requestId:'00000000-0000-4000-8000-000000000001',version:2,status:'Current',constituentId:'p1',constituentName:person.name,constituentVersion:3,listId:'list123',memberId,providerStatus:'subscribed',sourceCurrent:true,marketingEligible:true,eligibilityReason:'CURRENT_SUBSCRIBED',suppressed:false,suppressionReasons:[],providerChangedAt:'2026-09-12T12:00:00Z',createdAt:'2026-09-13T12:00:00Z',updatedAt:'2026-09-13T12:00:00Z'};
const identity={constituentId:'p1',constituentVersion:3,constituentName:person.name,listId:'list123',memberId,statement:'Computed from current primary email; provider member is not yet verified.'};
const saved=(b=binding)=>({binding:b,history:[{id:'h1',version:b.version,action:'Observed',status:b.status,reason:'Reviewed read-only observation',actor:'admin1',at:b.updatedAt}],historyCount:1,historyLimit:100,events:[],eventCount:0});
const campaign={id:'r1',campaignId:'mc1',version:1,listId:'list123',providerSentAt:'2026-09-12T12:00:00Z',emailsSent:100,hardBounces:2,softBounces:3,unsubscribed:4,uniqueOpens:20,uniqueClicks:10,observedAt:'2026-09-13T12:00:00Z',sourceCurrent:true,mode:'TEST_ONLY'};
async function ready({list=[],detail=saved(),status=provider,reports=[],api:custom,...extra}={}){const calls=[],render=harness(),props={user:{id:'admin1',role:'admin'},data:{constituents:[person,{id:'merged',version:1,name:'Merged',email:'merged@example.test',mergedInto:'p1'},{id:'noemail',version:1,name:'No email'}]},onDirty:()=>{},api:async(path,o)=>{calls.push([path,o]);return custom?custom(path,o):o?path.endsWith('/observe')?{campaign}:{binding}:path.endsWith('/status')?status:path.includes('member-identity?')?identity:path.includes('bindings?')?{bindings:list,nextCursor:null}:path.endsWith('/campaigns')?{campaigns:reports}:detail;},...extra};render(props);await flush();return{calls,render,props,tree:render(props)};}
const html=s=>renderToStaticMarkup(s.render(s.props)),submit=tree=>find(tree,e=>e.type==='form').props.onSubmit({preventDefault(){}});
function confirm(tree){find(tree,e=>e.type==='input'&&e.props.type==='checkbox').props.onChange({target:{checked:true}});}
async function fill(s){field(s.render(s.props),'Existing constituent').props.onChange({target:{value:'p1'}});await button(s.render(s.props),'Resolve member identity').props.onClick();field(s.render(s.props),'Member observation reason').props.onChange({target:{value:'Reviewed existing primary email and audience'}});button(s.render(s.props),'Review member observation').props.onClick();confirm(s.render(s.props));}
async function select(s){await button(s.render(s.props),'Existing constituent').props.onClick();await flush();return s.render(s.props);}
function action(s,label){button(s.render(s.props),label).props.onClick();field(s.render(s.props),'Reason for binding action').props.onChange({target:{value:'Reviewed retained binding and operation'}});confirm(s.render(s.props));}

test('existing native identity is resolved without a provider call then reviewed create pins list/member/source and request UUID',async()=>{const s=await ready();assert.ok(button(s.tree,'Review member observation').props.disabled);await fill(s);assert.match(html(s),/provider member is not yet verified/);assert.equal(s.calls.filter(([,o])=>o).length,0);assert.equal(field(s.render(s.props),'Existing Mailchimp member identifier').props.readOnly,true);for(const id of ['merged','noemail'])assert.equal(find(s.render(s.props),e=>e.type==='option'&&e.props.value===id),null);const tree=s.render(s.props);await Promise.all([submit(tree),submit(tree)]);const posts=s.calls.filter(([,o])=>o);assert.equal(posts.length,1);assert.match(posts[0][1].body.requestId,/^[a-f0-9-]{36}$/);assert.deepEqual(posts[0][1].body,{requestId:posts[0][1].body.requestId,constituentId:'p1',constituentVersion:3,listId:'list123',memberId,reason:'Reviewed existing primary email and audience',readOnlyConfirmed:true});assert.match(html(s),/No provider message, subscription change or delivery action/);});

test('disabled provider retains saved status/history but makes no synthetic observation or clearing action',async()=>{const s=await ready({status:{enabled:false,ready:false,mode:'Disabled',access:'READ_ONLY',listId:null},list:[binding]});assert.match(html(s),/Provider observation is unavailable/);assert.ok(find(s.tree,e=>e.type==='fieldset').props.disabled);await select(s);assert.ok(button(s.render(s.props),'Review member refresh').props.disabled);assert.ok(button(s.render(s.props),'Retire binding with reason').props.disabled);assert.match(html(s),/Reviewed read-only observation/);assert.equal(s.calls.filter(([,o])=>o).length,0);});

test('nonadministrators request nothing and cached private history vanishes immediately on role downgrade',async()=>{for(const role of ['staff','viewer','event-helper']){const s=await ready({user:{id:'u1',role}});assert.deepEqual(s.calls,[]);assert.match(html(s),/require administrator access/);}const s=await ready({list:[binding]});await select(s);s.props.user={id:'admin1',role:'staff'};assert.doesNotMatch(renderToStaticMarkup(s.render(s.props)),/Reviewed read-only observation|Existing constituent/);});

test('provider subscription and sticky marketing exclusion remain separate from current all-channel native preference',async()=>{const b={...binding,marketingEligible:false,suppressed:true,suppressionReasons:['Unsubscribed'],eligibilityReason:'RETAINED_SUPPRESSION'},s=await ready({list:[b],detail:saved(b)});await select(s);assert.match(html(s),/subscribed/);assert.match(html(s),/Excluded · RETAINED_SUPPRESSION/);assert.match(html(s),/Suppressed · Unsubscribed/);assert.match(html(s),/Native preference now/);assert.match(html(s),/>Email</);assert.match(html(s),/Later subscribed observations do not clear it/);assert.doesNotMatch(html(s),/Resubscribe member|Clear suppression|Send campaign/);assert.equal(s.calls.filter(([,o])=>o).length,0);});

test('fresh identical source arrays retain reviewed proof; changed primary-email version invalidates identity and submission',async()=>{const s=await ready();await fill(s);s.props.data=JSON.parse(JSON.stringify(s.props.data));assert.equal(button(s.render(s.props),'Observe reviewed member').props.disabled,false);s.props.data={constituents:[{...person,version:4,email:'changed@example.test'}]};s.render(s.props);assert.ok(button(s.render(s.props),'Observe reviewed member').props.disabled);assert.match(html(s),/Source records changed/);assert.ok(button(s.render(s.props),'Review member observation').props.disabled);assert.equal(s.calls.filter(([,o])=>o).length,0);});

test('member refresh is explicit/reasoned/versioned and unchanged provider observation is not invented as another version',async()=>{const s=await ready({list:[binding]});await select(s);action(s,'Review member refresh');assert.match(html(s),/unchanged observation does not create another version/);await submit(s.render(s.props));const post=s.calls.find(([,o])=>o);assert.equal(post[0],'/marketing-responses/bindings/b1/refresh');assert.deepEqual(post[1].body,{version:2,reason:'Reviewed retained binding and operation',readOnlyConfirmed:true});assert.match(html(s),/binding v2/);});

test('retiring preserves suppression/history and does not delete or resubscribe a provider member',async()=>{let b=binding;const s=await ready({list:[binding],api:async(path,o)=>{if(o){b={...binding,status:'Retired',version:3};return{binding:b};}return path.endsWith('/status')?provider:path.includes('bindings?')?{bindings:[b],nextCursor:null}:path.endsWith('/campaigns')?{campaigns:[]}:saved(b);}});await select(s);action(s,'Retire binding with reason');assert.match(html(s),/It does not remove a provider member/);await submit(s.render(s.props));const post=s.calls.find(([,o])=>o);assert.deepEqual(post[1].body,{version:2,reason:'Reviewed retained binding and operation'});assert.equal(button(s.render(s.props),'Review member refresh'),null);assert.equal(button(s.render(s.props),'Retire binding with reason'),null);assert.match(html(s),/Retired · binding v3/);});

test('uncertain write retains request ID/inputs and even stale submit cannot replay before explicit history inspection',async()=>{const s=await ready({api:async(path,o)=>{if(o)throw new Error('Connection ended after observation');return path.endsWith('/status')?provider:path.includes('member-identity?')?identity:path.includes('bindings?')?{bindings:[binding],nextCursor:null}:path.endsWith('/campaigns')?{campaigns:[]}:saved();}});await fill(s);const original=s.render(s.props);await submit(original);const id=s.calls.find(([,o])=>o)[1].body.requestId;assert.ok(html(s).includes(id));assert.match(html(s),/response was not confirmed/);assert.equal(field(s.render(s.props),'Member observation reason').props.value,'Reviewed existing primary email and audience');await submit(original);assert.equal(s.calls.filter(([,o])=>o).length,1);await button(s.render(s.props),'Discard inputs and inspect saved history').props.onClick();await flush();assert.equal(s.calls.filter(([,o])=>o).length,1);});

test('known saved observation with failed history fetch displays unknown action/callback counts and no false empty history',async()=>{let committed=false;const s=await ready({api:async(path,o)=>{if(o){committed=true;return{binding};}return path.endsWith('/status')?provider:path.includes('member-identity?')?identity:path.includes('bindings?')?{bindings:[],nextCursor:null}:path.endsWith('/campaigns')?{campaigns:[]}:(()=>{if(committed)throw new Error('History unavailable');return saved();})();}});await fill(s);await submit(s.render(s.props));assert.match(html(s),/action was saved, but retained history could not refresh/);assert.match(html(s),/Reload saved history to verify action counts/);assert.match(html(s),/Callback count awaiting refresh/);assert.doesNotMatch(html(s),/0 of 0|No history actions returned/);assert.ok(button(s.render(s.props),'Review member refresh').props.disabled);});

test('campaign observations replace saved versions without summed totals and keep source/provider chronology explicit',async()=>{const s=await ready({list:[binding],reports:[campaign],api:async(path,o)=>{if(o)return{campaign:{...campaign,version:2,emailsSent:105}};return path.endsWith('/status')?provider:path.includes('bindings?')?{bindings:[binding],nextCursor:null}:path.endsWith('/campaigns')?{campaigns:[{...campaign,version:2,emailsSent:105}]}:saved();}});await select(s);field(s.render(s.props),'Existing Mailchimp campaign identifier').props.onChange({target:{value:'mc1'}});field(s.render(s.props),'Campaign report reason').props.onChange({target:{value:'Reviewed existing newsletter report'}});button(s.render(s.props),'Review campaign report read').props.onClick();confirm(s.render(s.props));const tree=s.render(s.props);await submit(tree);const post=s.calls.find(([,o])=>o);assert.equal(post[0],'/marketing-responses/campaigns/observe');assert.deepEqual(post[1].body,{requestId:post[1].body.requestId,campaignId:'mc1',reason:'Reviewed existing newsletter report',readOnlyConfirmed:true});assert.match(html(s),/>105</);assert.doesNotMatch(html(s),/>205</);assert.match(html(s),/Provider sent at|Observed at/);assert.match(html(s),/not human replies|do not prove a person read or replied/);});

test('late native identity result is discarded after source selection changes and privacy denial clears retained observations',async()=>{let resolve;const s=await ready({api:async path=>path.endsWith('/status')?provider:path.includes('bindings?')?{bindings:[],nextCursor:null}:path.endsWith('/campaigns')?{campaigns:[]}:new Promise(r=>resolve=r)});field(s.tree,'Existing constituent').props.onChange({target:{value:'p1'}});const pending=button(s.render(s.props),'Resolve member identity').props.onClick();field(s.render(s.props),'Existing constituent').props.onChange({target:{value:''}});resolve(identity);await pending;assert.equal(field(s.render(s.props),'Existing Mailchimp member identifier').props.value,'');let deny=false;const q=await ready({list:[binding],reports:[campaign],api:async path=>{if(deny)throw Object.assign(new Error('Access revoked'),{status:403});return path.endsWith('/status')?provider:path.includes('bindings?')?{bindings:[binding],nextCursor:null}:path.endsWith('/campaigns')?{campaigns:[campaign]}:saved();}});await select(q);deny=true;await button(q.render(q.props),'Refresh saved history').props.onClick();assert.doesNotMatch(html(q),/Existing constituent|Reviewed read-only observation|mc1/);});

test('workspace refresh protects dirty inputs and initial failed reads are unknown rather than falsely empty',async()=>{let reloads=0;const s=await ready({onRefreshSources:()=>reloads++});button(s.tree,'Refresh workspace sources').props.onClick();assert.equal(reloads,1);field(s.render(s.props),'Campaign report reason').props.onChange({target:{value:'Unsaved review'}});const tree=s.render(s.props);assert.ok(button(tree,'Refresh workspace sources').props.disabled);button(tree,'Refresh workspace sources').props.onClick();assert.equal(reloads,1);const q=await ready({api:async()=>{throw new Error('Database unavailable');}});assert.match(html(q),/Saved bindings are unavailable/);assert.match(html(q),/Saved campaign observation counts are unavailable/);assert.doesNotMatch(html(q),/No member bindings returned|No campaign observations returned/);});


test('member and campaign confirmation cannot overlap, and canceling campaign inputs restores clean navigation',async()=>{const s=await ready();field(s.tree,'Campaign report reason').props.onChange({target:{value:'Review newsletter statistics'}});const tree=s.render(s.props),memberForm=find(tree,e=>e.type==='form'&&find(e,n=>n.type==='select'));assert.ok(find(memberForm,e=>e.type==='fieldset').props.disabled);assert.ok(button(tree,'Review another member').props.disabled);button(tree,'Cancel campaign report inputs').props.onClick();assert.equal(button(s.render(s.props),'Review another member').props.disabled,false);await fill(s);const reportForm=find(s.render(s.props),e=>e.type==='form'&&find(e,n=>n.type==='input'&&n.props.maxLength===100));assert.ok(find(reportForm,e=>e.type==='fieldset').props.disabled);assert.equal(s.calls.filter(([,o])=>o).length,0);});

test('callback source time and unspecified timezone stay separate from native received time without raw payload disclosure',async()=>{const detail=saved();detail.events=[{id:'e1',type:'unsubscribe',sourceFiredAt:'2026-09-11 07:15:00',sourceTimezone:'Unspecified',receivedAt:'2026-09-13T12:00:00Z',providerStatus:'unsubscribed',suppressionReason:'Unsubscribed'}];detail.eventCount=1;const s=await ready({list:[binding],detail});await select(s);assert.match(html(s),/Provider source time: 2026-09-11 07:15:00 · timezone Unspecified/);assert.match(html(s),/Native received at: 2026-09-13 12:00:00.000 UTC/);assert.match(html(s),/1 retained callback events/);assert.doesNotMatch(html(s),/webhookSecret|HMAC|rawBody/);});


test('pending reservation offers explicit member refresh; terminal ReviewRequired cannot refresh or retire',async()=>{const pending={...binding,status:'Pending',version:1,providerStatus:null,marketingEligible:false},s=await ready({list:[pending],detail:saved(pending)});await select(s);assert.equal(button(s.render(s.props),'Review member refresh').props.disabled,false);assert.equal(s.calls.filter(([,o])=>o).length,0);action(s,'Review member refresh');await submit(s.render(s.props));assert.equal(s.calls.find(([,o])=>o)[1].body.version,1);const closed={...binding,status:'ReviewRequired',sourceCurrent:false},q=await ready({list:[closed],detail:saved(closed)});await select(q);assert.equal(button(q.render(q.props),'Review member refresh'),null);assert.equal(button(q.render(q.props),'Retire binding with reason'),null);assert.match(html(q),/This binding is closed for source review/);});
