import test from 'node:test';import assert from 'node:assert/strict';import {once} from 'node:events';import {randomUUID,createHash,createHmac} from 'node:crypto';import {createApp} from '../server/app.js';
const sources=['marketingBindings','marketingResponseEvents','marketingCampaignObservations'];
async function fixture(t){
 const password='SyntheticMarketingReports!2026',initialAdmin={name:'Synthetic marketing administrator',email:'marketing.reports@example.test',password},sessions={},email='synthetic.donor@example.test',memberId=createHash('md5').update(email).digest('hex'),listId='list123',webhookSecret='synthetic-marketing-report-signing-secret',state={status:'subscribed',emailsSent:100};
 const adapter={async getMember(id){assert.equal(id,memberId);return{id,email_address:email,list_id:listId,status:state.status,last_changed:'2026-09-01T12:00:00+00:00',unique_email_id:'opaque123'};},async getCampaignReport(id){return{id,list_id:listId,send_time:'2026-09-01T12:00:00+00:00',emails_sent:state.emailsSent,bounces:{hard_bounces:2,soft_bounces:1},unsubscribed:3,opens:{unique_opens:40},clicks:{unique_subscriber_clicks:5}};}};
 const app=createApp({seed:false,tenantId:randomUUID(),initialAdmin,mfaKey:'',workflowWorker:false,reminderWorker:false,marketingResponses:{mode:'TEST_ONLY',access:'READ_ONLY',serverPrefix:'us1',apiKey:'a'.repeat(32)+'-us1',listId,webhookSecret,adapter}}),server=app.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{await new Promise(r=>server.close(r));app.locals.close();});const base='http://127.0.0.1:'+server.address().port;
 async function request(path,{method='GET',body,role='admin',headers={}}={}){const s=sessions[role],r=await fetch(base+'/api'+path,{method,headers:{...(body!==undefined?{'Content-Type':'application/json'}:{}),...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrfToken}:{}),...headers},...(body!==undefined?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});const text=await r.text();let json;try{json=JSON.parse(text);}catch{}return{status:r.status,json,text,headers:r.headers};}
 async function login(address){const r=await request('/auth/login',{method:'POST',role:'anonymous',body:{email:address,password}});assert.equal(r.status,200,r.text);return{...r.json,cookie:r.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ')};}
 sessions.admin=await login(initialAdmin.email);for(const role of ['staff','viewer']){assert.equal((await request('/users',{method:'POST',body:{name:'Synthetic marketing '+role,email:role+'.marketing.reports@example.test',password,role}})).status,201);sessions[role]=await login(role+'.marketing.reports@example.test');}
 const donor=await request('/records/constituents',{method:'POST',body:{name:'Synthetic newsletter donor',email,type:'Individual',preference:'Email'}});assert.equal(donor.status,201,donor.text);
 const created=await request('/marketing-responses/bindings',{method:'POST',body:{requestId:randomUUID(),constituentId:donor.json.record.id,constituentVersion:donor.json.record.version,listId,memberId,reason:'Synthetic primary email and audience reviewed; read only.',readOnlyConfirmed:true}});assert.equal(created.status,201,created.text);const binding=created.json.binding;
 const report=(entity,columns,role='admin')=>request('/custom-reports/run',{method:'POST',role,body:{name:'Synthetic provider observations',entity,columns,filters:[],groupBy:[],aggregates:[],includeVoided:false}});
 async function observe(requestId=randomUUID()){const r=await request('/marketing-responses/campaigns/observe',{method:'POST',body:{requestId,campaignId:'providerCampaign123',reason:'Synthetic provider aggregate source observation; no send.',readOnlyConfirmed:true}});assert.equal(r.status,201,r.text);return r.json.campaign;}
 async function unsubscribe(){const raw=new URLSearchParams({type:'unsubscribe',fired_at:'2026-09-13 12:00:00','data[id]':'opaque123','data[list_id]':listId,'data[email]':email,'data[action]':'unsub'}).toString(),timestamp=Math.floor(Date.now()/1000),sig=createHmac('sha256',webhookSecret).update(timestamp+'.'+raw).digest('hex');const r=await request('/marketing-responses/webhook',{method:'POST',role:'anonymous',body:raw,headers:{'Content-Type':'application/x-www-form-urlencoded','X-Mailchimp-Signature':'t='+timestamp+',v1='+sig}});assert.equal(r.status,200,r.text);}
 const native=()=>app.locals.db.prepare('SELECT collection,id,data FROM records ORDER BY collection,id').all();return{app,request,report,observe,unsubscribe,state,binding,donor:donor.json.record,native,sessions,password,initialAdmin,login};
}
test('marketing report catalogs and execution allow current administrators only and exclude provider addresses and bindings',async t=>{
 const f=await fixture(t);await f.observe();await f.unsubscribe();const catalog=await f.request('/custom-reports/catalog');assert.equal(catalog.status,200,catalog.text);
 for(const source of sources){const e=catalog.json.entities.find(e=>e.id===source);assert.equal(e?.requiredRole,'admin',source);assert.match(e.description,/not a consent grant/);assert.equal((await f.report(source,['id'])).status,200);for(const role of ['staff','viewer']){assert.equal((await f.report(source,['id'],role)).status,403);const c=await f.request('/custom-reports/catalog',{role});assert.equal(c.json.entities.some(e=>e.id===source),false);}for(const key of ['email','memberId','listId','callbackMemberId','payload','signature','requestId','apiKey','configDigest'])assert.equal((await f.report(source,[key])).status,400,source+':'+key);}
});
test('marketing snapshots replace repeated provider totals and suppression reporting does not modify native donor or finances',async t=>{
 const f=await fixture(t),native=f.native(),first=await f.observe();await f.observe();let r=await f.report('marketingCampaignObservations',['id','emailsSent','unsubscribed','uniqueOpens']);assert.equal(r.status,200,r.text);assert.equal(r.json.rows.length,1);assert.deepEqual(r.json.rows[0].slice(1),[100,3,40]);
 f.state.emailsSent=110;await f.observe();r=await f.report('marketingCampaignObservations',['campaignId','emailsSent','revision']);assert.equal(r.status,200,r.text);assert.equal(r.json.rows.length,1);assert.deepEqual(r.json.rows[0],['providerCampaign123',110,2]);assert.equal(first.version,1);
 await f.unsubscribe();const current=await f.report('marketingBindings',['id','marketingEligible','suppressed','constituentId']);assert.equal(current.status,200,current.text);assert.deepEqual(current.json.rows,[[f.binding.id,false,true,f.donor.id]]);assert.deepEqual(current.json.recordReferences,[{collection:'constituents',id:f.donor.id}]);const events=await f.report('marketingResponseEvents',['type','sourceFiredAt','sourceTimezone']);assert.equal(events.status,200,events.text);assert.ok(events.json.rows.some(r=>r[0]==='unsubscribe'&&r[1]==='2026-09-13 12:00:00'&&r[2]==='Unspecified'));assert.deepEqual(f.native(),native);
});
test('retained scheduled provider-statistics report remains private after its owner loses administrator authority',async t=>{
 const f=await fixture(t);await f.observe();const native=f.native(),saved=await f.request('/custom-reports',{method:'POST',body:{name:'Private provider snapshot',entity:'marketingCampaignObservations',columns:['id','emailsSent']}});assert.equal(saved.status,201,saved.text);const startAt=new Date(Date.now()+30000).toISOString(),schedule=await f.request('/report-schedules',{method:'POST',body:{name:'Private marketing source review',reportId:saved.json.report.id,cadence:'Daily',startAt}});assert.equal(schedule.status,201,schedule.text);assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1).produced,1);const d=f.app.locals.db.prepare('SELECT id,result FROM report_deliveries WHERE schedule_id=?').get(schedule.json.schedule.id);assert.equal(JSON.parse(d.result).requiredRole,'admin');for(const role of ['staff','viewer'])assert.equal((await f.request('/report-deliveries/'+d.id,{role})).status,403);
 assert.equal((await f.request('/users',{method:'POST',body:{name:'Second synthetic marketing administrator',email:'second.marketing.reports@example.test',password:f.password,role:'admin'}})).status,201);assert.equal((await f.request('/users/'+f.sessions.admin.user.id,{method:'PATCH',body:{version:1,role:'staff',active:true}})).status,200);f.sessions.admin=await f.login(f.initialAdmin.email);assert.equal((await f.request('/report-deliveries/'+d.id)).status,403);assert.equal((await f.request('/custom-reports/'+saved.json.report.id+'/run')).status,403);assert.deepEqual(f.native(),native);
});
