import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID, randomBytes, createHash, createHmac } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { Worker } from 'node:worker_threads';
import { createApp } from '../server/app.js';
import { totp } from '../server/mfa.js';
import { backupWorkspace, restoreWorkspace } from '../server/backup.js';

// Mailchimp official webhook guide: HMAC-SHA256 over timestamp+'.'+untouched raw form bytes.
// https://mailchimp.com/developer/marketing/guides/sync-audience-data-webhooks/
const password='SyntheticMarketingAcceptance!2026',secret='SyntheticMailchimpWebhookSecretNoProviderCalls2026',listId='list123';
const memberId=email=>createHash('md5').update(email.toLowerCase()).digest('hex');
async function fixture(t){
 const dir=await mkdtemp(join(tmpdir(),'wimblo-marketing-integrity-')),dbPath=join(dir,'workspace.sqlite'),tenantId=randomUUID(),initialAdmin={name:'Synthetic marketing administrator',email:'marketing.admin@example.test',password},sessions={},mfaKey=randomBytes(32).toString('base64'),members=new Map(),reports=new Map(),calls=[];let app,server,base,active=true,memberHook=null,reportHook=null;
 const adapter={async getMember(id){calls.push({type:'member',id});if(memberHook)return memberHook(id);assert.ok(members.has(id),'Only simulated approved members may be read');return structuredClone(members.get(id));},async getCampaignReport(id){calls.push({type:'report',id});if(reportHook)return reportHook(id);assert.ok(reports.has(id),'Only simulated existing campaign reports may be read');return structuredClone(reports.get(id));}};
 const config={mode:'TEST_ONLY',access:'READ_ONLY',serverPrefix:'us1',apiKey:'a'.repeat(32)+'-us1',listId,webhookSecret:secret,adapter};
 async function close(){if(server)await new Promise(resolve=>server.close(resolve));server=null;app?.locals.close();app=null;}
 async function request(path,{method='GET',body,session=sessions.admin,csrf=true,raw,signature}={}){const r=await fetch(base+'/api'+path,{method,headers:{...(body===undefined&&raw===undefined?{}:{'Content-Type':raw===undefined?'application/json':'application/x-www-form-urlencoded'}),...(session?{Cookie:session.cookie,...(csrf?{'X-CSRF-Token':session.csrfToken}:{})}:{}),...(signature?{'X-Mailchimp-Signature':signature}:{})},...(raw!==undefined?{body:raw}:body===undefined?{}:{body:JSON.stringify(body)})});const text=await r.text();let json;try{json=JSON.parse(text);}catch{json=null;}return{status:r.status,json,text,headers:r.headers};}
 async function login(email=initialAdmin.email){const r=await request('/auth/login',{method:'POST',session:null,body:{email,password}});assert.equal(r.status,200,r.text);return{...r.json,cookie:r.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ')};}
 async function open(path=dbPath){app=createApp({dbPath:path,seed:false,tenantId,initialAdmin,mfaKey,isTenantActive:()=>active,reminderWorker:false,workflowWorker:false,marketingResponses:config,marketingResponsesClock:Date.now});server=app.listen(0,'127.0.0.1');await once(server,'listening');base='http://127.0.0.1:'+server.address().port;sessions.admin=await login();}
 await open();t.after(async()=>{await close();await rm(dir,{recursive:true,force:true});});
 for(const role of ['staff','viewer','event-helper']){const r=await request('/users',{method:'POST',body:{name:'Synthetic marketing '+role,email:role+'.marketing@example.test',role,password}});assert.equal(r.status,201,r.text);sessions[role]=await login(role+'.marketing@example.test');}
 async function create(collection,body){const r=await request('/records/'+collection,{method:'POST',body});assert.equal(r.status,201,r.text);return r.json.record;}
 const donor=await create('constituents',{name:'Actual marketing donor',type:'Individual',email:'actual.marketing@example.test',preference:'Email',contacts:[{name:'Different secondary contact',email:'secondary.marketing@example.test',role:'Contact'}]}),fund=await create('designations',{name:'Actual financial fund',accountCode:'MARK-100'}),gift=await create('gifts',{constituentId:donor.id,amount:10001,type:'Cash',method:'Check',date:'2026-09-01',giftKind:'One-time',allocations:[{designationId:fund.id,amount:10001}]});
 const nativeMember={id:memberId(donor.email),email_address:donor.email,list_id:listId,status:'subscribed',last_changed:'2026-09-01T12:00:00+00:00',unique_email_id:'opaque1234'};members.set(nativeMember.id,nativeMember);reports.set('campaign123',{id:'campaign123',list_id:listId,send_time:'2026-09-01T13:00:00+00:00',emails_sent:1000,bounces:{hard_bounces:5,soft_bounces:7},unsubscribed:3,opens:{unique_opens:400},clicks:{unique_subscriber_clicks:100}});
 const row=(collection,id)=>JSON.parse(app.locals.db.prepare('SELECT data FROM records WHERE collection=? AND id=?').get(collection,id).data);
 const tables=()=>app.locals.db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name LIKE 'marketing_%' ORDER BY name").all().map(x=>x.name);
 const snapshot=(audit=true)=>Object.fromEntries(['records',...tables(),...(audit?['audit']:[])].map(name=>[name,app.locals.db.prepare('SELECT * FROM '+name+' ORDER BY rowid').all()]));
 const financial=()=>Object.fromEntries(['records','receipt_preparations','receipt_issues','receipt_voids','correspondence_preparations','correspondence_finalizations','correspondence_fulfillments'].map(name=>[name,name==='records'?app.locals.db.prepare("SELECT * FROM records WHERE collection IN ('gifts','campaigns','pledges','grants','communications') ORDER BY rowid").all():app.locals.db.prepare('SELECT * FROM '+name+' ORDER BY rowid').all()]));
 const payload=(changes={})=>({requestId:randomUUID(),constituentId:donor.id,constituentVersion:row('constituents',donor.id).version,listId,memberId:nativeMember.id,reason:'Explicit reviewed current primary-email member binding',readOnlyConfirmed:true,...changes});
 async function binding(changes={}){const r=await request('/marketing-responses/bindings',{method:'POST',body:payload(changes)});assert.equal(r.status,201,r.text);return r.json.binding;}
 const detail=(id,session)=>request('/marketing-responses/bindings/'+id,{session});
 const refresh=(b,changes={})=>request('/marketing-responses/bindings/'+b.id+'/refresh',{method:'POST',body:{version:b.version,reason:'Read existing member state only',readOnlyConfirmed:true,...changes}});
 const observe=(changes={})=>request('/marketing-responses/campaigns/observe',{method:'POST',body:{requestId:randomUUID(),campaignId:'campaign123',reason:'Read existing aggregate report, not sending or cash',readOnlyConfirmed:true,...changes}});
 const form=(type='unsubscribe',changes={})=>new URLSearchParams({type,fired_at:'2026-09-13 14:40:00','data[id]':nativeMember.unique_email_id,'data[list_id]':listId,'data[email]':donor.email,...changes}).toString();
 const sign=(raw,{timestamp=Math.floor(Date.now()/1000),key=secret}={})=>'t='+timestamp+',v1='+createHmac('sha256',key).update(timestamp+'.').update(raw).digest('hex');
 const webhook=(raw=form(),options={})=>request('/marketing-responses/webhook',{method:'POST',session:null,raw,signature:sign(raw,options)});
 return{dir,dbPath,tenantId,initialAdmin,sessions,adapter,config,members,reports,calls,donor,fund,gift,nativeMember,row,tables,snapshot,financial,create,payload,binding,detail,refresh,observe,form,sign,webhook,request,login,open,close,get db(){return app.locals.db;},get app(){return app;},set active(v){active=v;},set memberHook(v){memberHook=v;},set reportHook(v){reportHook=v;},restart:async()=>{await close();await open();}};
}

test('provider subscribed status never overrides native Do not contact or changes financial identity/consent',async t=>{
 const f=await fixture(t);const changed=await f.request('/records/constituents/'+f.donor.id,{method:'PATCH',body:{version:1,preference:'Do not contact'}});assert.equal(changed.status,200,changed.text);const before=f.snapshot().records,finance=f.financial(),b=await f.binding();assert.equal(b.providerStatus,'subscribed');assert.equal(b.marketingEligible,false);assert.equal(f.row('constituents',f.donor.id).preference,'Do not contact');assert.deepEqual(f.snapshot().records,before);assert.deepEqual(f.financial(),finance);const text=JSON.stringify(b);assert.ok(!text.includes(f.donor.email));assert.ok(!text.includes(f.config.apiKey));assert.ok(!text.includes(secret));
});

test('retained unsubscribe/cleaned/delete suppression survives stale subscribed polls and leaves Print and native donor/gift untouched',async t=>{
 const f=await fixture(t),b=await f.binding(),before=f.snapshot().records,finance=f.financial();const a=await f.request('/audiences',{method:'POST',body:{name:'Native Print policy',filters:{segmentTokens:[],segmentMatch:'Any',types:[],preferences:[]}}});assert.equal(a.status,201,a.text);const audience=a.json.audience;
 for(const [type,fields]of [['unsubscribe',{}],['cleaned',{}],['unsubscribe',{'data[action]':'delete'}]]){const r=await f.webhook(f.form(type,fields));assert.equal(r.status,200,r.text);const current=(await f.detail(b.id)).json.binding;assert.equal(current.suppressed,true);assert.equal(current.marketingEligible,false);const poll=await f.refresh(current);assert.equal(poll.status,200,poll.text);assert.equal(poll.json.binding.providerStatus,'subscribed');assert.equal(poll.json.binding.suppressed,true);assert.equal(poll.json.binding.marketingEligible,false);assert.deepEqual(f.snapshot().records,before);assert.deepEqual(f.financial(),finance);}
 const print=await f.request('/audiences/'+audience.id+'/preview?version=1&channel=Print');assert.equal(print.status,200,print.text);assert.equal(print.json.eligibleCount,1);assert.equal(print.json.recipients[0].id,f.donor.id);assert.equal(f.row('constituents',f.donor.id).preference,'Email');assert.equal(f.row('gifts',f.gift.id).amount,10001);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM records WHERE collection='constituents'").get().n,1);
});

test('exact primary identity rejects duplicate primary email, secondary-only and provider/list/source mismatches',async t=>{
 const f=await fixture(t);const before=f.snapshot();for(const change of [{memberId:memberId(f.donor.contacts[0].email)},{listId:'foreign123'},{constituentVersion:99},{constituentId:randomUUID()}]){const r=await f.request('/marketing-responses/bindings',{method:'POST',body:f.payload(change)});assert.ok([400,404,409].includes(r.status),r.text);assert.deepEqual(f.snapshot(),before);}
 const duplicate=await f.create('constituents',{name:'Separate ambiguous primary profile',type:'Individual',email:f.donor.email.toUpperCase(),preference:'Email'}),dupBefore=f.snapshot();const ambiguity=await f.request('/marketing-responses/bindings',{method:'POST',body:f.payload()});assert.equal(ambiguity.status,409,ambiguity.text);assert.deepEqual(f.snapshot(),dupBefore);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM marketing_bindings').get().n,0);assert.notEqual(duplicate.id,f.donor.id);
});

test('read-only member/report operations default-deny staff/viewer/helpers and missing CSRF',async t=>{
 const f=await fixture(t),b=await f.binding(),before=f.snapshot();for(const role of ['staff','viewer','event-helper']){for(const path of ['/marketing-responses/status','/marketing-responses/bindings','/marketing-responses/bindings/'+b.id])assert.equal((await f.request(path,{session:f.sessions[role]})).status,403);for(const [path,body]of [['/marketing-responses/bindings',f.payload()],['/marketing-responses/bindings/'+b.id+'/refresh',{version:b.version,reason:'Unauthorized',readOnlyConfirmed:true}],['/marketing-responses/campaigns/observe',{requestId:randomUUID(),campaignId:'campaign123',reason:'Unauthorized',readOnlyConfirmed:true}]])assert.equal((await f.request(path,{method:'POST',body,session:f.sessions[role]})).status,403);}
 assert.equal((await f.request('/marketing-responses/bindings',{method:'POST',body:f.payload(),csrf:false})).status,403);assert.deepEqual(f.snapshot(),before);
});

test('official signed raw form rejects stale/tampered/duplicate/nested/foreign identity deliveries and bounded size; exact replay is once-only',async t=>{
 const f=await fixture(t),b=await f.binding(),before=f.snapshot();for(const options of [{key:'WrongSyntheticSigningSecretAtLeast32Characters'},{timestamp:Math.floor(Date.now()/1000)-3600},{timestamp:Math.floor(Date.now()/1000)+3600}]){const r=await f.webhook(f.form(),options);assert.equal(r.status,400,r.text);assert.deepEqual(f.snapshot(),before);}
 const raw=f.form(),tampered=await f.request('/marketing-responses/webhook',{method:'POST',session:null,raw:raw+'&data%5Bemail%5D=other%40example.test',signature:f.sign(raw)});assert.equal(tampered.status,400,tampered.text);assert.deepEqual(f.snapshot(),before);
 for(const bad of [raw+'&type=subscribe',raw+'&data%5Blist_id%5D=foreign123',raw+'&data%5Bunexpected%5D%5Bunsafe%5D=x',f.form('unsubscribe',{'data[list_id]':'foreign123'}),f.form('unsubscribe',{'data[id]':'foreign123'}),f.form('unsubscribe',{'data[email]':'foreign@example.test'})]){const r=await f.webhook(bad);assert.ok([400,404,409].includes(r.status),r.text);assert.deepEqual(f.snapshot(),before);}
 const tooLarge=await f.webhook(raw+'&padding='+'x'.repeat(270000));assert.equal(tooLarge.status,413,tooLarge.text);assert.deepEqual(f.snapshot(),before);const accepted=await f.webhook(raw);assert.equal(accepted.status,200,accepted.text);assert.equal((await f.detail(b.id)).json.binding.suppressed,true);const retained=f.snapshot();assert.equal((await f.webhook(raw)).status,200);assert.deepEqual(f.snapshot(),retained);const subscribed=await f.webhook(f.form('subscribe'));assert.equal(subscribed.status,200,subscribed.text);assert.equal((await f.detail(b.id)).json.binding.suppressed,true);assert.deepEqual(f.snapshot().records,before.records);
});

test('native source/account/tenant changes during async member retrieval cannot authorize a current binding',async t=>{
 const f=await fixture(t),finance=f.financial();f.memberHook=async()=>{f.db.prepare("UPDATE records SET data=json_set(data,'$.email','changed.during.read@example.test','$.version',2) WHERE collection='constituents' AND id=?").run(f.donor.id);return structuredClone(f.nativeMember);};const changed=await f.request('/marketing-responses/bindings',{method:'POST',body:f.payload()});assert.ok([400,409].includes(changed.status),changed.text);assert.equal(f.db.prepare("SELECT COUNT(*) n FROM marketing_bindings WHERE status='Current'").get().n,0);assert.deepEqual(f.financial(),finance);
 const suspended=await fixture(t);suspended.memberHook=async()=>{suspended.active=false;return structuredClone(suspended.nativeMember);};const denied=await suspended.request('/marketing-responses/bindings',{method:'POST',body:suspended.payload()});assert.ok([403,503].includes(denied.status),denied.text);assert.equal(suspended.db.prepare("SELECT COUNT(*) n FROM marketing_bindings WHERE status='Current'").get().n,0);suspended.active=true;
 const account=await fixture(t);account.memberHook=async()=>{account.db.prepare('UPDATE users SET version=version+1 WHERE id=?').run(account.sessions.admin.user.id);return structuredClone(account.nativeMember);};const stale=await account.request('/marketing-responses/bindings',{method:'POST',body:account.payload()});assert.ok([401,403,409].includes(stale.status),stale.text);assert.equal(account.db.prepare("SELECT COUNT(*) n FROM marketing_bindings WHERE status='Current'").get().n,0);
 const mfa=await fixture(t);mfa.memberHook=async()=>{const begin=await mfa.request('/auth/mfa/enroll',{method:'POST',body:{password}});assert.equal(begin.status,200,begin.text);const confirm=await mfa.request('/auth/mfa/confirm',{method:'POST',body:{code:totp(begin.json.secret)}});assert.equal(confirm.status,200,confirm.text);return structuredClone(mfa.nativeMember);};const factorChanged=await mfa.request('/marketing-responses/bindings',{method:'POST',body:mfa.payload()});assert.equal(factorChanged.status,401,factorChanged.text);assert.equal(mfa.db.prepare("SELECT COUNT(*) n FROM marketing_bindings WHERE status='Current'").get().n,0);
});

test('primary email correction invalidates retained member mapping and old provider callbacks cannot infer a new address or donor',async t=>{
 const f=await fixture(t),b=await f.binding(),finance=f.financial();const changed=await f.request('/records/constituents/'+f.donor.id,{method:'PATCH',body:{version:1,email:'corrected.marketing@example.test'}});assert.equal(changed.status,200,changed.text);const current=await f.detail(b.id);assert.equal(current.status,200,current.text);assert.equal(current.json.binding.sourceCurrent,false);assert.equal(current.json.binding.marketingEligible,false);const refreshed=await f.refresh(current.json.binding);assert.ok([400,409].includes(refreshed.status),refreshed.text);await f.webhook(f.form('subscribe'));const again=(await f.detail(b.id)).json.binding;assert.equal(again.marketingEligible,false);assert.equal(f.row('constituents',f.donor.id).email,'corrected.marketing@example.test');assert.deepEqual(f.financial(),finance);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM marketing_bindings').get().n,1);
});

test('retiring and rebinding the same primary donor/list identity cannot clear unsubscribe or removal tombstones',async t=>{
 const f=await fixture(t);for(const fields of [{},{'data[action]':'delete'}]){const b=await f.binding();assert.equal((await f.webhook(f.form('unsubscribe',fields))).status,200);const current=(await f.detail(b.id)).json.binding;const retired=await f.request('/marketing-responses/bindings/'+b.id+'/retire',{method:'POST',body:{version:current.version,reason:'Retained history must not be a consent reset'}});assert.equal(retired.status,200,retired.text);const before=f.financial(),suppressionCount=f.db.prepare('SELECT COUNT(*) n FROM marketing_suppressions').get().n;assert.ok(suppressionCount>0);const rebind=await f.request('/marketing-responses/bindings',{method:'POST',body:f.payload()});assert.ok([201,409].includes(rebind.status),rebind.text);if(rebind.status===201){assert.equal(rebind.json.binding.suppressed,true);assert.equal(rebind.json.binding.marketingEligible,false);const poll=await f.refresh(rebind.json.binding);assert.equal(poll.status,200,poll.text);assert.equal(poll.json.binding.marketingEligible,false);const next=(await f.detail(rebind.json.binding.id)).json.binding;const close=await f.request('/marketing-responses/bindings/'+next.id+'/retire',{method:'POST',body:{version:next.version,reason:'Keep denial evidence through another lifecycle'}});assert.equal(close.status,200,close.text);}assert.equal(f.db.prepare('SELECT COUNT(*) n FROM marketing_suppressions').get().n,suppressionCount);assert.deepEqual(f.financial(),before);if(rebind.status===409)break;}
});

test('aggregate campaign observations replace/version counts instead of adding repeated polls, and request drift is rejected',async t=>{
 const f=await fixture(t),finance=f.financial(),requestId=randomUUID(),first=await f.observe({requestId});assert.equal(first.status,201,first.text);assert.equal(first.json.campaign.version,1);assert.equal(first.json.campaign.emailsSent,1000);assert.equal(first.json.campaign.hardBounces,5);assert.equal(first.json.campaign.softBounces,7);assert.equal(first.json.campaign.unsubscribed,3);const before=f.snapshot();const replay=await f.observe({requestId});assert.equal(replay.status,201,replay.text);assert.equal(replay.json.campaign.id,first.json.campaign.id);assert.deepEqual(f.snapshot(),before);
 const same=await f.observe();assert.equal(same.status,201,same.text);assert.equal(same.json.unchanged,true);assert.equal(same.json.campaign.id,first.json.campaign.id);assert.equal(same.json.campaign.version,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM marketing_campaign_observations').get().n,1);
 f.reports.get('campaign123').bounces.hard_bounces=6;f.reports.get('campaign123').unsubscribed=4;const updated=await f.observe();assert.equal(updated.status,201,updated.text);assert.equal(updated.json.campaign.version,2);assert.equal(updated.json.campaign.hardBounces,6);assert.equal(updated.json.campaign.softBounces,7);assert.equal(updated.json.campaign.unsubscribed,4);const list=await f.request('/marketing-responses/campaigns');assert.equal(list.status,200,list.text);assert.equal(list.json.campaigns.length,1);assert.equal(list.json.campaigns[0].emailsSent,1000);assert.equal(list.json.campaigns[0].hardBounces,6);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM marketing_campaign_observations').get().n,2);assert.deepEqual(f.financial(),finance);const retained=f.snapshot();const drift=await f.observe({requestId,reason:'Altered original reviewed request'});assert.equal(drift.status,409,drift.text);assert.deepEqual(f.snapshot(),retained);
});

test('member/source/suppression persistence, audit and deferred COMMIT faults roll back current observation atomically',async t=>{
 const f=await fixture(t),b=await f.binding(),before=f.snapshot();f.members.get(f.nativeMember.id).status='cleaned';f.members.get(f.nativeMember.id).last_changed='2026-09-02T12:00:00+00:00';
 const faults=[
 "CREATE TRIGGER synthetic_marketing_fault AFTER INSERT ON marketing_member_observations BEGIN UPDATE marketing_bindings SET status='Retired' WHERE id=NEW.binding_id; END",
 "CREATE TRIGGER synthetic_marketing_fault AFTER INSERT ON marketing_member_observations BEGIN UPDATE records SET data=json_set(data,'$.name','Wrong native source after save') WHERE collection='constituents'; END",
 "CREATE TRIGGER synthetic_marketing_fault AFTER INSERT ON audit WHEN NEW.action='observe_marketing_member' BEGIN UPDATE marketing_bindings SET version=version+1; END",
 "CREATE TRIGGER synthetic_marketing_fault BEFORE INSERT ON audit WHEN NEW.action='observe_marketing_member' BEGIN SELECT RAISE(ABORT,'Synthetic marketing audit unavailable'); END"
 ];for(const sql of faults){f.db.exec(sql);const r=await f.refresh(b);assert.ok([409,500,503].includes(r.status),r.text);assert.deepEqual(f.snapshot(),before);f.db.exec('DROP TRIGGER synthetic_marketing_fault');}
 f.db.exec("CREATE TABLE synthetic_marketing_commit_fault(owner_id TEXT REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED); CREATE TRIGGER synthetic_marketing_fault AFTER INSERT ON marketing_member_observations BEGIN INSERT INTO synthetic_marketing_commit_fault VALUES('no-such-native-owner'); END");const commit=await f.refresh(b);assert.equal(commit.status,500,commit.text);assert.deepEqual(f.snapshot(),before);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM synthetic_marketing_commit_fault').get().n,0);f.db.exec('DROP TRIGGER synthetic_marketing_fault');const success=await f.refresh(b);assert.equal(success.status,200,success.text);assert.equal(success.json.binding.suppressed,true);assert.equal(success.json.binding.marketingEligible,false);
});

test('signed response audit/persisted-source faults leave no false suppression, event or history',async t=>{
 const f=await fixture(t),b=await f.binding(),before=f.snapshot();const faults=["CREATE TRIGGER synthetic_marketing_fault AFTER INSERT ON audit WHEN NEW.action='observe_marketing_response' BEGIN UPDATE marketing_bindings SET current_observation_id='no-such-observation'; END","CREATE TRIGGER synthetic_marketing_fault AFTER INSERT ON audit WHEN NEW.action='observe_marketing_response' BEGIN UPDATE records SET data=json_set(data,'$.preference','Do not contact') WHERE collection='constituents'; END","CREATE TRIGGER synthetic_marketing_fault BEFORE INSERT ON audit WHEN NEW.action='observe_marketing_response' BEGIN SELECT RAISE(ABORT,'Synthetic response audit unavailable'); END"];
 for(const sql of faults){f.db.exec(sql);const r=await f.webhook();assert.ok([409,500,503].includes(r.status),r.text);assert.deepEqual(f.snapshot(),before);f.db.exec('DROP TRIGGER synthetic_marketing_fault');}assert.equal((await f.webhook()).status,200);assert.equal((await f.detail(b.id)).json.binding.suppressed,true);
});

test('restart and encrypted new-path recovery retain eight ledgers and sticky denial while recovered Pending authority closes without provider reads',async t=>{
 const f=await fixture(t),b=await f.binding();assert.equal((await f.webhook()).status,200);assert.equal((await f.observe()).status,201);const ordinary=f.snapshot();await f.restart();assert.deepEqual(f.snapshot(),ordinary);assert.equal((await f.detail(b.id)).json.binding.suppressed,true);
 const other=await f.create('constituents',{name:'Separate pending source',type:'Individual',email:'pending.marketing@example.test',preference:'Email'}),otherMember={...structuredClone(f.nativeMember),id:memberId(other.email),email_address:other.email,unique_email_id:'pending456'};let release;const gate=new Promise(resolve=>{release=resolve;});f.memberHook=async id=>{assert.equal(id,otherMember.id);await gate;return structuredClone(otherMember);};const inFlight=f.request('/marketing-responses/bindings',{method:'POST',body:f.payload({constituentId:other.id,constituentVersion:1,memberId:otherMember.id})});
 for(let n=0;n<100&&f.db.prepare("SELECT COUNT(*) n FROM marketing_bindings WHERE status='Pending'").get().n!==1;n++)await new Promise(resolve=>setTimeout(resolve,5));assert.equal(f.db.prepare("SELECT COUNT(*) n FROM marketing_bindings WHERE status='Pending'").get().n,1);const before=f.snapshot(),finance=f.financial();assert.deepEqual(f.tables(),['marketing_bindings','marketing_campaign_observations','marketing_campaign_requests','marketing_history','marketing_member_observations','marketing_requests','marketing_response_events','marketing_suppressions']);assert.equal(before.marketing_bindings.length,2);assert.equal(before.marketing_requests.length,2);assert.equal(before.marketing_member_observations.length,1);assert.equal(before.marketing_response_events.length,1);assert.equal(before.marketing_suppressions.length,1);
 const archivePath=join(f.dir,'marketing.backup'),destinationPath=join(f.dir,'restored-workspace.sqlite'),encryptionKey=randomBytes(32).toString('base64'),oldSession=f.sessions.admin;await backupWorkspace({db:f.db,outputPath:archivePath,tenantId:f.tenantId,encryptionKey});release();assert.equal((await inFlight).status,201);f.memberHook=null;const restored=await restoreWorkspace({archivePath,destinationPath,expectedTenantId:f.tenantId,encryptionKey});assert.ok(restored.cleared.sessions>0);const copy=new DatabaseSync(destinationPath);try{for(const[table,rows]of Object.entries(before))assert.deepEqual(copy.prepare('SELECT * FROM '+table+' ORDER BY rowid').all(),rows,table);assert.equal(copy.prepare('SELECT COUNT(*) n FROM sessions').get().n,0);assert.throws(()=>copy.exec('DELETE FROM marketing_suppressions'),/retained|immutable/);}finally{copy.close();}
 await f.close();const readCount=f.calls.length;await f.open(destinationPath);assert.equal((await f.detail(b.id,oldSession)).status,401);const current=(await f.detail(b.id)).json.binding;assert.equal(current.status,'ReviewRequired');assert.equal(current.suppressed,true);assert.equal(current.marketingEligible,false);const pendingId=before.marketing_bindings.find(x=>x.status==='Pending').id,pending=(await f.detail(pendingId)).json.binding;assert.equal(pending.status,'ReviewRequired');assert.equal(pending.marketingEligible,false);assert.equal((await f.refresh(pending)).status,409);assert.equal(f.calls.length,readCount);assert.deepEqual(f.financial(),finance);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM marketing_suppressions').get().n,1);
});

test('slow older campaign read cannot overwrite a newer completed observation, while later explicit corrections can reduce counts',async t=>{
 const f=await fixture(t),first=await f.observe();assert.equal(first.status,201,first.text);let release,started;const gate=new Promise(resolve=>{release=resolve;}),entered=new Promise(resolve=>{started=resolve;});let reads=0;const old=structuredClone(f.reports.get('campaign123')),newer={...structuredClone(old),emails_sent:1100,bounces:{hard_bounces:6,soft_bounces:8},opens:{unique_opens:410}};f.reportHook=async()=>{if(++reads===1){started();await gate;return old;}return newer;};
 const delayed=f.observe();await entered;let fast;try{fast=await f.observe();}finally{release();}assert.equal(fast.status,201,fast.text);assert.equal(fast.json.campaign.version,2);assert.equal(fast.json.campaign.emailsSent,1100);const stale=await delayed;assert.equal(stale.status,409,stale.text);const list=await f.request('/marketing-responses/campaigns');assert.equal(list.json.campaigns[0].emailsSent,1100);assert.equal(list.json.campaigns[0].version,2);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM marketing_campaign_observations').get().n,2);
 f.reportHook=null;f.reports.set('campaign123',{...newer,emails_sent:1050});const correction=await f.observe();assert.equal(correction.status,201,correction.text);assert.equal(correction.json.campaign.version,3);assert.equal(correction.json.campaign.emailsSent,1050);assert.equal((await f.request('/marketing-responses/campaigns')).json.campaigns[0].emailsSent,1050);
});

test('two independent SQLite callback writers preserve one signed response, one sticky suppression and one history revision',async t=>{
 const f=await fixture(t),b=await f.binding(),finance=f.financial(),raw=f.form(),signature=f.sign(raw);const {adapter,...configuration}=f.config;
 const code=`const {parentPort,workerData}=require('node:worker_threads');(async()=>{const {createApp}=await import(workerData.appUrl);const app=createApp({dbPath:workerData.dbPath,seed:false,tenantId:workerData.tenantId,initialAdmin:workerData.initialAdmin,workflowWorker:false,reminderWorker:false,marketingResponses:{...workerData.configuration,adapter:{getMember:async()=>{throw Error('Unexpected external member read');},getCampaignReport:async()=>{throw Error('Unexpected external report read');}}}});app.locals.db.exec('PRAGMA busy_timeout=5000');const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const url='http://127.0.0.1:'+server.address().port+'/api/marketing-responses/webhook';parentPort.postMessage({ready:true});parentPort.once('message',async()=>{try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','X-Mailchimp-Signature':workerData.signature},body:workerData.raw}),result={status:r.status,json:await r.json()};await new Promise(resolve=>server.close(resolve));app.locals.close();parentPort.postMessage({result});}catch(error){server.close();app.locals.close();parentPort.postMessage({error:error.message});}});})().catch(error=>parentPort.postMessage({error:error.message}));`;
 async function start(){const w=new Worker(code,{eval:true,workerData:{appUrl:new URL('../server/app.js',import.meta.url).href,dbPath:f.dbPath,tenantId:f.tenantId,initialAdmin:f.initialAdmin,configuration,raw,signature}});t.after(()=>w.terminate());await new Promise((resolve,reject)=>{w.once('error',reject);w.once('message',m=>m.ready?resolve():reject(Error(m.error)));});return w;}
 const workers=[await start(),await start()],responses=workers.map(w=>new Promise((resolve,reject)=>{w.once('error',reject);w.once('message',m=>m.error?reject(Error(m.error)):resolve(m.result));}));for(const w of workers)w.postMessage('deliver');const results=await Promise.all(responses);assert.deepEqual(results.map(x=>x.status),[200,200],JSON.stringify(results));assert.deepEqual(results.map(x=>x.json.replayed).sort(),[false,true]);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM marketing_response_events').get().n,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM marketing_suppressions').get().n,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM marketing_history WHERE binding_id=?').get(b.id).n,3);assert.equal((await f.detail(b.id)).json.binding.version,3);assert.equal((await f.detail(b.id)).json.binding.marketingEligible,false);assert.deepEqual(f.financial(),finance);
});
