import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
// Isolated component state harness, not a replacement for browser integration.
function component(file,dependencies={}){let index=0,effects=[],state=[];const mock={...React,lazy:()=>()=>null,useState(initial){const i=index++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return [state[i],value=>state[i]=typeof value==='function'?value(state[i]):value];},useRef(initial){const i=index++;return state[i]??=({current:initial});},useCallback(fn){index++;return fn;},useEffect(fn){index++;effects.push(fn);}};const icon=()=>null,require=id=>id==='react'?mock:id==='lucide-react'?new Proxy({},{get:()=>icon}):dependencies[id]||{__esModule:true,default:()=>null};const module={exports:{}};new Function('require','module','exports',transformSync(readFileSync(new URL(file,import.meta.url),'utf8'),{loader:'jsx',format:'cjs'}).code)(require,module,module.exports);const render=props=>{index=0;effects=[];return module.exports.default(props);};return {render,effects:()=>effects,html:props=>renderToStaticMarkup(render(props))};}
function find(tree,predicate){if(!tree||typeof tree!=='object')return null;if(predicate(tree))return tree;for(const child of React.Children.toArray(tree.props?.children)){const found=find(child,predicate);if(found)return found;}return null;}
const flush=()=>new Promise(r=>setImmediate(r));
test('required account security has enrollment controls but no disable action once enabled',async()=>{const calls=[],api=async path=>{calls.push(path);return {available:true,enabled:true,recoveryCodesRemaining:7,required:true};},h=component('../src/features/AccountSecurity.jsx');h.render({api,user:{id:'admin'}});h.effects()[0]();await flush();const html=h.html({api,user:{id:'admin'}});assert.match(html,/MFA is required for production administrators/);assert.doesNotMatch(html,/Disable MFA|Current password/);assert.deepEqual(calls,['/auth/mfa/status']);});
test('enrollment UI clears password, displays setup identity and gates fresh sign-in until recovery codes saved',async()=>{let reauthenticated=0;const calls=[],props={required:true,issuer:'Wimblo platform',user:{id:'operator',email:'operator@example.test'},onReauthenticate:()=>reauthenticated++,api:async(path,options)=>{calls.push([path,options]);if(path.endsWith('status'))return {available:true,enabled:false};if(path.endsWith('enroll'))return {secret:'SYNTHETICSETUPKEY',expiresAt:Date.now()+300000};if(path.endsWith('confirm'))return {recoveryCodes:['SYNTHETIC-RECOVERY']};throw Error('Unexpected API');}},h=component('../src/features/AccountSecurity.jsx');h.render(props);h.effects()[0]();await flush();let tree=h.render(props);find(tree,e=>e.type==='input'&&e.props.type==='password').props.onChange({target:{value:'NeverRenderPassword!'}});tree=h.render(props);find(tree,e=>e.type==='form').props.onSubmit({preventDefault(){}});await flush();tree=h.render(props);assert.doesNotMatch(renderToStaticMarkup(tree),/NeverRenderPassword/);assert.match(renderToStaticMarkup(tree),/Wimblo platform|SYNTHETICSETUPKEY/);find(tree,e=>e.type==='input'&&e.props.pattern==='[0-9]{6}').props.onChange({target:{value:'123456'}});tree=h.render(props);find(tree,e=>e.type==='form').props.onSubmit({preventDefault(){}});await flush();tree=h.render(props);assert.match(renderToStaticMarkup(tree),/SYNTHETIC-RECOVERY/);const proceed=find(tree,e=>e.type==='button'&&e.props.disabled===true);assert.ok(proceed);assert.equal(reauthenticated,0);find(tree,e=>e.type==='input'&&e.props.type==='checkbox').props.onChange({target:{checked:true}});tree=h.render(props);find(tree,e=>e.type==='button').props.onClick();assert.equal(reauthenticated,1);assert.doesNotMatch(h.html(props),/SYNTHETIC-RECOVERY/);assert.deepEqual(calls.map(c=>c[0]),['/auth/mfa/status','/auth/mfa/enroll','/auth/mfa/confirm']);assert.equal(calls[1][1].body.password,'NeverRenderPassword!');});
test('platform existing enrollment session renders standalone setup without fetching tenant or audit data',async t=>{const savedFetch=globalThis.fetch,savedDocument=globalThis.document,calls=[];globalThis.document={title:''};globalThis.fetch=async path=>{calls.push(path);return {ok:true,json:async()=>({mfaEnrollmentRequired:true,user:{id:'operator'},csrfToken:'csrf'})};};t.after(()=>{globalThis.fetch=savedFetch;globalThis.document=savedDocument;});const h=component('../src/features/PlatformAdmin.jsx',{'./AccountSecurity':{__esModule:true,default:()=>React.createElement('section',null,'Standalone MFA')}});h.render();h.effects()[0]();await flush();await flush();assert.match(h.html(),/Finish platform administrator security setup|Standalone MFA/);assert.deepEqual(calls,['/api/platform/auth/me']);});

test('platform succession UI protects last administrator and clears explicit handoff password on submit',async t=>{const savedFetch=globalThis.fetch,savedDocument=globalThis.document;globalThis.document={title:''};t.after(()=>{globalThis.fetch=savedFetch;globalThis.document=savedDocument;});const primary={id:'primary',name:'Primary operator',email:'primary@example.test',role:'platform_admin',active:true,version:1,mfaEnabled:true},operators=[primary],calls=[];let release;globalThis.fetch=async(path,options)=>{calls.push([path,options]);let payload;if(path.endsWith('/auth/me'))payload={user:primary,csrfToken:'csrf',platformCapabilities:{syntheticWorkspaceCreation:false}};else if(path.endsWith('/tenants'))payload={tenants:[],audit:[]};else if(path.endsWith('/administrators')&&options.method==='POST'){const body=JSON.parse(options.body);await new Promise(r=>release=r);operators.push({...primary,...body,id:'secondary',mfaEnabled:false});payload={administrator:operators[1]};}else if(path.endsWith('/administrators'))payload={administrators:operators};else throw Error('Unexpected UI request');return {ok:true,json:async()=>payload};};const h=component('../src/features/PlatformAdmin.jsx');h.render();h.effects()[0]();await flush();await flush();let tree=h.render();find(tree,e=>e.type==='button'&&e.props['aria-label']==='Manage platform access for Primary operator').props.onClick();tree=h.render();const suspend=find(tree,e=>e.type==='option'&&e.props.value==='false');assert.equal(suspend.props.disabled,true);find(tree,e=>e.type==='button'&&e.props.type==='button').props.onClick();tree=h.render();find(tree,e=>e.type==='button'&&React.Children.toArray(e.props.children).includes('Add administrator')).props.onClick();for(const [label,value]of [['Full name','Trusted successor'],['Email','secondary@example.test'],['Initial password','HandoffSecure!2026'],['Reason for privileged access','Approved succession']]){tree=h.render();const field=find(tree,e=>e.type==='label'&&React.Children.toArray(e.props.children).includes(label));find(field,e=>e.type==='input'||e.type==='textarea').props.onChange({target:{value}});}tree=h.render();const submission=find(tree,e=>e.type==='form').props.onSubmit({preventDefault(){}});tree=h.render();assert.equal(find(tree,e=>e.type==='input'&&e.props.type==='password').props.value,'');assert.equal(JSON.parse(calls.at(-1)[1].body).password,'HandoffSecure!2026');assert.equal(calls.at(-1)[1].headers['X-CSRF-Token'],'csrf');release();await submission;const html=h.html();assert.match(html,/Trusted successor|no message was sent/);assert.doesNotMatch(html,/HandoffSecure!2026|Synthetic testing only/);});
