import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,randomUUID} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {createApp} from '../server/app.js';
const TENANT='d45efc29-7b4a-407d-8c87-8c0cb375ff64';
const hash=b=>createHash('sha256').update(b).digest('hex');
const bytes=Buffer.from('Synthetic immutable object document evidence\n');
const metadata={title:'Synthetic grant evidence',category:'Report',visibility:'Workspace',status:'Final',evidenceDate:'2025-09-13'};
const file={filename:'evidence.txt',contentBase64:bytes.toString('base64')};
function fakeStorage(){const objects=new Map();let hooks={},failPut=false,failGet=false,corrupt=false,failCleanup=false,ready=true,unverifiedPut=null;const deleted=[];
 const storage={kind:'object',scope:{provider:'s3',bucket:'synthetic-private-documents',namespace:'synthetic-release'},async verifyReadiness(){if(!ready)throw Object.assign(new Error('Synthetic private policy not verified'),{status:503});return {verified:true};},stage(p){return {...p,...this.scope,key:`namespaces/${this.scope.namespace}/tenants/${p.tenantId}/documents/${p.documentId}/revisions/${p.revision}/${p.attemptId}`,version:null};},async put(ref,data){await hooks.put?.(ref);if(failPut)throw Object.assign(new Error('Synthetic private upload failed'),{status:503});const stored={...ref,version:randomUUID(),encryption:'AES256'};objects.set(stored.key,{reference:stored,bytes:Buffer.from(data)});if(unverifiedPut)throw Object.assign(new Error('Synthetic successful unverified PUT'),{status:503,stagedReference:{...stored,version:unverifiedPut==='version'?null:stored.version},storageErrorCode:unverifiedPut==='version'?'PUT_VERSION_UNVERIFIED':'PUT_ENCRYPTION_UNVERIFIED'});return stored;},async get(ref){await hooks.get?.(ref);if(failGet)throw Object.assign(new Error('Synthetic exact version unavailable'),{status:503});const o=objects.get(ref.key);if(!o||o.reference.version!==ref.version||o.reference.tenantId!==ref.tenantId)throw Object.assign(new Error('Synthetic wrong reference'),{status:503});return corrupt?Buffer.alloc(ref.size,88):o.bytes;},async deleteStaged(ref){if(failCleanup)throw new Error('Synthetic cleanup failed');deleted.push(ref);objects.delete(ref.key);}};
 return {storage,objects,deleted,set:v=>{if(v.hooks!==undefined)hooks=v.hooks;if(v.failPut!==undefined)failPut=v.failPut;if(v.failGet!==undefined)failGet=v.failGet;if(v.corrupt!==undefined)corrupt=v.corrupt;if(v.failCleanup!==undefined)failCleanup=v.failCleanup;if(v.ready!==undefined)ready=v.ready;if(v.unverifiedPut!==undefined)unverifiedPut=v.unverifiedPut;}};}
async function fixture(t,{scanner=null}={}){const temp=await mkdtemp(join(tmpdir(),'wimblo-private-object-')),dbPath=join(temp,'business.sqlite'),f=fakeStorage();let app,server,base;
 async function open(storage=f.storage,tenant=TENANT){app=createApp({dbPath,seed:true,documentStorage:storage,documentTenantId:tenant,documentScanner:scanner});server=app.listen(0,'127.0.0.1');await once(server,'listening');base=`http://127.0.0.1:${server.address().port}/api`;}
 async function close(){if(server)await new Promise(r=>server.close(r));server=null;app?.locals.close();app=null;}
 await open();t.after(async()=>{await close();await rm(temp,{recursive:true,force:true});});
 async function request(path,{method='GET',body,session,csrf=true}={}){const r=await fetch(base+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(session?{Cookie:session.cookie,...(csrf?{'X-CSRF-Token':session.csrfToken}:{})}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,json:await r.json()};}
 async function login(email){const r=await fetch(base+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:'FoundationDemo!2026'})});assert.equal(r.status,200);return {...await r.json(),cookie:r.headers.get('set-cookie').split(';')[0]};}
 const admin=await login('alex@foundation.example'),staff=await login('staff@foundation.example'),viewer=await login('board@foundation.example');
 async function create(collection,p){const r=await request('/records/'+collection,{method:'POST',session:admin,body:p});assert.equal(r.status,201,JSON.stringify(r.json));return r.json.record;}
 const task=await create('tasks',{title:'Synthetic document source',dueDate:'2025-09-13',status:'Open'});
 const upload=(changes={},session=admin)=>request('/documents',{method:'POST',session,body:{...metadata,...file,collection:'tasks',recordId:task.id,...changes}});
 const content=(document,revision=1,session=admin)=>request(`/documents/${document.id}/revisions/${revision}/content`,{session});
 return {...f,request,admin,staff,viewer,task,create,upload,content,get db(){return app.locals.db;},get service(){return app.locals.documentService;},restart:async(storage=f.storage,tenant=TENANT)=>{await close();await open(storage,tenant);}};}

test('mounted private revision upload commits only readback-verified references and returns bytes without exposing bucket keys or URLs',async t=>{const f=await fixture(t),r=await f.upload({},f.staff);assert.equal(r.status,201,JSON.stringify(r.json));const d=r.json.document;assert.equal(d.revisions[0].size,bytes.length);assert.equal(d.revisions[0].sha256,hash(bytes));assert.equal(d.revisions[0].metadata.storage.state,'Verified');assert.equal(f.db.prepare('SELECT length(bytes) n FROM document_revisions WHERE document_id=?').get(d.id).n,0);const storage=f.db.prepare('SELECT * FROM document_revision_storage WHERE document_id=?').get(d.id);assert.equal(storage.tenant_id,TENANT);assert.ok(storage.object_version);assert.equal(storage.sha256,hash(bytes));assert.equal(f.db.prepare('SELECT state FROM document_upload_attempts WHERE document_id=?').get(d.id).state,'Committed');assert.deepEqual(Buffer.from((await f.content(d,1,f.viewer)).json.contentBase64,'base64'),bytes);assert.doesNotMatch(JSON.stringify(r.json),/synthetic-private-documents|namespaces\/|https:|object_key/);assert.throws(()=>f.db.exec("UPDATE document_revision_storage SET object_key='another'"),/immutable/);assert.throws(()=>f.db.exec('DELETE FROM document_revision_storage'),/retained/);await f.restart();assert.deepEqual(Buffer.from((await f.content(d)).json.contentBase64,'base64'),bytes);});

test('failed, corrupt, quarantined or unverified uploads never become usable document evidence',async t=>{const f=await fixture(t);f.set({ready:false});assert.equal((await f.upload()).status,503);assert.equal(f.objects.size,0);f.set({ready:true,failPut:true});assert.equal((await f.upload()).status,503);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM documents').get().n,0);f.set({failPut:false,corrupt:true});assert.equal((await f.upload()).status,503);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM document_revisions').get().n,0);assert.equal(f.objects.size,0);const quarantine=await fixture(t,{scanner:async()=>({status:'Infected',sha256:hash(bytes)})});assert.equal((await quarantine.upload()).status,409);assert.equal(quarantine.objects.size,0);assert.equal(quarantine.db.prepare('SELECT state FROM document_upload_attempts').get().state,'Quarantined');assert.equal(quarantine.db.prepare('SELECT COUNT(*) n FROM document_revisions').get().n,0);});

test('document role/CSRF and current plus historical private revisions stay enforced with external bytes',async t=>{const f=await fixture(t);assert.equal((await f.upload({},f.viewer)).status,403);assert.equal((await f.request('/documents',{method:'POST',session:f.staff,csrf:false,body:{...metadata,...file,collection:'tasks',recordId:f.task.id}})).status,403);const privateDoc=(await f.upload({visibility:'Administrators'})).json.document;assert.equal((await f.content(privateDoc,1,f.staff)).status,404);const revised=await f.request(`/documents/${privateDoc.id}/revisions`,{method:'POST',session:f.admin,body:{...metadata,...file,version:1,title:'Shared later revision'}});assert.equal(revised.status,200,JSON.stringify(revised.json));const detail=await f.request(`/documents/${privateDoc.id}`,{session:f.viewer});assert.deepEqual(detail.json.document.revisions.map(v=>v.revision),[2]);assert.equal((await f.content(privateDoc,1,f.viewer)).status,404);assert.equal((await f.content(privateDoc,2,f.viewer)).status,200);});

test('async upload leaves no transaction open and rechecks source versions before committing, cleaning rejected objects',async t=>{const f=await fixture(t);f.set({hooks:{put:async()=>{const changed=await f.request('/records/tasks/'+f.task.id,{method:'PATCH',session:f.admin,body:{version:1,title:'Concurrent source correction'}});assert.equal(changed.status,200);}}});const r=await f.upload();assert.equal(r.status,409,JSON.stringify(r.json));assert.equal(f.db.prepare('SELECT COUNT(*) n FROM documents').get().n,0);assert.equal(f.objects.size,0);assert.equal(f.deleted.length,1);assert.equal(f.db.prepare('SELECT state FROM document_upload_attempts').get().state,'Failed');});

test('audit failure rolls back private revision metadata and retains failed attempt rather than false completion',async t=>{const f=await fixture(t);f.db.exec("CREATE TRIGGER synthetic_document_commit_audit_fault BEFORE INSERT ON audit WHEN NEW.action='upload_document' BEGIN SELECT RAISE(ABORT,'Synthetic private document audit failure'); END;");assert.equal((await f.upload()).status,500);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM documents').get().n,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM document_revisions').get().n,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM document_revision_storage').get().n,0);assert.equal(f.objects.size,0);assert.equal(f.db.prepare('SELECT state FROM document_upload_attempts').get().state,'Failed');});

test('post-read role/privacy changes and wrong tenant storage never return previously authorized content',async t=>{const f=await fixture(t),d=(await f.upload()).json.document;f.set({hooks:{get:async()=>{f.db.prepare('UPDATE documents SET visibility=?,version=version+1 WHERE id=?').run('Administrators',d.id);}}});assert.equal((await f.content(d,1,f.viewer)).status,404);f.set({hooks:{}});await f.restart(f.storage,'e6fb20b8-73f7-4a29-8839-bc9931b862b3');assert.equal((await f.content(d,1,f.admin)).status,503);});

test('trusted offline recovery materialization preserves immutable external provenance and verifies inline bytes',async t=>{const f=await fixture(t),d=(await f.upload()).json.document,stored=f.db.prepare('SELECT * FROM document_revision_storage WHERE document_id=?').get(d.id),verified=await f.service.exportStoredRevision(stored);assert.deepEqual(verified,bytes);f.db.exec('DROP TRIGGER document_revision_no_update');f.db.prepare('UPDATE document_revisions SET bytes=? WHERE document_id=? AND revision=1').run(verified,d.id);f.db.exec("CREATE TRIGGER document_revision_no_update BEFORE UPDATE ON document_revisions BEGIN SELECT RAISE(ABORT,'Document revisions are immutable'); END;");f.objects.clear();await f.restart(null);assert.deepEqual(Buffer.from((await f.content(d)).json.contentBase64,'base64'),bytes);assert.deepEqual(f.db.prepare('SELECT * FROM document_revision_storage WHERE document_id=?').get(d.id),stored);assert.equal((await f.service.readRevision(d.id,1,f.admin.user)).materializedInline,true);assert.throws(()=>f.db.prepare('UPDATE document_revisions SET bytes=? WHERE document_id=?').run(Buffer.from('Alter'),d.id),/immutable/);});

async function grantEvidence(f){const w=(await f.request('/workspace',{session:f.admin})).json.data,grant=w.grants[0],r=await f.request('/grant-operations',{method:'POST',session:f.staff,body:{grantId:grant.id,grantVersion:grant.version,name:'Synthetic object report milestone',kind:'Report',dueDate:'2025-09-13',ownerId:f.staff.user.id,ownerVersion:1}});assert.equal(r.status,201,JSON.stringify(r.json));const d=await f.upload({collection:'grants',recordId:grant.id});assert.equal(d.status,201,JSON.stringify(d.json));return {grant,m:r.json.milestone,d:d.json.document,body:{version:1,grantVersion:grant.version,ownerVersion:1,documentId:d.json.document.id,documentVersion:1,revision:1,completedDate:'2025-09-14',reference:'Synthetic staff documentary proof; no external submission',confirmed:true}};}

test('grant completion awaits exact object evidence outside transactions and retains real byte checksum/size without income writes',async t=>{const f=await fixture(t),g=await grantEvidence(f),giftsBefore=f.db.prepare("SELECT data FROM records WHERE collection='gifts' ORDER BY id").all();assert.equal(f.db.prepare('SELECT length(bytes) n FROM document_revisions WHERE document_id=?').get(g.d.id).n,0);const r=await f.request('/grant-operations/'+g.m.id+'/complete',{method:'POST',session:f.staff,body:g.body});assert.equal(r.status,200,JSON.stringify(r.json));assert.equal(r.json.milestone.status,'Completed');assert.equal(r.json.milestone.completion.document.size,bytes.length);assert.equal(r.json.milestone.completion.document.sha256,hash(bytes));assert.deepEqual(f.db.prepare("SELECT data FROM records WHERE collection='gifts' ORDER BY id").all(),giftsBefore);await f.restart();assert.equal((await f.request('/grant-operations/'+g.m.id,{session:f.staff})).json.milestone.completion.document.size,bytes.length);});

test('missing/corrupt object evidence and concurrent milestone/source changes cannot complete a grant',async t=>{const f=await fixture(t),g=await grantEvidence(f);f.set({failGet:true});assert.equal((await f.request('/grant-operations/'+g.m.id+'/complete',{method:'POST',session:f.staff,body:g.body})).status,503);f.set({failGet:false,corrupt:true});assert.equal((await f.request('/grant-operations/'+g.m.id+'/complete',{method:'POST',session:f.staff,body:g.body})).status,503);f.set({corrupt:false,hooks:{get:async()=>{const updated=await f.request('/records/grants/'+g.grant.id,{method:'PATCH',session:f.admin,body:{version:g.grant.version,notes:'Concurrent source version changed while object readback awaited'}});assert.equal(updated.status,200);}}});const denied=await f.request('/grant-operations/'+g.m.id+'/complete',{method:'POST',session:f.staff,body:g.body});assert.equal(denied.status,409,JSON.stringify(denied.json));assert.equal(f.db.prepare("SELECT COUNT(*) n FROM grant_milestones WHERE json_extract(data,'$.status')='Completed'").get().n,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM grant_milestone_history').get().n,1);});

test('account suspension/session revocation during object upload or readback cannot retain authorized completion/content',async t=>{const f=await fixture(t),d=(await f.upload()).json.document;f.set({hooks:{get:async()=>{f.db.prepare('DELETE FROM sessions WHERE user_id=?').run(f.viewer.user.id);}}});assert.equal((await f.content(d,1,f.viewer)).status,401);f.set({hooks:{put:async()=>{f.db.prepare('UPDATE users SET active=0,version=version+1 WHERE id=?').run(f.staff.user.id);}}});const failed=await f.upload({},f.staff);assert.equal(failed.status,401,JSON.stringify(failed.json));assert.equal(f.db.prepare('SELECT COUNT(*) n FROM documents').get().n,1);assert.equal(f.objects.size,1);});

test('mounted object-backed document reports show real immutable byte sizes and protect private original revisions',async t=>{const f=await fixture(t),d=(await f.upload({visibility:'Administrators',filename:'PRIVATE_ORIGINAL.txt'})).json.document;const revised=await f.request(`/documents/${d.id}/revisions`,{method:'POST',session:f.admin,body:{...metadata,...file,version:1,title:'Shared later revision'}});assert.equal(revised.status,200);assert.equal(f.db.prepare('SELECT sum(length(bytes)) n FROM document_revisions WHERE document_id=?').get(d.id).n,0);for(const session of [f.admin,f.staff,f.viewer]){const current=await f.request('/custom-reports/run',{method:'POST',session,body:{name:'Actual object document size',entity:'documents',columns:['id','latestSize']}});assert.equal(current.status,200,JSON.stringify(current.json));assert.deepEqual(current.json.rows,[[d.id,bytes.length]]);const history=await f.request('/custom-reports/run',{method:'POST',session,body:{name:'Actual object revision size',entity:'documentRevisions',columns:['documentId','revision','filename','size']}});assert.equal(history.status,200,JSON.stringify(history.json));assert.equal(history.json.rows.length,session===f.admin?2:1);assert.ok(history.json.rows.every(r=>r[0]===d.id&&r[3]===bytes.length));if(session!==f.admin)assert.doesNotMatch(JSON.stringify(history.json),/PRIVATE_ORIGINAL/);assert.doesNotMatch(JSON.stringify(history.json),/synthetic-private-documents|object_key|namespaces\//);}});


test('mounted successful unverified PUT retains exact cleanup or durable ambiguous orphan without usable evidence',async t=>{const f=await fixture(t);f.set({unverifiedPut:'encryption'});assert.equal((await f.upload()).status,503);assert.equal(f.objects.size,0);const cleaned=f.db.prepare('SELECT * FROM document_upload_attempts').get();assert.equal(cleaned.state,'Failed');assert.ok(cleaned.object_version);assert.equal(cleaned.error_code,'PUT_ENCRYPTION_UNVERIFIED');assert.equal(f.deleted.length,1);f.set({unverifiedPut:'version'});assert.equal((await f.upload()).status,503);const orphan=f.db.prepare("SELECT * FROM document_upload_attempts WHERE state='Orphaned'").get();assert.ok(orphan.object_key);assert.equal(orphan.object_version,null);assert.equal(orphan.error_code,'PUT_VERSION_UNVERIFIED');assert.equal(f.objects.size,1);assert.equal(f.deleted.length,1);assert.equal(f.db.prepare('SELECT count(*) n FROM document_revisions').get().n,0);await f.restart();assert.equal(f.db.prepare("SELECT count(*) n FROM document_upload_attempts WHERE state='Orphaned'").get().n,1);assert.equal((await f.request('/documents',{session:f.admin})).json.documents.length,0);});
