import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {Readable} from 'node:stream';
import {createS3DocumentStorage,createObjectStorageFromEnv} from '../server/objectStorage.js';
const hash=b=>createHash('sha256').update(b).digest('hex');
const bytes=Buffer.from('Synthetic private evidence\n');
function fixture(){const calls=[],objects=new Map();let tamper=null,publicBucket=false,versioned=true,encrypted=true,location=null,putResult=null;
 const client={async send(command){const input=command.input,type=command.constructor.name;calls.push({type,input});if(type==='GetBucketLocationCommand')return {LocationConstraint:location};if(type==='GetBucketAclCommand')return {Owner:{ID:'synthetic-owner'},Grants:[{Grantee:publicBucket?{URI:'http://acs.amazonaws.com/groups/global/AllUsers'}:{ID:'synthetic-owner'},Permission:'FULL_CONTROL'}]};if(type==='GetPublicAccessBlockCommand')return {PublicAccessBlockConfiguration:{BlockPublicAcls:true,IgnorePublicAcls:true,BlockPublicPolicy:true,RestrictPublicBuckets:true}};if(type==='GetBucketPolicyStatusCommand')return {PolicyStatus:{IsPublic:false}};if(type==='GetBucketEncryptionCommand')return encrypted?{ServerSideEncryptionConfiguration:{Rules:[{ApplyServerSideEncryptionByDefault:{SSEAlgorithm:'AES256'}}]}}:{};if(type==='GetBucketVersioningCommand')return {Status:versioned?'Enabled':'Suspended'};if(type==='PutObjectCommand'){if(objects.has(input.Key))throw Object.assign(new Error('Already exists'),{name:'PreconditionFailed'});objects.set(input.Key,{bytes:Buffer.from(input.Body),metadata:input.Metadata,version:'synthetic-exact-version'});return putResult||{VersionId:'synthetic-exact-version',ServerSideEncryption:'AES256'};}if(type==='GetObjectCommand'){const object=objects.get(input.Key);if(!object)throw new Error('Missing exact file');return {ServerSideEncryption:tamper?.ServerSideEncryption??'AES256',...(tamper||{}),Body:tamper?.Body||Readable.from([object.bytes]),ContentLength:tamper?.ContentLength??object.bytes.length,VersionId:tamper?.VersionId??object.version,Metadata:tamper?.Metadata??object.metadata};}if(type==='DeleteObjectCommand'){objects.delete(input.Key);return {};}throw new Error(type);}};
 const storage=createS3DocumentStorage({bucket:'synthetic-private-documents',namespace:'synthetic-release',region:'us-east-1',privateConfirmed:true,client});return {calls,objects,storage,setTamper:v=>tamper=v,setPublic:v=>publicBucket=v,setVersioned:v=>versioned=v,setEncrypted:v=>encrypted=v,setLocation:v=>location=v,setPutResult:v=>putResult=v};}

test('private readiness exercises access policy, provider versioning and exact synthetic roundtrip without public URLs',async()=>{const f=fixture(),ready=await f.storage.verifyReadiness();assert.equal(ready.verified,true);assert.equal(ready.private,true);assert.equal(ready.versioned,true);assert.equal(f.objects.size,0);assert.deepEqual(f.calls.map(c=>c.type),['GetBucketLocationCommand','GetBucketAclCommand','GetPublicAccessBlockCommand','GetBucketPolicyStatusCommand','GetBucketEncryptionCommand','GetBucketVersioningCommand','PutObjectCommand','GetObjectCommand','DeleteObjectCommand']);const put=f.calls.find(c=>c.type==='PutObjectCommand').input;assert.equal(put.IfNoneMatch,'*');assert.equal(put.CacheControl,'private, no-store');assert.equal(put.ACL,undefined);assert.equal(f.calls.at(-1).input.VersionId,'synthetic-exact-version');assert.equal('url' in ready,false);f.setPublic(true);await assert.rejects(f.storage.verifyReadiness({force:true}),/verification failed/);f.setPublic(false);f.setVersioned(false);await assert.rejects(f.storage.verifyReadiness({force:true}),/verification failed/);f.setVersioned(true);f.setEncrypted(false);await assert.rejects(f.storage.verifyReadiness({force:true}),/verification failed/);});

test('exact version and tenant/checksum/size gates deny corrupt or redirected private object content',async()=>{const f=fixture(),pending=f.storage.stage({tenantId:'tenant-a',documentId:'document-a',revision:1,sha256:hash(bytes),size:bytes.length}),ref=await f.storage.put(pending,bytes,'text/plain');assert.deepEqual(await f.storage.get(ref),bytes);await assert.rejects(f.storage.get({...ref,bucket:'other-bucket'}),/outside/);await assert.rejects(f.storage.get({...ref,tenantId:'tenant-b'}),/outside/);await assert.rejects(f.storage.get({...ref,version:null}),/exact provider version/);for(const tamper of [{VersionId:'other-version'},{Metadata:{'wimblo-tenant-id':'other','wimblo-sha256':hash(bytes)}},{ContentLength:bytes.length+1},{Body:Readable.from([Buffer.from('x'.repeat(bytes.length))])}]){f.setTamper(tamper);await assert.rejects(f.storage.get(ref),/verification failed/);}f.setTamper(null);await f.storage.deleteStaged(ref);await assert.rejects(f.storage.get(ref),/unavailable/);});

test('streaming private download enforces expected byte bounds before accepting content',async()=>{const f=fixture(),pending=f.storage.stage({tenantId:'tenant-a',documentId:'document-a',revision:1,sha256:hash(bytes),size:bytes.length}),ref=await f.storage.put(pending,bytes,'text/plain');f.setTamper({Body:Readable.from([bytes,Buffer.from('overflow')])});await assert.rejects(f.storage.get(ref),/size verification failed/);});

test('configuration refuses implicit public status, wrong Neon region and credential-bearing endpoints',()=>{assert.equal(createObjectStorageFromEnv({}),null);assert.throws(()=>createObjectStorageFromEnv({DOCUMENT_STORAGE_PROVIDER:'s3'}),/server-only/);const config={bucket:'private-documents',namespace:'release-a',region:'us-east-1',privateConfirmed:true};assert.throws(()=>createS3DocumentStorage({...config,privateConfirmed:false}),/verified private/);assert.throws(()=>createS3DocumentStorage({...config,provider:'neon'}),/us-east-2/);for(const endpoint of ['http://unsafe.example','https://key:secret@example.test','https://example.test?token=secret'])assert.throws(()=>createS3DocumentStorage({...config,endpoint}),/HTTPS endpoint/);});


test('native actual bucket location must match configured region before any readiness upload',async()=>{const f=fixture();for(const actual of ['eu-west-1','EU','ca-central-1','us-east-2']){f.setLocation(actual);await assert.rejects(f.storage.verifyReadiness({force:true}),/verification failed/);assert.equal(f.objects.size,0);assert.equal(f.calls.some(c=>c.type==='PutObjectCommand'),false);}f.setLocation(null);const proof=await f.storage.verifyReadiness({force:true});assert.equal(proof.bucketRegion,'us-east-1');assert.equal(proof.locationVerified,true);});

test('production document configuration rejects foreign regions, all custom endpoints and unverified Neon',()=>{const env={NODE_ENV:'production',DOCUMENT_STORAGE_PROVIDER:'s3',DOCUMENT_STORAGE_BUCKET:'private-documents',DOCUMENT_STORAGE_NAMESPACE:'release-a',DOCUMENT_STORAGE_PRIVATE_CONFIRMED:'true',AWS_REGION:'us-east-1',AWS_ACCESS_KEY_ID:'synthetic',AWS_SECRET_ACCESS_KEY:'not-live'};assert.equal(createObjectStorageFromEnv(env).scope.region,'us-east-1');for(const AWS_REGION of ['eu-west-1','ap-south-1','us-gov-west-1'])assert.throws(()=>createObjectStorageFromEnv({...env,AWS_REGION}),/US or Canada/);for(const field of ['AWS_ENDPOINT_URL_S3','AWS_ENDPOINT_URL'])assert.throws(()=>createObjectStorageFromEnv({...env,[field]:'https://s3.eu-west-1.amazonaws.com'}),/custom (?:AWS )?endpoint/);assert.throws(()=>createObjectStorageFromEnv({...env,DOCUMENT_STORAGE_PROVIDER:'neon',AWS_REGION:'us-east-2'}),/Neon storage has not been verified/);});


test('successful native PUT with unverified encryption or omitted version retains a safe ambiguous staging reference',async()=>{const f=fixture();await f.storage.verifyReadiness();for(const result of [{VersionId:'synthetic-exact-version'},{ServerSideEncryption:'AES256'}]){f.setPutResult(result);const pending=f.storage.stage({tenantId:'tenant-a',documentId:'document-a',revision:1,sha256:hash(bytes),size:bytes.length});await assert.rejects(f.storage.put(pending,bytes,'text/plain'),error=>{assert.equal(error.stagedReference.key,pending.key);assert.equal(error.stagedReference.version,result.VersionId||null);assert.match(error.storageErrorCode,/PUT_(ENCRYPTION|VERSION)_UNVERIFIED/);return true;});assert.ok(f.objects.has(pending.key));}assert.equal(f.objects.size,2);});
