import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtemp,mkdir,rm,readFile,lstat,readdir,rename,chmod} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createApp} from '../server/app.js';
import {openOfflineRecoverySchedule} from '../server/offlineRecoverySchedule.js';
const legacy='00000000-0000-4000-8000-000000000001',key='82'.repeat(32);
async function fixture(t,{store=null,requireOffHost=false}={}){
 const dir=await mkdtemp(join(tmpdir(),'wimblo-offline-schedule-')),source=join(dir,'source'),rootDir=join(source,'platform'),legacyDbPath=join(source,'legacy.sqlite'),archiveDir=join(dir,'archives'),journalPath=join(dir,'operator','journal.sqlite');await mkdir(rootDir,{recursive:true});
 const app=createApp({dbPath:legacyDbPath,seed:false,initialAdmin:{name:'Archive operator',email:'archive@example.test',password:'InertArchiveFixture!2026'},mfaKey:'83'.repeat(32),reminderWorker:false,workflowWorker:false});app.locals.db.prepare("INSERT INTO records VALUES(?,?,?)").run('retained-source','constituents',JSON.stringify({id:'retained-source',name:'Retained source',version:1}));app.locals.close();
 const registry=new DatabaseSync(join(rootDir,'platform.sqlite'));registry.exec('CREATE TABLE tenants(id TEXT PRIMARY KEY);CREATE TABLE administrators(id TEXT);CREATE TABLE platform_sessions(token_hash TEXT);CREATE TABLE platform_audit(id INTEGER);');registry.prepare('INSERT INTO tenants VALUES(?)').run(legacy);registry.close();
 let time=Date.now();const options={journalPath,clock:()=>time,store};let service=await openOfflineRecoverySchedule(options);t.after(async()=>{service?.close();await rm(dir,{recursive:true,force:true});});
 const body={rootDir,legacyDbPath,archiveDir,recoveryId:randomUUID(),cadence:'Daily',firstRunAt:new Date(time).toISOString(),requireOffHost,reason:'Explicit synthetic offline schedule approval'};
 await service.arm(body);return{dir,rootDir,legacyDbPath,archiveDir,journalPath,body,advance:n=>time+=n,get service(){return service;},restart:async()=>{service.close();service=await openOfflineRecoverySchedule(options);},run:()=>service.runDue({offlineConfirmed:true,encryptionKey:key})};
}
test('one due offline occurrence verifies an encrypted complete archive, persists private evidence and catches up only once',async t=>{
 const f=await fixture(t);await assert.rejects(f.service.runDue({encryptionKey:key}),/stopped/);assert.equal(f.service.inspect().runs.length,0);
 f.advance(3*86400000+1000);const result=await f.run();assert.equal(result.status,'Verified');assert.equal(result.tenantCount,1);assert.equal(result.offHostVerified,false);assert.equal(result.storage,'Local archive only');assert.equal(result.restoreVerified,true);
 const file=join(f.archiveDir,result.id+'.wrecovery');assert.equal((await lstat(file)).mode&0o777,0o600);assert.equal((await lstat(f.journalPath)).mode&0o777,0o600);assert.equal((await readFile(file)).includes(Buffer.from('Retained source')),false);
 assert.equal((await readdir(f.archiveDir)).some(n=>n.startsWith('.scheduled-drill-')),false);await f.restart();assert.equal(f.service.inspect().runs.length,1);assert.deepEqual(await f.run(),{due:false,notice:f.service.inspect().notice});assert.ok(Date.parse(f.service.inspect().schedule.nextRunAt)>Date.now());
 const journal=new DatabaseSync(f.journalPath);try{assert.throws(()=>journal.exec('DELETE FROM offline_recovery_outcomes'),/retained/);assert.throws(()=>journal.exec("UPDATE offline_recovery_outcomes SET reason='rewritten'"),/immutable/);assert.throws(()=>journal.exec('DELETE FROM offline_recovery_runs'),/retained/);}finally{journal.close();}
});
test('source failure is dated and blocks automatic retry; explicit reasoned recovery reuses the same occurrence',async t=>{
 const f=await fixture(t),path=join(f.rootDir,'platform.sqlite');await rename(path,path+'.held');await assert.rejects(f.run(),/failed/);const failed=f.service.inspect().runs[0];assert.equal(failed.status,'Failed');assert.equal(failed.phase,'Reserved');assert.equal(failed.restoreVerified,false);await assert.rejects(f.run(),/explicit recovery/);await rename(path+'.held',path);
 await assert.rejects(f.service.recover({runId:failed.id,version:failed.revision,offlineConfirmed:true,runnerStoppedConfirmed:true,reason:' ',encryptionKey:key}));
 const restored=await f.service.recover({runId:failed.id,version:failed.revision,offlineConfirmed:true,runnerStoppedConfirmed:true,reason:'Source returned; original runner stopped',encryptionKey:key});assert.equal(restored.status,'Verified');assert.equal(restored.id,failed.id);assert.equal(f.service.inspect().runs.length,1);assert.ok(f.service.getRun(failed.id).outcomes.some(o=>o.action==='Failed'));
});
test('deferred final journal COMMIT failure never reports Verified or advances due cycle; retained exact archive recovers without overwrite',async t=>{
 const f=await fixture(t),db=new DatabaseSync(f.journalPath),before=f.service.inspect().schedule.nextRunAt;db.exec("PRAGMA foreign_keys=ON;CREATE TABLE fail_parent(id INTEGER PRIMARY KEY);CREATE TABLE fail_child(id INTEGER REFERENCES fail_parent(id) DEFERRABLE INITIALLY DEFERRED);CREATE TRIGGER fail_final AFTER INSERT ON offline_recovery_outcomes WHEN NEW.action='Verified' BEGIN INSERT INTO fail_child VALUES(1);END;");
 await assert.rejects(f.run(),/failed/);const failed=f.service.inspect().runs[0],bytes=await readFile(join(f.archiveDir,failed.id+'.wrecovery'));assert.equal(failed.status,'Failed');assert.equal(failed.phase,'Archived');assert.equal(f.service.inspect().schedule.nextRunAt,before);assert.equal(f.service.getRun(failed.id).outcomes.some(o=>o.action==='Verified'),false);assert.equal(db.prepare('SELECT COUNT(*) n FROM fail_child').get().n,0);db.exec('DROP TRIGGER fail_final');db.close();
 const recovered=await f.service.recover({runId:failed.id,version:failed.revision,offlineConfirmed:true,runnerStoppedConfirmed:true,reason:'Final journal fault repaired after shutdown',encryptionKey:key});assert.equal(recovered.status,'Verified');assert.deepEqual(await readFile(join(f.archiveDir,failed.id+'.wrecovery')),bytes);
});
test('ambiguous off-host publication requires exact version readback and cannot auto-republish even after a wrong recovery reference',async t=>{
 let bytes,puts=0,reads=0,failRead=true;const store={private:true,offHost:true,putImmutable:async input=>{puts++;bytes=Buffer.from(input.bytes);return{key:'private/exact-root',versionId:'version-one'};},readVersion:async ref=>{reads++;if(failRead||ref.versionId!=='version-one')throw Error('Injected readback unavailable');return bytes;}};
 const f=await fixture(t,{store,requireOffHost:true});await assert.rejects(f.run(),/failed/);let failed=f.service.inspect().runs[0];assert.equal(failed.publicationRecoveryRequired,true);assert.equal(puts,1);
 const recovery=()=>({runId:failed.id,version:failed.revision,offlineConfirmed:true,runnerStoppedConfirmed:true,reason:'Inspect exact retained publication after shutdown',encryptionKey:key});await assert.rejects(f.service.recover(recovery()),/automatic republishing/);failRead=false;
 await assert.rejects(f.service.recover({...recovery(),reference:{key:'private/exact-root',versionId:'wrong-version'}}),/failed/);failed=f.service.inspect().runs[0];await assert.rejects(f.service.recover(recovery()),/automatic republishing/);assert.equal(puts,1);
 const result=await f.service.recover({...recovery(),reference:{key:'private/exact-root',versionId:'version-one'}});assert.equal(result.status,'Verified');assert.equal(result.offHostVerified,true);assert.equal(result.objectKey,'private/exact-root');assert.equal(puts,1);assert.ok(reads>=3);
});
test('two native journal connections cannot reserve duplicate due cycles; retirement is reasoned/versioned and cannot rearm',async t=>{
 const f=await fixture(t);const other=await openOfflineRecoverySchedule({journalPath:f.journalPath});try{const outcomes=await Promise.allSettled([f.run(),other.runDue({offlineConfirmed:true,encryptionKey:key})]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.service.inspect().runs.length,1);}finally{other.close();}
 const s=f.service.inspect().schedule;assert.throws(()=>f.service.retire({version:s.revision-1,reason:'stale'}),/revision/);const retired=f.service.retire({version:s.revision,reason:'Preserve journal; stop this schedule'});assert.equal(retired.status,'Retired');assert.equal(retired.nextRunAt,null);await assert.rejects(f.run(),/active/);await assert.rejects(f.service.arm(f.body),/retained schedule/);assert.equal(f.service.inspect().runs[0].status,'Verified');
});
test('private operator custody and preserved archive integrity are mandatory, with no local directory treated as off-host',async t=>{
 const f=await fixture(t);const result=await f.run(),file=join(f.archiveDir,result.id+'.wrecovery');await chmod(f.journalPath,0o644);await assert.rejects(openOfflineRecoverySchedule({journalPath:f.journalPath}),/private regular/);await chmod(f.journalPath,0o600);
 const db=new DatabaseSync(f.journalPath);const row=JSON.parse(db.prepare('SELECT data FROM offline_recovery_runs').get().data);db.prepare('UPDATE offline_recovery_runs SET data=?').run(JSON.stringify({...row,status:'Failed'}));const s=JSON.parse(db.prepare('SELECT data FROM offline_recovery_schedule').get().data);db.prepare('UPDATE offline_recovery_schedule SET data=?').run(JSON.stringify({...s,currentRunId:row.id}));db.close();const data=await readFile(file);data[data.length-1]^=1;await import('node:fs/promises').then(fs=>fs.writeFile(file,data));
 await assert.rejects(f.service.recover({runId:row.id,version:row.revision,offlineConfirmed:true,runnerStoppedConfirmed:true,reason:'Reject damaged retained archive',encryptionKey:key}),/failed/);assert.equal(f.service.inspect().runs[0].restoreVerified,false);
});
test('missing off-host configuration never creates an ambiguous publication flag; explicit recovery with the adopted adapter works',async t=>{
 const f=await fixture(t,{requireOffHost:true});await assert.rejects(f.run(),/failed/);const failed=f.service.inspect().runs[0];assert.equal(failed.phase,'Archived');assert.equal(failed.publicationRecoveryRequired,false);let stored,puts=0;const store={private:true,offHost:true,putImmutable:async i=>{puts++;stored=Buffer.from(i.bytes);return{key:'private/adopted',versionId:'exact-v1'};},readVersion:async()=>stored};const other=await openOfflineRecoverySchedule({journalPath:f.journalPath,store});try{const result=await other.recover({runId:failed.id,version:failed.revision,offlineConfirmed:true,runnerStoppedConfirmed:true,reason:'Private adapter configured after offline inspection',encryptionKey:key});assert.equal(result.status,'Verified');assert.equal(result.offHostVerified,true);assert.equal(puts,1);}finally{other.close();}
});
test('two independent worker threads competing at the same UTC occurrence commit exactly one archive and journal run',async t=>{
 const {Worker}=await import('node:worker_threads'),f=await fixture(t),moduleURL=new URL('../server/offlineRecoverySchedule.js',import.meta.url).href;
 const code=`const {parentPort,workerData}=require('node:worker_threads');let service;import(workerData.moduleURL).then(async m=>{service=await m.openOfflineRecoverySchedule({journalPath:workerData.journalPath});parentPort.postMessage({ready:true});parentPort.once('message',async()=>{try{const run=await service.runDue({offlineConfirmed:true,encryptionKey:workerData.key});parentPort.postMessage({status:run.status,due:run.due});}catch(e){parentPort.postMessage({failed:true});}finally{service.close();}});}).catch(e=>{parentPort.postMessage({setupError:true});});`;
 const workers=[0,1].map(()=>new Worker(code,{eval:true,workerData:{moduleURL,journalPath:f.journalPath,key}}));t.after(async()=>{await Promise.all(workers.map(w=>w.terminate()));});
 await Promise.all(workers.map(w=>new Promise((resolve,reject)=>{w.once('message',m=>m.ready?resolve():reject(Error('worker setup failed')));w.once('error',reject);})));const replies=workers.map(w=>new Promise((resolve,reject)=>{w.once('message',resolve);w.once('error',reject);}));for(const w of workers)w.postMessage('run');const results=await Promise.all(replies);assert.equal(results.filter(r=>r.status==='Verified').length,1);assert.equal(results.filter(r=>r.failed||r.due===false).length,1);assert.equal(f.service.inspect().runs.length,1);assert.equal((await readdir(f.archiveDir)).filter(n=>n.endsWith('.wrecovery')).length,1);
});
test('five-thousand retained-run capacity accepts the final due archive then refuses overflow without purging history',async t=>{
 const f=await fixture(t),db=new DatabaseSync(f.journalPath),start=Date.parse(f.body.firstRunAt);db.exec('BEGIN');const insert=db.prepare('INSERT INTO offline_recovery_runs VALUES(?,?,?)');for(let n=1;n<5000;n++){const id=randomUUID(),at=new Date(start-n*86400000).toISOString();insert.run(id,at,JSON.stringify({id,scheduledAt:at,status:'Verified',phase:'Archived',revision:1,startedAt:at}));}db.exec('COMMIT');
 assert.equal(f.service.inspect().limits.runCapacity,5000);assert.equal(f.service.inspect().limits.outcomeCapacity,50000);const last=await f.run();assert.equal(last.status,'Verified');assert.equal(db.prepare('SELECT COUNT(*) n FROM offline_recovery_runs').get().n,5000);f.advance(86400000);await assert.rejects(f.run(),/capacity/);assert.equal(db.prepare('SELECT COUNT(*) n FROM offline_recovery_runs').get().n,5000);assert.equal(f.service.inspect().runs.length,100);assert.equal((await readdir(f.archiveDir)).filter(n=>n.endsWith('.wrecovery')).length,1);db.close();
});
