import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID, randomBytes, createHash } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { Worker } from 'node:worker_threads';
import { createApp } from '../server/app.js';
import { backupWorkspace, restoreWorkspace } from '../server/backup.js';

const password = 'SyntheticPeerAttributionAcceptance!2026';
async function fixture(t) {
  const dir = await mkdtemp(join(tmpdir(), 'wimblo-peer-integrity-')), dbPath = join(dir, 'workspace.sqlite'), tenantId = randomUUID(), initialAdmin = { name: 'Synthetic peer administrator', email: 'admin.peer@example.test', password }; let app, server, base, active = true; const sessions = {};
  async function close() { if (server) await new Promise(resolve => server.close(resolve)); server = null; app?.locals.close(); app = null; }
  async function request(path, { method = 'GET', body, session = sessions.admin, csrf = true } = {}) { const r = await fetch(base + '/api' + path, { method, headers: { ...(body === undefined ? {} : { 'Content-Type': 'application/json' }), ...(session ? { Cookie: session.cookie, ...(csrf ? { 'X-CSRF-Token': session.csrfToken } : {}) } : {}) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); const text = await r.text(); let json; try { json = JSON.parse(text); } catch { json = null; } return { status: r.status, json, text, headers: r.headers }; }
  async function login(email = initialAdmin.email) { const r = await request('/auth/login', { method: 'POST', session: null, body: { email, password } }); assert.equal(r.status, 200, r.text); return { ...r.json, cookie: r.headers.getSetCookie().map(value => value.split(';')[0]).join('; ') }; }
  async function open(path = dbPath) { app = createApp({ dbPath: path, seed: false, tenantId, initialAdmin, isTenantActive: () => active, workflowWorker: false, reminderWorker: false }); server = app.listen(0, '127.0.0.1'); await once(server, 'listening'); base = 'http://127.0.0.1:' + server.address().port; sessions.admin = await login(); }
  await open(); t.after(async () => { await close(); await rm(dir, { recursive: true, force: true }); });
  for (const [key, role] of [['staff', 'staff'], ['other', 'staff'], ['viewer', 'viewer'], ['helper', 'event-helper']]) { const r = await request('/users', { method: 'POST', body: { name: 'Synthetic peer ' + key, email: key + '.peer@example.test', password, role } }); assert.equal(r.status, 201, r.text); sessions[key] = await login(key + '.peer@example.test'); }
  async function create(collection, body) { const r = await request('/records/' + collection, { method: 'POST', body }); assert.equal(r.status, 201, r.text); return r.json.record; }
  async function person(name) { return create('constituents', { name, type: 'Individual', email: name.toLowerCase().replaceAll(' ', '.') + '@example.test', preference: 'Do not contact' }); }
  const donor = await person('Actual donor'), fundraiser = await person('Peer fundraiser'), softCredit = await person('Separate soft credit'), second = await person('Second peer fundraiser');
  const campaign = await create('campaigns', { name: 'Internal peer campaign', type: 'Peer-to-peer', goal: 999999, startDate: '2026-01-01', endDate: '2026-12-31', status: 'Active' }); const otherCampaign = await create('campaigns', { name: 'Different peer campaign', type: 'Peer-to-peer', goal: 999999, startDate: '2026-01-01', endDate: '2026-12-31', status: 'Active' });
  const fund = await create('designations', { name: 'Actual receipt fund', accountCode: 'PEER-101' });
  async function gift(changes = {}) { return create('gifts', { constituentId: donor.id, amount: 10001, type: 'Cash', method: 'Check', date: '2026-09-01', allocations: [{ designationId: fund.id, amount: 10001 }], campaignId: campaign.id, softCreditId: softCredit.id, giftKind: 'One-time', ...changes }); }
  const originalGift = await gift();
  const row = (collection, key) => JSON.parse(app.locals.db.prepare('SELECT data FROM records WHERE collection=? AND id=?').get(collection, key).data);
  const peerTables = () => app.locals.db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name LIKE 'peer_%' ORDER BY name").all().map(r => r.name);
  const snapshot = (withAudit = false) => Object.fromEntries(['records', ...peerTables(), ...(withAudit ? ['audit'] : [])].map(table => [table, app.locals.db.prepare('SELECT * FROM ' + table + ' ORDER BY rowid').all()]));
  const financial = () => Object.fromEntries(['records', 'receipt_preparations', 'receipt_issues', 'receipt_voids', 'correspondence_preparations', 'correspondence_finalizations', 'correspondence_fulfillments'].map(table => [table, table === 'records' ? app.locals.db.prepare("SELECT * FROM records WHERE collection IN ('gifts','campaigns','pledges','grants','communications') ORDER BY rowid").all() : app.locals.db.prepare('SELECT * FROM ' + table + ' ORDER BY rowid').all()]));
  async function setup(changes = {}, session = sessions.staff) { return request('/peer-fundraisers', { method: 'POST', session, body: { campaignId: campaign.id, campaignVersion: row('campaigns', campaign.id).version, constituentId: fundraiser.id, constituentVersion: row('constituents', fundraiser.id).version, coordinatorId: sessions.staff.user.id, coordinatorVersion: app.locals.db.prepare('SELECT version FROM users WHERE id=?').get(sessions.staff.user.id).version, title: 'Peer effort', goalCents: 25000, visibility: 'Workspace', ...changes } }); }
  async function detail(key, session = sessions.admin) { return request('/peer-fundraisers/' + key, { session }); }
  async function attribute(peer, changes = {}, session = sessions.staff) { return request('/peer-fundraisers/' + peer.id + '/attributions', { method: 'POST', session, body: { version: peer.version, giftId: originalGift.id, giftVersion: row('gifts', originalGift.id).version, campaignVersion: row('campaigns', campaign.id).version, coordinatorVersion: app.locals.db.prepare('SELECT version FROM users WHERE id=?').get(peer.coordinatorId || sessions.staff.user.id).version, reason: 'Reviewed existing gift referral ownership', ...changes } }); }
  return { dir, dbPath, tenantId, initialAdmin, sessions, donor, fundraiser, softCredit, second, campaign, otherCampaign, fund, originalGift, create, gift, row, request, login, setup, detail, attribute, snapshot, financial, peerTables, close, open, get db() { return app.locals.db; }, get app() { return app; }, set active(value) { active = value; }, restart: async () => { await close(); await open(); for (const key of ['staff', 'other', 'viewer', 'helper']) sessions[key] = await login(key + '.peer@example.test'); } };
}
async function effort(f, changes = {}, session) { const r = await f.setup(changes, session); assert.equal(r.status, 201, r.text); return r.json.fundraiser; }

test('internal peer attribution retains actual donor, separate soft credit and issued receipt without changing income', async t => {
  const f = await fixture(t); const permitted = await f.request('/records/constituents/' + f.donor.id, { method: 'PATCH', body: { version: 1, preference: 'Email' } }); assert.equal(permitted.status, 200); const profile = await f.request('/receipt-profile', { method: 'PUT', body: { version: 0, organizationName: 'Synthetic approved receipt organization', address: '123 Synthetic Street', taxIdentifier: 'SYNTHETIC-ONLY', signatureLabel: 'Synthetic signer', customFooter: 'Fixture approval only', approved: true } }); assert.equal(profile.status, 200, profile.text);
  const prepared = await f.request('/receipts/prepare', { method: 'POST', body: { kind: 'Individual', giftId: f.originalGift.id, profileVersion: 1, benefitsReviewed: true, benefitsAssessment: 'None provided', revenueClassification: 'Contribution' } }); assert.equal(prepared.status, 201, prepared.text); assert.equal(prepared.json.receipt.recipient.id, f.donor.id);
  const issued = await f.request('/receipts/' + prepared.json.receipt.id + '/issue', { method: 'POST', body: { version: 1, preparationDigest: prepared.json.receipt.preparationDigest, channel: 'Print', printed: true, handSigned: true, issueDate: '2026-09-13' } }); assert.equal(issued.status, 200, issued.text);
  const before = f.financial(), peer = await effort(f), linked = await f.attribute(peer); assert.equal(linked.status, 201, linked.text); assert.equal(linked.json.fundraiser.progress.postedCashCents, 10001); assert.equal(linked.json.fundraiser.progress.attributedGiftCount, 1); assert.deepEqual(f.financial(), before);
  const gift = f.row('gifts', f.originalGift.id); assert.equal(gift.constituentId, f.donor.id); assert.equal(gift.softCreditId, f.softCredit.id); assert.notEqual(gift.constituentId, f.fundraiser.id); assert.notEqual(gift.softCreditId, f.fundraiser.id); assert.equal(gift.amount, 10001); assert.equal(f.row('campaigns', f.campaign.id).goal, 999999); assert.equal(linked.json.fundraiser.goalCents, 25000);
  const receipt = await f.request('/receipts/' + prepared.json.receipt.id, { session: f.sessions.viewer }); assert.equal(receipt.json.receipt.recipient.id, f.donor.id); assert.equal(receipt.json.receipt.monetaryCents, 10001); assert.equal(receipt.json.receipt.number, issued.json.receipt.number);
  const duplicate = await f.attribute(linked.json.fundraiser); assert.equal(duplicate.status, 409, duplicate.text); assert.deepEqual(f.financial(), before);
});

test('reasoned unlink, native financial correction and fresh attribution preserve prior snapshots without double counting', async t => {
  const f = await fixture(t), peer = await effort(f), linked = await f.attribute(peer); assert.equal(linked.status, 201, linked.text);
  const correction = { version: 1, amount: 20002, allocations: [{ designationId: f.fund.id, amount: 20002 }], correctionReason: 'Correct actual source receipt value after review' };
  assert.equal((await f.request('/records/gifts/' + f.originalGift.id, { method: 'PATCH', body: correction })).status, 409);
  const aid = linked.json.attribution.id, unlinkBody = { version: linked.json.fundraiser.version, attributionVersion: linked.json.attribution.version, giftVersion: 1, reason: 'Release peer relation before actual financial correction' };
  const unlinked = await f.request('/peer-fundraisers/' + peer.id + '/attributions/' + aid + '/unlink', { method: 'POST', session: f.sessions.staff, body: unlinkBody }); assert.equal(unlinked.status, 200, unlinked.text); assert.equal(unlinked.json.fundraiser.progress.postedCashCents, 0);
  const corrected = await f.request('/records/gifts/' + f.originalGift.id, { method: 'PATCH', body: correction }); assert.equal(corrected.status, 200, corrected.text); assert.equal(corrected.json.record.version, 2);
  const relinked = await f.attribute(unlinked.json.fundraiser); assert.equal(relinked.status, 201, relinked.text); assert.equal(relinked.json.fundraiser.progress.postedCashCents, 20002); assert.equal(relinked.json.fundraiser.progress.unlinkedCount, 1); assert.notEqual(relinked.json.attribution.id, aid); assert.equal(f.db.prepare('SELECT count(*) n FROM gift_financial_corrections').get().n, 1);
  const attributionRows = f.db.prepare('SELECT * FROM peer_gift_attributions ORDER BY rowid').all(); assert.equal(attributionRows.length, 2); assert.match(JSON.stringify(attributionRows[0]), /10001/); assert.match(JSON.stringify(attributionRows[1]), /20002/);
  const retired = await f.request('/peer-fundraisers/' + peer.id + '/retire', { method: 'POST', session: f.sessions.staff, body: { version: relinked.json.fundraiser.version, reason: 'End the effort while preserving received support' } }); assert.equal(retired.status, 200, retired.text); assert.equal(retired.json.fundraiser.progress.postedCashCents, 20002);
  const voided = await f.request('/gifts/' + f.originalGift.id + '/void', { method: 'POST', body: { version: 2, reason: 'Void a duplicate manually recorded receipt, not a provider refund' } }); assert.equal(voided.status, 200, voided.text);
  const current = await f.detail(peer.id); assert.equal(current.json.fundraiser.progress.postedCashCents, 0); assert.equal(current.json.fundraiser.progress.voidedGiftCount, 1); assert.equal(f.row('gifts', f.originalGift.id).amount, 20002); assert.equal(f.db.prepare('SELECT count(*) n FROM peer_gift_attributions').get().n, 2); assert.equal(f.db.prepare('SELECT count(*) n FROM peer_gift_attribution_history').get().n, 3);
});

test('versions, actual gift classification, exact campaign, staff authority and current tenant access bound attribution', async t => {
  const f = await fixture(t), peer = await effort(f), baseline = f.snapshot();
  for (const session of [null, f.sessions.viewer, f.sessions.helper]) { const r = await f.attribute(peer, {}, session); assert.equal(r.status, session ? 403 : 401, r.text); assert.deepEqual(f.snapshot(), baseline); }
  for (const change of [{ version: 999 }, { giftVersion: 999 }, { campaignVersion: 999 }, { coordinatorVersion: 999 }, { reason: '' }, { giftId: randomUUID() }, { unexpected: true }]) { const r = await f.attribute(peer, change); assert.ok([400, 404, 409].includes(r.status), r.text); assert.deepEqual(f.snapshot(), baseline); }
  const invalid = [await f.gift({ campaignId: f.otherCampaign.id }), await f.gift({ type: 'Fee payment' }), await f.gift({ type: 'In-kind', method: 'In-kind' }), await f.gift({ giftKind: 'Recurring' }), await f.gift({ date: '2999-01-01' })];
  for (const gift of invalid) { const r = await f.attribute(peer, { giftId: gift.id, giftVersion: 1 }); assert.equal(r.status, 409, r.text); }
  const financial = f.financial(); f.active = false; const suspended = await f.attribute(peer); assert.equal(suspended.status, 403, suspended.text); assert.deepEqual(f.financial(), financial); f.active = true;
  const noCsrf = await f.request('/peer-fundraisers/' + peer.id + '/attributions', { method: 'POST', session: f.sessions.staff, csrf: false, body: { version: peer.version, giftId: f.originalGift.id, giftVersion: 1, campaignVersion: 1, coordinatorVersion: 1, reason: 'No CSRF cannot change relations' } }); assert.equal(noCsrf.status, 403);
});

test('current and retained historical private visibility hide the full effort and gift attribution lineage', async t => {
  const f = await fixture(t), peer = await effort(f), linked = await f.attribute(peer); assert.equal(linked.status, 201, linked.text);
  const body = { version: linked.json.fundraiser.version, title: 'PRIVATE_PEER_HISTORY_MARKER', goalCents: 25000, visibility: 'Administrators', coordinatorId: f.sessions.staff.user.id, coordinatorVersion: 1, reason: 'Tighten confidential effort access' };
  assert.equal((await f.request('/peer-fundraisers/' + peer.id, { method: 'PATCH', session: f.sessions.staff, body })).status, 403);
  const tightened = await f.request('/peer-fundraisers/' + peer.id, { method: 'PATCH', body }); assert.equal(tightened.status, 200, tightened.text);
  const relaxed = await f.request('/peer-fundraisers/' + peer.id, { method: 'PATCH', body: { ...body, version: tightened.json.fundraiser.version, visibility: 'Workspace', reason: 'Cannot disclose historical private chain' } }); assert.equal(relaxed.status, 409, relaxed.text);
  for (const session of [f.sessions.staff, f.sessions.viewer]) { const list = await f.request('/peer-fundraisers', { session }); assert.equal(list.status, 200, list.text); assert.doesNotMatch(list.text, /PRIVATE_PEER_HISTORY_MARKER/); assert.equal((await f.detail(peer.id, session)).status, 404); }
  assert.equal((await f.detail(peer.id, f.sessions.helper)).status, 403);
  // A corrupted current flag must never erase the privacy of retained versions.
  f.db.prepare("UPDATE peer_fundraisers SET data=json_set(data,'$.visibility','Workspace') WHERE id=?").run(peer.id);
  for (const session of [f.sessions.staff, f.sessions.viewer]) assert.equal((await f.detail(peer.id, session)).status, 404);
  assert.equal((await f.detail(peer.id)).status, 200);
});

test('retained fundraiser sources and active gift associations protect deletion, merges and coordinator lifecycle', async t => {
  const f = await fixture(t), peer = await effort(f), linked = await f.attribute(peer); assert.equal(linked.status, 201, linked.text);
  for (const [collection, id] of [['constituents', f.fundraiser.id], ['constituents', f.donor.id], ['campaigns', f.campaign.id]]) assert.equal((await f.request('/records/' + collection + '/' + id, { method: 'DELETE', body: { version: 1 } })).status, 409);
  const merged = await f.request('/identity/merge/preview', { method: 'POST', body: { sourceId: f.fundraiser.id, targetId: f.second.id, sourceVersion: 1, targetVersion: 1, reason: 'Retained fundraiser identity cannot disappear' } }); assert.equal(merged.status, 409, merged.text);
  const campaignChanged = await f.request('/records/campaigns/' + f.campaign.id, { method: 'PATCH', body: { version: 1, type: 'Annual' } }); assert.equal(campaignChanged.status, 409, campaignChanged.text);
  const inactive = await f.request('/users/' + f.sessions.staff.user.id, { method: 'PATCH', body: { version: 1, role: 'staff', active: false } }); assert.equal(inactive.status, 200, inactive.text);
  const otherGift = await f.gift(), current = await f.detail(peer.id); assert.equal(current.status, 200); assert.equal(current.json.fundraiser.coordinatorAvailable, false); assert.equal(current.json.fundraiser.progress.postedCashCents, 10001);
  assert.equal((await f.attribute(current.json.fundraiser, { giftId: otherGift.id, giftVersion: 1 }, f.sessions.admin)).status, 409);
  const reassigned = await f.request('/peer-fundraisers/' + peer.id, { method: 'PATCH', body: { version: current.json.fundraiser.version, title: 'Peer effort reassigned', goalCents: 25000, visibility: 'Workspace', coordinatorId: f.sessions.other.user.id, coordinatorVersion: 1, reason: 'Assign an available replacement coordinator' } }); assert.equal(reassigned.status, 200, reassigned.text);
  const newLinked = await f.attribute(reassigned.json.fundraiser, { giftId: otherGift.id, giftVersion: 1 }, f.sessions.admin); assert.equal(newLinked.status, 201, newLinked.text); assert.equal(newLinked.json.fundraiser.progress.postedCashCents, 20002);
});

test('two independent native SQLite writers cannot attribute the same actual gift to competing efforts', async t => {
  const f = await fixture(t), first = await effort(f), second = await effort(f, { constituentId: f.second.id, constituentVersion: 1, title: 'Competing peer effort' }), finance = f.financial();
  const code = `const {parentPort,workerData}=require('node:worker_threads');(async()=>{const {createApp}=await import(workerData.appUrl);const app=createApp({dbPath:workerData.dbPath,seed:false,tenantId:workerData.tenantId,initialAdmin:workerData.initialAdmin,workflowWorker:false,reminderWorker:false});app.locals.db.exec('PRAGMA busy_timeout=5000');const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port+'/api';const auth=await fetch(base+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:workerData.initialAdmin.email,password:workerData.initialAdmin.password})});const session=await auth.json(),cookie=auth.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ');if(auth.status!==200)throw Error('Synthetic worker sign-in failed');parentPort.postMessage({ready:true});parentPort.once('message',async()=>{try{const response=await fetch(base+'/peer-fundraisers/'+workerData.peer.id+'/attributions',{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie,'X-CSRF-Token':session.csrfToken},body:JSON.stringify({version:workerData.peer.version,giftId:workerData.giftId,giftVersion:1,campaignVersion:1,coordinatorVersion:1,reason:'Simultaneous reviewed native source attribution'})});const result={status:response.status,json:await response.json()};await new Promise(r=>server.close(r));app.locals.close();parentPort.postMessage({result});}catch(error){server.close();app.locals.close();parentPort.postMessage({error:error.message});}});})().catch(error=>parentPort.postMessage({error:error.message}));`;
  async function start(peer) { const worker = new Worker(code, { eval: true, workerData: { appUrl: new URL('../server/app.js', import.meta.url).href, dbPath: f.dbPath, tenantId: f.tenantId, initialAdmin: f.initialAdmin, peer, giftId: f.originalGift.id } }); t.after(() => worker.terminate()); await new Promise((resolve, reject) => { worker.once('error', reject); worker.once('message', message => message.ready ? resolve() : reject(Error(message.error))); }); return worker; }
  const workers = [await start(first), await start(second)], responses = workers.map(worker => new Promise((resolve, reject) => { worker.once('error', reject); worker.once('message', message => message.error ? reject(Error(message.error)) : resolve(message.result)); })); for (const worker of workers) worker.postMessage('attribute'); const results = await Promise.all(responses); assert.deepEqual(results.map(r => r.status).sort(), [201, 409], JSON.stringify(results));
  assert.equal(f.db.prepare("SELECT count(*) n FROM peer_gift_attributions WHERE status='Active'").get().n, 1); assert.equal(f.db.prepare('SELECT count(*) n FROM peer_gift_attribution_history').get().n, 1); const a = await f.detail(first.id), b = await f.detail(second.id); assert.equal(a.json.fundraiser.progress.postedCashCents + b.json.fundraiser.progress.postedCashCents, 10001); assert.deepEqual(f.financial(), finance);
});

test('encrypted backup restores exact peer ownership and attribution history into a new native workspace path', async t => {
  const f = await fixture(t), peer = await effort(f), linked = await f.attribute(peer); assert.equal(linked.status, 201, linked.text); const before = f.snapshot(true), finance = f.financial(), oldSession = f.sessions.staff;
  const archivePath = join(f.dir, 'peer.backup'), destinationPath = join(f.dir, 'new-native-workspace.sqlite'), encryptionKey = randomBytes(32).toString('base64'); const backup = await backupWorkspace({ db: f.db, outputPath: archivePath, tenantId: f.tenantId, encryptionKey }); assert.ok(backup.tables.some(table => table.name === 'peer_gift_attribution_history'));
  const restored = await restoreWorkspace({ archivePath, destinationPath, expectedTenantId: f.tenantId, encryptionKey }); assert.ok(restored.cleared.sessions > 0); const copy = new DatabaseSync(destinationPath); try { for (const [table, rows] of Object.entries(before)) assert.deepEqual(copy.prepare('SELECT * FROM ' + table + ' ORDER BY rowid').all(), rows, table); assert.equal(copy.prepare('SELECT count(*) n FROM sessions').get().n, 0); assert.throws(() => copy.exec('DELETE FROM peer_gift_attribution_history'), /retained|immutable/); } finally { copy.close(); }
  await f.close(); await f.open(destinationPath); assert.equal((await f.detail(peer.id, oldSession)).status, 401); f.sessions.staff = await f.login('staff.peer@example.test'); const current = await f.detail(peer.id, f.sessions.staff); assert.equal(current.status, 200, current.text); assert.equal(current.json.fundraiser.progress.postedCashCents, 10001); assert.equal((await f.attribute(current.json.fundraiser)).status, 409); assert.deepEqual(f.financial(), finance);
});

test('foreign native workspace identifiers never disclose or mutate another tenant peer lineage', async t => {
  const local = await fixture(t), foreign = await fixture(t), peer = await effort(local), otherPeer = await effort(foreign), before = local.snapshot(); assert.equal((await local.detail(otherPeer.id)).status, 404); assert.equal((await local.attribute(peer, { giftId: foreign.originalGift.id, giftVersion: 1 })).status, 404); assert.deepEqual(local.snapshot(), before); assert.equal(foreign.db.prepare('SELECT count(*) n FROM peer_gift_attributions').get().n, 0);
});

test('source and whole native row corruption, audit failure and deferred COMMIT leave no false attribution or progress', async t => {
  const f = await fixture(t), peer = await effort(f), before = f.snapshot(true);
  const faults = [
    "CREATE TRIGGER synthetic_peer_fault AFTER INSERT ON peer_gift_attributions BEGIN UPDATE peer_gift_attributions SET status='Unlinked',unlinked_by='unapproved' WHERE id=NEW.id; END",
    "CREATE TRIGGER synthetic_peer_fault AFTER INSERT ON audit WHEN NEW.action='attribute_peer_gift' BEGIN UPDATE records SET data=json_set(data,'$.amount',10002,'$.allocations[0].amount',10002) WHERE collection='gifts'; END",
    "CREATE TRIGGER synthetic_peer_fault AFTER INSERT ON audit WHEN NEW.action='attribute_peer_gift' BEGIN UPDATE peer_fundraisers SET data=json_set(data,'$.title','Wrong persisted effort') WHERE id='" + peer.id + "'; END",
    "CREATE TRIGGER synthetic_peer_fault BEFORE INSERT ON audit WHEN NEW.action='attribute_peer_gift' BEGIN SELECT RAISE(ABORT,'Synthetic peer audit unavailable'); END",
  ];
  for (const fault of faults) { f.db.exec(fault); const r = await f.attribute(peer); assert.ok([409, 500, 503].includes(r.status), r.text); assert.deepEqual(f.snapshot(true), before); assert.equal((await f.detail(peer.id)).json.fundraiser.progress.postedCashCents, 0); f.db.exec('DROP TRIGGER synthetic_peer_fault'); }
  f.db.exec("CREATE TABLE synthetic_peer_commit_fault(owner_id TEXT REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED); CREATE TRIGGER synthetic_peer_fault AFTER INSERT ON peer_gift_attribution_history BEGIN INSERT INTO synthetic_peer_commit_fault VALUES('missing-native-owner'); END");
  const failed = await f.attribute(peer); assert.equal(failed.status, 500, failed.text); assert.deepEqual(f.snapshot(true), before); assert.equal(f.db.prepare('SELECT count(*) n FROM synthetic_peer_commit_fault').get().n, 0); f.db.exec('DROP TRIGGER synthetic_peer_fault'); assert.equal((await f.attribute(peer)).status, 201);
});

test('malformed native financial sources cannot gain peer attribution merely because their amounts sum', async t => {
  const f = await fixture(t), peer = await effort(f), original = f.row('gifts', f.originalGift.id);
  const changes = [{ method: 'Crypto' }, { allocations: [{ designationId: f.fund.id, amount: 5000 }, { designationId: f.fund.id, amount: 5001 }] }, { allocations: [{ designationId: randomUUID(), amount: 10001 }] }, { amount: 1000000000001, allocations: [{ designationId: f.fund.id, amount: 1000000000001 }] }];
  for (const change of changes) { f.db.prepare("UPDATE records SET data=? WHERE collection='gifts' AND id=?").run(JSON.stringify({ ...original, ...change }), original.id); const before = f.snapshot(true); const result = await f.attribute(peer); assert.ok([400, 409, 503].includes(result.status), 'Corrupt native source accepted: ' + result.text); assert.deepEqual(f.snapshot(true), before); }
});

test('shared financial boundaries protect legacy pledge facts, permit equivalent allocation order and retain soft-credit identity after unlink', async t => {
  const f = await fixture(t), otherFund = await f.create('designations', { name: 'Second split fund', accountCode: 'PEER-102' }), split = await f.gift({ allocations: [{ designationId: f.fund.id, amount: 5000 }, { designationId: otherFund.id, amount: 5001 }] }), peer = await effort(f), linked = await f.attribute(peer, { giftId: split.id, giftVersion: 1 }); assert.equal(linked.status, 201, linked.text);
  const pledge = await f.request('/records/gifts/' + split.id, { method: 'PATCH', body: { version: 1, pledge: 'Changed legacy pledge fact', correctionReason: 'Review changed native financial fact' } }); assert.equal(pledge.status, 409, pledge.text); assert.match(pledge.text, /peer/i);
  const reorder = await f.request('/records/gifts/' + split.id, { method: 'PATCH', body: { version: 1, allocations: [...split.allocations].reverse() } }); assert.equal(reorder.status, 200, reorder.text); const current = await f.detail(peer.id); assert.equal(current.json.fundraiser.progress.postedCashCents, 10001); assert.equal(current.json.fundraiser.progress.sourceChangedCount, 1); assert.equal(f.db.prepare('SELECT count(*) n FROM gift_financial_corrections').get().n, 0);
  const unlinked = await f.request('/peer-fundraisers/' + peer.id + '/attributions/' + linked.json.attribution.id + '/unlink', { method: 'POST', body: { version: current.json.fundraiser.version, attributionVersion: 1, giftVersion: 2, reason: 'Retain original soft-credit lineage after controlled unlink' } }); assert.equal(unlinked.status, 200, unlinked.text);
  const merge = await f.request('/identity/merge/preview', { method: 'POST', body: { sourceId: f.softCredit.id, targetId: f.second.id, sourceVersion: 1, targetVersion: 1, reason: 'Retained soft-credit identity cannot be merged away' } }); assert.equal(merge.status, 409, merge.text); assert.match(merge.text, /peer/i);
  const replacement = await f.request('/records/constituents/' + f.softCredit.id, { method: 'PATCH', body: { version: 1, type: 'Business' } }); assert.equal(replacement.status, 409, replacement.text); assert.match(replacement.text, /peer/i);
  const deleted = await f.request('/records/constituents/' + f.softCredit.id, { method: 'DELETE', body: { version: 1 } }); assert.equal(deleted.status, 409, deleted.text); assert.match(deleted.text, /peer/i); assert.equal(f.row('constituents', f.softCredit.id).type, 'Individual');
});

test('native merge transaction catches a valid peer reference arriving after the early HTTP guard and preserves canonical identities', async t => {
  const f = await fixture(t), source = await f.create('constituents', { name: 'Previously unreferenced merge source', type: 'Individual', email: 'late.source@example.test' }), target = await f.create('constituents', { name: 'Previously unreferenced merge target', type: 'Individual', email: 'late.target@example.test' }), input = { sourceId: source.id, targetId: target.id, sourceVersion: 1, targetVersion: 1, reason: 'Reviewed duplicate identity before a new peer reference arrives' };
  const preview = await f.request('/identity/merge/preview', { method: 'POST', body: input }); assert.equal(preview.status, 200, preview.text); assert.deepEqual(preview.json.preview.blockers, []);
  const canonicalState = () => ({ records: f.db.prepare('SELECT * FROM records ORDER BY collection,id').all(), aliases: f.db.prepare('SELECT * FROM identity_aliases ORDER BY source_id').all(), audit: f.db.prepare('SELECT * FROM audit ORDER BY rowid').all() }); const before = canonicalState();
  const service = f.app.locals.peerFundraising, original = service.hasConstituentReferences, at = new Date().toISOString(), pid = randomUUID(), body = { campaignId: f.campaign.id, constituentId: source.id, coordinatorId: f.sessions.staff.user.id, title: 'Valid late-arriving peer source reference', goalCents: 0, visibility: 'Workspace', status: 'Active' }, record = { ...body, id: pid, version: 1, createdAt: at, updatedAt: at };
  const canonical = value => value && typeof value === 'object' ? Array.isArray(value) ? '[' + value.map(canonical).join(',') + ']' : '{' + Object.keys(value).sort().map(key => JSON.stringify(key) + ':' + canonical(value[key])).join(',') + '}' : JSON.stringify(value), digest = value => createHash('sha256').update(canonical(value)).digest('hex');
  const owner = f.db.prepare('SELECT id,name,role,active,version FROM users WHERE id=?').get(f.sessions.staff.user.id), refs = [{ collection: 'campaigns', id: f.campaign.id, version: 1, digest: digest(f.row('campaigns', f.campaign.id)) }, { collection: 'constituents', id: source.id, version: 1, digest: digest(source) }, { collection: 'users', id: owner.id, version: owner.version, digest: digest(owner) }]; let injected = false, lateChecks = 0;
  service.hasConstituentReferences = id => { if (id === source.id && !injected) { assert.equal(f.db.isTransaction, false, 'Fault is inserted between early HTTP check and native BEGIN'); assert.equal(original(id), false); f.db.prepare('INSERT INTO peer_fundraisers VALUES(?,?,?,?,?)').run(pid, 1, JSON.stringify(body), at, at); f.db.prepare('INSERT INTO peer_fundraiser_versions VALUES(?,?,?,?,?,?,?)').run(pid, 1, JSON.stringify(record), JSON.stringify(refs), owner.id, at, 'Synthetic valid external writer before merge transaction'); injected = true; return false; } if (id === source.id && injected) lateChecks++; return original(id); };
  let result; try { result = await f.request('/identity/merge', { method: 'POST', body: { ...input, previewDigest: preview.json.preview.previewDigest } }); } finally { service.hasConstituentReferences = original; }
  assert.equal(injected, true); assert.ok(lateChecks >= 1, 'Protected history is checked again inside native merge'); assert.equal(result.status, 409, result.text); assert.deepEqual(canonicalState(), before); assert.equal((await f.detail(pid)).status, 200, 'Valid new external peer relation remains retained'); assert.equal(f.row('constituents', source.id).mergedInto, undefined); assert.equal(f.row('constituents', target.id).version, 1);
});
