import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import * as lib from '../src/lib.js';
function harness(){let index=0,state=[],effects=[],keys=[],cleanups=[];const mock={...React,useState(initial){const i=index++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return[state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){return state[index++]??=({current:initial});},useEffect(effect,deps){const i=index++;if(!keys[i]||!deps||deps.some((d,j)=>d!==keys[i][j])){keys[i]=deps;effects.push(()=>{cleanups[i]?.();cleanups[i]=effect();});}}};const module={exports:{}},require=id=>id==='react'?mock:id.includes('lib')?lib:new Proxy({},{get:()=>()=>null});new Function('React','require','module','exports',transformSync(readFileSync(new URL('../src/features/PeerFundraising.jsx',import.meta.url),'utf8'),{loader:'jsx',format:'cjs'}).code)(React,require,module,module.exports);const render=props=>{index=0;const tree=module.exports.default(props),pending=effects;effects=[];pending.forEach(e=>e());return tree;};render.unmount=()=>cleanups.forEach(c=>c?.());return render;}
function find(tree,p){if(!tree||typeof tree!=='object')return null;if(p(tree))return tree;for(const c of React.Children.toArray(tree.props?.children)){const result=find(c,p);if(result)return result;}return null;}
const text=e=>React.Children.toArray(e.props.children).filter(c=>typeof c==='string').join(''),button=(tree,label)=>find(tree,e=>e.type==='button'&&text(e)===label),field=(tree,label)=>find(find(tree,e=>e.type==='label'&&text(e)===label),e=>['input','select','textarea'].includes(e.type)),flush=async()=>{for(let i=0;i<16;i++)await Promise.resolve();};
const campaign={id:'c1',version:4,name:'Community introductions',type:'Peer-to-peer',status:'Active'},person={id:'p1',version:2,name:'Fundraiser Alex',type:'Business'},donor={id:'p2',version:1,name:'Actual donor'},owner={id:'u1',version:5,name:'Staff coordinator',role:'staff'},gift={id:'g1',version:3,constituentId:'p2',campaignId:'c1',amount:10001,date:lib.today(),status:'Posted',type:'Cash',method:'Check',giftKind:'One-time',allocations:[{designationId:'d1',amount:10001}]};
const fundraiser={id:'f1',version:1,title:'Alex community plan',campaignId:'c1',campaignVersion:4,campaignName:campaign.name,campaignStatus:'Active',constituentId:'p1',constituentVersion:2,fundraiserName:person.name,coordinatorId:'u1',coordinatorVersion:5,coordinatorName:owner.name,coordinatorAvailable:true,goalCents:250000,visibility:'Workspace',status:'Active',progress:{postedCashCents:10001,attributedGiftCount:1,unlinkedCount:0,voidedGiftCount:0,sourceChangedCount:0,asOf:lib.today()}},attribution={id:'a1',version:1,fundraiserId:'f1',giftId:'g1',status:'Active',giftVersion:3,originalSource:{donorId:'p2',amountCents:10001,campaignId:'c1',date:gift.date,type:'Cash',method:'Check',giftKind:'One-time',status:'Posted'},currentSource:{giftVersion:3,donorId:'p2',donorName:'Actual donor',amountCents:10001,date:gift.date,status:'Posted',sourceCurrent:true,compatible:true}};
const details=(extra={})=>({fundraiser,attributions:[],nextCursor:null,attributionCount:0,revisions:[],revisionCount:1,history:[{id:'h1',action:'Created',reason:'Initial plan',actor:{name:'Staff coordinator'},at:'2026-09-13T12:00:00.000Z',version:1}],historyCount:1,historyLimit:100,...extra});
async function ready({list=[],detail=details(),api:custom,...extra}={}){const calls=[],render=harness(),props={user:{id:'u1',role:'staff'},data:{campaigns:[campaign,{id:'c2',type:'Annual',status:'Active',name:'Annual campaign'}],constituents:[person,donor],gifts:[gift],taskOwners:[owner]},onDirty:()=>{},api:async(path,o)=>{calls.push([path,o]);return custom?custom(path,o):o?{fundraiser}:path.startsWith('/peer-fundraisers?')?{fundraisers:list,nextCursor:null}:detail;},...extra};render(props);await flush();return{calls,render,props,tree:render(props)};}
async function fill(s){for(const[label,value]of [['Plan title','New champion plan'],['Peer-to-peer campaign','c1'],['Fundraiser constituent','p1'],['Staff coordinator','u1'],['Fundraiser goal · USD','2500.01']])field(s.render(s.props),label).props.onChange({target:{value}});}
function confirm(tree){find(tree,e=>e.type==='input'&&e.props.type==='checkbox').props.onChange({target:{checked:true}});}
async function select(s){await button(s.render(s.props),'Alex community plan').props.onClick();await flush();return s.render(s.props);}
const submit=tree=>find(tree,e=>e.type==='form').props.onSubmit({preventDefault(){}});

test('a plan requires reviewed existing source versions and explicit confirmation; double submission posts once',async()=>{
 const s=await ready();await fill(s);let tree=s.render(s.props);assert.ok(button(tree,'Save fundraiser plan').props.disabled);assert.equal(find(tree,e=>e.type==='option'&&e.props.value==='c2'),null);button(tree,'Review fundraiser plan').props.onClick();tree=s.render(s.props);confirm(tree);tree=s.render(s.props);assert.equal(Boolean(button(tree,'Save fundraiser plan').props.disabled),false);await Promise.all([submit(tree),submit(tree)]);const posts=s.calls.filter(([,o])=>o?.method==='POST');assert.equal(posts.length,1);assert.deepEqual(posts[0][1].body,{campaignId:'c1',campaignVersion:4,constituentId:'p1',constituentVersion:2,coordinatorId:'u1',coordinatorVersion:5,title:'New champion plan',goalCents:250001,visibility:'Workspace'});assert.match(renderToStaticMarkup(s.render(s.props)),/No gift or payment was created/);
});

test('stable relevant arrays preserve review on ordinary parent rerenders, changed source versions invalidate it',async()=>{
 const s=await ready();await fill(s);button(s.render(s.props),'Review fundraiser plan').props.onClick();confirm(s.render(s.props));s.props.data={...s.props.data,events:[]};let tree=s.render(s.props);assert.equal(Boolean(button(tree,'Save fundraiser plan').props.disabled),false);s.props.data={...s.props.data,campaigns:[{...campaign,version:5}]};s.render(s.props);tree=s.render(s.props);assert.ok(button(tree,'Save fundraiser plan').props.disabled);assert.match(renderToStaticMarkup(tree),/Source records changed/);assert.equal(s.calls.filter(([,o])=>o).length,0);
});

test('native receipt attribution preserves actual donor, exact gift versions and reason; incompatible candidates are omitted',async()=>{
 const s=await ready({list:[fundraiser]});s.props.data={...s.props.data,gifts:[gift,{...gift,id:'future',date:'2099-01-01'},{...gift,id:'void',status:'Voided'},{...gift,id:'fee',type:'Fee payment'},{...gift,id:'planned',giftKind:'Planned gift'},{...gift,id:'pledge',pledgeId:'p9'},{...gift,id:'wrong-campaign',campaignId:'c2'}]};let tree=await select(s);field(tree,'Candidate existing gift').props.onChange({target:{value:'g1'}});field(s.render(s.props),'Reason for fundraiser attribution').props.onChange({target:{value:'Fundraiser introduced this donor'}});tree=s.render(s.props);confirm(tree);tree=s.render(s.props);assert.match(renderToStaticMarkup(tree),/Actual donor/);assert.match(renderToStaticMarkup(tree),/Fundraiser Alex/);for(const id of ['future','void','fee','planned','pledge','wrong-campaign'])assert.equal(find(tree,e=>e.type==='option'&&e.props.value===id),null);await submit(tree);const posted=s.calls.find(([path,o])=>path.endsWith('/attributions')&&o?.method==='POST');assert.deepEqual(posted[1].body,{version:1,giftId:'g1',giftVersion:3,campaignVersion:4,coordinatorVersion:5,reason:'Fundraiser introduced this donor'});assert.match(renderToStaticMarkup(s.render(s.props)),/received income were unchanged/);
});

test('unconfirmed writes block replay and retain inputs until explicit saved-history reload',async()=>{
 const s=await ready({list:[fundraiser],api:async(path,o)=>{if(o)throw new Error('Connection ended after write');return path.startsWith('/peer-fundraisers?')?{fundraisers:[fundraiser],nextCursor:null}:details();}});let tree=await select(s);field(tree,'Candidate existing gift').props.onChange({target:{value:'g1'}});field(s.render(s.props),'Reason for fundraiser attribution').props.onChange({target:{value:'Verified referral'}});confirm(s.render(s.props));await submit(s.render(s.props));tree=s.render(s.props);assert.match(renderToStaticMarkup(tree),/response was not confirmed/);assert.equal(field(tree,'Reason for fundraiser attribution').props.value,'Verified referral');assert.ok(button(tree,'Attribute existing gift').props.disabled);assert.equal(s.calls.filter(([,o])=>o?.method==='POST').length,1);await flush();assert.equal(s.calls.filter(([,o])=>o?.method==='POST').length,1);await button(tree,'Discard inputs and reload saved history').props.onClick();await flush();tree=s.render(s.props);assert.equal(field(tree,'Reason for fundraiser attribution').props.value,'');assert.equal(s.calls.filter(([,o])=>o?.method==='POST').length,1);
});

test('viewers read retained workspace history without write controls; helpers request nothing and private plans stay omitted',async()=>{
 const s=await ready({user:{role:'viewer'},list:[fundraiser,{...fundraiser,id:'private',title:'PRIVATE_PLAN',visibility:'Administrators'}]});assert.doesNotMatch(renderToStaticMarkup(s.tree),/PRIVATE_PLAN|Create fundraiser plan/);const tree=await select(s);assert.equal(find(tree,e=>e.type==='form'),null);assert.match(renderToStaticMarkup(tree),/Actual donors stay/);assert.match(renderToStaticMarkup(tree),/Staff coordinator/);assert.equal(button(tree,'Retire with reason'),null);const helper=await ready({user:{role:'event-helper'}});assert.deepEqual(helper.calls,[]);assert.match(renderToStaticMarkup(helper.tree),/cannot access fundraiser plans/);
});

test('late detail reads cannot replace the current corpus and unmounted reads never publish state',async()=>{
 let resolve;const s=await ready({list:[fundraiser],api:async path=>path.startsWith('/peer-fundraisers?')?{fundraisers:[fundraiser],nextCursor:null}:new Promise(r=>resolve=r)});const pending=button(s.tree,'Alex community plan').props.onClick();s.props.data={...s.props.data,gifts:[{...gift,version:4}]};s.render(s.props);resolve(details());await pending;assert.equal(find(s.render(s.props),e=>e.type==='h2'&&e.props.children==='Attributed source gifts'),null);
 const q=await ready({list:[fundraiser],api:async path=>path.startsWith('/peer-fundraisers?')?{fundraisers:[fundraiser],nextCursor:null}:new Promise(r=>resolve=r)});const unmounted=button(q.tree,'Alex community plan').props.onClick();q.render.unmount();resolve(details());await unmounted;assert.equal(q.calls.filter(([,o])=>o).length,0);
});

test('unlinking and retirement require separate reviewed reasons and preserve immutable financial sources',async()=>{
 const s=await ready({list:[fundraiser],detail:details({attributions:[attribution],attributionCount:1})});let tree=await select(s);button(tree,'Unlink with reason').props.onClick();tree=s.render(s.props);assert.ok(button(tree,'Unlink and retain history').props.disabled);field(tree,'Reason for unlinking').props.onChange({target:{value:'Referral incorrectly assigned'}});confirm(s.render(s.props));await submit(s.render(s.props));const unlink=s.calls.find(([p,o])=>p.endsWith('/unlink')&&o);assert.deepEqual(unlink[1].body,{version:1,attributionVersion:1,giftVersion:3,reason:'Referral incorrectly assigned'});tree=s.render(s.props);button(tree,'Retire with reason').props.onClick();field(s.render(s.props),'Reason for retirement').props.onChange({target:{value:'Fundraiser completed this effort'}});confirm(s.render(s.props));await submit(s.render(s.props));const retired=s.calls.find(([p,o])=>p.endsWith('/retire')&&o);assert.deepEqual(retired[1].body,{version:1,reason:'Fundraiser completed this effort'});
});

test('a changed saved fundraiser between attribution pages blocks mixed-version history',async()=>{
 const s=await ready({list:[fundraiser],api:async path=>path.startsWith('/peer-fundraisers?')?{fundraisers:[fundraiser],nextCursor:null}:path.includes('after=')?details({fundraiser:{...fundraiser,version:2},attributions:[{...attribution,id:'a2'}],nextCursor:null}):details({attributions:[attribution],nextCursor:'a1',attributionCount:2})});let tree=await select(s);await button(tree,'Load more source gifts').props.onClick();tree=s.render(s.props);assert.match(renderToStaticMarkup(tree),/changed between pages/);assert.doesNotMatch(renderToStaticMarkup(tree),/a2/);
});

test('reasoned revisions keep identities fixed, show exact saved source chronology and send the captured fundraiser version',async()=>{
 const s=await ready({list:[fundraiser],detail:details({revisions:[{...fundraiser,version:1,reason:'Created internal fundraiser',at:'2026-09-13T12:00:00.000Z',sourceVersions:[{collection:'campaigns',id:'c1',version:4}]}],history:[],historyCount:0})});let tree=await select(s);assert.match(renderToStaticMarkup(tree),/campaigns c1 v4/);button(tree,'Revise plan').props.onClick();tree=s.render(s.props);assert.equal(field(tree,'Peer-to-peer campaign').props.disabled,true);assert.equal(field(tree,'Fundraiser constituent').props.disabled,true);field(tree,'Plan title').props.onChange({target:{value:'Revised champion plan'}});field(s.render(s.props),'Reason for plan revision').props.onChange({target:{value:'Revised the agreed goal wording'}});button(s.render(s.props),'Review fundraiser plan').props.onClick();confirm(s.render(s.props));await submit(s.render(s.props));const patch=s.calls.find(([,o])=>o?.method==='PATCH');assert.deepEqual(patch[1].body,{version:1,title:'Revised champion plan',goalCents:250000,visibility:'Workspace',coordinatorId:'u1',coordinatorVersion:5,reason:'Revised the agreed goal wording'});
});

test('a lost detail permission removes retained content and private state cannot survive a role downgrade',async()=>{
 const privatePlan={...fundraiser,visibility:'Administrators',title:'PRIVATE_PLAN_HISTORY'};let deny=false;const s=await ready({user:{id:'admin1',role:'admin'},list:[privatePlan],api:async path=>{if(path.startsWith('/peer-fundraisers?'))return{fundraisers:[privatePlan],nextCursor:null};if(deny)throw Object.assign(new Error('Fundraiser not found'),{status:404});return details({fundraiser:privatePlan});}});await button(s.tree,'PRIVATE_PLAN_HISTORY').props.onClick();let tree=s.render(s.props);assert.match(renderToStaticMarkup(tree),/PRIVATE_PLAN_HISTORY/);deny=true;await button(tree,'Refresh saved history').props.onClick();tree=s.render(s.props);assert.doesNotMatch(renderToStaticMarkup(tree),/PRIVATE_PLAN_HISTORY/);
 const q=await ready({user:{id:'admin1',role:'admin'},list:[privatePlan],detail:details({fundraiser:privatePlan})});await button(q.tree,'PRIVATE_PLAN_HISTORY').props.onClick();q.props.user={id:'admin1',role:'viewer'};tree=q.render(q.props);assert.doesNotMatch(renderToStaticMarkup(tree),/PRIVATE_PLAN_HISTORY/);
});

test('opening a source gift passes its current saved revision so the parent can refresh a stale native record',async()=>{
 const opened=[],s=await ready({list:[fundraiser],detail:details({attributions:[{...attribution,currentSource:{...attribution.currentSource,giftVersion:4,sourceCurrent:false}}],attributionCount:1}),onOpen:async(...args)=>opened.push(args)});const tree=await select(s);await button(tree,'Actual donor').props.onClick();await flush();assert.deepEqual(opened,[['gifts','g1',4]]);assert.equal(s.calls.filter(([,o])=>o).length,0);
});

test('a changed request identity loads its own register while an older read is pending and rejects the older response',async()=>{
 let resolve;const s=await ready({list:[fundraiser],api:async path=>path.startsWith('/peer-fundraisers?')?{fundraisers:[fundraiser],nextCursor:null}:new Promise(r=>resolve=r)});const old=button(s.tree,'Alex community plan').props.onClick();s.props.api=async()=>({fundraisers:[{...fundraiser,id:'f2',title:'New session plan'}],nextCursor:null});s.render(s.props);await flush();let tree=s.render(s.props);assert.match(renderToStaticMarkup(tree),/New session plan/);resolve(details());await old;tree=s.render(s.props);assert.doesNotMatch(renderToStaticMarkup(tree),/Alex community plan|Attributed source gifts/);assert.equal(button(tree,'Refresh saved history').props.disabled,false);
});

test('a confirmed mutation with failed history refresh shows unknown counts and never claims retained history is empty',async()=>{
 let saved=false;const s=await ready({list:[fundraiser],api:async(path,o)=>{if(o){saved=true;return{fundraiser:{...fundraiser,version:2}};}if(path.startsWith('/peer-fundraisers?'))return{fundraisers:[fundraiser],nextCursor:null};if(saved)throw new Error('History temporarily unavailable');return details();}});let tree=await select(s);field(tree,'Candidate existing gift').props.onChange({target:{value:'g1'}});field(s.render(s.props),'Reason for fundraiser attribution').props.onChange({target:{value:'Reviewed referral'}});confirm(s.render(s.props));await submit(s.render(s.props));tree=s.render(s.props);const html=renderToStaticMarkup(tree);assert.match(html,/Your change was saved, but history could not refresh/);assert.match(html,/Reload saved history to verify counts/);assert.match(html,/Saved history awaiting refresh/);assert.doesNotMatch(html,/0 of 0|0 retained|No source gifts are attributed|No action history returned/);assert.equal(s.calls.filter(([,o])=>o?.method==='POST').length,1);assert.ok(button(tree,'Attribute existing gift').props.disabled);
});

test('workspace source refresh reloads once from clean state and is blocked while plan inputs are unsaved',async()=>{
 let reloads=0;const s=await ready({onRefreshSources:()=>reloads++});let tree=s.render(s.props);assert.equal(button(tree,'Refresh workspace sources').props.disabled,false);button(tree,'Refresh workspace sources').props.onClick();assert.equal(reloads,1);field(tree,'Plan title').props.onChange({target:{value:'Unsaved plan'}});tree=s.render(s.props);assert.equal(button(tree,'Refresh workspace sources').props.disabled,true);button(tree,'Refresh workspace sources').props.onClick();assert.equal(reloads,1);button(tree,'Cancel plan inputs').props.onClick();tree=s.render(s.props);assert.equal(button(tree,'Refresh workspace sources').props.disabled,false);assert.equal(s.calls.filter(([,o])=>o).length,0);
});

test('a successful own-create followed by fresh identical workspace arrays leaves attribution usable without a source-change warning',async()=>{
 let savedVersion=0;const s=await ready({api:async(path,o)=>{if(o){savedVersion++;return{fundraiser:{...fundraiser,version:savedVersion}};}if(path.startsWith('/peer-fundraisers?'))return{fundraisers:savedVersion?[{...fundraiser,version:savedVersion}]:[],nextCursor:null};return details({fundraiser:{...fundraiser,version:savedVersion},attributions:savedVersion>=2?[attribution]:[],attributionCount:savedVersion>=2?1:0});}});s.props.onCommitted=async()=>{s.props.data=JSON.parse(JSON.stringify(s.props.data));s.render(s.props);};await fill(s);button(s.render(s.props),'Review fundraiser plan').props.onClick();confirm(s.render(s.props));await submit(s.render(s.props));await flush();let tree=s.render(s.props);assert.doesNotMatch(renderToStaticMarkup(tree),/Source records changed|Discard inputs and reload saved history/);assert.equal(field(tree,'Candidate existing gift').props.disabled,undefined);assert.equal(find(tree,e=>e.type==='fieldset').props.disabled,false);assert.equal(button(tree,'Revise plan').props.disabled,false);field(tree,'Candidate existing gift').props.onChange({target:{value:'g1'}});field(s.render(s.props),'Reason for fundraiser attribution').props.onChange({target:{value:'Reviewed new-plan referral'}});confirm(s.render(s.props));tree=s.render(s.props);assert.equal(button(tree,'Attribute existing gift').props.disabled,false);await submit(tree);await flush();tree=s.render(s.props);assert.doesNotMatch(renderToStaticMarkup(tree),/Source records changed/);assert.equal(button(tree,'Unlink with reason').props.disabled,false);assert.equal(button(tree,'Retire with reason').props.disabled,false);assert.equal(savedVersion,2);
 s.props.data={...s.props.data,gifts:[{...gift,version:4}]};s.render(s.props);tree=s.render(s.props);assert.match(renderToStaticMarkup(tree),/Source records changed/);assert.equal(button(tree,'Unlink with reason').props.disabled,true);
});
