import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {createApp} from '../server/app.js';
async function fixture(t){const app=createApp();const server=app.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{await new Promise(r=>server.close(r));app.locals.close();});const base='http://127.0.0.1:'+server.address().port;
 async function request(path,body,session,method=body?'POST':'GET',extra={}){const response=await fetch(base+'/api'+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrfToken}:{}),...extra},body:body?JSON.stringify(body):undefined});return {status:response.status,json:await response.json(),headers:response.headers};}
 async function login(prefix='alex'){const r=await request('/auth/login',{email:prefix+'@foundation.example',password:'FoundationDemo!2026'});assert.equal(r.status,200);return {...r.json,cookie:r.headers.get('set-cookie').split(';')[0]};}
 const admin=await login();const ws=(await request('/workspace',null,admin)).json;const people=ws.data.constituents.filter(c=>['Individual','Alumni','Employee'].includes(c.type));
 async function create(c,body){const r=await request('/records/'+c,body,admin);assert.equal(r.status,201,JSON.stringify(r.json));return r.json.record;}
 const patch=(c,r,changes)=>request('/records/'+c+'/'+r.id,{version:r.version,...changes},admin,'PATCH');
 return {app,request,login,admin,ws,people,create,patch};
}
const shift=(overrides={})=>({name:'Synthetic service shift',date:'2026-10-15',startTime:'09:00',endTime:'11:00',location:'Foundation venue',capacity:1,eventId:null,status:'Open',notes:'',...overrides});
const booking=(s,p,status='Reserved')=>({shiftId:s.id,constituentId:p.id,status,notes:''});
test('shift capacity is enforced atomically under concurrent reservation requests',async t=>{const f=await fixture(t);const s=await f.create('volunteerShifts',shift());const results=await Promise.all(f.people.slice(0,2).map(p=>f.request('/records/shiftReservations',booking(s,p),f.admin)));assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);const ws=(await f.request('/workspace',null,f.admin)).json;assert.equal(ws.data.shiftReservations.filter(r=>r.status==='Reserved').length,1);assert.equal(ws.audit.filter(a=>a.collection==='shiftReservations'&&a.action==='create').length,1);});
test('waitlists require explicit promotion and cancellation retains history and releases capacity',async t=>{const f=await fixture(t);const s=await f.create('volunteerShifts',shift());const first=await f.create('shiftReservations',booking(s,f.people[0]));const waiting=await f.create('shiftReservations',booking(s,f.people[1],'Waitlisted'));assert.equal((await f.patch('shiftReservations',waiting,{status:'Reserved'})).status,409);assert.equal((await f.patch('shiftReservations',first,{status:'Cancelled'})).status,200);let ws=(await f.request('/workspace',null,f.admin)).json;assert.equal(ws.data.shiftReservations.find(r=>r.id===waiting.id).status,'Waitlisted');assert.equal((await f.patch('shiftReservations',waiting,{status:'Reserved'})).status,200);assert.equal((await f.patch('shiftReservations',waiting,{status:'Cancelled'})).status,409);ws=(await f.request('/workspace',null,f.admin)).json;assert.equal(ws.data.shiftReservations.length,2);assert.equal(ws.data.shiftReservations.find(r=>r.id===first.id).status,'Cancelled');assert.equal(ws.data.volunteerTime.length,f.ws.data.volunteerTime.length);});
test('active duplicates and identity mutation are rejected including cancelled-history reactivation',async t=>{const f=await fixture(t);const s=await f.create('volunteerShifts',shift({capacity:3}));const r=await f.create('shiftReservations',booking(s,f.people[0]));assert.equal((await f.request('/records/shiftReservations',booking(s,f.people[0],'Waitlisted'),f.admin)).status,409);assert.equal((await f.patch('shiftReservations',r,{constituentId:f.people[1].id})).status,409);const cancelled=(await f.patch('shiftReservations',r,{status:'Cancelled'})).json.record;await f.create('shiftReservations',booking(s,f.people[0]));assert.equal((await f.patch('shiftReservations',cancelled,{status:'Reserved'})).status,409);assert.equal((await f.request('/records/shiftReservations/'+r.id,{version:cancelled.version},f.admin,'DELETE')).status,403);assert.equal((await f.request('/records/volunteerShifts/'+s.id,{version:s.version},f.admin,'DELETE')).status,409);});
test('reserved time conflicts reject overlaps while adjacent intervals and other dates work',async t=>{const f=await fixture(t);const a=await f.create('volunteerShifts',shift());const b=await f.create('volunteerShifts',shift({startTime:'10:30',endTime:'12:00'}));const c=await f.create('volunteerShifts',shift({startTime:'11:00',endTime:'12:00'}));await f.create('shiftReservations',booking(a,f.people[0]));assert.equal((await f.request('/records/shiftReservations',booking(b,f.people[0]),f.admin)).status,409);const wait=await f.create('shiftReservations',booking(b,f.people[0],'Waitlisted'));assert.equal((await f.patch('shiftReservations',wait,{status:'Reserved'})).status,409);await f.create('shiftReservations',booking(c,f.people[0]));const next=await f.create('volunteerShifts',shift({date:'2026-10-16'}));await f.create('shiftReservations',booking(next,f.people[0]));});
test('shift schedules, references, eligible people, closed booking and capacity edits preserve commitments',async t=>{const f=await fixture(t);for(const change of [{startTime:'11:00',endTime:'09:00'},{date:'2026-02-30'},{startTime:'25:00'},{capacity:0},{eventId:'missing'}])assert.equal((await f.request('/records/volunteerShifts',shift(change),f.admin)).status,400);const s=await f.create('volunteerShifts',shift({capacity:2}));await f.create('shiftReservations',booking(s,f.people[0]));await f.create('shiftReservations',booking(s,f.people[1]));assert.equal((await f.patch('volunteerShifts',s,{capacity:1})).status,409);assert.equal((await f.patch('volunteerShifts',s,{startTime:'08:00'})).status,409);const closed=(await f.patch('volunteerShifts',s,{status:'Closed'})).json.record;assert.equal((await f.request('/records/shiftReservations',booking(closed,f.people[2],'Waitlisted'),f.admin)).status,409);const org=f.ws.data.constituents.find(p=>p.type==='Business');assert.equal((await f.request('/records/shiftReservations',booking(closed,org),f.admin)).status,400);assert.equal((await f.request('/records/shiftReservations',{shiftId:'missing',constituentId:f.people[2].id,status:'Reserved'},f.admin)).status,400);});
test('reservation writes require role, CSRF and allowed origin; readiness is administrator-only',async t=>{const f=await fixture(t);const board=await f.login('board');const staff=await f.login('staff');const s=await f.create('volunteerShifts',shift());assert.equal((await f.request('/records/shiftReservations',booking(s,f.people[0]),board)).status,403);assert.equal((await f.request('/records/shiftReservations',booking(s,f.people[0]),f.admin,'POST',{'X-CSRF-Token':'invalid'})).status,403);assert.equal((await f.request('/records/shiftReservations',booking(s,f.people[0]),f.admin,'POST',{Origin:'https://untrusted.example'})).status,403);assert.equal((await f.request('/readiness',null,board)).status,403);assert.equal((await f.request('/readiness',null,staff)).status,403);assert.equal((await f.request('/readiness')).status,401);assert.equal((await f.request('/records/shiftReservations',booking(s,f.people[0]),staff)).status,201);});
test('readiness checks expose broken references without mutating records or audit and do not claim external approval',async t=>{const f=await fixture(t);const s=await f.create('volunteerShifts',shift());await f.create('shiftReservations',booking(s,f.people[0]));let r=await f.request('/readiness',null,f.admin);assert.equal(r.status,200);assert.ok(r.json.checks.every(c=>c.status==='Passed'),JSON.stringify(r.json));assert.match(r.json.scope,/no external/);const before=(await f.request('/workspace',null,f.admin)).json;f.app.locals.db.prepare('UPDATE records SET data=? WHERE collection=? AND id=?').run(JSON.stringify({...s,eventId:'missing'}),'volunteerShifts',s.id);r=await f.request('/readiness',null,f.admin);assert.equal(r.json.checks.find(c=>c.key==='records').status,'Needs review');assert.ok(r.json.checks.find(c=>c.key==='records').issues.some(i=>i.recordId===s.id));const after=(await f.request('/workspace',null,f.admin)).json;assert.equal(after.audit.length,before.audit.length);assert.equal(after.data.volunteerShifts[0].eventId,'missing');const backup=await f.request('/backup',null,f.admin);assert.equal(backup.json.data.shiftReservations.length,1);assert.ok(!JSON.stringify(r.json).includes('password_hash'));});

test('constituent classification remains eligible after reservation history, including cancellation',async t=>{const f=await fixture(t);const s=await f.create('volunteerShifts',shift());const p=f.people[0];const r=await f.create('shiftReservations',booking(s,p));await f.patch('shiftReservations',r,{status:'Cancelled'});assert.equal((await f.patch('constituents',p,{type:'Business'})).status,409);assert.equal((await f.patch('constituents',p,{type:'Alumni'})).status,200);});
test('readiness detects a volunteer hour mismatch against its dated and historical ledger',async t=>{const f=await fixture(t);const volunteer=f.ws.data.volunteers[0];f.app.locals.db.prepare('UPDATE records SET data=? WHERE collection=? AND id=?').run(JSON.stringify({...volunteer,hours:volunteer.hours+1}),'volunteers',volunteer.id);const r=await f.request('/readiness',null,f.admin);assert.equal(r.json.checks.find(c=>c.key==='time-ledger').status,'Needs review');assert.ok(r.json.checks.find(c=>c.key==='time-ledger').issues.some(i=>i.recordId===volunteer.id));});
