import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtemp,rm,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID,createCipheriv} from 'node:crypto';
import {inspectProductionReadiness,createHealthMonitoringProbe} from '../server/productionReadiness.js';

async function fixture(t){const durableRoot=await mkdtemp(join(tmpdir(),'wimblo-readiness-')),dbPath=join(durableRoot,'workspace.sqlite'),db=new DatabaseSync(dbPath);db.exec("CREATE TABLE users(id TEXT,email TEXT,role TEXT,active INTEGER); INSERT INTO users VALUES('admin','real@example.test','admin',1)");db.exec('CREATE TABLE mfa_settings(user_id TEXT,enabled INTEGER,encrypted_secret TEXT)');const nonce=Buffer.alloc(12,3),cipher=createCipheriv('aes-256-gcm',Buffer.from('1'.repeat(64),'hex'),nonce);cipher.setAAD(Buffer.from('wimblo-mfa-v1:admin'));const encoded=Buffer.concat([cipher.update('VALID_SYNTHETIC_SECRET'),cipher.final()]);db.prepare('INSERT INTO mfa_settings VALUES(?,?,?)').run('admin',1,['v1',nonce.toString('base64'),cipher.getAuthTag().toString('base64'),encoded.toString('base64')].join('.'));t.after(async()=>{db.close();await rm(durableRoot,{recursive:true,force:true});});const now=Date.now(),tenantId=randomUUID(),archiveSha256='a'.repeat(64),env={NODE_ENV:'production',APP_ORIGIN:'https://crm.example.test',MFA_ENCRYPTION_KEY:'1'.repeat(64),BACKUP_ENCRYPTION_KEY:'2'.repeat(64),PERSISTENT_STORAGE_CONFIRMED:'true'},recoveryEvidence={tenantId,backup:{tenantId,verified:true,offHost:true,archiveSha256,createdAt:new Date(now-1000).toISOString()},restore:{tenantId,verified:true,archiveSha256,restoredAt:new Date(now-1000).toISOString()},retention:{approved:true,backupDays:30}},monitoring={probe:async()=>({verified:true})};return {db,dbPath,durableRoot,expectedTenantId:tenantId,env,recoveryEvidence,monitoring,now};}
test('readiness passes exercised runtime evidence without leaking secrets, identities or storage paths',async t=>{const f=await fixture(t),result=await inspectProductionReadiness(f);assert.equal(result.ready,true);assert.doesNotMatch(JSON.stringify(result),/real@example|workspace.sqlite|wimblo-readiness/);for(const value of [f.env.MFA_ENCRYPTION_KEY,f.env.BACKUP_ENCRYPTION_KEY,f.durableRoot])assert.equal(JSON.stringify(result).includes(value),false);assert.deepEqual(await readdir(f.durableRoot),['workspace.sqlite']);});
test('configuration cannot substitute for off-host readback, matching restore drill or exercised monitoring',async t=>{const f=await fixture(t);for(const patch of [{recoveryEvidence:{}},{recoveryEvidence:{...f.recoveryEvidence,backup:{...f.recoveryEvidence.backup,offHost:false}}},{recoveryEvidence:{...f.recoveryEvidence,restore:{...f.recoveryEvidence.restore,archiveSha256:'b'.repeat(64)}}},{monitoring:{probe:async()=>{throw Error('SECRET_PROVIDER_FAILURE');}}}]){const result=await inspectProductionReadiness({...f,...patch});assert.equal(result.ready,false);assert.doesNotMatch(JSON.stringify(result),/SECRET_PROVIDER_FAILURE/);}});
test('expired, future, wrong-tenant recovery evidence and equivalent differently encoded encryption keys are blocked',async t=>{const f=await fixture(t);for(const backup of [{...f.recoveryEvidence.backup,tenantId:randomUUID()},{...f.recoveryEvidence.backup,createdAt:new Date(f.now+1000).toISOString()},{...f.recoveryEvidence.backup,createdAt:new Date(f.now-25*3600000).toISOString()}])assert.equal((await inspectProductionReadiness({...f,recoveryEvidence:{...f.recoveryEvidence,backup}})).checks.find(c=>c.id==='off-host-backup').status,'blocked');const same=Buffer.from(f.env.MFA_ENCRYPTION_KEY,'hex').toString('base64');assert.equal((await inspectProductionReadiness({...f,env:{...f.env,BACKUP_ENCRYPTION_KEY:same}})).checks.find(c=>c.id==='backup-key').status,'blocked');});
test('demo identities, unconfirmed ephemeral storage and unverified external document providers block handover',async t=>{const f=await fixture(t);f.db.exec("INSERT INTO users VALUES('demo','alex@foundation.example','admin',1); CREATE TABLE document_revision_storage(document_id TEXT); INSERT INTO document_revision_storage VALUES('external')");const result=await inspectProductionReadiness({...f,env:{...f.env,PERSISTENT_STORAGE_CONFIRMED:'false'}});for(const id of ['workspace-accounts','persistent-workspace','document-storage'])assert.equal(result.checks.find(c=>c.id===id).status,'blocked');assert.equal(result.externalDocumentRevisions,1);});
test('monitoring exercises bounded HTTPS health and still requires a recent separately recorded alert drill',async()=>{const now=Date.now(),fetchImpl=async(url,options)=>{assert.equal(String(url),'https://crm.example.test/api/health');assert.equal(options.redirect,'error');return new Response(JSON.stringify({status:'ok'}));};assert.equal((await createHealthMonitoringProbe({origin:'https://crm.example.test',fetchImpl}).probe()).verified,false);assert.equal((await createHealthMonitoringProbe({origin:'https://crm.example.test',fetchImpl,alertDrill:{verified:true,at:new Date(now).toISOString()},now:()=>now}).probe()).verified,true);await assert.rejects(createHealthMonitoringProbe({origin:'http://localhost',fetchImpl}).probe(),/HTTPS/);await assert.rejects(createHealthMonitoringProbe({origin:'https://crm.example.test',fetchImpl:async()=>new Response('x'.repeat(3000))}).probe(),/limit/);});

test('a correctly formatted but wrong MFA key cannot produce ready status for existing administrator secrets',async t=>{const f=await fixture(t),result=await inspectProductionReadiness({...f,env:{...f.env,MFA_ENCRYPTION_KEY:'3'.repeat(64)}});assert.equal(result.ready,false);assert.equal(result.checks.find(c=>c.id==='administrator-mfa').status,'blocked');});

test('unrelated or unspecified selected workspace identity cannot borrow another tenant recovery evidence',async t=>{const f=await fixture(t);for(const expectedTenantId of [undefined,randomUUID()]){const result=await inspectProductionReadiness({...f,expectedTenantId});assert.equal(result.ready,false);assert.equal(result.checks.find(c=>c.id==='recovery-identity').status,'blocked');}});

test('unresolved staging and orphan copies block handover even with otherwise matching recovery proof',async t=>{const f=await fixture(t);f.db.exec('CREATE TABLE document_upload_attempts(state TEXT)');for(const state of ['Uploading','Verified','Orphaned']){f.db.prepare('INSERT INTO document_upload_attempts VALUES(?)').run(state);const result=await inspectProductionReadiness(f);assert.equal(result.ready,false);assert.equal(result.checks.find(c=>c.id==='document-upload-reconciliation').status,'blocked');f.db.exec('DELETE FROM document_upload_attempts');}f.db.exec("INSERT INTO document_upload_attempts VALUES('Committed')");assert.equal((await inspectProductionReadiness(f)).ready,true);});
