import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {createApp} from '../server/app.js';
import {installReceiptRoutes} from '../server/receipts.js';

const reviewedCash={benefitsReviewed:true,benefitsAssessment:'None provided',revenueClassification:'Contribution'};
const profile=(changes={})=>({version:0,organizationName:'Receipt test organization',address:'123 Test Street, Test City',taxIdentifier:'TEST-ONLY-ID',signatureLabel:'Authorized receipt signer',customFooter:'Client approval pending; fictional test organization.',approved:true,...changes});
async function fixture(t,{configure=true}={}){
 const dir=await mkdtemp(join(tmpdir(),'wimblo-receipts-'));let app,server,base;
 async function open(){app=createApp({dbPath:join(dir,'workspace.sqlite'),seed:true});server=app.listen(0,'127.0.0.1');await once(server,'listening');base=`http://127.0.0.1:${server.address().port}`;}
 async function close(){if(server)await new Promise(resolve=>server.close(resolve));server=null;app?.locals.close();app=null;}
 await open();t.after(async()=>{await close();await rm(dir,{recursive:true,force:true});});
 async function request(path,{method='GET',body,session,csrf=true}={}){const headers={};if(body!==undefined)headers['Content-Type']='application/json';if(session){headers.Cookie=session.cookie;if(csrf)headers['X-CSRF-Token']=csrf===true?session.csrfToken:csrf;}const r=await fetch(base+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,json:await r.json(),headers:r.headers};}
 async function login(email='alex@foundation.example'){const r=await request('/api/auth/login',{method:'POST',body:{email,password:'FoundationDemo!2026'}});assert.equal(r.status,200,JSON.stringify(r.json));return {...r.json,cookie:r.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ')};}
 const admin=await login(),staff=await login('staff@foundation.example'),viewer=await login('board@foundation.example');
 async function create(path,body){const r=await request(path,{method:'POST',body,session:staff});assert.equal(r.status,201,JSON.stringify(r.json));return r.json;}
 async function person(name,changes={}){return (await create('/api/records/constituents',{name,type:'Individual',preference:'Email',email:name.toLowerCase().replace(/[^a-z]/g,'')+'@example.test',...changes})).record;}
 const donor=await person('Receipt donor'),other=await person('Other donor'),fund=(await create('/api/records/designations',{name:'Receipts fund',accountCode:'RECEIPTS-4100'})).record;
 if(configure){const r=await request('/api/receipt-profile',{method:'PUT',session:admin,body:profile()});assert.equal(r.status,200,JSON.stringify(r.json));}
 async function gift(amount=12345,changes={}){return (await create('/api/records/gifts',{constituentId:donor.id,amount,type:'Cash',method:'Check',date:'2025-09-13',allocations:[{designationId:fund.id,amount}],...changes})).record;}
 async function prepare(selection,changes={}){const g=selection.giftId?JSON.parse(app.locals.db.prepare('SELECT data FROM records WHERE collection=? AND id=?').get('gifts',selection.giftId).data):null;return (await create('/api/receipts/prepare',{kind:'Individual',profileVersion:1,...(g?.type==='Cash'?reviewedCash:{}),...selection,...changes})).receipt;}
 async function issue(r,changes={},session=staff){return request(`/api/receipts/${r.id}/issue`,{method:'POST',session,body:{version:1,preparationDigest:r.preparationDigest,channel:'Print',printed:true,handSigned:true,issueDate:'2026-09-13',...changes}});}
 async function voidReceipt(r,changes={}){return request(`/api/receipts/${r.id}/void`,{method:'POST',session:staff,body:{version:r.version,reason:'Approved correction',...changes}});}
 async function read(id,session=viewer){return request(`/api/receipts/${id}`,{session});}
 return {request,admin,staff,viewer,donor,other,fund,person,gift,prepare,issue,voidReceipt,read,restart:async()=>{await close();await open();},get db(){return app.locals.db;}};
}

test('no default tax identity or profile exists; explicit admin approval is strict, versioned and retained',async t=>{
 const f=await fixture(t,{configure:false});const initial=await f.request('/api/receipt-profile',{session:f.viewer});assert.equal(initial.status,200);assert.equal(initial.json.configured,false);assert.equal(initial.json.profile,null);const g=await f.gift();assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{kind:'Individual',giftId:g.id,profileVersion:1}})).status,409);
 for(const body of [profile({approved:false}),profile({taxIdentifier:''}),{...profile(),legalCertified:true}])assert.equal((await f.request('/api/receipt-profile',{method:'PUT',session:f.admin,body})).status,400);
 const first=await f.request('/api/receipt-profile',{method:'PUT',session:f.admin,body:profile()});assert.equal(first.status,200);assert.equal(first.json.profile.version,1);assert.equal(first.json.profile.approvedBy,f.admin.user.id);assert.equal((await f.request('/api/receipt-profile',{method:'PUT',session:f.admin,body:profile()})).status,409);
 const second=await f.request('/api/receipt-profile',{method:'PUT',session:f.admin,body:profile({version:1,address:'Revised test address'})});assert.equal(second.status,200);const history=await f.request('/api/receipt-profile',{session:f.admin});assert.equal(history.json.revisions.length,2);assert.equal(history.json.revisions[0].address,profile().address);assert.throws(()=>f.db.prepare('DELETE FROM receipt_profile_revisions').run(),/retained/);
});

test('individual receipt preserves exact monetary facts and numbers only explicit staff-confirmed printing and hand-signing',async t=>{
 const f=await fixture(t),g=await f.gift(12345,{softCreditId:f.other.id}),r=await f.prepare({giftId:g.id});assert.equal(r.status,'Prepared');assert.equal(r.number,null);assert.equal(r.monetaryCents,12345);assert.equal(r.recipient.id,f.donor.id);assert.equal(r.references.find(x=>x.collection==='gifts').version,1);assert.doesNotMatch(JSON.stringify(r.recipient),/Other donor/);assert.equal(r.taxDeductibility,'Not determined');
 for(const change of [{printed:false},{handSigned:false},{channel:'Email'},{issueDate:'2027-09-13'},{issueDate:'2025-01-01'},{preparationDigest:'0'.repeat(64)},{version:2}])assert.ok([400,409].includes((await f.issue(r,change)).status));assert.equal(f.db.prepare('SELECT value FROM receipt_number_sequence').get().value,0);
 const before=f.db.prepare('SELECT data FROM records WHERE collection=? AND id=?').get('gifts',g.id).data;const issued=await f.issue(r);assert.equal(issued.status,200);assert.equal(issued.json.receipt.number,'R-00000001');assert.equal(issued.json.receipt.version,2);assert.equal(issued.json.receipt.issue.channel,'Print');assert.equal(issued.json.receipt.issue.handSigned,true);assert.equal(f.db.prepare('SELECT data FROM records WHERE collection=? AND id=?').get('gifts',g.id).data,before);assert.equal(JSON.parse(before).acknowledgment,undefined);assert.equal((await f.issue(r)).status,409);assert.equal(f.db.prepare('SELECT value FROM receipt_number_sequence').get().value,1);
});

test('active issued receipts reject financial changes and gift voids, permit notes, and release protection only after logged receipt void',async t=>{
 const f=await fixture(t),g=await f.gift(),r=await f.prepare({giftId:g.id}),issued=(await f.issue(r)).json.receipt;
 for(const body of [{version:1,date:'2025-09-14'},{version:1,constituentId:f.other.id},{version:1,amount:12346,allocations:[{designationId:f.fund.id,amount:12346}]},{version:1,type:'Sponsorship'}]){const edit=await f.request(`/api/records/gifts/${g.id}`,{method:'PATCH',session:f.staff,body});assert.equal(edit.status,409);assert.equal(edit.json.receiptId,r.id);assert.match(edit.json.error,/Void the receipt/);}
 assert.equal((await f.request(`/api/gifts/${g.id}/void`,{method:'POST',session:f.staff,body:{version:1,reason:'Correction'}})).status,409);const note=await f.request(`/api/records/gifts/${g.id}`,{method:'PATCH',session:f.staff,body:{version:1,notes:'Nonfinancial note'}});assert.equal(note.status,200);assert.equal((await f.read(r.id)).json.receipt.monetaryCents,12345);
 const receiptVoid=await f.voidReceipt(issued);assert.equal(receiptVoid.status,200);assert.equal(receiptVoid.json.receipt.status,'Voided');assert.equal(receiptVoid.json.receipt.version,3);assert.equal((await f.voidReceipt(issued)).status,409);
 const edit=await f.request(`/api/records/gifts/${g.id}`,{method:'PATCH',session:f.staff,body:{version:2,correctionReason:'Correct recorded cash value after receipt void',amount:12346,allocations:[{designationId:f.fund.id,amount:12346}]}});assert.equal(edit.status,200);assert.equal((await f.read(r.id)).json.receipt.monetaryCents,12345);assert.equal((await f.read(r.id)).json.receipt.number,'R-00000001');
});

test('issued receipt protection survives trailing slashes and encoded IDs without changing financial or audit history',async t=>{
 const f=await fixture(t),g=await f.gift(),r=await f.prepare({giftId:g.id}),issued=(await f.issue(r)).json.receipt;
 const encoded='%'+g.id.charCodeAt(0).toString(16)+g.id.slice(1),before=f.db.prepare('SELECT data FROM records WHERE collection=? AND id=?').get('gifts',g.id).data,auditBefore=f.db.prepare('SELECT count(*) n FROM audit').get().n;
 for(const id of [g.id,encoded])for(const suffix of ['/void','/void/']){const denied=await f.request(`/api/gifts/${id}${suffix}`,{method:'POST',session:f.staff,body:{version:1,reason:'Correct financial source'}});assert.equal(denied.status,409);assert.equal(denied.json.receiptId,r.id);assert.equal(f.db.prepare('SELECT data FROM records WHERE collection=? AND id=?').get('gifts',g.id).data,before);assert.equal(f.db.prepare('SELECT count(*) n FROM audit').get().n,auditBefore);assert.equal((await f.read(r.id)).json.receipt.status,'Issued');}
 // Exercise the shared writer contract with a complete next record, independent
 // of any Express route spelling or request-body field checks.
 const noop=()=>{},routes={use:noop,patch:noop,post:noop,get:noop,put:noop};const guard=installReceiptRoutes(routes,{db:f.db});const current=JSON.parse(before);
 for(const changes of [{status:'Voided'},{amount:12346},{constituentId:f.other.id}])assert.throws(()=>guard.validateMutation('gifts',current,{...current,...changes}),e=>e.status===409&&/Void the receipt/.test(e.message));
 assert.doesNotThrow(()=>guard.validateMutation('gifts',current,{...current,notes:'Permitted metadata',schoolYearOverride:'2024–2025'}));
 const fiscal=await f.request(`/api/gifts/${encoded}/school-year/`,{method:'POST',session:f.staff,body:{version:1,schoolYear:'2024–2025',reason:'Authorized fiscal assignment'}});assert.equal(fiscal.status,200);assert.equal(fiscal.json.record.amount,g.amount);assert.equal(fiscal.json.record.status,'Posted');
 const note=await f.request(`/api/records/gifts/${encoded}/`,{method:'PATCH',session:f.staff,body:{version:2,notes:'Permitted note'}});assert.equal(note.status,200);
 assert.equal((await f.voidReceipt(issued)).status,200);assert.doesNotThrow(()=>guard.validateMutation('gifts',current,{...current,status:'Voided'}));
 const released=await f.request(`/api/gifts/${encoded}/void/`,{method:'POST',session:f.staff,body:{version:3,reason:'Source correction after receipt void'}});assert.equal(released.status,200);assert.equal(released.json.record.status,'Voided');assert.equal((await f.read(r.id)).json.receipt.status,'Voided');assert.equal((await f.read(r.id)).json.receipt.monetaryCents,g.amount);
});

test('fees and voids cannot issue, noncash requires description without assigned value, and sponsors explicitly disclose benefits',async t=>{
 const f=await fixture(t),fee=await f.gift(100,{type:'Fee payment'}),voided=await f.gift(100);await f.request(`/api/gifts/${voided.id}/void`,{method:'POST',session:f.staff,body:{version:1,reason:'Source void'}});
 for(const id of [fee.id,voided.id])assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{kind:'Individual',giftId:id,profileVersion:1}})).status,409);
 const noncash=await f.gift(33333,{type:'In-kind',method:'In-kind'});assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{kind:'Individual',giftId:noncash.id,profileVersion:1}})).status,400);const nr=await f.prepare({giftId:noncash.id,noncashDescription:'Three donated classroom desks'});assert.equal(nr.monetaryCents,0);assert.equal(nr.gifts[0].monetaryCents,0);assert.equal(nr.noncashDescription,'Three donated classroom desks');assert.doesNotMatch(JSON.stringify(nr),/\"amount\":33333|noncashCents|deductibleCents/);assert.equal((await f.issue(nr)).status,200);
 const sponsor=await f.gift(20000,{type:'Sponsorship'});assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{kind:'Individual',giftId:sponsor.id,profileVersion:1}})).status,400);const sr=await f.prepare({giftId:sponsor.id,benefitsDescription:'Two event tickets',benefitValueCents:5000});assert.deepEqual(sr.benefits,{description:'Two event tickets',valueCents:5000});assert.equal(sr.monetaryCents,20000);assert.equal(sr.taxDeductibility,'Not determined');assert.equal(Object.hasOwn(sr,'deductibleCents'),false);assert.equal((await f.issue(sr)).status,200);
});

test('annual employee receipts use exact actual-calendar-year posted Payroll Employee giving and protect all linked gifts',async t=>{
 const f=await fixture(t),employee=await f.person('Payroll employee',{type:'Employee'}),base={constituentId:employee.id,type:'Employee giving',method:'Payroll'},a=await f.gift(10001,base),b=await f.gift(204,{...base,date:'2025-12-31'});await f.gift(100,{...base,date:'2026-01-01'});await f.gift(100,{...base,method:'Check'});await f.gift(100,{constituentId:employee.id,type:'Fee payment',method:'Payroll'});await f.gift(100,{constituentId:employee.id,type:'In-kind',method:'In-kind'});await f.gift(100,{softCreditId:employee.id});const reversed=await f.gift(100,base);await f.request(`/api/gifts/${reversed.id}/void`,{method:'POST',session:f.staff,body:{version:1,reason:'Reversed payroll'}});
 await f.request(`/api/gifts/${a.id}/school-year`,{method:'POST',session:f.staff,body:{version:1,schoolYear:'2024–2025',reason:'School-year assignment does not alter tax calendar'}});
 const r=await f.prepare({kind:'Annual employee',constituentId:employee.id,year:2025});assert.equal(r.monetaryCents,10205);assert.equal(r.giftCount,2);assert.equal(r.calendarYear,2025);assert.deepEqual(r.gifts.map(g=>g.id).sort(),[a.id,b.id].sort());assert.equal((await f.issue(r)).status,200);
 assert.equal((await f.request(`/api/records/gifts/${b.id}`,{method:'PATCH',session:f.staff,body:{version:1,date:'2026-01-01'}})).status,409);
 assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{kind:'Annual employee',constituentId:f.donor.id,year:2025,profileVersion:1}})).status,400);
});

test('source/profile/current recipient versions and annual membership changes block stale issuance without consuming numbers',async t=>{
 const f=await fixture(t),g=await f.gift(),r=await f.prepare({giftId:g.id});const edit=await f.request(`/api/records/gifts/${g.id}`,{method:'PATCH',session:f.staff,body:{version:1,notes:'Source changed after preparation'}});assert.equal(edit.status,200);assert.equal((await f.issue(r)).status,409);
 const fresh=await f.prepare({giftId:g.id});const update=await f.request('/api/receipt-profile',{method:'PUT',session:f.admin,body:profile({version:1,customFooter:'Revised client wording'})});assert.equal(update.status,200);assert.equal((await f.issue(fresh)).status,409);
 const employee=await f.person('Stale employee',{type:'Employee'});await f.gift(10,{constituentId:employee.id,type:'Employee giving',method:'Payroll'});const annual=await f.prepare({kind:'Annual employee',constituentId:employee.id,year:2025},{profileVersion:2});await f.gift(1,{constituentId:employee.id,type:'Employee giving',method:'Payroll'});assert.equal((await f.issue(annual)).status,409);assert.equal(f.db.prepare('SELECT value FROM receipt_number_sequence').get().value,0);
});

test('void/reissue keeps numbered original and correction reason, replacement uses current source, and concurrent/repeated issues cannot duplicate',async t=>{
 const f=await fixture(t),g=await f.gift(),prepared=await f.prepare({giftId:g.id}),original=(await f.issue(prepared)).json.receipt;
 assert.equal((await f.request(`/api/receipts/${original.id}/reissue`,{method:'POST',session:f.staff,body:{profileVersion:1,reason:'Correction'}})).status,409);assert.equal((await f.voidReceipt(original)).status,200);
 await f.request(`/api/records/gifts/${g.id}`,{method:'PATCH',session:f.staff,body:{version:1,correctionReason:'Correct recorded cash value after receipt void',amount:12346,allocations:[{designationId:f.fund.id,amount:12346}]}});
 const first=await f.request(`/api/receipts/${original.id}/reissue`,{method:'POST',session:f.staff,body:{profileVersion:1,reason:'Correct source amount',...reviewedCash}});assert.equal(first.status,201);const replacement=first.json.receipt;assert.equal(replacement.priorReceiptId,original.id);assert.equal(replacement.reissueReason,'Correct source amount');assert.equal(replacement.monetaryCents,12346);assert.equal(replacement.number,null);
 const competing=await f.request(`/api/receipts/${original.id}/reissue`,{method:'POST',session:f.staff,body:{profileVersion:1,reason:'Competing correction',...reviewedCash}});assert.equal(competing.status,201);
 const results=await Promise.all([f.issue(replacement),f.issue(replacement)]);assert.deepEqual(results.map(x=>x.status).sort(),[200,409]);assert.equal(results.find(x=>x.status===200).json.receipt.number,'R-00000002');assert.equal((await f.issue(competing.json.receipt)).status,409);assert.equal(f.db.prepare('SELECT value FROM receipt_number_sequence').get().value,2);
 const retained=(await f.read(original.id)).json.receipt;assert.equal(retained.status,'Voided');assert.equal(retained.number,'R-00000001');assert.equal(retained.monetaryCents,12345);assert.ok(retained.replacements.includes(replacement.id));
});

test('overlapping prepared receipts cannot both issue for the same source gift',async t=>{
 const f=await fixture(t),g=await f.gift(),a=await f.prepare({giftId:g.id}),b=await f.prepare({giftId:g.id});assert.equal((await f.issue(a)).status,200);assert.equal((await f.issue(b)).status,409);assert.equal(f.db.prepare('SELECT count(*) n FROM receipt_issues').get().n,1);
});

test('retained numbered history/profile/source links survive restart and searchable history exposes exact original facts',async t=>{
 const f=await fixture(t),g=await f.gift(),r=await f.prepare({giftId:g.id}),issued=(await f.issue(r)).json.receipt;await f.restart();assert.deepEqual((await f.read(r.id)).json.receipt,issued);
 for(const query of [`giftId=${g.id}`,`constituentId=${f.donor.id}`,`q=R-00000001&status=Issued`]){const h=await f.request('/api/receipts?'+query,{session:f.viewer});assert.equal(h.status,200);assert.equal(h.json.receipts.length,1);assert.equal(h.json.receipts[0].monetaryCents,12345);}
 assert.throws(()=>f.db.prepare('UPDATE receipt_preparations SET snapshot=? WHERE id=?').run('{}',r.id),/immutable/);assert.throws(()=>f.db.prepare('DELETE FROM receipt_issues WHERE receipt_id=?').run(r.id),/retained/);assert.throws(()=>f.db.prepare('DELETE FROM receipt_source_links WHERE receipt_id=?').run(r.id),/retained/);
 const next=await f.prepare({giftId:(await f.gift(2)).id});assert.equal((await f.issue(next)).json.receipt.number,'R-00000002');assert.equal((await f.request('/api/receipts?unknown=true',{session:f.viewer})).status,400);
});

test('receipt permissions require current auth, CSRF, staff issuance and administrator profile approval; payload cannot claim email or tax certification',async t=>{
 const f=await fixture(t),g=await f.gift(),body={kind:'Individual',giftId:g.id,profileVersion:1};for(const [options,status] of [[{body},401],[{body,session:f.viewer},403],[{body,session:f.staff,csrf:false},403],[{body,session:f.staff,csrf:'wrong'},403],[{body:{...body,recipientId:f.other.id},session:f.staff},400],[{body:{...body,deductibleCents:12345},session:f.staff},400]])assert.equal((await f.request('/api/receipts/prepare',{method:'POST',...options})).status,status);
 assert.equal((await f.request('/api/receipt-profile',{method:'PUT',session:f.staff,body:profile({version:1})})).status,403);assert.equal((await f.request('/api/receipt-profile',{method:'PUT',session:f.admin,csrf:false,body:profile({version:1})})).status,403);
 const r=await f.prepare({giftId:g.id});assert.equal((await f.issue(r,{},f.viewer)).status,403);assert.equal((await f.issue(r,{delivered:true})).status,400);assert.equal((await f.issue(r,{taxCertified:true})).status,400);assert.equal((await f.request(`/api/receipts/${r.id}/issue`,{method:'POST',session:f.staff,csrf:false,body:{version:1,preparationDigest:r.preparationDigest,channel:'Print',printed:true,handSigned:true,issueDate:'2026-09-13'}})).status,403);assert.equal((await f.request('/api/receipts')).status,401);assert.equal((await f.request('/api/receipt-profile')).status,401);
});

test('audit write failures roll back preparation, issue number and void; audit retains metadata rather than tax identifiers or custom wording',async t=>{
 const f=await fixture(t),g=await f.gift();f.db.exec("CREATE TRIGGER receipt_audit_fault BEFORE INSERT ON audit WHEN NEW.action='prepare_receipt' BEGIN SELECT RAISE(ABORT,'fixture receipt audit fault'); END;");const bad=await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{kind:'Individual',giftId:g.id,profileVersion:1,...reviewedCash}});assert.equal(bad.status,500);assert.equal(f.db.prepare('SELECT count(*) n FROM receipt_preparations').get().n,0);assert.equal(f.db.prepare('SELECT count(*) n FROM receipt_source_links').get().n,0);f.db.exec('DROP TRIGGER receipt_audit_fault');
 const r=await f.prepare({giftId:g.id});f.db.exec("CREATE TRIGGER receipt_audit_fault BEFORE INSERT ON audit WHEN NEW.action='issue_receipt' BEGIN SELECT RAISE(ABORT,'fixture receipt audit fault'); END;");assert.equal((await f.issue(r)).status,500);assert.equal(f.db.prepare('SELECT value FROM receipt_number_sequence').get().value,0);assert.equal(f.db.prepare('SELECT count(*) n FROM receipt_issues').get().n,0);f.db.exec('DROP TRIGGER receipt_audit_fault');const issued=(await f.issue(r)).json.receipt;
 f.db.exec("CREATE TRIGGER receipt_audit_fault BEFORE INSERT ON audit WHEN NEW.action='void_receipt' BEGIN SELECT RAISE(ABORT,'fixture receipt audit fault'); END;");assert.equal((await f.voidReceipt(issued)).status,500);assert.equal((await f.read(r.id)).json.receipt.status,'Issued');f.db.exec('DROP TRIGGER receipt_audit_fault');assert.equal((await f.voidReceipt(issued)).status,200);
 const metadata=f.db.prepare("SELECT details FROM audit WHERE action LIKE '%receipt%'").all();assert.doesNotMatch(JSON.stringify(metadata),/TEST-ONLY-ID|123 Test Street|Receipt donor|fictional test|csrf|password/);
});

test('Cash assessment is explicit, restricted to Cash, and preserves exact reviewed benefits without deductible amounts',async t=>{
 const f=await fixture(t),g=await f.gift(10001),base={kind:'Individual',giftId:g.id,profileVersion:1};
 for(const fields of [{},{...reviewedCash,benefitsReviewed:false},{...reviewedCash,benefitsAssessment:undefined},{...reviewedCash,revenueClassification:undefined},{...reviewedCash,benefitsDescription:'Contradictory benefits'},{...reviewedCash,benefitsAssessment:'Provided'},{...reviewedCash,benefitsAssessment:'Provided',benefitsDescription:'Reviewed dinner',benefitValueCents:12.5}])assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{...base,...fields}})).status,400);
 assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{...base,...reviewedCash,revenueClassification:'Exchange payment'}})).status,409);assert.equal(f.db.prepare('SELECT count(*) n FROM receipt_preparations').get().n,0);
 const r=await f.prepare({giftId:g.id},{...reviewedCash,benefitsAssessment:'Provided',benefitsDescription:'Staff-approved dinner estimate',benefitValueCents:3401});assert.equal(r.monetaryCents,10001);assert.equal(r.benefits.valueCents,3401);assert.equal(r.benefits.assessment,'Provided');assert.match(r.benefits.classification,/not a legal determination/);assert.equal(r.taxDeductibility,'Not determined');assert.doesNotMatch(JSON.stringify(r),/deductibleCents|fairValueCents/);assert.equal((await f.issue(r)).status,200);
 const none=await f.prepare({giftId:(await f.gift()).id});assert.equal(none.benefits.assessment,'None provided');assert.match(none.benefits.description,/No goods or services/);
 for(const type of ['Sponsorship','In-kind','Employee giving']){const source=await f.gift(500,{type,method:type==='In-kind'?'In-kind':'Check'});assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{...base,giftId:source.id,...reviewedCash,...(type==='In-kind'?{noncashDescription:'Desk'}:{benefitsDescription:'Recognition',benefitValueCents:0})}})).status,400);}
 const employee=await f.person('Assessment payroll',{type:'Employee'});await f.gift(500,{constituentId:employee.id,type:'Employee giving',method:'Payroll'});assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{kind:'Annual employee',constituentId:employee.id,year:2025,profileVersion:1,...reviewedCash}})).status,400);
});

test('ticket-linked Cash requires goods review and linkage changes invalidate preparation; issued source cannot acquire new event linkage',async t=>{
 const f=await fixture(t),created=await f.request('/api/records/events',{method:'POST',session:f.staff,body:{name:'Reviewed receipt benefit event',date:'2026-09-01',location:'Test hall',capacity:5,ticketPrice:10001,sponsorGoal:0}});assert.equal(created.status,201);const event=created.json.record;
 assert.equal((await f.request(`/api/events/${event.id}/register`,{method:'POST',session:f.staff,body:{constituentId:f.donor.id}})).status,200);
 const workspace=(await f.request('/api/workspace',{session:f.staff})).json.data,ticket=(await f.request(`/api/event-operations/events/${event.id}/tickets`,{method:'POST',session:f.staff,body:{eventVersion:workspace.events.find(e=>e.id===event.id).version,constituentId:f.donor.id}})).json.ticket;assert.ok(ticket?.id);
 const g=await f.gift(10001),early=await f.prepare({giftId:g.id}),payment={ownerType:'ticket',ownerId:ticket.id,version:ticket.version,giftId:g.id,giftVersion:g.version,revenueCase:'Cash'};
 assert.equal((await f.request('/api/event-operations/payments',{method:'POST',session:f.staff,body:payment})).status,201);assert.equal((await f.issue(early)).status,409);
 assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{kind:'Individual',profileVersion:1,giftId:g.id,...reviewedCash}})).status,409);
 const fields={...reviewedCash,benefitsAssessment:'Provided',benefitsDescription:'Event admission and meal; staff approved estimate',benefitValueCents:4001},prepared=await f.prepare({giftId:g.id},fields);assert.equal(prepared.eventContext[0].ownerType,'ticket');assert.equal(prepared.eventContext[0].ownerId,ticket.id);assert.equal(prepared.benefits.valueCents,4001);assert.equal((await f.issue(prepared)).status,200);
 assert.equal((await f.request(`/api/events/${event.id}/register`,{method:'POST',session:f.staff,body:{constituentId:f.other.id}})).status,200);const currentEvent=(await f.request('/api/workspace',{session:f.staff})).json.data.events.find(e=>e.id===event.id);const freeTicketResponse=await f.request(`/api/event-operations/events/${event.id}/tickets`,{method:'POST',session:f.staff,body:{eventVersion:currentEvent.version,constituentId:f.other.id}});assert.equal(freeTicketResponse.status,201);const freeTicket=freeTicketResponse.json.ticket;const second=await f.gift(10001,{constituentId:f.other.id}),unlinked=await f.prepare({giftId:second.id}),issued=(await f.issue(unlinked)).json.receipt;const before=f.db.prepare('SELECT count(*) n FROM event_payment_links').get().n,auditBefore=f.db.prepare('SELECT count(*) n FROM audit').get().n;
 assert.equal((await f.request('/api/event-operations/payments/',{method:'POST',session:f.staff,body:{...payment,ownerId:freeTicket.id,giftId:second.id,version:freeTicket.version}})).status,409);assert.equal(f.db.prepare('SELECT count(*) n FROM event_payment_links').get().n,before);assert.equal(f.db.prepare('SELECT count(*) n FROM audit').get().n,auditBefore);assert.equal((await f.read(issued.id)).json.receipt.status,'Issued');assert.equal((await f.voidReceipt(issued)).status,200);assert.equal((await f.request('/api/event-operations/payments',{method:'POST',session:f.staff,body:{...payment,ownerId:freeTicket.id,giftId:second.id,version:freeTicket.version}})).status,201);
});

test('Cash auction receipt requires approved goods disclosure without inferring value from the winning bid',async t=>{
 const f=await fixture(t),event=(await f.request('/api/records/events',{method:'POST',session:f.staff,body:{name:'Reviewed auction receipt',date:'2026-09-01',location:'Test hall',capacity:2,ticketPrice:0,sponsorGoal:0}})).json.record;
 const itemResponse=await f.request('/api/event-operations/auction-items',{method:'POST',session:f.staff,body:{eventId:event.id,eventVersion:event.version,name:'Donated artwork',startingBid:10001,minIncrement:100,description:'Auction property'}});assert.equal(itemResponse.status,201);const item=itemResponse.json.item;
 const bid=await f.request(`/api/event-operations/auction-items/${item.id}/bids`,{method:'POST',session:f.staff,body:{version:item.version,bidderId:f.donor.id,amount:12345}});assert.equal(bid.status,201);const closed=await f.request(`/api/event-operations/auction-items/${item.id}/close`,{method:'POST',session:f.staff,body:{version:bid.json.item.version,winningBidId:bid.json.item.bids[0].id,confirmed:true}});assert.equal(closed.status,200);
 const g=await f.gift(12345);assert.equal((await f.request('/api/event-operations/payments',{method:'POST',session:f.staff,body:{ownerType:'auction',ownerId:item.id,version:closed.json.item.version,giftId:g.id,giftVersion:g.version,revenueCase:'Cash'}})).status,201);
 const base={kind:'Individual',profileVersion:1,giftId:g.id,...reviewedCash};assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:base})).status,409);assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{...base,benefitsAssessment:'Provided',benefitsDescription:'Artwork; value pending'}})).status,400);
 const prepared=await f.prepare({giftId:g.id},{benefitsAssessment:'Provided',benefitsDescription:'Artwork; staff-approved good-faith value',benefitValueCents:8201});assert.equal(prepared.eventContext[0].ownerType,'auction');assert.equal(prepared.monetaryCents,12345);assert.equal(prepared.benefits.valueCents,8201);assert.notEqual(prepared.benefits.valueCents,closed.json.item.winner.amount);assert.equal(prepared.taxDeductibility,'Not determined');assert.equal((await f.issue(prepared)).status,200);
});

test('reviewed Cash goods disclosures retain immutable originals through void/reissue, enforce privacy and roll back failed preparation audit',async t=>{
 const f=await fixture(t),g=await f.gift(12345),fields={...reviewedCash,benefitsAssessment:'Provided',benefitsDescription:'<script>historic approved meal</script>',benefitValueCents:3456},prepared=await f.prepare({giftId:g.id},fields),issued=(await f.issue(prepared)).json.receipt;
 assert.equal((await f.voidReceipt(issued)).status,200);const path=`/api/receipts/${prepared.id}/reissue`,base={profileVersion:1,reason:'Correct approved benefits estimate'};
 assert.equal((await f.request(path,{method:'POST',session:f.staff,body:base})).status,400);
 f.db.exec("CREATE TRIGGER receipt_reissue_fault BEFORE INSERT ON audit WHEN NEW.action='prepare_receipt_reissue' BEGIN SELECT RAISE(ABORT,'fixture reissue audit fault'); END;");const count=f.db.prepare('SELECT count(*) n FROM receipt_preparations').get().n;
 const revised={...base,...reviewedCash,benefitsAssessment:'Provided',benefitsDescription:'Corrected staff-approved meal estimate',benefitValueCents:3333};assert.equal((await f.request(path,{method:'POST',session:f.staff,body:revised})).status,500);assert.equal(f.db.prepare('SELECT count(*) n FROM receipt_preparations').get().n,count);f.db.exec('DROP TRIGGER receipt_reissue_fault');
 assert.equal((await f.request(path,{method:'POST',session:f.viewer,body:revised})).status,403);assert.equal((await f.request(path,{method:'POST',session:f.staff,csrf:false,body:revised})).status,403);assert.equal((await f.request(`/api/receipts/${prepared.id}`)).status,401);
 const replacement=(await f.request(path,{method:'POST',session:f.staff,body:revised})).json.receipt;assert.equal(replacement.benefits.valueCents,3333);assert.equal(replacement.priorReceiptId,prepared.id);assert.equal((await f.issue(replacement)).status,200);await f.restart();const original=(await f.read(prepared.id)).json.receipt;assert.equal(original.benefits.valueCents,3456);assert.equal(original.benefits.description,fields.benefitsDescription);assert.equal(original.status,'Voided');assert.equal(original.number,'R-00000001');assert.equal((await f.read(replacement.id)).json.receipt.benefits.valueCents,3333);
 const donor=(await f.request('/api/workspace',{session:f.staff})).json.data.constituents.find(p=>p.id===f.donor.id);assert.equal((await f.request(`/api/records/constituents/${donor.id}`,{method:'PATCH',session:f.staff,body:{version:donor.version,preference:'Do not contact'}})).status,200);assert.equal((await f.request('/api/receipts/prepare',{method:'POST',session:f.staff,body:{kind:'Individual',profileVersion:1,giftId:g.id,...fields}})).status,403);
});

test('identity merge protects both source and target issued recipients and catches issuance after a prior merge preview',async t=>{
 const f=await fixture(t),g=await f.gift(),r=await f.prepare({giftId:g.id});const payload={targetId:f.other.id,sourceId:f.donor.id,targetVersion:1,sourceVersion:1,reason:'Reconcile duplicate identity'};
 const preview=await f.request('/api/identity/merge/preview',{method:'POST',session:f.admin,body:payload});assert.equal(preview.status,200);assert.equal(preview.json.preview.blockers.length,0);const issued=(await f.issue(r)).json.receipt;
 for(const body of [payload,{...payload,targetId:f.donor.id,sourceId:f.other.id}]){const denied=await f.request('/api/identity/merge/preview',{method:'POST',session:f.admin,body});assert.equal(denied.status,409);assert.equal(denied.json.receiptId,r.id);assert.match(denied.json.error,/Void the affected receipt/);}
 const commit=await f.request('/api/identity/merge',{method:'POST',session:f.admin,body:{...payload,previewDigest:preview.json.preview.previewDigest}});assert.equal(commit.status,409);assert.equal(f.db.prepare('SELECT count(*) n FROM identity_aliases').get().n,0);
 assert.equal((await f.voidReceipt(issued)).status,200);const released=await f.request('/api/identity/merge/preview',{method:'POST',session:f.admin,body:payload});assert.equal(released.status,200);assert.equal(released.json.preview.blockers.length,0);
});

test('identity merge blocks active receipt source soft-credit rewrites, while prepared-only merge invalidates stale receipt issuance',async t=>{
 const f=await fixture(t),third=await f.person('Third identity'),g=await f.gift(100,{softCreditId:f.other.id}),r=await f.prepare({giftId:g.id}),issued=(await f.issue(r)).json.receipt;
 const softMerge={targetId:third.id,sourceId:f.other.id,targetVersion:1,sourceVersion:1,reason:'Reconcile soft-credit identity'};assert.equal((await f.request('/api/identity/merge/preview',{method:'POST',session:f.admin,body:softMerge})).status,409);await f.voidReceipt(issued);
 const donorOnly=await f.person('Prepared only donor'),target=await f.person('Prepared target'),unissuedGift=await f.gift(20,{constituentId:donorOnly.id}),prepared=await f.prepare({giftId:unissuedGift.id});const payload={targetId:target.id,sourceId:donorOnly.id,targetVersion:1,sourceVersion:1,reason:'Merge before receipt issuance'};
 const preview=await f.request('/api/identity/merge/preview',{method:'POST',session:f.admin,body:payload});assert.equal(preview.status,200);assert.equal(preview.json.preview.blockers.length,0);const merge=await f.request('/api/identity/merge',{method:'POST',session:f.admin,body:{...payload,previewDigest:preview.json.preview.previewDigest}});assert.equal(merge.status,200);assert.equal((await f.issue(prepared)).status,409);assert.equal((await f.read(prepared.id)).json.receipt.recipient.id,donorOnly.id);const fresh=await f.prepare({giftId:unissuedGift.id});assert.equal(fresh.recipient.id,target.id);assert.equal((await f.issue(fresh)).status,200);
});
