import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';

function harness(){let index=0,state=[],effects=[],keys=[],cleanup=[],downloads=[];const mock={...React,useState(initial){const i=index++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return [state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){return state[index++]??=({current:initial});},useEffect(effect,deps){const i=index++;if(!keys[i]||deps.some((d,j)=>d!==keys[i][j])){keys[i]=deps;effects.push(()=>{cleanup[i]?.();cleanup[i]=effect();});}}};const module={exports:{}},require=id=>id==='react'?mock:id==='../lib.js'?{money:String,cents:v=>Math.round(Number(v)*100),dateLabel:String,download:(...args)=>downloads.push(args),toCSV:()=>''}:new Proxy({},{get:()=>()=>null});new Function('React','require','module','exports',transformSync(readFileSync(new URL('../src/features/CustomReports.jsx',import.meta.url),'utf8'),{loader:'jsx',format:'cjs'}).code)(React,require,module,module.exports);return {downloads,render(props,commit=true){index=0;const tree=module.exports.default(props);if(commit){const pending=effects;effects=[];pending.forEach(e=>e());}return tree;},unmount(){cleanup.forEach(fn=>fn?.());}};}
function find(tree,predicate){if(!tree||typeof tree!=='object')return null;if(predicate(tree))return tree;for(const child of React.Children.toArray(tree.props?.children)){const found=find(child,predicate);if(found)return found;}return null;}
const button=(tree,text)=>find(tree,e=>e.type==='button'&&React.Children.toArray(e.props.children).filter(c=>typeof c==='string').join('')===text),flush=async()=>{for(let i=0;i<24;i++)await Promise.resolve();};
const definition={name:'Reviewed result',entity:'gifts',columns:['amount'],filters:[{field:'amount',op:'eq',value:10001}],groupBy:[],aggregates:[],includeVoided:false};
const result={definition,columns:[{key:'amount',label:'Amount',type:'money'}],rows:[[10001]],recordReferences:[],matchedRows:301,totalResultRows:301,page:{offset:250,limit:250,nextOffset:null},sourceFingerprint:'1'.repeat(64),sourcePreview:{columns:[],rows:[],recordReferences:[]},scope:'Synthetic source',totalsComplete:true,textTruncated:true};
const catalog={entities:[{id:'gifts',label:'Gifts',fields:['date','donorName','amount'].map(key=>({key,label:key,type:key==='amount'?'money':'text',aggregateable:key==='amount',groupable:true}))}]};
const exportResult={filename:'Reviewed-result-complete.csv',csv:'\uFEFF"Amount (USD)"\r\n"100.01"',rowCount:301,sourceFingerprint:result.sourceFingerprint,complete:true};
async function setup(exporter){const h=harness(),calls=[],api=async(path,options)=>{calls.push([path,options]);return path==='/custom-reports/catalog'?catalog:path==='/custom-reports'?{reports:[]}:path.startsWith('/custom-reports/export')?exporter():result;},props={api,user:{id:'staff',role:'staff'}};h.render(props);await flush();await find(h.render(props),e=>e.type==='form').props.onSubmit({preventDefault(){}});await flush();return {h,calls,props};}

test('complete CSV requests the exact reviewed definition and source, downloads all verified rows rather than visible page',async()=>{const {h,calls,props}=await setup(()=>exportResult);let tree=h.render(props);assert.ok(button(tree,'Export visible CSV'));assert.match(renderToStaticMarkup(tree),/full saved text/);await button(tree,'Export complete CSV').props.onClick();await flush();assert.deepEqual(calls.at(-1),['/custom-reports/export?fingerprint='+result.sourceFingerprint,{method:'POST',body:definition}]);assert.deepEqual(h.downloads,[[exportResult.filename,exportResult.csv,'text/csv;charset=utf-8']]);assert.match(renderToStaticMarkup(h.render(props)),/301 result rows · source verified/);});

for(const mutation of ['edit','account','api','unmount'])test(`pending complete CSV never downloads after ${mutation}`,async()=>{let resolve;const pending=new Promise(r=>resolve=r),{h,props}=await setup(()=>pending),tree=h.render(props),request=button(tree,'Export complete CSV').props.onClick();if(mutation==='edit')find(tree,e=>e.type==='input'&&e.props.maxLength===120).props.onChange({target:{value:'Changed definition'}});if(mutation==='account')h.render({...props,user:{id:'other',role:'viewer'}},false);if(mutation==='api')h.render({...props,api:async()=>({})},false);if(mutation==='unmount')h.unmount();resolve(exportResult);await request;await flush();assert.equal(h.downloads.length,0);});

for(const changes of [{complete:false},{rowCount:300},{sourceFingerprint:'2'.repeat(64)},{csv:null}])test('incomplete or mismatched export proof withholds download '+JSON.stringify(changes),async()=>{const {h,props}=await setup(()=>({...exportResult,...changes}));await button(h.render(props),'Export complete CSV').props.onClick();await flush();assert.equal(h.downloads.length,0);assert.match(renderToStaticMarkup(h.render(props)),/complete export could not be verified/);});

for(const status of [409,413,503])test(`export ${status} refuses download and truthfully preserves or invalidates preview`,async()=>{const {h,props}=await setup(()=>{throw Object.assign(new Error(status===409?'Sources changed; rerun report.':'Complete export unavailable; narrow report or retry.'),{status});});await button(h.render(props),'Export complete CSV').props.onClick();await flush();const tree=h.render(props);assert.equal(h.downloads.length,0);assert.equal(Boolean(button(tree,'Export visible CSV')),status!==409);assert.match(renderToStaticMarkup(tree),status===409?/Sources changed/:/Complete export unavailable/);});
