import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';

function harness(){let index=0,state=[],effects=[],keys=[],cleanup=[],downloads=[];const mock={...React,useState(initial){const i=index++;if(!(i in state))state[i]=typeof initial==='function'?initial():initial;return [state[i],v=>state[i]=typeof v==='function'?v(state[i]):v];},useRef(initial){return state[index++]??=({current:initial});},useEffect(effect,deps){const i=index++;if(!keys[i]||deps.some((d,j)=>d!==keys[i][j])){keys[i]=deps;effects.push(()=>{cleanup[i]?.();cleanup[i]=effect();});}}};const module={exports:{}},require=id=>id==='react'?mock:id==='../lib.js'?{money:String,cents:v=>Math.round(Number(v)*100),dateLabel:String,download:(...args)=>downloads.push(args),toCSV:()=>''}:new Proxy({},{get:()=>()=>null});new Function('React','require','module','exports',transformSync(readFileSync(new URL('../src/features/CustomReports.jsx',import.meta.url),'utf8'),{loader:'jsx',format:'cjs'}).code)(React,require,module,module.exports);return {downloads,render(props,commit=true){index=0;const tree=module.exports.default(props);if(commit){const pending=effects;effects=[];pending.forEach(e=>e());}return tree;},unmount(){cleanup.forEach(fn=>fn?.());}};}
function find(tree,predicate){if(!tree||typeof tree!=='object')return null;if(predicate(tree))return tree;for(const child of React.Children.toArray(tree.props?.children)){const found=find(child,predicate);if(found)return found;}return null;}
const button=(tree,text)=>find(tree,e=>e.type==='button'&&React.Children.toArray(e.props.children).filter(c=>typeof c==='string').join('')===text),flush=async()=>{for(let i=0;i<24;i++)await Promise.resolve();};
const definition={name:'Reviewed result',entity:'gifts',columns:['amount'],filters:[{field:'amount',op:'eq',value:10001}],groupBy:[],aggregates:[],includeVoided:false};
const result={definition,columns:[{key:'amount',label:'Amount',type:'money'}],rows:[[10001]],recordReferences:[],matchedRows:301,totalResultRows:301,page:{offset:250,limit:250,nextOffset:null},sourceFingerprint:'1'.repeat(64),sourcePreview:{columns:[],rows:[],recordReferences:[]},scope:'Synthetic source',totalsComplete:true,textTruncated:true};
const catalog={entities:[{id:'gifts',label:'Gifts',fields:['date','donorName','amount'].map(key=>({key,label:key,type:key==='amount'?'money':'text',aggregateable:key==='amount',groupable:true}))}]};
const exportResult={filename:'Reviewed-result-complete.csv',csv:'\uFEFF"Amount (USD)"\r\n"100.01"',rowCount:301,sourceFingerprint:result.sourceFingerprint,complete:true};
const inspection={entities:[{...catalog.entities[0],fields:[...catalog.entities[0].fields,{key:'lateOptionalField',label:'Late optional field',type:'text',groupable:true,aggregateable:false}]}],inspection:{entity:'gifts',sourceRowsInspected:301,fieldCount:4,depthLimit:4,arrayItemLimit:100,includesVoidedGiftRows:true}};
async function setup(inspector,savedReports=[]){const h=harness(),calls=[],initial={entities:[...catalog.entities,{id:'tasks',label:'Tasks',fields:[{key:'id',label:'Id',type:'text'}]}]},api=async(path,options)=>{calls.push([path,options]);return path==='/custom-reports/catalog'?initial:path==='/custom-reports'?{reports:savedReports}:path.startsWith('/custom-reports/catalog?')?inspector():result;},props={api,user:{id:'staff',role:'staff'}};h.render(props);await flush();await find(h.render(props),e=>e.type==='form').props.onSubmit({preventDefault(){}});await flush();return {h,calls,props};}

test('field inspection exposes later optional fields for selected source, clears old result and preserves reviewed definition',async()=>{const {h,calls,props}=await setup(()=>inspection);assert.ok(button(h.render(props),'Export complete CSV'));await button(h.render(props),'Review all source fields').props.onClick();await flush();const tree=h.render(props);assert.equal(calls.at(-1)[0],'/custom-reports/catalog?entity=gifts');assert.equal(button(tree,'Export complete CSV'),null);assert.ok(find(tree,e=>e.type==='input'&&e.props.type==='checkbox'&&e.props.checked===false&&React.Children.toArray(e.props?.children).length===0));assert.match(renderToStaticMarkup(tree),/Late optional field/);assert.match(renderToStaticMarkup(tree),/301 visible source rows inspected/);assert.equal(find(tree,e=>e.type==='input'&&e.props.maxLength===120).props.value,'Untitled report');assert.match(renderToStaticMarkup(tree),/four levels and 100 items/);assert.match(renderToStaticMarkup(tree),/includes authorized voided gifts; your report filters are unchanged/);assert.equal(h.downloads.length,0);});

for(const change of ['edit','entity','account','api','unmount'])test(`late schema response cannot republish fields after ${change}`,async()=>{let resolve;const pending=new Promise(r=>resolve=r),{h,props}=await setup(()=>pending),tree=h.render(props),request=button(tree,'Review all source fields').props.onClick();if(change==='edit')find(tree,e=>e.type==='input'&&e.props.maxLength===120).props.onChange({target:{value:'Changed definition'}});if(change==='entity')find(tree,e=>e.type==='select'&&e.props.value==='gifts').props.onChange({target:{value:'tasks'}});if(change==='account')h.render({...props,user:{id:'other',role:'staff'}},false);if(change==='api')h.render({...props,api:async()=>({})},false);if(change==='unmount')h.unmount();resolve(inspection);await request;await flush();assert.doesNotMatch(renderToStaticMarkup(h.render(props)),/Late optional field|301 visible source rows inspected/);assert.equal(h.downloads.length,0);});

for(const changed of [{entities:[{...inspection.entities[0],id:'tasks'}]},{entities:[...inspection.entities,...inspection.entities]},{inspection:{entity:'gifts',sourceRowsInspected:-1}},{inspection:{entity:'tasks',sourceRowsInspected:301}}])test('mismatched field inspection is rejected without replacing schema '+JSON.stringify(changed),async()=>{const {h,props}=await setup(()=>({...inspection,...changed}));await button(h.render(props),'Review all source fields').props.onClick();await flush();const tree=h.render(props);assert.match(renderToStaticMarkup(tree),/field inspection could not be verified/);assert.doesNotMatch(renderToStaticMarkup(tree),/Late optional field/);assert.ok(button(tree,'Export complete CSV'));});

for(const status of [413,503])test(`failed ${status} field inspection preserves usable prior schema and result`,async()=>{const {h,props}=await setup(()=>{throw Object.assign(new Error('Field inspection unavailable; narrow source or retry.'),{status});});await button(h.render(props),'Review all source fields').props.onClick();await flush();const tree=h.render(props);assert.match(renderToStaticMarkup(tree),/Field inspection unavailable/);assert.ok(button(tree,'Export complete CSV'));assert.equal(button(tree,'Review all source fields').props.disabled,false);assert.doesNotMatch(renderToStaticMarkup(tree),/Late optional field/);});

for(const value of [10001,-10001,9007199254740990,[10001,-10001,9007199254740990]])test('saved rare monetary filter preserves exact cents through full field inspection '+JSON.stringify(value),async()=>{const report={...definition,id:'saved-money',version:1,columns:['metadata.amount'],filters:[{field:'metadata.amount',op:Array.isArray(value)?'in':'eq',value}]},review={...inspection,entities:[{...inspection.entities[0],fields:[...inspection.entities[0].fields,{key:'metadata.amount',label:'Metadata amount',type:'money',aggregateable:true,groupable:true}]}]}, {h,calls,props}=await setup(()=>review,[report]);let tree=h.render(props);find(tree,e=>e.type==='select'&&e.props.value==='').props.onChange({target:{value:report.id}});tree=h.render(props);await find(tree,e=>e.type==='form').props.onSubmit({preventDefault(){}});await flush();assert.match(renderToStaticMarkup(h.render(props)),/resolve each saved filter/);await button(h.render(props),'Review all source fields').props.onClick();await flush();tree=h.render(props);await find(tree,e=>e.type==='form').props.onSubmit({preventDefault(){}});await flush();const normalized=calls.at(-1)[1].body;assert.deepEqual(normalized.filters,report.filters);assert.equal(normalized.name,report.name);assert.equal(normalized.filters[0]._savedValue,undefined);});

test('explicit saved-filter value edit is respected as dollars instead of restoring original unresolved cents',async()=>{const report={...definition,id:'edited-money',version:1,columns:['metadata.amount'],filters:[{field:'metadata.amount',op:'eq',value:10001}]},review={...inspection,entities:[{...inspection.entities[0],fields:[...inspection.entities[0].fields,{key:'metadata.amount',label:'Metadata amount',type:'money',aggregateable:true,groupable:true}]}]}, {h,calls,props}=await setup(()=>review,[report]);find(h.render(props),e=>e.type==='select'&&e.props.value==='').props.onChange({target:{value:report.id}});let tree=h.render(props);const input=find(tree,e=>e.type==='input'&&e.props.value===10001);input.props.onChange({target:{value:'123.45'}});await button(h.render(props),'Review all source fields').props.onClick();await flush();await find(h.render(props),e=>e.type==='form').props.onSubmit({preventDefault(){}});await flush();assert.equal(calls.at(-1)[1].body.filters[0].value,12345);});

test('already known saved money filters roundtrip signed safe-range values without a one-cent drift',async()=>{const report={...definition,id:'known-extreme',version:1,filters:[{field:'amount',op:'in',value:[-9007199254740990,9007199254740990]}]},{h,calls,props}=await setup(()=>inspection,[report]);find(h.render(props),e=>e.type==='select'&&e.props.value==='').props.onChange({target:{value:report.id}});const tree=h.render(props);assert.ok(find(tree,e=>e.type==='input'&&e.props.value==='-90071992547409.90, 90071992547409.90'));await find(tree,e=>e.type==='form').props.onSubmit({preventDefault(){}});await flush();assert.deepEqual(calls.at(-1)[1].body.filters,report.filters);});

test('operator-only edits keep unresolved saved currency custody until field review',async()=>{const report={...definition,id:'operator-money',version:1,columns:['metadata.amount'],filters:[{field:'metadata.amount',op:'eq',value:10001}]},review={...inspection,entities:[{...inspection.entities[0],fields:[...inspection.entities[0].fields,{key:'metadata.amount',label:'Metadata amount',type:'money',aggregateable:true,groupable:true}]}]},{h,calls,props}=await setup(()=>review,[report]);find(h.render(props),e=>e.type==='select'&&e.props.value==='').props.onChange({target:{value:report.id}});let tree=h.render(props);assert.match(renderToStaticMarkup(tree),/metadata.amount · field not reviewed/);find(tree,e=>e.type==='select'&&e.props.value==='eq').props.onChange({target:{value:'gte'}});await button(h.render(props),'Review all source fields').props.onClick();await flush();await find(h.render(props),e=>e.type==='form').props.onSubmit({preventDefault(){}});await flush();assert.deepEqual(calls.at(-1)[1].body.filters,[{field:'metadata.amount',op:'gte',value:10001}]);});

test('unsafe typed money filter fails before a request rather than rounding into a different amount',async()=>{const {h,calls,props}=await setup(()=>inspection);const tree=h.render(props),input=find(tree,e=>e.type==='input'&&e.props.value==='');assert.ok(input);await button(tree,'Add filter').props.onClick();let edited=h.render(props);find(edited,e=>e.type==='select'&&e.props.value==='date').props.onChange({target:{value:'amount'}});edited=h.render(props);find(edited,e=>e.type==='input'&&e.props.required&&e.props.value==='').props.onChange({target:{value:'90071992547410.00'}});const previous=calls.length;await find(h.render(props),e=>e.type==='form').props.onSubmit({preventDefault(){}});await flush();assert.equal(calls.length,previous);assert.match(renderToStaticMarkup(h.render(props)),/filter amount is too large/);});
