import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {once} from 'node:events';
import {installReportingRoutes} from '../server/reporting.js';
import {buildReportCatalog,runCustomReport,validateReportDefinition} from '../src/reportEngine.js';
import {toCSV} from '../src/lib.js';
const person=randomUUID(),fundA=randomUUID(),fundB=randomUUID(),gift=randomUUID();
const records=()=>({constituents:[{id:person,name:'Example donor',notes:'User business notes',customRegion:'North',profile:{password:'HIDDEN',region:'West'},contacts:[{name:'Main contact',token:'HIDDEN'}],passwordHash:'HIDDEN'}],gifts:[{id:gift,constituentId:person,amount:10001,date:'2026-09-13',type:'Cash',status:'Posted',allocations:[{designationId:fundA,amount:6000},{designationId:fundB,amount:4001}]},{id:randomUUID(),amount:900,type:'Cash',status:'Voided',date:'2026-09-13',allocations:[{designationId:fundA,amount:900}]}],designations:[{id:fundA,name:'Scholarships',accountCode:'4100'},{id:fundB,name:'Programs',accountCode:'4200'}],tasks:[],events:[]});
const def=patch=>({name:'Giving report',entity:'gifts',columns:['donorName','amount'],...patch});

test('catalog discovers business and nested fields while excluding credentials, including in structured cells',()=>{const data=records(),catalog=buildReportCatalog(data),fields=catalog.entities.find(e=>e.id==='constituents').fields;assert.ok(fields.some(f=>f.key==='customRegion'));assert.ok(fields.some(f=>f.key==='notes'));assert.ok(fields.some(f=>f.key==='profile.region'));assert.ok(!fields.some(f=>/password|token/.test(f.key)));const result=runCustomReport(data,def({entity:'constituents',columns:['notes','profile','contacts']}),catalog);assert.match(JSON.stringify(result.rows),/User business notes|Main contact|West/);assert.doesNotMatch(JSON.stringify(result.rows),/HIDDEN|password|token/);});
test('gift projections remain one row per gift and joins do not multiply money',()=>{const r=runCustomReport(records(),def({columns:['donorName','designationNames','accountCodes','amount']}));assert.equal(r.matchedRows,1);assert.deepEqual(r.rows[0],['Example donor','Scholarships; Programs','4100; 4200',10001]);assert.equal(r.columns[3].unit,'cents');assert.equal(r.recordReferences[0].id,gift);});
test('allocations expose only split value, reconcile exact cents and group independently',()=>{const data=records(),catalog=buildReportCatalog(data);assert.ok(!catalog.entities.find(e=>e.id==='giftAllocations').fields.some(f=>f.key==='amount'));const r=runCustomReport(data,def({entity:'giftAllocations',columns:['designationName','allocationAmount'],groupBy:['accountCode'],aggregates:[{op:'sum',field:'allocationAmount'},{op:'count'}]}),catalog);assert.deepEqual(r.rows,[['4100',6000,1],['4200',4001,1]]);assert.equal(r.matchedRows,2);assert.equal(r.sourcePreview.rows.length,2);assert.equal(r.rows.reduce((n,x)=>n+x[1],0),10001);});
test('voided gifts are excluded by default but explicit inclusion is permitted',()=>{assert.equal(runCustomReport(records(),def()).matchedRows,1);assert.equal(runCustomReport(records(),def({includeVoided:true})).matchedRows,2);assert.equal(runCustomReport(records(),def({entity:'giftAllocations',columns:['allocationAmount'],includeVoided:true})).matchedRows,3);});
test('split mismatch and unsafe source or total cents reject rather than round',()=>{const a=records();a.gifts[0].allocations[0].amount++;assert.throws(()=>runCustomReport(a,def({entity:'giftAllocations',columns:['allocationAmount']})),/reconcile/);const b=records();b.gifts[0].amount=1.1;assert.throws(()=>runCustomReport(b,def()),/integer cents/);const c=records();c.gifts=[{...c.gifts[0],amount:Number.MAX_SAFE_INTEGER},{...c.gifts[0],id:randomUUID(),amount:1}];assert.throws(()=>runCustomReport(c,def({aggregates:[{op:'sum',field:'amount'}]})),/total exceeds/);});
test('strict field, cross-entity, type, SQL and fractional money definitions are rejected',()=>{const catalog=buildReportCatalog(records());for(const body of [def({columns:['passwordHash']}),def({columns:['name']}),def({entity:'sqlite_master'}),def({sql:'SELECT *'}),def({filters:[{field:'amount',op:'gte',value:1.2}]}),def({aggregates:[{op:'avg',field:'amount'}]}),def({groupBy:['allocations'],aggregates:[{op:'count'}]}),def({filters:[{field:'date',op:'eq',value:'2026-02-30'}]})])assert.throws(()=>validateReportDefinition(body,catalog));});
test('structured allocation cents are inspectable text while calculation uses the allocation entity',()=>{const r=runCustomReport(records(),def({columns:['allocations.amount']}));assert.deepEqual(r.rows,[['6000; 4001']]);assert.equal(r.columns[0].type,'text');});
test('filters and defaults use actual saved facts; zero-match totals remain exact',()=>{const r=runCustomReport(records(),def({filters:[{field:'amount',op:'gte',value:10002}],aggregates:[{op:'sum',field:'amount'},{op:'count'}]}));assert.deepEqual(r.rows,[[0,0]]);assert.equal(r.definition.includeVoided,false);assert.deepEqual(r.definition.groupBy,[]);});
test('output bounds preserve complete totals and source references; CSV protects spreadsheet formulas',()=>{const data=records();data.constituents=Array.from({length:300},()=>({id:randomUUID(),name:'=danger()',notes:'x'.repeat(9000)}));const r=runCustomReport(data,def({entity:'constituents',columns:['name','notes']}));assert.ok(r.rows.length<=250);assert.equal(r.totalResultRows,300);assert.equal(r.truncated,true);assert.equal(r.textTruncated,true);assert.equal(r.sourcePreview.rows.length,20);assert.match(toCSV(['Name'],[[r.rows[0][0]]]),/"'=danger\(\)"/);const totals=runCustomReport(data,def({entity:'constituents',columns:['name'],aggregates:[{op:'count'}]}));assert.deepEqual(totals.rows,[[300]]);});

async function fixture(t){const db=new DatabaseSync(':memory:'),data=records(),other=records();other.constituents[0].name='OTHER TENANT';const audits=[];const app=express();app.use(express.json());app.use((req,res,next)=>{req.tenantId=req.get('X-Tenant')||'first';if(req.get('X-Role')!=='anonymous')req.user={id:'user',role:req.get('X-Role')||'staff'};next();});const csrf=(req,res,next)=>req.get('X-CSRF-Token')==='test'?next():res.status(403).json({error:'CSRF'}),write=(req,res,next)=>['admin','staff'].includes(req.user?.role)?next():res.status(403).json({error:'Readonly'});const helpers=installReportingRoutes(app,{db,collections:Object.keys(data),list:(c,req)=>(req?.tenantId==='other'?other:data)[c]||[],csrf,write,audit:(...args)=>audits.push(args),transaction:fn=>{db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}});app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));const server=app.listen(0,'127.0.0.1');await once(server,'listening');t.after(async()=>{await new Promise(r=>server.close(r));db.close();});const request=async(path='',{method='GET',body,role='staff',tenant='first',token=true}={})=>{const r=await fetch(`http://127.0.0.1:${server.address().port}/api/custom-reports${path}`,{method,headers:{'Content-Type':'application/json','X-Role':role,'X-Tenant':tenant,...(token?{'X-CSRF-Token':'test'}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,json:await r.json()};};return {request,helpers,data,audits,db};}
test('definitions persist, viewer can read/run current records, staff edits are versioned and stale saves reject',async t=>{const f=await fixture(t);const create=await f.request('',{method:'POST',body:def()});assert.equal(create.status,201);const r=create.json.report;assert.equal(r.version,1);assert.equal(f.db.prepare('SELECT count(*) n FROM custom_reports').get().n,1);assert.equal((await f.request('',{role:'viewer'})).json.reports.length,1);f.data.gifts[0].amount=20001;const run=await f.request(`/${r.id}/run`,{role:'viewer'});assert.equal(run.status,200);assert.deepEqual(run.json.rows,[['Example donor',20001]]);assert.equal(run.json.version,1);const edit=await f.request(`/${r.id}`,{method:'PATCH',body:{...def({name:'Updated'}),version:1}});assert.equal(edit.status,200);assert.equal(edit.json.report.version,2);assert.equal((await f.request(`/${r.id}`,{method:'PATCH',body:{...def(),version:1}})).status,409);assert.equal(f.audits.length,2);assert.equal(f.helpers.runReport(r.id,{role:'viewer'},{tenantId:'first'}).version,2);assert.throws(()=>f.helpers.runReport(r.id,{role:'suspended'},{tenantId:'first'}),/role/);});
test('viewer writes, missing CSRF and anonymous reads deny while CSRF viewer preview is read-only',async t=>{const f=await fixture(t);assert.equal((await f.request('',{method:'POST',body:def(),role:'viewer'})).status,403);assert.equal((await f.request('',{method:'POST',body:def(),token:false})).status,403);assert.equal((await f.request('',{role:'anonymous'})).status,401);assert.equal((await f.request('/run',{method:'POST',body:def(),role:'viewer'})).status,200);assert.equal((await f.request('/run',{method:'POST',body:def(),role:'viewer',token:false})).status,403);assert.equal(f.audits.length,0);});
test('tenant definitions and current record joins never leak across scope',async t=>{const f=await fixture(t),created=await f.request('',{method:'POST',body:def()});assert.equal((await f.request('',{tenant:'other'})).json.reports.length,0);assert.equal((await f.request(`/${created.json.report.id}/run`,{tenant:'other'})).status,404);const own=await f.request('/run',{method:'POST',tenant:'other',body:def()});assert.equal(own.json.rows[0][0],'OTHER TENANT');const first=await f.request(`/${created.json.report.id}/run`);assert.doesNotMatch(JSON.stringify(first.json),/OTHER TENANT/);});
test('saved definition with removed dynamic field cannot silently rerun against a changed schema',async t=>{const f=await fixture(t);const created=await f.request('',{method:'POST',body:def({entity:'constituents',columns:['customRegion']})});delete f.data.constituents[0].customRegion;const run=await f.request(`/${created.json.report.id}/run`);assert.equal(run.status,400);assert.match(run.json.error,/fields/);});

async function integratedFixture(t){
 const {mkdtemp,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{createApp}=await import('../server/app.js');
 const dir=await mkdtemp(join(tmpdir(),'wimblo-report-metadata-')),dbPath=join(dir,'business.sqlite');let app,server,base;
 async function open(){app=createApp({dbPath,seed:true});server=app.listen(0,'127.0.0.1');await once(server,'listening');base=`http://127.0.0.1:${server.address().port}`;}
 async function close(){if(server)await new Promise(resolve=>server.close(resolve));server=null;app?.locals.close();app=null;}
 await open();t.after(async()=>{await close();await rm(dir,{recursive:true,force:true});});
 async function request(path,{method='GET',body,session}={}){const headers={};if(body!==undefined)headers['Content-Type']='application/json';if(session){headers.Cookie=session.cookie;headers['X-CSRF-Token']=session.csrfToken;}const r=await fetch(base+'/api'+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,json:await r.json()};}
 async function login(email){const r=await fetch(base+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:'FoundationDemo!2026'})});assert.equal(r.status,200);return {...await r.json(),cookie:r.headers.get('set-cookie').split(';')[0]};}
 const admin=await login('alex@foundation.example'),staff=await login('staff@foundation.example'),viewer=await login('board@foundation.example');
 async function create(collection,body){const r=await request('/records/'+collection,{method:'POST',session:admin,body});assert.equal(r.status,201,JSON.stringify(r.json));return r.json.record;}
 async function run(entity,columns,session=admin,extra={}){const r=await request('/custom-reports/run',{method:'POST',session,body:{name:'Metadata proof',entity,columns,...extra}});assert.equal(r.status,200,JSON.stringify(r.json));return r.json;}
 async function catalog(session=admin){const r=await request('/custom-reports/catalog',{session});assert.equal(r.status,200,JSON.stringify(r.json));return r.json;}
 return {request,create,run,catalog,login,admin,staff,viewer,get app(){return app;},get db(){return app.locals.db;},restart:async()=>{await close();await open();}};
}

test('current metadata catalog discovers later installers and exposes stable units without security tables',async t=>{
 const f=await integratedFixture(t),admin=await f.catalog(),staff=await f.catalog(f.staff);
 const names=['documents','documentRevisions','households','householdMemberships','identityAliases','migrationBatches','migrationMappings','customReportDefinitions','reportSchedules','reportDeliveries','correspondenceTemplates','correspondenceTemplateRevisions','correspondencePreparations','correspondenceFinalizations'];
 for(const name of names)assert.ok(admin.entities.some(e=>e.id===name),name);
 for(const name of ['identityAliases','migrationBatches','migrationMappings'])assert.equal(staff.entities.some(e=>e.id===name),false,name);
 const document=admin.entities.find(e=>e.id==='documents');assert.equal(document.fields.find(v=>v.key==='latestSize').unit,'bytes');assert.equal(document.fields.find(v=>v.key==='revisionCount').type,'number');
 const money=admin.entities.find(e=>e.id==='migrationBatches').fields.find(v=>v.key==='newGiftTotalCents');assert.equal(money.type,'money');assert.equal(money.unit,'cents');assert.equal(money.currency,'USD');
 assert.doesNotMatch(JSON.stringify(admin.entities.map(e=>({id:e.id,fields:e.fields.map(f=>f.key)}))),/contentBase64|source_snapshot|password_hash|sessions|mfa_credentials|record_hash|source_hash|snapshot/);
});

test('document and revision metadata obey current visibility and omit actual bytes and injected JSON keys',async t=>{
 const f=await integratedFixture(t),task=await f.create('tasks',{title:'Document metadata proof',dueDate:'2026-09-13',status:'Open'}),bytes=Buffer.from('PRIVATE FILE BYTES NEVER IN REPORT\n');
 const upload=async visibility=>{const r=await f.request('/documents',{method:'POST',session:f.admin,body:{collection:'tasks',recordId:task.id,title:visibility==='Administrators'?'PRIVATE DOCUMENT TITLE':'Shared document',category:'Attachment',visibility,status:'Draft',evidenceDate:null,filename:'proof.txt',contentBase64:bytes.toString('base64')}});assert.equal(r.status,201);return r.json.document;};
 const shared=await upload('Workspace'),privateDoc=await upload('Administrators');
 const admin=await f.run('documents',['title','latestSize','revisionCount']);assert.equal(admin.requiredRole,'admin');assert.equal(admin.rows.length,2);
 for(const session of [f.staff,f.viewer]){const live=await f.run('documents',['title','latestSize'],session);assert.deepEqual(live.rows,[['Shared document',bytes.length]]);assert.equal(live.requiredRole,'authenticated');const revisions=await f.run('documentRevisions',['title','filename','sha256','metadata'],session);assert.equal(revisions.rows.length,1);assert.doesNotMatch(JSON.stringify(revisions),/PRIVATE DOCUMENT TITLE|PRIVATE FILE BYTES NEVER IN REPORT/);}
 f.db.exec('DROP TRIGGER document_revision_no_update');f.db.prepare('UPDATE document_revisions SET metadata=? WHERE document_id=?').run(JSON.stringify({title:'Shared document',category:'Attachment',visibility:'Workspace',status:'Draft',evidenceDate:null,contentBase64:'FILE_SECRET',source_snapshot:{password:'AUTH_SECRET'},unexpected:'UNALLOWLISTED'}),shared.id);
 const sanitized=await f.run('documentRevisions',['metadata']);assert.doesNotMatch(JSON.stringify(sanitized.rows),/FILE_SECRET|AUTH_SECRET|UNALLOWLISTED|contentBase64|source_snapshot|password/);
 for(const field of ['bytes','contentBase64','metadata.contentBase64'])assert.equal((await f.request('/custom-reports/run',{method:'POST',session:f.admin,body:{name:'Forbidden file',entity:'documentRevisions',columns:[field]}})).status,400);
 assert.ok(privateDoc.id);
});

test('admin-only provenance reports deny unauthorized saved-definition reads and never expose original snapshots or hashes',async t=>{
 const f=await integratedFixture(t),a=await f.create('constituents',{name:'Canonical metadata person',type:'Individual'}),b=await f.create('constituents',{name:'Duplicate metadata person',type:'Individual',notes:'RAW IDENTITY SNAPSHOT SECRET'}),body={targetId:a.id,sourceId:b.id,targetVersion:1,sourceVersion:1,reason:'Verified same person'};
 const p=await f.request('/identity/merge/preview',{method:'POST',session:f.admin,body});assert.equal(p.status,200);assert.equal((await f.request('/identity/merge',{method:'POST',session:f.admin,body:{...body,previewDigest:p.json.preview.previewDigest}})).status,200);
 const report=await f.request('/custom-reports',{method:'POST',session:f.admin,body:{name:'Alias provenance',entity:'identityAliases',columns:['sourceName','targetName','reason']}});assert.equal(report.status,201);
 const definitions=await f.run('customReportDefinitions',['name','entity']);assert.equal(definitions.requiredRole,'admin');
 const run=await f.request('/custom-reports/'+report.json.report.id+'/run',{session:f.admin});assert.equal(run.status,200);assert.equal(run.json.requiredRole,'admin');assert.doesNotMatch(JSON.stringify(run.json.rows),/RAW IDENTITY SNAPSHOT SECRET|source_snapshot/);
 for(const session of [f.staff,f.viewer]){assert.equal((await f.request('/custom-reports/'+report.json.report.id+'/run',{session})).status,403);assert.equal((await f.request('/custom-reports',{session})).json.reports.some(r=>r.id===report.json.report.id),false);assert.equal((await f.run('customReportDefinitions',['name','entity'],session)).rows.some(r=>r[0]==='Alias provenance'),false);}
});

test('household, migration, saved-definition and correspondence metadata report exact current facts and survive restart',async t=>{
 const f=await integratedFixture(t),member=await f.create('constituents',{name:'Reporting household member',type:'Individual',email:'member@example.test'});
 const h=await f.request('/households',{method:'POST',session:f.admin,body:{name:'Reporting family',address:'Synthetic address',memberIds:[member.id]}});assert.equal(h.status,201);
 const payload={source:'Test normalized source',fileKey:'metadata-import.csv',files:[{collection:'constituents',mapping:{sourceId:'id',name:'name',type:'type'},rows:[{id:'source-person',name:'Imported metadata person',type:'Individual'}]},{collection:'designations',mapping:{sourceId:'id',name:'name',accountCode:'code'},rows:[{id:'source-fund',name:'Imported metadata fund',code:'META-TEST'}]},{collection:'gifts',mapping:{sourceId:'id',donorSourceId:'donor',designationSourceId:'fund',amount:'amount',type:'type',method:'method',date:'date',externalRef:'ref'},rows:[{id:'source-gift',donor:'source-person',fund:'source-fund',amount:'100.01',type:'Cash',method:'Check',date:'2026-08-01',ref:'METADATA-IMPORT'}]}]};
 const preview=await f.request('/migration/preview',{method:'POST',session:f.admin,body:payload});assert.equal(preview.status,200,JSON.stringify(preview.json));assert.equal(preview.json.valid,true,JSON.stringify(preview.json));assert.equal((await f.request('/migration/commit',{method:'POST',session:f.admin,body:{...payload,previewDigest:preview.json.previewDigest}})).status,201);
 const batch=await f.run('migrationBatches',['totalRows','createCount','giftCount','newGiftTotalCents','actualNewGiftCents']);assert.deepEqual(batch.rows,[[3,3,1,10001,10001]]);assert.equal(batch.columns[3].unit,'cents');
 const maps=await f.run('migrationMappings',['source','collection','externalId','recordId']);assert.equal(maps.rows.length,3);assert.doesNotMatch(JSON.stringify(maps),/record_hash|source_hash|preview_digest/);
 const saved=await f.request('/custom-reports',{method:'POST',session:f.admin,body:{name:'Managed reporting family',entity:'householdMemberships',columns:['householdName','constituentName']}});assert.equal(saved.status,201);
 const template=await f.request('/correspondence/templates',{method:'POST',session:f.admin,body:{name:'Reporting message',kind:'Messaging',subject:'Hello {{recipientName}}',body:'Shared reporting proof'}});assert.equal(template.status,201);
 const prep=await f.request('/correspondence/prepare',{method:'POST',session:f.admin,body:{templateId:template.json.template.id,templateVersion:1,channel:'Print',constituentIds:[member.id]}});assert.equal(prep.status,201,JSON.stringify(prep.json));
 assert.equal((await f.request('/correspondence/'+prep.json.correspondence.id+'/finalize',{method:'POST',session:f.admin,body:{version:1,preparationDigest:prep.json.correspondence.preparationDigest,confirmed:true}})).status,200);
 const correspondence=await f.run('correspondencePreparations',['templateName','recipientCount','monetaryCents','noncashCents','status','delivery'],f.viewer);assert.deepEqual(correspondence.rows,[['Reporting message',1,0,0,'Finalized','Not sent']]);assert.equal(correspondence.columns[2].unit,'cents');
 const household=await f.run('householdMemberships',['householdName','constituentName']);assert.deepEqual(household.rows,[['Reporting family',member.name]]);assert.deepEqual(household.recordReferences,[{collection:'constituents',id:member.id}]);
 const expected={batch:batch.rows,household:household.rows,correspondence:correspondence.rows};await f.restart();assert.deepEqual((await f.run('migrationBatches',['totalRows','createCount','giftCount','newGiftTotalCents','actualNewGiftCents'])).rows,expected.batch);assert.deepEqual((await f.run('householdMemberships',['householdName','constituentName'])).rows,expected.household);assert.deepEqual((await f.run('correspondencePreparations',['templateName','recipientCount','monetaryCents','noncashCents','status','delivery'])).rows,expected.correspondence);
 assert.ok((await f.catalog()).entities.some(e=>e.id==='correspondenceFinalizations'));
});

test('scheduled reports use the current owner role and result metadata never exposes saved report cells',async t=>{
 const f=await integratedFixture(t),task=await f.create('tasks',{title:'Scheduled private document',dueDate:'2026-09-13',status:'Open'});
 assert.equal((await f.request('/documents',{method:'POST',session:f.admin,body:{collection:'tasks',recordId:task.id,title:'SCHEDULE PRIVATE TITLE',category:'Attachment',visibility:'Administrators',status:'Draft',evidenceDate:null,filename:'private.txt',contentBase64:Buffer.from('SCHEDULE PRIVATE BYTES').toString('base64')}})).status,201);
 const report=await f.request('/custom-reports',{method:'POST',session:f.admin,body:{name:'Private metadata schedule',entity:'documents',columns:['title']}});assert.equal(report.status,201);
 const startAt=new Date(Date.now()+30000).toISOString(),schedule=await f.request('/report-schedules',{method:'POST',session:f.admin,body:{reportId:report.json.report.id,name:'Private metadata schedule',cadence:'Daily',startAt}});assert.equal(schedule.status,201);
 assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1000).produced,1);
 const stored=JSON.parse(f.db.prepare('SELECT result FROM report_deliveries WHERE schedule_id=?').get(schedule.json.schedule.id).result);assert.equal(stored.requiredRole,'admin');assert.deepEqual(stored.rows,[['SCHEDULE PRIVATE TITLE']]);
 const admin=await f.run('reportDeliveries',['name','resultSummary']);assert.equal(admin.requiredRole,'admin');assert.equal(JSON.parse(admin.rows[0][1]).matchedRows,1);assert.doesNotMatch(JSON.stringify(admin.rows),/SCHEDULE PRIVATE TITLE|SCHEDULE PRIVATE BYTES|sourcePreview|USD|currency/);
 for(const session of [f.staff,f.viewer]){const metadata=await f.run('reportDeliveries',['name','resultSummary'],session);assert.equal(metadata.rows[0][1],null);assert.equal(metadata.requiredRole,'authenticated');}
 const indirect=await f.request('/custom-reports',{method:'POST',session:f.admin,body:{name:'Derived private counts',entity:'reportDeliveries',columns:['resultSummary']}});assert.equal(indirect.status,201);
 const indirectStart=new Date(Date.now()+45000).toISOString(),indirectSchedule=await f.request('/report-schedules',{method:'POST',session:f.admin,body:{reportId:indirect.json.report.id,name:'Derived private counts',cadence:'Daily',startAt:indirectStart}});assert.equal(indirectSchedule.status,201);assert.equal(f.app.locals.runDueReports(Date.parse(indirectStart)+1000).produced,1);
 const indirectStored=f.db.prepare('SELECT id,result FROM report_deliveries WHERE schedule_id=?').get(indirectSchedule.json.schedule.id);assert.equal(JSON.parse(indirectStored.result).requiredRole,'admin');assert.equal((await f.request('/report-deliveries/'+indirectStored.id,{session:f.viewer})).status,403);
 const id=f.db.prepare('SELECT id FROM report_deliveries WHERE schedule_id=?').get(schedule.json.schedule.id).id;
 for(const session of [f.staff,f.viewer])assert.equal((await f.request('/report-deliveries/'+id,{session})).status,403);
 // A staff-owned schedule must use staff visibility even though the worker has no HTTP request object.
 const staffReport=await f.request('/custom-reports',{method:'POST',session:f.staff,body:{name:'Staff live metadata',entity:'documents',columns:['title']}});assert.equal(staffReport.status,201);
 const nextStart=new Date(Date.now()+60000).toISOString(),staffSchedule=await f.request('/report-schedules',{method:'POST',session:f.staff,body:{reportId:staffReport.json.report.id,name:'Staff live metadata',cadence:'Daily',startAt:nextStart}});assert.equal(staffSchedule.status,201);assert.equal(f.app.locals.runDueReports(Date.parse(nextStart)+1000).produced,1);
 const staffStored=JSON.parse(f.db.prepare('SELECT result FROM report_deliveries WHERE schedule_id=?').get(staffSchedule.json.schedule.id).result);assert.equal(staffStored.requiredRole,'authenticated');assert.deepEqual(staffStored.rows,[]);
});

async function reportingGift(f,donor,amount,changes={}){const funds=(await f.request('/workspace',{session:f.admin})).json.data.designations;return f.create('gifts',{constituentId:donor.id,amount,type:'Cash',method:'Check',date:'2026-01-01',allocations:[{designationId:funds[0].id,amount}],...changes});}
async function reportingPost(f,path,body,status=201){const r=await f.request(path,{method:'POST',session:f.admin,body});assert.equal(r.status,status,JSON.stringify(r.json));return r.json;}

test('fundraising report sources retain versions and exact linked cents while voids and unlinking stop received income',async t=>{
 const f=await integratedFixture(t),donor=await f.create('constituents',{name:'Synthetic planned donor',type:'Individual'}),g=await reportingGift(f,donor,10001,{giftKind:'Planned gift'});
 const definition={kind:'planned',name:'Synthetic documented intention',donorId:donor.id,instrument:'Bequest',commitmentAmount:20002,status:'Documented',campaignId:null,notes:'Business planning note'};
 let r=(await reportingPost(f,'/fundraising',definition)).record;
 r=(await reportingPost(f,`/fundraising/${r.id}/receipts`,{version:r.version,giftId:g.id,giftVersion:g.version},200)).record;
 const current=await f.run('fundraisingRecords',['name','commitmentAmount','revision','notes'],f.viewer);assert.deepEqual(current.rows,[['Synthetic documented intention',20002,2,'Business planning note']]);assert.equal(current.columns[1].unit,'cents');assert.match(current.scope,/not (?:received |new )?income/i);
 const versions=await f.run('fundraisingVersions',['revision','commitmentAmount']);assert.deepEqual(versions.rows,[[1,20002],[2,20002]]);
 const columns=['associatedAmountCents','currentGiftAmountCents','receivedAmountCents','status'];assert.deepEqual((await f.run('fundraisingAssociations',columns)).rows,[[10001,10001,10001,'active']]);
 const voided=await f.request(`/gifts/${g.id}/void`,{method:'POST',session:f.admin,body:{version:g.version,reason:'Synthetic report reversal'}});assert.equal(voided.status,200,JSON.stringify(voided.json));assert.deepEqual((await f.run('fundraisingAssociations',columns)).rows,[[10001,10001,0,'active']]);
 const a=r.associations[0];r=(await reportingPost(f,`/fundraising/${r.id}/receipts/${a.id}/unlink`,{version:r.version,associationVersion:a.version,reason:'Void reconciliation'},200)).record;
 assert.deepEqual((await f.run('fundraisingAssociations',[...columns,'unlinkReason'])).rows,[[10001,10001,0,'unlinked','Void reconciliation']]);
 const stored=JSON.parse(f.db.prepare('SELECT data FROM fundraising_records WHERE id=?').get(r.id).data);stored.password='PRIVATE_EXTRA';stored.originalSnapshot={amount:10001,version:1,email:'PRIVATE_EMAIL',privateNotes:'PRIVATE_SNAPSHOT'};f.db.prepare('UPDATE fundraising_records SET data=? WHERE id=?').run(JSON.stringify(stored),r.id);
 const safe=await f.run('fundraisingRecords',['name','originalGiftAmountCents']);assert.doesNotMatch(JSON.stringify(safe),/PRIVATE_EXTRA|PRIVATE_EMAIL|PRIVATE_SNAPSHOT/);
 await f.restart();assert.deepEqual((await f.run('fundraisingAssociations',columns)).rows,[[10001,10001,0,'unlinked']]);
});

test('receipt reports expose retained coverage and staff confirmation without recipient email, raw profiles or legal certification',async t=>{
 const f=await integratedFixture(t),donor=await f.create('constituents',{name:'Synthetic receipt recipient',type:'Individual',email:'PRIVATE_RECIPIENT@example.test'}),g=await reportingGift(f,donor,12345);
 const profile={version:0,organizationName:'Synthetic receipt organization',address:'PRIVATE_POSTAL_ADDRESS',taxIdentifier:'PRIVATE_TAX_ID',signatureLabel:'Approved signer',customFooter:'Synthetic footer',approved:true};
 const configured=await f.request('/receipt-profile',{method:'PUT',session:f.admin,body:profile});assert.equal(configured.status,200,JSON.stringify(configured.json));
 const prep=(await reportingPost(f,'/receipts/prepare',{kind:'Individual',giftId:g.id,profileVersion:1,benefitsReviewed:true,revenueClassification:'Contribution',benefitsAssessment:'None provided'})).receipt;
 await reportingPost(f,`/receipts/${prep.id}/issue`,{version:1,preparationDigest:prep.preparationDigest,channel:'Print',printed:true,handSigned:true,issueDate:'2026-01-02'},200);
 const columns=['recipientName','monetaryCents','taxDeductibility','status','staffConfirmedPrint','staffConfirmedHandSign'];const issued=await f.run('receiptHistory',columns,f.viewer);assert.deepEqual(issued.rows,[['Synthetic receipt recipient',12345,'Not determined','Issued',true,true]]);assert.equal(issued.columns[1].unit,'cents');assert.match(issued.scope,/not (?:received |new )?income/i);assert.doesNotMatch(JSON.stringify(issued),/PRIVATE_RECIPIENT|PRIVATE_POSTAL_ADDRESS|PRIVATE_TAX_ID|snapshot|digest/);
 const read=await f.request('/receipts/'+prep.id,{session:f.admin});await reportingPost(f,`/receipts/${prep.id}/void`,{version:read.json.receipt.version,reason:'Synthetic correction'},200);
 assert.deepEqual((await f.run('receiptGiftReferences',['giftId','monetaryCents','receiptStatus'],f.viewer)).rows,[[g.id,12345,'Voided']]);assert.equal((await f.run('receiptHistory',columns)).rows[0][3],'Voided');
 assert.deepEqual((await f.run('receiptProfiles',['organizationName','taxIdentifier'])).rows,[['Synthetic receipt organization','PRIVATE_TAX_ID']]);
 for(const field of ['snapshot','recipient.email','profile','preparationDigest'])assert.equal((await f.request('/custom-reports/run',{method:'POST',session:f.admin,body:{name:'Private receipt',entity:'receiptHistory',columns:[field]}})).status,400);
});

test('event reports distinguish exact ticket, sponsorship and bid commitments from existing posted and future payment receipts',async t=>{
 const f=await integratedFixture(t),person=await f.create('constituents',{name:'Synthetic event attendee',type:'Individual'}),sponsor=await f.create('constituents',{name:'Synthetic event sponsor',type:'Business'}),event=await f.create('events',{name:'Synthetic reporting benefit',date:'2026-10-01',capacity:4,ticketPrice:10001,sponsorGoal:50000});
 await reportingPost(f,`/events/${event.id}/register`,{constituentId:person.id},200);const e=(await f.request('/workspace',{session:f.admin})).json.data.events.find(x=>x.id===event.id),base={eventId:e.id,eventVersion:e.version};
 const table=(await reportingPost(f,`/event-operations/events/${e.id}/seating`,{eventVersion:e.version,name:'Reporting table',seats:2})).seating;
 await reportingPost(f,`/event-operations/seating/${table.id}/assign`,{tableVersion:table.version,eventVersion:e.version,constituentId:person.id,seatNumber:1});
 await reportingPost(f,`/event-operations/events/${e.id}/tickets`,{eventVersion:e.version,constituentId:person.id});
 let agreement=(await reportingPost(f,'/event-operations/sponsorships',{...base,sponsorId:sponsor.id,name:'Reporting sponsor commitment',amount:50000,benefits:[{name:'Recognition',completed:false}]})).sponsorship;
 let item=(await reportingPost(f,'/event-operations/auction-items',{...base,name:'Synthetic auction item',startingBid:10001,minIncrement:500,description:'Inventory description'})).item;
 item=(await reportingPost(f,`/event-operations/auction-items/${item.id}/bids`,{version:item.version,bidderId:person.id,amount:10001})).item;
 const g=await reportingGift(f,sponsor,20001,{type:'Sponsorship'});await reportingPost(f,'/event-operations/payments',{ownerType:'sponsorship',ownerId:agreement.id,version:agreement.version,giftId:g.id,giftVersion:g.version,revenueCase:'Sponsorship'});
 assert.deepEqual((await f.run('eventTables',['eventName','seats'])).rows,[['Synthetic reporting benefit',2]]);assert.deepEqual((await f.run('eventSeatAssignments',['constituentName','seatNumber'])).rows,[['Synthetic event attendee',1]]);
 const tickets=await f.run('eventTickets',['priceCents']);assert.deepEqual(tickets.rows,[[10001]]);assert.equal(tickets.columns[0].unit,'cents');assert.match(tickets.scope,/not (?:received |new )?income/i);
 assert.deepEqual((await f.run('eventSponsors',['commitmentAmountCents'])).rows,[[50000]]);assert.deepEqual((await f.run('eventAuctionItems',['startingBidCents','minIncrementCents'])).rows,[[10001,500]]);assert.deepEqual((await f.run('eventAuctionBids',['amountCents'])).rows,[[10001]]);
 assert.deepEqual((await f.run('eventPayments',['amountCents','receivedAmountCents'],f.viewer)).rows,[[20001,20001]]);
 const changed=await f.request(`/gifts/${g.id}/void`,{method:'POST',session:f.admin,body:{version:g.version,reason:'Synthetic report reversal'}});assert.equal(changed.status,200);assert.deepEqual((await f.run('eventPayments',['amountCents','receivedAmountCents'])).rows,[[20001,0]]);
 const future=await reportingGift(f,sponsor,30000,{type:'Sponsorship',date:'2099-01-01'});await reportingPost(f,'/event-operations/payments',{ownerType:'sponsorship',ownerId:agreement.id,version:2,giftId:future.id,giftVersion:future.version,revenueCase:'Sponsorship'});
 const payments=await f.run('eventPayments',['amountCents','receivedAmountCents'],f.viewer);assert.deepEqual(payments.rows.map(r=>r[0]).sort((a,b)=>a-b),[20001,30000]);assert.equal(payments.rows.reduce((n,r)=>n+r[1],0),0);
 f.db.prepare('UPDATE event_sponsorships SET benefits=? WHERE id=?').run(JSON.stringify([{name:'Recognition',completed:false,email:'PRIVATE_BENEFIT_EMAIL',secret:'PRIVATE_BENEFIT_SECRET'}]),agreement.id);assert.doesNotMatch(JSON.stringify((await f.run('eventSponsors',['benefits'])).rows),/PRIVATE_BENEFIT/);
 await f.restart();assert.equal((await f.run('eventPayments',['receivedAmountCents'])).rows.reduce((n,r)=>n+r[0],0),0);
});

test('administrative report sources deny creation, previews, edits and reruns after role changes, and protect retained schedule results',async t=>{
 const f=await integratedFixture(t),sources=['workspaceUsers','workspaceSettings','auditHistory','receiptProfiles','receiptProfileRevisions'];
 const catalog=await f.catalog();for(const entity of sources){assert.equal(catalog.entities.find(e=>e.id===entity).requiredRole,'admin');for(const session of [f.staff,f.viewer]){assert.equal((await f.catalog(session)).entities.some(e=>e.id===entity),false);const body={name:'Protected source',entity,columns:[entity==='workspaceUsers'?'name':entity==='workspaceSettings'?'organizationName':entity==='auditHistory'?'action':'organizationName']};assert.equal((await f.request('/custom-reports/run',{method:'POST',session,body})).status,403);assert.equal((await f.request('/custom-reports',{method:'POST',session,body})).status,403);}}
 const users=await f.run('workspaceUsers',['name','email','role','active']);assert.equal(users.requiredRole,'admin');assert.doesNotMatch(JSON.stringify(users),/password_hash|FoundationDemo|mfa_|session|token|encrypted/i);
 const audit=await f.run('auditHistory',['action','detailCount']);assert.equal(audit.requiredRole,'admin');assert.equal(audit.columns[1].type,'number');assert.doesNotMatch(JSON.stringify(audit),/password_hash|details\"|csrfToken/);
 const definition={name:'Administrative user report',entity:'workspaceUsers',columns:['name']},created=await f.request('/custom-reports',{method:'POST',session:f.admin,body:definition});assert.equal(created.status,201);const id=created.json.report.id;
 for(const session of [f.staff,f.viewer]){assert.equal((await f.request(`/custom-reports/${id}/run`,{session})).status,403);assert.equal((await f.request(`/custom-reports/${id}`,{method:'PATCH',session,body:{...definition,version:1}})).status,403);assert.equal((await f.request('/custom-reports',{session})).json.reports.some(r=>r.id===id),false);}
 const startAt=new Date(Date.now()+30000).toISOString(),schedule=await reportingPost(f,'/report-schedules',{name:'Protected user schedule',reportId:id,cadence:'Daily',startAt});assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1000).produced,1);const delivery=f.db.prepare('SELECT id,result FROM report_deliveries WHERE schedule_id=?').get(schedule.schedule.id);assert.equal(JSON.parse(delivery.result).requiredRole,'admin');assert.equal((await f.request('/report-deliveries/'+delivery.id,{session:f.viewer})).status,403);
 f.db.prepare('UPDATE users SET role=? WHERE id=?').run('staff',f.admin.user.id);assert.equal((await f.request(`/custom-reports/${id}/run`,{session:f.admin})).status,401);const changed=await f.login('alex@foundation.example');assert.equal(changed.user.role,'staff');assert.equal((await f.request(`/custom-reports/${id}/run`,{session:changed})).status,403);
});

async function reportingGrantFixture(f,name,visibility='Workspace'){
 const funder=await f.create('constituents',{name:'Synthetic milestone funder',type:'Foundation'}),grant=await f.create('grants',{name, funderId:funder.id,amount:12345,awardedAmount:10001,awardDate:'2026-01-01',stage:'Awarded',deadline:'2026-01-02'});
 const milestone=(await reportingPost(f,'/grant-operations',{grantId:grant.id,grantVersion:grant.version,name:name+' milestone',kind:'Report',dueDate:'2026-01-02',ownerId:f.staff.user.id,ownerVersion:1})).milestone;
 const doc=(await reportingPost(f,'/documents',{collection:'grants',recordId:grant.id,title:name+' documentary evidence',category:'Report',visibility,status:'Final',evidenceDate:'2026-01-02',filename:'evidence.txt',contentBase64:Buffer.from('PRIVATE_DOCUMENT_BYTES').toString('base64')})).document;
 const done=(await reportingPost(f,`/grant-operations/${milestone.id}/complete`,{version:milestone.version,grantVersion:grant.version,ownerVersion:1,documentId:doc.id,documentVersion:doc.version,revision:1,completedDate:'2026-01-03',reference:name+' verified reference',confirmed:true},200)).milestone;
 return {grant,doc,milestone:done};
}

test('grant reporting obeys whole-milestone current and retained evidence privacy while preserving cents, units and source versions',async t=>{
 const f=await integratedFixture(t),shared=await reportingGrantFixture(f,'Public report'),privateGrant=await reportingGrantFixture(f,'PRIVATE_REPORT','Administrators');
 for(const session of [f.staff,f.viewer]){
  const current=await f.run('grantMilestones',['grantName','requestedAmountCents','awardedAmountCents','grantRevision','revision'],session);assert.deepEqual(current.rows,[['Public report',12345,10001,1,2]]);assert.equal(current.columns[1].unit,'cents');assert.equal(current.columns[2].unit,'cents');assert.equal(current.columns[2].type,'money');assert.equal(current.requiredRole,'authenticated');
  const versions=await f.run('grantMilestoneVersions',['grantName','revision'],session);assert.deepEqual(versions.rows,[['Public report',1],['Public report',2]]);
  const evidence=await f.run('grantMilestoneEvidence',['documentTitle','documentSize','completedDate','staffConfirmed'],session);assert.deepEqual(evidence.rows,[['Public report documentary evidence',Buffer.byteLength('PRIVATE_DOCUMENT_BYTES'),'2026-01-03',true]]);assert.equal(evidence.columns[1].unit,'bytes');assert.doesNotMatch(JSON.stringify(evidence),/PRIVATE_REPORT|PRIVATE_DOCUMENT_BYTES|snapshot|sha256/);
 }
 const admin=await f.run('grantMilestoneEvidence',['grantName','completionReference']);assert.equal(admin.requiredRole,'admin');assert.equal(admin.rows.length,2);
 const reopened=(await reportingPost(f,`/grant-operations/${privateGrant.milestone.id}/reopen`,{version:2,reason:'Private evidence correction'},200)).milestone;assert.equal(reopened.version,3);
 await reportingPost(f,`/documents/${privateGrant.doc.id}/revisions`,{version:1,title:'Now public evidence',category:'Report',visibility:'Workspace',status:'Final',evidenceDate:'2026-01-02',filename:'public.txt',contentBase64:Buffer.from('Public later revision').toString('base64')},200);
 for(const session of [f.staff,f.viewer]){assert.equal((await f.run('grantMilestones',['grantName'],session)).rows.length,1);assert.equal((await f.run('grantMilestoneVersions',['grantName'],session)).rows.length,2);assert.equal((await f.run('grantMilestoneEvidence',['grantName'],session)).rows.length,1);}
 // A formerly public completion becomes hidden if its current source document becomes private.
 await reportingPost(f,`/documents/${shared.doc.id}/revisions`,{version:1,title:'PRIVATE_CURRENT_DOCUMENT',category:'Report',visibility:'Administrators',status:'Final',evidenceDate:'2026-01-02',filename:'private.txt',contentBase64:Buffer.from('Current private bytes').toString('base64')},200);
 for(const session of [f.staff,f.viewer])for(const entity of ['grantMilestones','grantMilestoneVersions','grantMilestoneEvidence'])assert.equal((await f.run(entity,['grantName'],session)).rows.length,0);
 for(const field of ['snapshot','completion','source','document.bytes','document.sha256'])assert.equal((await f.request('/custom-reports/run',{method:'POST',session:f.admin,body:{name:'Forbidden evidence',entity:'grantMilestoneEvidence',columns:[field]}})).status,400);
 await f.restart();assert.equal((await f.run('grantMilestoneEvidence',['grantName'],f.viewer)).rows.length,0);assert.equal((await f.run('grantMilestoneEvidence',['grantName'])).rows.length,2);
});

test('grant schedules bind administrator snapshots and nonadministrator schedules never include private retained evidence',async t=>{
 const f=await integratedFixture(t);await reportingGrantFixture(f,'PRIVATE_SCHEDULE_REPORT','Administrators');
 const reports=[];
 for(const session of [f.admin,f.staff]){const r=await f.request('/custom-reports',{method:'POST',session,body:{name:'Evidence schedule '+session.user.role,entity:'grantMilestoneEvidence',columns:['documentTitle']}});assert.equal(r.status,201);const startAt=new Date(Date.now()+30000+(reports.length*5000)).toISOString(),schedule=await f.request('/report-schedules',{method:'POST',session,body:{reportId:r.json.report.id,name:'Evidence privacy '+session.user.role,cadence:'Daily',startAt}});assert.equal(schedule.status,201);reports.push({session,schedule:schedule.json.schedule,startAt});}
 assert.equal(f.app.locals.runDueReports(Date.parse(reports[1].startAt)+1000).produced,2);
 for(const proof of reports){const row=f.db.prepare('SELECT id,result FROM report_deliveries WHERE schedule_id=?').get(proof.schedule.id),result=JSON.parse(row.result);if(proof.session===f.admin){assert.equal(result.requiredRole,'admin');assert.deepEqual(result.rows,[['PRIVATE_SCHEDULE_REPORT documentary evidence']]);assert.equal((await f.request('/report-deliveries/'+row.id,{session:f.viewer})).status,403);assert.equal((await f.request('/report-deliveries/'+row.id,{session:f.staff})).status,403);}else{assert.equal(result.requiredRole,'authenticated');assert.deepEqual(result.rows,[]);assert.equal((await f.request('/report-deliveries/'+row.id,{session:f.viewer})).status,200);}}
});

test('tribute current/history/notification reports are conservatively administrator-only, omit full bodies and donor snapshots and bind scheduled privacy',async t=>{
 const f=await integratedFixture(t),donor=await f.create('constituents',{name:'PRIVATE_TRIBUTE_DONOR',type:'Individual',email:'PRIVATE_DONOR_EMAIL@example.test',notes:'PRIVATE_DONOR_NOTES'}),recipient=await f.create('constituents',{name:'Synthetic tribute recipient',type:'Individual',preference:'Post',email:'PRIVATE_RECIPIENT_EMAIL@example.test'}),g=await reportingGift(f,donor,10001);
 const tribute=(await reportingPost(f,'/tributes',{giftId:g.id,type:'Memory',honoreeName:'Synthetic honoree',notificationRecipientId:recipient.id,visibility:'Team',donorDisclosureApproved:true,message:'PRIVATE_FULL_NOTIFICATION_MESSAGE',notes:'Tribute business note'})).tribute;
 const prepared=(await reportingPost(f,`/tributes/${tribute.id}/notifications/prepare`,{version:tribute.version,channel:'Print'})).notification;
 await reportingPost(f,`/tribute-notifications/${prepared.id}/finalize`,{version:1,preparationDigest:prepared.preparationDigest,confirmed:true},200);
 const edit=await f.request('/tributes/'+tribute.id,{method:'PATCH',session:f.admin,body:{version:1,visibility:'Staff only',donorDisclosureApproved:false,notes:'PRIVATE_STAFF_TRIBUTE_NOTE'}});assert.equal(edit.status,200,JSON.stringify(edit.json));
 const sources=['tributes','tributeVersions','tributeNotifications','tributeNotificationFinalizations'];for(const entity of sources){assert.equal((await f.catalog()).entities.find(e=>e.id===entity).requiredRole,'admin');for(const session of [f.staff,f.viewer]){assert.equal((await f.catalog(session)).entities.some(e=>e.id===entity),false);const body={name:'Private tribute report',entity,columns:[entity==='tributeNotificationFinalizations'?'delivery':'honoreeName']};assert.equal((await f.request('/custom-reports/run',{method:'POST',session,body})).status,403);assert.equal((await f.request('/custom-reports',{method:'POST',session,body})).status,403);}}
 const current=await f.run('tributes',['honoreeName','sourceGiftAmountCents','visibility','donorDisclosureApproved','messagePresent']);assert.deepEqual(current.rows,[['Synthetic honoree',10001,'Staff only',false,true]]);assert.equal(current.columns[1].unit,'cents');assert.equal(current.requiredRole,'admin');
 const versions=await f.run('tributeVersions',['revision','sourceGiftAmountCents','visibility']);assert.deepEqual(versions.rows,[[1,10001,'Team'],[2,10001,'Staff only']]);
 const notifications=await f.run('tributeNotifications',['honoreeName','recipientName','status','delivery']);assert.deepEqual(notifications.rows,[['Synthetic honoree','Synthetic tribute recipient','Finalized','Not sent']]);assert.deepEqual((await f.run('tributeNotificationFinalizations',['humanReviewed','delivery'])).rows,[[true,'Not sent']]);
 for(const r of [current,versions,notifications])assert.doesNotMatch(JSON.stringify({rows:r.rows,preview:r.sourcePreview.rows}),/PRIVATE_TRIBUTE_DONOR|PRIVATE_DONOR_EMAIL|PRIVATE_DONOR_NOTES|PRIVATE_RECIPIENT_EMAIL|PRIVATE_FULL_NOTIFICATION_MESSAGE|snapshot|digest/);
 for(const field of ['body','recipient.email','source','references','preparationDigest'])assert.equal((await f.request('/custom-reports/run',{method:'POST',session:f.admin,body:{name:'Forbidden notification',entity:'tributeNotifications',columns:[field]}})).status,400);
 const created=await f.request('/custom-reports',{method:'POST',session:f.admin,body:{name:'Tribute private history',entity:'tributeVersions',columns:['notes']}});assert.equal(created.status,201);const reportId=created.json.report.id;
 for(const session of [f.staff,f.viewer]){assert.equal((await f.request(`/custom-reports/${reportId}/run`,{session})).status,403);assert.equal((await f.request('/custom-reports',{session})).json.reports.some(r=>r.id===reportId),false);assert.equal((await f.run('customReportDefinitions',['name'],session)).rows.some(r=>r[0]==='Tribute private history'),false);}
 const startAt=new Date(Date.now()+30000).toISOString(),schedule=await reportingPost(f,'/report-schedules',{name:'Tribute protected schedule',reportId,cadence:'Daily',startAt});assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1000).produced,1);const stored=f.db.prepare('SELECT id,result FROM report_deliveries WHERE schedule_id=?').get(schedule.schedule.id);assert.equal(JSON.parse(stored.result).requiredRole,'admin');assert.ok(JSON.parse(stored.result).rows.some(r=>r[0]==='PRIVATE_STAFF_TRIBUTE_NOTE'));for(const session of [f.staff,f.viewer])assert.equal((await f.request('/report-deliveries/'+stored.id,{session})).status,403);
 await f.restart();assert.equal((await f.run('tributeNotifications',['delivery'])).rows[0][0],'Not sent');assert.equal((await f.request('/report-deliveries/'+stored.id,{session:f.viewer})).status,403);
 f.db.prepare('UPDATE users SET role=? WHERE id=?').run('staff',f.admin.user.id);assert.equal((await f.request(`/custom-reports/${reportId}/run`,{session:f.admin})).status,401);const changed=await f.login('alex@foundation.example');assert.equal(changed.user.role,'staff');assert.equal((await f.request(`/custom-reports/${reportId}/run`,{session:changed})).status,403);
});

test('private document revisions never enter nonadmin current reports or new schedules and untrusted old snapshots stay admin-only',async t=>{
 const f=await integratedFixture(t),task=await f.create('tasks',{title:'Revision boundary fixture',dueDate:'2026-01-01',status:'Open'});
 const doc=(await reportingPost(f,'/documents',{collection:'tasks',recordId:task.id,title:'PRIVATE_ORIGINAL_TITLE',category:'Attachment',visibility:'Administrators',status:'Final',evidenceDate:'2026-01-01',filename:'PRIVATE_ORIGINAL_FILENAME.txt',contentBase64:Buffer.from('PRIVATE_ORIGINAL_BYTES').toString('base64')})).document;
 await reportingPost(f,`/documents/${doc.id}/revisions`,{version:1,title:'Public revised metadata',category:'Attachment',visibility:'Workspace',status:'Final',evidenceDate:'2026-01-01',filename:'public.txt',contentBase64:Buffer.from('Public revised bytes').toString('base64')},200);
 const definition={name:'Role-filtered revision report',entity:'documentRevisions',columns:['revision','filename','metadata']};
 for(const session of [f.staff,f.viewer]){const run=await f.run(definition.entity,definition.columns,session);assert.equal(run.documentRevisionPrivacy,1);assert.deepEqual(run.documentRevisionSources,[{documentId:doc.id,revision:2}]);assert.equal(run.rows.length,1);assert.equal(run.rows[0][0],2);assert.doesNotMatch(JSON.stringify(run),/PRIVATE_ORIGINAL_TITLE|PRIVATE_ORIGINAL_FILENAME|PRIVATE_ORIGINAL_BYTES/);}
 const admin=await f.run('documentRevisions',definition.columns);assert.equal(admin.rows.length,2);assert.ok(admin.rows.some(row=>row[1]==='PRIVATE_ORIGINAL_FILENAME.txt'));
 const saved=await f.request('/custom-reports',{method:'POST',session:f.staff,body:definition});assert.equal(saved.status,201);const startAt=new Date(Date.now()+30000).toISOString(),schedule=await f.request('/report-schedules',{method:'POST',session:f.staff,body:{reportId:saved.json.report.id,name:'Public revision schedule',cadence:'Daily',startAt}});assert.equal(schedule.status,201);assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1000).produced,1);
 const stored=f.db.prepare('SELECT id,result FROM report_deliveries WHERE schedule_id=?').get(schedule.json.schedule.id),result=JSON.parse(stored.result);assert.equal(result.documentRevisionPrivacy,1);assert.equal(result.requiredRole,'authenticated');assert.equal(result.rows.length,1);assert.doesNotMatch(stored.result,/PRIVATE_ORIGINAL_TITLE|PRIVATE_ORIGINAL_FILENAME|PRIVATE_ORIGINAL_BYTES/);assert.equal((await f.request('/report-deliveries/'+stored.id,{session:f.viewer})).status,200);
 // Simulate an original pre-remediation immutable delivery, not a newly trusted result.
 const legacy={...result,rows:[[1,'PRIVATE_ORIGINAL_FILENAME.txt','PRIVATE_ORIGINAL_TITLE']]};delete legacy.documentRevisionPrivacy;delete legacy.documentRevisionSources;const legacyId=randomUUID();f.db.prepare('INSERT INTO report_deliveries VALUES(?,?,?,?,?,?,?,?)').run(legacyId,schedule.json.schedule.id,'2000-01-01T00:00:00.000Z','2000-01-01T00:00:00.000Z','Produced',1,JSON.stringify(legacy),null);
 for(const session of [f.staff,f.viewer])assert.equal((await f.request('/report-deliveries/'+legacyId,{session})).status,403);assert.equal((await f.request('/report-deliveries/'+legacyId,{session:f.admin})).status,200);
 const metadata=await f.run('reportDeliveries',['resultSummary'],f.viewer);assert.equal(metadata.rows.filter(row=>row[0]===null).length,1);
 // Source IDs are retained independently of selected columns, so a later private current document gates the old public result.
 await reportingPost(f,`/documents/${doc.id}/revisions`,{version:2,title:'Private current revision',category:'Attachment',visibility:'Administrators',status:'Final',evidenceDate:'2026-01-01',filename:'private-current.txt',contentBase64:Buffer.from('Private current bytes').toString('base64')},200);
 for(const session of [f.staff,f.viewer])assert.equal((await f.request('/report-deliveries/'+stored.id,{session})).status,403);assert.equal((await f.run('documentRevisions',['filename'],f.viewer)).rows.length,0);
 await f.restart();assert.equal((await f.request('/report-deliveries/'+legacyId,{session:f.viewer})).status,403);assert.equal((await f.request('/report-deliveries/'+stored.id,{session:f.viewer})).status,403);
});

test('financial correction reports preserve exact historical cents, allocations and source revisions without raw source notes',async t=>{
 const f=await integratedFixture(t),person=await f.create('constituents',{name:'Correction report donor',type:'Individual'}),a=await f.create('designations',{name:'First correction fund'}),b=await f.create('designations',{name:'Second correction fund'});
 const gift=await f.create('gifts',{constituentId:person.id,amount:10001,type:'Cash',method:'Check',date:'2026-08-01',allocations:[{designationId:a.id,amount:6001},{designationId:b.id,amount:4000}],notes:'RAW_CORRECTION_SOURCE_NOTE'});
 const edit=await f.request('/records/gifts/'+gift.id,{method:'PATCH',session:f.staff,body:{version:1,amount:12002,date:'2026-08-02',allocations:[{designationId:a.id,amount:8002},{designationId:b.id,amount:4000}],correctionReason:'Checked source statement; amount/date corrected'}});assert.equal(edit.status,200,JSON.stringify(edit.json));
 const catalog=await f.catalog(f.viewer),entity=catalog.entities.find(e=>e.id==='giftFinancialCorrections');assert.ok(entity);assert.equal(entity.requiredRole,'authenticated');assert.equal(entity.fields.find(v=>v.key==='beforeAmountCents').type,'money');assert.equal(entity.fields.find(v=>v.key==='afterAmountCents').unit,'cents');assert.match(entity.description,/not additional income/);
 const columns=['giftId','fromRevision','toRevision','beforeAmountCents','afterAmountCents','beforeDate','afterDate','beforeAllocations','afterAllocations','reason','sourceVersions'];
 const run=await f.run(entity.id,columns,f.viewer);assert.equal(run.matchedRows,1);assert.deepEqual(run.rows[0].slice(0,7),[gift.id,1,2,10001,12002,'2026-08-01','2026-08-02']);assert.deepEqual(JSON.parse(run.rows[0][7]),[{designationId:a.id,amount:6001},{designationId:b.id,amount:4000}]);assert.equal(JSON.parse(run.rows[0][8]).reduce((n,x)=>n+x.amount,0),12002);assert.ok(JSON.parse(run.rows[0][10]).before.some(ref=>ref.id===person.id&&ref.revision===1));assert.equal(run.giftCorrectionPrivacy,1);assert.equal(run.giftCorrectionSources[0].giftId,gift.id);assert.doesNotMatch(JSON.stringify(run),/RAW_CORRECTION_SOURCE_NOTE|before_json|after_json/);
 for(const column of ['before.notes','before_json','after_json','actor.password'])assert.equal((await f.request('/custom-reports/run',{method:'POST',session:f.admin,body:{name:'Blocked source snapshot',entity:entity.id,columns:[column]}})).status,400);
 const saved=await f.request('/custom-reports',{method:'POST',session:f.staff,body:{name:'Historical correction total',entity:entity.id,columns:['beforeAmountCents','afterAmountCents'],aggregates:[{op:'sum',field:'beforeAmountCents'},{op:'sum',field:'afterAmountCents'},{op:'count'}]}});assert.equal(saved.status,201);const id=saved.json.report.id;await f.restart();const persisted=await f.request('/custom-reports/'+id+'/run',{session:f.viewer});assert.equal(persisted.status,200);assert.deepEqual(persisted.json.rows,[[10001,12002,1]]);assert.equal(persisted.json.giftCorrectionSources.length,1);
});

test('scheduled correction reports retain prior facts and provenance and deny legacy or unavailable source histories',async t=>{
 const f=await integratedFixture(t),person=await f.create('constituents',{name:'Scheduled correction donor',type:'Individual'}),fund=await f.create('designations',{name:'Scheduled correction fund'}),gift=await f.create('gifts',{constituentId:person.id,amount:10001,type:'Cash',method:'Check',date:'2026-08-01',allocations:[{designationId:fund.id,amount:10001}]});
 const correct=async(version,amount)=>{const r=await f.request('/records/gifts/'+gift.id,{method:'PATCH',session:f.staff,body:{version,amount,allocations:[{designationId:fund.id,amount}],correctionReason:'Reviewed source amount '+amount}});assert.equal(r.status,200,JSON.stringify(r.json));};await correct(1,12002);
 const report=await f.request('/custom-reports',{method:'POST',session:f.staff,body:{name:'Correction source schedule',entity:'giftFinancialCorrections',columns:['giftId','beforeAmountCents','afterAmountCents'],aggregates:[{op:'count'}]}});assert.equal(report.status,201);
 const startAt=new Date(Date.now()+30000).toISOString(),scheduled=await f.request('/report-schedules',{method:'POST',session:f.staff,body:{reportId:report.json.report.id,name:'Correction source schedule',cadence:'Daily',startAt}});assert.equal(scheduled.status,201);assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1000).produced,1);
 const delivery=f.db.prepare('SELECT * FROM report_deliveries WHERE schedule_id=?').get(scheduled.json.schedule.id),stored=JSON.parse(delivery.result);assert.deepEqual(stored.rows,[[1]]);assert.deepEqual(stored.sourcePreview.rows,[[gift.id,10001,12002]]);assert.equal(stored.giftCorrectionPrivacy,1);assert.equal(stored.giftCorrectionSources.length,1);
 await correct(2,15003);const current=await f.run('giftFinancialCorrections',['afterAmountCents'],f.viewer);assert.equal(current.rows.length,2);const retained=await f.request('/report-deliveries/'+delivery.id,{session:f.viewer});assert.equal(retained.status,200);assert.deepEqual(retained.json.delivery.result.rows,[[1]]);assert.equal(retained.json.delivery.result.matchedRows,1);
 const legacy={...stored};delete legacy.giftCorrectionPrivacy;delete legacy.giftCorrectionSources;const legacyId=randomUUID();f.db.prepare('INSERT INTO report_deliveries VALUES(?,?,?,?,?,?,?,?)').run(legacyId,scheduled.json.schedule.id,'2000-01-01T00:00:00.000Z','2000-01-01T00:00:00.000Z','Produced',1,JSON.stringify(legacy),null);assert.equal((await f.request('/report-deliveries/'+legacyId,{session:f.viewer})).status,403);assert.equal((await f.request('/report-deliveries/'+legacyId,{session:f.admin})).status,200);
 f.db.prepare("DELETE FROM records WHERE collection='gifts' AND id=?").run(gift.id);assert.equal((await f.request('/report-deliveries/'+delivery.id,{session:f.viewer})).status,403);assert.equal((await f.run('reportDeliveries',['resultSummary'],f.viewer)).rows.every(row=>row[0]===null),true);
});

test('correction reporting follows gift source visibility and anonymous, unknown-role and viewer-write denials',async t=>{
 const f=await fixture(t);f.db.exec(`CREATE TABLE gift_financial_corrections(id TEXT,gift_id TEXT,from_version INTEGER,to_version INTEGER,before_json TEXT,after_json TEXT,changed_fields TEXT,reason TEXT,actor_json TEXT,at TEXT,before_references TEXT,after_references TEXT)`);
 const before={...f.data.gifts[0],notes:'RAW_PRIVATE_NOTE'},after={...before,amount:10002,allocations:[{designationId:fundA,amount:6001},{designationId:fundB,amount:4001}]},insert=f.db.prepare('INSERT INTO gift_financial_corrections VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');
 insert.run(randomUUID(),gift,1,2,JSON.stringify(before),JSON.stringify(after),'["amount","allocations"]','Own visible correction',JSON.stringify({id:'user',name:'User',role:'staff',unexpected:'ACTOR_SECRET'}),'2026-09-13T00:00:00Z','[]','[]');insert.run(randomUUID(),randomUUID(),1,2,JSON.stringify(before),JSON.stringify(after),'["amount"]','FOREIGN_CORRECTION_SECRET','{}','2026-09-13T00:00:00Z','[]','[]');
 const definition={name:'Visible correction report',entity:'giftFinancialCorrections',columns:['reason','beforeAmountCents','afterAmountCents']};const run=await f.request('/run',{method:'POST',role:'viewer',body:definition});assert.equal(run.status,200);assert.deepEqual(run.json.rows,[['Own visible correction',10001,10002]]);assert.doesNotMatch(JSON.stringify(run.json),/FOREIGN_CORRECTION_SECRET|RAW_PRIVATE_NOTE|ACTOR_SECRET/);
 assert.equal((await f.request('/run',{method:'POST',role:'anonymous',body:definition})).status,401);assert.equal((await f.request('/run',{method:'POST',role:'helper',body:definition})).status,403);assert.equal((await f.request('',{method:'POST',role:'viewer',body:definition})).status,403);assert.equal((await f.request('/run',{method:'POST',token:false,body:definition})).status,403);assert.equal(f.audits.length,0);
});

test('task responsibility reports preserve actual staff assignment changes and bind scheduled source access',async t=>{
 const f=await integratedFixture(t),task=await f.create('tasks',{title:'Assignment reporting proof',dueDate:'2026-09-13',status:'Open',ownerId:f.staff.user.id});
 const change=await f.request('/records/tasks/'+task.id,{method:'PATCH',session:f.staff,body:{version:task.version,ownerId:f.admin.user.id,assignmentReason:'Controller owns final review'}});assert.equal(change.status,200,JSON.stringify(change.json));
 const entity=(await f.catalog(f.viewer)).entities.find(e=>e.id==='taskAssignmentHistory');assert.ok(entity);assert.equal(entity.requiredRole,'authenticated');const run=await f.run(entity.id,['taskId','fromRevision','toRevision','beforeOwnerId','afterOwnerId','reason'],f.viewer);assert.equal(run.matchedRows,2);assert.deepEqual(run.rows[1],[task.id,1,2,f.staff.user.id,f.admin.user.id,'Controller owns final review']);assert.equal(run.taskAssignmentPrivacy,1);assert.equal(run.taskAssignmentSources.length,2);assert.doesNotMatch(JSON.stringify(entity.fields),/before_owner|after_owner|password|email/);
 const report=await f.request('/custom-reports',{method:'POST',session:f.staff,body:{name:'Assignment provenance',entity:entity.id,columns:['taskId'],aggregates:[{op:'count'}]}});assert.equal(report.status,201);const startAt=new Date(Date.now()+30000).toISOString(),scheduled=await f.request('/report-schedules',{method:'POST',session:f.staff,body:{reportId:report.json.report.id,name:'Assignment provenance',cadence:'Daily',startAt}});assert.equal(scheduled.status,201);assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1000).produced,1);const delivery=f.db.prepare('SELECT * FROM report_deliveries WHERE schedule_id=?').get(scheduled.json.schedule.id);assert.equal((await f.request('/report-deliveries/'+delivery.id,{session:f.viewer})).status,200);const stored=JSON.parse(delivery.result);assert.deepEqual(stored.rows,[[2]]);assert.equal(stored.taskAssignmentSources.length,2);
 f.db.prepare("DELETE FROM records WHERE collection='tasks' AND id=?").run(task.id);assert.equal((await f.request('/report-deliveries/'+delivery.id,{session:f.viewer})).status,403);assert.equal((await f.run('taskAssignmentHistory',['taskId'],f.viewer)).rows.length,0);
});

test('major follow-up reporting distinguishes completed action from legacy due date and preserves immutable activity',async t=>{
 const f=await integratedFixture(t),person=await f.create('constituents',{name:'Major follow-up report donor',type:'Individual'}),created=(await reportingPost(f,'/fundraising',{kind:'major',name:'Major follow-up reporting proof',donorId:person.id,ownerId:f.staff.user.id,stage:'Cultivation',expectedAmount:12345,nextActionDate:'2026-08-01'})).record;
 const done=await f.request('/fundraising/'+created.id+'/follow-up',{method:'POST',session:f.staff,body:{version:1,date:'2026-08-02',outcome:'Completed',note:'Spoke to donor; no funds recorded',reason:'Reviewed conversation outcome'}});assert.equal(done.status,200,JSON.stringify(done.json));
 const current=await f.run('fundraisingRecords',['nextActionDate','nextActionStatus','latestFollowup'],f.viewer);assert.equal(current.rows[0][0],'2026-08-01');assert.equal(current.rows[0][1],'Completed');assert.deepEqual(JSON.parse(current.rows[0][2]),{date:'2026-08-02',outcome:'Completed',previousDueDate:'2026-08-01',nextActionDate:null,actor:f.staff.user.id});
 const versions=await f.run('fundraisingVersions',['revision','nextActionStatus'],f.viewer);assert.deepEqual(versions.rows,[[1,'Open'],[2,'Completed']]);const history=await f.run('fundraisingActivity',['action','note'],f.viewer);const followup=history.rows.find(row=>row[0]==='record_major_followup');assert.ok(followup);assert.match(followup[1],/Spoke to donor; no funds recorded/);assert.match(followup[1],/Reviewed conversation outcome/);
 const stored=JSON.parse(f.db.prepare('SELECT data FROM fundraising_records WHERE id=?').get(created.id).data);stored.latestFollowup={...stored.latestFollowup,unexpected:'UNSAFE_FOLLOWUP_EXTRA',email:'UNSAFE_FOLLOWUP_EMAIL',note:'RAW_DUPLICATED_NOTE'};f.db.prepare('UPDATE fundraising_records SET data=? WHERE id=?').run(JSON.stringify(stored),created.id);assert.doesNotMatch(JSON.stringify(await f.run('fundraisingRecords',['latestFollowup'],f.viewer)),/UNSAFE_FOLLOWUP_EXTRA|UNSAFE_FOLLOWUP_EMAIL|RAW_DUPLICATED_NOTE/);
});

test('event ticket transition reports retain original check-in and reasoned reversal without raw attendee or payment snapshots',async t=>{
 const f=await integratedFixture(t),person=await f.create('constituents',{name:'Ticket transition report attendee',type:'Individual',email:'PRIVATE_TICKET_REPORT_EMAIL@example.test'}),event=await f.create('events',{name:'Ticket transition report event',date:'2026-10-01',capacity:2,ticketPrice:0});await reportingPost(f,'/events/'+event.id+'/register',{constituentId:person.id},200);
 const currentEvent=async()=>((await f.request('/workspace',{session:f.admin})).json.data.events.find(e=>e.id===event.id));let e=await currentEvent();let ticket=(await reportingPost(f,'/event-operations/events/'+event.id+'/tickets',{eventVersion:e.version,constituentId:person.id})).ticket;ticket=(await reportingPost(f,'/event-operations/tickets/'+ticket.id+'/checkin',{version:ticket.version,eventVersion:e.version},200)).ticket;
 const report=await f.request('/custom-reports',{method:'POST',session:f.staff,body:{name:'Ticket transition retained report',entity:'eventTicketTransitions',columns:['action','beforeCheckedIn','afterCheckedIn','afterCheckedInAt','reason']}});assert.equal(report.status,201,JSON.stringify(report.json));const startAt=new Date(Date.now()+30000).toISOString(),schedule=await f.request('/report-schedules',{method:'POST',session:f.staff,body:{reportId:report.json.report.id,name:'Ticket transition retained report',cadence:'Daily',startAt}});assert.equal(schedule.status,201);assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1000).produced,1);const delivery=f.db.prepare('SELECT * FROM report_deliveries WHERE schedule_id=?').get(schedule.json.schedule.id);const original=JSON.parse(delivery.result);assert.equal(original.rows.length,2);assert.deepEqual(original.rows[1].slice(0,3),['Checked in',false,true]);assert.equal(original.eventTicketTransitionPrivacy,1);assert.equal(original.eventTicketTransitionSources.length,2);
 e=await currentEvent();await reportingPost(f,'/event-operations/tickets/'+ticket.id+'/reverse-checkin',{version:ticket.version,eventVersion:e.version,reason:'Confirmed mistaken attendance entry',confirmed:true},200);
 const run=await f.run('eventTicketTransitions',['ticketId','eventId','action','beforeCheckedIn','afterCheckedIn','beforeCheckedInAt','afterCheckedInAt','reason'],f.viewer);assert.equal(run.rows.length,3);assert.deepEqual(run.rows[2].slice(0,5),[ticket.id,event.id,'Check-in reversed',true,false]);assert.ok(run.rows[2][5]);assert.equal(run.rows[2][6],null);assert.equal(run.rows[2][7],'Confirmed mistaken attendance entry');assert.doesNotMatch(JSON.stringify(run),/PRIVATE_TICKET_REPORT_EMAIL|before_json|after_json|actor_json/);assert.equal(run.recordReferences[2].collection,'events');assert.equal(run.recordReferences[2].id,event.id);
 const retained=await f.request('/report-deliveries/'+delivery.id,{session:f.viewer});assert.equal(retained.status,200);assert.equal(retained.json.delivery.result.rows.length,2);assert.equal(retained.json.delivery.result.rows[1][2],true);
 f.db.prepare("DELETE FROM records WHERE collection='events' AND id=?").run(event.id);assert.equal((await f.request('/report-deliveries/'+delivery.id,{session:f.viewer})).status,403);assert.equal((await f.run('eventTicketTransitions',['ticketId'],f.viewer)).rows.length,0);
});

test('manual correspondence fulfillment is natively reportable without claiming an application send and scheduled sources recheck access',async t=>{
 const f=await integratedFixture(t),person=await f.create('constituents',{name:'Correspondence fulfillment report donor',type:'Individual',preference:'Post',email:'PRIVATE_FULFILLMENT_EMAIL@example.test'}),gift=await reportingGift(f,person,12345);
 const template=(await reportingPost(f,'/correspondence/templates',{name:'Fulfillment reporting source',kind:'Acknowledgment',subject:'Recorded support',body:'PRIVATE_REVIEWED_WORDING_BODY {{recipientName}} {{monetaryAmount}}'})).template;
 const prepared=(await reportingPost(f,'/correspondence/prepare',{templateId:template.id,templateVersion:1,channel:'Print',giftIds:[gift.id]})).correspondence;
 await reportingPost(f,'/correspondence/'+prepared.id+'/finalize',{version:1,preparationDigest:prepared.preparationDigest,confirmed:true},200);
 const date=new Date().toISOString().slice(0,10),result=await f.request('/gifts/'+gift.id+'/acknowledge',{method:'POST',session:f.staff,body:{version:gift.version,date,channel:'Post',notes:'Synthetic reviewed wording manually delivered',correspondence:{preparationId:prepared.id,preparationDigest:prepared.preparationDigest,confirmed:true,reason:'Authorized staff confirms synthetic manual completion'}}});assert.equal(result.status,200,JSON.stringify(result.json));const communication=result.json.communication;
 const run=await f.run('correspondenceFulfillments',['preparationId','giftId','sourceGiftRevision','acknowledgmentGiftRevision','communicationId','channel','templateId','templateRevision','manualConfirmation','applicationSent'],f.viewer);assert.deepEqual(run.rows,[[prepared.id,gift.id,1,2,communication.id,'Post',template.id,1,true,false]]);assert.equal(run.correspondenceFulfillmentPrivacy,1);assert.equal(run.correspondenceFulfillmentSources.length,1);assert.deepEqual(run.recordReferences,[{collection:'gifts',id:gift.id}]);assert.doesNotMatch(JSON.stringify(run),/PRIVATE_FULFILLMENT_EMAIL|PRIVATE_REVIEWED_WORDING_BODY|source_json|wordingDigest|preparationDigest/);
 for(const field of ['source_json','source.wordingDigest','recipient.email','body'])assert.equal((await f.request('/custom-reports/run',{method:'POST',session:f.admin,body:{name:'Blocked raw fulfillment',entity:'correspondenceFulfillments',columns:[field]}})).status,400);
 const report=await f.request('/custom-reports',{method:'POST',session:f.staff,body:{name:'Fulfillment provenance schedule',entity:'correspondenceFulfillments',columns:['giftId'],aggregates:[{op:'count'}]}});assert.equal(report.status,201);const startAt=new Date(Date.now()+30000).toISOString(),schedule=await f.request('/report-schedules',{method:'POST',session:f.staff,body:{name:'Fulfillment provenance schedule',reportId:report.json.report.id,cadence:'Daily',startAt}});assert.equal(schedule.status,201);assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1000).produced,1);const delivery=f.db.prepare('SELECT * FROM report_deliveries WHERE schedule_id=?').get(schedule.json.schedule.id);assert.equal((await f.request('/report-deliveries/'+delivery.id,{session:f.viewer})).status,200);assert.equal(JSON.parse(delivery.result).correspondenceFulfillmentSources.length,1);
 f.db.prepare("DELETE FROM records WHERE collection='communications' AND id=?").run(communication.id);assert.equal((await f.request('/report-deliveries/'+delivery.id,{session:f.viewer})).status,403);assert.equal((await f.run('correspondenceFulfillments',['giftId'],f.viewer)).rows.length,0);
});

test('tribute withdrawal reports preserve finalized history, expose current withdrawn status and bind administrator access',async t=>{
 const f=await integratedFixture(t),person=await f.create('constituents',{name:'Withdrawal report donor',type:'Individual'}),recipient=await f.create('constituents',{name:'Withdrawal report recipient',type:'Individual',preference:'Post'}),gift=await reportingGift(f,person,10001),tribute=(await reportingPost(f,'/tributes',{giftId:gift.id,type:'Honor',honoreeName:'Withdrawal report honoree',notificationRecipientId:recipient.id,visibility:'Team',donorDisclosureApproved:true,message:'PRIVATE_WITHDRAWAL_WORDING'})).tribute;
 const notification=(await reportingPost(f,'/tributes/'+tribute.id+'/notifications/prepare',{version:1,channel:'Print'})).notification;await reportingPost(f,'/tribute-notifications/'+notification.id+'/finalize',{version:1,preparationDigest:notification.preparationDigest,confirmed:true},200);await reportingPost(f,'/tribute-notifications/'+notification.id+'/withdraw',{version:1,preparationDigest:notification.preparationDigest,reason:'PRIVATE_INTERNAL_WITHDRAWAL_REASON',confirmedNotSent:true},200);
 assert.deepEqual((await f.run('tributeNotifications',['status','delivery'])).rows,[['Withdrawn','Not sent']]);assert.deepEqual((await f.run('tributeNotificationFinalizations',['humanReviewed','delivery'])).rows,[[true,'Not sent']]);const run=await f.run('tributeNotificationWithdrawals',['notificationId','tributeId','revision','reason','confirmedNotSent','delivery']);assert.deepEqual(run.rows,[[notification.id,tribute.id,2,'PRIVATE_INTERNAL_WITHDRAWAL_REASON',true,'Not sent']]);assert.equal(run.requiredRole,'admin');assert.doesNotMatch(JSON.stringify(run),/PRIVATE_WITHDRAWAL_WORDING|digest|snapshot/);
 const definition={name:'Withdrawal internal history',entity:'tributeNotificationWithdrawals',columns:['reason']};const report=await f.request('/custom-reports',{method:'POST',session:f.admin,body:definition});assert.equal(report.status,201);
 for(const session of [f.staff,f.viewer]){assert.equal((await f.catalog(session)).entities.some(e=>e.id===definition.entity),false);assert.equal((await f.request('/custom-reports/run',{method:'POST',session,body:definition})).status,403);assert.equal((await f.request('/custom-reports/'+report.json.report.id+'/run',{session})).status,403);assert.equal((await f.request('/custom-reports',{session})).json.reports.some(r=>r.id===report.json.report.id),false);}
 const startAt=new Date(Date.now()+30000).toISOString(),schedule=await f.request('/report-schedules',{method:'POST',session:f.admin,body:{name:'Withdrawal internal history',reportId:report.json.report.id,cadence:'Daily',startAt}});assert.equal(schedule.status,201);assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1000).produced,1);const delivery=f.db.prepare('SELECT * FROM report_deliveries WHERE schedule_id=?').get(schedule.json.schedule.id);assert.equal(JSON.parse(delivery.result).requiredRole,'admin');for(const session of [f.staff,f.viewer])assert.equal((await f.request('/report-deliveries/'+delivery.id,{session})).status,403);
});

test('cancelled sponsorship reports distinguish retained original promises from zero active commitments and preserve scheduled transitions',async t=>{
 const f=await integratedFixture(t),sponsor=await f.create('constituents',{name:'Transition report sponsor',type:'Business'}),event=await f.create('events',{name:'Sponsor transition reporting event',date:'2026-10-01',capacity:4});let agreement=(await reportingPost(f,'/event-operations/sponsorships',{eventId:event.id,eventVersion:event.version,sponsorId:sponsor.id,name:'Unpaid reporting agreement',amount:12345,benefits:[{name:'Recognition',completed:false}]})).sponsorship;
 agreement=(await reportingPost(f,'/event-operations/sponsorships/'+agreement.id+'/cancel',{version:agreement.version,eventVersion:event.version,reason:'Sponsor declined the unpaid promise',confirmed:true},200)).sponsorship;
 const current=await f.run('eventSponsors',['status','commitmentAmountCents','activeCommitmentAmountCents'],f.viewer);assert.deepEqual(current.rows,[['Cancelled',12345,0]]);assert.match(current.scope,/original|Original/);assert.match(current.scope,/not income/);assert.equal(current.columns[2].unit,'cents');
 const columns=['ownerType','ownerId','action','fromRevision','toRevision','beforeStatus','afterStatus','beforeCommitmentAmountCents','afterCommitmentAmountCents','beforeActiveCommitmentAmountCents','afterActiveCommitmentAmountCents','reason','sourceReferences'];const transitions=await f.run('eventCommitmentTransitions',columns,f.viewer);assert.equal(transitions.rows.length,2);assert.deepEqual(transitions.rows[1].slice(0,12),['sponsorship',agreement.id,'Cancelled',1,2,'Active','Cancelled',12345,12345,12345,0,'Sponsor declined the unpaid promise']);assert.deepEqual(JSON.parse(transitions.rows[1][12]),{event:{id:event.id,revision:1},bids:[],receiptLinks:[]});assert.equal(transitions.eventCommitmentPrivacy,1);assert.equal(transitions.eventCommitmentSources.length,2);assert.deepEqual(transitions.recordReferences[1],{collection:'events',id:event.id});
 const definition={name:'Cancelled sponsor retained report',entity:'eventCommitmentTransitions',columns:['afterCommitmentAmountCents','afterActiveCommitmentAmountCents'],filters:[{field:'action',op:'eq',value:'Cancelled'}],aggregates:[{op:'sum',field:'afterCommitmentAmountCents'},{op:'sum',field:'afterActiveCommitmentAmountCents'}]};const report=await f.request('/custom-reports',{method:'POST',session:f.staff,body:definition});assert.equal(report.status,201);const startAt=new Date(Date.now()+30000).toISOString(),schedule=await f.request('/report-schedules',{method:'POST',session:f.staff,body:{name:definition.name,reportId:report.json.report.id,cadence:'Daily',startAt}});assert.equal(schedule.status,201);assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1000).produced,1);const delivery=f.db.prepare('SELECT * FROM report_deliveries WHERE schedule_id=?').get(schedule.json.schedule.id);assert.deepEqual(JSON.parse(delivery.result).rows,[[12345,0]]);assert.equal(JSON.parse(delivery.result).eventCommitmentSources.length,1);
 agreement=(await reportingPost(f,'/event-operations/sponsorships/'+agreement.id+'/reopen',{version:agreement.version,eventVersion:event.version,reason:'Sponsor renewed the unpaid agreement',confirmed:true},200)).sponsorship;assert.deepEqual((await f.run('eventSponsors',['status','activeCommitmentAmountCents'],f.viewer)).rows,[['Active',12345]]);const retained=await f.request('/report-deliveries/'+delivery.id,{session:f.viewer});assert.equal(retained.status,200);assert.deepEqual(retained.json.delivery.result.rows,[[12345,0]]);
 for(const field of ['before_json','after_json','source_json','actor_json','before.benefits'])assert.equal((await f.request('/custom-reports/run',{method:'POST',session:f.viewer,body:{name:'Blocked raw commitment',entity:'eventCommitmentTransitions',columns:[field]}})).status,400);
 f.db.prepare("DELETE FROM records WHERE collection='events' AND id=?").run(event.id);assert.equal((await f.request('/report-deliveries/'+delivery.id,{session:f.viewer})).status,403);assert.equal((await f.run('eventCommitmentTransitions',['ownerId'],f.viewer)).rows.length,0);
});

test('auction award reopening reports keep immutable winner and payment provenance without counting history as extra receipts',async t=>{
 const f=await integratedFixture(t),person=await f.create('constituents',{name:'Auction transition report buyer',type:'Individual'}),event=await f.create('events',{name:'Auction transition reporting event',date:'2026-10-01',capacity:4});let item=(await reportingPost(f,'/event-operations/auction-items',{eventId:event.id,eventVersion:event.version,name:'Reporting auction inventory',startingBid:10001,minIncrement:500,description:'PRIVATE_AUCTION_DESCRIPTION_NOT_REPORT_HISTORY'})).item;
 item=(await reportingPost(f,'/event-operations/auction-items/'+item.id+'/bids',{version:item.version,bidderId:person.id,amount:12345})).item;const winner=item.bids[0];item=(await reportingPost(f,'/event-operations/auction-items/'+item.id+'/close',{version:item.version,winningBidId:winner.id,confirmed:true},200)).item;
 item=(await reportingPost(f,'/event-operations/auction-items/'+item.id+'/reopen',{version:item.version,eventVersion:event.version,winningBidId:winner.id,reason:'Correct unpaid award before accepting later bids',confirmed:true},200)).item;
 const columns=['action','beforeStatus','afterStatus','beforeCommitmentAmountCents','afterCommitmentAmountCents','beforeWinningBidId','afterWinningBidId','winningBidId','winningBidAmountCents','highestBidId','highestBidAmountCents','sourceReferences'];const run=await f.run('eventCommitmentTransitions',columns,f.viewer);assert.equal(run.rows.length,2);assert.deepEqual(run.rows[1].slice(0,11),['Award reopened','Closed','Open',12345,0,winner.id,null,winner.id,12345,winner.id,12345]);assert.equal(run.eventCommitmentSources[1].bidIds[0],winner.id);assert.doesNotMatch(JSON.stringify(run),/PRIVATE_AUCTION_DESCRIPTION_NOT_REPORT_HISTORY|before_json|source_json/);
 item=(await reportingPost(f,'/event-operations/auction-items/'+item.id+'/close',{version:item.version,winningBidId:winner.id,confirmed:true},200)).item;const gift=await reportingGift(f,person,12345,{type:'Cash'});await reportingPost(f,'/event-operations/payments',{ownerType:'auction',ownerId:item.id,version:item.version,giftId:gift.id,giftVersion:gift.version,revenueCase:'Cash'});
 const paid=await f.run('eventCommitmentTransitions',['action','receiptLinkCount','referencedReceiptAmountCents','sourceReferences'],f.viewer);const payment=paid.rows.find(row=>row[0]==='Payment linked');assert.ok(payment);assert.deepEqual(payment.slice(1,3),[1,12345]);assert.equal(JSON.parse(payment[3]).receiptLinks[0].giftId,gift.id);assert.match(paid.scope,/not new income/);
 const definition={name:'Award receipt source snapshot',entity:'eventCommitmentTransitions',columns:['referencedReceiptAmountCents'],filters:[{field:'action',op:'eq',value:'Payment linked'}],aggregates:[{op:'sum',field:'referencedReceiptAmountCents'}]},report=await f.request('/custom-reports',{method:'POST',session:f.staff,body:definition});assert.equal(report.status,201);const startAt=new Date(Date.now()+30000).toISOString(),schedule=await f.request('/report-schedules',{method:'POST',session:f.staff,body:{name:definition.name,reportId:report.json.report.id,cadence:'Daily',startAt}});assert.equal(schedule.status,201);assert.equal(f.app.locals.runDueReports(Date.parse(startAt)+1000).produced,1);const delivery=f.db.prepare('SELECT * FROM report_deliveries WHERE schedule_id=?').get(schedule.json.schedule.id),stored=JSON.parse(delivery.result);assert.deepEqual(stored.rows,[[12345]]);assert.equal(stored.eventCommitmentSources.length,1);assert.equal(stored.eventCommitmentSources[0].receiptLinks[0].giftId,gift.id);assert.equal((await f.request('/report-deliveries/'+delivery.id,{session:f.viewer})).status,200);
 const legacy={...stored};delete legacy.eventCommitmentPrivacy;delete legacy.eventCommitmentSources;assert.throws(()=>f.app.locals.db.prepare('UPDATE report_deliveries SET result=? WHERE id=?').run(JSON.stringify(legacy),delivery.id));
 f.db.prepare("DELETE FROM records WHERE collection='gifts' AND id=?").run(gift.id);assert.equal((await f.request('/report-deliveries/'+delivery.id,{session:f.viewer})).status,403);
});


test('sponsorship reports retain prior fulfillment after current benefits are unchecked and recheck current event access',async t=>{
 const f=await integratedFixture(t),sponsor=await f.create('constituents',{name:'Protected benefit sponsor',type:'Business'}),event=await f.create('events',{name:'Retained benefit reporting event',date:'2026-10-01',capacity:4});
 let agreement=(await reportingPost(f,'/event-operations/sponsorships',{eventId:event.id,eventVersion:event.version,sponsorId:sponsor.id,name:'Previously fulfilled recognition',amount:12345,benefits:[{name:'Recognition',completed:false}]})).sponsorship;
 assert.deepEqual((await f.run('eventSponsors',['everFulfilled'],f.viewer)).rows,[[false]]);
 for(const completed of [true,false]){const edited=await f.request('/event-operations/sponsorships/'+agreement.id,{method:'PATCH',session:f.staff,body:{version:agreement.version,benefits:[{name:'Recognition',completed}]}});assert.equal(edited.status,200,JSON.stringify(edited.json));agreement=edited.json.sponsorship;}
 const entity=(await f.catalog(f.viewer)).entities.find(e=>e.id==='eventSponsors');assert.ok(entity.fields.some(field=>field.key==='everFulfilled'));assert.match(entity.description,/prior recorded benefit completion/);
 const result=await f.run('eventSponsors',['everFulfilled','benefits'],f.viewer);assert.deepEqual(result.rows,[[true,JSON.stringify([{name:'Recognition',completed:false}])]]);
 const denied=await f.request('/event-operations/sponsorships/'+agreement.id+'/cancel',{method:'POST',session:f.staff,body:{version:agreement.version,eventVersion:event.version,reason:'Checklist is currently unchecked',confirmed:true}});assert.equal(denied.status,409);assert.match(denied.json.error,/Previously recorded benefits/);
 f.db.prepare("DELETE FROM records WHERE collection='events' AND id=?").run(event.id);assert.deepEqual((await f.run('eventSponsors',['everFulfilled','benefits'],f.viewer)).rows,[]);
});
