import {installTaskOwnership} from './taskOwnership.js';
import {createHostedGivingService,installHostedGivingRoutes} from './hostedGiving.js';
import {installConstituentTimelineRoutes} from './constituentTimeline.js';
import {installFinancialCorrections} from './financialCorrections.js';
import {installFundraisingRoutes} from './fundraising.js';
import {installPeerFundraisingRoutes} from './peerFundraising.js';
import {installGrantOperationsRoutes} from './grantOperations.js';
import {installTributeRoutes} from './tributes.js';
import {installEventOperationsRoutes} from './eventOperations.js';
import {installEventHelperAccessRoutes} from './eventHelperAccess.js';
import {installReceiptRoutes} from './receipts.js';
import {installTaskReminderRoutes} from './taskReminders.js';
import {installCommunicationWorkflowRoutes} from './communicationWorkflows.js';
import {installAudienceRoutes} from './audiences.js';
import {installCommunicationsRoutes} from './communications.js';
import {createMfaService,assertMfaEncryptionKey,mfaAccountBinding} from './mfa.js';
import {installIdentityRoutes} from './identity.js';
import {installReportingRoutes} from './reporting.js';
import {installMigrationRoutes} from './migration.js';
import {installReportScheduleRoutes} from './reportSchedule.js';
import { installAiRoutes } from './ai.js';
import { installDocumentRoutes } from './documents.js';
import {installDocumentMigrationRoutes} from './documentMigration.js';
import express from 'express';
import helmet from 'helmet';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, randomUUID, scryptSync, timingSafeEqual, createHash } from 'node:crypto';
import { z } from 'zod';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const collections=['constituents','gifts','campaigns','grants','volunteers','events','tasks','communications','designations','pledges','volunteerTime','reportViews','evaluations','volunteerShifts','shiftReservations'];
const str=z.string().max(8000).default('');
const short=z.string().max(300).default('');
const name=z.string().trim().min(1).max(250);
const cents=z.number().int().min(0).max(1e12);
const id=z.string().min(1).max(100);
const fk=id.nullable().optional().default(null);
const email=z.union([z.literal(''),z.email().max(254)]).default('');
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v,'Invalid calendar date');
const time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/,'Use a 24-hour HH:mm time');
const schemas={
 volunteerShifts:z.object({name,date,startTime:time,endTime:time,location:short,capacity:z.number().int().min(1).max(100000),eventId:fk,status:z.enum(['Open','Closed']).default('Open'),notes:str}).strict(),
 shiftReservations:z.object({shiftId:id,constituentId:id,status:z.enum(['Reserved','Waitlisted','Cancelled']),notes:str}).strict(),
 constituents:z.object({name,email,phone:short,type:z.enum(['Individual','Business','Foundation','Alumni','Employee','Staff','Community partner']),household:short,parentId:fk,contacts:z.array(z.object({name,email,role:short}).strict()).max(50).default([]),segments:short,preference:z.enum(['Email','Phone','Post','Do not contact']).default('Email'),notes:str}).strict(),
 designations:z.object({name,school:short,parentId:fk,accountCode:short,description:str}).strict(),
 campaigns:z.object({name,type:z.enum(['Annual','Capital','Major gifts','Planned giving','Matching gifts','Peer-to-peer']),goal:cents,startDate:date,endDate:date,status:z.enum(['Active','Planned','Completed']),description:str}).strict(),
 gifts:z.object({constituentId:id,amount:cents.min(1),type:z.enum(['Cash','In-kind','Grant','Fee payment','Employee giving','Sponsorship']),method:z.enum(['Check','Cash','Credit card','ACH','Payroll','In-kind']),date,campaignId:fk,allocations:z.array(z.object({designationId:id,amount:cents.min(1)}).strict()).min(1).max(100),externalRef:short,notes:str,tribute:short,softCreditId:fk,pledge:short,pledgeId:fk,grantId:fk,giftKind:z.enum(['One-time','Recurring','Pledge fulfillment','Matching gift','Planned gift']).default('One-time')}).strict(),
 grants:z.object({name,funderId:fk,amount:cents,awardedAmount:cents.default(0),awardDate:date.nullable().optional().default(null),stage:z.enum(['Prospect','Preparing','Submitted','Awarded','Declined','Closed']),deadline:date,reportDue:date.nullable().optional().default(null),notes:str}).strict(),
 volunteers:z.object({constituentId:id,skills:short,shift:short,eventId:fk,hours:z.number().min(0).max(1e6).default(0),capacity:z.number().int().min(0).max(1e6).optional(),notes:str}).strict(),
 events:z.object({name,date,location:short,capacity:z.number().int().min(1).max(100000),ticketPrice:cents.default(0),sponsorGoal:cents.default(0),notes:str}).strict(),
 tasks:z.object({title:name,dueDate:date,owner:short,ownerId:fk,status:z.enum(['Open','In progress','Completed']),priority:z.enum(['Normal','High']).default('Normal'),constituentId:fk,eventId:fk,notes:str}).strict(),
 pledges:z.object({name,constituentId:id,amount:cents.min(1),startDate:date,installments:z.number().int().min(1).max(120),frequency:z.enum(['Monthly','Quarterly','Annual']),designationId:fk,campaignId:fk,status:z.enum(['Active','Paused','Cancelled']).default('Active'),notes:str}).strict(),
 reportViews:z.object({name,filters:z.object({report:z.enum(['Contributions by donor','Gifts by designation','Gift ledger','First-time donors','Donor follow-up','Volunteer hours','Grant pipeline','Soft-credit recognition','Organization rollup','Household rollup','Pledge balances','Volunteer time ledger','Grant reconciliation']),start:z.union([date,z.literal('')]).default(''),end:z.union([date,z.literal('')]).default(''),type:z.enum(['All','Cash','In-kind','Grant','Fee payment','Employee giving','Sponsorship']).default('All'),schoolYear:z.string().max(30).regex(/^(All|\d{4}|\d{4}[–-]\d{4})$/).default('All'),excludeFees:z.boolean().default(true),inactiveDays:z.number().int().min(1).max(3650).default(90)}).strict()}).strict(),
 evaluations:z.object({scenarioId:z.enum(['giving','pledges','recognition','grants','volunteers','events','stewardship','reporting','access','shifts','operations']),tester:name,result:z.enum(['Passed','Needs attention','Blocked']),severity:z.enum(['Low','Medium','High']).default('Medium'),actual:z.string().trim().min(1).max(8000),reproduction:str,notes:str}).strict(),
 communications:z.object({constituentId:fk,subject:name,channel:z.enum(['Email','Phone','Meeting','Post']),status:z.enum(['Draft','Logged']),date,body:str,notes:str}).strict()
};
const hash=v=>createHash('sha256').update(v).digest('hex');
const passwordHash=p=>{const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(p,salt,64).toString('hex');};
function verifyPassword(p,stored){try{const [s,h]=stored.split(':');const expected=Buffer.from(h,'hex');return timingSafeEqual(scryptSync(p,s,64),expected);}catch{return false;}}
class ApiError extends Error{constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new ApiError(status,message);};
const now=()=>new Date().toISOString();
const publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role});
const accountView=u=>({...publicUser(u),active:Boolean(u.active),version:u.version});
const validRoles=new Set(['admin','staff','viewer','event-helper']);

export function createApp({dbPath=':memory:',seed=true,tenantId=null,tenantInfo=null,initialAdmin=null,aiPolicy=null,isTenantActive=()=>true,mfaKey=process.env.MFA_ENCRYPTION_KEY,mfaClock=Date.now,reminderClock=Date.now,reminderWorker=true,workflowClock=Date.now,workflowWorker=true,hostedGiving=null,hostedGivingClock=Date.now,documentStorage=null,documentTenantId=tenantId,documentScanner=null}={}) {
 const evaluator=process.env.EVALUATOR_MODE==='true';
 const production=process.env.NODE_ENV==='production';
 const acceptanceEnabled=!production||process.env.ENABLE_ACCEPTANCE==='true';
 const demoAccess=evaluator||seed&&(!production||process.env.ALLOW_DEMO==='true');
 if(production&&acceptanceEnabled)throw new Error('Production cannot enable evaluator acceptance features. Use a separate synthetic deployment outside production.');
 if(evaluator){if(process.env.NODE_ENV==='production')throw new Error('Local evaluator mode cannot run in production.');if(process.env.APP_HOST&&!['127.0.0.1','localhost','::1'].includes(process.env.APP_HOST))throw new Error('Local evaluator mode requires a loopback APP_HOST.');if(process.env.APP_ORIGIN){let origin;try{origin=new URL(process.env.APP_ORIGIN);}catch{throw new Error('Local evaluator APP_ORIGIN must be a loopback HTTP origin.');}if(origin.protocol!=='http:'||!['127.0.0.1','localhost','[::1]'].includes(origin.hostname)||origin.origin!==process.env.APP_ORIGIN)throw new Error('Local evaluator APP_ORIGIN must be a loopback HTTP origin.');}}
 if(production&&(seed||process.env.ALLOW_DEMO==='true'))throw new Error('Production cannot enable demonstration seed or ALLOW_DEMO. Use a fresh production database.');
 if(process.env.NODE_ENV==='production') {
  let origin;try{origin=new URL(process.env.APP_ORIGIN);}catch{throw new Error('Production requires APP_ORIGIN as an HTTPS origin, for example https://crm.example.org.');}
  if(origin.protocol!=='https:'||origin.origin!==process.env.APP_ORIGIN||origin.username||origin.password)throw new Error('Production APP_ORIGIN must be an HTTPS origin without path, credentials, query or fragment.');
 }
 if(dbPath!==':memory:') mkdirSync(dirname(dbPath),{recursive:true});
 if(production)assertMfaEncryptionKey(mfaKey);
 const db=new DatabaseSync(dbPath);
 if(production&&db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name='users'").get()&&db.prepare('SELECT email,password_hash FROM users').all().some(u=>['alex@foundation.example','staff@foundation.example','board@foundation.example'].includes(u.email.toLowerCase())||verifyPassword('FoundationDemo!2026',u.password_hash))){db.close();throw new Error('Demonstration accounts or credentials detected. Use a reviewed production database; no data conversion is performed.');}
 db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;');
 db.exec(`CREATE TABLE IF NOT EXISTS records(collection TEXT NOT NULL,id TEXT NOT NULL,data TEXT NOT NULL,PRIMARY KEY(collection,id));
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,role TEXT NOT NULL,password_hash TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),csrf TEXT NOT NULL,expires INTEGER NOT NULL,last_seen INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),data TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,actor TEXT NOT NULL,action TEXT NOT NULL,collection TEXT,record_id TEXT,at TEXT NOT NULL,details TEXT NOT NULL);
 CREATE TRIGGER IF NOT EXISTS audit_no_update BEFORE UPDATE ON audit BEGIN SELECT RAISE(ABORT,'Audit is append-only'); END;
 CREATE TRIGGER IF NOT EXISTS audit_no_delete BEFORE DELETE ON audit BEGIN SELECT RAISE(ABORT,'Audit is append-only'); END;`);
 // Additive migration preserves existing users and credentials.
 const userColumns=new Set(db.prepare('PRAGMA table_info(users)').all().map(c=>c.name));
 if(!userColumns.has('active'))db.exec('ALTER TABLE users ADD COLUMN active INTEGER NOT NULL DEFAULT 1');
 if(!userColumns.has('version'))db.exec('ALTER TABLE users ADD COLUMN version INTEGER NOT NULL DEFAULT 1');
 db.prepare('INSERT OR IGNORE INTO settings VALUES(1,?)').run(JSON.stringify({organizationName:'Wimblo',fiscalStartMonth:7}));
 const getSettings=()=>JSON.parse(db.prepare('SELECT data FROM settings WHERE id=1').get().data);
 const list=c=>db.prepare('SELECT data FROM records WHERE collection=? ORDER BY rowid').all(c).map(r=>JSON.parse(r.data));
 const get=(c,i)=>{const r=db.prepare('SELECT data FROM records WHERE collection=? AND id=?').get(c,i);if(!r)fail(404,'Record not found');return JSON.parse(r.data);};
 const exists=(c,i)=>{if(i==null)return true;const row=db.prepare('SELECT data FROM records WHERE collection=? AND id=?').get(c,i);return Boolean(row&&!JSON.parse(row.data).mergedInto);};
 let fundraisingGuard=null,eventGuard=null,eventHelperGuard=null,tributeGuard=null,grantGuard=null,receiptGuard=null,taskOwnership=null,peerFundraisingGuard=null,hostedGivingService=null;
 const put=(c,r)=>{const previous=db.prepare('SELECT data FROM records WHERE collection=? AND id=?').get(c,r.id);if(previous){const old=JSON.parse(previous.data);fundraisingGuard?.validateMutation(c,old,r);peerFundraisingGuard?.validateMutation(c,old,r);hostedGivingService?.validateMutation(c,old,r);eventGuard?.validateMutation(c,old,r);tributeGuard?.validateMutation(c,old,r);receiptGuard?.validateMutation(c,old,r);}return db.prepare('INSERT INTO records VALUES(?,?,?) ON CONFLICT(collection,id) DO UPDATE SET data=excluded.data').run(c,r.id,JSON.stringify(r));};
 const transaction=fn=>{db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}};
 const audit=(u,action,c,r,details={})=>db.prepare('INSERT INTO audit(actor,action,collection,record_id,at,details) VALUES(?,?,?,?,?,?)').run(u?.id||'system',action,c||null,r||null,now(),JSON.stringify(details));
 const schoolYear=d=>{const y=+d.slice(0,4),m=+d.slice(5,7),month=getSettings().fiscalStartMonth;if(month===1)return String(y);const start=m>=month?y:y-1;return `${start}–${start+1}`;};
 const formatAssignedYear=(start,month=getSettings().fiscalStartMonth)=>month===1?String(start).padStart(4,'0'):`${String(start).padStart(4,'0')}–${String(start+1).padStart(4,'0')}`;
 const giftSchoolYear=gift=>gift.schoolYearOverride?formatAssignedYear(Number(gift.schoolYearOverride.slice(0,4))):schoolYear(gift.date);
 function parseAssignedYear(value){if(value===null)return null;const month=getSettings().fiscalStartMonth;const match=month===1?/^(\d{4})$/.exec(value):/^(\d{4})[–-](\d{4})$/.exec(value);if(!match||Number(match[1])>9998||(month!==1&&Number(match[2])!==Number(match[1])+1))fail(400,month===1?'Use a four-digit calendar year':'Use consecutive fiscal years, for example 2026–2027');return formatAssignedYear(Number(match[1]),month);}
 function validate(c,data,recordId=null,old=null){
  if(!schemas[c])fail(404,'Unknown collection');
  const parsed=schemas[c].parse(data);
  const refs=[];
  if(c==='constituents')refs.push(['constituents',parsed.parentId]);
  if(c==='designations')refs.push(['designations',parsed.parentId]);
  if(['gifts','volunteers','tasks','communications','pledges'].includes(c))refs.push(['constituents',parsed.constituentId]);
  if(c==='tasks'){
   if(parsed.ownerId){const u=db.prepare('SELECT id,name,role,active FROM users WHERE id=?').get(parsed.ownerId);if(!u||!u.active||!['admin','staff'].includes(u.role)){if(!old||old.ownerId!==parsed.ownerId)fail(400,'Choose an active staff owner; viewers cannot own tasks.');}else parsed.owner=u.name;}
   else if(parsed.owner.trim()&&!(old&&!old.ownerId&&parsed.owner===old.owner)){const candidates=db.prepare("SELECT id,name FROM users WHERE active=1 AND role IN ('admin','staff') AND name=?").all(parsed.owner.trim());if(candidates.length===1){parsed.ownerId=candidates[0].id;parsed.owner=candidates[0].name;}else if(!old||old.ownerId||parsed.owner!==old.owner)fail(400,'Choose a current staff account rather than a free-text owner.');}
  }
  if(c==='gifts'){if((parsed.type==='In-kind')!==(parsed.method==='In-kind'))fail(400,'In-kind gifts must use the In-kind method; other gift types cannot');refs.push(['campaigns',parsed.campaignId],['constituents',parsed.softCreditId]);for(const a of parsed.allocations)refs.push(['designations',a.designationId]);if(parsed.allocations.reduce((n,a)=>n+a.amount,0)!==parsed.amount)fail(400,'Allocations must sum to gift amount');if(new Set(parsed.allocations.map(a=>a.designationId)).size!==parsed.allocations.length)fail(400,'Duplicate designation allocation');if(parsed.externalRef&&list('gifts').some(g=>g.externalRef===parsed.externalRef&&g.id!==recordId))fail(409,'Duplicate externalRef');}
  if(c==='pledges')refs.push(['designations',parsed.designationId],['campaigns',parsed.campaignId]);
  if(c==='gifts')refs.push(['pledges',parsed.pledgeId],['grants',parsed.grantId]);
  if(c==='grants')refs.push(['constituents',parsed.funderId]);
  if(c==='volunteers'||c==='tasks'||c==='volunteerShifts')refs.push(['events',parsed.eventId]);
  if(c==='shiftReservations')refs.push(['volunteerShifts',parsed.shiftId],['constituents',parsed.constituentId]);
  for(const [target,key] of refs)if(!exists(target,key))fail(400,`Invalid ${target} reference`);
  if(c==='volunteerShifts'){
   if(parsed.startTime>=parsed.endTime)fail(400,'Shift end must follow start on the same date');
   const reservations=list('shiftReservations').filter(r=>r.shiftId===recordId);
   if(reservations.filter(r=>r.status==='Reserved').length>parsed.capacity)fail(409,'Capacity cannot be below reserved places');
   if(old&&reservations.length&&['date','startTime','endTime','eventId'].some(k=>parsed[k]!==old[k]))fail(409,'Shift date, times and event cannot change after reservations; create a new shift');
  }
  if(c==='shiftReservations'){
   if(old&&(parsed.shiftId!==old.shiftId||parsed.constituentId!==old.constituentId))fail(409,'Reservation identity cannot change; cancel and create a new reservation');
   const shift=get('volunteerShifts',parsed.shiftId);
   if(!['Individual','Alumni','Employee','Staff'].includes(get('constituents',parsed.constituentId).type))fail(400,'Reserve volunteer places for an individual, alumni, employee or staff constituent');
   if(parsed.status!=='Cancelled'){
    if((!old||old.status!==parsed.status)&&shift.status!=='Open')fail(409,'Closed shifts cannot accept reservations or waitlist changes');
    const active=list('shiftReservations').filter(r=>r.id!==recordId&&r.status!=='Cancelled');
    if(active.some(r=>r.shiftId===parsed.shiftId&&r.constituentId===parsed.constituentId))fail(409,'This person already has an active reservation or waitlist place');
    if(parsed.status==='Reserved'){
     if(active.filter(r=>r.shiftId===parsed.shiftId&&r.status==='Reserved').length>=shift.capacity)fail(409,'Shift is full; choose the waitlist');
     if(active.filter(r=>r.constituentId===parsed.constituentId&&r.status==='Reserved').some(r=>{const other=get('volunteerShifts',r.shiftId);return other.date===shift.date&&other.startTime<shift.endTime&&shift.startTime<other.endTime;}))fail(409,'This person has an overlapping reserved shift');
    }
   }
  }
  if(c==='constituents'&&recordId&&!['Individual','Alumni','Employee','Staff'].includes(parsed.type)&&list('shiftReservations').some(r=>r.constituentId===recordId))fail(409,'Constituent type is protected by volunteer reservation history');
  if(c==='constituents'||c==='designations'){let parent=parsed.parentId;const seen=new Set(recordId?[recordId]:[]);while(parent){if(seen.has(parent))fail(400,'Hierarchy cycle');seen.add(parent);parent=get(c,parent).parentId;}}
  if(c==='gifts'&&old?.acknowledgment&&(parsed.constituentId!==old.constituentId||parsed.type!==old.type))fail(409,'Acknowledged gift donor and revenue type cannot change');
  if(c==='communications'&&old&&(old.giftId||list('gifts').some(g=>g.acknowledgment?.communicationId===old.id))&&['constituentId','status','date','channel'].some(key=>parsed[key]!==old[key]))fail(409,'Linked acknowledgment identity, status, date and channel cannot change');
  if(c==='gifts'&&parsed.pledgeId){const pledge=get('pledges',parsed.pledgeId);if(parsed.constituentId!==pledge.constituentId)fail(400,'Gift donor must match pledge donor');if(['Fee payment','In-kind'].includes(parsed.type))fail(400,'Pledge receipts must be monetary contributions');const received=list('gifts').filter(g=>g.id!==recordId&&g.pledgeId===pledge.id&&g.status!=='Voided').reduce((total,g)=>total+g.amount,0);if(received+parsed.amount>pledge.amount)fail(409,'Gift exceeds outstanding pledge commitment');}
  if(c==='gifts'&&parsed.grantId){if(parsed.pledgeId)fail(400,'A gift cannot reconcile both a grant and a pledge');if(parsed.type!=='Grant')fail(400,'Linked grant receipts must use the Grant revenue type');const grant=get('grants',parsed.grantId);if(grant.funderId&&parsed.constituentId!==grant.funderId)fail(400,'Gift donor must match grant funder');const received=list('gifts').filter(g=>g.id!==recordId&&g.grantId===grant.id&&g.status!=='Voided').reduce((total,g)=>total+g.amount,0);if(!grant.awardedAmount||received+parsed.amount>grant.awardedAmount)fail(409,'Receipt exceeds the recorded grant award');}
  if(c==='grants'){if(parsed.awardedAmount>0&&(!['Awarded','Closed'].includes(parsed.stage)||!parsed.awardDate))fail(400,'A positive grant award requires Awarded or Closed stage and an award date');if(recordId){const receipts=list('gifts').filter(g=>g.grantId===recordId&&g.status!=='Voided');if(parsed.funderId&&receipts.some(g=>g.constituentId!==parsed.funderId))fail(409,'Grant funder cannot change while posted receipts are linked');if(receipts.reduce((total,g)=>total+g.amount,0)>parsed.awardedAmount)fail(409,'Grant award cannot be below posted receipts');}}
  if(c==='pledges'&&recordId){const receipts=list('gifts').filter(g=>g.pledgeId===recordId&&g.status!=='Voided');if(receipts.some(g=>g.constituentId!==parsed.constituentId))fail(409,'Pledge donor cannot change while received gifts are linked');if(receipts.reduce((total,g)=>total+g.amount,0)>parsed.amount)fail(409,'Pledge amount cannot be below received gifts');}
  if(c==='evaluations'&&parsed.result!=='Passed'&&!parsed.reproduction.trim())fail(400,'Reproduction details are required for a finding or blocked test');
  if(c==='reportViews'&&parsed.filters.start&&parsed.filters.end&&parsed.filters.start>parsed.filters.end)fail(400,'Report end date precedes start date');
  if(c==='volunteers'&&old&&parsed.constituentId!==old.constituentId&&list('volunteerTime').some(t=>t.volunteerId===old.id))fail(409,'Volunteer identity cannot change after time is recorded; create a new volunteer record');
  if(c==='volunteers'&&old?.clockIn&&(parsed.constituentId!==old.constituentId||parsed.eventId!==old.eventId))fail(409,'Clock out before changing volunteer or event');
  if(c==='campaigns'&&parsed.startDate>parsed.endDate)fail(400,'End date precedes start date');
  if(c==='events'&&old&&parsed.capacity<old.registrations.length)fail(409,'Capacity below existing registrations');
  if(c==='communications'&&parsed.status==='Draft'&&parsed.constituentId&&get('constituents',parsed.constituentId).preference==='Do not contact')fail(400,'Do not contact: draft blocked');
  return parsed;
 }
 function create(c,data,u){if(c==='volunteerTime')fail(403,'Volunteer time is generated by clocks and corrected through its dedicated endpoint');const p=validate(c,data);const r={...p,id:randomUUID(),version:1,createdAt:now(),updatedAt:now()};if(c==='gifts'){r.status='Posted';r.schoolYear=schoolYear(r.date);}if(c==='events')r.registrations=[];if(c==='volunteers')r.clockIn=null;put(c,r);audit(u,'create',c,r.id);if(c==='tasks')taskOwnership?.retain(null,r,u);if(c==='volunteers'&&r.hours>0)addTime(r,{startAt:null,endAt:null,hours:r.hours,source:'Historical',notes:'Undated initial hours; original activity dates unavailable.'},u,`historical-${r.id}`);return r;}
 function addTime(volunteer,fields,u,recordId=randomUUID()){const record={volunteerId:volunteer.id,constituentId:volunteer.constituentId,eventId:volunteer.eventId||null,...fields,id:recordId,version:1,createdAt:now(),updatedAt:now()};put('volunteerTime',record);audit(u,'create_time','volunteerTime',record.id,{source:record.source,hours:record.hours});return record;}
 function versionCheck(r,v){if(!Number.isInteger(v)||v<1)fail(400,'Integer version required');if(r.version!==v)fail(409,'Record changed; reload before saving');}
 function updateSpecial(c,r,u,action){r.version++;r.updatedAt=now();put(c,r);audit(u,action,c,r.id);return r;}
 if(seed&&!db.prepare('SELECT 1 FROM users LIMIT 1').get())transaction(()=>{
  for(const [n,e,role]of [['Alex Morgan','alex@foundation.example','admin'],['Casey Rivera','staff@foundation.example','staff'],['Jordan Lee','board@foundation.example','viewer']])db.prepare('INSERT INTO users(id,name,email,role,password_hash) VALUES(?,?,?,?,?)').run(randomUUID(),n,e,role,passwordHash('FoundationDemo!2026'));
  const school=create('designations',{name:'Canyon View School',school:'Canyon View',parentId:null,accountCode:'SYN-101'},null);
  const pantry=create('designations',{name:'Principal pantry',school:'District-wide',parentId:null,accountCode:'SYN-200'},null);
  const stem=create('designations',{name:'STEM classroom supplies',school:'Canyon View',parentId:school.id,accountCode:'SYN-101-STEM'},null);
  const donor=create('constituents',{name:'Taylor Bennett',email:'taylor@example.test',type:'Individual',household:'Bennett household',segments:'Monthly donor,Volunteer',notes:'Synthetic donor for evaluator testing.'},null);
  const business=create('constituents',{name:'Aspen Community Partners',email:'hello@example.test',type:'Business',contacts:[{name:'Robin Parker',email:'robin@example.test',role:'Community liaison'}],segments:'Sponsor'},null);
  const person=create('constituents',{name:'Sam Chen',email:'sam@example.test',type:'Employee',segments:'Employee giving'},null);
  create('constituents',{name:'Morgan Ellis',email:'morgan@example.test',type:'Alumni',preference:'Do not contact',notes:'Synthetic opt-out record.'},null);
  const campaign=create('campaigns',{name:'Classrooms for tomorrow',type:'Annual',goal:10000000,startDate:'2026-07-01',endDate:'2027-06-30',status:'Active',description:'Synthetic school-year campaign'},null);
  create('campaigns',{name:'Community matching week',type:'Matching gifts',goal:2500000,startDate:'2026-10-01',endDate:'2026-10-07',status:'Planned'},null);
  for(const [who,amt,type,method,day,dest,kind]of [[donor,25000,'Cash','Check','2025-09-12',pantry,'One-time'],[donor,50000,'Cash','Credit card','2026-07-15',stem,'Recurring'],[business,200000,'Sponsorship','Check','2026-08-20',pantry,'One-time'],[person,12500,'Employee giving','Payroll','2026-09-01',stem,'One-time'],[business,75000,'In-kind','In-kind','2026-09-05',pantry,'One-time'],[donor,3500,'Fee payment','Credit card','2026-09-08',school,'One-time']])create('gifts',{constituentId:who.id,amount:amt,type,method,date:day,campaignId:campaign.id,allocations:[{designationId:dest.id,amount:amt}],externalRef:'SYN-'+day+'-'+type,giftKind:kind},null);
  const event=create('events',{name:'Community classroom benefit',date:'2026-10-03',location:'Synthetic community center',capacity:80,ticketPrice:3500,sponsorGoal:500000},null);
  create('volunteers',{constituentId:donor.id,skills:'Event welcome, sorting supplies',shift:'10:00–12:00',eventId:event.id,hours:8},null);
  create('volunteers',{constituentId:person.id,skills:'STEM mentoring',shift:'14:00–16:00',hours:4.5},null);
  create('grants',{name:'Classroom innovation grant',funderId:business.id,amount:1500000,stage:'Preparing',deadline:'2026-10-15',reportDue:'2027-03-01',notes:'Synthetic prospect; no actual funder commitment.'},null);
  create('grants',{name:'Student pantry support',amount:750000,stage:'Awarded',deadline:'2026-08-01',reportDue:'2026-12-01'},null);
  create('tasks',{title:'Review classroom benefit registration',dueDate:'2026-09-22',owner:'Alex Morgan',status:'Open',priority:'High',constituentId:business.id},null);
  create('tasks',{title:'Prepare quarterly board report',dueDate:'2026-09-30',owner:'Casey Rivera',status:'In progress'},null);
  create('communications',{constituentId:donor.id,subject:'Thank-you note preview',channel:'Email',status:'Draft',date:'2026-09-13',body:'Dear {{name}}, thank you for supporting our classrooms. This is an unsent synthetic draft.'},null);
  create('communications',{constituentId:business.id,subject:'Sponsorship conversation',channel:'Phone',status:'Logged',date:'2026-09-09',body:'Synthetic call notes for demonstration.'},null);
  const arts=create('designations',{name:'Creative arts classroom',school:'Canyon View',parentId:school.id,accountCode:'SYN-101-ART'},null);
  const scholarships=create('designations',{name:'Student opportunity scholarships',school:'District-wide',accountCode:'SYN-300'},null);
  create('designations',{name:'Meadow Ridge School',school:'Meadow Ridge',accountCode:'SYN-400'},null);
  const pantryCampaign=create('campaigns',{name:'Full shelves, bright futures',type:'Annual',goal:6000000,startDate:'2026-07-01',endDate:'2027-06-30',status:'Active',description:'Synthetic pantry fundraising'},null);
  const scholarshipCampaign=create('campaigns',{name:'Opportunity scholarships',type:'Major gifts',goal:8000000,startDate:'2026-07-01',endDate:'2027-06-30',status:'Active'},null);
  const syntheticNames=['Avery Collins','Riley Brooks','Jamie Patel','Drew Sullivan','Quinn Anderson','Peyton Ross','Dakota Foster','Emerson Reed','Skyler Nguyen','Cameron Diaz','Reese Cooper','Finley Adams','Rowan Mitchell','Hayden Carter','Blake Wilson','Sage Thompson'];
  const extraDonors=syntheticNames.map((n,i)=>create('constituents',{name:n,email:`donor${i+1}@example.test`,type:i%5===0?'Employee':'Individual',household:n.split(' ').at(-1)+' household',segments:i%3===0?'Volunteer,Annual donor':'Annual donor',preference:i===15?'Do not contact':'Email',notes:'Synthetic evaluator record; no real personal data.'},null));
  for(let i=0;i<22;i++){const donor=extraDonors[i%extraDonors.length],amount=(i+2)*12500,month=i<4?'2025-09':`2026-${String(7+i%3).padStart(2,'0')}`,day=String(2+i%24).padStart(2,'0');const dest=[stem,pantry,arts,scholarships][i%4],activeCampaign=[campaign,pantryCampaign,scholarshipCampaign][i%3];create('gifts',{constituentId:donor.id,amount,type:i%7===0?'Employee giving':'Cash',method:i%7===0?'Payroll':i%2?'Check':'Credit card',date:month+'-'+day,campaignId:activeCampaign.id,allocations:[{designationId:dest.id,amount}],externalRef:'SYN-ADDITIONAL-'+i,giftKind:i%4===0?'Recurring':'One-time'},null);}
  for(const [title,due,owner]of [['Confirm pantry volunteer shift','2026-09-18','Casey Rivera'],['Review scholarship prospect list','2026-09-25','Alex Morgan'],['Draft October community newsletter','2026-10-01','Casey Rivera']])create('tasks',{title,dueDate:due,owner,status:'Open'},null);

 });
 transaction(()=>{
  for(const grant of list('grants'))if(grant.awardedAmount===undefined||grant.awardDate===undefined){put('grants',{...grant,awardedAmount:grant.awardedAmount??0,awardDate:grant.awardDate??null});audit(null,'upgrade_grant_fields','grants',grant.id);}
  const settings=getSettings();if(['Foundation CRM · Evaluator pilot','Jordan Education Foundation','Jordan Foundation'].includes(settings.organizationName)){const previousName=settings.organizationName;settings.organizationName='Wimblo';db.prepare('UPDATE settings SET data=? WHERE id=1').run(JSON.stringify(settings));audit(null,'upgrade_brand',null,null,{previousName,organizationName:'Wimblo'});}
  for(const volunteer of list('volunteers'))if(volunteer.hours>0&&!list('volunteerTime').some(t=>t.volunteerId===volunteer.id))addTime(volunteer,{startAt:null,endAt:null,hours:volunteer.hours,source:'Historical',notes:'Migrated legacy total; original activity dates unavailable.'},null,`historical-${volunteer.id}`);
  const synthetic=db.prepare("SELECT 1 FROM users WHERE email='alex@foundation.example'").get();
  if(seed&&synthetic&&!exists('pledges','synthetic-pledge-classrooms-2026')){const donor=list('constituents').find(c=>c.email==='taylor@example.test'),designation=list('designations').find(d=>d.accountCode==='SYN-101-STEM'),campaign=list('campaigns').find(c=>c.name==='Classrooms for tomorrow');if(donor&&designation){const p=validate('pledges',{name:'Classroom opportunity pledge',constituentId:donor.id,amount:300000,startDate:'2026-07-15',installments:6,frequency:'Monthly',designationId:designation.id,campaignId:campaign?.id||null,status:'Active',notes:'Synthetic installment commitment; only linked posted gifts count as received.'});const pledge={...p,id:'synthetic-pledge-classrooms-2026',version:1,createdAt:now(),updatedAt:now()};put('pledges',pledge);audit(null,'seed_pledge','pledges',pledge.id);const receipt=list('gifts').find(g=>g.externalRef==='SYN-2026-07-15-Cash'&&g.constituentId===donor.id&&g.status!=='Voided'&&!g.pledgeId&&g.amount<=pledge.amount);if(receipt)updateSpecial('gifts',{...receipt,pledgeId:pledge.id},null,'seed_pledge_receipt');}}
 });
 if(!seed&&!db.prepare('SELECT 1 FROM users LIMIT 1').get()&&(initialAdmin||production)) {
  const bootstrap=z.object({email:z.email().max(254),name:z.string().trim().min(1).max(250),password:z.string().min(16).max(200).refine(p=>/[a-z]/.test(p)&&/[A-Z]/.test(p)&&/[0-9]/.test(p)&&/[^a-zA-Z0-9]/.test(p),'Strong password required')}).safeParse(initialAdmin||{email:process.env.ADMIN_EMAIL,name:process.env.ADMIN_NAME,password:process.env.ADMIN_PASSWORD});
  if(production&&bootstrap.success&&(bootstrap.data.password==='FoundationDemo!2026'||['alex@foundation.example','staff@foundation.example','board@foundation.example'].includes(bootstrap.data.email.toLowerCase()))){db.close();throw new Error('Production bootstrap cannot use a known demonstration password.');}if(!bootstrap.success){db.close();throw new Error('Empty production database requires ADMIN_EMAIL, ADMIN_NAME and ADMIN_PASSWORD (16+ characters, upper/lowercase, number and symbol).');}
  transaction(()=>{const u=bootstrap.data;const key=randomUUID();db.prepare('INSERT INTO users(id,name,email,role,password_hash) VALUES(?,?,?,?,?)').run(key,u.name,u.email.toLowerCase(),'admin',passwordHash(u.password));audit({id:key},'bootstrap_admin',null,key);});
 }
 if(production&&db.prepare("SELECT 1 FROM users WHERE email IN ('alex@foundation.example','staff@foundation.example','board@foundation.example')").get()){db.close();throw new Error('Demo accounts detected. Use a fresh production DB_PATH and real administrator configuration.');}
 const dummyHash=passwordHash(randomBytes(32).toString('hex'));
 for(const [name,definition] of [['mfa_verified','INTEGER NOT NULL DEFAULT 0'],['account_binding',"TEXT NOT NULL DEFAULT ''"]])if(!db.prepare('PRAGMA table_info(sessions)').all().some(c=>c.name===name))db.exec(`ALTER TABLE sessions ADD COLUMN ${name} ${definition}`);
 const app=express();app.locals.db=db;app.locals.close=()=>db.close();app.locals.revokeAllSessions=()=>db.prepare('DELETE FROM sessions').run().changes;
 if(process.env.TRUST_PROXY==='true')app.set('trust proxy',1);
 app.use(helmet());
 const webhookLimits=new Map();
 app.post('/api/hosted-giving/webhook',(req,res,next)=>{res.set('Cache-Control','no-store');if(req.get('Origin'))return res.status(403).json({error:'Provider callback origin denied'});const tick=Date.now(),key=req.ip;for(const [ip,value]of webhookLimits)if(value.until<tick)webhookLimits.delete(ip);let rate=webhookLimits.get(key);if(!rate){if(webhookLimits.size>=1024)return res.status(429).json({error:'Provider callback limit exceeded'});rate={count:0,until:tick+60000};webhookLimits.set(key,rate);}if(++rate.count>300)return res.status(429).json({error:'Provider callback limit exceeded'});next();},express.raw({type:'application/json',limit:'256kb'}),(req,res,next)=>{try{if(!hostedGivingService)fail(503,'Hosted giving is unavailable');res.json(hostedGivingService.receive(req.body,req.get('Stripe-Signature')));}catch(e){next(e);}});
 app.use(express.json({limit:'2mb'}));
 app.get('/api/health',(req,res)=>{res.set('Cache-Control','no-store');res.json({status:'ok',version:'0.5.0',mode:evaluator?'evaluator':process.env.NODE_ENV==='production'?'production':'local'});});
 const allowed=new Set(process.env.NODE_ENV==='production'?[process.env.APP_ORIGIN]:['http://localhost:5174','http://127.0.0.1:5174','http://localhost:5173','http://127.0.0.1:5173','http://localhost:4311','http://127.0.0.1:4311',...(evaluator?[`http://127.0.0.1:${process.env.PORT||4321}`,`http://localhost:${process.env.PORT||4321}`]:[]),...(process.env.APP_ORIGIN?[process.env.APP_ORIGIN]:[])]);
 app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(process.env.NODE_ENV==='production'&&!req.secure)return res.status(403).json({error:'HTTPS required; configure the trusted reverse proxy explicitly'});const origin=req.get('Origin');if(origin&&!allowed.has(origin))return res.status(403).json({error:'Origin denied'});if(origin){res.set('Access-Control-Allow-Origin',origin);res.set('Vary','Origin');res.set('Access-Control-Allow-Credentials','true');res.set('Access-Control-Allow-Headers','Content-Type,X-CSRF-Token');res.set('Access-Control-Allow-Methods','GET,POST,PUT,PATCH,DELETE,OPTIONS');}if(req.method==='OPTIONS')return res.sendStatus(204);next();});
 if(tenantId&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(tenantId))throw new Error('Invalid tenant session namespace');
 const cookieName=tenantId?'wimblo_tenant_'+tenantId.replaceAll('-','')+'_session':evaluator?'jordan_everbright_evaluator_session':'foundation_session';const cookieOptions={httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',path:'/',maxAge:8*3600*1000};
 app.get('/api/config',(req,res)=>res.json({demoAccess,acceptanceEnabled,...(tenantInfo?{tenant:tenantInfo,platformAvailable:true}:{})}));
 const auth=(req,res,next)=>{try{const cookie=(req.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='));const token=cookie?.slice(cookieName.length+1);const session=token&&db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(hash(token));const time=Date.now();if(!session||session.expires<time||session.last_seen<time-30*60*1000){if(session)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(session.token_hash);fail(401,'Authentication required');}const user=db.prepare('SELECT * FROM users WHERE id=?').get(session.user_id);if(!user||!user.active||!validRoles.has(user.role))fail(401,'Authentication required');if(session.account_binding!==mfaAccountBinding(user)){db.prepare('DELETE FROM sessions WHERE token_hash=?').run(session.token_hash);fail(401,'Account access changed. Sign in again');}const factor=mfa.status(user);if(session.mfa_verified===1&&!factor.enabled){db.prepare('DELETE FROM sessions WHERE token_hash=?').run(session.token_hash);fail(401,'MFA enrollment changed. Sign in again');}if(factor.enabled&&(!factor.available||session.mfa_verified!==1))fail(factor.available?401:503,'MFA-authenticated session required');db.prepare('UPDATE sessions SET last_seen=? WHERE token_hash=?').run(time,session.token_hash);req.user=publicUser(user);req.session=session;next();}catch(e){next(e);}};
 const csrf=(req,res,next)=>{if(req.get('X-CSRF-Token')!==req.session.csrf)return res.status(403).json({error:'Invalid CSRF token'});next();};
 const write=(req,res,next)=>{if(!['admin','staff'].includes(req.user.role))return res.status(403).json({error:'Readonly role'});next();};
 const admin=(req,res,next)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Administrator required'});next();};
 const mfa=createMfaService({db,audit,verifyPassword,key:mfaKey,clock:mfaClock,roles:[...validRoles]});
 const issueSession=(u,res,{mfaVerified=false,expectedBinding=mfaAccountBinding(u)}={})=>{const account=db.prepare('SELECT * FROM users WHERE id=?').get(u.id);if(!account?.active||!validRoles.has(account.role)||mfaAccountBinding(account)!==expectedBinding)fail(401,'Account access changed. Sign in again');const time=Date.now(),token=randomBytes(32).toString('hex'),csrfToken=randomBytes(32).toString('hex'),mfaEnrollmentRequired=production&&account.role==='admin'&&!mfaVerified;db.prepare('INSERT INTO sessions(token_hash,user_id,csrf,expires,last_seen,mfa_verified,account_binding) VALUES(?,?,?,?,?,?,?)').run(hash(token),account.id,csrfToken,time+8*3600*1000,time,mfaVerified?1:0,mfaAccountBinding(account));res.cookie(cookieName,token,cookieOptions).json({user:publicUser(account),csrfToken,...(mfaEnrollmentRequired?{mfaEnrollmentRequired:true,access:'MFA enrollment only'}:{})});};
 const limits=new Map();
 app.post('/api/auth/login',(req,res)=>{const {email:mail,password}=z.object({email:z.email().max(254),password:z.string().min(1).max(200)}).strict().parse(req.body);const key=req.ip+':'+mail.toLowerCase();const time=Date.now();const ipKey='ip:'+req.ip;let ipAttempts=limits.get(ipKey);if(!ipAttempts||ipAttempts.until<time){ipAttempts={count:0,until:time+15*60*1000};limits.set(ipKey,ipAttempts);}if(ipAttempts.count>=50)fail(429,'Too many login attempts');ipAttempts.count++;if(limits.size>10000)for(const [k,v]of limits)if(v.until<time)limits.delete(k);let attempts=limits.get(key);if(!attempts||attempts.until<time){attempts={count:0,until:time+15*60*1000};limits.set(key,attempts);}if(attempts.count>=10)fail(429,'Too many login attempts');attempts.count++;const u=db.prepare('SELECT * FROM users WHERE email=?').get(mail.toLowerCase());const verified=verifyPassword(password,u?.password_hash||dummyHash);if(!u||!verified||!u.active||!validRoles.has(u.role))fail(401,'Invalid email or password');limits.delete(key);if(mfa.status(u).enabled)return res.json({mfaRequired:true,...mfa.challenge(u)});issueSession(u,res);});
 app.post('/api/auth/mfa/verify',(req,res)=>{const body=z.object({challengeToken:z.string().regex(/^[a-f0-9]{64}$/),code:z.string().min(6).max(17)}).strict().parse(req.body);const result=mfa.verifyChallenge(body.challengeToken,body.code);issueSession(result.user,res,{mfaVerified:true,expectedBinding:result.accountBinding});});
 app.get('/api/auth/me',auth,(req,res)=>res.json({user:req.user,csrfToken:req.session.csrf,...(production&&req.user.role==='admin'&&req.session.mfa_verified!==1?{mfaEnrollmentRequired:true,access:'MFA enrollment only'}:{})}));
 app.post('/api/auth/logout',auth,csrf,(req,res)=>{db.prepare('DELETE FROM sessions WHERE token_hash=?').run(req.session.token_hash);res.clearCookie(cookieName,cookieOptions).json({ok:true});});
 app.use('/api',auth);
 app.get('/api/auth/mfa/status',(req,res)=>res.json({...mfa.status(req.user),...(production&&req.user.role==='admin'?{required:true}:{})}));
 app.post('/api/auth/mfa/enroll',csrf,(req,res)=>{const body=z.object({password:z.string().min(1).max(200)}).strict().parse(req.body);res.json(mfa.beginEnrollment(req.user,body.password));});
 app.post('/api/auth/mfa/confirm',csrf,(req,res)=>{const body=z.object({code:z.string().regex(/^\d{6}$/)}).strict().parse(req.body);const result=mfa.confirmEnrollment(req.user,body.code);res.clearCookie(cookieName,cookieOptions).json(result);});
 app.post('/api/auth/mfa/disable',csrf,(req,res)=>{const body=z.object({password:z.string().min(1).max(200),code:z.string().min(6).max(17)}).strict().parse(req.body);if(production&&req.user.role==='admin')fail(403,'Production administrators cannot disable required MFA. Use an unused recovery code or the approved account-recovery procedure');const result=mfa.disable(req.user,body.password,body.code);res.clearCookie(cookieName,cookieOptions).json(result);});
 app.use('/api',(req,res,next)=>{if(production&&req.user.role==='admin'&&req.session.mfa_verified!==1)return res.status(403).json({error:'Administrator MFA enrollment and fresh MFA sign-in are required before workspace access',mfaEnrollmentRequired:true});next();});
 eventHelperGuard=installEventHelperAccessRoutes(app,{db,get,list,audit,csrf,admin,transaction,isTenantActive,checkInTicket:(req,input)=>{if(!eventGuard)fail(503,'Event check-in is unavailable');return eventGuard.checkInTicket(req,input);},recheckAccess:req=>{
  const session=db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(req.session.token_hash),u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id),time=Date.now();
  if(!session||session.user_id!==req.user.id||session.expires<time||session.last_seen<time-30*60*1000||!u?.active||!validRoles.has(u.role)||u.role!==req.user.role||session.account_binding!==mfaAccountBinding(u))return false;
  const factor=mfa.status(u);return factor.enabled?factor.available&&session.mfa_verified===1:session.mfa_verified!==1&&!(production&&u.role==='admin');
 }});
 app.use('/api',(req,res,next)=>req.user.role==='event-helper'?res.status(403).json({error:'This account can check in tickets for assigned events only'}):next());
 tributeGuard=installTributeRoutes(app,{db,list,get,getSettings,audit,csrf,write,admin,transaction});
 for(const route of ['/api/identity/merge/preview','/api/identity/merge'])app.post(route,csrf,admin,(req,res,next)=>{if([req.body?.sourceId,req.body?.targetId].some(id=>typeof id==='string'&&tributeGuard.hasConstituentReferences(id)))return res.status(409).json({error:'This identity has retained tribute or notification history. Historical consolidation requires a reviewed alias workflow.'});next();});
 fundraisingGuard=installFundraisingRoutes(app,{db,list,get,getSettings,audit,csrf,write,admin,transaction});
 const eventOperations=eventGuard=installEventOperationsRoutes(app,{db,list,get,put,audit,csrf,write,admin,transaction,validateReceiptPaymentLink:giftId=>{if(!receiptGuard)fail(503,'Receipt source protection is unavailable');receiptGuard.validateEventPaymentLink(giftId);peerFundraisingGuard?.validateEventPaymentLink(giftId);}});
 for(const route of ['/api/identity/merge/preview','/api/identity/merge'])app.post(route,csrf,admin,(req,res,next)=>{if(typeof req.body?.sourceId==='string'&&eventOperations.hasConstituentReferences(req.body.sourceId))return res.status(409).json({error:'This source identity has retained event, ticket, sponsorship or auction history. Historical consolidation requires a reviewed alias workflow.'});next();});
 receiptGuard=installReceiptRoutes(app,{db,list,get,getSettings,audit,csrf,write,admin,transaction});
 const financialCorrections=installFinancialCorrections(app,{db,get,audit});
 taskOwnership=installTaskOwnership(app,{db,get,audit,fail});
 peerFundraisingGuard=installPeerFundraisingRoutes(app,{db,get,audit,csrf,write,admin,transaction,isTenantActive,validateGiftSource:gift=>{const input=Object.fromEntries(Object.keys(schemas.gifts.shape).filter(key=>Object.hasOwn(gift,key)).map(key=>[key,gift[key]]));const parsed=validate('gifts',input,gift.id);if(JSON.stringify(parsed)!==JSON.stringify(Object.fromEntries(Object.keys(parsed).map(key=>[key,gift[key]]))))fail(503,'Native gift source does not match validated recorded fields');},recheckAccess:req=>{const session=db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(req.session?.token_hash),user=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id),time=Date.now();if(!session||session.user_id!==req.user.id||session.expires<time||session.last_seen<time-30*60*1000||!user?.active||!['admin','staff','viewer'].includes(user.role)||user.role!==req.user.role||session.account_binding!==mfaAccountBinding(user))return false;const factor=mfa.status(user);return factor.enabled?factor.available&&session.mfa_verified===1:session.mfa_verified!==1&&!(production&&user.role==='admin');}});app.locals.peerFundraising=peerFundraisingGuard;
 for(const route of ['/api/identity/merge/preview','/api/identity/merge'])app.post(route,csrf,admin,(req,res,next)=>{if(typeof req.body?.sourceId==='string'&&peerFundraisingGuard.hasConstituentReferences(req.body.sourceId))return res.status(409).json({error:'This source identity has retained peer fundraising history. Historical consolidation requires a reviewed alias workflow'});next();});
 installIdentityRoutes(app,{db,list,get,put,validate,audit,csrf,admin,transaction,collections,hasProtectedConstituentHistory:id=>peerFundraisingGuard.hasConstituentReferences(id)||hostedGivingService?.hasProtectedConstituentHistory(id)});
 const reminders=installTaskReminderRoutes(app,{db,get,audit,csrf,write,transaction,isTenantActive,clock:reminderClock,worker:reminderWorker,recheckAccess:req=>{const session=db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(req.session.token_hash);const user=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id);const time=Date.now();if(!session||session.user_id!==req.user.id||session.expires<time||session.last_seen<time-30*60*1000||!user?.active||!['admin','staff'].includes(user.role)||session.account_binding!==mfaAccountBinding(user))return false;const factor=mfa.status(user);return factor.enabled?factor.available&&session.mfa_verified===1:session.mfa_verified!==1&&!(production&&user.role==='admin');}});app.locals.runDueReminders=reminders.runDueReminders;app.locals.suppressTaskReminders=reminders.suppressPendingForTenant;
 const audienceService=installAudienceRoutes(app,{db,list,audit,csrf,write,transaction,isTenantActive,recheckAccess:req=>{const session=db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(req.session.token_hash);const user=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id);const time=Date.now();if(!session||session.user_id!==req.user.id||session.expires<time||session.last_seen<time-30*60*1000||!user?.active||!['admin','staff','viewer'].includes(user.role)||session.account_binding!==mfaAccountBinding(user))return false;const factor=mfa.status(user);return factor.enabled?factor.available&&session.mfa_verified===1:session.mfa_verified!==1&&!(production&&user.role==='admin');}});
 const correspondenceService=installCommunicationsRoutes(app,{db,list,get,getSettings,audit,csrf,write,transaction,audiences:audienceService});
 const communicationWorkflowService=installCommunicationWorkflowRoutes(app,{db,get,audiences:audienceService,communications:correspondenceService,create,audit,csrf,write,admin,transaction,isTenantActive,clock:workflowClock,worker:workflowWorker,ownerAllowed:user=>{const factor=mfa.status(user);return factor.enabled?factor.available:!(production&&user.role==='admin');},recheckAccess:req=>{const session=db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(req.session.token_hash);const user=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id);const time=Date.now();if(!session||session.user_id!==req.user.id||session.expires<time||session.last_seen<time-30*60*1000||!user?.active||!['admin','staff','viewer'].includes(user.role)||session.account_binding!==mfaAccountBinding(user))return false;const factor=mfa.status(user);return factor.enabled?factor.available&&session.mfa_verified===1:session.mfa_verified!==1&&!(production&&user.role==='admin');}});app.locals.runCommunicationWorkflows=communicationWorkflowService.runCommunicationWorkflows;app.locals.suppressCommunicationWorkflows=communicationWorkflowService.suppressPendingForTenant;
 const documentService=installDocumentRoutes(app,{db,list,get,audit,csrf,write,admin,transaction,collections,objectStorage:documentStorage,tenantId:documentTenantId,isTenantActive,scanDocument:documentScanner});app.locals.documentService=documentService;
 // A dedicated legacy SQLite instance retains the registered legacy workspace identity.
 // External object storage always requires its explicit tenant identity.
 const documentMigrationTenantId=documentTenantId||(!documentStorage?'00000000-0000-4000-8000-000000000001':null);
 installDocumentMigrationRoutes(app,{db,documentService,audit,csrf,admin,transaction,tenantId:documentMigrationTenantId,isTenantActive,recheckAccess:req=>{const session=db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(req.session?.token_hash);const user=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id);const time=Date.now();if(!session||session.user_id!==req.user.id||session.expires<time||session.last_seen<time-30*60*1000||!user?.active||user.role!=='admin'||session.account_binding!==mfaAccountBinding(user))return false;const factor=mfa.status(user);return factor.enabled?factor.available&&session.mfa_verified===1:session.mfa_verified!==1&&!(production&&user.role==='admin');}});
 grantGuard=installGrantOperationsRoutes(app,{db,list,get,audit,csrf,write,admin,transaction,documentService});
 hostedGivingService=createHostedGivingService({db,get,create,audit,transaction,tenantId,config:hostedGiving,clock:hostedGivingClock,isTenantActive,validateGiftSource:gift=>{const input=Object.fromEntries(Object.keys(schemas.gifts.shape).filter(key=>Object.hasOwn(gift,key)).map(key=>[key,gift[key]]));validate('gifts',input,gift.id);},recheckAccess:req=>{const session=db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(req.session?.token_hash),u=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id),time=Date.now();if(!session||session.user_id!==req.user.id||session.expires<time||session.last_seen<time-30*60*1000||!u?.active||u.role!=='admin'||session.account_binding!==mfaAccountBinding(u))return false;const factor=mfa.status(u);return factor.enabled?factor.available&&session.mfa_verified===1:session.mfa_verified!==1&&!(production&&u.role==='admin');}});app.locals.hostedGiving=hostedGivingService;installHostedGivingRoutes(app,hostedGivingService,{csrf,admin});
 const reporting=installReportingRoutes(app,{db,list,get,audit,csrf,write,transaction,documentMigrationTenantId,communicationWorkflows:communicationWorkflowService,peerFundraising:peerFundraisingGuard,hostedGiving:hostedGivingService,collections:collections.filter(c=>c!=='evaluations'||acceptanceEnabled)});
 installConstituentTimelineRoutes(app,{db,list:(collection,req)=>list(collection),get:(collection,id,req)=>get(collection,id),getGrantMilestones:user=>grantGuard.getQueueMilestones(user)});
 installMigrationRoutes(app,{db,list,get,create,put,validate,audit,csrf,admin,transaction,collections,schoolYear});
 const scheduling=installReportScheduleRoutes(app,{db,...reporting,csrf,write,audit,isTenantActive});app.locals.runDueReports=scheduling.runDueReports;const closeWorkspace=app.locals.close;app.locals.close=()=>{scheduling.close();reminders.close();communicationWorkflowService.close();closeWorkspace();};
 installAiRoutes(app,{list,get,audit,csrf,write,admin,demoAccess,getGrantMilestones:req=>grantGuard.getQueueMilestones(req.user),getFundraisingNextActions:req=>fundraisingGuard.getQueueNextActions(req.user),aiPolicy:aiPolicy||{enabled:!production,dataMode:demoAccess?'synthetic':'restricted'},recheckAccess:req=>{const session=db.prepare('SELECT * FROM sessions WHERE token_hash=?').get(req.session.token_hash);const user=db.prepare('SELECT * FROM users WHERE id=?').get(req.user.id);const time=Date.now();if(!session||session.user_id!==req.user.id||session.expires<time||session.last_seen<time-30*60*1000||!user?.active||!['admin','staff'].includes(user.role)||session.account_binding!==mfaAccountBinding(user))return false;const factor=mfa.status(user);return factor.enabled?factor.available&&session.mfa_verified===1:session.mfa_verified!==1&&!(production&&user.role==='admin');}});
 app.use('/api/records/evaluations',(req,res,next)=>acceptanceEnabled?next():res.status(404).json({error:'Endpoint not found'}));
 app.get('/api/workspace',(req,res)=>res.json({user:req.user,...(tenantInfo?{tenant:tenantInfo}:{}),csrfToken:req.session.csrf,taskOwners:taskOwnership.users(),fundraisingNextActions:fundraisingGuard.getQueueNextActions(req.user),grantMilestones:grantGuard.getQueueMilestones(req.user),data:Object.fromEntries(collections.map(c=>[c,c==='evaluations'&&!acceptanceEnabled?[]:c==='tasks'?list(c).map(t=>({...t,ownerStatus:taskOwnership.owner(t).status})):c==='communications'?list(c).map(r=>{const origin=communicationWorkflowService.getDraftOrigin(r.id,req.user);return {...r,...(origin?{workflowOrigin:origin}:{})};}):c==='events'?list(c).map(e=>({...e,canonicalSeating:eventGuard.getRegistrationSeating(e.id)})):list(c)])),capabilities:{acceptanceEnabled,demoAccess},audit:req.user.role==='admin'?db.prepare('SELECT * FROM audit ORDER BY id DESC LIMIT 250').all().map(r=>({...r,details:JSON.parse(r.details)})):[],settings:getSettings()}));
 app.post('/api/records/:collection',csrf,(req,res,next)=>req.params.collection==='evaluations'?next():write(req,res,next),(req,res)=>res.status(201).json({record:transaction(()=>create(req.params.collection,req.body,req.user))}));
 app.patch('/api/records/:collection/:id',csrf,write,(req,res)=>{const record=transaction(()=>{const c=req.params.collection;if(c==='volunteerTime')fail(403,'Use the volunteer time correction endpoint');const r=get(c,req.params.id);const {version,...changes}=z.object({version:z.number().int().min(1)}).passthrough().parse(req.body);const assignmentReason=c==='tasks'?changes.assignmentReason:undefined;if(c==='tasks')delete changes.assignmentReason;const correctionReason=c==='gifts'?changes.correctionReason:undefined;if(c==='gifts')delete changes.correctionReason;versionCheck(r,version);if(c==='gifts'&&r.status==='Voided')fail(409,'Voided gifts cannot change');if(c==='volunteers'&&('hours'in changes||'clockIn'in changes))fail(400,'Use volunteer clock to change hours');const {id:i,version:v,createdAt,updatedAt,status,schoolYear:sy,schoolYearOverride,schoolYearAssignment,clockIn,registrations,acknowledgment,giftId,correspondence,...editable}=r; // retain editable status outside gifts
 if(c!=='gifts'&&status!==undefined)editable.status=status;
 const parsed=validate(c,{...editable,...changes},r.id,r);const next={...r,...parsed,...(c==='gifts'?{schoolYear:giftSchoolYear({...r,...parsed})}:{})};
 if(c==='gifts'){fundraisingGuard?.validateMutation(c,r,next);eventGuard?.validateMutation(c,r,next);tributeGuard?.validateMutation(c,r,next);receiptGuard?.validateMutation(c,r,next);const change=financialCorrections.reasonFor(r,next,correctionReason);const updated=updateSpecial(c,next,req.user,'update');financialCorrections.retain(r,updated,req.user,change);return updated;}
 if(c==='tasks'){const updated=updateSpecial(c,next,req.user,'update');taskOwnership.retain(r,updated,req.user,assignmentReason);return updated;}
 return updateSpecial(c,next,req.user,'update');});res.json({record});});
 app.delete('/api/records/:collection/:id',csrf,write,(req,res)=>{transaction(()=>{const c=req.params.collection;if(!collections.includes(c))fail(404,'Unknown collection');if(c==='gifts')fail(403,'Financial records must be voided');if(c==='volunteerTime')fail(403,'Volunteer time entries cannot be deleted');if(c==='shiftReservations')fail(403,'Cancel reservations to preserve roster history');const r=get(c,req.params.id);reminders.validateDeletion(c,r);communicationWorkflowService.validateDeletion(c,r);peerFundraisingGuard.validateDeletion(c,r);hostedGivingService?.validateDeletion(c,r);if(c==='tasks')taskOwnership.validateDeletion(r);versionCheck(r,z.object({version:z.number().int().min(1)}).parse(req.body).version);financialCorrections.validateDeletion(c,r);for(const target of collections)for(const other of list(target)){if(target===c&&other.id===r.id)continue;const referenced=(c==='constituents'&&[other.constituentId,other.funderId,other.softCreditId,other.parentId,other.mergedInto,...(other.registrations||[]).map(x=>x.constituentId)].includes(r.id))||(c==='designations'&&(other.designationId===r.id||other.parentId===r.id||(other.allocations||[]).some(a=>a.designationId===r.id)))||(c==='campaigns'&&other.campaignId===r.id)||(c==='events'&&other.eventId===r.id)||(c==='grants'&&other.grantId===r.id)||(c==='pledges'&&other.pledgeId===r.id)||(c==='volunteerShifts'&&other.shiftId===r.id)||(c==='volunteers'&&other.volunteerId===r.id)||(c==='communications'&&other.acknowledgment?.communicationId===r.id);if(referenced)fail(409,'Record is referenced and cannot delete');}if(c==='events'&&r.registrations.length)fail(409,'Registered event cannot delete');fundraisingGuard?.validateMutation(c,r,null);eventGuard?.validateDeletion(c,r);eventHelperGuard?.validateDeletion(c,r);tributeGuard?.validateDeletion(c,r);grantGuard?.validateDeletion(c,r);db.prepare('DELETE FROM records WHERE collection=? AND id=?').run(c,r.id);audit(req.user,'delete',c,r.id);});res.json({ok:true});});
 app.post('/api/gifts/import',csrf,write,(req,res)=>{const {rows}=z.object({rows:z.array(z.unknown()).min(1).max(500)}).strict().parse(req.body);const imported=transaction(()=>rows.map(row=>create('gifts',row,req.user)));res.status(201).json({imported:imported.length});});
 app.post('/api/gifts/:id/school-year',csrf,write,(req,res)=>{
  const body=z.object({version:z.number().int().min(1),schoolYear:z.string().trim().min(1).max(9).nullable(),reason:z.string().trim().min(1).max(2000)}).strict().parse(req.body);
  const record=transaction(()=>{const gift=get('gifts',req.params.id);versionCheck(gift,body.version);if(gift.status==='Voided')fail(409,'Voided gifts cannot change');const override=parseAssignedYear(body.schoolYear),at=now();const next={...gift,schoolYearOverride:override,schoolYearAssignment:{schoolYear:override,reason:body.reason,at,actorId:req.user.id,fiscalStartMonth:getSettings().fiscalStartMonth},version:gift.version+1,updatedAt:at};next.schoolYear=giftSchoolYear(next);put('gifts',next);audit(req.user,override===null?'reset_school_year':'reassign_school_year','gifts',gift.id,{previousSchoolYear:gift.schoolYear||giftSchoolYear(gift),previousOverride:gift.schoolYearOverride??null,schoolYear:next.schoolYear,override,reason:body.reason,fiscalStartMonth:getSettings().fiscalStartMonth});return next;});
  res.json({record});
 });
 app.post('/api/gifts/:id/void',csrf,write,(req,res)=>{const body=z.object({version:z.number().int().min(1),reason:z.string().trim().min(1).max(2000)}).strict().parse(req.body);const record=transaction(()=>{const r=get('gifts',req.params.id);versionCheck(r,body.version);if(r.status==='Voided')fail(409,'Already voided');return updateSpecial('gifts',{...r,status:'Voided',voidReason:body.reason,voidedAt:now()},req.user,'void');});res.json({record});});
 app.post('/api/volunteers/:id/clock',csrf,write,(req,res)=>{const body=z.object({action:z.enum(['in','out']),version:z.number().int().min(1)}).strict().parse(req.body);const record=transaction(()=>{const r=get('volunteers',req.params.id);versionCheck(r,body.version);if(body.action==='in'){if(list('volunteers').some(v=>v.constituentId===r.constituentId&&v.clockIn))fail(409,'This constituent is already clocked in');r.clockIn=now();}else{if(!r.clockIn)fail(409,'Not clocked in');const endAt=now();if(Date.parse(endAt)<Date.parse(r.clockIn))fail(409,'Clock interval ends before it starts');const hours=Math.round((Date.parse(endAt)-Date.parse(r.clockIn))/3600000*1000000)/1000000;addTime(r,{startAt:r.clockIn,endAt,hours,source:'Clock',notes:''},req.user);r.hours=Math.round(list('volunteerTime').filter(t=>t.volunteerId===r.id).reduce((total,t)=>total+t.hours,0)*1000000)/1000000;r.clockIn=null;}return updateSpecial('volunteers',r,req.user,'clock_'+body.action);});res.json({record});});
 app.post('/api/volunteer-time/:id/correct',csrf,write,(req,res)=>{const body=z.object({version:z.number().int().min(1),hours:z.number().min(0).max(1e6),reason:z.string().trim().min(1).max(2000)}).strict().parse(req.body);const result=transaction(()=>{const record=get('volunteerTime',req.params.id);versionCheck(record,body.version);const volunteer=get('volunteers',record.volunteerId),previousHours=record.hours;record.originalHours=record.originalHours??previousHours;record.hours=body.hours;record.correctionReason=body.reason;record.correctedAt=now();record.version++;record.updatedAt=now();put('volunteerTime',record);audit(req.user,'correct_time','volunteerTime',record.id,{previousHours,hours:body.hours,originalHours:record.originalHours,reason:body.reason});volunteer.hours=Math.round(list('volunteerTime').filter(t=>t.volunteerId===volunteer.id).reduce((total,t)=>total+t.hours,0)*1000000)/1000000;updateSpecial('volunteers',volunteer,req.user,'reconcile_time');return {record,volunteer};});res.json(result);});
 app.post('/api/gifts/:id/acknowledge',csrf,write,(req,res)=>{const body=z.object({version:z.number().int().min(1),date,channel:z.enum(['Email','Phone','Meeting','Post']),notes:str,correspondence:z.object({preparationId:id,preparationDigest:z.string().length(64),confirmed:z.literal(true),reason:z.string().trim().min(1).max(2000)}).strict().optional()}).strict().parse(req.body);const result=transaction(()=>{const gift=get('gifts',req.params.id);versionCheck(gift,body.version);if(body.date>now().slice(0,10))fail(400,'Completed acknowledgment date cannot be in the future');if(gift.status==='Voided'||gift.type==='Fee payment')fail(409,'This gift cannot be acknowledged');if(gift.acknowledgment)fail(409,'Gift already acknowledged');if(body.date<gift.date)fail(400,'Completed acknowledgment cannot precede the gift date');const source=correspondenceService.validateAcknowledgmentSource(req.user,gift,body);const donor=get('constituents',gift.constituentId);if(donor.preference==='Do not contact')fail(403,'Do not contact: acknowledgment blocked');const communication=create('communications',{constituentId:donor.id,subject:'Manual gift acknowledgment',channel:body.channel,status:'Logged',date:body.date,body:body.notes,notes:'Manual completed action recorded; no message sent or receipt issued.'},req.user);communication.giftId=gift.id;if(source)communication.correspondence=source;put('communications',communication);gift.acknowledgment={date:body.date,channel:body.channel,notes:body.notes,communicationId:communication.id,at:now(),...(source?{correspondence:source}:{})};updateSpecial('gifts',gift,req.user,'acknowledge');if(source)correspondenceService.retainAcknowledgmentFulfillment(req.user,source,{gift,communication,date:body.date,channel:body.channel,reason:body.correspondence.reason});return {record:gift,communication};});res.json(result);});
 app.post('/api/events/:id/register',csrf,write,(req,res)=>{const body=z.object({constituentId:id,seating:short}).strict().parse(req.body);const record=transaction(()=>{const r=get('events',req.params.id);if(!exists('constituents',body.constituentId))fail(400,'Invalid constituent reference');eventGuard.validateRegistrationSeating(r.id,body.constituentId,body.seating);if(r.registrations.some(x=>x.constituentId===body.constituentId))fail(409,'Already registered');if(r.registrations.length>=r.capacity)fail(409,'Event at capacity');r.registrations.push({...body,checkedIn:false,registeredAt:now()});return updateSpecial('events',r,req.user,'register');});res.json({record});});
 app.post('/api/events/:id/checkin',csrf,write,(req,res)=>{const body=z.object({constituentId:id}).strict().parse(req.body);const record=transaction(()=>{const r=get('events',req.params.id),entry=r.registrations.find(x=>x.constituentId===body.constituentId);if(!entry)fail(400,'Registration required');if(entry.checkedIn)fail(409,'Already checked in');entry.checkedIn=true;return updateSpecial('events',r,req.user,'checkin');});res.json({record});});
 app.delete('/api/events/:id/register/:constituentId',csrf,write,(req,res)=>{const record=transaction(()=>{const r=get('events',req.params.id);if(!r.registrations.some(x=>x.constituentId===req.params.constituentId))fail(404,'Registration not found');r.registrations=r.registrations.filter(x=>x.constituentId!==req.params.constituentId);return updateSpecial('events',r,req.user,'cancel_registration');});res.json({record});});
 app.get('/api/readiness',admin,(req,res)=>{
  const data=Object.fromEntries(collections.map(c=>[c,list(c)]));
  const issues=[];
  for(const c of collections)for(const r of data[c]){
   if(!schemas[c])continue;
   const input=Object.fromEntries(Object.keys(schemas[c].shape).filter(k=>r[k]!==undefined).map(k=>[k,r[k]]));
   try{if(c==='gifts'&&r.status==='Voided'){for(const [target,key]of [['pledges','pledgeId'],['grants','grantId']])if(!exists(target,r[key]))fail(400,'Invalid '+target+' reference');input.pledgeId=null;input.grantId=null;}validate(c,input,r.id,r);}catch(e){issues.push({collection:c,recordId:r.id,label:r.name||r.title||r.subject||data.constituents.find(p=>p.id===r.constituentId)?.name||'Record',problem:e instanceof z.ZodError?'Record fields need review':e.message});}
  }
  const ledgerIssues=[];
  for(const entry of data.volunteerTime){const volunteer=data.volunteers.find(v=>v.id===entry.volunteerId);const validDates=entry.source==='Historical'?entry.startAt===null&&entry.endAt===null:entry.source==='Clock'&&Number.isFinite(Date.parse(entry.startAt))&&Number.isFinite(Date.parse(entry.endAt))&&Date.parse(entry.endAt)>=Date.parse(entry.startAt);
   if(!volunteer||entry.constituentId!==volunteer.constituentId||!exists('constituents',entry.constituentId)||!exists('events',entry.eventId)||!Number.isFinite(entry.hours)||entry.hours<0||!validDates)ledgerIssues.push({collection:'volunteerTime',recordId:entry.id,label:'Volunteer time entry',problem:'Review time fields, dated/historical distinction and original references'});
  }
  for(const volunteer of data.volunteers){const hours=Math.round(data.volunteerTime.filter(t=>t.volunteerId===volunteer.id).reduce((sum,t)=>sum+t.hours,0)*1e6)/1e6;if(hours!==volunteer.hours)ledgerIssues.push({collection:'volunteers',recordId:volunteer.id,label:data.constituents.find(p=>p.id===volunteer.constituentId)?.name||'Volunteer',problem:'Recorded hours do not reconcile to the time ledger'});}
  const checks=[{key:'time-ledger',label:'Volunteer time history and hour reconciliation',issues:ledgerIssues},{key:'records',label:'Record fields and connected references',issues},
   {key:'clocks',label:'One active volunteer clock per person',issues:data.volunteers.filter(v=>v.clockIn&&data.volunteers.some(o=>o.id!==v.id&&o.constituentId===v.constituentId&&o.clockIn)).map(v=>({collection:'volunteers',recordId:v.id,label:data.constituents.find(c=>c.id===v.constituentId)?.name||'Volunteer',problem:'Multiple active clocks for this person'}))}];
  res.json({checkedAt:now(),scope:'Local records only; no external provider or institutional approval checked',recordCount:Object.values(data).reduce((n,rows)=>n+rows.length,0),checks:checks.map(c=>({...c,status:c.issues.length?'Needs review':'Passed'}))});
 });
 app.get('/api/users',admin,(req,res)=>res.json({users:db.prepare('SELECT id,name,email,role,active,version FROM users ORDER BY name').all().map(accountView)}));
 app.post('/api/users',csrf,admin,(req,res)=>{const p=z.object({name,email:z.email().max(254).transform(x=>x.toLowerCase()),password:z.string().min(12).max(200),role:z.enum(['admin','staff','viewer','event-helper'])}).strict().parse(req.body);const user=transaction(()=>{if(db.prepare('SELECT 1 FROM users WHERE email=?').get(p.email))fail(409,'Email already exists');const u={id:randomUUID(),name:p.name,email:p.email,role:p.role,active:1,version:1};db.prepare('INSERT INTO users(id,name,email,role,password_hash) VALUES(?,?,?,?,?)').run(u.id,u.name,u.email,u.role,passwordHash(p.password));audit(req.user,'create_user','users',u.id,{role:u.role,active:true});return accountView(u);});res.status(201).json({user});});
 app.patch('/api/users/:id',csrf,admin,(req,res)=>{
  const body=z.object({version:z.number().int().min(1),role:z.enum(['admin','staff','viewer','event-helper']),active:z.boolean()}).strict().parse(req.body);
  const result=transaction(()=>{
   const previous=db.prepare('SELECT * FROM users WHERE id=?').get(req.params.id);
   if(!previous)fail(404,'Account not found');
   versionCheck(previous,body.version);
   if(previous.role===body.role&&Boolean(previous.active)===body.active)return {user:accountView(previous),sessionsRevoked:0};
   if(previous.active&&previous.role==='admin'&&(!body.active||body.role!=='admin')){
    const others=db.prepare("SELECT COUNT(*) AS count FROM users WHERE active=1 AND role='admin' AND id<>?").get(previous.id).count;
    if(!others)fail(409,'Keep at least one active administrator. Add another administrator before changing this account.');
   }
   db.prepare('UPDATE users SET role=?,active=?,version=version+1 WHERE id=?').run(body.role,Number(body.active),previous.id);
   const sessionsRevoked=db.prepare('DELETE FROM sessions WHERE user_id=?').run(previous.id).changes;
   db.prepare('DELETE FROM mfa_challenges WHERE user_id=?').run(previous.id);
   eventHelperGuard.retireAccountAssignments(req,previous,previous.version+1);
   audit(req.user,'change_access','users',previous.id,{previousRole:previous.role,role:body.role,previousActive:Boolean(previous.active),active:body.active,sessionsRevoked});
   return {user:accountView(db.prepare('SELECT * FROM users WHERE id=?').get(previous.id)),sessionsRevoked};
  });
  res.json(result);
 });
 app.patch('/api/settings',csrf,admin,(req,res)=>{const p=z.object({organizationName:name,fiscalStartMonth:z.number().int().min(1).max(12)}).strict().parse(req.body);transaction(()=>{db.prepare('UPDATE settings SET data=? WHERE id=1').run(JSON.stringify(p));for(const gift of list('gifts')){const override=gift.schoolYearOverride?formatAssignedYear(Number(gift.schoolYearOverride.slice(0,4)),p.fiscalStartMonth):null;const next={...gift,...(gift.schoolYearOverride?{schoolYearOverride:override}:{}),schoolYear:giftSchoolYear({...gift,schoolYearOverride:override}),version:gift.version+1,updatedAt:now()};put('gifts',next);if(gift.schoolYearOverride&&(gift.schoolYearOverride!==override||gift.schoolYear!==next.schoolYear))audit(req.user,'reformat_school_year','gifts',gift.id,{previousSchoolYear:gift.schoolYear,previousOverride:gift.schoolYearOverride,schoolYear:next.schoolYear,override,fiscalStartMonth:p.fiscalStartMonth});}audit(req.user,'update_settings',null,null);});res.json({settings:p});});
 app.get('/api/backup',admin,(req,res)=>{res.set('Cache-Control','no-store');res.set('Content-Disposition','attachment; filename="wimblo-workspace-snapshot.json"');res.json({exportedAt:now(),settings:getSettings(),data:Object.fromEntries(collections.map(c=>[c,list(c)])),users:db.prepare('SELECT id,name,email,role FROM users').all(),audit:db.prepare('SELECT * FROM audit ORDER BY id').all()});});
 app.use('/api',(req,res)=>res.status(404).json({error:'Endpoint not found'}));
 app.use((err,req,res,next)=>{if(err instanceof z.ZodError)return res.status(400).json({error:'Invalid input',fields:err.issues.map(x=>({path:x.path,message:x.message}))});if(err.status)return res.status(err.status).json({error:err.status===413?'Request too large':err.message});if(err.type==='entity.parse.failed')return res.status(400).json({error:'Invalid JSON'});console.error('API internal error',err.message);res.status(500).json({error:'Internal server error'});});
 return app;
}
