import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';

const fail=(status,message)=>{const e=new Error(message);e.status=status;throw e;};
const version=z.number().int().min(1),id=z.uuid(),channel=z.enum(['Print','Email draft']);
const types=['Individual','Business','Foundation','Alumni','Employee','Staff','Community partner'];
const preferences=['Email','Phone','Post','Do not contact'];
const distinct=(schema,max)=>z.array(schema).max(max).refine(values=>new Set(values).size===values.length,'Choose each value only once');
const filters=z.object({segmentTokens:distinct(z.string().trim().min(1).max(300).refine(value=>!value.includes(','),'Use one comma-free segment token'),25),segmentMatch:z.enum(['Any','All']),types:distinct(z.enum(types),7),preferences:distinct(z.enum(preferences),4)}).strict();
const definitionSchema=z.object({name:z.string().trim().min(1).max(250),filters}).strict();
export const audienceReferenceSchema=z.object({id,version,sourceDigest:z.string().regex(/^[a-f0-9]{64}$/)}).strict();
const canonical=value=>Array.isArray(value)?'['+value.map(canonical).join(',')+']':value&&typeof value==='object'?'{'+Object.keys(value).sort().map(key=>JSON.stringify(key)+':'+canonical(value[key])).join(',')+'}':JSON.stringify(value);
const hash=value=>createHash('sha256').update(canonical(value)).digest('hex');
const reasons=['Merged identity','Outside saved criteria','Do not contact','Email preference required','Invalid primary email'];
const matches=(p,f)=>{const tokens=new Set(String(p.segments||'').split(',').map(value=>value.trim()).filter(Boolean));return (!f.types.length||f.types.includes(p.type))&&(!f.preferences.length||f.preferences.includes(p.preference))&&(!f.segmentTokens.length||(f.segmentMatch==='All'?f.segmentTokens.every(token=>tokens.has(token)):f.segmentTokens.some(token=>tokens.has(token))));};
const recipientView=p=>({id:p.id,name:p.name,version:p.version,preference:p.preference});

// Saved criteria construct candidates only. Existing contact preferences still
// control preparation; tags and secondary contacts never establish permission.
export function installAudienceRoutes(app,{db,list,audit,csrf,write,transaction,recheckAccess=()=>false,isTenantActive=()=>true}){
 db.exec(`CREATE TABLE IF NOT EXISTS audience_definitions(id TEXT PRIMARY KEY,version INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN ('Active','Retired')),definition TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS audience_revisions(audience_id TEXT NOT NULL REFERENCES audience_definitions(id),version INTEGER NOT NULL,status TEXT NOT NULL,definition TEXT NOT NULL,reason TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL,PRIMARY KEY(audience_id,version));
 CREATE TRIGGER IF NOT EXISTS audience_no_delete BEFORE DELETE ON audience_definitions BEGIN SELECT RAISE(ABORT,'Saved audience history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS audience_revision_no_update BEFORE UPDATE ON audience_revisions BEGIN SELECT RAISE(ABORT,'Saved audience history is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS audience_revision_no_delete BEFORE DELETE ON audience_revisions BEGIN SELECT RAISE(ABORT,'Saved audience history is retained'); END;`);
 const authorized=(req,res,next)=>{if(!req.user)return res.status(401).json({error:'Authentication required'});if(!['admin','staff','viewer'].includes(req.user.role))return res.status(403).json({error:'Your role cannot access saved audiences'});if(!isTenantActive())return res.status(403).json({error:'Workspace is suspended'});if(!recheckAccess(req))return res.status(401).json({error:'Account access changed. Sign in again'});next();};
 const action=fn=>(req,res,next)=>{try{fn(req,res);}catch(e){next(e);}};
 const live=req=>{if(!req?.user||!['admin','staff'].includes(req.user.role))fail(403,'Current staff access required');if(!isTenantActive())fail(403,'Workspace is suspended');if(!recheckAccess(req))fail(401,'Account access changed. Sign in again');};
 app.use('/api/audiences',authorized);
 const present=row=>({id:row.id,version:row.version,status:row.status,...JSON.parse(row.definition),createdAt:row.created_at,updatedAt:row.updated_at});
 function find(key){const row=db.prepare('SELECT * FROM audience_definitions WHERE id=?').get(key);if(!row)fail(404,'Saved audience not found');return present(row);}
 const definitionDigest=a=>hash({name:a.name,filters:a.filters,status:a.status});
 function currentPreview(key,expectedVersion,requestedChannel){if(!isTenantActive())fail(403,'Workspace is suspended');const a=find(key);if(a.version!==expectedVersion)fail(409,'Saved audience changed. Reload its current version');if(a.status!=='Active')fail(409,'This audience is retired. Create a new audience');const validated=definitionSchema.parse({name:a.name,filters:a.filters}),profiles=list('constituents').sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0),eligible=[],reasonCounts=Object.fromEntries(reasons.map(reason=>[reason,0]));let matchedCount=0;
  for(const p of profiles){let reason;if(p.mergedInto)reason=reasons[0];else if(!matches(p,validated.filters))reason=reasons[1];else{matchedCount++;if(p.preference==='Do not contact')reason=reasons[2];else if(requestedChannel==='Email draft'&&p.preference!=='Email')reason=reasons[3];else if(requestedChannel==='Email draft'&&!z.email().safeParse(p.email).success)reason=reasons[4];}if(reason)reasonCounts[reason]++;else eligible.push(p);}
  const digest=definitionDigest(a),sourceDigest=hash({audience:{id:a.id,version:a.version,definitionDigest:digest},channel:requestedChannel,constituents:profiles.map(p=>({id:p.id,version:p.version,recordDigest:hash(p)}))});
  return {audience:{id:a.id,version:a.version,name:a.name,definitionDigest:digest},channel:requestedChannel,sourceDigest,totalCount:profiles.length,matchedCount,eligibleCount:eligible.length,excludedCount:profiles.length-eligible.length,reasonCounts,eligible};
 }
 function validateSelection(reference,requestedChannel,selectedIds,req){live(req);const r=audienceReferenceSchema.parse(reference);channel.parse(requestedChannel);const selected=distinct(z.string().min(1).max(100),100).min(1).parse(selectedIds),preview=currentPreview(r.id,r.version,requestedChannel);if(preview.sourceDigest!==r.sourceDigest)fail(409,'Audience source records changed. Refresh eligibility and explicitly review the selected recipients again');const eligible=new Set(preview.eligible.map(p=>p.id));if(selected.some(key=>!eligible.has(key)))fail(409,'Selected recipients are outside this audience or currently excluded. Refresh eligibility and review a new selection');return {...preview.audience,sourceDigest:preview.sourceDigest,channel:requestedChannel,selectedConstituentIds:[...selected]};}
 function retain(key,currentVersion,status,p,reason,actor,at){db.prepare('INSERT INTO audience_revisions VALUES(?,?,?,?,?,?,?)').run(key,currentVersion,status,JSON.stringify(p),reason,actor,at);}
 app.get('/api/audiences',action((req,res)=>{z.object({}).strict().parse(req.query);res.json({audiences:db.prepare("SELECT * FROM audience_definitions ORDER BY CASE status WHEN 'Active' THEN 0 ELSE 1 END,updated_at DESC,id LIMIT 200").all().map(present),limit:200});}));
 app.post('/api/audiences',csrf,write,action((req,res)=>{const p=definitionSchema.parse(req.body),result=transaction(()=>{live(req);if(db.prepare("SELECT COUNT(*) n FROM audience_definitions WHERE status='Active'").get().n>=200)fail(409,'This workspace has 200 active audiences. Retire an unused audience before creating another');const key=randomUUID(),at=new Date().toISOString();db.prepare('INSERT INTO audience_definitions VALUES(?,1,?,?,?,?)').run(key,'Active',JSON.stringify(p),at,at);retain(key,1,'Active',p,'',req.user.id,at);audit(req.user,'create_audience',null,key,{version:1,definitionDigest:hash({...p,status:'Active'}),delivery:'Not sent'});return find(key);});res.status(201).json({audience:result});}));
 app.get('/api/audiences/:id/preview',action((req,res)=>{const key=id.parse(req.params.id),q=z.object({version:z.coerce.number().int().min(1),channel,limit:z.coerce.number().int().min(1).max(100).optional(),after:id.optional()}).strict().parse(req.query),preview=currentPreview(key,q.version,q.channel),limit=q.limit||100,{eligible,...summary}=preview,after=eligible.filter(p=>!q.after||p.id>q.after),page=after.slice(0,limit);res.json({...summary,recipients:page.map(recipientView),nextCursor:after.length>limit?page.at(-1).id:null,limit});}));
 app.get('/api/audiences/:id',action((req,res)=>{id.parse(req.params.id);z.object({}).strict().parse(req.query);const a=find(req.params.id),rows=db.prepare('SELECT * FROM audience_revisions WHERE audience_id=? ORDER BY version DESC LIMIT 100').all(a.id),revisionCount=db.prepare('SELECT COUNT(*) n FROM audience_revisions WHERE audience_id=?').get(a.id).n;res.json({audience:a,revisions:rows.map(row=>({version:row.version,status:row.status,...JSON.parse(row.definition),reason:row.reason,actor:row.actor,at:row.at})),revisionCount,revisionLimit:100});}));
 app.patch('/api/audiences/:id',csrf,write,action((req,res)=>{id.parse(req.params.id);const {version:expectedVersion,status,reason,...body}=definitionSchema.extend({version,status:z.enum(['Active','Retired']),reason:z.string().trim().min(1).max(500).optional()}).strict().parse(req.body);if(status==='Retired'&&!reason)fail(400,'A retirement reason is required');if(status==='Active'&&reason!==undefined)fail(400,'A reason is supported only when retiring an audience');const p=definitionSchema.parse(body),result=transaction(()=>{live(req);const old=find(req.params.id);if(old.status==='Retired')fail(409,'This audience is retired. Create a new audience');if(old.version!==expectedVersion)fail(409,'Saved audience changed. Reload before saving');const at=new Date().toISOString();db.prepare('UPDATE audience_definitions SET version=version+1,status=?,definition=?,updated_at=? WHERE id=?').run(status,JSON.stringify(p),at,old.id);retain(old.id,old.version+1,status,p,reason||'',req.user.id,at);audit(req.user,status==='Retired'?'retire_audience':'update_audience',null,old.id,{version:old.version+1,previousDefinitionDigest:definitionDigest(old),definitionDigest:hash({...p,status}),...(reason?{reason}:{}),delivery:'Not sent'});return find(old.id);});res.json({audience:result});}));
 return {validateSelection,find};
}
