import {randomUUID,createHash} from 'node:crypto';
import {createS3DocumentStorage,APPROVED_STORAGE_REGIONS} from './objectStorage.js';
const MAX_ARCHIVE_BYTES=128*1024*1024;
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const fail=message=>{throw Object.assign(new Error(message),{status:503});};
const uuid=value=>{if(typeof value!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value))fail('Off-host recovery requires an explicit UUID.');return value.toLowerCase();};
export function createS3BackupStorage(config={}){
 const stores=Object.fromEntries(['backups','platform-backups'].map(purpose=>[purpose,createS3DocumentStorage({...config,provider:'s3',requireVersionId:true,maxBytes:MAX_ARCHIVE_BYTES,objectPurpose:purpose})]));
 function identity({tenantId,recoveryId}){if(Boolean(tenantId)===Boolean(recoveryId))fail('Recovery storage requires exactly one tenant or platform recovery identity.');const platform=Boolean(recoveryId);return {owner:uuid(platform?recoveryId:tenantId),platform,store:stores[platform?'platform-backups':'backups'],magic:Buffer.from(platform?'WIMBLO-PLATFORM-RECOVERY\n':'WIMBLO-BACKUP\n')};}
 async function putImmutable(input){const {owner,platform,store,magic}=identity(input),content=Buffer.from(input.bytes);if(!content.length||content.length>MAX_ARCHIVE_BYTES||hash(content)!==input.sha256||!content.subarray(0,magic.length).equals(magic))fail('Only bounded, checksum-verified Wimblo encrypted archives can use the recovery store.');const pending=store.stage({tenantId:owner,documentId:randomUUID(),revision:1,attemptId:randomUUID(),sha256:input.sha256,size:content.length}),reference=await store.put(pending,content,'application/octet-stream');return {key:reference.key,versionId:reference.version,sha256:input.sha256,size:content.length,...(platform?{recoveryId:owner}:{tenantId:owner})};}
 async function readVersion(input){const {owner,store,magic}=identity(input),maxBytes=input.maxBytes??MAX_ARCHIVE_BYTES;if(!Number.isSafeInteger(maxBytes)||maxBytes<1||maxBytes>MAX_ARCHIVE_BYTES)fail('Recovery archive byte limit is invalid.');const reference=await store.describeExact({tenantId:owner,key:input.key,version:input.versionId});if(reference.size>maxBytes)fail('Exact recovery archive exceeds its allowed byte limit.');const bytes=await store.get(reference);if(!bytes.subarray(0,magic.length).equals(magic))fail('Exact recovery object is not the expected Wimblo encrypted archive.');return bytes;}
 return {offHost:true,private:true,putImmutable,readVersion,verifyReadiness:stores.backups.verifyReadiness};
}
export function createBackupStorageFromEnv(env=process.env){if(!env.BACKUP_STORAGE_BUCKET)return null;const production=env.NODE_ENV==='production';if(production&&(env.BACKUP_AWS_ENDPOINT_URL||env.AWS_ENDPOINT_URL))fail('Production recovery cannot use a custom AWS endpoint.');const accessKeyId=env.BACKUP_AWS_ACCESS_KEY_ID||env.AWS_ACCESS_KEY_ID,secretAccessKey=env.BACKUP_AWS_SECRET_ACCESS_KEY||env.AWS_SECRET_ACCESS_KEY,sessionToken=env.BACKUP_AWS_SESSION_TOKEN||env.AWS_SESSION_TOKEN;if(!accessKeyId||!secretAccessKey)fail('Off-host recovery needs server-only storage credentials.');return createS3BackupStorage({... (production?{approvedRegions:APPROVED_STORAGE_REGIONS,nativeAwsOnly:true}:{}),bucket:env.BACKUP_STORAGE_BUCKET,namespace:env.BACKUP_STORAGE_NAMESPACE||env.DOCUMENT_STORAGE_NAMESPACE,region:env.BACKUP_AWS_REGION||env.AWS_REGION,endpoint:env.BACKUP_AWS_ENDPOINT_URL_S3||env.AWS_ENDPOINT_URL_S3,privateConfirmed:env.BACKUP_STORAGE_PRIVATE_CONFIRMED==='true',credentials:{accessKeyId,secretAccessKey,...(sessionToken?{sessionToken}:{})}});}
