import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
import {mfaAccountBinding} from './mfa.js';

const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const canonical=v=>v&&typeof v==='object'?Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const hash=v=>createHash('sha256').update(canonical(v)).digest('hex');
const iso=time=>new Date(time).toISOString(),id=z.uuid(),version=z.number().int().positive();
const armSchema=z.object({name:z.string().trim().min(1).max(250),audienceId:id,audienceVersion:version,sourceDigest:z.string().regex(/^[a-f0-9]{64}$/),templateId:id,templateVersion:version,channel:z.enum(['Print','Email draft']),confirmed:z.literal(true)}).strict();
const limits={activeRules:20,profileWatermarksPerRule:1000,membershipEpisodesPerRule:1000,draftAttemptsPerCycle:40,retries:5,retrySeconds:60,outcomePage:100};
const delivery='Not sent';

// Explicit prospective local draft production only. A background principal is
// bound to the reviewed owner's current account/MFA policy, not a browser cookie.
export function installCommunicationWorkflowRoutes(app,{db,get,audiences,communications,create,audit,csrf,write,admin,transaction,isTenantActive=()=>true,recheckAccess=()=>false,ownerAllowed=()=>false,clock=Date.now,worker=true}){
 if(!audiences?.previewForWorkflow||!communications?.prepareWorkflowMessage||!communications?.getWorkflowTemplate||typeof create!=='function')throw new Error('Communication workflows require the validated audience, Messaging renderer and native create services');
 db.exec(`CREATE TABLE IF NOT EXISTS automation_recovery_markers(id TEXT PRIMARY KEY,at TEXT NOT NULL,archive_sha256 TEXT NOT NULL,source_sha256 TEXT NOT NULL);
 CREATE TRIGGER IF NOT EXISTS automation_recovery_marker_no_update BEFORE UPDATE ON automation_recovery_markers BEGIN SELECT RAISE(ABORT,'Recovery markers are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS automation_recovery_marker_no_delete BEFORE DELETE ON automation_recovery_markers BEGIN SELECT RAISE(ABORT,'Recovery markers are retained'); END;
 CREATE TABLE IF NOT EXISTS communication_workflows(id TEXT PRIMARY KEY,name TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Active','Retired','Suppressed')),version INTEGER NOT NULL,owner_id TEXT NOT NULL REFERENCES users(id),owner_version INTEGER NOT NULL,owner_binding TEXT NOT NULL,security_binding TEXT NOT NULL,recovery_marker TEXT NOT NULL,audience_id TEXT NOT NULL REFERENCES audience_definitions(id),audience_version INTEGER NOT NULL,audience_digest TEXT NOT NULL,template_id TEXT NOT NULL REFERENCES correspondence_templates(id),template_version INTEGER NOT NULL,template_digest TEXT NOT NULL,channel TEXT NOT NULL,baseline_count INTEGER NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,next_attempt TEXT NOT NULL,failure_count INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS communication_workflow_memberships(workflow_id TEXT NOT NULL REFERENCES communication_workflows(id),constituent_id TEXT NOT NULL,eligible INTEGER NOT NULL CHECK(eligible IN (0,1)),episode INTEGER NOT NULL,record_version INTEGER,record_digest TEXT,last_seen_at TEXT NOT NULL,PRIMARY KEY(workflow_id,constituent_id));
 CREATE TABLE IF NOT EXISTS communication_workflow_entries(id TEXT PRIMARY KEY,workflow_id TEXT NOT NULL REFERENCES communication_workflows(id),constituent_id TEXT NOT NULL,episode INTEGER NOT NULL,source_version INTEGER NOT NULL,source_digest TEXT NOT NULL,audience_source_digest TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Pending','Drafted','Suppressed')),version INTEGER NOT NULL,attempt_count INTEGER NOT NULL DEFAULT 0,next_attempt TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(workflow_id,constituent_id,episode));
 CREATE INDEX IF NOT EXISTS communication_workflow_due ON communication_workflow_entries(status,next_attempt,id);
 CREATE TABLE IF NOT EXISTS communication_workflow_executions(id TEXT PRIMARY KEY,entry_id TEXT NOT NULL UNIQUE REFERENCES communication_workflow_entries(id),workflow_id TEXT NOT NULL REFERENCES communication_workflows(id),constituent_id TEXT NOT NULL,episode INTEGER NOT NULL,source_version INTEGER NOT NULL,audience_version INTEGER NOT NULL,template_version INTEGER NOT NULL,communication_id TEXT NOT NULL UNIQUE,communication_version INTEGER NOT NULL,communication_digest TEXT NOT NULL,wording_digest TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL,delivery TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS communication_workflow_outcomes(id TEXT PRIMARY KEY,workflow_id TEXT NOT NULL REFERENCES communication_workflows(id),workflow_version INTEGER NOT NULL,entry_id TEXT REFERENCES communication_workflow_entries(id),entry_version INTEGER,status TEXT NOT NULL,reason TEXT NOT NULL,at TEXT NOT NULL,retry_at TEXT);
 CREATE TRIGGER IF NOT EXISTS communication_workflow_no_delete BEFORE DELETE ON communication_workflows BEGIN SELECT RAISE(ABORT,'Workflow history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS communication_workflow_definition_no_update BEFORE UPDATE ON communication_workflows WHEN NEW.id IS NOT OLD.id OR NEW.name IS NOT OLD.name OR NEW.owner_id IS NOT OLD.owner_id OR NEW.owner_version IS NOT OLD.owner_version OR NEW.owner_binding IS NOT OLD.owner_binding OR NEW.security_binding IS NOT OLD.security_binding OR NEW.recovery_marker IS NOT OLD.recovery_marker OR NEW.audience_id IS NOT OLD.audience_id OR NEW.audience_version IS NOT OLD.audience_version OR NEW.audience_digest IS NOT OLD.audience_digest OR NEW.template_id IS NOT OLD.template_id OR NEW.template_version IS NOT OLD.template_version OR NEW.template_digest IS NOT OLD.template_digest OR NEW.channel IS NOT OLD.channel OR NEW.baseline_count IS NOT OLD.baseline_count OR NEW.created_at IS NOT OLD.created_at BEGIN SELECT RAISE(ABORT,'Reviewed activation definitions are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS communication_workflow_closed_no_update BEFORE UPDATE ON communication_workflows WHEN OLD.status!='Active' BEGIN SELECT RAISE(ABORT,'Closed activations cannot resume or change'); END;
 CREATE TRIGGER IF NOT EXISTS communication_workflow_member_no_delete BEFORE DELETE ON communication_workflow_memberships BEGIN SELECT RAISE(ABORT,'Membership watermarks are retained'); END;
 CREATE TRIGGER IF NOT EXISTS communication_workflow_entry_no_delete BEFORE DELETE ON communication_workflow_entries BEGIN SELECT RAISE(ABORT,'Membership episodes are retained'); END;
 CREATE TRIGGER IF NOT EXISTS communication_workflow_entry_closed_no_update BEFORE UPDATE ON communication_workflow_entries WHEN OLD.status!='Pending' BEGIN SELECT RAISE(ABORT,'Closed membership episodes cannot resume or change'); END;
 CREATE TRIGGER IF NOT EXISTS communication_workflow_execution_no_update BEFORE UPDATE ON communication_workflow_executions BEGIN SELECT RAISE(ABORT,'Draft execution history is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS communication_workflow_execution_no_delete BEFORE DELETE ON communication_workflow_executions BEGIN SELECT RAISE(ABORT,'Draft execution history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS communication_workflow_outcome_no_update BEFORE UPDATE ON communication_workflow_outcomes BEGIN SELECT RAISE(ABORT,'Workflow outcome history is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS communication_workflow_outcome_no_delete BEFORE DELETE ON communication_workflow_outcomes BEGIN SELECT RAISE(ABORT,'Workflow outcome history is retained'); END;`);
 const tx=fn=>db.isTransaction?fn():transaction(fn);
 const rule=key=>{const row=db.prepare('SELECT * FROM communication_workflows WHERE id=?').get(key);if(!row)fail(404,'Communication workflow not found');return row;};
 const entry=key=>db.prepare('SELECT * FROM communication_workflow_entries WHERE id=?').get(key);
 const marker=()=>db.prepare('SELECT id FROM automation_recovery_markers ORDER BY rowid DESC LIMIT 1').get()?.id||'none';
 const account=key=>db.prepare('SELECT * FROM users WHERE id=?').get(key);
 const securityBinding=owner=>{const factor=db.prepare('SELECT enabled,encrypted_secret FROM mfa_settings WHERE user_id=?').get(owner.id);return hash({account:mfaAccountBinding(owner),enabled:Boolean(factor?.enabled),secret:factor?.enabled?factor.encrypted_secret:null});};
 function current(req,read=false){if(!req?.user||!(read?['admin','staff','viewer']:['admin','staff']).includes(req.user.role))fail(403,'Your role cannot access communication workflows');if(!isTenantActive())fail(403,'Workspace is suspended');if(!recheckAccess(req))fail(401,'Account access changed. Sign in again');}
 function source(row){
  if(!isTenantActive())return {reason:'Workspace suspended'};if(marker()!==row.recovery_marker)return {reason:'Workspace restored; a new reviewed activation is required'};const owner=account(row.owner_id);
  if(!owner?.active||!['admin','staff'].includes(owner.role)||!ownerAllowed(owner))return {reason:'Owner authorization unavailable'};
  if(owner.version!==row.owner_version||mfaAccountBinding(owner)!==row.owner_binding||securityBinding(owner)!==row.security_binding)return {reason:'Owner security changed'};
  let preview,template;try{preview=audiences.previewForWorkflow({id:row.audience_id,version:row.audience_version,channel:row.channel});if(preview.audience.definitionDigest!==row.audience_digest)return {reason:'Audience definition changed'};}catch(e){if(e.status)return {reason:'Audience definition unavailable or changed'};throw e;}
  try{template=communications.getWorkflowTemplate(row.template_id,row.template_version);if(template.definitionDigest!==row.template_digest)return {reason:'Messaging template changed'};}catch(e){if(e.status)return {reason:'Messaging template unavailable or changed'};throw e;}
  if(preview.totalCount>limits.profileWatermarksPerRule)return {reason:'Current audience corpus exceeds the 1000-profile workflow bound'};return {owner,preview,template};
 }
 function outcome(row,status,reason,time,{edge=null,retryAt=null,workflowVersion=row.version}={}){db.prepare('INSERT INTO communication_workflow_outcomes VALUES(?,?,?,?,?,?,?,?,?)').run(randomUUID(),row.id,workflowVersion,edge?.id||null,edge?.version??null,status,reason,iso(time),retryAt);}
 function suppressEntry(row,edge,reason,time){db.prepare("UPDATE communication_workflow_entries SET status='Suppressed',version=version+1,updated_at=? WHERE id=? AND status='Pending'").run(iso(time),edge.id);outcome(row,'Suppressed',reason,time,{edge:{...edge,version:edge.version+1}});}
 function closeRule(row,reason,time,status='Suppressed',actor={id:'system'}){
  if(row.status!=='Active')return 0;db.prepare('UPDATE communication_workflows SET status=?,version=version+1,updated_at=? WHERE id=?').run(status,iso(time),row.id);const closed={...row,status,version:row.version+1};let count=0;for(const edge of db.prepare("SELECT * FROM communication_workflow_entries WHERE workflow_id=? AND status='Pending' ORDER BY id").all(row.id)){suppressEntry(closed,edge,reason,time);count++;}outcome(closed,status,reason,time);audit(actor,status==='Retired'?'retire_communication_workflow':'suppress_communication_workflow',null,row.id,{reason,pendingEpisodesSuppressed:count,delivery});return 1;
 }
 const outcomes=key=>db.prepare('SELECT * FROM communication_workflow_outcomes WHERE workflow_id=? ORDER BY at DESC,rowid DESC LIMIT 100').all(key).map(r=>{let linked=null;if(r.status==='Drafted'&&r.entry_id){const execution=db.prepare('SELECT communication_id,communication_version,constituent_id FROM communication_workflow_executions WHERE entry_id=? AND workflow_id=?').get(r.entry_id,key);if(execution)try{const native=get('communications',execution.communication_id);if(native.id===execution.communication_id&&native.constituentId===execution.constituent_id)linked={communicationId:execution.communication_id,communicationVersion:execution.communication_version};}catch(e){if(e.status!==404)throw e;}}return {id:r.id,workflowVersion:r.workflow_version,entryId:r.entry_id,entryVersion:r.entry_version,status:r.status,reason:r.reason,at:r.at,retryAt:r.retry_at,...(linked||{})};});
 function view(row){const s=source(row);return {id:row.id,name:row.name,version:row.version,status:row.status,ownerId:row.owner_id,audienceId:row.audience_id,audienceVersion:row.audience_version,templateId:row.template_id,templateVersion:row.template_version,channel:row.channel,baselineCount:row.baseline_count,sourceCurrent:row.status==='Active'&&!s.reason,createdAt:row.created_at,updatedAt:row.updated_at,lastOutcome:outcomes(row.id)[0]||null};}
 const route=fn=>(req,res,next)=>{try{fn(req,res);}catch(e){next(e);}};
 app.use('/api/communication-workflows',(req,res,next)=>{try{current(req,true);next();}catch(e){next(e);}});
 app.post('/api/communication-workflows',csrf,write,route((req,res)=>{const p=armSchema.parse(req.body),result=tx(()=>{
  current(req);const owner=account(req.user.id);if(!ownerAllowed(owner))fail(403,'Current owner MFA policy is unavailable');const preview=audiences.previewForWorkflow({id:p.audienceId,version:p.audienceVersion,channel:p.channel}),template=communications.getWorkflowTemplate(p.templateId,p.templateVersion);if(preview.sourceDigest!==p.sourceDigest)fail(409,'Audience source changed. Review the current baseline again');if(preview.totalCount>1000)fail(409,'This activation supports at most 1000 current profiles');if(db.prepare("SELECT COUNT(*) n FROM communication_workflows WHERE status='Active'").get().n>=20)fail(409,'This workspace has 20 active workflows. Retire an unused workflow');const key=randomUUID(),at=iso(clock()),recoveryMarker=marker();
  db.prepare('INSERT INTO communication_workflows VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(key,p.name,'Active',1,owner.id,owner.version,mfaAccountBinding(owner),securityBinding(owner),recoveryMarker,p.audienceId,p.audienceVersion,preview.audience.definitionDigest,p.templateId,p.templateVersion,template.definitionDigest,p.channel,preview.eligibleCount,at,at,at,0);
  const eligible=new Map(preview.eligible.map(profile=>[profile.id,profile]));for(const profileId of preview.profileIds){const profile=eligible.get(profileId);db.prepare('INSERT INTO communication_workflow_memberships VALUES(?,?,?,?,?,?,?)').run(key,profileId,profile?1:0,0,profile?.version??null,profile?hash(profile):null,at);}const saved=rule(key);outcome(saved,'Armed','Current eligible membership recorded as baseline; no historical drafts created',clock());audit(req.user,'arm_communication_workflow',null,key,{audienceId:p.audienceId,audienceVersion:p.audienceVersion,templateId:p.templateId,templateVersion:p.templateVersion,baselineCount:preview.eligibleCount,baselineProfiles:preview.totalCount,historicalBackfill:false,delivery});current(req);const fresh=source(saved);if(fresh.reason||fresh.preview.sourceDigest!==preview.sourceDigest)fail(409,'Activation source changed before it was armed');return view(saved);
 });res.status(201).json({workflow:result,delivery,historicalBackfill:false,limits});}));
 app.get('/api/communication-workflows',route((req,res)=>{z.object({}).strict().parse(req.query);const workflows=tx(()=>db.prepare("SELECT * FROM communication_workflows ORDER BY CASE status WHEN 'Active' THEN 0 ELSE 1 END,created_at DESC,id LIMIT 100").all().map(view));res.json({workflows,limit:100,limits,delivery});}));
 app.get('/api/communication-workflows/:id',route((req,res)=>{id.parse(req.params.id);z.object({}).strict().parse(req.query);const result=tx(()=>({workflow:view(rule(req.params.id)),outcomes:outcomes(req.params.id),outcomeCount:db.prepare('SELECT COUNT(*) n FROM communication_workflow_outcomes WHERE workflow_id=?').get(req.params.id).n}));res.json({...result,outcomeLimit:100,limits,delivery});}));
 app.post('/api/communication-workflows/:id/retire',csrf,write,route((req,res)=>{id.parse(req.params.id);const p=z.object({version,reason:z.string().trim().min(1).max(500)}).strict().parse(req.body),result=tx(()=>{current(req);const row=rule(req.params.id);if(row.owner_id!==req.user.id&&req.user.role!=='admin')fail(403,'Only the owner or an administrator can retire this workflow');if(row.status!=='Active')fail(409,'This activation is closed. Create a new reviewed workflow');if(row.version!==p.version)fail(409,'Workflow changed. Reload its current version');closeRule(row,p.reason,clock(),'Retired',req.user);current(req);return view(rule(row.id));});res.json({workflow:result,delivery});}));
 function reconcile(row,time){
  if(row.status!=='Active')return {queued:0,suppressed:0};const s=source(row);if(s.reason)return {queued:0,suppressed:closeRule(row,s.reason,time)};if(row.next_attempt>iso(time))return {queued:0,suppressed:0};
  const prior=db.prepare('SELECT * FROM communication_workflow_memberships WHERE workflow_id=? ORDER BY constituent_id').all(row.id),old=new Map(prior.map(member=>[member.constituent_id,member])),eligible=new Map(s.preview.eligible.map(profile=>[profile.id,profile])),present=new Set(s.preview.profileIds),newProfiles=s.preview.profileIds.filter(key=>!old.has(key)).length,newEdges=s.preview.eligible.filter(profile=>!old.get(profile.id)?.eligible);
  if(prior.length+newProfiles>1000||db.prepare('SELECT COUNT(*) n FROM communication_workflow_entries WHERE workflow_id=?').get(row.id).n+newEdges.length>1000)return {queued:0,suppressed:closeRule(row,'Retained watermark or membership episode bound reached; review a new activation',time)};
  for(const profileId of s.preview.profileIds){const member=old.get(profileId),profile=eligible.get(profileId),isEligible=profile?1:0,episode=(member?.episode||0)+(isEligible&&!member?.eligible?1:0);if(!member)db.prepare('INSERT INTO communication_workflow_memberships VALUES(?,?,?,?,?,?,?)').run(row.id,profileId,isEligible,episode,profile?.version??null,profile?hash(profile):null,iso(time));else db.prepare('UPDATE communication_workflow_memberships SET eligible=?,episode=?,record_version=?,record_digest=?,last_seen_at=? WHERE workflow_id=? AND constituent_id=?').run(isEligible,episode,profile?.version??null,profile?hash(profile):null,iso(time),row.id,profileId);
   if(isEligible&&!member?.eligible)db.prepare('INSERT INTO communication_workflow_entries VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),row.id,profileId,episode,profile.version,hash(profile),s.preview.sourceDigest,'Pending',1,0,iso(time),iso(time),iso(time));
  }
  for(const member of prior)if(!present.has(member.constituent_id)&&member.eligible)db.prepare('UPDATE communication_workflow_memberships SET eligible=0,last_seen_at=? WHERE workflow_id=? AND constituent_id=?').run(iso(time),row.id,member.constituent_id);
  db.prepare('UPDATE communication_workflows SET failure_count=0,next_attempt=? WHERE id=?').run(iso(time),row.id);const fresh=source(rule(row.id));if(fresh.reason||fresh.preview.sourceDigest!==s.preview.sourceDigest)fail(409,'Audience or authorization changed during membership reconciliation');return {queued:newEdges.length,suppressed:0};
 }
 function suppressPendingForTenant(time=clock()){let suppressed=0;tx(()=>{for(const row of db.prepare("SELECT * FROM communication_workflows WHERE status='Active' ORDER BY id").all())suppressed+=closeRule(row,'Workspace suspended',time);});return {drafted:0,queued:0,suppressed,failed:0,suspended:true};}
 function runCommunicationWorkflows(time=clock()){
  if(!Number.isSafeInteger(time)||time<0)fail(503,'Workflow clock unavailable');if(!isTenantActive())return suppressPendingForTenant(time);let drafted=0,queued=0,suppressed=0,failed=0;
  for(const candidate of db.prepare("SELECT id FROM communication_workflows WHERE status='Active' ORDER BY id LIMIT 20").all())try{const result=tx(()=>reconcile(rule(candidate.id),time));queued+=result.queued;suppressed+=result.suppressed;}catch{failed++;try{const result=tx(()=>{const row=rule(candidate.id);if(row.status!=='Active')return 0;const s=source(row);if(s.reason)return closeRule(row,s.reason,time);if(row.failure_count>=4){db.prepare('UPDATE communication_workflows SET failure_count=failure_count+1 WHERE id=?').run(row.id);return closeRule(row,'Membership reconciliation retry limit reached; review a new activation',time);}const retryAt=iso(time+60000);db.prepare('UPDATE communication_workflows SET failure_count=failure_count+1,next_attempt=?,updated_at=? WHERE id=?').run(retryAt,iso(time),row.id);outcome(row,'Failed','Membership persistence failed; retry scheduled',time,{retryAt});audit({id:'system'},'retry_communication_workflow',null,row.id,{retryAt,delivery});return 0;});suppressed+=result;}catch{console.error('Communication workflow persistence unavailable; no draft success is confirmed.');}}
  const due=db.prepare("SELECT id FROM communication_workflow_entries WHERE status='Pending' AND next_attempt<=? ORDER BY next_attempt,id LIMIT 40").all(iso(time));
  for(const candidate of due)try{const result=tx(()=>{
   const edge=entry(candidate.id);if(!edge||edge.status!=='Pending')return;const row=rule(edge.workflow_id);if(row.status!=='Active')return;const s=source(row);if(s.reason){closeRule(row,s.reason,time);return 'Suppressed';}const profile=s.preview.eligible.find(p=>p.id===edge.constituent_id);if(!profile||profile.version!==edge.source_version||hash(profile)!==edge.source_digest){suppressEntry(row,edge,'Selected recipient changed or is no longer eligible; no draft produced',time);audit({id:'system'},'suppress_communication_workflow_entry',null,row.id,{entryId:edge.id,reason:'Recipient source changed',delivery});return 'Suppressed';}
   const snapshot=communications.prepareWorkflowMessage({templateId:row.template_id,templateVersion:row.template_version,channel:row.channel,constituentId:edge.constituent_id}),item=snapshot.items[0],body={constituentId:edge.constituent_id,subject:item.subject,body:item.body,channel:row.channel==='Print'?'Post':'Email',status:'Draft',date:iso(time).slice(0,10),notes:'Prospective workflow-generated draft. Human review is required; no message has been sent.'},native=create('communications',body,{id:'system'}),executionId=randomUUID();
   db.prepare('INSERT INTO communication_workflow_executions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(executionId,edge.id,row.id,edge.constituent_id,edge.episode,edge.source_version,row.audience_version,row.template_version,native.id,native.version,hash(native),hash({subject:item.subject,body:item.body}),'system',iso(time),delivery);db.prepare("UPDATE communication_workflow_entries SET status='Drafted',version=version+1,attempt_count=attempt_count+1,updated_at=? WHERE id=?").run(iso(time),edge.id);outcome(row,'Drafted','One native Messaging draft produced; human review required; not sent',time,{edge:{...edge,version:edge.version+1}});audit({id:'system'},'draft_communication_workflow',null,row.id,{executionId,entryId:edge.id,episode:edge.episode,constituentId:edge.constituent_id,sourceVersion:edge.source_version,audienceVersion:row.audience_version,templateVersion:row.template_version,communicationId:native.id,communicationVersion:native.version,delivery});
   const currentRow=rule(row.id),fresh=source(currentRow),current=get('communications',native.id);if(currentRow.status!=='Active'||currentRow.version!==row.version||fresh.reason||fresh.preview.sourceDigest!==s.preview.sourceDigest||hash(communications.prepareWorkflowMessage({templateId:row.template_id,templateVersion:row.template_version,channel:row.channel,constituentId:edge.constituent_id}))!==hash(snapshot)||hash(current)!==hash(native))fail(409,'Current consent, source, authorization or native draft changed before commit');return 'Drafted';
  });if(result==='Drafted')drafted++;if(result==='Suppressed')suppressed++;}catch{failed++;try{const recovery=tx(()=>{const edge=entry(candidate.id);if(!edge||edge.status!=='Pending')return;const row=rule(edge.workflow_id),s=source(row);if(row.status!=='Active')return;if(s.reason){closeRule(row,s.reason,time);return 'Suppressed';}if(edge.attempt_count>=4){db.prepare('UPDATE communication_workflow_entries SET attempt_count=attempt_count+1 WHERE id=?').run(edge.id);suppressEntry(row,edge,'Draft persistence retry limit reached; human review required',time);audit({id:'system'},'suppress_communication_workflow_entry',null,row.id,{entryId:edge.id,reason:'Retry limit reached',delivery});return 'Suppressed';}const retryAt=iso(time+60000);db.prepare('UPDATE communication_workflow_entries SET version=version+1,attempt_count=attempt_count+1,next_attempt=?,updated_at=? WHERE id=?').run(retryAt,iso(time),edge.id);outcome(row,'Failed','Native draft persistence failed; retry scheduled; nothing sent',time,{edge:{...edge,version:edge.version+1},retryAt});audit({id:'system'},'retry_communication_workflow_entry',null,row.id,{entryId:edge.id,retryAt,delivery});return 'Retried';});if(recovery==='Suppressed')suppressed++;}catch{console.error('Communication draft persistence unavailable; no successful draft is confirmed.');}}
  return {drafted,queued,suppressed,failed,suspended:false};
 }
 function getDraftOrigin(communicationId,user){if(!['admin','staff','viewer'].includes(user?.role))fail(403,'Workflow draft origin is unavailable');return tx(()=>{const execution=db.prepare('SELECT * FROM communication_workflow_executions WHERE communication_id=?').get(communicationId);if(!execution)return null;const row=rule(execution.workflow_id);let sourceCurrent=false;try{const s=source(row),profile=s.preview?.eligible.find(p=>p.id===execution.constituent_id),native=get('communications',communicationId);const retainedEntry=entry(execution.entry_id);sourceCurrent=row.status==='Active'&&!s.reason&&profile?.version===execution.source_version&&hash(profile)===retainedEntry?.source_digest&&native.version===execution.communication_version&&hash(native)===execution.communication_digest&&native.status==='Draft'&&native.constituentId===execution.constituent_id&&hash({subject:native.subject,body:native.body})===execution.wording_digest;}catch(e){if(!e.status)throw e;}return {workflowId:row.id,workflowName:row.name,episode:execution.episode,producedAt:execution.at,sourceCurrent,delivery,reviewRequired:true};});}
 const timer=worker?setInterval(()=>{try{runCommunicationWorkflows();}catch{console.error('Communication workflow cycle could not complete.');}},30000):null;timer?.unref();
 return {runCommunicationWorkflows,suppressPendingForTenant,getDraftOrigin,close:()=>{if(timer)clearInterval(timer);},validateDeletion:(collection,record)=>{if(collection==='communications'&&db.prepare('SELECT 1 FROM communication_workflow_executions WHERE communication_id=?').get(record.id))fail(409,'Retained workflow execution history protects this draft from deletion');if(collection==='constituents'&&db.prepare('SELECT 1 FROM communication_workflow_entries WHERE constituent_id=?').get(record.id))fail(409,'Retained workflow membership episodes protect this constituent from deletion; change its contact preference instead');}};
}
