import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
import {audienceReferenceSchema} from './audiences.js';

const fail=(status,message)=>{const e=new Error(message);e.status=status;throw e;};
const fields={
 Acknowledgment:['recipientName','recipientEmail','organizationName','giftDate','giftType','giftReference','monetaryAmount','noncashValue'],
 'Annual employee':['recipientName','recipientEmail','organizationName','calendarYear','annualEmployeeAmount','giftCount'],
 Messaging:['recipientName','recipientEmail','organizationName']
};
const templateSchema=z.object({name:z.string().trim().min(1).max(250),kind:z.enum(['Acknowledgment','Annual employee','Messaging']),subject:z.string().trim().min(1).max(500),body:z.string().trim().min(1).max(16000)}).strict();
const ids=z.array(z.string().min(1).max(100)).min(1).max(100).refine(v=>new Set(v).size===v.length,'Select each record only once');
const preparationSchema=z.object({templateId:z.string().uuid(),templateVersion:z.number().int().min(1),channel:z.enum(['Print','Email draft']),giftIds:ids.optional(),constituentIds:ids.optional(),year:z.number().int().min(1900).max(9998).optional(),audience:audienceReferenceSchema.optional()}).strict();
const canonical=value=>Array.isArray(value)?'['+value.map(canonical).join(',')+']':value&&typeof value==='object'?'{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}':JSON.stringify(value);
const hash=value=>createHash('sha256').update(canonical(value)).digest('hex');
const usd=cents=>{if(!Number.isSafeInteger(cents)||cents<0)fail(400,'Recorded value must be safe integer cents.');return '$'+Math.floor(cents/100).toLocaleString('en-US')+'.'+String(cents%100).padStart(2,'0');};
const safeDate=value=>{if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value))||new Date(value+'T00:00:00Z').toISOString().slice(0,10)!==value)fail(400,'Gift must retain an actual valid transaction date.');return value;};

// Plain text only: replacement values are never interpreted as another template,
// HTML, executable code, an object path or a recipient/audience selector.
export function renderCorrespondenceText(text,values,allowed){
 if(typeof text!=='string'||text.length>16000)fail(400,'Template text is invalid or too long.');
 const remaining=text.replace(/\{\{([A-Za-z][A-Za-z0-9]*)\}\}/g,(token,key)=>{if(!allowed.includes(key)||!Object.hasOwn(values,key))fail(400,'Unsupported or unavailable merge field: '+key);return '';});
 if(/[{}]/.test(remaining))fail(400,'Use only the listed {{mergeField}} placeholders.');
 return text.replace(/\{\{([A-Za-z][A-Za-z0-9]*)\}\}/g,(token,key)=>String(values[key]));
}
function verifyTemplate(p){const values=Object.fromEntries(fields[p.kind].map(k=>[k,'']));renderCorrespondenceText(p.subject,values,fields[p.kind]);renderCorrespondenceText(p.body,values,fields[p.kind]);return p;}

export function installCommunicationsRoutes(app,{db,list,get,getSettings=()=>({organizationName:'Workspace'}),audit,csrf,write,transaction,audiences=null}){
 db.exec(`CREATE TABLE IF NOT EXISTS correspondence_templates(id TEXT PRIMARY KEY,version INTEGER NOT NULL,definition TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS correspondence_template_revisions(template_id TEXT NOT NULL,version INTEGER NOT NULL,definition TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL,PRIMARY KEY(template_id,version));
 CREATE TABLE IF NOT EXISTS correspondence_preparations(id TEXT PRIMARY KEY,snapshot TEXT NOT NULL,digest TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS correspondence_finalizations(preparation_id TEXT PRIMARY KEY,actor TEXT NOT NULL,at TEXT NOT NULL,digest TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS correspondence_fulfillments(id TEXT PRIMARY KEY,preparation_id TEXT NOT NULL,preparation_digest TEXT NOT NULL,gift_id TEXT NOT NULL UNIQUE,source_gift_version INTEGER NOT NULL,acknowledgment_gift_version INTEGER NOT NULL,communication_id TEXT NOT NULL UNIQUE,date TEXT NOT NULL,channel TEXT NOT NULL,actor TEXT NOT NULL,reason TEXT NOT NULL,source_json TEXT NOT NULL,at TEXT NOT NULL);
 CREATE TRIGGER IF NOT EXISTS correspondence_fulfillment_no_update BEFORE UPDATE ON correspondence_fulfillments BEGIN SELECT RAISE(ABORT,'Correspondence fulfillment is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS correspondence_fulfillment_no_delete BEFORE DELETE ON correspondence_fulfillments BEGIN SELECT RAISE(ABORT,'Correspondence fulfillment is retained'); END;
 CREATE TRIGGER IF NOT EXISTS correspondence_revision_no_update BEFORE UPDATE ON correspondence_template_revisions BEGIN SELECT RAISE(ABORT,'Template history is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS correspondence_revision_no_delete BEFORE DELETE ON correspondence_template_revisions BEGIN SELECT RAISE(ABORT,'Template history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS correspondence_preparation_no_update BEFORE UPDATE ON correspondence_preparations BEGIN SELECT RAISE(ABORT,'Prepared correspondence is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS correspondence_preparation_no_delete BEFORE DELETE ON correspondence_preparations BEGIN SELECT RAISE(ABORT,'Prepared correspondence is retained'); END;
 CREATE TRIGGER IF NOT EXISTS correspondence_finalization_no_update BEFORE UPDATE ON correspondence_finalizations BEGIN SELECT RAISE(ABORT,'Reviewed correspondence is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS correspondence_finalization_no_delete BEFORE DELETE ON correspondence_finalizations BEGIN SELECT RAISE(ABORT,'Reviewed correspondence is retained'); END;`);
 const authorized=(req,res,next)=>{if(!req.user)return res.status(401).json({error:'Authentication required'});if(!['admin','staff','viewer'].includes(req.user.role))return res.status(403).json({error:'Your role cannot access correspondence'});next();};
 const handler=fn=>(req,res,next)=>{try{fn(req,res);}catch(e){next(e);}};
 app.use('/api/correspondence',authorized);
 const presentTemplate=r=>({id:r.id,version:r.version,...JSON.parse(r.definition),createdAt:r.created_at,updatedAt:r.updated_at});
 const template=id=>{const r=db.prepare('SELECT * FROM correspondence_templates WHERE id=?').get(id);if(!r)fail(404,'Correspondence template not found');return presentTemplate(r);};
 const reference=(collection,r)=>({collection,id:r.id,version:r.version,recordDigest:hash(r)});
 const person=(id,channel)=>{const p=get('constituents',id);if(p.mergedInto)fail(409,'Merged identities cannot receive new correspondence; select the surviving constituent.');if(p.preference==='Do not contact')fail(403,'Do not contact: selected recipient is excluded.');if(channel==='Email draft'&&(p.preference!=='Email'||!z.email().safeParse(p.email).success))fail(400,'Email drafts require the selected constituent’s primary email and Email preference.');return p;};
 const validateGift=g=>{if(g.status!=='Posted')fail(409,'Only posted gifts can be prepared for acknowledgment.');if(g.type==='Fee payment')fail(409,'Fee payments are not donation acknowledgments.');safeDate(g.date);if(g.date>new Date().toISOString().slice(0,10))fail(409,'Future-dated gifts are not actual received support for acknowledgment.');if(!Number.isSafeInteger(g.amount)||g.amount<=0)fail(400,'Gift value must be positive safe integer cents.');if(!Array.isArray(g.allocations)||g.allocations.length===0||g.allocations.some(a=>!Number.isSafeInteger(a.amount)||a.amount<=0)||g.allocations.reduce((sum,a)=>sum+BigInt(a.amount),0n)!==BigInt(g.amount))fail(400,'Gift allocations must reconcile to the recorded value.');if((g.type==='In-kind')!==(g.method==='In-kind'))fail(400,'In-kind gift type and method must agree.');};
 function prepare(p,req=null){
  const t=template(p.templateId);if(t.version!==p.templateVersion)fail(409,'Template changed. Reload its latest version.');
  let audience=null;if(p.audience){if(t.kind!=='Messaging')fail(400,'Saved audiences are supported only for explicitly selected Messaging recipients');if(!audiences?.validateSelection)fail(503,'Saved audience validation is unavailable');audience=audiences.validateSelection(p.audience,p.channel,p.constituentIds,req);}
  if(t.kind==='Acknowledgment'){if(!p.giftIds||p.constituentIds||p.year!==undefined)fail(400,'Acknowledgments require only explicitly selected giftIds.');}
  else if(!p.constituentIds||p.giftIds||(t.kind==='Annual employee'?(p.year===undefined||p.year>new Date().getUTCFullYear()):p.year!==undefined))fail(400,'Select constituentIds and a current or historical calendar year only for annual employee statements.');
  const settings=getSettings(),organizationName=String(settings.organizationName||'Workspace');const items=[];
  const add=(recipient,values,semantics,refs)=>{const merged={recipientName:String(recipient.name||''),recipientEmail:String(recipient.email||''),organizationName,...values};const subject=renderCorrespondenceText(t.subject,merged,fields[t.kind]),body=renderCorrespondenceText(t.body,merged,fields[t.kind]);items.push({recipient:{id:recipient.id,name:merged.recipientName,email:merged.recipientEmail,preference:recipient.preference},subject,body:body+'\n\n'+semantics.statement,semantics,references:[reference('constituents',recipient),...refs]});};
  if(t.kind==='Acknowledgment')for(const id of p.giftIds){const g=get('gifts',id);validateGift(g);const recipient=person(g.constituentId,p.channel);const noncash=g.type==='In-kind';add(recipient,{giftDate:g.date,giftType:g.type,giftReference:String(g.externalRef||''),monetaryAmount:noncash?'Not monetary support':usd(g.amount),noncashValue:noncash?usd(g.amount):'No noncash value'},{kind:noncash?'Noncash acknowledgment':'Recorded monetary acknowledgment',monetaryCents:noncash?0:g.amount,noncashCents:noncash?g.amount:0,statement:noncash?'Noncash support: the displayed value is the CRM’s recorded value, not an assessed deductible amount. This document does not determine tax deductibility.':'Recorded monetary support only. This document does not determine tax deductibility or the value of goods or services received.'},[reference('gifts',g)]);}
  else for(const id of p.constituentIds){const recipient=person(id,p.channel);if(t.kind==='Messaging')add(recipient,{}, {kind:'Message',statement:'Prepared correspondence only; no message has been sent.'},[]);
   else {if(recipient.type!=='Employee')fail(400,'Annual employee statements require explicitly selected Employee constituents.');const gifts=list('gifts').filter(g=>g.constituentId===id&&g.type==='Employee giving'&&g.method==='Payroll'&&g.status==='Posted'&&safeDate(g.date).slice(0,4)===String(p.year)&&g.date<=new Date().toISOString().slice(0,10)).sort((a,b)=>a.id.localeCompare(b.id));if(!gifts.length)fail(400,'Selected employee has no posted payroll employee-giving records in that calendar year.');let total=0n;for(const g of gifts){validateGift(g);total+=BigInt(g.amount);}if(total>BigInt(Number.MAX_SAFE_INTEGER))fail(400,'Annual employee total exceeds safe integer cents.');add(recipient,{calendarYear:String(p.year),annualEmployeeAmount:usd(Number(total)),giftCount:gifts.length},{kind:'Annual payroll record statement',monetaryCents:Number(total),noncashCents:0,calendarYear:p.year,giftCount:gifts.length,statement:'This calendar-year statement includes only posted payroll Employee giving records through today for the named employee. It excludes fees, noncash support, voids and soft-credit recognition. It does not determine tax deductibility.'},gifts.map(g=>reference('gifts',g)));}
  }
  const snapshot={template:{id:t.id,version:t.version,name:t.name,kind:t.kind,definitionDigest:hash({name:t.name,kind:t.kind,subject:t.subject,body:t.body})},channel:p.channel,organizationName,items,request:p,...(audience?{audience}:{}),delivery:'Not sent',acknowledgmentLedger:'Unchanged; record completed external actions separately using the existing acknowledgment endpoint.'};
  if(Buffer.byteLength(JSON.stringify(snapshot),'utf8')>1000000)fail(413,'Prepared correspondence exceeds the storage limit. Select fewer records or shorter templates.');return snapshot;
 }
 const find=id=>{const r=db.prepare('SELECT * FROM correspondence_preparations WHERE id=?').get(id);if(!r)fail(404,'Prepared correspondence not found');return r;};
 const retainedSnapshot=r=>{let snapshot;try{snapshot=JSON.parse(r.snapshot);}catch{fail(503,'Prepared correspondence integrity check failed.');}if(hash(snapshot)!==r.digest)fail(503,'Prepared correspondence integrity check failed.');return snapshot;};
 const hasConstituentReferences=id=>{for(const r of db.prepare('SELECT snapshot,digest FROM correspondence_preparations').iterate()){const snapshot=retainedSnapshot(r);if(!Array.isArray(snapshot.items))fail(503,'Prepared correspondence recipient integrity check failed.');if(snapshot.items.some(item=>item.recipient?.id===id||item.references?.some(ref=>ref.collection==='constituents'&&ref.id===id)))return true;}return false;};
 const fulfillments=id=>db.prepare('SELECT * FROM correspondence_fulfillments WHERE preparation_id=? ORDER BY at,id').all(id).map(r=>({id:r.id,preparationId:r.preparation_id,preparationDigest:r.preparation_digest,giftId:r.gift_id,sourceGiftVersion:r.source_gift_version,acknowledgmentGiftVersion:r.acknowledgment_gift_version,communicationId:r.communication_id,date:r.date,channel:r.channel,actor:r.actor,reason:r.reason,source:JSON.parse(r.source_json),at:r.at,statement:'Staff-confirmed manual completion; the application did not send, print, sign or verify external delivery.'}));
 const present=r=>{const snapshot=retainedSnapshot(r);const final=db.prepare('SELECT * FROM correspondence_finalizations WHERE preparation_id=?').get(r.id);return {id:r.id,version:1,status:final?'Finalized':'Prepared',preparationDigest:r.digest,...snapshot,createdBy:r.actor,createdAt:r.at,finalizedBy:final?.actor??null,finalizedAt:final?.at??null,fulfillments:fulfillments(r.id),review:'Finalization is human review of a retained snapshot; it is not sending, delivery confirmation or a tax certification.'};};
 // Prepared wording is retained evidence even before human finalization. Keep
 // its source identity reachable; stopping outreach remains a preference change.
 app.delete('/api/records/constituents/:id',csrf,write,(req,res,next)=>{try{const constituent=get('constituents',req.params.id),version=z.object({version:z.number().int().min(1)}).parse(req.body).version;if(constituent.version!==version)fail(409,'Record changed. Reload before deleting.');if(hasConstituentReferences(constituent.id))fail(409,'This constituent has retained correspondence and cannot be deleted. Update its contact preference to stop outreach while preserving its source identity.');next();}catch(e){next(e);}});
 app.get('/api/correspondence/templates',handler((req,res)=>res.json({templates:db.prepare('SELECT * FROM correspondence_templates ORDER BY updated_at DESC,id LIMIT 200').all().map(presentTemplate),mergeFields:fields,format:'Plain text',delivery:'Not sent'})));
 app.post('/api/correspondence/templates',csrf,write,handler((req,res)=>{const p=verifyTemplate(templateSchema.parse(req.body));const result=transaction(()=>{if(db.prepare('SELECT count(*) n FROM correspondence_templates').get().n>=200)fail(409,'This workspace has 200 correspondence templates. Edit existing templates.');const id=randomUUID(),at=new Date().toISOString();db.prepare('INSERT INTO correspondence_templates VALUES(?,1,?,?,?)').run(id,JSON.stringify(p),at,at);db.prepare('INSERT INTO correspondence_template_revisions VALUES(?,1,?,?,?)').run(id,JSON.stringify(p),req.user.id,at);audit(req.user,'create_correspondence_template',null,id,{version:1,kind:p.kind});return template(id);});res.status(201).json({template:result});}));
 app.patch('/api/correspondence/templates/:id',csrf,write,handler((req,res)=>{const {version,...body}=z.object({version:z.number().int().min(1)}).passthrough().parse(req.body);const p=verifyTemplate(templateSchema.parse(body));const result=transaction(()=>{const old=template(req.params.id);if(old.version!==version)fail(409,'Template changed. Reload before saving.');if(p.kind!==old.kind)fail(409,'Template kind cannot change; create a new template.');const at=new Date().toISOString();db.prepare('UPDATE correspondence_templates SET version=version+1,definition=?,updated_at=? WHERE id=?').run(JSON.stringify(p),at,old.id);db.prepare('INSERT INTO correspondence_template_revisions VALUES(?,?,?,?,?)').run(old.id,version+1,JSON.stringify(p),req.user.id,at);audit(req.user,'update_correspondence_template',null,old.id,{version:version+1,kind:p.kind});return template(old.id);});res.json({template:result});}));
 app.get('/api/correspondence/templates/:id',handler((req,res)=>{const t=template(req.params.id),history=db.prepare('SELECT version,definition,actor,at FROM correspondence_template_revisions WHERE template_id=? ORDER BY version').all(t.id).map(r=>({version:r.version,...JSON.parse(r.definition),actor:r.actor,at:r.at}));res.json({template:t,revisions:history});}));
 app.post('/api/correspondence/prepare',csrf,write,handler((req,res)=>{const p=preparationSchema.parse(req.body);const result=transaction(()=>{const snapshot=prepare(p,req),id=randomUUID(),at=new Date().toISOString(),digest=hash(snapshot);db.prepare('INSERT INTO correspondence_preparations VALUES(?,?,?,?,?)').run(id,JSON.stringify(snapshot),digest,req.user.id,at);audit(req.user,'prepare_correspondence',null,id,{templateId:p.templateId,templateVersion:p.templateVersion,kind:snapshot.template.kind,recipientCount:snapshot.items.length,channel:p.channel,digest,delivery:'Not sent'});return present(find(id));});res.status(201).json({correspondence:result,delivery:'Not sent'});}));
 app.get('/api/correspondence',handler((req,res)=>{const q=z.object({q:z.string().trim().max(200).optional(),constituentId:z.string().min(1).max(100).optional(),giftId:z.string().min(1).max(100).optional(),status:z.enum(['Prepared','Finalized']).optional()}).strict().parse(req.query);const selected=[];for(const r of db.prepare('SELECT * FROM correspondence_preparations ORDER BY at DESC,id DESC').iterate()){const c=present(r);if(q.status&&c.status!==q.status||q.constituentId&&!c.items.some(i=>i.recipient.id===q.constituentId)||q.giftId&&!c.items.some(i=>i.references.some(ref=>ref.collection==='gifts'&&ref.id===q.giftId))||q.q&&!JSON.stringify({name:c.template.name,items:c.items.map(i=>({recipient:i.recipient.name,subject:i.subject,body:i.body}))}).toLowerCase().includes(q.q.toLowerCase()))continue;selected.push(c);if(selected.length===100)break;}res.json({correspondence:selected,delivery:'Not sent',limit:100});}));
 app.get('/api/correspondence/:id',handler((req,res)=>res.json({correspondence:present(find(req.params.id)),delivery:'Not sent'})));
 app.post('/api/correspondence/:id/finalize',csrf,write,handler((req,res)=>{const p=z.object({version:z.literal(1),preparationDigest:z.string().regex(/^[a-f0-9]{64}$/),confirmed:z.literal(true)}).strict().parse(req.body);const result=transaction(()=>{const r=find(req.params.id),old=present(r);if(old.preparationDigest!==p.preparationDigest)fail(409,'Prepared snapshot changed. Reopen and review it.');if(old.status==='Finalized')fail(409,'This correspondence has already been finalized.');const current=prepare(old.request,req);if(hash(current)!==old.preparationDigest)fail(409,'Referenced records, preferences, annual membership or template changed. Prepare and review a new snapshot.');const at=new Date().toISOString();db.prepare('INSERT INTO correspondence_finalizations VALUES(?,?,?,?)').run(r.id,req.user.id,at,r.digest);audit(req.user,'finalize_correspondence',null,r.id,{templateId:old.template.id,templateVersion:old.template.version,recipientCount:old.items.length,digest:r.digest,delivery:'Not sent',humanReviewed:true});return present(find(r.id));});res.json({correspondence:result,delivery:'Not sent'});}));
 const validateAcknowledgmentSource=(user,gift,body)=>{
  if(!body.correspondence)return null;
  if(!user||!['admin','staff'].includes(user.role))fail(403,'Only current staff or administrators can confirm manual correspondence fulfillment');
  const link=z.object({preparationId:z.string().uuid(),preparationDigest:z.string().regex(/^[a-f0-9]{64}$/),confirmed:z.literal(true),reason:z.string().trim().min(1).max(2000)}).strict().parse(body.correspondence);
  const raw=find(link.preparationId),retained=present(raw),final=db.prepare('SELECT * FROM correspondence_finalizations WHERE preparation_id=?').get(raw.id);
  if(retained.status!=='Finalized'||retained.template.kind!=='Acknowledgment')fail(409,'Select a finalized reviewed gift acknowledgment, not a prepared document, message or annual statement');
  if(link.preparationDigest!==raw.digest||final.digest!==raw.digest)fail(409,'Finalized correspondence integrity or selected digest changed. Reopen the retained source');
  const revision=db.prepare('SELECT definition FROM correspondence_template_revisions WHERE template_id=? AND version=?').get(retained.template.id,retained.template.version);
  if(!revision||hash(JSON.parse(revision.definition))!==retained.template.definitionDigest)fail(503,'Retained template revision integrity check failed');
  const matches=retained.items.map((item,index)=>({item,index})).filter(({item})=>item.references.some(ref=>ref.collection==='gifts'&&ref.id===gift.id));
  if(matches.length!==1)fail(409,'This finalized acknowledgment does not contain exactly one document for the selected gift');
  const {item,index}=matches[0],giftReferences=item.references.filter(ref=>ref.collection==='gifts');if(giftReferences.length!==1)fail(409,'Select an individual gift acknowledgment');
  validateGift(gift);if(gift.acknowledgment||db.prepare('SELECT 1 FROM correspondence_fulfillments WHERE gift_id=?').get(gift.id))fail(409,'The gift already has a completed acknowledgment');
  const actualDate=safeDate(body.date),finalDate=final.at.slice(0,10);if(actualDate>new Date().toISOString().slice(0,10)||actualDate<finalDate||actualDate<gift.date)fail(400,'Actual completion must be on or after the gift and human finalization dates, and cannot be in the future');
  if(body.channel!==(retained.channel==='Print'?'Post':'Email'))fail(400,'Actual completion channel must match the retained Print (Post) or Email draft (Email) document');
  if(gift.constituentId!==item.recipient.id)fail(409,'The gift donor no longer matches the retained recipient');person(item.recipient.id,retained.channel);
  for(const ref of item.references){const current=ref.collection==='gifts'?gift:get(ref.collection,ref.id);if(current.version!==ref.version||hash(current)!==ref.recordDigest)fail(409,'Gift source, recipient details or consent changed after preparation. Prepare and review new wording before confirming completion');}
  return {preparationId:raw.id,preparationDigest:raw.digest,finalizationDigest:final.digest,finalizedBy:final.actor,finalizedAt:final.at,templateId:retained.template.id,templateVersion:retained.template.version,itemIndex:index,giftId:gift.id,giftVersion:gift.version,recipientId:item.recipient.id,wordingDigest:hash({subject:item.subject,body:item.body}),preparedChannel:retained.channel};
 };
 const retainAcknowledgmentFulfillment=(user,source,{gift,communication,date,channel,reason})=>{
  if(!source)return null;if(!db.isTransaction)fail(503,'Manual fulfillment must be retained in the acknowledgment transaction');
  if(gift.id!==source.giftId||gift.version!==source.giftVersion+1||gift.acknowledgment?.communicationId!==communication.id||gift.acknowledgment?.date!==date||gift.acknowledgment?.channel!==channel||communication.giftId!==gift.id||hash(gift.acknowledgment?.correspondence)!==hash(source)||hash(communication.correspondence)!==hash(source))fail(503,'Acknowledgment source handoff is inconsistent');
  const completionReason=z.string().trim().min(1).max(2000).parse(reason),at=new Date().toISOString(),id=randomUUID();db.prepare('INSERT INTO correspondence_fulfillments VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,source.preparationId,source.preparationDigest,gift.id,source.giftVersion,gift.version,communication.id,date,channel,user.id,completionReason,JSON.stringify(source),at);
  audit(user,'fulfill_correspondence','gifts',gift.id,{preparationId:source.preparationId,preparationDigest:source.preparationDigest,wordingDigest:source.wordingDigest,communicationId:communication.id,sourceGiftVersion:source.giftVersion,acknowledgmentGiftVersion:gift.version,date,channel,manualConfirmation:true,applicationSent:false});return fulfillments(source.preparationId).find(r=>r.id===id);
 };
 function workflowTemplate(key,expectedVersion){const t=template(z.uuid().parse(key));if(t.kind!=='Messaging')fail(400,'Workflow templates must be Messaging templates');if(t.version!==expectedVersion)fail(409,'Workflow template changed');const revision=db.prepare('SELECT definition FROM correspondence_template_revisions WHERE template_id=? AND version=?').get(t.id,t.version);if(!revision||hash(JSON.parse(revision.definition))!==hash({name:t.name,kind:t.kind,subject:t.subject,body:t.body}))fail(503,'Workflow template revision integrity check failed');return {...t,definitionDigest:hash({name:t.name,kind:t.kind,subject:t.subject,body:t.body})};}
 return {mergeFields:fields,prepareCorrespondence:prepare,validateAcknowledgmentSource,retainAcknowledgmentFulfillment,getWorkflowTemplate:workflowTemplate,prepareWorkflowMessage:body=>{if(!db.isTransaction)fail(503,'Workflow preparation requires the native transaction');const p=z.object({templateId:z.uuid(),templateVersion:z.number().int().positive(),channel:z.enum(['Print','Email draft']),constituentId:z.uuid()}).strict().parse(body);workflowTemplate(p.templateId,p.templateVersion);return prepare(preparationSchema.parse({templateId:p.templateId,templateVersion:p.templateVersion,channel:p.channel,constituentIds:[p.constituentId]}));}};
}
