import {createHash} from 'node:crypto';
import {z} from 'zod';

const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const hash=v=>createHash('sha256').update(canonical(v)??'null').digest('hex');
const parsed=value=>{try{return JSON.parse(value);}catch{fail(503,'Timeline source metadata is invalid. Ask an administrator to reconcile the source.');}};
const day=value=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value.slice(0,10))&&Number.isFinite(Date.parse(value))?value.slice(0,10):null;
const text=value=>typeof value==='string'?value.slice(0,2000):'';
const cents=value=>{if(value===null||value===undefined)return null;if(!Number.isSafeInteger(value)||value<0)fail(503,'Timeline source money is not safe integer cents.');return value;};
const query=z.object({limit:z.coerce.number().int().min(1).max(50).default(30),cursor:z.string().regex(/^[A-Za-z0-9_-]+$/).max(300).optional()}).strict();
const MAX_SOURCE_ROWS=10000,MAX_ENTRIES=10000;

// This is a curated, read-only relationship index. No income is aggregated and
// no raw donor/template/document snapshots are returned. Source visibility is
// rechecked on every page; a changed source fingerprint invalidates old cursors.
export function installConstituentTimelineRoutes(app,{db,list,get,getGrantMilestones}){
 const hasTable=name=>Boolean(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(name));
 const rows=(sql,...args)=>{const result=db.prepare(sql+' LIMIT '+(MAX_SOURCE_ROWS+1)).all(...args);if(result.length>MAX_SOURCE_ROWS)fail(413,'The timeline source exceeds this review limit. Reconcile or narrow the source inventory before viewing it.');return result;};
 const actor=value=>{let saved;if(value&&typeof value==='object')saved=value;else if(typeof value==='string'&&value.startsWith('{'))saved=parsed(value);else saved={id:value};if(!saved?.id)return null;const user=hasTable('users')?db.prepare('SELECT name FROM users WHERE id=?').get(saved.id):null;return {id:String(saved.id),name:text(saved.name)||text(user?.name)||'Recorded staff member',nameBasis:saved.name?'Retained staff name':'Current account label'};};
 const source=(collection,r,version=r.version)=>({collection,id:r.id,version:version??null,currentVersion:r.version??null,versionBasis:version!==r.version?'Retained source revision':'Current source revision'});
 const moduleSource=(view,id,version,endpoint)=>({view,id,version:version??null,versionBasis:view==='correspondence'?'Retained preparation revision':version===null?'Revision not supplied':'Current tracking record revision',endpoint});
 function build(req){
  if(!req.user)fail(401,'Authentication required');if(!['admin','staff','viewer'].includes(req.user.role))fail(403,'Your role cannot access relationship history');
  const person=get('constituents',req.params.id,req),people=new Map(),records={};
  for(const collection of ['constituents','gifts','communications','tasks','events','grants']){const result=list(collection,req);if(!Array.isArray(result)||result.length>MAX_SOURCE_ROWS)fail(413,'The current relationship source exceeds this review limit.');records[collection]=new Map(result.map(r=>[r.id,r]));}
  for(const [id,p] of records.constituents)people.set(id,p);
  if(!people.has(person.id))fail(404,'Constituent not found');
  const entries=[],asOf=new Date().toISOString().slice(0,10);
  const add=entry=>{if(entries.length>=MAX_ENTRIES)fail(413,'This relationship exceeds the bounded timeline review limit.');const date=day(entry.date||entry.recordedAt);entries.push({id:entry.id,category:entry.category,kind:entry.kind,fact:entry.fact||'Retained action',date,dateMeaning:entry.dateMeaning||({'Gift source':'Transaction date','Soft-credit source':'Recognition source transaction date','Task':'Due date','Major ask':'Next action / saved date','Event registration':'Event / registration date','Grant obligation':'Obligation due date'}[entry.kind]||'Recorded action date'),recordedAt:entry.recordedAt||null,title:text(entry.title),summary:text(entry.summary),summaryTruncated:typeof entry.summary==='string'&&entry.summary.length>2000,status:text(entry.status),source:entry.source,relatedSources:entry.relatedSources||[],actor:entry.actor||null,amountCents:cents(entry.amountCents),amountMeaning:entry.amountMeaning||null,provenance:entry.provenance||null,...(entry.changes?{changes:entry.changes}:{})});};
  const visibleGift=(id)=>{const g=records.gifts.get(id);return g&&people.has(g.constituentId)?g:null;};
  for(const g of records.gifts.values())if(people.has(g.constituentId)&&(g.constituentId===person.id||g.softCreditId===person.id)){
   const recognition=g.constituentId!==person.id,status=g.status==='Voided'?'Voided — excluded from contributions':g.date>asOf?'Future-dated — excluded from received totals':g.type==='Fee payment'?'Fee payment — separate from contributions':g.type==='In-kind'?'Recorded noncash support':g.status;
   add({id:'gift:'+g.id,category:recognition?'Recognition':'Giving',kind:recognition?'Soft-credit source':'Gift source',fact:'Current record',date:g.date,recordedAt:g.createdAt,title:recognition?'Soft-credit recognition':`${g.type} gift`,summary:recognition?'Recognition references another donor’s gift and is not additional received income.':'Current recorded transaction. This value does not prove settlement or tax deductibility.',status,source:source('gifts',g),amountCents:g.amount,amountMeaning:recognition?'Recognition source value':g.type==='In-kind'?'CRM recorded noncash value':'Current recorded gift value'});
   if(!recognition&&g.acknowledgment){const a=g.acknowledgment,c=records.communications.get(a.communicationId);if(c&&c.constituentId===person.id&&c.giftId===g.id)add({id:'acknowledgment:'+g.id,category:'Relationship',kind:'Gift acknowledgment',date:a.date,recordedAt:a.at,title:'Actual acknowledgment recorded',summary:a.notes,status:`Staff-recorded ${a.channel}; no application delivery inferred`,source:source('communications',c),relatedSources:[source('gifts',g)],actor:actor(a.correspondence&&hasTable('correspondence_fulfillments')?db.prepare('SELECT actor FROM correspondence_fulfillments WHERE gift_id=?').get(g.id)?.actor:null)});}
  }
  if(hasTable('gift_financial_corrections'))for(const r of rows("SELECT * FROM gift_financial_corrections WHERE json_extract(before_json,'$.constituentId')=? OR json_extract(after_json,'$.constituentId')=? ORDER BY at,id",person.id,person.id)){
   const g=visibleGift(r.gift_id);if(!g)continue;const before=parsed(r.before_json),after=parsed(r.after_json);if(!people.has(before.constituentId)||!people.has(after.constituentId))continue;const changed=parsed(r.changed_fields);if(!Array.isArray(changed)||changed.some(v=>typeof v!=='string'))fail(503,'Correction history fields are invalid.');
   add({id:'correction:'+r.id,category:'Giving',kind:'Financial correction',date:r.at,recordedAt:r.at,title:`Gift corrected · v${r.from_version} → v${r.to_version}`,summary:r.reason,status:'Retained correction; before/after values are not additional income',source:source('gifts',g),actor:actor(r.actor_json),changes:{fromVersion:r.from_version,toVersion:r.to_version,beforeAmountCents:cents(before.amount),afterAmountCents:cents(after.amount),changedFields:changed},relatedSources:[]});
  }
  for(const c of records.communications.values())if(c.constituentId===person.id){if(c.giftId&&!visibleGift(c.giftId))continue;
   // The gift acknowledgment above represents its generated communication once.
   if(c.giftId&&visibleGift(c.giftId)?.acknowledgment?.communicationId===c.id)continue;
   add({id:'communication:'+c.id,category:'Relationship',kind:'Interaction',fact:'Current record',date:c.date,recordedAt:c.createdAt,title:c.subject,summary:c.body,status:c.status==='Draft'?'Draft — not sent':`${c.status}; recorded interaction, no delivery inferred`,source:source('communications',c),relatedSources:c.giftId&&visibleGift(c.giftId)?[source('gifts',visibleGift(c.giftId))]:[]});
  }
  for(const task of records.tasks.values())if(task.constituentId===person.id){
   const account=task.ownerId&&hasTable('users')?db.prepare('SELECT name,active,role FROM users WHERE id=?').get(task.ownerId):null,currentOwner=account?.name||task.owner||'Unassigned',ownerStatus=task.ownerId?account?.active&&['admin','staff'].includes(account.role)?'Assigned':'Needs reassignment':task.owner?'Legacy label — choose staff':'Unassigned';
   add({id:'task:'+task.id,category:'Responsibility',kind:'Task',fact:'Current record',date:task.dueDate,recordedAt:task.updatedAt,title:task.title,summary:`Owner: ${currentOwner} · ${ownerStatus}. Due dates do not deliver reminders.`,status:task.status,source:source('tasks',task)});
   if(hasTable('task_assignments'))for(const h of rows('SELECT * FROM task_assignments WHERE task_id=? ORDER BY at,id',task.id)){const before=parsed(h.before_owner),after=parsed(h.after_owner);add({id:'task-assignment:'+h.id,category:'Responsibility',kind:'Responsibility change',date:h.at,recordedAt:h.at,title:`${text(before.name)||'Unassigned'} → ${text(after.name)||'Unassigned'}`,summary:h.reason,status:`Retained assignment · v${h.from_version??'new'} → v${h.to_version}`,source:source('tasks',task,h.to_version),provenance:{transitionId:h.id,fromVersion:h.from_version,toVersion:h.to_version},actor:actor(h.actor)});}
  }
  if(hasTable('fundraising_records'))for(const raw of rows("SELECT * FROM fundraising_records WHERE json_extract(data,'$.donorId')=? OR json_extract(data,'$.matchingOrganizationId')=? ORDER BY updated_at,id",person.id,person.id)){
   const r=parsed(raw.data);if(r.originalGiftId&&!visibleGift(r.originalGiftId))continue;if(hasTable('fundraising_associations')&&rows('SELECT gift_id FROM fundraising_associations WHERE record_id=? ORDER BY id',raw.id).some(a=>!visibleGift(a.gift_id)))continue;if(r.donorId&&!people.has(r.donorId)||r.matchingOrganizationId&&!people.has(r.matchingOrganizationId))continue;
   const currentSource=moduleSource('fundraising',raw.id,raw.version,'/api/fundraising'),kind=r.kind==='major'?'Major ask':r.kind==='planned'?'Planned commitment':'Matching claim';
   add({id:'fundraising:'+raw.id,category:'Fundraising',kind,fact:'Current record',date:r.nextActionDate||raw.updated_at,recordedAt:raw.updated_at,title:r.name,summary:r.kind==='major'?`Next action ${r.nextActionDate||'not scheduled'} · ${r.nextActionStatus||'Open'}. Owner ${actor(r.ownerId)?.name||'Unavailable'}.`:'Tracking record only; a commitment or claim is not received income.',status:r.stage||r.status,source:currentSource,amountCents:r.kind==='major'?r.expectedAmount:r.kind==='planned'?r.commitmentAmount:null,amountMeaning:r.kind==='major'?'Ask estimate — not income':r.kind==='planned'?'Documented intention — not income':null});
   if(hasTable('fundraising_activity'))for(const a of rows('SELECT * FROM fundraising_activity WHERE record_id=? ORDER BY at,id',raw.id))add({id:'fundraising-activity:'+a.id,category:'Fundraising',kind:a.action==='record_major_followup'?'Actual follow-up disposition':'Fundraising activity',date:a.date,recordedAt:a.at,title:a.action.replaceAll('_',' '),summary:a.note,status:'Retained staff action — no application sending or new income',source:currentSource,provenance:{activityId:a.id,retainedActivityRevision:null,currentTrackingRevision:raw.version},actor:actor(a.actor)});
   if(hasTable('fundraising_associations'))for(const a of rows('SELECT * FROM fundraising_associations WHERE record_id=? ORDER BY created_at,id',raw.id)){const g=visibleGift(a.gift_id);if(!g||g.constituentId!==person.id)continue;add({id:'fundraising-association:'+a.id,category:'Fundraising',kind:'Existing gift association',date:a.unlinked_at||a.created_at,recordedAt:a.unlinked_at||a.created_at,title:a.status==='active'?'Existing gift linked':'Gift association unlinked',summary:a.unlink_reason||'References an existing gift; does not create or duplicate ledger income.',status:`${a.status} association · v${a.version}`,source:source('gifts',g,a.gift_version),relatedSources:[currentSource]});}
  }
  if(hasTable('correspondence_preparations'))for(const raw of rows("SELECT * FROM correspondence_preparations WHERE EXISTS(SELECT 1 FROM json_each(snapshot,'$.items') i WHERE json_extract(i.value,'$.recipient.id')=?) ORDER BY at,id",person.id)){
   const snapshot=parsed(raw.snapshot);if(hash(snapshot)!==raw.digest)fail(503,'Correspondence timeline integrity check failed.');const final=hasTable('correspondence_finalizations')?db.prepare('SELECT * FROM correspondence_finalizations WHERE preparation_id=?').get(raw.id):null;if(final&&final.digest!==raw.digest)fail(503,'Correspondence finalization integrity check failed.');
   for(const [index,item] of snapshot.items.entries())if(item.recipient.id===person.id){if(!Array.isArray(item.references)||item.references.some(ref=>ref.collection==='gifts'&&!visibleGift(ref.id)||ref.collection==='constituents'&&!people.has(ref.id)))continue;const giftRefs=item.references.filter(ref=>ref.collection==='gifts').map(ref=>source('gifts',visibleGift(ref.id),ref.version));
    const retainedSource=moduleSource('correspondence',raw.id,1,`/api/correspondence/${encodeURIComponent(raw.id)}`);
    add({id:`correspondence:${raw.id}:${index}`,category:'Correspondence',kind:final?'Reviewed correspondence':'Prepared correspondence',date:final?.at||raw.at,recordedAt:final?.at||raw.at,title:`${snapshot.template.kind} · ${snapshot.template.name}`,summary:'Retained subject: '+item.subject,status:final?'Finalized human review — application Not sent':'Prepared draft — application Not sent',source:retainedSource,relatedSources:giftRefs,actor:actor(final?.actor||raw.actor)});
    if(hasTable('correspondence_fulfillments'))for(const f of rows('SELECT * FROM correspondence_fulfillments WHERE preparation_id=? ORDER BY at,id',raw.id)){const link=parsed(f.source_json);if(link.itemIndex!==index)continue;const g=visibleGift(f.gift_id),c=records.communications.get(f.communication_id);if(!g||!c||c.constituentId!==person.id||f.preparation_digest!==raw.digest||link.preparationId!==raw.id||link.giftId!==f.gift_id||link.preparationDigest!==raw.digest||link.recipientId!==person.id||link.giftVersion!==f.source_gift_version||hash(g.acknowledgment?.correspondence)!==hash(link)||hash(c.correspondence)!==hash(link)||!g.acknowledgment?.correspondence||g.acknowledgment.communicationId!==c.id||c.giftId!==g.id)continue;
     add({id:'correspondence-fulfillment:'+f.id,category:'Correspondence',kind:'Reviewed wording fulfilled manually',date:f.date,recordedAt:f.at,title:'Staff-confirmed manual fulfillment',summary:f.reason,status:`Actual ${f.channel} recorded; application did not send, print or sign`,source:source('communications',c),relatedSources:[retainedSource,source('gifts',g,f.source_gift_version)],actor:actor(f.actor)});
    }
   }
  }
  for(const e of records.events.values())for(const r of e.registrations||[])if(r.constituentId===person.id)add({id:'event-registration:'+e.id,category:'Events',kind:'Event registration',fact:'Current record',date:e.date||r.registeredAt,recordedAt:r.registeredAt,title:e.name,summary:'Current guest registration; check-in does not create volunteer hours or a gift.',status:r.checkedIn?'Checked in':'Registered',source:source('events',e)});
  if(typeof getGrantMilestones==='function')for(const m of getGrantMilestones(req.user)){const g=records.grants.get(m.grantId);if(!g||g.funderId!==person.id)continue;add({id:'grant-milestone:'+m.id,category:'Grants',kind:'Grant obligation',fact:'Current authorized projection',date:m.dueDate,title:m.name,summary:`${m.kind} obligation · Owner ${m.owner?.name||'Unavailable'}. Documentary completion is separate from funder acceptance and income.`,status:m.status,source:source('grants',g),relatedSources:[moduleSource('grant-operations',m.id,null,`/api/grant-operations/${encodeURIComponent(m.id)}`)]});}
  entries.sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.recordedAt||'').localeCompare(a.recordedAt||'')||a.id.localeCompare(b.id));
  return {person,asOf,entries};
 }
 app.get('/api/constituents/:id/timeline',(req,res,next)=>{try{
  const p=query.parse(req.query);let result;const alreadyReading=db.isTransaction;if(!alreadyReading)db.exec('BEGIN');try{result=build(req);if(!alreadyReading)db.exec('COMMIT');}catch(e){if(!alreadyReading)db.exec('ROLLBACK');throw e;}
  const fingerprint=hash({userId:req.user.id,role:req.user.role,constituentId:result.person.id,constituentVersion:result.person.version,asOf:result.asOf,entries:result.entries});let offset=0;
  if(p.cursor){let cursor;try{cursor=JSON.parse(Buffer.from(p.cursor,'base64url').toString('utf8'));}catch{fail(400,'Timeline page cursor is invalid.');}if(!cursor||typeof cursor.digest!=='string'||!/^[a-f0-9]{64}$/.test(cursor.digest)||!Number.isSafeInteger(cursor.offset)||cursor.offset<0)fail(400,'Timeline page cursor is invalid.');if(cursor.digest!==fingerprint)fail(409,'Relationship sources or your access changed. Reload the timeline before continuing.');offset=cursor.offset;}
  const entries=result.entries.slice(offset,offset+p.limit),nextOffset=offset+entries.length;res.json({constituentId:result.person.id,constituentVersion:result.person.version,asOf:result.asOf,entries,nextCursor:nextOffset<result.entries.length?Buffer.from(JSON.stringify({digest:fingerprint,offset:nextOffset})).toString('base64url'):null,hasMore:nextOffset<result.entries.length,limit:p.limit,fingerprint,scope:'Curated authorized relationship index. Current records and retained actions are distinct; source values are not additional income. Core gifts, corrections, acknowledgments, interactions, tasks, fundraising, correspondence, current event registrations and authorized grant obligations are included. Tribute history, private documents, event inventory/bid histories and volunteer time are not indexed here; use their permission-checked workspaces. No sending, settlement or external acceptance is inferred.'});
 }catch(e){next(e);}});
 return {buildTimeline:build};
}
