import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';

const MAX_BYTES=1024*1024;
const digest=b=>createHash('sha256').update(b).digest('hex');
const fail=(status,message)=>{const e=new Error(message);e.status=status;throw e;};
const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v,'Use a valid calendar date');
const metadata={title:z.string().trim().min(1).max(250),category:z.enum(['Attachment','Proposal','Agreement','Report']),visibility:z.enum(['Workspace','Administrators']),status:z.enum(['Draft','Final','Submitted']),evidenceDate:day.nullable().default(null)};
const upload={filename:z.string().trim().min(1).max(180).refine(v=>!/[\u0000-\u001f\/\\]/.test(v),'Use a plain filename'),contentBase64:z.string().min(4).max(Math.ceil(MAX_BYTES/3)*4).regex(/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/)};

function decodeFile(p){
 const bytes=Buffer.from(p.contentBase64,'base64');if(!bytes.length||bytes.length>MAX_BYTES||bytes.toString('base64')!==p.contentBase64)fail(400,'File must be valid base64 and no larger than 1 MiB.');
 const extension=p.filename.split('.').at(-1).toLowerCase();let mime;
 if(extension==='pdf'&&bytes.subarray(0,5).toString()==='%PDF-')mime='application/pdf';
 else if(extension==='png'&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))mime='image/png';
 else if(['jpg','jpeg'].includes(extension)&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255)mime='image/jpeg';
 else if(['txt','csv'].includes(extension)&&!bytes.includes(0)&&Buffer.from(bytes.toString('utf8')).equals(bytes))mime=extension==='csv'?'text/csv;charset=utf-8':'text/plain;charset=utf-8';
 if(!mime)fail(400,'Use a valid PDF, PNG, JPEG, UTF-8 TXT or CSV file. Executables, HTML, archives and Office files are not supported.');
 return {bytes,mime,sha256:digest(bytes)};
}

export function installDocumentRoutes(app,{db,list,get,audit,csrf,write,admin,transaction,collections,objectStorage=null,tenantId=null,isTenantActive=()=>true,scanDocument=null}){
 const linkedCollections=collections.filter(c=>!['evaluations','reportViews','volunteerTime','shiftReservations'].includes(c));
 db.exec(`CREATE TABLE IF NOT EXISTS documents(id TEXT PRIMARY KEY,collection TEXT NOT NULL,record_id TEXT NOT NULL,title TEXT NOT NULL,category TEXT NOT NULL,visibility TEXT NOT NULL,status TEXT NOT NULL,evidence_date TEXT,version INTEGER NOT NULL,archived INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,retention_until TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS document_revisions(document_id TEXT NOT NULL REFERENCES documents(id),revision INTEGER NOT NULL,filename TEXT NOT NULL,mime TEXT NOT NULL,bytes BLOB NOT NULL,sha256 TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL,metadata TEXT NOT NULL,PRIMARY KEY(document_id,revision));
 CREATE TABLE IF NOT EXISTS document_revision_storage(document_id TEXT NOT NULL,revision INTEGER NOT NULL,tenant_id TEXT NOT NULL,provider TEXT NOT NULL,bucket TEXT NOT NULL,namespace TEXT NOT NULL,object_key TEXT NOT NULL,object_version TEXT,sha256 TEXT NOT NULL,size INTEGER NOT NULL CHECK(size>0),created_at TEXT NOT NULL,PRIMARY KEY(document_id,revision),FOREIGN KEY(document_id,revision) REFERENCES document_revisions(document_id,revision));
 CREATE TABLE IF NOT EXISTS document_upload_attempts(id TEXT PRIMARY KEY,document_id TEXT NOT NULL,revision INTEGER NOT NULL,tenant_id TEXT NOT NULL,collection TEXT NOT NULL,record_id TEXT NOT NULL,visibility TEXT NOT NULL,requested_version INTEGER NOT NULL,provider TEXT NOT NULL,bucket TEXT NOT NULL,namespace TEXT NOT NULL,object_key TEXT NOT NULL,object_version TEXT,sha256 TEXT NOT NULL,size INTEGER NOT NULL,state TEXT NOT NULL CHECK(state IN ('Uploading','Verified','Committed','Failed','Quarantined','Orphaned')),actor TEXT NOT NULL,started_at TEXT NOT NULL,updated_at TEXT NOT NULL,error_code TEXT);
 CREATE TRIGGER IF NOT EXISTS document_storage_no_update BEFORE UPDATE ON document_revision_storage BEGIN SELECT RAISE(ABORT,'Private document references are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS document_storage_no_delete BEFORE DELETE ON document_revision_storage BEGIN SELECT RAISE(ABORT,'Private document references are retained'); END;
 CREATE TRIGGER IF NOT EXISTS document_revision_no_update BEFORE UPDATE ON document_revisions BEGIN SELECT RAISE(ABORT,'Document revisions are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS document_revision_no_delete BEFORE DELETE ON document_revisions BEGIN SELECT RAISE(ABORT,'Document revisions are retained'); END;`);
 const mayRead=(r,u)=>r.visibility!=='Administrators'||u.role==='admin';
 function find(id,u){const r=db.prepare('SELECT * FROM documents WHERE id=?').get(id);if(!r||!mayRead(r,u))fail(404,'Document not found');return r;}
 const publicRevision=r=>({revision:r.revision,filename:r.filename,mime:r.mime,size:r.size,sha256:r.sha256,actor:r.actor,at:r.at,metadata:JSON.parse(r.metadata)});
 const revisions=(id,user)=>db.prepare('SELECT revision,filename,mime,CASE WHEN length(bytes)>0 THEN length(bytes) ELSE COALESCE((SELECT size FROM document_revision_storage s WHERE s.document_id=document_revisions.document_id AND s.revision=document_revisions.revision),0) END AS size,sha256,actor,at,metadata FROM document_revisions WHERE document_id=? ORDER BY revision DESC').all(id).filter(r=>mayRead(JSON.parse(r.metadata),user)).map(publicRevision);
 const view=(r,user)=>({id:r.id,collection:r.collection,recordId:r.record_id,title:r.title,category:r.category,visibility:r.visibility,status:r.status,evidenceDate:r.evidence_date,version:r.version,archived:Boolean(r.archived),createdAt:r.created_at,updatedAt:r.updated_at,retentionUntil:r.retention_until,revisions:revisions(r.id,user)});
 function verifyMetadata(p,u){if(p.visibility==='Administrators'&&u.role!=='admin')fail(403,'Only administrators can create or change administrator-only documents.');if(p.status==='Submitted'&&!p.evidenceDate)fail(400,'A submitted document needs its actual submission date.');if(p.evidenceDate&&p.evidenceDate>new Date().toISOString().slice(0,10))fail(400,'Evidence date cannot be in the future.');}
 const storageRow=(documentId,revision)=>db.prepare('SELECT * FROM document_revision_storage WHERE document_id=? AND revision=?').get(documentId,revision);
 const reference=r=>({documentId:r.document_id,revision:r.revision,provider:r.provider,bucket:r.bucket,namespace:r.namespace,tenantId:r.tenant_id,key:r.object_key,version:r.object_version,sha256:r.sha256,size:r.size});
 const rowPin=(document,file,stored)=>({documentId:document.id,documentVersion:document.version,revision:file.revision,rowDigest:digest(Buffer.from(JSON.stringify({filename:file.filename,mime:file.mime,sha256:file.sha256,metadata:file.metadata,storage:stored||null})))});
 function assertTenant(stored){if(!tenantId||stored.tenant_id!==tenantId)fail(503,'Private document reference cannot be read outside its explicit tenant.');}
 function assertRevisionCurrent(pin,user){if(!isTenantActive())fail(403,'Tenant access changed during document verification.');if(pin.sessionTokenHash&&!db.prepare('SELECT 1 FROM sessions WHERE token_hash=? AND expires>? AND last_seen>?').get(pin.sessionTokenHash,Date.now(),Date.now()-30*60*1000))fail(401,'Document session is no longer active.');if(pin.accountId){const current=db.prepare('SELECT role,active,version FROM users WHERE id=?').get(pin.accountId);if(!current?.active||current.role!==pin.accountRole||current.version!==pin.accountVersion)fail(401,'Account access changed during document verification.');}const document=find(pin.documentId,user),file=db.prepare('SELECT * FROM document_revisions WHERE document_id=? AND revision=?').get(document.id,pin.revision);if(!file||!mayRead(JSON.parse(file.metadata),user))fail(404,'Document revision not found');const stored=storageRow(document.id,file.revision);if(stored)assertTenant(stored);if(document.version!==pin.documentVersion||rowPin(document,file,stored).rowDigest!==pin.rowDigest)fail(409,'Document access, metadata or storage reference changed during verification. Reload and review the current revision.');return {document,file,storage:stored};}
 function assertRequestCurrent(req){const account=db.prepare('SELECT id,role,active,version FROM users WHERE id=?').get(req.user.id);if(!account?.active||!['admin','staff'].includes(account.role)||account.role!==req.user.role||account.version!==req.documentAccountVersion)fail(401,'Account access changed during upload. Sign in again.');if(req.session?.token_hash&&!db.prepare('SELECT 1 FROM sessions WHERE token_hash=? AND expires>?').get(req.session.token_hash,Date.now()))fail(401,'Upload session is no longer active.');if(!isTenantActive())fail(403,'Tenant access changed during upload.');}
 async function storedBytes(file,stored){const inline=Buffer.from(file.bytes);if(stored){assertTenant(stored);if(stored.sha256!==file.sha256)fail(503,'Private revision checksum reference is inconsistent.');if(inline.length){if(inline.length!==stored.size||digest(inline)!==stored.sha256)fail(503,'Recovered document integrity check failed.');return {bytes:inline,materializedInline:true};}if(!objectStorage)fail(503,'Exact private document storage is not configured.');const bytes=Buffer.from(await objectStorage.get(reference(stored)));if(bytes.length!==stored.size||digest(bytes)!==file.sha256)fail(503,'Private document integrity check failed.');return {bytes,materializedInline:false};}if(JSON.parse(file.metadata).storage?.kind==='object')fail(503,'Private revision reference is missing.');if(!inline.length||digest(inline)!==file.sha256)fail(503,'Document integrity check failed. Ask an administrator to investigate.');return {bytes:inline,materializedInline:false};}
 async function readRevision(documentId,revision,user,{sessionTokenHash=null}={}){const document=find(documentId,user),file=db.prepare('SELECT * FROM document_revisions WHERE document_id=? AND revision=?').get(document.id,revision);if(!file||!mayRead(JSON.parse(file.metadata),user))fail(404,'Document revision not found');const stored=storageRow(document.id,revision),account=db.prepare('SELECT role,active,version FROM users WHERE id=?').get(user.id);if(!account?.active||account.role!==user.role)fail(401,'Document account access is no longer active.');const pin={...rowPin(document,file,stored),accountId:user.id,accountVersion:account.version,accountRole:account.role,sessionTokenHash},verified=await storedBytes(file,stored);assertRevisionCurrent(pin,user);return {...verified,file,document,storage:stored,pin};}
 async function exportStoredRevision(row){const stored=storageRow(row.document_id,row.revision);if(!stored||JSON.stringify(stored)!==JSON.stringify(row))fail(503,'Recovery private revision provenance changed.');const file=db.prepare('SELECT * FROM document_revisions WHERE document_id=? AND revision=?').get(row.document_id,row.revision);if(!file)fail(503,'Recovery document revision is missing.');const verified=await storedBytes(file,stored);if(JSON.stringify(storageRow(row.document_id,row.revision))!==JSON.stringify(stored))fail(503,'Recovery private revision reference changed during verification.');return verified.bytes;}
 const setAttempt=(id,state,stored,errorCode=null)=>db.prepare('UPDATE document_upload_attempts SET state=?,object_version=?,updated_at=?,error_code=? WHERE id=?').run(state,stored?.version||null,new Date().toISOString(),errorCode,id);
 async function stageFile(req,p,file,documentId,revision,sourceVersion){if(!objectStorage)return null;if(!tenantId)fail(503,'Private uploads require an explicit tenant identity.');req.documentAccountVersion=db.prepare('SELECT version FROM users WHERE id=?').get(req.user.id)?.version;if(typeof objectStorage.verifyReadiness!=='function'||(await objectStorage.verifyReadiness({probe:false}))?.verified!==true)fail(503,'Actual private bucket access must be verified before uploads.');const id=randomUUID(),stored=objectStorage.stage({tenantId,documentId,revision,sha256:file.sha256,size:file.bytes.length,attemptId:id}),at=new Date().toISOString();transaction(()=>{assertRequestCurrent(req);db.prepare('INSERT INTO document_upload_attempts VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,documentId,revision,tenantId,p.collection,p.recordId,p.visibility,sourceVersion,stored.provider,stored.bucket,stored.namespace,stored.key,null,file.sha256,file.bytes.length,'Uploading',req.user.id,at,at,null);audit(req.user,'stage_document_upload',p.collection,p.recordId,{documentId,revision,attemptId:id,sha256:file.sha256,size:file.bytes.length});});let uploaded=null;try{if(scanDocument){const scan=await scanDocument({bytes:file.bytes,filename:p.filename,mime:file.mime,sha256:file.sha256,tenantId});if(scan?.status!=='Clean'||scan.sha256!==file.sha256){setAttempt(id,'Quarantined',null,'SCAN_NOT_CLEAN');fail(409,'Upload is quarantined and cannot become document evidence.');}}uploaded=await objectStorage.put(stored,file.bytes,file.mime);const verified=Buffer.from(await objectStorage.get(uploaded));if(verified.length!==file.bytes.length||digest(verified)!==file.sha256)fail(503,'Private upload readback verification failed.');setAttempt(id,'Verified',uploaded);return {id,reference:uploaded};}catch(e){const failed=e.stagedReference;if(!uploaded&&failed?.key===stored.key&&failed?.bucket===stored.bucket&&failed?.provider===stored.provider)uploaded={...stored,version:typeof failed.version==='string'&&failed.version.length>0&&failed.version.length<=1000?failed.version:null};const state=db.prepare('SELECT state FROM document_upload_attempts WHERE id=?').get(id)?.state;if(state!=='Quarantined')setAttempt(id,uploaded&&!uploaded.version?'Orphaned':'Failed',uploaded,e.storageErrorCode||'UPLOAD_NOT_VERIFIED');if(uploaded?.version){try{await objectStorage.deleteStaged(uploaded);}catch{setAttempt(id,'Orphaned',uploaded,'STAGED_CLEANUP_FAILED');}}throw e;}}
 async function rejectStage(staged){if(!staged||db.prepare('SELECT state FROM document_upload_attempts WHERE id=?').get(staged.id)?.state==='Committed')return;setAttempt(staged.id,'Failed',staged.reference,'COMMIT_REJECTED');try{await objectStorage.deleteStaged(staged.reference);}catch{setAttempt(staged.id,'Orphaned',staged.reference,'STAGED_CLEANUP_FAILED');}}
 function addRevision(id,version,p,file,u,at,staged=null,provenance=null){const meta={title:p.title,category:p.category,visibility:p.visibility,status:p.status,evidenceDate:p.evidenceDate,...(provenance?{sourceConversion:provenance}:{}),...(staged?{storage:{kind:'object',state:'Verified',size:file.bytes.length,sha256:file.sha256,encryptionAlgorithm:staged.reference.encryption||null,scan:scanDocument?'Clean':'Format validation only'}}:{})};db.prepare('INSERT INTO document_revisions VALUES(?,?,?,?,?,?,?,?,?)').run(id,version,p.filename,file.mime,staged?Buffer.alloc(0):file.bytes,file.sha256,u.id,at,JSON.stringify(meta));if(staged){const r=staged.reference;db.prepare('INSERT INTO document_revision_storage VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,version,tenantId,r.provider,r.bucket,r.namespace,r.key,r.version,file.sha256,file.bytes.length,at);setAttempt(staged.id,'Committed',r);}}
 // Both ordinary uploads and governed conversion use this exact native validator/writer.
 // Trusted callbacks are synchronous and execute inside the native final transaction.
 function prepareRevision(req,input,{documentId=null}={}){
  const p=z.object({...metadata,...upload,...(documentId?{version:z.number().int().min(1)}:{collection:z.enum(linkedCollections),recordId:z.string().min(1).max(100)})}).strict().parse(input);verifyMetadata(p,req.user);const file=decodeFile(p),initial=documentId?find(documentId,req.user):null;
  if(initial?.version!==undefined&&initial.version!==p.version)fail(409,'Document changed. Reload its history before adding a revision.');if(initial?.archived)fail(409,'Archived documents cannot receive new revisions.');
  const source=get(initial?.collection||p.collection,initial?.record_id||p.recordId);
  return {p,file,initial,source,collection:initial?.collection||p.collection,recordId:initial?.record_id||p.recordId,dependencies:{source,document:initial,revisionMetadata:initial?db.prepare('SELECT revision,filename,mime,sha256,metadata FROM document_revisions WHERE document_id=? ORDER BY revision').all(initial.id):[]}};
 }
 async function writeRevision(req,input,{documentId=null,assertCurrent=()=>{},beforeCommit=()=>{},afterWrite=()=>{},provenance=null}={}){
  let staged=null;try{const prepared=prepareRevision(req,input,{documentId}),{p,file,initial,source,collection,recordId}=prepared,id=initial?.id||randomUUID(),version=initial?initial.version+1:1;assertCurrent();beforeCommit(prepared);
   staged=await stageFile(req,{...p,collection,recordId},file,id,version,source.version);
   return transaction(()=>{assertCurrent();const current=prepareRevision(req,input,{documentId});if(staged){assertRequestCurrent(req);if(current.source.version!==source.version)fail(409,'Linked record changed during upload. Review its current record before attaching evidence.');}beforeCommit(current);const at=new Date().toISOString(),retention=new Date(at);retention.setUTCFullYear(retention.getUTCFullYear()+10);
    if(initial)db.prepare('UPDATE documents SET title=?,category=?,visibility=?,status=?,evidence_date=?,version=?,updated_at=?,retention_until=MAX(retention_until,?) WHERE id=?').run(p.title,p.category,p.visibility,p.status,p.evidenceDate,version,at,retention.toISOString(),id);
    else db.prepare('INSERT INTO documents VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,collection,recordId,p.title,p.category,p.visibility,p.status,p.evidenceDate,version,0,at,at,retention.toISOString());
    addRevision(id,version,p,file,req.user,at,staged,provenance);audit(req.user,initial?'revise_document':'upload_document',collection,recordId,{documentId:id,revision:version,size:file.bytes.length,sha256:file.sha256});
    const document=view(find(id,req.user),req.user);afterWrite({document,revision:version,file,at,prepared:current});assertCurrent();return view(find(id,req.user),req.user);
   });
  }catch(e){await rejectStage(staged);throw e;}
 }

 app.get('/api/documents',(req,res)=>{const q=z.object({collection:z.enum(linkedCollections).optional(),recordId:z.string().min(1).max(100).optional(),archived:z.enum(['true','false']).optional()}).strict().parse(req.query);if(q.recordId&&!q.collection)fail(400,'Select a record collection before its identifier.');if(q.collection&&q.recordId)get(q.collection,q.recordId);const documents=db.prepare('SELECT * FROM documents ORDER BY updated_at DESC,id').all().filter(r=>mayRead(r,req.user)&&(!q.collection||r.collection===q.collection)&&(!q.recordId||r.record_id===q.recordId)&&(q.archived==='true'||!r.archived));res.json({documents:documents.map(r=>view(r,req.user)),limits:{maxBytes:MAX_BYTES,formats:['PDF','PNG','JPEG','TXT','CSV'],retentionYears:10,storage:objectStorage?'Private object revisions':'Local SQLite revisions',scan:scanDocument?'Configured scanner':'Format validation only'},collections:linkedCollections});});
 app.post('/api/documents',csrf,write,async(req,res,next)=>{try{res.status(201).json({document:await writeRevision(req,req.body)});}catch(e){next(e);}});
 app.get('/api/documents/:id',(req,res)=>res.json({document:view(find(req.params.id,req.user),req.user)}));
 app.post('/api/documents/:id/revisions',csrf,write,async(req,res,next)=>{try{res.json({document:await writeRevision(req,req.body,{documentId:req.params.id})});}catch(e){next(e);}});
 app.post('/api/documents/:id/archive',csrf,write,(req,res)=>{const p=z.object({version:z.number().int().min(1),reason:z.string().trim().min(1).max(1000)}).strict().parse(req.body);const document=transaction(()=>{const old=find(req.params.id,req.user);if(old.version!==p.version)fail(409,'Document changed. Reload before archiving.');if(old.archived)fail(409,'Document already archived.');db.prepare('UPDATE documents SET archived=1,version=version+1,updated_at=? WHERE id=?').run(new Date().toISOString(),old.id);audit(req.user,'archive_document',old.collection,old.record_id,{documentId:old.id,reason:p.reason});return view(find(old.id,req.user),req.user);});res.json({document});});
 app.get('/api/documents/:id/revisions/:revision/content',async(req,res,next)=>{try{const n=z.coerce.number().int().min(1).parse(req.params.revision),verified=await readRevision(req.params.id,n,req.user,{sessionTokenHash:req.session?.token_hash});audit(req.user,'download_document',verified.document.collection,verified.document.record_id,{documentId:verified.document.id,revision:n});res.json({filename:verified.file.filename,mime:verified.file.mime,contentBase64:verified.bytes.toString('base64'),sha256:verified.file.sha256});}catch(e){next(e);}});
 app.delete('/api/documents/:id',csrf,admin,(req,res)=>{find(req.params.id,req.user);fail(403,'Document revisions are retained. Archive the document; approved institutional disposal requires a separate controlled retention process.');});
 // Business record deletion cannot orphan retained evidence, including archived documents.
 app.delete('/api/records/:collection/:id',csrf,write,(req,res,next)=>{if(db.prepare('SELECT 1 FROM documents WHERE collection=? AND record_id=?').get(req.params.collection,req.params.id))return res.status(409).json({error:'This record has retained documents and cannot be deleted.'});next();});
 return {readRevision,assertRevisionCurrent,exportStoredRevision,verifyRevisionForEvidence:readRevision,prepareRevision,writeRevision,getDocumentView:(id,user)=>view(find(id,user),user)};
}
