import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';

const MAX_BYTES=1024*1024;
const digest=b=>createHash('sha256').update(b).digest('hex');
const fail=(status,message)=>{const e=new Error(message);e.status=status;throw e;};
const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v,'Use a valid calendar date');
const metadata={title:z.string().trim().min(1).max(250),category:z.enum(['Attachment','Proposal','Agreement','Report']),visibility:z.enum(['Workspace','Administrators']),status:z.enum(['Draft','Final','Submitted']),evidenceDate:day.nullable().default(null)};
const upload={filename:z.string().trim().min(1).max(180).refine(v=>!/[\u0000-\u001f\/\\]/.test(v),'Use a plain filename'),contentBase64:z.string().min(4).max(Math.ceil(MAX_BYTES/3)*4).regex(/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/)};

function decodeFile(p){
 const bytes=Buffer.from(p.contentBase64,'base64');if(!bytes.length||bytes.length>MAX_BYTES||bytes.toString('base64')!==p.contentBase64)fail(400,'File must be valid base64 and no larger than 1 MiB.');
 const extension=p.filename.split('.').at(-1).toLowerCase();let mime;
 if(extension==='pdf'&&bytes.subarray(0,5).toString()==='%PDF-')mime='application/pdf';
 else if(extension==='png'&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))mime='image/png';
 else if(['jpg','jpeg'].includes(extension)&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255)mime='image/jpeg';
 else if(['txt','csv'].includes(extension)&&!bytes.includes(0)&&Buffer.from(bytes.toString('utf8')).equals(bytes))mime=extension==='csv'?'text/csv;charset=utf-8':'text/plain;charset=utf-8';
 if(!mime)fail(400,'Use a valid PDF, PNG, JPEG, UTF-8 TXT or CSV file. Executables, HTML, archives and Office files are not supported.');
 return {bytes,mime,sha256:digest(bytes)};
}

export function installDocumentRoutes(app,{db,list,get,audit,csrf,write,admin,transaction,collections}){
 const linkedCollections=collections.filter(c=>!['evaluations','reportViews','volunteerTime','shiftReservations'].includes(c));
 db.exec(`CREATE TABLE IF NOT EXISTS documents(id TEXT PRIMARY KEY,collection TEXT NOT NULL,record_id TEXT NOT NULL,title TEXT NOT NULL,category TEXT NOT NULL,visibility TEXT NOT NULL,status TEXT NOT NULL,evidence_date TEXT,version INTEGER NOT NULL,archived INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,retention_until TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS document_revisions(document_id TEXT NOT NULL REFERENCES documents(id),revision INTEGER NOT NULL,filename TEXT NOT NULL,mime TEXT NOT NULL,bytes BLOB NOT NULL,sha256 TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL,metadata TEXT NOT NULL,PRIMARY KEY(document_id,revision));
 CREATE TRIGGER IF NOT EXISTS document_revision_no_update BEFORE UPDATE ON document_revisions BEGIN SELECT RAISE(ABORT,'Document revisions are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS document_revision_no_delete BEFORE DELETE ON document_revisions BEGIN SELECT RAISE(ABORT,'Document revisions are retained'); END;`);
 const mayRead=(r,u)=>r.visibility!=='Administrators'||u.role==='admin';
 function find(id,u){const r=db.prepare('SELECT * FROM documents WHERE id=?').get(id);if(!r||!mayRead(r,u))fail(404,'Document not found');return r;}
 const publicRevision=r=>({revision:r.revision,filename:r.filename,mime:r.mime,size:r.size,sha256:r.sha256,actor:r.actor,at:r.at,metadata:JSON.parse(r.metadata)});
 const revisions=(id,user)=>db.prepare('SELECT revision,filename,mime,length(bytes) AS size,sha256,actor,at,metadata FROM document_revisions WHERE document_id=? ORDER BY revision DESC').all(id).filter(r=>mayRead(JSON.parse(r.metadata),user)).map(publicRevision);
 const view=(r,user)=>({id:r.id,collection:r.collection,recordId:r.record_id,title:r.title,category:r.category,visibility:r.visibility,status:r.status,evidenceDate:r.evidence_date,version:r.version,archived:Boolean(r.archived),createdAt:r.created_at,updatedAt:r.updated_at,retentionUntil:r.retention_until,revisions:revisions(r.id,user)});
 function verifyMetadata(p,u){if(p.visibility==='Administrators'&&u.role!=='admin')fail(403,'Only administrators can create or change administrator-only documents.');if(p.status==='Submitted'&&!p.evidenceDate)fail(400,'A submitted document needs its actual submission date.');if(p.evidenceDate&&p.evidenceDate>new Date().toISOString().slice(0,10))fail(400,'Evidence date cannot be in the future.');}
 const addRevision=(id,version,p,file,u,at)=>db.prepare('INSERT INTO document_revisions VALUES(?,?,?,?,?,?,?,?,?)').run(id,version,p.filename,file.mime,file.bytes,file.sha256,u.id,at,JSON.stringify({title:p.title,category:p.category,visibility:p.visibility,status:p.status,evidenceDate:p.evidenceDate}));
 app.get('/api/documents',(req,res)=>{const q=z.object({collection:z.enum(linkedCollections).optional(),recordId:z.string().min(1).max(100).optional(),archived:z.enum(['true','false']).optional()}).strict().parse(req.query);if(q.recordId&&!q.collection)fail(400,'Select a record collection before its identifier.');if(q.collection&&q.recordId)get(q.collection,q.recordId);const documents=db.prepare('SELECT * FROM documents ORDER BY updated_at DESC,id').all().filter(r=>mayRead(r,req.user)&&(!q.collection||r.collection===q.collection)&&(!q.recordId||r.record_id===q.recordId)&&(q.archived==='true'||!r.archived));res.json({documents:documents.map(r=>view(r,req.user)),limits:{maxBytes:MAX_BYTES,formats:['PDF','PNG','JPEG','TXT','CSV'],retentionYears:10},collections:linkedCollections});});
 app.post('/api/documents',csrf,write,(req,res)=>{const p=z.object({...metadata,...upload,collection:z.enum(linkedCollections),recordId:z.string().min(1).max(100)}).strict().parse(req.body);verifyMetadata(p,req.user);const file=decodeFile(p);const document=transaction(()=>{get(p.collection,p.recordId);const id=randomUUID(),at=new Date().toISOString();const retention=new Date(at);retention.setUTCFullYear(retention.getUTCFullYear()+10);db.prepare('INSERT INTO documents VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,p.collection,p.recordId,p.title,p.category,p.visibility,p.status,p.evidenceDate,1,0,at,at,retention.toISOString());addRevision(id,1,p,file,req.user,at);audit(req.user,'upload_document',p.collection,p.recordId,{documentId:id,revision:1,size:file.bytes.length,sha256:file.sha256});return view(find(id,req.user),req.user);});res.status(201).json({document});});
 app.get('/api/documents/:id',(req,res)=>res.json({document:view(find(req.params.id,req.user),req.user)}));
 app.post('/api/documents/:id/revisions',csrf,write,(req,res)=>{const p=z.object({...metadata,...upload,version:z.number().int().min(1)}).strict().parse(req.body);verifyMetadata(p,req.user);const file=decodeFile(p);const document=transaction(()=>{const old=find(req.params.id,req.user);if(old.version!==p.version)fail(409,'Document changed. Reload its history before adding a revision.');if(old.archived)fail(409,'Archived documents cannot receive new revisions.');get(old.collection,old.record_id);const at=new Date().toISOString(),version=old.version+1;const retention=new Date(at);retention.setUTCFullYear(retention.getUTCFullYear()+10);db.prepare('UPDATE documents SET title=?,category=?,visibility=?,status=?,evidence_date=?,version=?,updated_at=?,retention_until=MAX(retention_until,?) WHERE id=?').run(p.title,p.category,p.visibility,p.status,p.evidenceDate,version,at,retention.toISOString(),old.id);addRevision(old.id,version,p,file,req.user,at);audit(req.user,'revise_document',old.collection,old.record_id,{documentId:old.id,revision:version,sha256:file.sha256,size:file.bytes.length});return view(find(old.id,req.user),req.user);});res.json({document});});
 app.post('/api/documents/:id/archive',csrf,write,(req,res)=>{const p=z.object({version:z.number().int().min(1),reason:z.string().trim().min(1).max(1000)}).strict().parse(req.body);const document=transaction(()=>{const old=find(req.params.id,req.user);if(old.version!==p.version)fail(409,'Document changed. Reload before archiving.');if(old.archived)fail(409,'Document already archived.');db.prepare('UPDATE documents SET archived=1,version=version+1,updated_at=? WHERE id=?').run(new Date().toISOString(),old.id);audit(req.user,'archive_document',old.collection,old.record_id,{documentId:old.id,reason:p.reason});return view(find(old.id,req.user),req.user);});res.json({document});});
 app.get('/api/documents/:id/revisions/:revision/content',(req,res)=>{const document=find(req.params.id,req.user);const n=z.coerce.number().int().min(1).parse(req.params.revision);const file=db.prepare('SELECT * FROM document_revisions WHERE document_id=? AND revision=?').get(document.id,n);if(!file||!mayRead(JSON.parse(file.metadata),req.user))fail(404,'Document revision not found');const bytes=Buffer.from(file.bytes);if(digest(bytes)!==file.sha256)fail(503,'Document integrity check failed. Ask an administrator to investigate.');audit(req.user,'download_document',document.collection,document.record_id,{documentId:document.id,revision:n});res.json({filename:file.filename,mime:file.mime,contentBase64:bytes.toString('base64'),sha256:file.sha256});});
 app.delete('/api/documents/:id',csrf,admin,(req,res)=>{find(req.params.id,req.user);fail(403,'Document revisions are retained. Archive the document; approved institutional disposal requires a separate controlled retention process.');});
 // Business record deletion cannot orphan retained evidence, including archived documents.
 app.delete('/api/records/:collection/:id',csrf,write,(req,res,next)=>{if(db.prepare('SELECT 1 FROM documents WHERE collection=? AND record_id=?').get(req.params.collection,req.params.id))return res.status(409).json({error:'This record has retained documents and cannot be deleted.'});next();});
}
