import {createHash,createHmac,randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
import {z} from 'zod';

const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';
const hash=v=>createHash('sha256').update(canonical(v)).digest('hex');
const byteHash=b=>createHash('sha256').update(b).digest('hex');
const name=z.string().trim().min(1).max(100).refine(v=>!/[\u0000-\u001f\u007f]/.test(v),'Source identifiers cannot contain control characters');
const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v,'Use a valid calendar date');
const visibility=z.enum(['Workspace','Administrators']),version=z.number().int().positive(),sha=z.string().regex(/^[a-f0-9]{64}$/);
const requestSchema=z.object({source:z.object({namespace:name,documentId:name,revisionId:name,visibility,originalDate:day.nullable()}).strict(),document:z.object({title:z.string(),category:z.literal('Agreement'),status:z.enum(['Draft','Final','Submitted']),visibility,evidenceDate:day.nullable(),filename:z.string(),contentBase64:z.string(),collection:z.string(),recordId:z.string(),recordVersion:version,targetDocumentId:z.string().uuid().optional(),targetVersion:version.optional()}).strict().refine(v=>Boolean(v.targetDocumentId)===(v.targetVersion!==undefined),'Supply both targetDocumentId and targetVersion for an append'),sha256:sha,size:z.number().int().min(1).max(1024*1024)}).strict();
const scope='One normalized Agreement revision, supported PDF/PNG/JPEG/UTF-8 TXT/CSV bytes only. Original source calendar date is separate from the importing actor/time; no contract execution, external submission, grant completion, source disposal or full historical conversion is asserted.';

export function installDocumentMigrationRoutes(app,{db,documentService,audit,csrf,admin,transaction,tenantId,isTenantActive=()=>true,recheckAccess=()=>false}){
 if(!documentService?.prepareRevision||!documentService?.writeRevision||!tenantId)throw new Error('Document conversion requires the native document writer and explicit tenant identity');
 db.exec(`CREATE TABLE IF NOT EXISTS document_migration_reconciliations(id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,source_namespace TEXT NOT NULL,source_document_id TEXT NOT NULL,source_revision_id TEXT NOT NULL,source_visibility TEXT NOT NULL,original_date TEXT,document_id TEXT NOT NULL,revision INTEGER NOT NULL,collection TEXT NOT NULL,record_id TEXT NOT NULL,record_version INTEGER NOT NULL,requested_document_version INTEGER,source_hash TEXT NOT NULL,native_hash TEXT NOT NULL,filename TEXT NOT NULL,mime TEXT NOT NULL,sha256 TEXT NOT NULL,size INTEGER NOT NULL CHECK(size>0),metadata TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL,UNIQUE(source_namespace,source_document_id,source_revision_id),FOREIGN KEY(document_id,revision) REFERENCES document_revisions(document_id,revision));
 CREATE TABLE IF NOT EXISTS document_migration_mappings(source_namespace TEXT NOT NULL,source_document_id TEXT NOT NULL,source_revision_id TEXT NOT NULL,document_id TEXT NOT NULL,revision INTEGER NOT NULL,reconciliation_id TEXT NOT NULL REFERENCES document_migration_reconciliations(id),source_hash TEXT NOT NULL,native_hash TEXT NOT NULL,PRIMARY KEY(source_namespace,source_document_id,source_revision_id),FOREIGN KEY(document_id,revision) REFERENCES document_revisions(document_id,revision));
 CREATE INDEX IF NOT EXISTS document_migration_history ON document_migration_reconciliations(at DESC,id DESC);
 CREATE TRIGGER IF NOT EXISTS document_migration_mapping_no_update BEFORE UPDATE ON document_migration_mappings BEGIN SELECT RAISE(ABORT,'Imported source mappings are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS document_migration_mapping_no_delete BEFORE DELETE ON document_migration_mappings BEGIN SELECT RAISE(ABORT,'Imported source mappings are retained'); END;
 CREATE TRIGGER IF NOT EXISTS document_migration_reconciliation_no_update BEFORE UPDATE ON document_migration_reconciliations BEGIN SELECT RAISE(ABORT,'Import reconciliation is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS document_migration_reconciliation_no_delete BEFORE DELETE ON document_migration_reconciliations BEGIN SELECT RAISE(ABORT,'Import reconciliation is retained'); END;`);
 const signingKey=randomBytes(32);
 function live(req){if(req.user?.role!=='admin')fail(403,'Administrator access is required for contract conversion');if(!isTenantActive())fail(403,'Workspace is suspended');if(!recheckAccess(req))fail(401,'Account access changed. Sign in again');}
 function authority(req){live(req);const user=db.prepare('SELECT id,role,active,version FROM users WHERE id=?').get(req.user.id),session=db.prepare('SELECT token_hash,user_id,account_binding FROM sessions WHERE token_hash=?').get(req.session?.token_hash);if(!user?.active||user.role!=='admin'||!session||session.user_id!==user.id)fail(401,'Current administrator session required');return {...user,sessionToken:session.token_hash,sessionBinding:session.account_binding,tenantId};}
 function parse(body,commit=false){if(Buffer.byteLength(JSON.stringify(body)||'')>2*1024*1024)fail(413,'One conversion request must not exceed 2 MiB');const p=(commit?requestSchema.extend({proof:sha}):requestSchema).parse(body);if(p.source.originalDate&&p.source.originalDate>new Date().toISOString().slice(0,10))fail(400,'Original source date cannot be in the future');if(p.source.visibility==='Administrators'&&p.document.visibility!=='Administrators')fail(400,'Private source visibility cannot be relaxed');return p;}
 const mappings=s=>db.prepare('SELECT * FROM document_migration_mappings WHERE source_namespace=? AND source_document_id=? ORDER BY source_revision_id').all(s.namespace,s.documentId);
 const mapped=p=>db.prepare('SELECT * FROM document_migration_mappings WHERE source_namespace=? AND source_document_id=? AND source_revision_id=?').get(p.source.namespace,p.source.documentId,p.source.revisionId);
 function reconciliationFor(row){const retained=db.prepare('SELECT * FROM document_migration_reconciliations WHERE id=?').get(row.reconciliation_id);if(!retained||retained.tenant_id!==tenantId||retained.source_namespace!==row.source_namespace||retained.source_document_id!==row.source_document_id||retained.source_revision_id!==row.source_revision_id||retained.document_id!==row.document_id||retained.revision!==row.revision||retained.source_hash!==row.source_hash||retained.native_hash!==row.native_hash)fail(409,'Retained source reconciliation does not match this tenant and mapping');return retained;}
 function nativeRequest(p,{append=true}={}){const {recordVersion,targetDocumentId,targetVersion,...document}=p.document;return append&&targetDocumentId?{title:document.title,category:document.category,status:document.status,visibility:document.visibility,evidenceDate:document.evidenceDate,filename:document.filename,contentBase64:document.contentBase64,version:targetVersion}:document;}
 function normalized(req,p){const prepared=documentService.prepareRevision(req,nativeRequest(p,{append:false}));if(prepared.source.version!==p.document.recordVersion)fail(409,'Linked record changed. Review its current version');if(prepared.file.sha256!==p.sha256||prepared.file.bytes.length!==p.size)fail(400,'Declared file checksum and size must match the exact original bytes');return {prepared,metadata:{title:prepared.p.title,category:prepared.p.category,status:prepared.p.status,visibility:prepared.p.visibility,evidenceDate:prepared.p.evidenceDate},filename:prepared.p.filename};}
 function nativeSnapshot(documentId,revision){const document=db.prepare('SELECT * FROM documents WHERE id=?').get(documentId),file=db.prepare('SELECT * FROM document_revisions WHERE document_id=? AND revision=?').get(documentId,revision);if(!document||!file)fail(409,'Retained native revision is unavailable');return {document,file,nativeHash:hash({documentId,revision,collection:document.collection,recordId:document.record_id,filename:file.filename,mime:file.mime,sha256:file.sha256,metadata:JSON.parse(file.metadata),actor:file.actor,at:file.at,storage:db.prepare('SELECT * FROM document_revision_storage WHERE document_id=? AND revision=?').get(documentId,revision)||null})};}
 function privacy(p,documentId){if(p.document.visibility==='Workspace'&&db.prepare("SELECT 1 FROM documents WHERE id=? AND visibility='Administrators' UNION ALL SELECT 1 FROM document_revisions WHERE document_id=? AND json_extract(metadata,'$.visibility')='Administrators' LIMIT 1").get(documentId,documentId))fail(409,'A retained private document chain cannot be imported with workspace visibility');}
 function dependencies(req,p,norm,old){let target=null;if(old)target=nativeSnapshot(old.document_id,old.revision).document;else if(p.document.targetDocumentId){const prepared=documentService.prepareRevision(req,nativeRequest(p),{documentId:p.document.targetDocumentId});if(prepared.collection!==p.document.collection||prepared.recordId!==p.document.recordId)fail(409,'Append target must have the exact reviewed native link');target=prepared.initial;}const chain=mappings(p.source);for(const row of chain)reconciliationFor(row);if(chain.some(row=>row.document_id!==(old?.document_id||p.document.targetDocumentId)))fail(409,'This source document is already linked. Append to its existing native document explicitly');if(target){if(target.collection!==p.document.collection||target.record_id!==p.document.recordId)fail(409,'Source document link changed');if(p.document.targetDocumentId&&p.document.targetDocumentId!==target.id)fail(409,'Source revision is mapped to another native document');if(!old&&p.document.targetVersion!==undefined&&p.document.targetVersion!==target.version)fail(409,'Document changed. Review its current version');if(!old)privacy(p,target.id);}return {authority:authority(req),source:norm.prepared.source,target,chain,revisionMetadata:target?db.prepare('SELECT revision,filename,mime,sha256,metadata FROM document_revisions WHERE document_id=? ORDER BY revision').all(target.id):[]};}
 const sign=(contentHash,dependencyHash)=>createHmac('sha256',signingKey).update(contentHash+':'+dependencyHash).digest('hex');
 const dto=r=>({id:r.id,tenantId:r.tenant_id,source:{namespace:r.source_namespace,documentId:r.source_document_id,revisionId:r.source_revision_id,visibility:r.source_visibility,originalDate:r.original_date},documentId:r.document_id,revision:r.revision,collection:r.collection,recordId:r.record_id,recordVersion:r.record_version,requestedDocumentVersion:r.requested_document_version,sourceHash:r.source_hash,nativeHash:r.native_hash,file:{filename:r.filename,mime:r.mime,sha256:r.sha256,size:r.size},metadata:JSON.parse(r.metadata),actor:r.actor,at:r.at,reconciliation:{sourceRevisions:1,sourceBytes:r.size,nativeRevisions:1,nativeBytes:r.size}});
 async function plan(req,p){const auth=authority(req),norm=normalized(req,p),contentHash=hash({source:p.source,metadata:norm.metadata,filename:norm.filename,mime:norm.prepared.file.mime,sha256:p.sha256,size:p.size,collection:p.document.collection,recordId:p.document.recordId}),old=mapped(p);let replayPin=null;if(old){reconciliationFor(old);if(old.source_hash!==contentHash)fail(409,'This source document/revision was already imported with different bytes, metadata or link');const verified=await documentService.readRevision(old.document_id,old.revision,req.user,{sessionTokenHash:req.session.token_hash});replayPin=verified.pin;if(verified.file.sha256!==p.sha256||verified.bytes.length!==p.size||byteHash(verified.bytes)!==p.sha256||nativeSnapshot(old.document_id,old.revision).nativeHash!==old.native_hash)fail(409,'Retained native revision no longer matches its source reconciliation');}const deps=dependencies(req,p,normalized(req,p),old);if(hash(auth)!==hash(deps.authority))fail(401,'Administrator access changed during review');const dependencyHash=hash(deps),operation=old?'Replay':p.document.targetDocumentId?'Append':'Create';return {norm,old,replayPin,deps,contentHash,dependencyHash,operation,proof:sign(contentHash,dependencyHash)};}
 function preview(p,review){return {valid:true,operation:review.operation,proof:review.proof,contentHash:review.contentHash,dependencyHash:review.dependencyHash,reconciliation:{sourceRevisions:1,sourceBytes:p.size,nativeRevisions:review.old?0:1,nativeBytes:review.old?0:p.size},target:{collection:p.document.collection,recordId:p.document.recordId,recordVersion:p.document.recordVersion,documentId:review.old?.document_id||p.document.targetDocumentId||null,documentVersion:review.deps.target?.version||null},file:{filename:review.norm.filename,mime:review.norm.prepared.file.mime,sha256:p.sha256,size:p.size},source:p.source,metadata:review.norm.metadata,scope};}
 app.use('/api/document-migration',(req,res,next)=>{try{live(req);next();}catch(e){next(e);}});
 app.post('/api/document-migration/preview',csrf,admin,async(req,res,next)=>{try{const p=parse(req.body),review=await plan(req,p);res.json(preview(p,review));}catch(e){next(e);}});
 app.post('/api/document-migration/commit',csrf,admin,async(req,res,next)=>{try{const p=parse(req.body,true),review=await plan(req,p);if(!timingSafeEqual(Buffer.from(p.proof,'hex'),Buffer.from(review.proof,'hex')))fail(409,'Reviewed conversion changed. Preview the exact source revision again');const assertCurrent=()=>{if(hash(authority(req))!==hash(review.deps.authority))fail(401,'Administrator access changed during import');};const checkDependencies=()=>{const norm=normalized(req,p);if(hash(dependencies(req,p,norm,mapped(p)))!==review.dependencyHash)fail(409,'Reviewed native link, document or source mapping changed during import');};
  if(review.old){const result=transaction(()=>{assertCurrent();checkDependencies();documentService.assertRevisionCurrent(review.replayPin,req.user);if(nativeSnapshot(review.old.document_id,review.old.revision).nativeHash!==review.old.native_hash)fail(409,'Retained native revision changed');const r=db.prepare('SELECT * FROM document_migration_reconciliations WHERE id=?').get(review.old.reconciliation_id);if(!r||r.tenant_id!==tenantId)fail(409,'Source reconciliation is unavailable');return {replayed:true,document:documentService.getDocumentView(r.document_id,req.user),reconciliation:dto(r)};});res.json(result);return;}
  let result;const provenance={namespace:p.source.namespace,sourceDocumentId:p.source.documentId,sourceRevisionId:p.source.revisionId,sourceVisibility:p.source.visibility,originalDate:p.source.originalDate};
  const document=await documentService.writeRevision(req,nativeRequest(p),{documentId:p.document.targetDocumentId||null,assertCurrent,beforeCommit:checkDependencies,provenance,afterWrite:({document,revision,file,at})=>{const id=randomUUID(),snapshot=nativeSnapshot(document.id,revision),expectedMetadata={...review.norm.metadata,sourceConversion:provenance};const verify=()=>{if(hash(normalized(req,p).prepared.source)!==hash(review.deps.source))fail(409,'Linked source changed during native reconciliation');const current=nativeSnapshot(document.id,revision),meta=JSON.parse(current.file.metadata),expectedVersion=(p.document.targetVersion||0)+1;if(current.document.collection!==p.document.collection||current.document.record_id!==p.document.recordId||current.document.version!==expectedVersion||current.document.archived||current.document.title!==review.norm.metadata.title||current.document.category!=='Agreement'||current.document.status!==p.document.status||current.document.visibility!==p.document.visibility||current.document.evidence_date!==p.document.evidenceDate||current.file.filename!==review.norm.filename||current.file.mime!==file.mime||current.file.sha256!==p.sha256||current.file.actor!==req.user.id||current.file.at!==at||hash({...meta,storage:undefined})!==hash({...expectedMetadata,storage:undefined}))fail(409,'Persisted native revision failed exact reconciliation');const stored=db.prepare('SELECT * FROM document_revision_storage WHERE document_id=? AND revision=?').get(document.id,revision);if(stored){if(stored.tenant_id!==tenantId||stored.sha256!==p.sha256||stored.size!==p.size||!stored.object_version)fail(409,'Persisted exact private revision reference failed reconciliation');}else if(Buffer.from(current.file.bytes).length!==p.size||byteHash(Buffer.from(current.file.bytes))!==p.sha256)fail(409,'Persisted native bytes failed reconciliation');return current;};verify();
   db.prepare('INSERT INTO document_migration_reconciliations VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,tenantId,p.source.namespace,p.source.documentId,p.source.revisionId,p.source.visibility,p.source.originalDate,document.id,revision,p.document.collection,p.document.recordId,p.document.recordVersion,p.document.targetVersion||null,review.contentHash,snapshot.nativeHash,review.norm.filename,file.mime,p.sha256,p.size,JSON.stringify(review.norm.metadata),req.user.id,at);
   db.prepare('INSERT INTO document_migration_mappings VALUES(?,?,?,?,?,?,?,?)').run(p.source.namespace,p.source.documentId,p.source.revisionId,document.id,revision,id,review.contentHash,snapshot.nativeHash);audit(req.user,'import_document_revision',p.document.collection,p.document.recordId,{reconciliationId:id,documentId:document.id,revision,sourceNamespace:p.source.namespace,sourceDocumentId:p.source.documentId,sourceRevisionId:p.source.revisionId,sourceHash:review.contentHash,nativeHash:snapshot.nativeHash,sha256:p.sha256,size:p.size});const final=verify();if(final.nativeHash!==snapshot.nativeHash)fail(409,'Native revision changed during source reconciliation');result=dto(db.prepare('SELECT * FROM document_migration_reconciliations WHERE id=?').get(id));
  }});res.status(201).json({replayed:false,document,reconciliation:result});
 }catch(e){next(e);}});
 app.get('/api/document-migration/history',(req,res,next)=>{try{const q=z.object({limit:z.coerce.number().int().min(1).max(100).default(100),after:z.string().uuid().optional()}).strict().parse(req.query);authority(req);const cursor=q.after?db.prepare('SELECT at,id FROM document_migration_reconciliations WHERE id=? AND tenant_id=?').get(q.after,tenantId):null;if(q.after&&!cursor)fail(400,'History cursor is unavailable');const rows=cursor?db.prepare('SELECT * FROM document_migration_reconciliations WHERE tenant_id=? AND (at<? OR (at=? AND id<?)) ORDER BY at DESC,id DESC LIMIT ?').all(tenantId,cursor.at,cursor.at,cursor.id,q.limit+1):db.prepare('SELECT * FROM document_migration_reconciliations WHERE tenant_id=? ORDER BY at DESC,id DESC LIMIT ?').all(tenantId,q.limit+1),more=rows.length>q.limit;res.json({reconciliations:rows.slice(0,q.limit).map(dto),nextCursor:more?rows[q.limit-1].id:null,limit:q.limit,scope});}catch(e){next(e);}});
 return {scope};
}
