import {randomUUID} from 'node:crypto';
import {z} from 'zod';

const fail=(status,message)=>{const e=new Error(message);e.status=status;throw e;};
const id=z.string().min(1).max(100),version=z.number().int().min(1),money=z.number().int().min(1).max(1e12),name=z.string().trim().min(1).max(250),text=z.string().max(8000).default('');
const reason=z.string().trim().min(1).max(2000);
const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v,'Use a valid calendar date');
const benefits=z.array(z.object({name,completed:z.boolean()}).strict()).max(50).refine(items=>new Set(items.map(b=>b.name.toLocaleLowerCase())).size===items.length,'Benefits must be distinct');
const utcDay=()=>new Date().toISOString().slice(0,10),now=()=>new Date().toISOString();
const personTypes=new Set(['Individual','Alumni','Employee']),organizationTypes=new Set(['Business','Foundation','Community partner']);

export function installEventOperationsRoutes(app,{db,list,get,put,audit,csrf,write,admin,transaction}){
 db.exec(`CREATE TABLE IF NOT EXISTS event_seating(id TEXT PRIMARY KEY,event_id TEXT NOT NULL,name TEXT NOT NULL COLLATE NOCASE,seats INTEGER NOT NULL,version INTEGER NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(event_id,name));
 CREATE TABLE IF NOT EXISTS event_seat_assignments(id TEXT PRIMARY KEY,event_id TEXT NOT NULL,table_id TEXT NOT NULL REFERENCES event_seating(id),constituent_id TEXT NOT NULL,seat_number INTEGER NOT NULL,status TEXT NOT NULL,version INTEGER NOT NULL,assigned_at TEXT NOT NULL,cancelled_at TEXT,cancel_reason TEXT);
 CREATE UNIQUE INDEX IF NOT EXISTS event_unique_active_seat ON event_seat_assignments(table_id,seat_number) WHERE status='Assigned';
 CREATE UNIQUE INDEX IF NOT EXISTS event_unique_active_person_seat ON event_seat_assignments(event_id,constituent_id) WHERE status='Assigned';
 CREATE TABLE IF NOT EXISTS event_tickets(id TEXT PRIMARY KEY,event_id TEXT NOT NULL,constituent_id TEXT NOT NULL,price INTEGER NOT NULL,status TEXT NOT NULL,version INTEGER NOT NULL,issued_at TEXT NOT NULL,checked_in_at TEXT,cancelled_at TEXT,cancel_reason TEXT);
 CREATE UNIQUE INDEX IF NOT EXISTS event_unique_active_ticket ON event_tickets(event_id,constituent_id) WHERE status='Issued';
 CREATE TABLE IF NOT EXISTS event_sponsorships(id TEXT PRIMARY KEY,event_id TEXT NOT NULL,sponsor_id TEXT NOT NULL,name TEXT NOT NULL,amount INTEGER NOT NULL,benefits TEXT NOT NULL,version INTEGER NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS event_auction_items(id TEXT PRIMARY KEY,event_id TEXT NOT NULL,name TEXT NOT NULL,starting_bid INTEGER NOT NULL,min_increment INTEGER NOT NULL,description TEXT NOT NULL,status TEXT NOT NULL,winning_bid_id TEXT,version INTEGER NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS event_auction_bids(id TEXT PRIMARY KEY,item_id TEXT NOT NULL REFERENCES event_auction_items(id),bidder_id TEXT NOT NULL,amount INTEGER NOT NULL,at TEXT NOT NULL,actor TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS event_payment_links(id TEXT PRIMARY KEY,owner_type TEXT NOT NULL,owner_id TEXT NOT NULL,gift_id TEXT NOT NULL UNIQUE,revenue_case TEXT NOT NULL,at TEXT NOT NULL,actor TEXT NOT NULL);
 CREATE TRIGGER IF NOT EXISTS event_bid_no_update BEFORE UPDATE ON event_auction_bids BEGIN SELECT RAISE(ABORT,'Auction bids are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS event_bid_no_delete BEFORE DELETE ON event_auction_bids BEGIN SELECT RAISE(ABORT,'Auction bids are retained'); END;
 CREATE TRIGGER IF NOT EXISTS event_payment_no_update BEFORE UPDATE ON event_payment_links BEGIN SELECT RAISE(ABORT,'Payment links are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS event_payment_no_delete BEFORE DELETE ON event_payment_links BEGIN SELECT RAISE(ABORT,'Payment links are retained'); END;`);
 const tableNames={ticket:'event_tickets',sponsorship:'event_sponsorships',auction:'event_auction_items'};
 const find=(table,key)=>{const r=db.prepare('SELECT * FROM '+table+' WHERE id=?').get(key);if(!r)fail(404,'Event operation record not found');return r;};
 const checkVersion=(r,v)=>{if(r.version!==v)fail(409,'Event operation changed. Reload its current version before continuing');};
 const activeConstituent=key=>{const c=get('constituents',key);if(c.mergedInto)fail(409,'Select the surviving constituent');return c;};
 function event(key,v){const r=get('events',key);if(v!==undefined)checkVersion(r,v);if((r.registrations||[]).length>r.capacity)fail(409,'Event registrations exceed capacity; reconcile the event first');return r;}
 function attendee(eventId,key){activeConstituent(key);const e=event(eventId),entry=(e.registrations||[]).find(r=>r.constituentId===key);if(!entry)fail(409,'Register this attendee with the event before assigning seating or issuing a ticket');return {e,entry};}
 const links=(type,key)=>db.prepare('SELECT * FROM event_payment_links WHERE owner_type=? AND owner_id=? ORDER BY at,id').all(type,key);
 function paymentView(r,asOf){const gift=get('gifts',r.gift_id);return {id:r.id,ownerType:r.owner_type,ownerId:r.owner_id,giftId:r.gift_id,revenueCase:r.revenue_case,at:r.at,actor:r.actor,amount:gift.amount,constituentId:gift.constituentId,date:gift.date,type:gift.type,status:gift.status,received:gift.status==='Posted'&&gift.date<=asOf,futureDated:gift.date>asOf};}
 function financial(type,key,amount,asOf){const payments=links(type,key).map(r=>paymentView(r,asOf)),received=payments.filter(p=>p.received).reduce((n,p)=>n+BigInt(p.amount),0n);if(received>BigInt(Number.MAX_SAFE_INTEGER))fail(503,'Received total exceeds safe integer cents');return {payments,received:Number(received),balance:Math.max(0,amount-Number(received)),asOf};}
 const seatingView=r=>({id:r.id,eventId:r.event_id,name:r.name,seats:r.seats,version:r.version,createdAt:r.created_at,updatedAt:r.updated_at});
 const assignmentView=r=>({id:r.id,eventId:r.event_id,tableId:r.table_id,constituentId:r.constituent_id,seatNumber:r.seat_number,status:r.status,version:r.version,assignedAt:r.assigned_at,cancelledAt:r.cancelled_at,cancelReason:r.cancel_reason});
 const ticketView=(r,asOf=utcDay())=>({id:r.id,eventId:r.event_id,constituentId:r.constituent_id,price:r.price,status:r.status,version:r.version,issuedAt:r.issued_at,checkedInAt:r.checked_in_at,checkedIn:Boolean(r.checked_in_at),cancelledAt:r.cancelled_at,cancelReason:r.cancel_reason,...financial('ticket',r.id,r.price,asOf),...(r.status==='Cancelled'?{balance:0}:{})});
 const sponsorshipView=(r,asOf=utcDay())=>({id:r.id,eventId:r.event_id,sponsorId:r.sponsor_id,name:r.name,amount:r.amount,benefits:JSON.parse(r.benefits),version:r.version,createdAt:r.created_at,updatedAt:r.updated_at,...financial('sponsorship',r.id,r.amount,asOf)});
 const bids=key=>db.prepare('SELECT * FROM event_auction_bids WHERE item_id=? ORDER BY amount DESC,at,id').all(key).map(r=>({id:r.id,itemId:r.item_id,bidderId:r.bidder_id,amount:r.amount,at:r.at,actor:r.actor}));
 const auctionView=(r,asOf=utcDay())=>{const history=bids(r.id),winner=history.find(b=>b.id===r.winning_bid_id)||null;return {id:r.id,eventId:r.event_id,name:r.name,startingBid:r.starting_bid,minIncrement:r.min_increment,description:r.description,status:r.status,winningBidId:r.winning_bid_id,winner,bids:history,version:r.version,createdAt:r.created_at,updatedAt:r.updated_at,...financial('auction',r.id,winner?.amount||0,asOf)};};
 function owner(type,key){const r=find(tableNames[type],key);let donor,amount;if(type==='ticket'){if(r.status!=='Issued')fail(409,'Cancelled tickets cannot receive payment links');attendee(r.event_id,r.constituent_id);donor=r.constituent_id;amount=r.price;}else if(type==='sponsorship'){if(!organizationTypes.has(activeConstituent(r.sponsor_id).type))fail(409,'Sponsorship donor must retain organization identity');donor=r.sponsor_id;amount=r.amount;}else{if(r.status!=='Closed'||!r.winning_bid_id)fail(409,'Close the auction with a confirmed winning bid before linking payment');const winner=bids(r.id).find(b=>b.id===r.winning_bid_id);if(!winner)fail(503,'Winning bid history is missing');activeConstituent(winner.bidderId);donor=winner.bidderId;amount=winner.amount;}return {record:r,donor,amount};}
 const current=(type,key)=>{const r=find(tableNames[type],key);return type==='ticket'?ticketView(r):type==='sponsorship'?sponsorshipView(r):auctionView(r);};
 const action=fn=>(req,res,next)=>{try{fn(req,res);}catch(e){next(e);}};
 const prefix='/api/event-operations';
 app.get(prefix,action((req,res)=>{const q=z.object({eventId:id.optional(),asOf:day.optional()}).strict().parse(req.query),asOf=q.asOf||utcDay();if(asOf>utcDay())fail(400,'Received balances require a current or historical as-of date');if(q.eventId)event(q.eventId);const read=table=>db.prepare('SELECT * FROM '+table+(q.eventId?' WHERE event_id=?':'')+' ORDER BY id LIMIT 10001').all(...(q.eventId?[q.eventId]:[]));res.json({asOf,events:list('events').filter(e=>!q.eventId||e.id===q.eventId),seating:read('event_seating').map(seatingView),seatAssignments:read('event_seat_assignments').map(assignmentView),tickets:read('event_tickets').map(r=>ticketView(r,asOf)),sponsorships:read('event_sponsorships').map(r=>sponsorshipView(r,asOf)),auctionItems:read('event_auction_items').map(r=>auctionView(r,asOf)),scope:'Offline staff-entered event operations. Agreements and winning bids are commitments, not received income. Payments reference existing posted gift records; no checkout, collection, tax determination or message delivery occurs.'});}));
 app.post(prefix+'/events/:eventId/seating',csrf,write,action((req,res)=>{const p=z.object({eventVersion:version,name,seats:z.number().int().min(1).max(10000)}).strict().parse(req.body);const seating=transaction(()=>{const e=event(req.params.eventId,p.eventVersion),total=db.prepare('SELECT COALESCE(SUM(seats),0) AS total FROM event_seating WHERE event_id=?').get(e.id).total;if(total+p.seats>e.capacity)fail(409,'Seating inventory cannot exceed event capacity');if(db.prepare('SELECT 1 FROM event_seating WHERE event_id=? AND name=?').get(e.id,p.name))fail(409,'This event already has a table with that name');const key=randomUUID(),at=now();db.prepare('INSERT INTO event_seating VALUES(?,?,?,?,?,?,?)').run(key,e.id,p.name,p.seats,1,at,at);audit(req.user,'create_event_seating','events',e.id,{tableId:key,name:p.name,seats:p.seats});return seatingView(find('event_seating',key));});res.status(201).json({seating});}));
 app.patch(prefix+'/seating/:id',csrf,write,action((req,res)=>{const p=z.object({version,name,seats:z.number().int().min(1).max(10000)}).strict().parse(req.body);const seating=transaction(()=>{const r=find('event_seating',req.params.id);checkVersion(r,p.version);if(db.prepare('SELECT 1 FROM event_seat_assignments WHERE table_id=?').get(r.id))fail(409,'Seating inventory is locked after assignment history; create a new table');const e=event(r.event_id),total=db.prepare('SELECT COALESCE(SUM(seats),0) AS total FROM event_seating WHERE event_id=? AND id<>?').get(e.id,r.id).total;if(total+p.seats>e.capacity)fail(409,'Seating inventory cannot exceed event capacity');if(db.prepare('SELECT 1 FROM event_seating WHERE event_id=? AND name=? AND id<>?').get(e.id,p.name,r.id))fail(409,'Table names must be unique within the event');db.prepare('UPDATE event_seating SET name=?,seats=?,version=version+1,updated_at=? WHERE id=?').run(p.name,p.seats,now(),r.id);audit(req.user,'update_event_seating','events',e.id,{tableId:r.id,name:p.name,seats:p.seats});return seatingView(find('event_seating',r.id));});res.json({seating});}));
 app.post(prefix+'/seating/:id/assign',csrf,write,action((req,res)=>{const p=z.object({tableVersion:version,eventVersion:version,constituentId:id,seatNumber:z.number().int().min(1).max(10000)}).strict().parse(req.body);const assignment=transaction(()=>{const r=find('event_seating',req.params.id);checkVersion(r,p.tableVersion);event(r.event_id,p.eventVersion);attendee(r.event_id,p.constituentId);if(p.seatNumber>r.seats)fail(400,'Choose an available seat within the table inventory');if(db.prepare("SELECT 1 FROM event_seat_assignments WHERE status='Assigned' AND ((table_id=? AND seat_number=?) OR (event_id=? AND constituent_id=?))").get(r.id,p.seatNumber,r.event_id,p.constituentId))fail(409,'That seat or attendee already has an active assignment');const key=randomUUID(),at=now();db.prepare('INSERT INTO event_seat_assignments VALUES(?,?,?,?,?,?,?,?,?,?)').run(key,r.event_id,r.id,p.constituentId,p.seatNumber,'Assigned',1,at,null,null);db.prepare('UPDATE event_seating SET version=version+1,updated_at=? WHERE id=?').run(at,r.id);audit(req.user,'assign_event_seat','events',r.event_id,{assignmentId:key,tableId:r.id,constituentId:p.constituentId,seatNumber:p.seatNumber});return assignmentView(find('event_seat_assignments',key));});res.status(201).json({assignment});}));
 app.post(prefix+'/seat-assignments/:id/cancel',csrf,write,action((req,res)=>{const p=z.object({version,reason}).strict().parse(req.body);const assignment=transaction(()=>{const r=find('event_seat_assignments',req.params.id);checkVersion(r,p.version);if(r.status!=='Assigned')fail(409,'Seat assignment is already cancelled');if(attendee(r.event_id,r.constituent_id).entry.checkedIn)fail(409,'Checked-in seating requires a separate explicit attendance correction policy');const at=now();db.prepare("UPDATE event_seat_assignments SET status='Cancelled',version=version+1,cancelled_at=?,cancel_reason=? WHERE id=?").run(at,p.reason,r.id);db.prepare('UPDATE event_seating SET version=version+1,updated_at=? WHERE id=?').run(at,r.table_id);audit(req.user,'cancel_event_seat','events',r.event_id,{assignmentId:r.id,reason:p.reason});return assignmentView(find('event_seat_assignments',r.id));});res.json({assignment});}));
 app.post(prefix+'/events/:eventId/tickets',csrf,write,action((req,res)=>{const p=z.object({eventVersion:version,constituentId:id}).strict().parse(req.body);const ticket=transaction(()=>{const e=event(req.params.eventId,p.eventVersion),{entry}=attendee(e.id,p.constituentId);if(entry.checkedIn)fail(409,'Already checked-in attendees retain their existing attendance history');if(db.prepare("SELECT 1 FROM event_tickets WHERE event_id=? AND constituent_id=? AND status='Issued'").get(e.id,p.constituentId))fail(409,'This attendee already has an active ticket');const key=randomUUID(),at=now();db.prepare('INSERT INTO event_tickets VALUES(?,?,?,?,?,?,?,?,?,?)').run(key,e.id,p.constituentId,e.ticketPrice||0,'Issued',1,at,null,null,null);audit(req.user,'issue_event_ticket','events',e.id,{ticketId:key,constituentId:p.constituentId,price:e.ticketPrice||0});return ticketView(find('event_tickets',key));});res.status(201).json({ticket});}));
 app.post(prefix+'/tickets/:id/checkin',csrf,write,action((req,res)=>{const p=z.object({version,eventVersion:version}).strict().parse(req.body);const ticket=transaction(()=>{const r=find('event_tickets',req.params.id);checkVersion(r,p.version);const e=event(r.event_id,p.eventVersion),{entry}=attendee(e.id,r.constituent_id);if(r.status!=='Issued'||r.checked_in_at||entry.checkedIn)fail(409,'Only an active, unchecked ticket can check in once');const at=now();put('events',{...e,registrations:e.registrations.map(x=>x.constituentId===r.constituent_id?{...x,checkedIn:true}:x),version:e.version+1,updatedAt:at});db.prepare('UPDATE event_tickets SET checked_in_at=?,version=version+1 WHERE id=?').run(at,r.id);audit(req.user,'checkin_event_ticket','events',e.id,{ticketId:r.id,constituentId:r.constituent_id});return ticketView(find('event_tickets',r.id));});res.json({ticket});}));
 app.post(prefix+'/tickets/:id/cancel',csrf,write,action((req,res)=>{const p=z.object({version,reason}).strict().parse(req.body);const ticket=transaction(()=>{const r=find('event_tickets',req.params.id);checkVersion(r,p.version);if(r.status!=='Issued')fail(409,'Ticket already cancelled');if(ticketView(r).checkedIn||attendee(r.event_id,r.constituent_id).entry.checkedIn)fail(409,'Checked-in ticket history requires a separate explicit attendance correction policy');if(links('ticket',r.id).some(l=>get('gifts',l.gift_id).status==='Posted'))fail(409,'Reconcile or void the linked payment before cancelling a paid ticket');db.prepare("UPDATE event_tickets SET status='Cancelled',version=version+1,cancelled_at=?,cancel_reason=? WHERE id=?").run(now(),p.reason,r.id);audit(req.user,'cancel_event_ticket','events',r.event_id,{ticketId:r.id,reason:p.reason});return ticketView(find('event_tickets',r.id));});res.json({ticket});}));
 app.post(prefix+'/sponsorships',csrf,write,action((req,res)=>{const p=z.object({eventId:id,eventVersion:version,sponsorId:id,name,amount:money,benefits}).strict().parse(req.body);const sponsorship=transaction(()=>{event(p.eventId,p.eventVersion);if(!organizationTypes.has(activeConstituent(p.sponsorId).type))fail(400,'Sponsorship agreements require an organization, foundation or community partner');const key=randomUUID(),at=now();db.prepare('INSERT INTO event_sponsorships VALUES(?,?,?,?,?,?,?,?,?)').run(key,p.eventId,p.sponsorId,p.name,p.amount,JSON.stringify(p.benefits),1,at,at);audit(req.user,'create_event_sponsorship','events',p.eventId,{sponsorshipId:key,sponsorId:p.sponsorId,amount:p.amount,meaning:'Commitment, not received income'});return sponsorshipView(find('event_sponsorships',key));});res.status(201).json({sponsorship});}));
 app.patch(prefix+'/sponsorships/:id',csrf,write,action((req,res)=>{const p=z.object({version,name:name.optional(),sponsorId:id.optional(),amount:money.optional(),benefits:benefits.optional()}).strict().parse(req.body);const sponsorship=transaction(()=>{const r=find('event_sponsorships',req.params.id);checkVersion(r,p.version);if(p.sponsorId&&!organizationTypes.has(activeConstituent(p.sponsorId).type))fail(400,'Select an organization sponsor');if(links('sponsorship',r.id).length&&((p.sponsorId&&p.sponsorId!==r.sponsor_id)||(p.amount!==undefined&&p.amount!==r.amount)))fail(409,'Sponsor and commitment amount are protected after payment-link history');db.prepare('UPDATE event_sponsorships SET name=?,sponsor_id=?,amount=?,benefits=?,version=version+1,updated_at=? WHERE id=?').run(p.name??r.name,p.sponsorId??r.sponsor_id,p.amount??r.amount,p.benefits===undefined?r.benefits:JSON.stringify(p.benefits),now(),r.id);audit(req.user,'update_event_sponsorship','events',r.event_id,{sponsorshipId:r.id,benefits:p.benefits,amount:p.amount??r.amount});return sponsorshipView(find('event_sponsorships',r.id));});res.json({sponsorship});}));
 app.post(prefix+'/auction-items',csrf,write,action((req,res)=>{const p=z.object({eventId:id,eventVersion:version,name,startingBid:money,minIncrement:money,description:text}).strict().parse(req.body);const item=transaction(()=>{event(p.eventId,p.eventVersion);const key=randomUUID(),at=now();db.prepare('INSERT INTO event_auction_items VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(key,p.eventId,p.name,p.startingBid,p.minIncrement,p.description,'Open',null,1,at,at);audit(req.user,'create_event_auction_item','events',p.eventId,{itemId:key,startingBid:p.startingBid,minIncrement:p.minIncrement});return auctionView(find('event_auction_items',key));});res.status(201).json({item});}));
 app.patch(prefix+'/auction-items/:id',csrf,write,action((req,res)=>{const p=z.object({version,name,startingBid:money,minIncrement:money,description:text}).strict().parse(req.body);const item=transaction(()=>{const r=find('event_auction_items',req.params.id);checkVersion(r,p.version);if(r.status!=='Open'||bids(r.id).length)fail(409,'Auction inventory terms are locked after bids or closure');db.prepare('UPDATE event_auction_items SET name=?,starting_bid=?,min_increment=?,description=?,version=version+1,updated_at=? WHERE id=?').run(p.name,p.startingBid,p.minIncrement,p.description,now(),r.id);audit(req.user,'update_event_auction_item','events',r.event_id,{itemId:r.id});return auctionView(find('event_auction_items',r.id));});res.json({item});}));
 app.post(prefix+'/auction-items/:id/bids',csrf,write,action((req,res)=>{const p=z.object({version,bidderId:id,amount:money}).strict().parse(req.body);const item=transaction(()=>{const r=find('event_auction_items',req.params.id);checkVersion(r,p.version);if(r.status!=='Open')fail(409,'Closed auctions cannot accept bids');activeConstituent(p.bidderId);const high=bids(r.id)[0];if(p.amount<(high?high.amount+r.min_increment:r.starting_bid))fail(400,'Bid must meet the starting amount and then exceed the highest bid by the minimum increment');const key=randomUUID(),at=now();db.prepare('INSERT INTO event_auction_bids VALUES(?,?,?,?,?,?)').run(key,r.id,p.bidderId,p.amount,at,req.user.id);db.prepare('UPDATE event_auction_items SET version=version+1,updated_at=? WHERE id=?').run(at,r.id);audit(req.user,'record_event_auction_bid','events',r.event_id,{itemId:r.id,bidId:key,bidderId:p.bidderId,amount:p.amount});return auctionView(find('event_auction_items',r.id));});res.status(201).json({item});}));
 app.post(prefix+'/auction-items/:id/close',csrf,write,action((req,res)=>{const p=z.object({version,winningBidId:id,confirmed:z.literal(true)}).strict().parse(req.body);const item=transaction(()=>{const r=find('event_auction_items',req.params.id);checkVersion(r,p.version);if(r.status!=='Open')fail(409,'Auction already closed');const high=bids(r.id)[0];if(!high||high.id!==p.winningBidId)fail(409,'Confirm the current highest bid as the winner');db.prepare("UPDATE event_auction_items SET status='Closed',winning_bid_id=?,version=version+1,updated_at=? WHERE id=?").run(high.id,now(),r.id);audit(req.user,'close_event_auction','events',r.event_id,{itemId:r.id,winningBidId:high.id,bidderId:high.bidderId,amount:high.amount,meaning:'Winning commitment, not received income'});return auctionView(find('event_auction_items',r.id));});res.json({item});}));
 app.post(prefix+'/payments',csrf,write,action((req,res)=>{const p=z.object({ownerType:z.enum(['ticket','sponsorship','auction']),ownerId:id,version,giftId:id,giftVersion:version,revenueCase:z.enum(['Fee payment','Cash','Sponsorship'])}).strict().parse(req.body);const record=transaction(()=>{const o=owner(p.ownerType,p.ownerId);checkVersion(o.record,p.version);const gift=get('gifts',p.giftId);checkVersion(gift,p.giftVersion);if(gift.status!=='Posted')fail(409,'Link only an actual posted gift record');if(gift.pledgeId||gift.grantId||gift.giftKind!=='One-time')fail(409,'Use a one-time receipt with no pledge, grant, planned, recurring or matching association');if(!Number.isSafeInteger(gift.amount)||gift.amount<1)fail(503,'Recorded payment must retain positive exact integer cents');if(gift.constituentId!==o.donor)fail(400,'Payment donor must match the attendee, sponsor or winning buyer');if(p.ownerType==='sponsorship'?(p.revenueCase!=='Sponsorship'||gift.type!=='Sponsorship'):(!['Fee payment','Cash'].includes(p.revenueCase)||gift.type!==p.revenueCase))fail(400,'Choose the actual recorded revenue case; it must match the posted gift type');if(db.prepare('SELECT 1 FROM event_payment_links WHERE gift_id=?').get(gift.id))fail(409,'This gift is already linked to an event payment; it cannot be counted twice');const attached=links(p.ownerType,p.ownerId).filter(l=>get('gifts',l.gift_id).status==='Posted').reduce((n,l)=>n+BigInt(get('gifts',l.gift_id).amount),0n);if(p.ownerType==='sponsorship'){if(attached+BigInt(gift.amount)>BigInt(o.amount))fail(409,'Linked receipt would exceed the sponsorship commitment');}else if(attached>0n||gift.amount!==o.amount)fail(409,'Use one existing payment record with the exact ticket price or winning amount');const key=randomUUID(),at=now();db.prepare('INSERT INTO event_payment_links VALUES(?,?,?,?,?,?,?)').run(key,p.ownerType,p.ownerId,gift.id,p.revenueCase,at,req.user.id);if(p.ownerType==='ticket')db.prepare('UPDATE event_tickets SET version=version+1 WHERE id=?').run(p.ownerId);else db.prepare('UPDATE '+tableNames[p.ownerType]+' SET version=version+1,updated_at=? WHERE id=?').run(at,p.ownerId);audit(req.user,'link_event_payment','events',o.record.event_id,{paymentLinkId:key,ownerType:p.ownerType,ownerId:p.ownerId,giftId:gift.id,revenueCase:p.revenueCase,amount:gift.amount,meaning:'Existing recorded revenue; no new gift created or tax treatment determined'});return current(p.ownerType,p.ownerId);});res.status(201).json({record});}));
 app.delete(prefix+'/:kind/:id',csrf,admin,action((req,res)=>{const tables={seating:'event_seating','seat-assignments':'event_seat_assignments',tickets:'event_tickets',sponsorships:'event_sponsorships','auction-items':'event_auction_items'};if(!tables[req.params.kind])fail(404,'Event operation not found');find(tables[req.params.kind],req.params.id);fail(403,'Event operational history is retained; use a controlled cancellation where supported');}));
 const hasConstituentReferences=key=>Boolean(db.prepare('SELECT 1 FROM event_seat_assignments WHERE constituent_id=? UNION ALL SELECT 1 FROM event_tickets WHERE constituent_id=? UNION ALL SELECT 1 FROM event_sponsorships WHERE sponsor_id=? UNION ALL SELECT 1 FROM event_auction_bids WHERE bidder_id=? LIMIT 1').get(key,key,key,key));
 function validateDeletion(collection,previous){
  if(!previous)return;
  const key=previous.id,referenced=collection==='constituents'?hasConstituentReferences(key):collection==='gifts'?Boolean(db.prepare('SELECT 1 FROM event_payment_links WHERE gift_id=?').get(key)):collection==='events'?Boolean(db.prepare('SELECT 1 FROM event_seating WHERE event_id=? UNION ALL SELECT 1 FROM event_tickets WHERE event_id=? UNION ALL SELECT 1 FROM event_sponsorships WHERE event_id=? UNION ALL SELECT 1 FROM event_auction_items WHERE event_id=? LIMIT 1').get(key,key,key,key)):false;
  if(referenced)fail(409,'This record has retained event operational references and cannot be deleted');
 }
 function validateMutation(collection,previous,next){
  if(!previous)return;
  const key=previous.id;
  if(collection==='gifts'&&db.prepare('SELECT 1 FROM event_payment_links WHERE gift_id=?').get(key)&&['constituentId','amount','type','giftKind','pledgeId','grantId'].some(k=>(next[k]??null)!==(previous[k]??null)))fail(409,'Linked event payment donor, amount, revenue type and commitment classification are protected; void and reconcile separately');
  if(collection==='constituents'&&!organizationTypes.has(next.type)&&db.prepare('SELECT 1 FROM event_sponsorships WHERE sponsor_id=?').get(key))fail(409,'A retained sponsorship donor must remain an organization, foundation or community partner');
  if(collection==='events'){
   const seats=db.prepare('SELECT COALESCE(SUM(seats),0) AS n FROM event_seating WHERE event_id=?').get(key).n;
   if(next.capacity<seats)fail(409,'Capacity cannot be below retained seating inventory');
   if(next.ticketPrice!==previous.ticketPrice&&db.prepare('SELECT 1 FROM event_tickets WHERE event_id=?').get(key))fail(409,'Event ticket price is protected after ticket history');
   const removed=(previous.registrations||[]).filter(r=>!(next.registrations||[]).some(n=>n.constituentId===r.constituentId));
   for(const registration of removed)if(db.prepare("SELECT 1 FROM event_tickets WHERE event_id=? AND constituent_id=? AND status='Issued' UNION ALL SELECT 1 FROM event_seat_assignments WHERE event_id=? AND constituent_id=? AND status='Assigned' LIMIT 1").get(key,registration.constituentId,key,registration.constituentId))fail(409,'Cancel active tickets and seating assignments before removing an event registration; checked-in history requires an explicit attendance correction policy');
  }
 }
 // Express decodes each route parameter once, exactly as the core routes do.
 // Route-specific guards and core persistence hooks share the same validation.
 app.delete('/api/records/:collection/:id',csrf,write,(req,res,next)=>{try{validateDeletion(req.params.collection,get(req.params.collection,req.params.id));next();}catch(e){next(e);}});
 app.patch('/api/records/:collection/:id',csrf,write,(req,res,next)=>{try{const previous=get(req.params.collection,req.params.id);validateMutation(req.params.collection,previous,{...previous,...req.body});next();}catch(e){next(e);}});
 app.post('/api/events/:eventId/checkin',csrf,write,(req,res,next)=>{try{const body=z.object({constituentId:id}).strict().parse(req.body);if(db.prepare('SELECT 1 FROM event_tickets WHERE event_id=? AND constituent_id=?').get(req.params.eventId,body.constituentId))fail(409,'Use the issued ticket check-in; cancelled ticket history cannot be bypassed');next();}catch(e){next(e);}});
 return {hasConstituentReferences,validateMutation,validateDeletion};
}
