import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {today} from '../src/lib.js';
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const id=z.string().min(1).max(100),amount=z.number().int().min(1).max(1e12),version=z.number().int().min(1),text=z.string().max(8000).default('');
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v,'Invalid calendar date');
const common={name:z.string().trim().min(1).max(250),campaignId:id.nullable().default(null),notes:text};
const shapes={
 major:{...common,kind:z.literal('major'),donorId:id,ownerId:id,stage:z.enum(['Prospect','Cultivation','Asked','Committed','Declined','Closed']),expectedAmount:amount,nextActionDate:date.nullable().default(null)},
 planned:{...common,kind:z.literal('planned'),donorId:id,instrument:z.enum(['Bequest','Beneficiary designation','Trust','Annuity','Other']),commitmentAmount:amount,status:z.enum(['Documented','Confirmed','Cancelled'])},
 matching:{...common,kind:z.literal('matching'),originalGiftId:id,originalGiftVersion:version,matchingOrganizationId:id,ratioNumerator:z.number().int().min(1).max(1000),ratioDenominator:z.number().int().min(1).max(1000),capAmount:z.number().int().min(0).max(1e12).nullable().default(null),status:z.enum(['Eligible','Submitted','Approved','Declined','Cancelled'])}
};
const reason=z.string().trim().min(1).max(2000);
const parse=(body,editing=false)=>{const shape=shapes[body?.kind];if(!shape)fail(400,'Choose major, planned or matching tracking.');return z.object({...shape,...(editing?{version,transitionReason:reason.optional()}:{})}).strict().parse(body);};
const safeTotal=values=>{let sum=0n;for(const value of values){if(!Number.isSafeInteger(value)||value<0)fail(409,'A linked gift has unsafe monetary cents.');sum+=BigInt(value);}if(sum>BigInt(Number.MAX_SAFE_INTEGER))fail(409,'Linked receipts exceed safe integer cents.');return Number(sum);};
const organizationTypes=new Set(['Business','Foundation','Community partner']);
export function installFundraisingRoutes(app,{db,list,get,getSettings,audit,csrf,write,admin,transaction}){
 db.exec(`CREATE TABLE IF NOT EXISTS fundraising_records(id TEXT PRIMARY KEY,version INTEGER NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS fundraising_associations(id TEXT PRIMARY KEY,record_id TEXT NOT NULL,gift_id TEXT NOT NULL,version INTEGER NOT NULL,status TEXT NOT NULL,gift_version INTEGER NOT NULL,snapshot TEXT NOT NULL,created_at TEXT NOT NULL,unlinked_at TEXT,unlink_reason TEXT);
 CREATE UNIQUE INDEX IF NOT EXISTS fundraising_one_active_receipt ON fundraising_associations(gift_id) WHERE status='active';
 CREATE TABLE IF NOT EXISTS fundraising_versions(record_id TEXT NOT NULL,version INTEGER NOT NULL,data TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL,PRIMARY KEY(record_id,version));
 CREATE TRIGGER IF NOT EXISTS fundraising_versions_no_update BEFORE UPDATE ON fundraising_versions BEGIN SELECT RAISE(ABORT,'Fundraising versions are retained'); END;
 CREATE TRIGGER IF NOT EXISTS fundraising_versions_no_delete BEFORE DELETE ON fundraising_versions BEGIN SELECT RAISE(ABORT,'Fundraising versions are retained'); END;
 CREATE TABLE IF NOT EXISTS fundraising_activity(id TEXT PRIMARY KEY,record_id TEXT NOT NULL,actor TEXT NOT NULL,date TEXT NOT NULL,note TEXT NOT NULL,action TEXT NOT NULL,at TEXT NOT NULL);
 CREATE TRIGGER IF NOT EXISTS fundraising_activity_no_update BEFORE UPDATE ON fundraising_activity BEGIN SELECT RAISE(ABORT,'Fundraising history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS fundraising_activity_no_delete BEFORE DELETE ON fundraising_activity BEGIN SELECT RAISE(ABORT,'Fundraising history is retained'); END;`);
 const authorized=user=>{if(!user)fail(401,'Authentication required');if(!['admin','staff','viewer'].includes(user.role))fail(403,'Your role cannot access fundraising tracking');};
 const person=key=>{const p=get('constituents',key);if(p.mergedInto)fail(409,'Use the surviving constituent');return p;};
 const base=key=>{const r=db.prepare('SELECT * FROM fundraising_records WHERE id=?').get(key);if(!r)fail(404,'Fundraising record not found');return {id:r.id,version:r.version,...JSON.parse(r.data),createdAt:r.created_at,updatedAt:r.updated_at};};
 const associations=key=>db.prepare('SELECT * FROM fundraising_associations WHERE record_id=? ORDER BY created_at,id').all(key).map(r=>({id:r.id,recordId:r.record_id,giftId:r.gift_id,version:r.version,status:r.status,giftVersion:r.gift_version,snapshot:JSON.parse(r.snapshot),createdAt:r.created_at,unlinkedAt:r.unlinked_at,unlinkReason:r.unlink_reason}));
 const originalEligible=(g,asOf)=>g.status==='Posted'&&!['In-kind','Fee payment'].includes(g.type)&&g.method!=='In-kind'&&g.giftKind!=='Matching gift'&&g.date<=asOf;
 const claimMaximum=(record,original)=>{safeTotal([original.amount]);const product=BigInt(original.amount)*BigInt(record.ratioNumerator),denominator=BigInt(record.ratioDenominator);let result=product/denominator;if(record.capAmount!==null)result=result<BigInt(record.capAmount)?result:BigInt(record.capAmount);if(result>BigInt(Number.MAX_SAFE_INTEGER))fail(400,'Matching claim exceeds safe integer cents');return {maximum:Number(result),roundingRemainder:Number(product%denominator)};};
 const target=(record,asOf)=>{if(record.kind==='major')return {amount:record.expectedAmount,eligible:true};if(record.kind==='planned')return {amount:record.commitmentAmount,eligible:record.status!=='Cancelled'};const original=get('gifts',record.originalGiftId);const max=claimMaximum(record,original),eligible=originalEligible(original,asOf);return {amount:eligible?max.maximum:0,eligible,roundingRemainder:max.roundingRemainder};};
 const compatible=(record,gift)=>{const donor=record.kind==='matching'?record.matchingOrganizationId:record.donorId;if(gift.constituentId!==donor)fail(400,'The receipt donor must match the planned donor or matching organization');if(gift.type!=='Cash'||gift.method==='In-kind'||gift.giftKind!==(record.kind==='major'?'One-time':record.kind==='planned'?'Planned gift':'Matching gift'))fail(400,'Use a posted cash gift classified One-time for a major ask, Planned gift for a planned commitment, or Matching gift for a matching claim');if((gift.campaignId??null)!==record.campaignId)fail(400,'The receipt campaign must match the tracked commitment');if(gift.pledgeId||gift.grantId)fail(409,'A pledge or grant receipt cannot also fulfill this commitment');};
 const followupState=r=>r.kind!=='major'?null:!r.nextActionDate?'None':r.nextActionStatus||'Open';
 const view=(key,asOf=today())=>{const r=base(key),links=associations(key),t=target(r,asOf),active=links.filter(a=>a.status==='active'),receipts=active.map(a=>{const g=get('gifts',a.giftId);return {...a,posted:g.status==='Posted',future:g.date>asOf,amount:g.amount,date:g.date};}),received=safeTotal(receipts.filter(a=>a.posted&&!a.future).map(a=>a.amount)),remaining=Math.max(0,t.amount-received);return {...r,associations:receipts.concat(links.filter(a=>a.status!=='active')),activity:db.prepare('SELECT id,actor,date,note,action,at FROM fundraising_activity WHERE record_id=? ORDER BY at,id').all(key),targetAmount:t.amount,receivedAmount:received,outstandingAmount:r.kind==='major'||r.status==='Cancelled'||r.status==='Declined'?0:remaining,originalEligible:t.eligible,roundingRemainder:t.roundingRemainder||0,reconciliationRequired:received>t.amount||!t.eligible&&active.length>0,nextActionStatus:followupState(r),nextActionOverdue:r.kind==='major'&&followupState(r)==='Open'&&r.nextActionDate<asOf,completion:r.kind==='major'?`${r.stage} · ${received>0?'Posted gift associated':'No posted receipt'}`:received>=t.amount&&t.amount>0?'Realized':received>0?'Partially realized':'No posted receipt',asOf};};
 const validate=(p,old=null)=>{if(p.campaignId)get('campaigns',p.campaignId);if(p.kind!=='matching')person(p.donorId);if(p.kind==='major'){const owner=db.prepare('SELECT * FROM users WHERE id=?').get(p.ownerId);if(!owner?.active||!['admin','staff'].includes(owner.role))fail(400,'Choose an active staff or administrator owner');if(!old)p={...p,nextActionStatus:!p.nextActionDate?'None':['Declined','Closed'].includes(p.stage)?'Cancelled':'Open'};}if(p.kind==='matching'){const organization=person(p.matchingOrganizationId),original=get('gifts',p.originalGiftId);person(original.constituentId);if(!organizationTypes.has(organization.type))fail(400,'Choose a business, foundation or community partner as matching organization');if(original.constituentId===p.matchingOrganizationId)fail(400,'Original donor and matching organization must remain separate');if(original.version!==p.originalGiftVersion)fail(409,'Original gift changed. Reload before saving');if((original.campaignId??null)!==p.campaignId)fail(400,'The claim campaign must match the original gift');if((!old||old.originalGiftId!==p.originalGiftId)&&!originalEligible(original,today()))fail(400,'The original gift must be posted monetary support, not a fee, matching payment, void or future gift');claimMaximum(p,original);p={...p,donorId:original.constituentId,originalSnapshot:{id:original.id,version:original.version,constituentId:original.constituentId,amount:original.amount,campaignId:original.campaignId??null,date:original.date,type:original.type,status:original.status}};}if(old){if(old.kind!==p.kind)fail(400,'Tracking kind cannot change');const links=associations(old.id).filter(a=>a.status==='active');for(const a of links)compatible(p,get('gifts',a.giftId));const linked=safeTotal(links.map(a=>get('gifts',a.giftId)).filter(g=>g.status==='Posted'&&g.date<=today()).map(g=>g.amount));if(links.length&&p.kind==='matching'&&old.originalGiftId!==p.originalGiftId)fail(409,'Unlink receipts with a reason before replacing the original gift');if(p.kind!=='major'&&linked>target(p,today()).amount&&target(p,today()).eligible)fail(409,'The revised commitment is below its associated receipt value');}return p;};
 const bump=(old,data)=>{const {id,version,createdAt,updatedAt,...body}=data,at=new Date().toISOString();db.prepare('UPDATE fundraising_records SET version=version+1,data=?,updated_at=? WHERE id=? AND version=?').run(JSON.stringify(body),at,old.id,old.version);return base(old.id);};
 const checkVersion=(r,v)=>{if(r.version!==v)fail(409,'This fundraising record changed. Reload before continuing');};
 const activity=(r,user,action,note,dateValue=today())=>{const at=new Date().toISOString();db.prepare('INSERT INTO fundraising_versions VALUES(?,?,?,?,?)').run(r.id,r.version,JSON.stringify(r),user.id,at);db.prepare('INSERT INTO fundraising_activity VALUES(?,?,?,?,?,?,?)').run(randomUUID(),r.id,user.id,dateValue,note,action,at);audit(user,action,'fundraising',r.id,{version:r.version});};
 const handler=fn=>(req,res,next)=>{try{authorized(req.user);fn(req,res);}catch(e){next(e);}};
 app.get('/api/fundraising',handler((req,res)=>{const asOf=req.query.asOf===undefined?today():date.parse(req.query.asOf);res.json({owners:db.prepare("SELECT id,name FROM users WHERE active=1 AND role IN ('admin','staff') ORDER BY name,id").all(),records:db.prepare('SELECT id FROM fundraising_records ORDER BY updated_at DESC,id').all().map(r=>view(r.id,asOf)),scope:'Manual fundraising tracking. Asks, planned commitments and matching claims are not income. Major asks accept explicit references to existing One-time cash gifts only after a reasoned Committed stage. Next actions are tracked here with explicit completion or rescheduling, not delivered reminders. Only existing posted cash receipts count as realizations; voided and future receipts are excluded. Matching ratio fractional cents are rounded down before the cap. No payments are collected or gift ledger entries created.'});}));
 app.post('/api/fundraising',csrf,write,handler((req,res)=>{const r=transaction(()=>{const p=validate(parse(req.body)),id=randomUUID(),at=new Date().toISOString();db.prepare('INSERT INTO fundraising_records VALUES(?,1,?,?,?)').run(id,JSON.stringify(p),at,at);const r=base(id);activity(r,req.user,'create_fundraising','Tracking record created');return view(id);});res.status(201).json({record:r});}));
 app.patch('/api/fundraising/:id',csrf,write,handler((req,res)=>{res.json({record:transaction(()=>{const old=base(req.params.id),{version,transitionReason,...body}=parse(req.body,true);checkVersion(old,version);const changes=old.kind==='major'&&(old.stage!==body.stage||(old.nextActionDate??null)!==body.nextActionDate);if(changes&&!transitionReason)fail(400,'Explain the stage or next-action change before saving');let p=validate(body,old);if(p.kind==='major'){const changedDate=(old.nextActionDate??null)!==p.nextActionDate;p={...p,...(old.latestFollowup?{latestFollowup:old.latestFollowup}:{}),nextActionStatus:!p.nextActionDate?'None':['Declined','Closed'].includes(p.stage)?'Cancelled':changedDate?'Open':followupState(old)};if(['Declined','Closed'].includes(old.stage)&&!['Declined','Closed'].includes(p.stage)&&p.nextActionDate)p.nextActionStatus='Open';}const r=bump(old,p);activity(r,req.user,changes?'transition_major_ask':'update_fundraising',changes?`${old.stage} → ${r.stage}; next action ${old.nextActionDate||'none'} → ${r.nextActionDate||'none'}. Reason: ${transitionReason}`:'Tracking details updated');return view(r.id);})});}));
 app.post('/api/fundraising/:id/activity',csrf,write,handler((req,res)=>{const p=z.object({version,date,note:z.string().trim().min(1).max(8000)}).strict().parse(req.body);res.json({record:transaction(()=>{const old=base(req.params.id);checkVersion(old,p.version);const r=bump(old,old);activity(r,req.user,'log_fundraising_activity',p.note,p.date);return view(r.id);})});}));
 app.post('/api/fundraising/:id/follow-up',csrf,write,handler((req,res)=>{const p=z.object({version,date,note:z.string().trim().min(1).max(8000),outcome:z.enum(['Completed','Cancelled','Rescheduled']),nextActionDate:date.nullable().default(null),reason}).strict().parse(req.body);res.json({record:transaction(()=>{const old=base(req.params.id);checkVersion(old,p.version);if(old.kind!=='major')fail(400,'Follow-up disposition is for major asks');if(['Declined','Closed'].includes(old.stage))fail(409,'Reopen the ask with a reason before recording another follow-up');if(followupState(old)!=='Open')fail(409,'No open next action remains. Schedule a new action with a reason first');if(p.date>today())fail(400,'An actual follow-up cannot be recorded in the future');if(p.nextActionDate&&p.nextActionDate<p.date)fail(400,'The next action must not precede the recorded follow-up');if(p.outcome==='Rescheduled'&&!p.nextActionDate)fail(400,'Choose the rescheduled next action date');if(p.outcome==='Rescheduled'&&p.nextActionDate===old.nextActionDate)fail(400,'A rescheduled action needs a different due date');if(p.outcome==='Cancelled'&&p.nextActionDate)fail(400,'A cancelled action cannot schedule another action in the same disposition');const r=bump(old,{...old,nextActionDate:p.nextActionDate||old.nextActionDate,nextActionStatus:p.nextActionDate?'Open':p.outcome,latestFollowup:{date:p.date,outcome:p.outcome,note:p.note,reason:p.reason,previousDueDate:old.nextActionDate,nextActionDate:p.nextActionDate,actor:req.user.id}});activity(r,req.user,'record_major_followup',`${p.outcome}: ${p.note}. Reason: ${p.reason}; previous due ${old.nextActionDate}; next due ${p.nextActionDate||'none'}`,p.date);return view(r.id);})});}));
 app.post('/api/fundraising/:id/receipts',csrf,write,handler((req,res)=>{const p=z.object({version,giftId:id,giftVersion:version}).strict().parse(req.body);res.json({record:transaction(()=>{const old=base(req.params.id);checkVersion(old,p.version);if(old.kind==='major'&&old.stage!=='Committed')fail(409,'Move a major ask to Committed with a reason before linking an existing gift');if(['Cancelled','Declined'].includes(old.status))fail(409,'Cancelled or declined commitments cannot receive associations');const gift=get('gifts',p.giftId);if(gift.version!==p.giftVersion)fail(409,'Gift changed. Reload before associating');compatible(old,gift);if(gift.status!=='Posted'||gift.date>today())fail(400,'Associate only a posted receipt dated no later than today');if(db.prepare("SELECT 1 FROM fundraising_associations WHERE gift_id=? AND status='active'").get(gift.id))fail(409,'This gift already fulfills a fundraising commitment');const existing=associations(old.id).filter(a=>a.status==='active').map(a=>get('gifts',a.giftId)).filter(g=>g.status==='Posted'),t=target(old,today());if(!t.eligible)fail(409,'The original matching gift is not eligible');if(old.kind!=='major'&&safeTotal([...existing.map(g=>g.amount),gift.amount])>t.amount)fail(409,'This receipt exceeds the unfulfilled commitment or matching maximum');const at=new Date().toISOString(),associationId=randomUUID(),snapshot={constituentId:gift.constituentId,amount:gift.amount,type:gift.type,giftKind:gift.giftKind,campaignId:gift.campaignId??null,date:gift.date};db.prepare('INSERT INTO fundraising_associations VALUES(?,?,?,1,\'active\',?,?,?,NULL,NULL)').run(associationId,old.id,gift.id,gift.version,JSON.stringify(snapshot),at);const r=bump(old,old);activity(r,req.user,'associate_fundraising_receipt',`Associated receipt ${gift.id}`);audit(req.user,'associate_fundraising_receipt','gifts',gift.id,{fundraisingId:old.id,associationId,giftVersion:gift.version});return view(r.id);})});}));
 app.post('/api/fundraising/:id/receipts/:associationId/unlink',csrf,write,handler((req,res)=>{const p=z.object({version,associationVersion:version,reason:z.string().trim().min(1).max(2000)}).strict().parse(req.body);res.json({record:transaction(()=>{const old=base(req.params.id);checkVersion(old,p.version);const a=associations(old.id).find(a=>a.id===req.params.associationId);if(!a)fail(404,'Receipt association not found');if(a.version!==p.associationVersion||a.status!=='active')fail(409,'Association changed. Reload before unlinking');db.prepare("UPDATE fundraising_associations SET status='unlinked',version=version+1,unlinked_at=?,unlink_reason=? WHERE id=?").run(new Date().toISOString(),p.reason,a.id);const r=bump(old,old);activity(r,req.user,'unlink_fundraising_receipt',p.reason);audit(req.user,'unlink_fundraising_receipt','gifts',a.giftId,{fundraisingId:r.id,associationId:a.id,reason:p.reason});return view(r.id);})});}));
 const referencedIdentity=key=>db.prepare('SELECT data FROM fundraising_records').all().some(r=>{const p=JSON.parse(r.data);return [p.donorId,p.matchingOrganizationId].includes(key);});
 function validateMutation(collection,previous,next){if(collection==='gifts'){const receipt=db.prepare("SELECT 1 FROM fundraising_associations WHERE gift_id=? AND status='active'").get(previous.id),original=db.prepare('SELECT data FROM fundraising_records').all().some(r=>{const p=JSON.parse(r.data);return p.kind==='matching'&&p.originalGiftId===previous.id;});if(receipt||original){if(!next)fail(409,'Associated gift history cannot be deleted');for(const field of ['constituentId','amount','type','method','giftKind','campaignId','date','pledgeId','grantId'])if((previous[field]??null)!==(next[field]??null))fail(409,'Unlink or reconcile fundraising references before changing protected gift fields');}}if(collection==='constituents'&&referencedIdentity(previous.id)){if(!next||next.mergedInto||next.type!==previous.type)fail(409,'Fundraising identity references are retained; reconcile the tracking history before deleting, merging or changing constituent type');}if(collection==='campaigns'&&!next&&db.prepare('SELECT data FROM fundraising_records').all().some(r=>JSON.parse(r.data).campaignId===previous.id))fail(409,'Campaign is referenced by fundraising tracking');}
 app.use('/api',(req,res,next)=>{try{if(['GET','HEAD','OPTIONS'].includes(req.method))return next();const m=/^\/records\/(gifts|constituents|campaigns)\/([^/]+)$/.exec(req.path);if(m&&['PATCH','DELETE'].includes(req.method)){const old=get(m[1],decodeURIComponent(m[2]));validateMutation(m[1],old,req.method==='DELETE'?null:{...old,...req.body});}if(['/identity/merge','/identity/merge/preview'].includes(req.path)&&[req.body?.sourceId,req.body?.targetId].some(referencedIdentity))fail(409,'Fundraising identity history requires reconciliation before merging');next();}catch(error){next(error);}});
 const getQueueNextActions=user=>{authorized(user);return db.prepare('SELECT id FROM fundraising_records ORDER BY updated_at DESC,id').all().map(row=>base(row.id)).filter(r=>r.kind==='major'&&followupState(r)==='Open'&&!['Declined','Closed'].includes(r.stage)).map(r=>{const owner=db.prepare('SELECT id,name,active FROM users WHERE id=?').get(r.ownerId);return {id:r.id,name:r.name,owner:{id:r.ownerId,name:owner?`${owner.name}${owner.active?'':' (inactive)'}`:'Owner unavailable'},stage:r.stage,nextActionDate:r.nextActionDate,nextActionStatus:'Open',version:r.version};});};
 return {getFundraisingRecord:view,getQueueNextActions,validateMutation,referencedIdentity};
}
