import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
const fail=(status,message)=>{const e=new Error(message);e.status=status;throw e;};
const id=z.string().min(1).max(100),version=z.number().int().min(1),name=z.string().trim().min(1).max(250),reason=z.string().trim().min(1).max(2000);
const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v,'Use a valid calendar date');
const kind=z.enum(['Application','Report','Agreement']),today=()=>new Date().toISOString().slice(0,10),categories={Application:'Proposal',Report:'Report',Agreement:'Agreement'};
const editable={name,kind,dueDate:day,ownerId:id,ownerVersion:version,grantVersion:version};
export function installGrantOperationsRoutes(app,{db,list,get,audit,csrf,write,admin,transaction,documentService=null}){
 db.exec(`CREATE TABLE IF NOT EXISTS grant_milestones(id TEXT PRIMARY KEY,grant_id TEXT NOT NULL,version INTEGER NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS grant_milestone_history(milestone_id TEXT NOT NULL REFERENCES grant_milestones(id),version INTEGER NOT NULL,snapshot TEXT NOT NULL,action TEXT NOT NULL,reason TEXT,actor TEXT NOT NULL,at TEXT NOT NULL,PRIMARY KEY(milestone_id,version));
 CREATE TRIGGER IF NOT EXISTS grant_history_no_update BEFORE UPDATE ON grant_milestone_history BEGIN SELECT RAISE(ABORT,'Grant milestone history is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS grant_history_no_delete BEFORE DELETE ON grant_milestone_history BEGIN SELECT RAISE(ABORT,'Grant milestone history is retained'); END;`);
 const owner=key=>{const u=db.prepare('SELECT id,name,role,active,version FROM users WHERE id=?').get(key);if(!u||!u.active||!['admin','staff'].includes(u.role))fail(400,'Select an active staff or administrator milestone owner');return {id:u.id,name:u.name,role:u.role,version:u.version};};
 const source=(key,v)=>{const g=get('grants',key);if(g.version!==v)fail(409,'Grant changed. Reload its current version');return {id:g.id,version:g.version,name:g.name,funderId:g.funderId,stage:g.stage,requestedCents:g.amount,awardedCents:g.awardedAmount??null,awardDate:g.awardDate??null};};
 const check=(r,v)=>{if(r.version!==v)fail(409,'Milestone changed. Reload its current history');};
 const history=key=>db.prepare('SELECT version,snapshot,action,reason,actor,at FROM grant_milestone_history WHERE milestone_id=? ORDER BY version').all(key).map(r=>({...r,snapshot:JSON.parse(r.snapshot)}));
 const mayRead=(r,user)=>history(r.id).every(h=>h.snapshot.requiredRole!=='admin'&&(!h.snapshot.completion||db.prepare('SELECT visibility FROM documents WHERE id=?').get(h.snapshot.completion.document.id)?.visibility!=='Administrators'))||user.role==='admin';
 function find(key,user){const r=db.prepare('SELECT * FROM grant_milestones WHERE id=?').get(key);if(!r||!mayRead(r,user))fail(404,'Grant milestone not found');return {...r,...JSON.parse(r.data)};}
 const present=r=>({id:r.id,grantId:r.grant_id,version:r.version,...JSON.parse(r.data),createdAt:r.created_at,updatedAt:r.updated_at,history:history(r.id).map(h=>({...h,documentArchived:h.snapshot.completion?Boolean(db.prepare('SELECT archived FROM documents WHERE id=?').get(h.snapshot.completion.document.id)?.archived):null}))});
 function save(old,body,user,action,why=null){const key=old?.id||randomUUID(),v=(old?.version||0)+1,at=new Date().toISOString();if(old)db.prepare('UPDATE grant_milestones SET version=?,data=?,updated_at=? WHERE id=?').run(v,JSON.stringify(body),at,key);else db.prepare('INSERT INTO grant_milestones VALUES(?,?,?,?,?,?)').run(key,body.source.id,v,JSON.stringify(body),at,at);db.prepare('INSERT INTO grant_milestone_history VALUES(?,?,?,?,?,?,?)').run(key,v,JSON.stringify(body),action,why,user.id,at);audit(user,action,'grants',body.source.id,{milestoneId:key,version:v,kind:body.kind,status:body.status,documentId:body.completion?.document.id??null,revision:body.completion?.document.revision??null});return present(find(key,user));}
 function fields(p,grantId){const s=source(grantId,p.grantVersion),u=owner(p.ownerId);if(u.version!==p.ownerVersion)fail(409,'Owner account changed. Reload available owners');return {name:p.name,kind:p.kind,dueDate:p.dueDate,owner:u,source:s,status:'Open',completion:null,requiredRole:'authenticated'};}
 function evidenceMetadata(p,old,user){const d=db.prepare('SELECT * FROM documents WHERE id=?').get(p.documentId);if(!d||(d.visibility==='Administrators'&&user.role!=='admin'))fail(404,'Completion document not found');if(d.collection!=='grants'||d.record_id!==old.grant_id)fail(400,'Completion document must be linked to this grant');if(d.version!==p.documentVersion)fail(409,'Completion document changed. Reload its revisions');if(d.archived)fail(409,'Select an unarchived document for new completion evidence');const r=db.prepare('SELECT * FROM document_revisions WHERE document_id=? AND revision=?').get(d.id,p.revision);if(!r)fail(400,'Select an existing immutable document revision');const metadata=JSON.parse(r.metadata);if(metadata.visibility==='Administrators'&&user.role!=='admin')fail(404,'Completion document revision not found');if(metadata.category!==categories[old.kind]||!['Final','Submitted'].includes(metadata.status))fail(400,'Use a final or submitted '+categories[old.kind].toLowerCase()+' revision as completion evidence');if(metadata.evidenceDate&&metadata.evidenceDate>p.completedDate)fail(400,'Completion date cannot precede the recorded evidence date');return {d,r,metadata};}
 function evidence(p,old,user,verified=null){const {d,r,metadata}=evidenceMetadata(p,old,user);if(verified){if(verified.pin.documentId!==d.id||verified.pin.revision!==r.revision)fail(503,'Verified document revision does not match completion evidence');documentService.assertRevisionCurrent(verified.pin,user);}else if(metadata.storage?.kind==='object')fail(503,'Private completion evidence requires asynchronous object verification');const bytes=verified?Buffer.from(verified.bytes):Buffer.from(r.bytes);if(createHash('sha256').update(bytes).digest('hex')!==r.sha256)fail(503,'Completion document integrity check failed');return {document:{id:d.id,version:d.version,revision:r.revision,title:metadata.title,category:metadata.category,status:metadata.status,evidenceDate:metadata.evidenceDate,visibility:d.visibility,revisionVisibility:metadata.visibility,filename:r.filename,sha256:r.sha256,size:bytes.length},completedDate:p.completedDate,reference:p.reference,staffConfirmed:true};}
 const action=fn=>(req,res,next)=>{try{fn(req,res);}catch(e){next(e);}};
 const prefix='/api/grant-operations';
 app.get(prefix,action((req,res)=>{const q=z.object({grantId:id.optional(),status:z.enum(['Open','Completed']).optional(),kind:kind.optional(),from:day.optional(),to:day.optional()}).strict().parse(req.query);if(q.from&&q.to&&q.from>q.to)fail(400,'Start date must precede end date');if(q.grantId)get('grants',q.grantId);const milestones=db.prepare('SELECT * FROM grant_milestones ORDER BY updated_at,id').all().filter(r=>mayRead(r,req.user)).map(present).filter(r=>(!q.grantId||r.grantId===q.grantId)&&(!q.status||r.status===q.status)&&(!q.kind||r.kind===q.kind)&&(!q.from||r.dueDate>=q.from)&&(!q.to||r.dueDate<=q.to));const documents=db.prepare("SELECT id,record_id,title,category,status,visibility,version FROM documents WHERE collection='grants' AND archived=0 ORDER BY title,id").all().filter(d=>(!q.grantId||d.record_id===q.grantId)&&(req.user.role==='admin'||d.visibility!=='Administrators')).map(d=>({id:d.id,grantId:d.record_id,title:d.title,category:d.category,status:d.status,version:d.version,revisions:db.prepare('SELECT revision,filename,sha256,metadata FROM document_revisions WHERE document_id=? ORDER BY revision DESC').all(d.id).filter(r=>req.user.role==='admin'||JSON.parse(r.metadata).visibility!=='Administrators').map(r=>({revision:r.revision,filename:r.filename,sha256:r.sha256,metadata:JSON.parse(r.metadata)}))}));res.json({milestones,documents,grants:list('grants').map(g=>({id:g.id,name:g.name,version:g.version})),owners:db.prepare("SELECT id,name,role,version FROM users WHERE active=1 AND role IN ('admin','staff') ORDER BY name,id").all(),scope:'Staff-recorded grant milestones and human-confirmed documentary evidence only. No external submission, reminders, reporting delivery, awards or revenue writes.'});}));
 app.post(prefix,csrf,write,action((req,res)=>{const p=z.object({grantId:id,...editable}).strict().parse(req.body);res.status(201).json({milestone:transaction(()=>save(null,fields(p,p.grantId),req.user,'create_grant_milestone'))});}));
 app.get(prefix+'/:id',action((req,res)=>res.json({milestone:present(find(req.params.id,req.user))})));
 app.patch(prefix+'/:id',csrf,write,action((req,res)=>{const p=z.object({version,...editable}).strict().parse(req.body);res.json({milestone:transaction(()=>{const old=find(req.params.id,req.user);check(old,p.version);if(old.status!=='Open')fail(409,'Reopen a completed milestone with a reason before editing');return save(old,{...fields(p,old.grant_id),requiredRole:old.requiredRole},req.user,'update_grant_milestone');})});}));
 app.post(prefix+'/:id/complete',csrf,write,async(req,res,next)=>{try{const p=z.object({version,grantVersion:version,ownerVersion:version,documentId:id,documentVersion:version,revision:version,completedDate:day,reference:reason,confirmed:z.literal(true)}).strict().parse(req.body);if(p.completedDate>today())fail(400,'Record an actual nonfuture completion date');const initial=find(req.params.id,req.user);check(initial,p.version);if(initial.status!=='Open')fail(409,'Milestone is already completed');source(initial.grant_id,p.grantVersion);const initialOwner=owner(initial.owner.id);if(initialOwner.version!==p.ownerVersion)fail(409,'Owner account changed. Reload before confirming');evidenceMetadata(p,initial,req.user);const verified=documentService?await documentService.readRevision(p.documentId,p.revision,req.user,{sessionTokenHash:req.session?.token_hash}):null;res.json({milestone:transaction(()=>{const old=find(req.params.id,req.user);check(old,p.version);if(old.status!=='Open')fail(409,'Milestone is already completed');const s=source(old.grant_id,p.grantVersion),u=owner(old.owner.id);if(u.version!==p.ownerVersion)fail(409,'Owner account changed. Reload before confirming');const completion=evidence(p,old,req.user,verified),body={name:old.name,kind:old.kind,dueDate:old.dueDate,owner:u,source:s,status:'Completed',completion,requiredRole:old.requiredRole==='admin'||completion.document.visibility==='Administrators'||completion.document.revisionVisibility==='Administrators'?'admin':'authenticated'};return save(old,body,req.user,'complete_grant_milestone');})});}catch(e){next(e);}});
 app.post(prefix+'/:id/reopen',csrf,write,action((req,res)=>{const p=z.object({version,reason}).strict().parse(req.body);res.json({milestone:transaction(()=>{const old=find(req.params.id,req.user);check(old,p.version);if(old.status!=='Completed')fail(409,'Only completed milestones can be reopened');return save(old,{name:old.name,kind:old.kind,dueDate:old.dueDate,owner:old.owner,source:old.source,status:'Open',completion:null,requiredRole:old.requiredRole},req.user,'reopen_grant_milestone',p.reason);})});}));
 app.delete(prefix+'/:id',csrf,admin,action((req,res)=>{find(req.params.id,req.user);fail(403,'Grant milestone history is retained; reopen with a reason where appropriate');}));
 const hasDocumentReferences=key=>db.prepare('SELECT snapshot FROM grant_milestone_history').all().some(r=>JSON.parse(r.snapshot).completion?.document.id===key);
 const hasOwnerReferences=key=>db.prepare('SELECT snapshot FROM grant_milestone_history').all().some(r=>JSON.parse(r.snapshot).owner.id===key);
 function validateDeletion(collection,previous){if(!previous)return;if(collection==='grants'&&db.prepare('SELECT 1 FROM grant_milestones WHERE grant_id=?').get(previous.id)||collection==='documents'&&hasDocumentReferences(previous.id)||collection==='users'&&hasOwnerReferences(previous.id))fail(409,'Retained grant milestone history references this record; deletion is forbidden');}
 app.delete('/api/records/:collection/:id',csrf,write,(req,res,next)=>{try{if(req.params.collection==='grants')validateDeletion('grants',get('grants',req.params.id));next();}catch(e){next(e);}});
 app.delete('/api/documents/:id',csrf,admin,(req,res,next)=>{try{if(hasDocumentReferences(req.params.id))fail(409,'Retained grant completion evidence references this document');next();}catch(e){next(e);}});
 function getQueueMilestones(user){
  if(!user)fail(401,'Authentication required');if(!['admin','staff','viewer'].includes(user.role))fail(403,'Your role cannot access grant milestones');
  return db.prepare('SELECT * FROM grant_milestones ORDER BY id').all().filter(r=>mayRead(r,user)).map(r=>{const p=JSON.parse(r.data);return {id:r.id,grantId:r.grant_id,name:p.name,kind:p.kind,dueDate:p.dueDate,status:p.status,owner:{id:p.owner.id,name:p.owner.name}};});
 }
 return {validateDeletion,hasDocumentReferences,hasOwnerReferences,getQueueMilestones};
}
