import {randomBytes,createHash,createHmac,createCipheriv,createDecipheriv,timingSafeEqual} from 'node:crypto';
// RFC 6238 / RFC 4226: SHA-1 dynamic truncation, six digits, 30-second steps.
// Uses platform cryptographic primitives; secrets never enter audit records.
export class MfaError extends Error{constructor(message,status=400){super(message);this.status=status;}}
const hash=value=>createHash('sha256').update(value).digest('hex');
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
export function encodeBase32(bytes){let bits=0,value=0,out='';for(const byte of bytes){value=(value<<8)|byte;bits+=8;while(bits>=5){out+=alphabet[(value>>>(bits-5))&31];bits-=5;}}if(bits)out+=alphabet[(value<<(5-bits))&31];return out;}
function decodeBase32(secret){if(typeof secret!=='string'||!secret.length||!/^[A-Z2-7]+$/.test(secret))throw new MfaError('Invalid authenticator secret.');let bits=0,value=0,out=[];for(const c of secret){value=(value<<5)|alphabet.indexOf(c);bits+=5;if(bits>=8){out.push((value>>>(bits-8))&255);bits-=8;}}return Buffer.from(out);}
export function totp(secret,time=Date.now()){const step=Math.floor(time/30000);if(!Number.isSafeInteger(step)||step<0)throw new MfaError('Invalid authenticator time.');const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(step));const digest=createHmac('sha1',decodeBase32(secret)).update(counter).digest();const offset=digest.at(-1)&15;return String((digest.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,'0');}
function encryptionKey(input){if(Buffer.isBuffer(input))return input.length===32?Buffer.from(input):null;if(typeof input!=='string')return null;const value=input.trim();if(/^[a-f0-9]{64}$/i.test(value))return Buffer.from(value,'hex');if(/^[A-Za-z0-9+/]{43}=$/.test(value)){const bytes=Buffer.from(value,'base64');if(bytes.length===32&&bytes.toString('base64')===value)return bytes;}return null;}
const validRoles=new Set(['admin','staff','viewer']);
const failed=(message,status=401)=>({error:new MfaError(message,status)});
export function createMfaService({db,audit=()=>{},verifyPassword,key=process.env.MFA_ENCRYPTION_KEY,clock=Date.now}){
 const master=encryptionKey(key),ttl=5*60*1000;
 db.exec(`CREATE TABLE IF NOT EXISTS mfa_settings(user_id TEXT PRIMARY KEY,enabled INTEGER NOT NULL DEFAULT 0,encrypted_secret TEXT,pending_secret TEXT,pending_expires INTEGER,pending_attempts INTEGER NOT NULL DEFAULT 0,pending_binding TEXT,last_step INTEGER NOT NULL DEFAULT -1,updated_at INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS mfa_recovery(user_id TEXT NOT NULL,code_hash TEXT NOT NULL,consumed_at INTEGER,PRIMARY KEY(user_id,code_hash));
 CREATE TABLE IF NOT EXISTS mfa_challenges(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,account_binding TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS mfa_verification_limits(user_id TEXT PRIMARY KEY,window_start INTEGER NOT NULL,failures INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS mfa_disable_limits(user_id TEXT PRIMARY KEY,window_start INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0);`);
 const now=()=>{const time=clock();if(!Number.isSafeInteger(time)||time<0)throw new MfaError('Authenticator clock is unavailable.',503);return time;};
 const requireKey=()=>{if(!master)throw new MfaError('MFA is unavailable. Configure a valid server encryption key.',503);};
 const current=user=>{const found=typeof user?.id==='string'?db.prepare('SELECT * FROM users WHERE id=?').get(user.id):null;if(!found||!found.active||!validRoles.has(found.role))throw new MfaError('This account cannot authenticate.',401);return found;};
 const binding=user=>hash(JSON.stringify([user.password_hash,user.role,user.active,user.version??1]));
 const settings=id=>db.prepare('SELECT * FROM mfa_settings WHERE user_id=?').get(id);
 const encrypt=(secret,id)=>{requireKey();const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',master,iv);cipher.setAAD(Buffer.from('wimblo-mfa-v1:'+id));const encrypted=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return ['v1',iv.toString('base64'),cipher.getAuthTag().toString('base64'),encrypted.toString('base64')].join('.');};
 const decrypt=(encoded,id)=>{requireKey();try{const [version,iv,tag,ciphertext,...extra]=encoded.split('.');if(version!=='v1'||extra.length)throw Error();const decipher=createDecipheriv('aes-256-gcm',master,Buffer.from(iv,'base64'));decipher.setAAD(Buffer.from('wimblo-mfa-v1:'+id));decipher.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([decipher.update(Buffer.from(ciphertext,'base64')),decipher.final()]).toString('utf8');}catch{throw new MfaError('MFA cannot read this account’s protected secret. Restore the configured encryption key.',503);}};
 const atom=fn=>{db.exec('BEGIN IMMEDIATE');let result;try{result=fn();db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}if(result?.error)throw result.error;return result;};
 const log=(user,action,details={})=>audit({id:user.id},action,'users',user.id,details);
 const reauth=(user,password)=>{if(typeof password!=='string'||password.length<1||password.length>200||typeof verifyPassword!=='function'||verifyPassword(password,user.password_hash)!==true)throw new MfaError('Confirm your current password.',401);};
 const revoked=id=>{const count=db.prepare('DELETE FROM sessions WHERE user_id=?').run(id).changes;db.prepare('DELETE FROM mfa_challenges WHERE user_id=?').run(id);return count;};
 const matchStep=(secret,code,last,time)=>{if(typeof code!=='string'||!/^\d{6}$/.test(code))return null;const step=Math.floor(time/30000);for(const delta of [0,-1,1]){const candidate=step+delta;if(candidate<0)continue;const expected=totp(secret,candidate*30000);if(timingSafeEqual(Buffer.from(code),Buffer.from(expected))&&candidate>last)return candidate;}return null;};
 const consume=(user,row,code,time,allowRecovery=true)=>{
  const secret=decrypt(row.encrypted_secret,user.id),step=matchStep(secret,code,row.last_step,time);
  if(step!==null){const changed=db.prepare('UPDATE mfa_settings SET last_step=?,updated_at=? WHERE user_id=? AND enabled=1 AND last_step<?').run(step,time,user.id,step);return changed.changes===1;}
  if(!allowRecovery||typeof code!=='string'||!/^[A-F0-9]{8}-[A-F0-9]{8}$/.test(code))return false;
  return db.prepare('UPDATE mfa_recovery SET consumed_at=? WHERE user_id=? AND code_hash=? AND consumed_at IS NULL').run(time,user.id,hash(user.id+':'+code)).changes===1;
 };
 const status=user=>{const account=current(user),row=settings(account.id);let available=Boolean(master);if(available&&row?.enabled)try{decrypt(row.encrypted_secret,account.id);}catch{available=false;}return {available,enabled:Boolean(row?.enabled),recoveryCodesRemaining:db.prepare('SELECT count(*) n FROM mfa_recovery WHERE user_id=? AND consumed_at IS NULL').get(account.id).n};};
 const beginEnrollment=(user,password)=>{requireKey();return atom(()=>{const account=current(user);reauth(account,password);const row=settings(account.id);if(row?.enabled)throw new MfaError('MFA is already enabled. Disable it before replacing the authenticator.',409);const time=now(),secret=encodeBase32(randomBytes(20));db.prepare('INSERT INTO mfa_settings(user_id,pending_secret,pending_expires,pending_attempts,pending_binding,updated_at) VALUES(?,?,?,0,?,?) ON CONFLICT(user_id) DO UPDATE SET pending_secret=excluded.pending_secret,pending_expires=excluded.pending_expires,pending_attempts=0,pending_binding=excluded.pending_binding,updated_at=excluded.updated_at').run(account.id,encrypt(secret,account.id),time+ttl,binding(account),time);log(account,'mfa_enrollment_started');return {secret,otpauthUrl:`otpauth://totp/${encodeURIComponent('Wimblo:'+account.email)}?secret=${secret}&issuer=Wimblo&algorithm=SHA1&digits=6&period=30`,expiresAt:time+ttl};});};
 const confirmEnrollment=(user,code)=>{requireKey();return atom(()=>{const account=current(user),row=settings(account.id),time=now();if(!row?.pending_secret||row.enabled||row.pending_expires<=time||row.pending_binding!==binding(account))return failed('Enrollment expired. Confirm your password and start again.',409);if(row.pending_attempts>=5)return failed('Too many enrollment attempts. Start enrollment again.',429);db.prepare('UPDATE mfa_settings SET pending_attempts=pending_attempts+1 WHERE user_id=?').run(account.id);const step=matchStep(decrypt(row.pending_secret,account.id),code,-1,time);if(step===null){log(account,'mfa_enrollment_failed',{reason:'invalid_code'});return failed('Enter a valid six-digit authenticator code.');}db.prepare('UPDATE mfa_settings SET enabled=1,encrypted_secret=pending_secret,pending_secret=NULL,pending_expires=NULL,pending_binding=NULL,pending_attempts=0,last_step=?,updated_at=? WHERE user_id=?').run(step,time,account.id);db.prepare('DELETE FROM mfa_recovery WHERE user_id=?').run(account.id);const recoveryCodes=Array.from({length:8},()=>{const raw=randomBytes(8).toString('hex').toUpperCase();return raw.slice(0,8)+'-'+raw.slice(8);});for(const code of recoveryCodes)db.prepare('INSERT INTO mfa_recovery(user_id,code_hash) VALUES(?,?)').run(account.id,hash(account.id+':'+code));const sessionsRevoked=revoked(account.id);log(account,'mfa_enabled',{sessionsRevoked,recoveryCodes:8});return {enabled:true,recoveryCodes,sessionsRevoked,reauthenticationRequired:true};});};
 const challenge=user=>{requireKey();return atom(()=>{const account=current(user),row=settings(account.id);if(!row?.enabled)throw new MfaError('MFA is not enabled for this account.',409);decrypt(row.encrypted_secret,account.id);const time=now(),challengeToken=randomBytes(32).toString('hex');db.prepare('DELETE FROM mfa_challenges WHERE expires<=? OR user_id=?').run(time,account.id);db.prepare('INSERT INTO mfa_challenges(token_hash,user_id,expires,account_binding) VALUES(?,?,?,?)').run(hash(challengeToken),account.id,time+ttl,binding(account));return {challengeToken,expiresAt:time+ttl};});};
 const verifyChallenge=(challengeToken,code)=>{requireKey();if(typeof challengeToken!=='string'||!/^[a-f0-9]{64}$/.test(challengeToken))throw new MfaError('Invalid or expired MFA challenge.',401);return atom(()=>{const tokenHash=hash(challengeToken),entry=db.prepare('SELECT * FROM mfa_challenges WHERE token_hash=?').get(tokenHash),time=now();if(!entry||entry.expires<=time)return failed('Invalid or expired MFA challenge. Sign in again.');let account;try{account=current({id:entry.user_id});}catch{db.prepare('DELETE FROM mfa_challenges WHERE token_hash=?').run(tokenHash);return failed('This account cannot authenticate.');}if(entry.account_binding!==binding(account)){db.prepare('DELETE FROM mfa_challenges WHERE token_hash=?').run(tokenHash);return failed('Account access changed. Sign in again.');}let window=db.prepare('SELECT * FROM mfa_verification_limits WHERE user_id=?').get(account.id);if(!window||window.window_start<=time-ttl){db.prepare('INSERT INTO mfa_verification_limits(user_id,window_start,failures) VALUES(?,?,0) ON CONFLICT(user_id) DO UPDATE SET window_start=excluded.window_start,failures=0').run(account.id,time);window={failures:0};}if(window.failures>=5)return failed('Too many MFA attempts for this account. Try again in five minutes.',429);if(entry.attempts>=5)return failed('Too many MFA attempts. Sign in again.',429);db.prepare('UPDATE mfa_challenges SET attempts=attempts+1 WHERE token_hash=?').run(tokenHash);const row=settings(account.id);if(!row?.enabled||!consume(account,row,code,time)){db.prepare('UPDATE mfa_verification_limits SET failures=failures+1 WHERE user_id=?').run(account.id);log(account,'mfa_challenge_failed',{reason:'invalid_code'});return failed('Invalid or already used authenticator or recovery code.');}db.prepare('DELETE FROM mfa_challenges WHERE token_hash=?').run(tokenHash);db.prepare('DELETE FROM mfa_verification_limits WHERE user_id=?').run(account.id);log(account,'mfa_verified');return {verified:true,user:{id:account.id,name:account.name,email:account.email,role:account.role}};});};
 const disable=(user,password,code)=>{requireKey();return atom(()=>{const account=current(user);reauth(account,password);const row=settings(account.id);if(!row?.enabled)throw new MfaError('MFA is not enabled for this account.',409);const time=now();let limit=db.prepare('SELECT * FROM mfa_disable_limits WHERE user_id=?').get(account.id);if(!limit||limit.window_start<=time-ttl){db.prepare('INSERT INTO mfa_disable_limits(user_id,window_start,attempts) VALUES(?,?,0) ON CONFLICT(user_id) DO UPDATE SET window_start=excluded.window_start,attempts=0').run(account.id,time);limit={attempts:0};}if(limit.attempts>=5)return failed('Too many MFA attempts. Try again in five minutes.',429);db.prepare('UPDATE mfa_disable_limits SET attempts=attempts+1 WHERE user_id=?').run(account.id);if(!consume(account,row,code,time)){log(account,'mfa_disable_failed',{reason:'invalid_code'});return failed('Confirm a valid, unused authenticator or recovery code.');}db.prepare('DELETE FROM mfa_settings WHERE user_id=?').run(account.id);db.prepare('DELETE FROM mfa_recovery WHERE user_id=?').run(account.id);db.prepare('DELETE FROM mfa_disable_limits WHERE user_id=?').run(account.id);const sessionsRevoked=revoked(account.id);log(account,'mfa_disabled',{sessionsRevoked});return {enabled:false,sessionsRevoked,reauthenticationRequired:true};});};
 return {status,beginEnrollment,confirmEnrollment,challenge,verifyChallenge,disable};
}
