import {DatabaseSync} from 'node:sqlite';
import {constants} from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
import {mkdir,lstat,open,readFile,mkdtemp,rm} from 'node:fs/promises';
import {resolve,dirname,join,isAbsolute,relative} from 'node:path';
import {z} from 'zod';
import {backupPlatform,restorePlatform,publishOffHostPlatformBackup,retrieveOffHostPlatformBackup} from './platformRecovery.js';
import {parseBackupKey} from './backup.js';

const MAX_RUNS=5000,MAX_OUTCOMES=50000,MAX_ARCHIVE=128*1024*1024,periods={Daily:86400000,Weekly:604800000};
const fail=message=>{throw new Error(message);},sha=b=>createHash('sha256').update(b).digest('hex');
const absolute=z.string().min(1).max(2048).refine(isAbsolute,'Use an absolute operator path');
const reason=z.string().trim().min(1).max(500),uuid=z.uuid();
const armSchema=z.object({rootDir:absolute,legacyDbPath:absolute,archiveDir:absolute,recoveryId:uuid,cadence:z.enum(['Daily','Weekly']),firstRunAt:z.iso.datetime(),requireOffHost:z.boolean(),reason}).strict();
const inTree=(root,path)=>{const p=relative(root,path);return p===''||!p.startsWith('..')&&!isAbsolute(p);};
const iso=time=>new Date(time).toISOString();
const parse=row=>row?JSON.parse(row.data):null;
const notice='Operator-invoked offline orchestration only. No daemon, adopted schedule, cloud durability, retention/disposal approval or RPO/RTO/SLA is implied.';

export async function openOfflineRecoverySchedule({journalPath,clock=Date.now,documentStorageForTenant,store=null}={}){
 absolute.parse(journalPath);journalPath=resolve(journalPath);
 await mkdir(dirname(journalPath),{recursive:true,mode:0o700});
 const parent=await lstat(dirname(journalPath));if(!parent.isDirectory()||parent.isSymbolicLink()||(parent.mode&0o077))fail('The operator journal requires a private non-symlink parent directory.');
 try{const f=await open(journalPath,'wx',0o600);await f.close();}catch(e){if(e.code!=='EEXIST')throw e;}
 const stat=await lstat(journalPath);if(!stat.isFile()||stat.isSymbolicLink()||stat.nlink!==1||(stat.mode&0o077))fail('The operator journal must be a private regular file.');
 const db=new DatabaseSync(journalPath);db.exec(`PRAGMA foreign_keys=ON; PRAGMA busy_timeout=1000; PRAGMA synchronous=FULL;
 CREATE TABLE IF NOT EXISTS offline_recovery_schedule(id INTEGER PRIMARY KEY CHECK(id=1),data TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS offline_recovery_runs(id TEXT PRIMARY KEY,scheduled_at TEXT NOT NULL UNIQUE,data TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS offline_recovery_outcomes(id TEXT PRIMARY KEY,run_id TEXT,at TEXT NOT NULL,action TEXT NOT NULL,reason TEXT NOT NULL,data TEXT NOT NULL);
 CREATE TRIGGER IF NOT EXISTS offline_recovery_outcome_immutable_update BEFORE UPDATE ON offline_recovery_outcomes BEGIN SELECT RAISE(ABORT,'Recovery outcomes are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS offline_recovery_outcome_immutable_delete BEFORE DELETE ON offline_recovery_outcomes BEGIN SELECT RAISE(ABORT,'Recovery outcomes are retained'); END;
 CREATE TRIGGER IF NOT EXISTS offline_recovery_run_retained BEFORE DELETE ON offline_recovery_runs BEGIN SELECT RAISE(ABORT,'Recovery runs are retained'); END;
 CREATE TRIGGER IF NOT EXISTS offline_recovery_schedule_retained BEFORE DELETE ON offline_recovery_schedule BEGIN SELECT RAISE(ABORT,'Recovery schedule is retained'); END;`);
 const after=await lstat(journalPath);if(after.ino!==stat.ino||after.dev!==stat.dev){db.close();fail('Operator journal changed while opening.');}
 const tx=fn=>{db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}};
 const schedule=()=>parse(db.prepare('SELECT data FROM offline_recovery_schedule WHERE id=1').get());
 const run=id=>{uuid.parse(id);const r=parse(db.prepare('SELECT data FROM offline_recovery_runs WHERE id=?').get(id));if(!r)fail('Recovery run not found.');return r;};
 const saveSchedule=s=>{const data=JSON.stringify(s);db.prepare('INSERT INTO offline_recovery_schedule VALUES(1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').run(data);if(JSON.stringify(schedule())!==data)fail('Recovery schedule readback failed.');};
 const saveRun=r=>{const data=JSON.stringify(r);db.prepare('INSERT INTO offline_recovery_runs VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').run(r.id,r.scheduledAt,data);if(JSON.stringify(run(r.id))!==data||db.prepare('SELECT scheduled_at FROM offline_recovery_runs WHERE id=?').get(r.id)?.scheduled_at!==r.scheduledAt)fail('Recovery run readback failed.');};
 function outcome(r,action,why,details={}){if(db.prepare('SELECT COUNT(*) n FROM offline_recovery_outcomes').get().n>=MAX_OUTCOMES)fail('Recovery outcome capacity reached; preserve the journal for operator disposition.');const id=randomUUID(),at=iso(clock()),data=JSON.stringify(details);db.prepare('INSERT INTO offline_recovery_outcomes VALUES(?,?,?,?,?,?)').run(id,r?.id??null,at,action,why,data);const saved=db.prepare('SELECT * FROM offline_recovery_outcomes WHERE id=?').get(id);if(JSON.stringify(saved)!==JSON.stringify({id,run_id:r?.id??null,at,action,reason:why,data}))fail('Recovery outcome readback failed.');}
 const scheduleDTO=s=>s?{id:s.id,revision:s.revision,status:s.status,cadence:s.cadence,nextRunAt:s.status==='Active'?s.nextRunAt:null,requireOffHost:s.requireOffHost,currentRunId:s.currentRunId,createdAt:s.createdAt,retiredAt:s.retiredAt??null}:null;
 const runDTO=r=>({id:r.id,scheduledAt:r.scheduledAt,status:r.status,phase:r.phase,revision:r.revision,startedAt:r.startedAt,completedAt:r.completedAt??null,archiveSha256:r.archiveSha256??null,archiveBytes:r.archiveBytes??null,tenantCount:r.tenantCount??null,restoreVerified:r.status==='Verified',offHostVerified:r.status==='Verified'&&r.offHostVerified===true,storage:r.status==='Verified'&&r.offHostVerified?'Verified private off-host version':'Local archive only',...(r.offHostVerified?{objectKey:r.objectKey,versionId:r.versionId}:{}),lastReason:r.lastReason??null,publicationRecoveryRequired:r.status!=='Verified'&&r.publicationAttempted===true});
 function checkKey(key){const bytes=parseBackupKey(key);bytes.fill(0);}
 const sourcePin=s=>JSON.stringify(Object.fromEntries(['id','rootDir','legacyDbPath','archiveDir','recoveryId','cadence','requireOffHost'].map(k=>[k,s[k]])));
 function exactCurrent(s,r){const current=schedule(),saved=run(r.id);if(!current||sourcePin(current)!==sourcePin(s)||current.status!=='Active'||current.currentRunId!==r.id||JSON.stringify(saved)!==JSON.stringify(r)||saved.status!=='Reserved')fail('Recovery authority changed. Inspect history and recover explicitly.');return {current,saved};}
 async function archiveInfo(path){const f=await open(path,constants.O_RDONLY|constants.O_NOFOLLOW);try{const st=await f.stat();if(!st.isFile()||st.nlink!==1||(st.mode&0o077)||st.size<1||st.size>MAX_ARCHIVE)fail('Recovery archive is invalid or exceeds its bound.');const bytes=await f.readFile();if(bytes.length!==st.size)fail('Recovery archive changed while reading.');return {archiveSha256:sha(bytes),archiveBytes:bytes.length};}finally{await f.close();}}
 async function verifyArchive(s,r,key){const info=await archiveInfo(r.archivePath);if(r.archiveSha256&&r.archiveSha256!==info.archiveSha256)fail('Saved recovery archive checksum changed.');const temporary=await mkdtemp(join(s.archiveDir,'.scheduled-drill-'));try{const drill=await restorePlatform({archivePath:r.archivePath,destinationRoot:join(temporary,'NEW-root'),expectedRecoveryId:s.recoveryId,encryptionKey:key});const after=await archiveInfo(r.archivePath);if(info.archiveSha256!==after.archiveSha256||info.archiveBytes!==after.archiveBytes||drill.archiveSha256!==info.archiveSha256)fail('Recovery archive changed during the verification drill.');return {...info,tenantCount:drill.tenantCount};}finally{await rm(temporary,{recursive:true,force:true});}}
 async function execute(s,r,key,{existingArchive=false,reference=null}={}){
  try{
   if(!existingArchive)await backupPlatform({rootDir:s.rootDir,legacyDbPath:s.legacyDbPath,outputPath:r.archivePath,recoveryId:s.recoveryId,encryptionKey:key,offlineConfirmed:true,documentStorageForTenant});
   const verified=await verifyArchive(s,r,key);
   r=tx(()=>{exactCurrent(s,r);const next={...r,...verified,revision:r.revision+1,phase:'Archived'};saveRun(next);outcome(next,'Archive verified','Authenticated NEW-root restore drill completed',{...verified});return next;});
   let publication=null;
   if(s.requireOffHost){
    if(store?.private!==true||store?.offHost!==true||typeof store.putImmutable!=='function'||typeof store.readVersion!=='function')fail('Configured private off-host recovery storage is required before any publication attempt.');
    if(reference){const temporary=await mkdtemp(join(s.archiveDir,'.scheduled-readback-'));try{publication=await retrieveOffHostPlatformBackup({recoveryId:s.recoveryId,key:reference.key,versionId:reference.versionId,expectedSha256:r.archiveSha256,outputPath:join(temporary,'NEW-archive'),encryptionKey:key,store});}finally{await rm(temporary,{recursive:true,force:true});}}
    else{r=tx(()=>{exactCurrent(s,r);const next={...r,revision:r.revision+1,phase:'Publishing',publicationAttempted:true};saveRun(next);outcome(next,'Publication reserved','Private immutable off-host publication is beginning');return next;});publication=await publishOffHostPlatformBackup({archivePath:r.archivePath,recoveryId:s.recoveryId,encryptionKey:key,store});}
    if(publication.archiveSha256!==r.archiveSha256||publication.archiveBytes!==r.archiveBytes||publication.verified!==true)fail('Off-host publication does not match the reserved archive.');
   }
   const finalInfo=await archiveInfo(r.archivePath);if(finalInfo.archiveSha256!==r.archiveSha256||finalInfo.archiveBytes!==r.archiveBytes)fail('Recovery archive changed before final journal commit.');
   return tx(()=>{const {current}=exactCurrent(s,r),time=clock(),next={...r,status:'Verified',revision:r.revision+1,completedAt:iso(time),offHostVerified:Boolean(publication),...(publication?{objectKey:publication.key,versionId:publication.versionId}:{})};saveRun(next);const step=periods[s.cadence],scheduled=Date.parse(r.scheduledAt),nextRunAt=iso(scheduled+(Math.floor(Math.max(0,time-scheduled)/step)+1)*step);const nextSchedule={...current,revision:current.revision+1,currentRunId:null,nextRunAt};saveSchedule(nextSchedule);outcome(next,'Verified','Archive and NEW-root restore verified; next due cycle committed',{archiveSha256:r.archiveSha256,offHostVerified:next.offHostVerified});exactFinal(next,nextSchedule);return runDTO(next);});
  }catch(error){try{tx(()=>{const saved=run(r.id),current=schedule();if(saved.status!=='Reserved'||current.currentRunId!==r.id)return;const failed={...saved,status:'Failed',revision:saved.revision+1,lastReason:'Recovery did not complete; inspect retained archive and recover explicitly'};saveRun(failed);outcome(failed,'Failed',failed.lastReason,{phase:saved.phase});});}catch{/* A failed journal commit remains Reserved, never falsely Verified. */}throw Error('Scheduled recovery failed. No verified completion is claimed; inspect the private journal and recover explicitly.');}
 }
 function exactFinal(expected,expectedSchedule){if(JSON.stringify(run(expected.id))!==JSON.stringify(expected))fail('Recovery final journal readback failed.');const s=schedule();if(JSON.stringify(s)!==JSON.stringify(expectedSchedule))fail('Recovery next-cycle readback failed.');}
 return {
  async arm(input){const p=armSchema.parse(input),time=clock(),start=Date.parse(p.firstRunAt);if(start<time||start>time+366*86400000)fail('Choose an explicit UTC first run from now through the next year.');p.rootDir=resolve(p.rootDir);p.legacyDbPath=resolve(p.legacyDbPath);p.archiveDir=resolve(p.archiveDir);if(inTree(p.rootDir,p.archiveDir)||inTree(dirname(p.legacyDbPath),p.archiveDir)||inTree(p.archiveDir,journalPath)||inTree(p.rootDir,journalPath)||inTree(dirname(p.legacyDbPath),journalPath))fail('Archive and operator journal must be separate from source database trees and each other.');await mkdir(p.archiveDir,{recursive:true,mode:0o700});const st=await lstat(p.archiveDir);if(!st.isDirectory()||st.isSymbolicLink()||(st.mode&0o077))fail('Recovery archive directory must be private and non-symlink.');return tx(()=>{if(schedule())fail('This journal already has a retained schedule. Use a new private journal for a new schedule.');const s={...p,id:randomUUID(),revision:1,status:'Active',nextRunAt:iso(start),currentRunId:null,createdAt:iso(time)};saveSchedule(s);outcome(null,'Armed',p.reason,{scheduleId:s.id,cadence:s.cadence,firstRunAt:s.nextRunAt,requireOffHost:s.requireOffHost});if(JSON.stringify(schedule())!==JSON.stringify(s))fail('Armed schedule changed during journal persistence.');return scheduleDTO(s);});},
  async runDue({offlineConfirmed=false,encryptionKey}={}){if(offlineConfirmed!==true)fail('Confirm all application processes and workers are stopped before every due invocation.');checkKey(encryptionKey);const claimed=tx(()=>{const s=schedule();if(!s||s.status!=='Active')fail('An active operator schedule is required.');if(s.currentRunId)fail('An unresolved recovery occurrence requires explicit recovery; no automatic retry or takeover is performed.');if(Date.parse(s.nextRunAt)>clock())return null;if(db.prepare('SELECT COUNT(*) n FROM offline_recovery_runs').get().n>=MAX_RUNS)fail('Recovery journal capacity reached; preserve it and adopt a new journal under the retention plan.');const id=randomUUID(),r={id,scheduledAt:s.nextRunAt,status:'Reserved',phase:'Reserved',revision:1,archivePath:join(s.archiveDir,id+'.wrecovery'),startedAt:iso(clock())};saveRun(r);saveSchedule({...s,revision:s.revision+1,currentRunId:id});outcome(r,'Reserved','Due offline cycle reserved before archive creation');exactCurrent(s,r);return {s,r};});return claimed?execute(claimed.s,claimed.r,encryptionKey):{due:false,notice};},
  async recover(input){const p=z.object({runId:uuid,version:z.number().int().min(1),offlineConfirmed:z.literal(true),runnerStoppedConfirmed:z.literal(true),reason,encryptionKey:z.string(),reference:z.object({key:z.string().min(1).max(2048),versionId:z.string().min(1).max(1000)}).strict().optional()}).strict().parse(input);checkKey(p.encryptionKey);if(db.prepare('SELECT COUNT(*) n FROM offline_recovery_outcomes WHERE run_id=?').get(p.runId).n>=100)fail('This occurrence reached its bounded recovery history; preserve it for operator disposition.');const s=schedule(),old=run(p.runId);if(!s||s.status!=='Active'||s.currentRunId!==old.id||!['Reserved','Failed'].includes(old.status)||old.revision!==p.version)fail('Recovery source or version changed; inspect the retained occurrence.');let exists=false;try{const st=await lstat(old.archivePath);if(!st.isFile()||st.isSymbolicLink())fail('Retained archive must be a regular file.');exists=true;}catch(e){if(e.code!=='ENOENT')throw e;}
   if(s.requireOffHost&&(old.phase==='Publishing'||old.publicationAttempted===true)&&!p.reference)fail('Publication may have occurred. An exact retained object key/version is required; automatic republishing is refused.');if(p.reference&&(!s.requireOffHost||!exists))fail('Exact publication recovery requires its retained local archive and off-host schedule.');if(!exists&&old.phase!=='Reserved')fail('Verified or publication-stage archive is missing; reconstruction is refused.');
   const r=tx(()=>{const current=run(old.id),authority=schedule();if(current.revision!==old.revision||authority.currentRunId!==old.id||authority.status!=='Active')fail('Recovery source changed before reservation.');const next={...current,status:'Reserved',revision:current.revision+1,lastReason:p.reason};saveRun(next);outcome(next,'Recovery authorized',p.reason,{runnerStoppedConfirmed:true,existingArchive:exists,exactPublicationReference:Boolean(p.reference)});return next;});return execute(s,r,p.encryptionKey,{existingArchive:exists,reference:p.reference});},
  retire(input){const p=z.object({version:z.number().int().min(1),reason}).strict().parse(input);return tx(()=>{const s=schedule();if(!s||s.status!=='Active'||s.revision!==p.version)fail('Schedule is not active or its revision changed.');if(s.currentRunId)fail('Resolve the retained occurrence before retiring its schedule.');const next={...s,status:'Retired',revision:s.revision+1,retiredAt:iso(clock())};saveSchedule(next);outcome(null,'Retired',p.reason,{scheduleId:s.id});if(JSON.stringify(schedule())!==JSON.stringify(next))fail('Retired schedule changed during journal persistence.');return scheduleDTO(next);});},
  inspect(){return{schedule:scheduleDTO(schedule()),runs:db.prepare('SELECT data FROM offline_recovery_runs ORDER BY scheduled_at DESC,id DESC LIMIT 100').all().map(parse).map(runDTO),limits:{runCapacity:MAX_RUNS,outcomeCapacity:MAX_OUTCOMES,visibleRuns:100,visibleOutcomesPerRun:100,archiveBytes:MAX_ARCHIVE,tenantCount:1000},notice};},
  getRun(id){return{run:runDTO(run(id)),outcomes:db.prepare('SELECT id,at,action,reason,data FROM offline_recovery_outcomes WHERE run_id=? ORDER BY rowid DESC LIMIT 100').all(id).map(r=>({...r,details:JSON.parse(r.data),data:undefined})),notice};},
  close(){db.close();}
 };
}
