import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
import {changedGiftFinancialFields} from './financialCorrections.js';

const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const canonical=v=>v&&typeof v==='object'?Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const hash=v=>createHash('sha256').update(canonical(v)).digest('hex');
const key=z.string().min(1).max(100),version=z.number().int().positive(),reason=z.string().trim().min(1).max(2000),visibility=z.enum(['Workspace','Administrators']);
const bodySchema=z.object({campaignId:key,constituentId:key,coordinatorId:key,title:z.string().trim().min(1).max(250),goalCents:z.number().int().min(0).max(1e12),visibility,status:z.enum(['Active','Retired'])}).strict();
const recordSchema=bodySchema.extend({id:z.uuid(),version,createdAt:z.iso.datetime(),updatedAt:z.iso.datetime()}).strict();
const scope='Internal fundraiser ownership and attribution of existing posted One-time Cash gifts only. Fundraiser goals are aspirations; attribution is not additional income, soft credit, a receipt, online checkout, publication, outreach or a provider refund.';
const limits={activeFundraisers:100,attributionsPerFundraiser:1000,page:100,history:100};

export function installPeerFundraisingRoutes(app,{db,get,audit,csrf,write,admin,transaction,isTenantActive=()=>true,recheckAccess=()=>false,validateGiftSource=()=>{fail(503,'Native gift validation unavailable');}}){
 db.exec(`CREATE TABLE IF NOT EXISTS peer_fundraisers(id TEXT PRIMARY KEY,version INTEGER NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE UNIQUE INDEX IF NOT EXISTS peer_one_active_fundraiser ON peer_fundraisers(json_extract(data,'$.campaignId'),json_extract(data,'$.constituentId')) WHERE json_extract(data,'$.status')='Active';
 CREATE TABLE IF NOT EXISTS peer_fundraiser_versions(fundraiser_id TEXT NOT NULL REFERENCES peer_fundraisers(id),version INTEGER NOT NULL,data TEXT NOT NULL,source_versions TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL,reason TEXT NOT NULL,PRIMARY KEY(fundraiser_id,version));
 CREATE TABLE IF NOT EXISTS peer_gift_attributions(id TEXT PRIMARY KEY,fundraiser_id TEXT NOT NULL REFERENCES peer_fundraisers(id),gift_id TEXT NOT NULL,gift_version INTEGER NOT NULL,source_json TEXT NOT NULL,source_digest TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Active','Unlinked')),version INTEGER NOT NULL,linked_by TEXT NOT NULL,linked_at TEXT NOT NULL,unlinked_by TEXT,unlinked_at TEXT,unlink_reason TEXT);
 CREATE UNIQUE INDEX IF NOT EXISTS peer_one_active_gift ON peer_gift_attributions(gift_id) WHERE status='Active';
 CREATE TABLE IF NOT EXISTS peer_gift_attribution_history(id TEXT PRIMARY KEY,attribution_id TEXT NOT NULL REFERENCES peer_gift_attributions(id),fundraiser_id TEXT NOT NULL REFERENCES peer_fundraisers(id),gift_id TEXT NOT NULL,attribution_version INTEGER NOT NULL,action TEXT NOT NULL,source_json TEXT NOT NULL,source_digest TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL,reason TEXT NOT NULL);
 CREATE TRIGGER IF NOT EXISTS peer_fundraiser_no_delete BEFORE DELETE ON peer_fundraisers BEGIN SELECT RAISE(ABORT,'Peer fundraiser history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS peer_fundraiser_version_no_update BEFORE UPDATE ON peer_fundraiser_versions BEGIN SELECT RAISE(ABORT,'Peer fundraiser history is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS peer_fundraiser_version_no_delete BEFORE DELETE ON peer_fundraiser_versions BEGIN SELECT RAISE(ABORT,'Peer fundraiser history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS peer_attribution_no_delete BEFORE DELETE ON peer_gift_attributions BEGIN SELECT RAISE(ABORT,'Peer attribution history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS peer_attribution_source_no_update BEFORE UPDATE ON peer_gift_attributions WHEN NEW.id IS NOT OLD.id OR NEW.fundraiser_id IS NOT OLD.fundraiser_id OR NEW.gift_id IS NOT OLD.gift_id OR NEW.gift_version IS NOT OLD.gift_version OR NEW.source_json IS NOT OLD.source_json OR NEW.source_digest IS NOT OLD.source_digest OR NEW.linked_by IS NOT OLD.linked_by OR NEW.linked_at IS NOT OLD.linked_at OR OLD.status='Unlinked' BEGIN SELECT RAISE(ABORT,'Original peer attribution is immutable and closed associations cannot resume'); END;
 CREATE TRIGGER IF NOT EXISTS peer_attribution_history_no_update BEFORE UPDATE ON peer_gift_attribution_history BEGIN SELECT RAISE(ABORT,'Peer attribution history is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS peer_attribution_history_no_delete BEFORE DELETE ON peer_gift_attribution_history BEGIN SELECT RAISE(ABORT,'Peer attribution history is retained'); END;`);
 const tx=fn=>db.isTransaction?fn():transaction(fn),today=()=>new Date().toISOString().slice(0,10);
 const stored=(schema,value)=>{try{return schema.parse(JSON.parse(value));}catch{fail(503,'Stored peer fundraising provenance is unavailable');}};
 function base(id){const row=db.prepare('SELECT * FROM peer_fundraisers WHERE id=?').get(id);if(!row)fail(404,'Peer fundraiser not found');return recordSchema.parse({...stored(bodySchema,row.data),id:row.id,version:row.version,createdAt:row.created_at,updatedAt:row.updated_at});}
 function privateHistory(r){return r.visibility==='Administrators'||db.prepare("SELECT 1 FROM peer_fundraiser_versions WHERE fundraiser_id=? AND json_extract(data,'$.visibility')='Administrators' LIMIT 1").get(r.id)!==undefined;}
 function readable(r,user){if(!['admin','staff','viewer'].includes(user?.role))fail(403,'Peer fundraising access is unavailable');if(user.role!=='admin'&&privateHistory(r))fail(404,'Peer fundraiser not found');return r;}
 const find=(id,user)=>readable(base(id),user);
 function current(req,read=false){if(!req?.user||!(read?['admin','staff','viewer']:['admin','staff']).includes(req.user.role))fail(403,'Your role cannot access peer fundraising');if(!isTenantActive())fail(403,'Workspace is suspended');if(!recheckAccess(req))fail(401,'Account access changed. Sign in again');}
 const coordinator=id=>{const u=db.prepare('SELECT id,name,role,active,version FROM users WHERE id=?').get(id);if(!u)fail(409,'Coordinator account is unavailable');return u;};
 function sources(r,{active=false}={}){const campaign=get('campaigns',r.campaignId),person=get('constituents',r.constituentId),owner=coordinator(r.coordinatorId);if(campaign.id!==r.campaignId||person.id!==r.constituentId||person.mergedInto)fail(active?409:503,'Peer fundraiser identity provenance is unavailable');if(campaign.type!=='Peer-to-peer')fail(active?409:503,'Peer fundraiser campaign provenance is unavailable');if(active&&(campaign.status!=='Active'||!owner.active||!['admin','staff'].includes(owner.role)))fail(409,'Choose an active peer campaign and active staff coordinator before attributing gifts');return {campaign,person,owner};}
 const refs=s=>[{collection:'campaigns',id:s.campaign.id,version:s.campaign.version,digest:hash(s.campaign)},{collection:'constituents',id:s.person.id,version:s.person.version,digest:hash(s.person)},{collection:'users',id:s.owner.id,version:s.owner.version,digest:hash(s.owner)}];
 const eventLinked=id=>Boolean(db.prepare("SELECT 1 FROM sqlite_schema WHERE type='table' AND name='event_payment_links'").get()&&db.prepare('SELECT 1 FROM event_payment_links WHERE gift_id=? LIMIT 1').get(id));
 function eligible(g,r,{requirePosted=true}={}){const validDate=typeof g.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(g.date)&&Number.isFinite(Date.parse(g.date))&&new Date(g.date+'T00:00:00Z').toISOString().slice(0,10)===g.date;return g.id&&(!requirePosted||g.status==='Posted')&&g.type==='Cash'&&g.method!=='In-kind'&&g.giftKind==='One-time'&&!g.pledgeId&&!g.grantId&&g.campaignId===r.campaignId&&validDate&&g.date<=today()&&Number.isSafeInteger(g.amount)&&g.amount>0&&Array.isArray(g.allocations)&&g.allocations.length>0&&g.allocations.every(a=>Number.isSafeInteger(a.amount)&&a.amount>0)&&g.allocations.reduce((n,a)=>n+BigInt(a.amount),0n)===BigInt(g.amount)&&!eventLinked(g.id);}
 function original(a){let g;try{g=JSON.parse(a.source_json);}catch{fail(503,'Original peer attribution is unavailable');}if(g.id!==a.gift_id||g.version!==a.gift_version||hash(g)!==a.source_digest)fail(503,'Original peer attribution provenance is unavailable');return g;}
 function checkGift(gift){try{validateGiftSource(gift);}catch(e){if(e.status===503)throw e;fail(503,'Native peer gift source validation failed');}}
 function actual(a,r){const old=original(a);let gift;try{gift=get('gifts',a.gift_id);}catch(e){if(e.status===404)fail(503,'Peer attribution gift source is unavailable');throw e;}checkGift(gift);if(gift.id!==a.gift_id)fail(503,'Peer attribution gift identity is unavailable');if(a.status==='Active'&&changedGiftFinancialFields(old,gift).length>0)fail(503,'Active peer attribution financial source changed without reconciliation');if(a.status==='Active'&&!['Posted','Voided'].includes(gift.status))fail(503,'Peer attribution gift status is unavailable');return {old,gift,sourceCurrent:hash(gift)===a.source_digest,compatible:eligible(gift,r)};}
 const associations=id=>db.prepare('SELECT * FROM peer_gift_attributions WHERE fundraiser_id=? ORDER BY linked_at DESC,id DESC').all(id);
 function progress(r){let postedCashCents=0n,attributedGiftCount=0,unlinkedCount=0,voidedGiftCount=0,sourceChangedCount=0;for(const a of associations(r.id)){const s=actual(a,r);if(!s.sourceCurrent)sourceChangedCount++;if(a.status==='Unlinked'){unlinkedCount++;continue;}if(s.gift.status==='Voided'){voidedGiftCount++;continue;}if(!s.compatible)fail(503,'Active peer attribution is no longer financially compatible');postedCashCents+=BigInt(s.gift.amount);attributedGiftCount++;}if(postedCashCents>BigInt(Number.MAX_SAFE_INTEGER))fail(503,'Peer attributed progress exceeds safe integer cents');return {postedCashCents:Number(postedCashCents),attributedGiftCount,unlinkedCount,voidedGiftCount,sourceChangedCount,asOf:today()};}
 function view(r,user){readable(r,user);const s=sources(r);return {...r,campaignVersion:s.campaign.version,campaignName:s.campaign.name,campaignStatus:s.campaign.status,constituentVersion:s.person.version,fundraiserName:s.person.name,coordinatorVersion:s.owner.version,coordinatorName:s.owner.name,coordinatorAvailable:Boolean(s.owner.active&&['admin','staff'].includes(s.owner.role)),progress:progress(r)};}
 function associationView(a,r){const s=actual(a,r),donor=get('constituents',s.gift.constituentId);return {id:a.id,version:a.version,fundraiserId:a.fundraiser_id,giftId:a.gift_id,status:a.status,giftVersion:a.gift_version,originalSource:{donorId:s.old.constituentId,amountCents:s.old.amount,campaignId:s.old.campaignId,date:s.old.date,type:s.old.type,method:s.old.method,giftKind:s.old.giftKind,status:s.old.status},currentSource:{giftVersion:s.gift.version,donorId:s.gift.constituentId,donorName:donor.name,amountCents:s.gift.amount,campaignId:s.gift.campaignId,date:s.gift.date,status:s.gift.status,sourceCurrent:s.sourceCurrent,compatible:s.compatible},linkedBy:a.linked_by,linkedAt:a.linked_at,unlinkedBy:a.unlinked_by,unlinkedAt:a.unlinked_at,unlinkReason:a.unlink_reason};}
 function retain(r,s,user,why,at){db.prepare('INSERT INTO peer_fundraiser_versions VALUES(?,?,?,?,?,?,?)').run(r.id,r.version,JSON.stringify(r),JSON.stringify(refs(s)),user.id,at,why);}
 function save(old,data,s,user,why){const at=new Date().toISOString(),next={...old,...data,version:old.version+1,updatedAt:at},{id,version,createdAt,updatedAt,...body}=next;db.prepare('UPDATE peer_fundraisers SET version=?,data=?,updated_at=? WHERE id=?').run(version,JSON.stringify(body),at,id);retain(next,s,user,why,at);return next;}
 function verify(r,s){if(hash(base(r.id))!==hash(r)||hash(refs(sources(r)))!==hash(refs(s)))fail(409,'Peer fundraiser or current source changed before commit');const retained=db.prepare('SELECT data,source_versions FROM peer_fundraiser_versions WHERE fundraiser_id=? AND version=?').get(r.id,r.version);if(!retained||hash(stored(recordSchema,retained.data))!==hash(r)||canonical(JSON.parse(retained.source_versions))!==canonical(refs(s)))fail(409,'Saved peer fundraiser history failed exact reconciliation');}
 function history(a,r,gift,user,action,why){const at=new Date().toISOString(),snapshot={attributionId:a.id,fundraiserId:r.id,fundraiserVersion:r.version,giftId:gift.id,giftVersion:gift.version,attributionVersion:a.version,status:a.status,gift};db.prepare('INSERT INTO peer_gift_attribution_history VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),a.id,r.id,gift.id,a.version,action,JSON.stringify(snapshot),hash(snapshot),user.id,at,why);}
 function verifyAssociation(expected,r,gift){const saved=db.prepare('SELECT * FROM peer_gift_attributions WHERE id=?').get(expected.id);if(hash(saved)!==hash(expected)||hash(get('gifts',gift.id))!==hash(gift))fail(409,'Peer gift attribution or source changed before commit');const retained=db.prepare('SELECT * FROM peer_gift_attribution_history WHERE attribution_id=? AND attribution_version=?').all(saved.id,saved.version);if(retained.length!==1)fail(409,'Saved peer attribution history failed reconciliation');const h=retained[0],snapshot=JSON.parse(h.source_json);if(hash(snapshot)!==h.source_digest||snapshot.attributionId!==saved.id||snapshot.fundraiserId!==r.id||snapshot.fundraiserVersion!==r.version||snapshot.status!==saved.status||hash(snapshot.gift)!==hash(gift))fail(409,'Saved peer attribution history failed exact reconciliation');}
 const route=fn=>(req,res,next)=>{try{fn(req,res);}catch(e){next(e);}};
 app.use('/api/peer-fundraisers',(req,res,next)=>{try{current(req,true);next();}catch(e){next(e);}});
 app.post('/api/peer-fundraisers',csrf,write,route((req,res)=>{const p=bodySchema.omit({status:true}).extend({campaignVersion:version,constituentVersion:version,coordinatorVersion:version}).strict().parse(req.body),result=tx(()=>{current(req);if(p.visibility==='Administrators'&&req.user.role!=='admin')fail(403,'Only administrators may create private fundraisers');const {campaignVersion,constituentVersion,coordinatorVersion,...body}=p,r={...body,status:'Active',id:randomUUID(),version:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},s=sources(r,{active:true});if(s.campaign.version!==campaignVersion||s.person.version!==constituentVersion||s.owner.version!==coordinatorVersion)fail(409,'Campaign, fundraiser identity or coordinator changed');if(db.prepare("SELECT COUNT(*) n FROM peer_fundraisers WHERE json_extract(data,'$.status')='Active'").get().n>=100)fail(409,'This workspace has 100 active fundraisers. Retire an unused effort');if(db.prepare("SELECT 1 FROM peer_fundraisers WHERE json_extract(data,'$.status')='Active' AND json_extract(data,'$.campaignId')=? AND json_extract(data,'$.constituentId')=?").get(r.campaignId,r.constituentId))fail(409,'This person already has an active fundraiser for this campaign');db.prepare('INSERT INTO peer_fundraisers VALUES(?,?,?,?,?)').run(r.id,1,JSON.stringify({...body,status:'Active'}),r.createdAt,r.updatedAt);retain(r,s,req.user,'Created internal fundraiser',r.createdAt);audit(req.user,'create_peer_fundraiser','campaigns',r.campaignId,{fundraiserId:r.id,version:1,goalCents:r.goalCents,visibility:r.visibility});current(req);verify(r,s);return view(r,req.user);});res.status(201).json({fundraiser:result,limits,scope});}));
 app.patch('/api/peer-fundraisers/:id',csrf,write,route((req,res)=>{const p=bodySchema.pick({title:true,goalCents:true,visibility:true,coordinatorId:true}).extend({version,coordinatorVersion:version,reason}).strict().parse(req.body),result=tx(()=>{current(req);const old=find(req.params.id,req.user);if(old.version!==p.version)fail(409,'Fundraiser changed. Reload its current version');if(old.status!=='Active')fail(409,'Retired fundraisers cannot change; create a new effort');if(p.visibility==='Administrators'&&req.user.role!=='admin')fail(403,'Only administrators may manage private fundraisers');if(privateHistory(old)&&p.visibility!=='Administrators')fail(409,'Retained private fundraiser history cannot be made public');const {version,coordinatorVersion,reason:why,...body}=p,s=sources({...old,...body},{active:true});if(s.owner.version!==coordinatorVersion)fail(409,'Coordinator account changed');const r=save(old,body,s,req.user,why);audit(req.user,'update_peer_fundraiser','campaigns',r.campaignId,{fundraiserId:r.id,version:r.version,reason:why});current(req);verify(r,s);return view(r,req.user);});res.json({fundraiser:result,scope});}));
 app.post('/api/peer-fundraisers/:id/retire',csrf,write,route((req,res)=>{const p=z.object({version,reason}).strict().parse(req.body),result=tx(()=>{current(req);const old=find(req.params.id,req.user);if(old.version!==p.version||old.status!=='Active')fail(409,'Fundraiser changed or already retired');const s=sources(old),r=save(old,{status:'Retired'},s,req.user,p.reason);audit(req.user,'retire_peer_fundraiser','campaigns',r.campaignId,{fundraiserId:r.id,version:r.version,reason:p.reason});current(req);verify(r,s);return view(r,req.user);});res.json({fundraiser:result,scope});}));
 app.post('/api/peer-fundraisers/:id/attributions',csrf,write,route((req,res)=>{const p=z.object({version,giftId:key,giftVersion:version,campaignVersion:version,coordinatorVersion:version,reason}).strict().parse(req.body),result=tx(()=>{current(req);const old=find(req.params.id,req.user);if(old.version!==p.version||old.status!=='Active')fail(409,'Fundraiser changed or is retired');const s=sources(old,{active:true}),gift=get('gifts',p.giftId),donor=get('constituents',gift.constituentId);checkGift(gift);if(gift.id!==p.giftId||donor.id!==gift.constituentId||donor.mergedInto)fail(409,'Gift donor identity is unavailable');if(gift.version!==p.giftVersion||s.campaign.version!==p.campaignVersion||s.owner.version!==p.coordinatorVersion)fail(409,'Gift, campaign or coordinator changed');if(!eligible(gift,old))fail(409,'Select an existing posted One-time Cash gift for the same campaign, without pledge, grant or event payment linkage');if(db.prepare("SELECT 1 FROM peer_gift_attributions WHERE gift_id=? AND status='Active'").get(gift.id))fail(409,'This gift already has an active peer attribution');if(associations(old.id).length>=1000)fail(409,'This fundraiser has 1000 retained attributions; reconcile through a new effort');const at=new Date().toISOString(),a={id:randomUUID(),fundraiser_id:old.id,gift_id:gift.id,gift_version:gift.version,source_json:JSON.stringify(gift),source_digest:hash(gift),status:'Active',version:1,linked_by:req.user.id,linked_at:at,unlinked_by:null,unlinked_at:null,unlink_reason:null};db.prepare('INSERT INTO peer_gift_attributions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...Object.values(a));const r=save(old,{},s,req.user,p.reason);history(a,r,gift,req.user,'Linked',p.reason);audit(req.user,'attribute_peer_gift','gifts',gift.id,{fundraiserId:r.id,fundraiserVersion:r.version,attributionId:a.id,giftVersion:gift.version,reason:p.reason});current(req);verify(r,s);verifyAssociation(a,r,gift);if(hash(get('constituents',donor.id))!==hash(donor)||!eligible(get('gifts',gift.id),r))fail(409,'Gift eligibility or donor changed before attribution commit');return {fundraiser:view(r,req.user),attribution:associationView(a,r)};});res.status(201).json({...result,scope});}));
 app.post('/api/peer-fundraisers/:id/attributions/:attributionId/unlink',csrf,write,route((req,res)=>{const p=z.object({version,attributionVersion:version,giftVersion:version,reason}).strict().parse(req.body),result=tx(()=>{current(req);const old=find(req.params.id,req.user),a=db.prepare('SELECT * FROM peer_gift_attributions WHERE id=? AND fundraiser_id=?').get(req.params.attributionId,old.id);if(!a)fail(404,'Peer attribution not found');if(old.version!==p.version||a.version!==p.attributionVersion||a.status!=='Active')fail(409,'Fundraiser or attribution changed');const s=sources(old),gift=get('gifts',a.gift_id);if(gift.version!==p.giftVersion)fail(409,'Gift changed. Reload its current source');original(a);const at=new Date().toISOString(),next={...a,status:'Unlinked',version:a.version+1,unlinked_by:req.user.id,unlinked_at:at,unlink_reason:p.reason};db.prepare("UPDATE peer_gift_attributions SET status='Unlinked',version=version+1,unlinked_by=?,unlinked_at=?,unlink_reason=? WHERE id=?").run(req.user.id,at,p.reason,a.id);const r=save(old,{},s,req.user,p.reason);history(next,r,gift,req.user,'Unlinked',p.reason);audit(req.user,'unlink_peer_gift','gifts',gift.id,{fundraiserId:r.id,attributionId:a.id,attributionVersion:next.version,reason:p.reason});current(req);verify(r,s);verifyAssociation(next,r,gift);return {fundraiser:view(r,req.user),attribution:associationView(next,r)};});res.json({...result,scope});}));
 const pageSchema=z.object({limit:z.coerce.number().int().min(1).max(100).default(100),after:z.uuid().optional()}).strict();
 function permitted(user){return db.prepare('SELECT id FROM peer_fundraisers ORDER BY created_at DESC,id DESC').all().map(row=>base(row.id)).filter(r=>user.role==='admin'||!privateHistory(r));}
 function revisions(r){return db.prepare('SELECT * FROM peer_fundraiser_versions WHERE fundraiser_id=? ORDER BY version DESC LIMIT 100').all(r.id).map(v=>{const record=stored(recordSchema,v.data);if(record.id!==r.id||record.version!==v.version)fail(503,'Peer fundraiser revision provenance is unavailable');return {...record,actor:v.actor,at:v.at,reason:v.reason,sourceVersions:JSON.parse(v.source_versions).map(ref=>({collection:ref.collection,id:ref.id,version:ref.version}))};});}
 function histories(r){return db.prepare('SELECT * FROM peer_gift_attribution_history WHERE fundraiser_id=? ORDER BY at DESC,id DESC LIMIT 100').all(r.id).map(h=>{const snapshot=JSON.parse(h.source_json),a=db.prepare('SELECT * FROM peer_gift_attributions WHERE id=?').get(h.attribution_id);if(hash(snapshot)!==h.source_digest||!a||a.fundraiser_id!==r.id||a.gift_id!==h.gift_id||snapshot.gift.id!==h.gift_id||snapshot.attributionVersion!==h.attribution_version||snapshot.attributionId!==h.attribution_id)fail(503,'Peer attribution history provenance is unavailable');return {id:h.id,attributionId:h.attribution_id,giftId:h.gift_id,attributionVersion:h.attribution_version,fundraiserVersion:snapshot.fundraiserVersion,action:h.action,status:snapshot.status,giftVersion:snapshot.giftVersion,amountCents:snapshot.gift.amount,donorId:snapshot.gift.constituentId,actor:h.actor,at:h.at,reason:h.reason};});}
 app.get('/api/peer-fundraisers',route((req,res)=>{const q=pageSchema.extend({campaignId:key.optional(),status:z.enum(['Active','Retired']).optional()}).strict().parse(req.query),result=tx(()=>{const all=permitted(req.user).filter(r=>(!q.campaignId||r.campaignId===q.campaignId)&&(!q.status||r.status===q.status)),cursor=q.after?all.find(r=>r.id===q.after):null;if(q.after&&!cursor)fail(400,'Fundraiser cursor is unavailable');const rows=cursor?all.filter(r=>r.createdAt<cursor.createdAt||(r.createdAt===cursor.createdAt&&r.id<cursor.id)):all,page=rows.slice(0,q.limit);return {fundraisers:page.map(r=>view(r,req.user)),nextCursor:rows.length>q.limit?page.at(-1).id:null,limit:q.limit,limits,scope};});res.json(result);}));
 app.get('/api/peer-fundraisers/:id',route((req,res)=>{const q=pageSchema.parse(req.query),result=tx(()=>{const r=find(req.params.id,req.user),all=associations(r.id),cursor=q.after?all.find(a=>a.id===q.after):null;if(q.after&&!cursor)fail(400,'Attribution cursor is unavailable');const rows=cursor?all.filter(a=>a.linked_at<cursor.linked_at||(a.linked_at===cursor.linked_at&&a.id<cursor.id)):all,page=rows.slice(0,q.limit);return {fundraiser:view(r,req.user),attributions:page.map(a=>associationView(a,r)),nextCursor:rows.length>q.limit?page.at(-1).id:null,limit:q.limit,attributionCount:all.length,revisions:revisions(r),revisionCount:db.prepare('SELECT COUNT(*) n FROM peer_fundraiser_versions WHERE fundraiser_id=?').get(r.id).n,history:histories(r),historyCount:db.prepare('SELECT COUNT(*) n FROM peer_gift_attribution_history WHERE fundraiser_id=?').get(r.id).n,historyLimit:100,scope,limits};});res.json(result);}));
 const hasConstituentReferences=id=>db.prepare('SELECT id,data FROM peer_fundraisers').all().some(row=>stored(bodySchema,row.data).constituentId===id)||db.prepare('SELECT source_json FROM peer_gift_attributions').all().some(row=>[JSON.parse(row.source_json).constituentId,JSON.parse(row.source_json).softCreditId].includes(id));
 function validateMutation(collection,previous,next){if(collection==='gifts'){const active=db.prepare("SELECT * FROM peer_gift_attributions WHERE gift_id=? AND status='Active'").get(previous.id);if(active&&(!next||changedGiftFinancialFields(previous,next).length>0))fail(409,'Unlink the peer attribution with a reason before correcting protected gift facts');}if(collection==='constituents'&&hasConstituentReferences(previous.id)&&(!next||next.mergedInto||next.type!==previous.type))fail(409,'Retained peer fundraising identity history prevents deletion, merge or type replacement');if(collection==='campaigns'&&db.prepare("SELECT 1 FROM peer_fundraisers WHERE json_extract(data,'$.campaignId')=? LIMIT 1").get(previous.id)&&(!next||next.type!=='Peer-to-peer'))fail(409,'Retained peer fundraisers protect this campaign identity and type');}
 function reportSources(user){if(!['admin','staff','viewer'].includes(user?.role)||!isTenantActive())fail(403,'Current peer fundraising read access required');return tx(()=>{const result={peerFundraisers:[],peerFundraiserVersions:[],peerGiftAttributions:[],peerGiftAttributionHistory:[]};for(const r of permitted(user)){if(result.peerFundraisers.length>10000)break;const v=view(r,user);result.peerFundraisers.push({id:r.id,revision:r.version,title:r.title,campaignId:r.campaignId,constituentId:r.constituentId,coordinatorId:r.coordinatorId,goalCents:r.goalCents,status:r.status,visibility:r.visibility,coordinatorAvailable:v.coordinatorAvailable,postedCashCents:v.progress.postedCashCents,attributedGiftCount:v.progress.attributedGiftCount,unlinkedCount:v.progress.unlinkedCount,voidedGiftCount:v.progress.voidedGiftCount,sourceChangedCount:v.progress.sourceChangedCount,asOf:v.progress.asOf,createdAt:r.createdAt,updatedAt:r.updatedAt});for(const row of revisions(r)){if(result.peerFundraiserVersions.length>10000)break;result.peerFundraiserVersions.push({id:r.id+':'+row.version,fundraiserId:r.id,revision:row.version,campaignId:row.campaignId,constituentId:row.constituentId,coordinatorId:row.coordinatorId,goalCents:row.goalCents,status:row.status,visibility:row.visibility,actor:row.actor,at:row.at,reason:row.reason});}for(const a of associations(r.id)){if(result.peerGiftAttributions.length>10000)break;const v=associationView(a,r);result.peerGiftAttributions.push({id:a.id,fundraiserId:r.id,giftId:a.gift_id,revision:a.version,status:a.status,actualDonorId:v.originalSource.donorId,originalGiftRevision:a.gift_version,originalAmountCents:v.originalSource.amountCents,currentGiftRevision:v.currentSource.giftVersion,currentGiftStatus:v.currentSource.status,receivedAmountCents:a.status==='Active'&&v.currentSource.compatible?v.currentSource.amountCents:0,sourceCurrent:v.currentSource.sourceCurrent,linkedBy:a.linked_by,linkedAt:a.linked_at,unlinkedBy:a.unlinked_by,unlinkedAt:a.unlinked_at,reason:a.unlink_reason,asOf:today()});}for(const h of histories(r)){if(result.peerGiftAttributionHistory.length>10000)break;result.peerGiftAttributionHistory.push({id:h.id,attributionId:h.attributionId,fundraiserId:r.id,giftId:h.giftId,revision:h.attributionVersion,fundraiserRevision:h.fundraiserVersion,action:h.action,status:h.status,originalGiftRevision:h.giftVersion,originalAmountCents:h.amountCents,actualDonorId:h.donorId,actor:h.actor,at:h.at,reason:h.reason});}}return result;});}
 return {list:user=>tx(()=>permitted(user).map(r=>view(r,user))),get:(id,user)=>tx(()=>view(find(id,user),user)),progress:(id,user)=>tx(()=>progress(find(id,user))),reportSources,hasPrivateHistory:()=>db.prepare("SELECT 1 FROM peer_fundraiser_versions WHERE json_extract(data,'$.visibility')='Administrators' LIMIT 1").get()!==undefined,hasConstituentReferences,validateMutation,validateDeletion:validateMutation,validateEventPaymentLink:giftId=>{if(db.prepare("SELECT 1 FROM peer_gift_attributions WHERE gift_id=? AND status='Active'").get(giftId))fail(409,'Unlink the peer attribution before adding event payment linkage');},scope,limits};
}
