import {DatabaseSync} from 'node:sqlite';
import {lstatSync} from 'node:fs';
import {createCipheriv,createDecipheriv,createHash,randomBytes} from 'node:crypto';
import {mkdtemp,mkdir,chmod,open,readFile,lstat,rm,link,rename} from 'node:fs/promises';
import {join,resolve,dirname} from 'node:path';
import {backupWorkspace,restoreWorkspace,backupPlatformRegistry,restorePlatformRegistry,parseBackupKey} from './backup.js';

const LEGACY_ID='00000000-0000-4000-8000-000000000001',MAGIC=Buffer.from('WIMBLO-PLATFORM-RECOVERY\n'),MAX_BYTES=128*1024*1024,MAX_TENANTS=1000;
const fail=message=>{throw Error(message);},sha=b=>createHash('sha256').update(b).digest('hex');
const uuid=value=>{if(typeof value!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(value))fail('An explicit recovery UUID and valid tenant UUIDs are required.');return value.toLowerCase();};
const privateWrite=async(path,bytes)=>{const f=await open(path,'wx',0o600);try{await f.writeFile(bytes);await f.sync();}finally{await f.close();}};
const syncDirectory=async path=>{const file=await open(path,'r');try{await file.sync();}finally{await file.close();}};
const absent=async path=>{try{await lstat(path);fail('Recovery destination already exists; overwrite is refused.');}catch(e){if(e.code!=='ENOENT')throw e;}};
const lock=path=>{const metadata=lstatSync(path);if(!metadata.isFile()||metadata.isSymbolicLink())fail('Platform recovery sources must be existing regular databases.');const db=new DatabaseSync(path);try{db.exec('PRAGMA busy_timeout=100; PRAGMA locking_mode=EXCLUSIVE; BEGIN EXCLUSIVE; COMMIT;');return db;}catch(e){db.close();throw e;}};
const artifact=(name,bytes)=>({name,sha256:sha(bytes),bytes:bytes.toString('base64')});
const decode=a=>{if(!a||typeof a.bytes!=='string'||a.bytes.length>MAX_BYTES*1.4)fail('Recovery artifact is invalid.');const bytes=Buffer.from(a.bytes,'base64');if(bytes.toString('base64')!==a.bytes||sha(bytes)!==a.sha256)fail('Recovery artifact checksum is invalid.');return bytes;};

export async function backupPlatform({rootDir,legacyDbPath,outputPath,recoveryId,encryptionKey,offlineConfirmed=false,documentStorageForTenant}={}){
 if(offlineConfirmed!==true)fail('Offline shutdown confirmation is required for consistent platform recovery.');const id=uuid(recoveryId),key=parseBackupKey(encryptionKey),root=resolve(rootDir),output=resolve(outputPath);await absent(output);const temporary=await mkdtemp(join(dirname(output),'.platform-backup-'));await chmod(temporary,0o700);const connections=[];
 try{
  const platform=lock(join(root,'platform.sqlite'));connections.push(platform);const tenants=platform.prepare('SELECT id FROM tenants ORDER BY id').all().map(t=>uuid(t.id));if(tenants.length>MAX_TENANTS||new Set(tenants).size!==tenants.length)fail('Platform tenant inventory is invalid or exceeds the recovery limit.');
  const workspaces=tenants.map(tenantId=>{const path=tenantId===LEGACY_ID?resolve(legacyDbPath):join(root,'tenants',tenantId,'workspace.sqlite');const db=lock(path);connections.push(db);return {tenantId,db};});
  const registry=join(temporary,'registry.wbackup');await backupPlatformRegistry({db:platform,outputPath:registry,tenantId:id,encryptionKey});const artifacts=[artifact('platform',await readFile(registry))];let bytes=artifacts[0].bytes.length;
  for(const {tenantId,db}of workspaces){const outputPath=join(temporary,tenantId+'.wbackup'),documentStorage=typeof documentStorageForTenant==='function'?await documentStorageForTenant(tenantId,db):undefined;await backupWorkspace({db,outputPath,tenantId,encryptionKey,documentStorage});const a=artifact(tenantId,await readFile(outputPath));bytes+=a.bytes.length;if(bytes>MAX_BYTES-4096)fail('Platform recovery bundle exceeds the 128 MiB limit.');artifacts.push(a);}
  const plaintext=Buffer.from(JSON.stringify({version:1,recoveryId:id,createdAt:new Date().toISOString(),tenants,artifacts,mfaDependency:'Retain the same separately managed MFA_ENCRYPTION_KEY.'}));if(plaintext.length>MAX_BYTES-1024)fail('Platform recovery bundle exceeds the 128 MiB limit.');const nonce=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,nonce);cipher.setAAD(Buffer.from('wimblo-platform-v1:'+id));const encrypted=Buffer.concat([cipher.update(plaintext),cipher.final()]),header=Buffer.from(JSON.stringify({version:1,recoveryId:id,nonce:nonce.toString('base64'),tag:cipher.getAuthTag().toString('base64')})),size=Buffer.alloc(4);size.writeUInt32BE(header.length);const archive=Buffer.concat([MAGIC,size,header,encrypted]);if(archive.length>MAX_BYTES)fail('Platform recovery bundle exceeds the 128 MiB limit.');const staged=join(temporary,'root.wrecovery');await privateWrite(staged,archive);await link(staged,output);await syncDirectory(dirname(output));return {outputPath:output,recoveryId:id,archiveSha256:sha(archive),archiveBytes:archive.length,tenantCount:tenants.length,encrypted:true,createdAt:new Date().toISOString(),notice:'Offline locked database and exact document-version recovery bundle. Off-host publication and real restore drills remain separate.'};
 }finally{for(const db of connections.reverse())db.close();key.fill(0);await rm(temporary,{recursive:true,force:true});}
}

export async function restorePlatform({archivePath,destinationRoot,expectedRecoveryId,encryptionKey}={}){
 const id=uuid(expectedRecoveryId),key=parseBackupKey(encryptionKey),destination=resolve(destinationRoot);await absent(destination);let temporary,reserved=false;
 try{
  const file=await open(resolve(archivePath),'r');let archive;try{const metadata=await file.stat();if(!metadata.isFile()||metadata.size>MAX_BYTES||metadata.size<MAGIC.length+4)fail('Platform recovery archive is invalid or too large.');archive=await file.readFile();if(archive.length!==metadata.size)fail('Platform recovery archive changed during reading.');}finally{await file.close();}
  if(!archive.subarray(0,MAGIC.length).equals(MAGIC))fail('Platform recovery archive format is invalid.');const size=archive.readUInt32BE(MAGIC.length),start=MAGIC.length+4;let header;try{if(size<1||size>4096||start+size>=archive.length)throw Error();header=JSON.parse(archive.subarray(start,start+size));}catch{fail('Platform recovery header is invalid.');}if(header.version!==1||uuid(header.recoveryId)!==id)fail('Platform recovery identity does not match.');const nonce=Buffer.from(String(header.nonce),'base64'),tag=Buffer.from(String(header.tag),'base64');if(nonce.length!==12||tag.length!==16)fail('Platform recovery encryption header is invalid.');let manifest;try{const cipher=createDecipheriv('aes-256-gcm',key,nonce);cipher.setAAD(Buffer.from('wimblo-platform-v1:'+id));cipher.setAuthTag(tag);manifest=JSON.parse(Buffer.concat([cipher.update(archive.subarray(start+size)),cipher.final()]));}catch{fail('Platform recovery authentication failed.');}
  if(manifest.version!==1||manifest.recoveryId!==id||!Array.isArray(manifest.tenants)||manifest.tenants.length>MAX_TENANTS||!Array.isArray(manifest.artifacts)||manifest.artifacts.length!==manifest.tenants.length+1)fail('Platform recovery inventory is invalid.');const tenants=manifest.tenants.map(uuid);if(new Set(tenants).size!==tenants.length)fail('Platform recovery tenant inventory is duplicated.');const artifacts=new Map();for(const a of manifest.artifacts){if(artifacts.has(a.name)||!['platform',...tenants].includes(a.name))fail('Platform recovery artifact identity is invalid.');artifacts.set(a.name,decode(a));}if(!artifacts.has('platform')||tenants.some(t=>!artifacts.has(t)))fail('Platform recovery artifact inventory is incomplete.');
  temporary=await mkdtemp(join(dirname(destination),'.platform-restore-'));await chmod(temporary,0o700);const root=join(temporary,'restored');await mkdir(root,{mode:0o700});const registry=join(temporary,'registry.wbackup');await privateWrite(registry,artifacts.get('platform'));const platform=await restorePlatformRegistry({archivePath:registry,destinationPath:join(root,'platform.sqlite'),expectedTenantId:id,encryptionKey});const db=new DatabaseSync(join(root,'platform.sqlite'),{readOnly:true});try{const actual=db.prepare('SELECT id FROM tenants ORDER BY id').all().map(t=>uuid(t.id));if(JSON.stringify(actual)!==JSON.stringify([...tenants].sort()))fail('Restored registry and tenant archives do not match.');}finally{db.close();}
  const restored=[];for(const tenantId of tenants){const parent=join(root,'tenants',tenantId);await mkdir(parent,{recursive:true,mode:0o700});const archivePath=join(temporary,tenantId+'.wbackup');await privateWrite(archivePath,artifacts.get(tenantId));const result=await restoreWorkspace({archivePath,destinationPath:join(parent,'workspace.sqlite'),expectedTenantId:tenantId,encryptionKey});restored.push({tenantId,materializedDocumentRevisions:result.materializedDocumentRevisions,cleared:result.cleared});}
  await mkdir(destination,{mode:0o700});reserved=true;await rename(root,join(destination,'restored'));await syncDirectory(destination);await syncDirectory(dirname(destination));const finalRoot=join(destination,'restored');return {rootDir:finalRoot,legacyDbPath:join(finalRoot,'tenants',LEGACY_ID,'workspace.sqlite'),recoveryId:id,archiveSha256:sha(archive),tenantCount:tenants.length,tenants:restored,platformCleared:platform.cleared,verified:true,restoredAt:new Date().toISOString(),notice:'New offline root verified. Configure both PLATFORM_DATA_DIR and DB_PATH to these returned paths; original live roots are untouched. Retain the same MFA encryption key.'};
 }catch(e){if(reserved)await rm(destination,{recursive:true,force:true});throw e;}finally{key.fill(0);if(temporary)await rm(temporary,{recursive:true,force:true});}
}

export async function publishOffHostPlatformBackup({archivePath,recoveryId,encryptionKey,store}={}){
 const id=uuid(recoveryId);if(store?.private!==true||store?.offHost!==true||typeof store.putImmutable!=='function'||typeof store.readVersion!=='function')fail('A private off-host immutable recovery store is required.');
 const file=await open(resolve(archivePath),'r');let bytes;try{const stat=await file.stat();if(!stat.isFile()||stat.size>MAX_BYTES)fail('Platform recovery archive exceeds the limit.');bytes=await file.readFile();if(bytes.length!==stat.size)fail('Platform recovery archive changed.');}finally{await file.close();}
 const temporary=await mkdtemp(join(dirname(resolve(archivePath)),'.platform-publication-'));await chmod(temporary,0o700);try{const captured=join(temporary,'captured.wrecovery');await privateWrite(captured,bytes);await restorePlatform({archivePath:captured,destinationRoot:join(temporary,'drill'),expectedRecoveryId:id,encryptionKey});}finally{await rm(temporary,{recursive:true,force:true});}
 const archiveSha256=sha(bytes),reference=await store.putImmutable({recoveryId:id,bytes,sha256:archiveSha256});if(typeof reference?.key!=='string'||!reference.key||typeof reference.versionId!=='string'||!reference.versionId)fail('Off-host recovery store returned no immutable version.');const readback=await store.readVersion({recoveryId:id,key:reference.key,versionId:reference.versionId,maxBytes:MAX_BYTES});if(!(readback instanceof Uint8Array)||readback.length!==bytes.length||sha(readback)!==archiveSha256)fail('Off-host platform recovery readback failed.');return {recoveryId:id,key:reference.key,versionId:reference.versionId,archiveSha256,archiveBytes:bytes.length,verified:true,offHost:true,encrypted:true,createdAt:new Date().toISOString(),notice:'Authenticated full-root recovery and exact off-host encrypted version verified. Retention/geography remain operator responsibilities.'};
}

export async function retrieveOffHostPlatformBackup({recoveryId,key,versionId,expectedSha256,outputPath,encryptionKey,store}={}){
 const id=uuid(recoveryId);if(store?.private!==true||store?.offHost!==true||typeof store.readVersion!=='function')fail('A private off-host immutable recovery store is required.');
 if(typeof key!=='string'||!key||key.length>2048||typeof versionId!=='string'||!versionId||versionId.length>1000||typeof expectedSha256!=='string'||!/^[a-f0-9]{64}$/i.test(expectedSha256)||typeof outputPath!=='string'||!outputPath)fail('Exact object key, version, expected SHA256 and new archive path are required.');
 const keyCheck=parseBackupKey(encryptionKey);keyCheck.fill(0);
 const output=resolve(outputPath);await absent(output);const bytes=await store.readVersion({recoveryId:id,key,versionId,maxBytes:MAX_BYTES});if(!(bytes instanceof Uint8Array)||bytes.length<MAGIC.length+4||bytes.length>MAX_BYTES||sha(bytes)!==expectedSha256.toLowerCase())fail('Retrieved recovery archive size or expected checksum does not match.');
 const temporary=await mkdtemp(join(dirname(output),'.platform-retrieval-'));await chmod(temporary,0o700);let published=false;
 try{const captured=join(temporary,'captured.wrecovery');await privateWrite(captured,bytes);const drill=await restorePlatform({archivePath:captured,destinationRoot:join(temporary,'drill'),expectedRecoveryId:id,encryptionKey});await link(captured,output);published=true;await syncDirectory(dirname(output));return {outputPath:output,recoveryId:id,key,versionId,archiveSha256:sha(bytes),archiveBytes:bytes.length,tenantCount:drill.tenantCount,verified:true,encrypted:true,notice:'Exact off-host version and expected checksum verified; authenticated new-root recovery drill completed. Run restore to a new destination and configure its returned paths before activation. Current bounds: 128 MiB and 1,000 tenants; buyer-scale historical recovery remains unaccepted.'};
 }catch(e){if(published)await rm(output,{force:true});throw e;}finally{await rm(temporary,{recursive:true,force:true});}
}
