import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';

const fail=(status,message)=>{const e=new Error(message);e.status=status;throw e;};
const canonical=v=>Array.isArray(v)?'['+v.map(canonical).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}':JSON.stringify(v);
const digest=v=>createHash('sha256').update(canonical(v)).digest('hex');
const text=z.string().trim().min(1).max(2000),identifier=z.string().min(1).max(100),version=z.number().int().min(1),cents=z.number().int().min(0).max(1e12);
const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>Number.isFinite(Date.parse(v))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v,'Use an actual valid calendar date');
const profileSchema=z.object({version:z.number().int().min(0),organizationName:z.string().trim().min(1).max(250),address:text,taxIdentifier:z.string().trim().min(1).max(100),signatureLabel:z.string().trim().min(1).max(250),customFooter:z.string().max(4000),approved:z.literal(true)}).strict();
const extra={noncashDescription:text.optional(),benefitsDescription:text.optional(),benefitValueCents:cents.optional()};
const prepareSchema=z.discriminatedUnion('kind',[
 z.object({kind:z.literal('Individual'),giftId:identifier,profileVersion:version,...extra}).strict(),
 z.object({kind:z.literal('Annual employee'),constituentId:identifier,year:z.number().int().min(1900).max(9998),profileVersion:version}).strict()
]);
const financialFields=['constituentId','amount','type','method','date','allocations','externalRef','campaignId','pledgeId','grantId','giftKind','softCreditId'];
const disclaimer='Organization profile and receipt wording require the client’s tax/legal approval. This register records staff-confirmed printing and hand-signing; it does not determine deductible amounts or certify legal compliance, delivery or email transmission.';

export function installReceiptRoutes(app,{db,list,get,getSettings,audit,csrf,write,admin,transaction}){
 db.exec(`CREATE TABLE IF NOT EXISTS receipt_profiles(id INTEGER PRIMARY KEY CHECK(id=1),version INTEGER NOT NULL,profile TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS receipt_profile_revisions(version INTEGER PRIMARY KEY,profile TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS receipt_preparations(id TEXT PRIMARY KEY,snapshot TEXT NOT NULL,digest TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL,prior_receipt_id TEXT,reissue_reason TEXT);
 CREATE TABLE IF NOT EXISTS receipt_source_links(receipt_id TEXT NOT NULL,gift_id TEXT NOT NULL,PRIMARY KEY(receipt_id,gift_id));
 CREATE TABLE IF NOT EXISTS receipt_issues(receipt_id TEXT PRIMARY KEY,number TEXT UNIQUE NOT NULL,issue_date TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL,confirmation TEXT NOT NULL,prior_receipt_id TEXT UNIQUE);
 CREATE TABLE IF NOT EXISTS receipt_voids(receipt_id TEXT PRIMARY KEY,reason TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS receipt_number_sequence(id INTEGER PRIMARY KEY CHECK(id=1),value INTEGER NOT NULL);
 INSERT OR IGNORE INTO receipt_number_sequence VALUES(1,0);
 CREATE TRIGGER IF NOT EXISTS receipt_profile_history_no_update BEFORE UPDATE ON receipt_profile_revisions BEGIN SELECT RAISE(ABORT,'Receipt profile history is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS receipt_profile_history_no_delete BEFORE DELETE ON receipt_profile_revisions BEGIN SELECT RAISE(ABORT,'Receipt profile history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS receipt_preparation_no_update BEFORE UPDATE ON receipt_preparations BEGIN SELECT RAISE(ABORT,'Receipt originals are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS receipt_preparation_no_delete BEFORE DELETE ON receipt_preparations BEGIN SELECT RAISE(ABORT,'Receipt originals are retained'); END;
 CREATE TRIGGER IF NOT EXISTS receipt_issue_no_update BEFORE UPDATE ON receipt_issues BEGIN SELECT RAISE(ABORT,'Receipt issue history is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS receipt_issue_no_delete BEFORE DELETE ON receipt_issues BEGIN SELECT RAISE(ABORT,'Receipt issue history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS receipt_void_no_update BEFORE UPDATE ON receipt_voids BEGIN SELECT RAISE(ABORT,'Receipt void history is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS receipt_void_no_delete BEFORE DELETE ON receipt_voids BEGIN SELECT RAISE(ABORT,'Receipt void history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS receipt_source_no_update BEFORE UPDATE ON receipt_source_links BEGIN SELECT RAISE(ABORT,'Receipt source links are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS receipt_source_no_delete BEFORE DELETE ON receipt_source_links BEGIN SELECT RAISE(ABORT,'Receipt source links are retained'); END;`);
 const authorized=(req,res,next)=>{if(!req.user)return res.status(401).json({error:'Authentication required'});if(!['admin','staff','viewer'].includes(req.user.role))return res.status(403).json({error:'Your role cannot access receipts'});next();};
 const handler=fn=>(req,res,next)=>{try{fn(req,res);}catch(e){next(e);}};
 app.use('/api/receipts',authorized);app.use('/api/receipt-profile',authorized);
 const profile=()=>{const r=db.prepare('SELECT * FROM receipt_profiles WHERE id=1').get();return r?{version:r.version,...JSON.parse(r.profile),approvedBy:r.actor,approvedAt:r.at}:null;};
 const reference=(collection,r)=>({collection,id:r.id,version:r.version,recordDigest:digest(r)});
 const find=id=>{const r=db.prepare('SELECT * FROM receipt_preparations WHERE id=?').get(id);if(!r)fail(404,'Receipt not found');return r;};
 const present=r=>{const snapshot=JSON.parse(r.snapshot);if(digest(snapshot)!==r.digest)fail(503,'Receipt integrity check failed.');const issue=db.prepare('SELECT * FROM receipt_issues WHERE receipt_id=?').get(r.id),voided=db.prepare('SELECT * FROM receipt_voids WHERE receipt_id=?').get(r.id);return {id:r.id,version:voided?3:issue?2:1,status:voided?'Voided':issue?'Issued':'Prepared',number:issue?.number??null,preparationDigest:r.digest,...snapshot,createdBy:r.actor,createdAt:r.at,priorReceiptId:r.prior_receipt_id,reissueReason:r.reissue_reason,issue:issue?{number:issue.number,issueDate:issue.issue_date,actorId:issue.actor,at:issue.at,...JSON.parse(issue.confirmation)}:null,void:voided?{reason:voided.reason,actorId:voided.actor,at:voided.at}:null,replacements:db.prepare('SELECT id FROM receipt_preparations WHERE prior_receipt_id=? ORDER BY at,id').all(r.id).map(v=>v.id),delivery:'No email sent; physical printing and hand-signing are staff confirmations.',notice:disclaimer};};
 function validateGift(g){
  if(g.status!=='Posted'||g.type==='Fee payment')fail(409,'Receipts require posted non-fee source gifts. Voids and fees are excluded.');
  day.parse(g.date);if(!Number.isSafeInteger(g.amount)||g.amount<=0)fail(400,'Gift value must be positive safe integer cents.');
  if(!Array.isArray(g.allocations)||!g.allocations.length||g.allocations.some(a=>!Number.isSafeInteger(a.amount)||a.amount<=0)||g.allocations.reduce((n,a)=>n+BigInt(a.amount),0n)!==BigInt(g.amount))fail(400,'Gift allocations must reconcile to the source value.');
  if((g.type==='In-kind')!==(g.method==='In-kind'))fail(400,'In-kind gift type and method must agree.');
 }
 function prepare(p){
  const approved=profile();if(!approved)fail(409,'An administrator must configure and approve the organization receipt profile first.');if(approved.version!==p.profileVersion)fail(409,'Receipt profile changed. Reload the approved version.');
  let recipient,gifts;
  if(p.kind==='Individual'){const gift=get('gifts',p.giftId);validateGift(gift);gifts=[gift];recipient=get('constituents',gift.constituentId);
   if(gift.type==='In-kind'){if(!p.noncashDescription||p.benefitsDescription!==undefined||p.benefitValueCents!==undefined)fail(400,'Noncash receipts require a description and do not assign a tax value.');}
   else if(gift.type==='Sponsorship'){if(p.noncashDescription!==undefined||!p.benefitsDescription||p.benefitValueCents===undefined)fail(400,'Sponsorship receipts require disclosed benefits description and benefitValueCents, including an explicit zero if no benefits.');}
   else if(p.noncashDescription!==undefined||p.benefitsDescription!==undefined||p.benefitValueCents!==undefined)fail(400,'Descriptions/benefit values apply only to noncash or sponsorship sources.');
  }else{if(p.year>new Date().getUTCFullYear())fail(400,'Use a current or historical calendar year.');recipient=get('constituents',p.constituentId);if(recipient.type!=='Employee')fail(400,'Annual employee receipts require an Employee constituent.');
   gifts=list('gifts').filter(g=>g.constituentId===recipient.id&&g.type==='Employee giving'&&g.method==='Payroll'&&g.status==='Posted'&&day.parse(g.date).slice(0,4)===String(p.year)).sort((a,b)=>a.id.localeCompare(b.id));if(!gifts.length)fail(400,'Employee has no posted payroll Employee giving in the selected calendar year.');for(const g of gifts)validateGift(g);
  }
  if(recipient.mergedInto)fail(409,'This receipt identity was merged. Select the surviving constituent.');
  if(recipient.preference==='Do not contact')fail(403,'Do not contact: receipt preparation is excluded for this recipient.');
  if(gifts.length>10000)fail(413,'Annual receipt exceeds 10,000 source gifts.');
  const noncash=p.kind==='Individual'&&gifts[0].type==='In-kind';let total=0n;for(const g of gifts)if(g.type!=='In-kind')total+=BigInt(g.amount);if(total>BigInt(Number.MAX_SAFE_INTEGER))fail(400,'Receipt total exceeds safe integer cents.');
  return {kind:p.kind,profile:approved,recipient:{id:recipient.id,name:String(recipient.name||''),email:String(recipient.email||''),preference:recipient.preference},calendarYear:p.kind==='Annual employee'?p.year:null,monetaryCents:Number(total),noncashDescription:noncash?p.noncashDescription:null,benefits:p.kind==='Individual'&&gifts[0].type==='Sponsorship'?{description:p.benefitsDescription,valueCents:p.benefitValueCents}:null,giftCount:gifts.length,gifts:gifts.map(g=>({id:g.id,date:g.date,type:g.type,reference:String(g.externalRef||''),monetaryCents:g.type==='In-kind'?0:g.amount})),references:[reference('constituents',recipient),...gifts.map(g=>reference('gifts',g))],request:p,semantics:noncash?'Noncash description only. No assigned tax value or deductible amount.':p.kind==='Annual employee'?'Actual calendar-year posted Payroll Employee giving only. Fees, voids, noncash and soft credits excluded.':'Recorded monetary receipts; benefits disclosed separately. No deductible amount is calculated.',taxDeductibility:'Not determined'};
 }
 function storePreparation(p,u,prior=null,reason=null){const snapshot=prepare(p);if(Buffer.byteLength(JSON.stringify(snapshot),'utf8')>1000000)fail(413,'Receipt exceeds the storage limit.');const id=randomUUID(),at=new Date().toISOString(),hash=digest(snapshot);db.prepare('INSERT INTO receipt_preparations VALUES(?,?,?,?,?,?,?)').run(id,JSON.stringify(snapshot),hash,u.id,at,prior,reason);for(const g of snapshot.gifts)db.prepare('INSERT INTO receipt_source_links VALUES(?,?)').run(id,g.id);audit(u,prior?'prepare_receipt_reissue':'prepare_receipt',null,id,{kind:p.kind,profileVersion:p.profileVersion,giftCount:snapshot.giftCount,monetaryCents:snapshot.monetaryCents,digest:hash,priorReceiptId:prior});return present(find(id));}
 const activeForGift=id=>db.prepare('SELECT i.receipt_id,i.number FROM receipt_source_links l JOIN receipt_issues i ON i.receipt_id=l.receipt_id LEFT JOIN receipt_voids v ON v.receipt_id=i.receipt_id WHERE l.gift_id=? AND v.receipt_id IS NULL LIMIT 1').get(id);
 const protectGift=(req,res,next)=>{try{const active=activeForGift(req.params.id);if(active){const current=get('gifts',req.params.id);if(req.path.endsWith('/void')||financialFields.some(k=>Object.hasOwn(req.body||{},k)&&canonical(req.body[k])!==canonical(current[k])))return res.status(409).json({error:'This gift has an active issued receipt. Void the receipt before adjusting financial facts or voiding the gift.',receiptId:active.receipt_id,receiptNumber:active.number});}next();}catch(e){next(e);}};
 // These guards must be mounted before the generic CRM gift handlers.
 app.patch('/api/records/gifts/:id',csrf,write,protectGift);
 app.post('/api/gifts/:id/void',csrf,write,protectGift);
 const protectMerge=(req,res,next)=>{try{const affected=new Set([req.body?.sourceId,req.body?.targetId].filter(v=>typeof v==='string'));if(affected.size){const active=db.prepare('SELECT p.id,p.snapshot,i.number FROM receipt_preparations p JOIN receipt_issues i ON i.receipt_id=p.id LEFT JOIN receipt_voids v ON v.receipt_id=p.id WHERE v.receipt_id IS NULL').all();for(const r of active){const snapshot=JSON.parse(r.snapshot);if(affected.has(snapshot.recipient.id)||snapshot.gifts.some(g=>{const current=get('gifts',g.id);return affected.has(current.constituentId)||affected.has(current.softCreditId);}))return res.status(409).json({error:'An identity selected for merge has active issued receipt history. Void the affected receipt before merging, then prepare and review any replacement.',receiptId:r.id,receiptNumber:r.number});}}next();}catch(e){next(e);}};
 // Identity merge rewires records directly, so generic gift PATCH guards alone
 // cannot protect original issued recipient and source provenance.
 app.post('/api/identity/merge/preview',csrf,admin,protectMerge);
 app.post('/api/identity/merge',csrf,admin,protectMerge);
 app.get('/api/receipt-profile',handler((req,res)=>{const p=profile();res.json({profile:p,configured:Boolean(p),notice:disclaimer,...(req.user.role==='admin'?{revisions:db.prepare('SELECT version,profile,actor,at FROM receipt_profile_revisions ORDER BY version').all().map(r=>({version:r.version,...JSON.parse(r.profile),approvedBy:r.actor,approvedAt:r.at}))}:{})});}));
 app.put('/api/receipt-profile',csrf,admin,handler((req,res)=>{const {version:requested,...p}=profileSchema.parse(req.body);const result=transaction(()=>{const old=profile();if((old?.version??0)!==requested)fail(409,'Receipt profile changed. Reload before saving.');const at=new Date().toISOString(),v=requested+1;db.prepare('INSERT INTO receipt_profiles VALUES(1,?,?,?,?) ON CONFLICT(id) DO UPDATE SET version=excluded.version,profile=excluded.profile,actor=excluded.actor,at=excluded.at').run(v,JSON.stringify(p),req.user.id,at);db.prepare('INSERT INTO receipt_profile_revisions VALUES(?,?,?,?)').run(v,JSON.stringify(p),req.user.id,at);audit(req.user,'approve_receipt_profile',null,null,{version:v});return profile();});res.json({profile:result,notice:disclaimer});}));
 app.post('/api/receipts/prepare',csrf,write,handler((req,res)=>{const p=prepareSchema.parse(req.body),r=transaction(()=>storePreparation(p,req.user));res.status(201).json({receipt:r});}));
 app.post('/api/receipts/:id/issue',csrf,write,handler((req,res)=>{const p=z.object({version:z.literal(1),preparationDigest:z.string().regex(/^[a-f0-9]{64}$/),channel:z.literal('Print'),printed:z.literal(true),handSigned:z.literal(true),issueDate:day}).strict().parse(req.body);const r=transaction(()=>{const old=present(find(req.params.id));if(old.status!=='Prepared')fail(409,'Receipt was already issued. Repeated issue is not permitted.');if(old.preparationDigest!==p.preparationDigest)fail(409,'Receipt snapshot changed. Reopen the prepared receipt.');if(p.issueDate>new Date().toISOString().slice(0,10)||old.gifts.some(g=>g.date>p.issueDate))fail(400,'Issue date must be an actual nonfuture date on or after the source transactions.');const current=prepare(old.request);if(digest(current)!==old.preparationDigest)fail(409,'Profile, source records, preferences or annual membership changed. Prepare and review a new receipt.');
   if(old.priorReceiptId){const prior=present(find(old.priorReceiptId));if(prior.status!=='Voided')fail(409,'Void the previous issued receipt before issuing its replacement.');if(db.prepare('SELECT 1 FROM receipt_issues WHERE prior_receipt_id=?').get(old.priorReceiptId))fail(409,'The previous receipt already has an issued replacement.');}
   for(const g of old.gifts){const active=activeForGift(g.id);if(active)fail(409,'A source gift already has an active issued receipt. Void it before issuing another.');}
   db.prepare('UPDATE receipt_number_sequence SET value=value+1 WHERE id=1').run();const n=db.prepare('SELECT value FROM receipt_number_sequence WHERE id=1').get().value,number='R-'+String(n).padStart(8,'0'),at=new Date().toISOString();db.prepare('INSERT INTO receipt_issues VALUES(?,?,?,?,?,?,?)').run(old.id,number,p.issueDate,req.user.id,at,JSON.stringify({channel:p.channel,printed:true,handSigned:true,confirmation:'Staff log of actual printing and hand-signing, not independently verified delivery.'}),old.priorReceiptId);audit(req.user,'issue_receipt',null,old.id,{number,issueDate:p.issueDate,profileVersion:old.profile.version,giftCount:old.giftCount,monetaryCents:old.monetaryCents,priorReceiptId:old.priorReceiptId,channel:'Print',staffConfirmed:true});return present(find(old.id));});res.json({receipt:r});}));
 app.post('/api/receipts/:id/void',csrf,write,handler((req,res)=>{const p=z.object({version,reason:text}).strict().parse(req.body);const r=transaction(()=>{const old=present(find(req.params.id));if(old.version!==p.version)fail(409,'Receipt changed. Refresh before voiding.');if(old.status!=='Issued')fail(409,'Only an active issued receipt can be voided.');const at=new Date().toISOString();db.prepare('INSERT INTO receipt_voids VALUES(?,?,?,?)').run(old.id,p.reason,req.user.id,at);audit(req.user,'void_receipt',null,old.id,{number:old.number});return present(find(old.id));});res.json({receipt:r});}));
 app.post('/api/receipts/:id/reissue',csrf,write,handler((req,res)=>{const p=z.object({profileVersion:version,reason:text,giftId:identifier.optional(),...extra}).strict().parse(req.body);const r=transaction(()=>{const old=present(find(req.params.id));if(old.status!=='Voided')fail(409,'Void the issued original receipt before preparing a replacement.');if(db.prepare('SELECT 1 FROM receipt_issues WHERE prior_receipt_id=?').get(old.id))fail(409,'Original already has an issued replacement; use that receipt for later correction.');let next={...old.request,profileVersion:p.profileVersion};if(old.kind==='Individual'){for(const k of Object.keys(extra))delete next[k];for(const k of ['giftId','noncashDescription','benefitsDescription','benefitValueCents'])if(p[k]!==undefined)next[k]=p[k];}else if(p.giftId||Object.keys(extra).some(k=>p[k]!==undefined))fail(400,'Annual replacements use the original employee and calendar year.');return storePreparation(prepareSchema.parse(next),req.user,old.id,p.reason);});res.status(201).json({receipt:r});}));
 app.get('/api/receipts',handler((req,res)=>{const q=z.object({q:z.string().trim().max(200).optional(),giftId:identifier.optional(),constituentId:identifier.optional(),status:z.enum(['Prepared','Issued','Voided']).optional()}).strict().parse(req.query),rows=[];for(const r of db.prepare('SELECT * FROM receipt_preparations ORDER BY at DESC,id DESC').iterate()){const p=present(r);if(q.status&&p.status!==q.status||q.giftId&&!p.gifts.some(g=>g.id===q.giftId)||q.constituentId&&p.recipient.id!==q.constituentId||q.q&&!JSON.stringify({number:p.number,name:p.recipient.name,references:p.gifts.map(g=>g.reference)}).toLowerCase().includes(q.q.toLowerCase()))continue;rows.push(p);if(rows.length===100)break;}res.json({receipts:rows,limit:100,notice:disclaimer});}));
 app.get('/api/receipts/:id',handler((req,res)=>res.json({receipt:present(find(req.params.id))})));
 return {prepareReceipt:prepare,activeReceiptForGift:activeForGift};
}
