import {randomUUID} from 'node:crypto';
import {buildReportCatalog,validateReportDefinition,runCustomReport,ReportError,REPORT_LIMITS} from '../src/reportEngine.js';

// Definitions live beside each workspace's records; the extra scope key also
// prevents accidental sharing when a host uses one connection for several tenants.
export function installReportingRoutes(app,{list,audit,csrf,write,transaction,db,collections}){
 db.exec(`CREATE TABLE IF NOT EXISTS custom_reports(id TEXT NOT NULL, scope TEXT NOT NULL, version INTEGER NOT NULL, definition TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(scope,id))`);
 const adminEntities=new Set(['identityAliases','migrationBatches','migrationMappings','receiptProfiles','receiptProfileRevisions','workspaceUsers','workspaceSettings','auditHistory','tributes','tributeVersions','tributeNotifications','tributeNotificationFinalizations','tributeNotificationWithdrawals']);
 const enforceSourceRole=(entity,user)=>{if(adminEntities.has(entity)&&user.role!=='admin')throw new ReportError('This report source requires administrator access.',403);};
 const requiredRole=(entity,user)=>adminEntities.has(entity)||['documents','documentRevisions','reportDeliveries','customReportDefinitions','grantMilestones','grantMilestoneVersions','grantMilestoneEvidence'].includes(entity)&&user.role==='admin'?'admin':'authenticated';
 const scope=req=>String(req?.tenantId??req?.tenant?.id??'workspace');
 const authorized=user=>{if(!user)throw new ReportError('Sign in to use reports.',401);if(!['admin','staff','viewer'].includes(user.role))throw new ReportError('Your role cannot access reports.',403);};
 const data=req=>Object.fromEntries(collections.map(c=>[c,list(c,req)]));
 const json=value=>{try{const parsed=JSON.parse(value);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:{};}catch{throw new ReportError('Stored report metadata is invalid. Ask an administrator to reconcile it.',503);}};
 const hasTable=name=>Boolean(db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(name));
 const rows=sql=>db.prepare(sql+' LIMIT '+(REPORT_LIMITS.sourceRows+1)).all();
 const centsValue=value=>{if(value==null)return null;if(typeof value==='string'&&!/^\d+$/.test(value)||typeof value!=='string'&&!Number.isSafeInteger(value))throw new ReportError('Stored metadata money must be exact integer cents.',503);const n=BigInt(value);if(n<0n||n>BigInt(Number.MAX_SAFE_INTEGER))throw new ReportError('Stored metadata money exceeds safe integer cents.',503);return Number(n);};
 const templateMeta=value=>{const p=json(value);return Object.fromEntries(['name','kind','subject','body'].filter(k=>typeof p[k]==='string').map(k=>[k,p[k]]));};
 const safeDefinition=value=>{const p=json(value);return {name:typeof p.name==='string'?p.name:null,entity:typeof p.entity==='string'?p.entity:null,columns:Array.isArray(p.columns)?p.columns.filter(v=>typeof v==='string').slice(0,20):[],filters:Array.isArray(p.filters)?p.filters.slice(0,12).map(f=>Object.fromEntries(['field','op','value'].filter(k=>Object.hasOwn(f||{},k)&&(['field','op'].includes(k)?typeof f[k]==='string':['string','number'].includes(typeof f[k])||Array.isArray(f[k])&&f[k].every(v=>['string','number'].includes(typeof v)))).map(k=>[k,f[k]]))):[],groupBy:Array.isArray(p.groupBy)?p.groupBy.filter(v=>typeof v==='string').slice(0,3):[],aggregates:Array.isArray(p.aggregates)?p.aggregates.slice(0,8).map(a=>Object.fromEntries(['op','field','label'].filter(k=>typeof a?.[k]==='string').map(k=>[k,a[k]]))):[],includeVoided:p.includeVoided===true};};
 function metadata(req){
  authorized(req.user);const result={},admin=req.user.role==='admin',people=new Map(list('constituents',req).map(c=>[c.id,c]));
  const add=(entity,table,sql,project)=>{if(hasTable(table))result[entity]=rows(sql).map(project);};
  if(hasTable('documents')&&hasTable('document_revisions')){
   const where=admin?'':" WHERE d.visibility<>'Administrators'";
   result.documents=rows('SELECT d.*, (SELECT COUNT(*) FROM document_revisions r WHERE r.document_id=d.id) AS revision_count, r.filename,r.mime,length(r.bytes) AS latest_size FROM documents d LEFT JOIN document_revisions r ON r.document_id=d.id AND r.revision=(SELECT MAX(x.revision) FROM document_revisions x WHERE x.document_id=d.id)'+where+' ORDER BY d.id').map(r=>({id:r.id,collection:r.collection,recordId:r.record_id,title:r.title,category:r.category,visibility:r.visibility,status:r.status,evidenceDate:r.evidence_date,archived:Boolean(r.archived),createdAt:r.created_at,updatedAt:r.updated_at,retentionUntil:r.retention_until,revisionCount:r.revision_count,latestFilename:r.filename,latestMime:r.mime,latestSize:r.latest_size}));
   result.documentRevisions=rows('SELECT r.document_id,r.revision,r.filename,r.mime,length(r.bytes) AS size,r.sha256,r.actor,r.at,r.metadata,d.collection,d.record_id,d.title,d.visibility FROM document_revisions r JOIN documents d ON d.id=r.document_id'+where+' ORDER BY r.document_id,r.revision').map(r=>{const m=json(r.metadata);return {id:r.document_id+':'+r.revision,documentId:r.document_id,collection:r.collection,recordId:r.record_id,title:r.title,visibility:r.visibility,revision:r.revision,filename:r.filename,mime:r.mime,size:r.size,sha256:r.sha256,actor:r.actor,at:r.at,metadata:Object.fromEntries(['title','category','visibility','status','evidenceDate'].filter(k=>typeof m[k]==='string'||m[k]===null).map(k=>[k,m[k]]))};}).filter(r=>admin||r.metadata.visibility==='Workspace');
  }
  add('households','households','SELECT * FROM households ORDER BY id',r=>{const memberIds=hasTable('household_members')?db.prepare('SELECT constituent_id FROM household_members WHERE household_id=? ORDER BY constituent_id').all(r.id).map(m=>m.constituent_id):[];return {id:r.id,name:r.name,address:r.address,memberIds,memberCount:memberIds.length,createdAt:r.created_at,updatedAt:r.updated_at};});
  if(hasTable('households'))add('householdMemberships','household_members','SELECT m.household_id,m.constituent_id,h.name FROM household_members m JOIN households h ON h.id=m.household_id ORDER BY m.household_id,m.constituent_id',r=>({id:r.household_id+':'+r.constituent_id,householdId:r.household_id,householdName:r.name,constituentId:r.constituent_id}));
  if(admin){
   add('identityAliases','identity_aliases','SELECT source_id,target_id,reason,actor,at FROM identity_aliases ORDER BY source_id',r=>({id:r.source_id,sourceId:r.source_id,targetId:r.target_id,sourceName:people.get(r.source_id)?.name||null,targetName:people.get(r.target_id)?.name||null,reason:r.reason,actor:r.actor,at:r.at}));
   add('migrationMappings','migration_mapping','SELECT source,collection,external_id,record_id,batch_id FROM migration_mapping ORDER BY source,collection,external_id',r=>({id:JSON.stringify([r.source,r.collection,r.external_id]),source:r.source,collection:r.collection,externalId:r.external_id,recordId:r.record_id,batchId:r.batch_id}));
   add('migrationBatches','import_batches','SELECT id,source,file_key,committed_at,actor,result FROM import_batches ORDER BY id',r=>{const p=json(r.result),s=p.summary||{},c=p.reconciliation||{};return {id:r.id,source:r.source,fileKey:r.file_key,committedAt:r.committed_at,actor:r.actor,valid:p.valid===true,totalRows:s.rowCount??null,createCount:s.createCounts?Object.values(s.createCounts).reduce((n,v)=>n+(Number.isSafeInteger(v)?v:0),0):null,mappedCount:s.reusedRows??null,errorRows:s.errorRows??null,giftCount:s.gifts??null,allocationCount:s.allocationCount??null,...Object.fromEntries(['newGiftTotalCents','allocationTotalCents','monetaryContributionCents','noncashValueCents','feePaymentCents'].map(k=>[k,centsValue(s[k])])),actualNewGiftCents:centsValue(c.actualNewGiftCents)};});
  }
  result.customReportDefinitions=db.prepare('SELECT id,definition,created_at,updated_at FROM custom_reports WHERE scope=? ORDER BY id LIMIT '+(REPORT_LIMITS.sourceRows+1)).all(scope(req)).map(r=>{const d=safeDefinition(r.definition);return {id:r.id,...d,columnCount:d.columns.length,filterCount:d.filters.length,groupCount:d.groupBy.length,calculationCount:d.aggregates.length,createdAt:r.created_at,updatedAt:r.updated_at};}).filter(r=>admin||!adminEntities.has(r.entity));
  add('reportSchedules','report_schedules','SELECT id,report_id,name,owner_id,cadence,next_run,status,created_at,updated_at FROM report_schedules ORDER BY id',r=>({id:r.id,reportId:r.report_id,name:r.name,ownerId:r.owner_id,cadence:r.cadence,nextRun:r.next_run,status:r.status,createdAt:r.created_at,updatedAt:r.updated_at}));
  if(hasTable('report_schedules'))add('reportDeliveries','report_deliveries','SELECT d.id,d.schedule_id,d.scheduled_at,d.executed_at,d.status,d.report_version,d.result,d.error,s.report_id,s.name FROM report_deliveries d JOIN report_schedules s ON s.id=d.schedule_id ORDER BY d.id',r=>{const p=r.result?json(r.result):null;let sourceDenied=false;try{assertStoredReportAccess(p,req.user,req);}catch(e){if(e.status!==403)throw e;sourceDenied=true;}const restricted=sourceDenied||p&&(p.requiredRole==='admin'||!p.requiredRole&&(adminEntities.has(p.definition?.entity)||['documents','documentRevisions','reportDeliveries','customReportDefinitions'].includes(p.definition?.entity)));return {id:r.id,scheduleId:r.schedule_id,reportId:r.report_id,name:r.name,scheduledAt:r.scheduled_at,executedAt:r.executed_at,status:r.status,reportVersion:r.report_version,error:r.error,resultSummary:!p||!admin&&restricted?null:{matchedRows:Number.isSafeInteger(p.matchedRows)?p.matchedRows:null,totalResultRows:Number.isSafeInteger(p.totalResultRows)?p.totalResultRows:null,returnedRows:Array.isArray(p.rows)?p.rows.length:null,columnCount:Array.isArray(p.columns)?p.columns.length:null,truncated:p.truncated===true,textTruncated:p.textTruncated===true}};});
  add('correspondenceTemplates','correspondence_templates','SELECT id,definition,created_at,updated_at FROM correspondence_templates ORDER BY id',r=>({id:r.id,...templateMeta(r.definition),createdAt:r.created_at,updatedAt:r.updated_at}));
  add('correspondenceTemplateRevisions','correspondence_template_revisions','SELECT template_id,version,definition,actor,at FROM correspondence_template_revisions ORDER BY template_id,version',r=>({id:r.template_id+':'+r.version,templateId:r.template_id,revision:r.version,...templateMeta(r.definition),actor:r.actor,at:r.at}));
  add('correspondencePreparations','correspondence_preparations','SELECT id,snapshot,actor,at FROM correspondence_preparations ORDER BY id',r=>{const p=json(r.snapshot),items=Array.isArray(p.items)?p.items:[];let monetary=0n,noncash=0n;const gifts=new Set();for(const item of items){monetary+=BigInt(centsValue(item.semantics?.monetaryCents)??0);noncash+=BigInt(centsValue(item.semantics?.noncashCents)??0);for(const ref of item.references||[])if(ref.collection==='gifts'&&typeof ref.id==='string')gifts.add(ref.id);}return {id:r.id,templateId:p.template?.id??null,templateName:p.template?.name??null,templateKind:p.template?.kind??null,templateRevision:p.template?.version??null,channel:p.channel??null,organizationName:p.organizationName??null,recipientCount:items.length,giftCount:gifts.size,monetaryCents:centsValue(monetary.toString()),noncashCents:centsValue(noncash.toString()),delivery:'Not sent',status:hasTable('correspondence_finalizations')&&db.prepare('SELECT 1 FROM correspondence_finalizations WHERE preparation_id=?').get(r.id)?'Finalized':'Prepared',actor:r.actor,at:r.at};});
  add('correspondenceFinalizations','correspondence_finalizations','SELECT preparation_id,actor,at FROM correspondence_finalizations ORDER BY preparation_id',r=>({id:r.preparation_id,preparationId:r.preparation_id,actor:r.actor,at:r.at,humanReviewed:true,delivery:'Not sent'}));
  const gifts=new Map(list('gifts',req).map(g=>[g.id,g])),events=new Map(list('events',req).map(e=>[e.id,e])),campaigns=new Map(list('campaigns',req).map(c=>[c.id,c])),asOf=new Date().toISOString().slice(0,10);
  const pick=(p,keys)=>Object.fromEntries(keys.filter(k=>typeof p[k]==='string'||typeof p[k]==='number'||typeof p[k]==='boolean'||p[k]===null).map(k=>[k,p[k]]));
  const correctionReferences=value=>{let refs;try{refs=JSON.parse(value);}catch{throw new ReportError('Stored financial correction references are invalid.',503);}if(!Array.isArray(refs)||refs.some(ref=>!ref||!['constituents','campaigns','pledges','grants','designations'].includes(ref.collection)||typeof ref.id!=='string'||!Number.isSafeInteger(ref.version)||ref.version<1))throw new ReportError('Stored financial correction references are invalid.',503);return refs.map(ref=>({collection:ref.collection,id:ref.id,revision:ref.version}));};
  const correctionFacts=(value,prefix)=>{const p=json(value),facts=Object.fromEntries(['Date','ConstituentId','Type','Method','CampaignId','Pledge','PledgeId','GrantId','SoftCreditId','ExternalRef','GiftKind'].map(key=>[prefix+key,typeof p[key[0].toLowerCase()+key.slice(1)]==='string'?p[key[0].toLowerCase()+key.slice(1)]:null]));if(!Array.isArray(p.allocations))throw new ReportError('Stored financial correction allocations are invalid.',503);const allocations=p.allocations.map(a=>{if(typeof a?.designationId!=='string')throw new ReportError('Stored financial correction allocation source is invalid.',503);return {designationId:a.designationId,amount:centsValue(a.amount)};});const amount=centsValue(p.amount);if(amount===null||allocations.some(a=>a.amount===null)||allocations.reduce((sum,a)=>sum+BigInt(a.amount),0n)!==BigInt(amount))throw new ReportError('Stored financial correction allocations do not reconcile.',503);return {...facts,[prefix+'AmountCents']:amount,[prefix+'Allocations']:allocations};};
  if(hasTable('gift_financial_corrections'))result.giftFinancialCorrections=rows('SELECT * FROM gift_financial_corrections ORDER BY gift_id,from_version,id').filter(r=>gifts.has(r.gift_id)).map(r=>{const actor=json(r.actor_json);let changed;try{changed=JSON.parse(r.changed_fields);}catch{throw new ReportError('Stored financial correction fields are invalid.',503);}const allowed=new Set(['constituentId','amount','type','method','date','campaignId','allocations','externalRef','softCreditId','pledge','pledgeId','grantId','giftKind']);if(!Array.isArray(changed)||changed.some(field=>!allowed.has(field)))throw new ReportError('Stored financial correction fields are invalid.',503);return {id:r.id,giftId:r.gift_id,fromRevision:r.from_version,toRevision:r.to_version,changedFields:changed,reason:r.reason,actorId:typeof actor.id==='string'?actor.id:null,actorName:typeof actor.name==='string'?actor.name:null,actorRole:typeof actor.role==='string'?actor.role:null,at:r.at,...correctionFacts(r.before_json,'before'),...correctionFacts(r.after_json,'after'),sourceVersions:{before:correctionReferences(r.before_references),after:correctionReferences(r.after_references)}};});

  const fundraisingMeta=value=>{const p=json(value),original=p.originalSnapshot||{};return {...(p.latestFollowup&&typeof p.latestFollowup==='object'&&!Array.isArray(p.latestFollowup)?{latestFollowup:pick(p.latestFollowup,['date','outcome','previousDueDate','nextActionDate','actor'])}:{}),...pick(p,['nextActionStatus','kind','name','donorId','ownerId','stage','nextActionDate','instrument','status','campaignId','originalGiftId','matchingOrganizationId','ratioNumerator','ratioDenominator','notes']),...Object.fromEntries(['expectedAmount','commitmentAmount','capAmount'].map(k=>[k,centsValue(p[k])])),donorName:people.get(p.donorId)?.name??null,campaignName:campaigns.get(p.campaignId)?.name??null,matchingOrganizationName:people.get(p.matchingOrganizationId)?.name??null,originalGiftRevision:Number.isSafeInteger(original.version)?original.version:Number.isSafeInteger(p.originalGiftVersion)?p.originalGiftVersion:null,originalGiftAmountCents:centsValue(original.amount)};};
  add('fundraisingRecords','fundraising_records','SELECT id,version,data,created_at,updated_at FROM fundraising_records ORDER BY id',r=>({id:r.id,...fundraisingMeta(r.data),revision:r.version,createdAt:r.created_at,updatedAt:r.updated_at}));
  add('fundraisingVersions','fundraising_versions','SELECT record_id,version,data,actor,at FROM fundraising_versions ORDER BY record_id,version',r=>({id:r.record_id+':'+r.version,recordId:r.record_id,revision:r.version,...fundraisingMeta(r.data),actor:r.actor,at:r.at}));
  add('fundraisingAssociations','fundraising_associations','SELECT id,record_id,gift_id,version,status,gift_version,snapshot,created_at,unlinked_at,unlink_reason FROM fundraising_associations ORDER BY id',r=>{const p=json(r.snapshot),g=gifts.get(r.gift_id),received=r.status==='active'&&g?.status==='Posted'&&g.date<=asOf;return {id:r.id,recordId:r.record_id,giftId:r.gift_id,revision:r.version,status:r.status,giftRevision:r.gift_version,associatedDonorId:typeof p.constituentId==='string'?p.constituentId:null,associatedAmountCents:centsValue(p.amount),associatedType:typeof p.type==='string'?p.type:null,associatedGiftKind:typeof p.giftKind==='string'?p.giftKind:null,associatedCampaignId:typeof p.campaignId==='string'?p.campaignId:null,associatedDate:typeof p.date==='string'?p.date:null,currentGiftAmountCents:centsValue(g?.amount),currentGiftStatus:g?.status??null,receivedAmountCents:received?centsValue(g.amount):0,asOf,createdAt:r.created_at,unlinkedAt:r.unlinked_at,unlinkReason:r.unlink_reason};});
  add('fundraisingActivity','fundraising_activity','SELECT id,record_id,actor,date,note,action,at FROM fundraising_activity ORDER BY id',r=>({id:r.id,recordId:r.record_id,actor:r.actor,date:r.date,note:r.note,action:r.action,at:r.at}));
  if(hasTable('task_assignments')){const visibleTasks=new Set(list('tasks',req).map(task=>task.id));result.taskAssignmentHistory=rows('SELECT * FROM task_assignments ORDER BY task_id,to_version,id').filter(r=>visibleTasks.has(r.task_id)).map(r=>{const before=json(r.before_owner),after=json(r.after_owner),actor=json(r.actor);return {id:r.id,taskId:r.task_id,fromRevision:r.from_version,toRevision:r.to_version,beforeOwnerId:typeof before.id==='string'?before.id:null,beforeOwnerName:typeof before.name==='string'?before.name:null,afterOwnerId:typeof after.id==='string'?after.id:null,afterOwnerName:typeof after.name==='string'?after.name:null,reason:r.reason,actorId:typeof actor.id==='string'?actor.id:null,actorName:typeof actor.name==='string'?actor.name:null,at:r.at};});}
  if(hasTable('correspondence_fulfillments')){const visibleCommunications=new Set(list('communications',req).map(c=>c.id));result.correspondenceFulfillments=rows('SELECT * FROM correspondence_fulfillments ORDER BY preparation_id,gift_id,id').filter(r=>gifts.has(r.gift_id)&&visibleCommunications.has(r.communication_id)).map(r=>{const source=json(r.source_json);return {id:r.id,preparationId:r.preparation_id,giftId:r.gift_id,sourceGiftRevision:r.source_gift_version,acknowledgmentGiftRevision:r.acknowledgment_gift_version,communicationId:r.communication_id,date:r.date,channel:r.channel,actorId:r.actor,reason:r.reason,at:r.at,templateId:typeof source.templateId==='string'?source.templateId:null,templateRevision:Number.isSafeInteger(source.templateVersion)?source.templateVersion:null,recipientId:typeof source.recipientId==='string'?source.recipientId:null,finalizedBy:typeof source.finalizedBy==='string'?source.finalizedBy:null,finalizedAt:typeof source.finalizedAt==='string'?source.finalizedAt:null,manualConfirmation:true,applicationSent:false};});}
  const receiptProfile=value=>pick(json(value),['organizationName','address','taxIdentifier','signatureLabel','customFooter','approved']);
  if(admin){
   add('receiptProfiles','receipt_profiles','SELECT id,version,profile,actor,at FROM receipt_profiles ORDER BY id',r=>({id:String(r.id),revision:r.version,...receiptProfile(r.profile),actor:r.actor,at:r.at}));
   add('receiptProfileRevisions','receipt_profile_revisions','SELECT version,profile,actor,at FROM receipt_profile_revisions ORDER BY version',r=>({id:String(r.version),revision:r.version,...receiptProfile(r.profile),actor:r.actor,at:r.at}));
   add('workspaceUsers','users','SELECT id,name,email,role,active,version FROM users ORDER BY id',r=>({id:r.id,name:r.name,email:r.email,role:r.role,active:Boolean(r.active),revision:r.version}));
   add('workspaceSettings','settings','SELECT id,data FROM settings ORDER BY id',r=>({id:String(r.id),...pick(json(r.data),['organizationName','fiscalStartMonth'])}));
   add('auditHistory','audit','SELECT id,actor,action,collection,record_id,at,details FROM audit ORDER BY id',r=>({id:String(r.id),actor:r.actor,actorName:hasTable('users')?db.prepare('SELECT name FROM users WHERE id=?').get(r.actor)?.name??null:null,action:r.action,collection:r.collection,recordId:r.record_id,at:r.at,detailCount:Object.keys(json(r.details)).length}));
  }
  if(hasTable('receipt_preparations')&&hasTable('receipt_issues')&&hasTable('receipt_voids')){
   const receipts=rows('SELECT p.id,p.snapshot,p.actor,p.at,p.prior_receipt_id,p.reissue_reason,i.number,i.issue_date,i.confirmation,v.reason AS void_reason,v.at AS voided_at FROM receipt_preparations p LEFT JOIN receipt_issues i ON i.receipt_id=p.id LEFT JOIN receipt_voids v ON v.receipt_id=p.id ORDER BY p.id');
   result.receiptHistory=receipts.map(r=>{const p=json(r.snapshot),confirmation=r.confirmation?json(r.confirmation):{};return {id:r.id,kind:p.kind??null,recipientId:p.recipient?.id??null,recipientName:p.recipient?.name??null,calendarYear:p.calendarYear??null,monetaryCents:centsValue(p.monetaryCents),benefitValueCents:centsValue(p.benefits?.valueCents),benefitDescription:typeof p.benefits?.description==='string'?p.benefits.description:null,noncashDescription:typeof p.noncashDescription==='string'?p.noncashDescription:null,giftCount:Number.isSafeInteger(p.giftCount)?p.giftCount:null,profileRevision:Number.isSafeInteger(p.profile?.version)?p.profile.version:null,organizationName:typeof p.profile?.organizationName==='string'?p.profile.organizationName:null,taxDeductibility:p.taxDeductibility==='Not determined'?'Not determined':null,semantics:typeof p.semantics==='string'?p.semantics:null,status:r.voided_at?'Voided':r.number?'Issued':'Prepared',number:r.number,issueDate:r.issue_date,staffConfirmedPrint:confirmation.printed===true,staffConfirmedHandSign:confirmation.handSigned===true,createdAt:r.at,actor:r.actor,priorReceiptId:r.prior_receipt_id,reissueReason:r.reissue_reason,voidReason:r.void_reason,voidedAt:r.voided_at};});
   result.receiptGiftReferences=[];
   for(const r of receipts){const p=json(r.snapshot);for(const g of Array.isArray(p.gifts)?p.gifts:[]){if(result.receiptGiftReferences.length>REPORT_LIMITS.sourceRows)break;result.receiptGiftReferences.push({id:r.id+':'+g.id,receiptId:r.id,giftId:typeof g.id==='string'?g.id:null,date:typeof g.date==='string'?g.date:null,type:typeof g.type==='string'?g.type:null,monetaryCents:centsValue(g.monetaryCents),reference:typeof g.reference==='string'?g.reference:null,receiptStatus:r.voided_at?'Voided':r.number?'Issued':'Prepared'});}}
  }
  const eventMeta=r=>({eventId:r.event_id,eventName:events.get(r.event_id)?.name??null});
  add('eventTables','event_seating','SELECT * FROM event_seating ORDER BY id',r=>({id:r.id,...eventMeta(r),name:r.name,seats:r.seats,revision:r.version,createdAt:r.created_at,updatedAt:r.updated_at}));
  add('eventSeatAssignments','event_seat_assignments','SELECT * FROM event_seat_assignments ORDER BY id',r=>({id:r.id,...eventMeta(r),tableId:r.table_id,constituentId:r.constituent_id,constituentName:people.get(r.constituent_id)?.name??null,seatNumber:r.seat_number,status:r.status,revision:r.version,assignedAt:r.assigned_at,cancelledAt:r.cancelled_at,cancelReason:r.cancel_reason}));
  add('eventTickets','event_tickets','SELECT * FROM event_tickets ORDER BY id',r=>({id:r.id,...eventMeta(r),constituentId:r.constituent_id,constituentName:people.get(r.constituent_id)?.name??null,priceCents:centsValue(r.price),status:r.status,revision:r.version,issuedAt:r.issued_at,checkedInAt:r.checked_in_at,cancelledAt:r.cancelled_at,cancelReason:r.cancel_reason}));
  add('eventSponsors','event_sponsorships','SELECT * FROM event_sponsorships ORDER BY id',r=>{let benefits;try{benefits=JSON.parse(r.benefits);}catch{throw new ReportError('Stored event benefits are invalid.',503);}return {id:r.id,...eventMeta(r),sponsorId:r.sponsor_id,sponsorName:people.get(r.sponsor_id)?.name??null,name:r.name,status:r.status||'Active',everFulfilled:Boolean(r.fulfilled_once),commitmentAmountCents:centsValue(r.amount),activeCommitmentAmountCents:r.status==='Cancelled'?0:centsValue(r.amount),benefits:Array.isArray(benefits)?benefits.map(b=>({name:typeof b.name==='string'?b.name:null,completed:b.completed===true})):[],revision:r.version,createdAt:r.created_at,updatedAt:r.updated_at};});
  if(result.eventSponsors)result.eventSponsors=result.eventSponsors.filter(r=>events.has(r.eventId)&&people.has(r.sponsorId));
  add('eventAuctionItems','event_auction_items','SELECT * FROM event_auction_items ORDER BY id',r=>({id:r.id,...eventMeta(r),name:r.name,startingBidCents:centsValue(r.starting_bid),minIncrementCents:centsValue(r.min_increment),description:r.description,status:r.status,winningBidId:r.winning_bid_id,revision:r.version,createdAt:r.created_at,updatedAt:r.updated_at}));
  add('eventAuctionBids','event_auction_bids','SELECT * FROM event_auction_bids ORDER BY id',r=>({id:r.id,itemId:r.item_id,bidderId:r.bidder_id,bidderName:people.get(r.bidder_id)?.name??null,amountCents:centsValue(r.amount),actor:r.actor,at:r.at}));
  if(hasTable('event_ticket_transitions')&&hasTable('event_tickets'))result.eventTicketTransitions=rows('SELECT h.*,t.event_id FROM event_ticket_transitions h JOIN event_tickets t ON t.id=h.ticket_id ORDER BY h.ticket_id,h.to_version,h.id').filter(r=>events.has(r.event_id)).map(r=>{const before=r.before_json?json(r.before_json):{},after=json(r.after_json),actor=json(r.actor_json);return {id:r.id,ticketId:r.ticket_id,eventId:r.event_id,action:r.action,fromRevision:r.from_version,toRevision:r.to_version,eventRevision:r.event_version,reason:r.reason,actorId:typeof actor.id==='string'?actor.id:null,actorName:typeof actor.name==='string'?actor.name:null,at:r.at,beforeStatus:typeof before.status==='string'?before.status:null,afterStatus:typeof after.status==='string'?after.status:null,beforeCheckedIn:Boolean(before.checked_in_at),afterCheckedIn:Boolean(after.checked_in_at),beforeCheckedInAt:typeof before.checked_in_at==='string'?before.checked_in_at:null,afterCheckedInAt:typeof after.checked_in_at==='string'?after.checked_in_at:null};});
  if(hasTable('event_commitment_transitions')){
   const owners={sponsorship:'event_sponsorships',auction:'event_auction_items'};
   result.eventCommitmentTransitions=rows('SELECT * FROM event_commitment_transitions ORDER BY owner_type,owner_id,to_version,id').filter(r=>{const table=owners[r.owner_type],owner=table&&hasTable(table)?db.prepare('SELECT event_id FROM '+table+' WHERE id=?').get(r.owner_id):null;return owner&&events.has(owner.event_id);}).map(r=>{
    const before=r.before_json?json(r.before_json):null,after=json(r.after_json),source=json(r.source_json),actor=json(r.actor_json),eventId=source.event?.id;
    const owner=db.prepare('SELECT event_id FROM '+owners[r.owner_type]+' WHERE id=?').get(r.owner_id);
    if(eventId!==owner.event_id||source.event?.version!==r.event_version||after.id!==r.owner_id||after.event_id!==eventId||before&&(before.id!==r.owner_id||before.event_id!==eventId))throw new ReportError('Stored event commitment source links are inconsistent.',503);
    const retainedBids=[source.winningBid,source.highestBid].filter(Boolean).map(bid=>{const current=hasTable('event_auction_bids')?db.prepare('SELECT item_id,amount FROM event_auction_bids WHERE id=?').get(bid.id):null;if(r.owner_type!=='auction'||typeof bid.id!=='string'||bid.itemId!==r.owner_id||!current||current.item_id!==r.owner_id||current.amount!==centsValue(bid.amount))throw new ReportError('Stored event commitment bid sources are inconsistent.',503);return {id:bid.id,itemId:bid.itemId,amountCents:centsValue(bid.amount)};});
    if(!Array.isArray(source.receiptLinks)||source.receiptLinks.length>REPORT_LIMITS.sourceRows)throw new ReportError('Stored event commitment receipt sources are invalid.',503);
    const receiptLinks=source.receiptLinks.map(link=>{const current=hasTable('event_payment_links')?db.prepare('SELECT owner_type,owner_id,gift_id,revenue_case FROM event_payment_links WHERE id=?').get(link.id):null;if(typeof link.id!=='string'||typeof link.giftId!=='string'||!Number.isSafeInteger(link.giftVersion)||link.giftVersion<1||!gifts.has(link.giftId)||!current||current.owner_type!==r.owner_type||current.owner_id!==r.owner_id||current.gift_id!==link.giftId||current.revenue_case!==link.revenueCase||centsValue(link.amount)===null||gifts.get(link.giftId).amount!==centsValue(link.amount))throw new ReportError('Stored event commitment receipt sources are inconsistent or unavailable.',503);return {id:link.id,giftId:link.giftId,giftRevision:link.giftVersion,status:typeof link.status==='string'?link.status:null,date:typeof link.date==='string'?link.date:null,amountCents:centsValue(link.amount),revenueCase:link.revenueCase};});
    const amount=record=>{if(!record)return null;if(r.owner_type==='sponsorship')return centsValue(record.amount);if(!record.winning_bid_id)return 0;const bid=retainedBids.find(b=>b.id===record.winning_bid_id);if(!bid)throw new ReportError('Stored event commitment winning bid is unavailable.',503);return bid.amountCents;};
    const originalBefore=amount(before),originalAfter=amount(after),active=(record,value)=>!record?null:record.status===(r.owner_type==='sponsorship'?'Active':'Closed')?value:0;
    const referencedTotal=receiptLinks.reduce((n,link)=>n+BigInt(link.amountCents??0),0n);
    return {id:r.id,eventId,ownerType:r.owner_type,ownerId:r.owner_id,action:r.action,fromRevision:r.from_version,toRevision:r.to_version,eventRevision:r.event_version,reason:r.reason,actorId:typeof actor.id==='string'?actor.id:null,actorName:typeof actor.name==='string'?actor.name:null,at:r.at,beforeStatus:before?.status??null,afterStatus:after.status??null,beforeName:before?.name??null,afterName:after.name??null,beforeCommitmentAmountCents:originalBefore,afterCommitmentAmountCents:originalAfter,beforeActiveCommitmentAmountCents:active(before,originalBefore),afterActiveCommitmentAmountCents:active(after,originalAfter),beforeWinningBidId:before?.winning_bid_id??null,afterWinningBidId:after.winning_bid_id??null,winningBidId:source.winningBid?.id??null,winningBidAmountCents:source.winningBid?centsValue(source.winningBid.amount):null,highestBidId:source.highestBid?.id??null,highestBidAmountCents:source.highestBid?centsValue(source.highestBid.amount):null,receiptLinkCount:receiptLinks.length,referencedReceiptAmountCents:centsValue(referencedTotal.toString()),sourceReferences:{event:{id:eventId,revision:r.event_version},bids:[...new Map(retainedBids.map(b=>[b.id,b])).values()],receiptLinks}};
   });
  }
  const eventOwner=(type,key)=>{const table={ticket:'event_tickets',sponsorship:'event_sponsorships',auction:'event_auction_items'}[type];return table&&hasTable(table)?db.prepare('SELECT event_id FROM '+table+' WHERE id=?').get(key)?.event_id??null:null;};
  add('eventPayments','event_payment_links','SELECT * FROM event_payment_links ORDER BY id',r=>{const g=gifts.get(r.gift_id),eventId=eventOwner(r.owner_type,r.owner_id);return {id:r.id,ownerType:r.owner_type,ownerId:r.owner_id,eventId,eventName:events.get(eventId)?.name??null,giftId:r.gift_id,revenueCase:r.revenue_case,constituentId:g?.constituentId??null,constituentName:people.get(g?.constituentId)?.name??null,amountCents:centsValue(g?.amount),date:g?.date??null,type:g?.type??null,status:g?.status??null,receivedAmountCents:g?.status==='Posted'&&g.date<=asOf?centsValue(g.amount):0,asOf,actor:r.actor,at:r.at};});
  if(hasTable('grant_milestones')&&hasTable('grant_milestone_history')){
   const grantRows=rows('SELECT * FROM grant_milestones ORDER BY id');
   const histories=new Map(grantRows.map(r=>[r.id,db.prepare('SELECT milestone_id,version,snapshot,action,reason,actor,at FROM grant_milestone_history WHERE milestone_id=? ORDER BY version LIMIT '+(REPORT_LIMITS.sourceRows+1)).all(r.id)]));
   const grantData=value=>{const p=json(value),source=p.source||{},owner=p.owner||{};return {...pick(p,['name','kind','dueDate','status','requiredRole']),grantId:typeof source.id==='string'?source.id:null,grantName:typeof source.name==='string'?source.name:null,grantRevision:Number.isSafeInteger(source.version)?source.version:null,funderId:typeof source.funderId==='string'?source.funderId:null,requestedAmountCents:centsValue(source.requestedCents),awardedAmountCents:centsValue(source.awardedCents),awardDate:typeof source.awardDate==='string'?source.awardDate:null,sourceStage:typeof source.stage==='string'?source.stage:null,ownerId:typeof owner.id==='string'?owner.id:null,ownerName:typeof owner.name==='string'?owner.name:null,ownerRole:typeof owner.role==='string'?owner.role:null,ownerRevision:Number.isSafeInteger(owner.version)?owner.version:null};};
   const publicGrantSnapshot=p=>{if(p.requiredRole==='admin')return false;if(!p.completion)return true;const d=p.completion.document;if(!d||d.visibility==='Administrators'||d.revisionVisibility==='Administrators'||!hasTable('documents'))return false;const current=db.prepare('SELECT visibility FROM documents WHERE id=?').get(d.id);return Boolean(current)&&current.visibility!=='Administrators';};
   // An oversized history cannot establish that all retained evidence is public.
   const visibleGrant=r=>admin||publicGrantSnapshot(json(r.data))&&histories.get(r.id).length<=REPORT_LIMITS.sourceRows&&histories.get(r.id).every(h=>publicGrantSnapshot(json(h.snapshot)));
   const visible=grantRows.filter(visibleGrant);result.grantMilestones=visible.map(r=>({id:r.id,...grantData(r.data),revision:r.version,createdAt:r.created_at,updatedAt:r.updated_at}));result.grantMilestoneVersions=[];result.grantMilestoneEvidence=[];
   for(const r of visible)for(const h of histories.get(r.id)){
    if(result.grantMilestoneVersions.length<=REPORT_LIMITS.sourceRows)result.grantMilestoneVersions.push({id:r.id+':'+h.version,milestoneId:r.id,...grantData(h.snapshot),revision:h.version,action:h.action,reason:h.reason,actor:h.actor,at:h.at});
    const p=json(h.snapshot),completion=p.completion,d=completion?.document;if(!d)continue;
    if(result.grantMilestoneEvidence.length<=REPORT_LIMITS.sourceRows){const current=hasTable('documents')?db.prepare('SELECT archived FROM documents WHERE id=?').get(d.id):null;result.grantMilestoneEvidence.push({id:r.id+':'+h.version,milestoneId:r.id,milestoneRevision:h.version,grantId:r.grant_id,grantName:p.source?.name??null,documentId:typeof d.id==='string'?d.id:null,documentVersion:Number.isSafeInteger(d.version)?d.version:null,documentRevision:Number.isSafeInteger(d.revision)?d.revision:null,documentTitle:typeof d.title==='string'?d.title:null,documentCategory:typeof d.category==='string'?d.category:null,documentStatus:typeof d.status==='string'?d.status:null,documentEvidenceDate:typeof d.evidenceDate==='string'?d.evidenceDate:null,documentVisibility:typeof d.visibility==='string'?d.visibility:null,revisionVisibility:typeof d.revisionVisibility==='string'?d.revisionVisibility:null,documentFilename:typeof d.filename==='string'?d.filename:null,documentSize:Number.isSafeInteger(d.size)?d.size:null,documentArchived:current?Boolean(current.archived):null,completedDate:typeof completion.completedDate==='string'?completion.completedDate:null,completionReference:typeof completion.reference==='string'?completion.reference:null,staffConfirmed:completion.staffConfirmed===true,actor:h.actor,at:h.at});}
   }
  }
  if(admin&&hasTable('tributes')){
   const tributeData=(p,source)=>{const g=source?.gift||gifts.get(p.giftId),recipient=source?.recipient||people.get(p.notificationRecipientId),honoree=source?.honoree||people.get(p.honoreeId);return {...pick(p,['giftId','type','honoreeId','notificationRecipientId','visibility','donorDisclosureApproved','notes']),honoreeName:typeof p.honoreeName==='string'&&p.honoreeName?p.honoreeName:honoree?.name??null,notificationRecipientName:typeof recipient?.name==='string'?recipient.name:null,messagePresent:typeof p.message==='string'&&p.message.length>0,sourceGiftAmountCents:centsValue(g?.amount),sourceGiftType:g?.type??null,sourceGiftStatus:g?.status??null,sourceGiftDate:g?.date??null};};
   add('tributes','tributes','SELECT id,version,data,created_at,updated_at FROM tributes ORDER BY id',r=>({id:r.id,...tributeData(json(r.data)),revision:r.version,createdAt:r.created_at,updatedAt:r.updated_at}));
   add('tributeVersions','tribute_versions','SELECT tribute_id,version,snapshot,actor,at FROM tribute_versions ORDER BY tribute_id,version',r=>{const p=json(r.snapshot);return {id:r.tribute_id+':'+r.version,tributeId:r.tribute_id,...tributeData(p.definition||{},p.source),revision:r.version,actor:r.actor,at:r.at};});
   if(hasTable('tribute_notification_finalizations')){
    add('tributeNotifications','tribute_notifications','SELECT n.id,n.tribute_id,n.snapshot,n.actor,n.at,f.actor AS finalized_by,f.at AS finalized_at,w.at AS withdrawn_at FROM tribute_notifications n LEFT JOIN tribute_notification_finalizations f ON f.notification_id=n.id LEFT JOIN tribute_notification_withdrawals w ON w.notification_id=n.id ORDER BY n.id',r=>{const p=json(r.snapshot);return {id:r.id,tributeId:r.tribute_id,tributeRevision:Number.isSafeInteger(p.tributeVersion)?p.tributeVersion:null,...pick(p,['type','honoreeName','honoreeId','visibility','channel','subject']),recipientId:typeof p.recipient?.id==='string'?p.recipient.id:null,recipientName:typeof p.recipient?.name==='string'?p.recipient.name:null,giftId:typeof p.source?.giftId==='string'?p.source.giftId:null,giftDate:typeof p.source?.giftDate==='string'?p.source.giftDate:null,status:r.withdrawn_at?'Withdrawn':r.finalized_at?'Finalized':'Draft',delivery:'Not sent',actor:r.actor,createdAt:r.at,finalizedBy:r.finalized_by,finalizedAt:r.finalized_at};});
    if(hasTable('tribute_notifications'))add('tributeNotificationWithdrawals','tribute_notification_withdrawals','SELECT w.notification_id,w.version,w.reason,w.actor,w.at,w.confirmed_not_sent,n.tribute_id FROM tribute_notification_withdrawals w JOIN tribute_notifications n ON n.id=w.notification_id ORDER BY w.notification_id',r=>({id:r.notification_id,notificationId:r.notification_id,tributeId:r.tribute_id,revision:r.version,reason:r.reason,actorId:r.actor,at:r.at,confirmedNotSent:r.confirmed_not_sent===1,delivery:'Not sent'}));
    if(hasTable('tribute_notifications'))add('tributeNotificationFinalizations','tribute_notification_finalizations','SELECT f.notification_id,f.actor,f.at,n.tribute_id FROM tribute_notification_finalizations f JOIN tribute_notifications n ON n.id=f.notification_id ORDER BY f.notification_id',r=>({id:r.notification_id,notificationId:r.notification_id,tributeId:r.tribute_id,actor:r.actor,at:r.at,humanReviewed:true,delivery:'Not sent'}));
   }
  }
  return result;
 }
 const snapshot=req=>{const records={...data(req),...metadata(req)};return {records,catalog:buildReportCatalog(records,Object.keys(records))};};
 const present=row=>row?{id:row.id,version:row.version,...JSON.parse(row.definition),createdAt:row.created_at,updatedAt:row.updated_at}:null;
 const getReport=(id,user,req={})=>{authorized(user);if(typeof id!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id))throw new ReportError('Use a valid report ID.');const report=present(db.prepare('SELECT * FROM custom_reports WHERE scope=? AND id=?').get(scope(req),id));if(!report)throw new ReportError('Report not found.',404);if(adminEntities.has(report.entity)&&user.role!=='admin')throw new ReportError('This report source requires administrator access.',403);return report;};
 const assertStoredReportAccess=(snapshot,user,req={})=>{
  authorized(user);if(!snapshot||user.role==='admin')return;
  if(snapshot.requiredRole==='admin'||adminEntities.has(snapshot.definition?.entity))throw new ReportError('This retained report requires administrator access.',403);
  if(snapshot.definition?.entity==='giftFinancialCorrections'){
   if(snapshot.giftCorrectionPrivacy!==1||!Array.isArray(snapshot.giftCorrectionSources)||snapshot.giftCorrectionSources.length>REPORT_LIMITS.sourceRows)throw new ReportError('This older retained financial correction report requires administrator review. Run a current report with your own permissions.',403);
   const visibleGifts=new Set(list('gifts',{...req,user}).map(g=>g.id));
   for(const ref of snapshot.giftCorrectionSources){
    if(typeof ref?.correctionId!=='string'||typeof ref?.giftId!=='string'||!hasTable('gift_financial_corrections')||!visibleGifts.has(ref.giftId)||!db.prepare('SELECT 1 FROM gift_financial_corrections WHERE id=? AND gift_id=?').get(ref.correctionId,ref.giftId))throw new ReportError('Current financial correction source access is unavailable. Run a current report with your own permissions.',403);
   }
  }
  if(snapshot.definition?.entity==='taskAssignmentHistory'){
   if(snapshot.taskAssignmentPrivacy!==1||!Array.isArray(snapshot.taskAssignmentSources)||snapshot.taskAssignmentSources.length>REPORT_LIMITS.sourceRows)throw new ReportError('This older retained assignment report requires administrator review. Run a current report with your own permissions.',403);
   const visibleTasks=new Set(list('tasks',{...req,user}).map(task=>task.id));
   for(const ref of snapshot.taskAssignmentSources)if(typeof ref?.assignmentId!=='string'||typeof ref?.taskId!=='string'||!hasTable('task_assignments')||!visibleTasks.has(ref.taskId)||!db.prepare('SELECT 1 FROM task_assignments WHERE id=? AND task_id=?').get(ref.assignmentId,ref.taskId))throw new ReportError('Current task assignment source access is unavailable. Run a current report with your own permissions.',403);
  }
  if(snapshot.definition?.entity==='eventTicketTransitions'){
   if(snapshot.eventTicketTransitionPrivacy!==1||!Array.isArray(snapshot.eventTicketTransitionSources)||snapshot.eventTicketTransitionSources.length>REPORT_LIMITS.sourceRows)throw new ReportError('This older retained ticket transition report requires administrator review. Run a current report with your own permissions.',403);
   const visibleEvents=new Set(list('events',{...req,user}).map(event=>event.id));
   for(const ref of snapshot.eventTicketTransitionSources)if(typeof ref?.transitionId!=='string'||typeof ref?.ticketId!=='string'||typeof ref?.eventId!=='string'||!hasTable('event_tickets')||!hasTable('event_ticket_transitions')||!visibleEvents.has(ref.eventId)||!db.prepare('SELECT 1 FROM event_tickets t JOIN event_ticket_transitions h ON h.ticket_id=t.id WHERE t.id=? AND t.event_id=? AND h.id=?').get(ref.ticketId,ref.eventId,ref.transitionId))throw new ReportError('Current event ticket source access is unavailable. Run a current report with your own permissions.',403);
  }
  if(snapshot.definition?.entity==='correspondenceFulfillments'){
   if(snapshot.correspondenceFulfillmentPrivacy!==1||!Array.isArray(snapshot.correspondenceFulfillmentSources)||snapshot.correspondenceFulfillmentSources.length>REPORT_LIMITS.sourceRows)throw new ReportError('This older retained correspondence fulfillment report requires administrator review. Run a current report with your own permissions.',403);
   const visibleGifts=new Set(list('gifts',{...req,user}).map(g=>g.id)),visibleCommunications=new Set(list('communications',{...req,user}).map(c=>c.id));
   for(const ref of snapshot.correspondenceFulfillmentSources)if(typeof ref?.fulfillmentId!=='string'||typeof ref?.giftId!=='string'||typeof ref?.communicationId!=='string'||typeof ref?.preparationId!=='string'||!hasTable('correspondence_fulfillments')||!visibleGifts.has(ref.giftId)||!visibleCommunications.has(ref.communicationId)||!db.prepare('SELECT 1 FROM correspondence_fulfillments WHERE id=? AND gift_id=? AND communication_id=? AND preparation_id=?').get(ref.fulfillmentId,ref.giftId,ref.communicationId,ref.preparationId))throw new ReportError('Current correspondence fulfillment source access is unavailable. Run a current report with your own permissions.',403);
  }
  if(snapshot.definition?.entity==='eventCommitmentTransitions'){
   if(snapshot.eventCommitmentPrivacy!==1||!Array.isArray(snapshot.eventCommitmentSources)||snapshot.eventCommitmentSources.length>REPORT_LIMITS.sourceRows)throw new ReportError('This older retained commitment transition report requires administrator review. Run a current report with your own permissions.',403);
   const visibleEvents=new Set(list('events',{...req,user}).map(event=>event.id)),visibleGifts=new Set(list('gifts',{...req,user}).map(gift=>gift.id)),owners={sponsorship:'event_sponsorships',auction:'event_auction_items'};
   for(const ref of snapshot.eventCommitmentSources){
    const table=owners[ref?.ownerType];if(!table||typeof ref.transitionId!=='string'||typeof ref.ownerId!=='string'||typeof ref.eventId!=='string'||!visibleEvents.has(ref.eventId)||!hasTable(table)||!hasTable('event_commitment_transitions')||!Array.isArray(ref.bidIds)||!Array.isArray(ref.receiptLinks)||ref.bidIds.length>REPORT_LIMITS.sourceRows||ref.receiptLinks.length>REPORT_LIMITS.sourceRows||!db.prepare('SELECT 1 FROM '+table+' o JOIN event_commitment_transitions h ON h.owner_id=o.id AND h.owner_type=? WHERE o.id=? AND o.event_id=? AND h.id=?').get(ref.ownerType,ref.ownerId,ref.eventId,ref.transitionId))throw new ReportError('Current event commitment source access is unavailable. Run a current report with your own permissions.',403);
    for(const bidId of ref.bidIds)if(ref.ownerType!=='auction'||typeof bidId!=='string'||!hasTable('event_auction_bids')||!db.prepare('SELECT 1 FROM event_auction_bids WHERE id=? AND item_id=?').get(bidId,ref.ownerId))throw new ReportError('Retained event bid source access is unavailable.',403);
    for(const link of ref.receiptLinks)if(typeof link?.id!=='string'||typeof link?.giftId!=='string'||!visibleGifts.has(link.giftId)||!hasTable('event_payment_links')||!db.prepare('SELECT 1 FROM event_payment_links WHERE id=? AND gift_id=? AND owner_type=? AND owner_id=?').get(link.id,link.giftId,ref.ownerType,ref.ownerId))throw new ReportError('Retained event receipt source access is unavailable.',403);
   }
  }
  if(snapshot.definition?.entity==='documentRevisions'){
   if(snapshot.documentRevisionPrivacy!==1||!Array.isArray(snapshot.documentRevisionSources)||snapshot.documentRevisionSources.length>REPORT_LIMITS.sourceRows)throw new ReportError('This older retained revision report requires administrator review. Run a current report with your own permissions.',403);
   for(const ref of snapshot.documentRevisionSources){
    if(typeof ref?.documentId!=='string'||!Number.isSafeInteger(ref.revision)||ref.revision<1||!hasTable('documents')||!hasTable('document_revisions'))throw new ReportError('This retained revision report cannot establish current source access.',403);
    const document=db.prepare('SELECT visibility FROM documents WHERE id=?').get(ref.documentId),revision=db.prepare('SELECT metadata FROM document_revisions WHERE document_id=? AND revision=?').get(ref.documentId,ref.revision);
    if(document?.visibility!=='Workspace'||!revision||json(revision.metadata).visibility!=='Workspace')throw new ReportError('Current or retained document evidence is private. Run a current report with your own permissions.',403);
   }
  }
 };
 const privacyMarker=definition=>definition.entity==='documentRevisions'?{documentRevisionPrivacy:1}:definition.entity==='giftFinancialCorrections'?{giftCorrectionPrivacy:1}:definition.entity==='taskAssignmentHistory'?{taskAssignmentPrivacy:1}:definition.entity==='eventTicketTransitions'?{eventTicketTransitionPrivacy:1}:definition.entity==='correspondenceFulfillments'?{correspondenceFulfillmentPrivacy:1}:definition.entity==='eventCommitmentTransitions'?{eventCommitmentPrivacy:1}:{};
 const runReport=(id,user,req={})=>{const report=getReport(id,user,req),{id:reportId,version,createdAt,updatedAt,...definition}=report;const {records,catalog}=snapshot({...req,user});return {...runCustomReport(records,definition,catalog),...privacyMarker(definition),requiredRole:requiredRole(definition.entity,user),reportId,version,executedAt:new Date().toISOString()};};
 const handler=fn=>(req,res,next)=>{try{authorized(req.user);fn(req,res);}catch(error){next(error);}};
 app.get('/api/custom-reports/catalog',handler((req,res)=>res.json(snapshot(req).catalog)));
 app.get('/api/custom-reports',handler((req,res)=>res.json({reports:db.prepare('SELECT * FROM custom_reports WHERE scope=? ORDER BY updated_at DESC,id LIMIT 201').all(scope(req)).map(present).filter(r=>req.user.role==='admin'||!adminEntities.has(r.entity))})));
 app.post('/api/custom-reports/run',csrf,handler((req,res)=>{enforceSourceRole(req.body?.entity,req.user);const {records,catalog}=snapshot(req);res.json({...runCustomReport(records,req.body,catalog),...privacyMarker(req.body),requiredRole:requiredRole(req.body.entity,req.user),executedAt:new Date().toISOString()});}));
 app.get('/api/custom-reports/:id/run',handler((req,res)=>res.json(runReport(req.params.id,req.user,req))));
 app.post('/api/custom-reports',csrf,write,handler((req,res)=>{
  const report=transaction(()=>{enforceSourceRole(req.body?.entity,req.user);const {catalog}=snapshot(req),definition=validateReportDefinition(req.body,catalog);if(db.prepare('SELECT count(*) AS n FROM custom_reports WHERE scope=?').get(scope(req)).n>=200)throw new ReportError('This workspace has 200 saved reports. Edit an existing definition.',409);const id=randomUUID(),now=new Date().toISOString();db.prepare('INSERT INTO custom_reports(id,scope,version,definition,created_at,updated_at) VALUES(?,?,1,?,?,?)').run(id,scope(req),JSON.stringify(definition),now,now);audit(req.user,'create','customReports',id,{version:1,entity:definition.entity});return getReport(id,req.user,req);});res.status(201).json({report});
 }));
 app.patch('/api/custom-reports/:id',csrf,write,handler((req,res)=>{
  const report=transaction(()=>{const previous=getReport(req.params.id,req.user,req);if(!req.body||typeof req.body!=='object'||!Number.isSafeInteger(req.body.version)||req.body.version<1)throw new ReportError('Include the saved report version.');if(req.body.version!==previous.version)throw new ReportError('This report changed. Reload its latest definition before saving.',409);enforceSourceRole(req.body.entity,req.user);const {version,...body}=req.body,{catalog}=snapshot(req),definition=validateReportDefinition(body,catalog);const now=new Date().toISOString();const changed=db.prepare('UPDATE custom_reports SET version=version+1,definition=?,updated_at=? WHERE scope=? AND id=? AND version=?').run(JSON.stringify(definition),now,scope(req),req.params.id,version);if(changed.changes!==1)throw new ReportError('This report changed. Reload before saving.',409);audit(req.user,'update','customReports',previous.id,{version:version+1,entity:definition.entity});return getReport(previous.id,req.user,req);});res.json({report});
 }));
 return {getReport,runReport,executeSavedReport:runReport,assertStoredReportAccess};
}
