import {randomUUID} from 'node:crypto';
import {z} from 'zod';
const fail=(status,message)=>{const e=new Error(message);e.status=status;throw e;};
const intervals={Hourly:3600000,Daily:86400000,Weekly:604800000};
const scheduleSchema=z.object({reportId:z.string().uuid(),name:z.string().trim().min(1).max(250),cadence:z.enum(['Hourly','Daily','Weekly']),startAt:z.iso.datetime()}).strict();
const scheduleChangeSchema=z.object({version:z.number().int().min(1),status:z.enum(['Active','Paused','Retired']),reason:z.string().trim().min(1).max(500).optional()}).strict().superRefine((p,ctx)=>{if(p.status==='Retired'&&!p.reason)ctx.addIssue({code:'custom',path:['reason'],message:'Provide a reason for retiring this schedule.'});if(p.status!=='Retired'&&p.reason!==undefined)ctx.addIssue({code:'custom',path:['reason'],message:'A reason is accepted only when retiring a schedule.'});});

export function installReportScheduleRoutes(app,{db,getReport,runReport,assertStoredReportAccess,csrf,write,audit,isTenantActive=()=>true,ownerAllowed=()=>true,clock=()=>Date.now(),worker=true}){
 db.exec(`CREATE TABLE IF NOT EXISTS report_schedules(id TEXT PRIMARY KEY,report_id TEXT NOT NULL,name TEXT NOT NULL,owner_id TEXT NOT NULL,cadence TEXT NOT NULL,next_run TEXT NOT NULL,status TEXT NOT NULL,version INTEGER NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS report_deliveries(id TEXT PRIMARY KEY,schedule_id TEXT NOT NULL,scheduled_at TEXT NOT NULL,executed_at TEXT NOT NULL,status TEXT NOT NULL,report_version INTEGER,result TEXT,error TEXT,UNIQUE(schedule_id,scheduled_at));
 CREATE TRIGGER IF NOT EXISTS report_delivery_no_update BEFORE UPDATE ON report_deliveries BEGIN SELECT RAISE(ABORT,'Report deliveries are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS report_delivery_no_delete BEFORE DELETE ON report_deliveries BEGIN SELECT RAISE(ABORT,'Report deliveries are retained'); END;`);
 const user=id=>db.prepare('SELECT id,name,email,role,active FROM users WHERE id=?').get(id);
 const view=r=>({id:r.id,reportId:r.report_id,name:r.name,ownerId:r.owner_id,ownerName:user(r.owner_id)?.name||'Unavailable account',cadence:r.cadence,nextRun:r.next_run,status:r.status,version:r.version,createdAt:r.created_at,updatedAt:r.updated_at});
 const find=id=>{const s=db.prepare('SELECT * FROM report_schedules WHERE id=?').get(id);if(!s)fail(404,'Report schedule not found');return s;};
 const canManage=(s,u)=>{if(u.role!=='admin'&&s.owner_id!==u.id)fail(403,'Only the schedule owner or an administrator can change this schedule.');};
 const transaction=fn=>{db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}};
 function runDueReports(time=clock()){
  if(!isTenantActive())return {produced:0,failed:0,suspended:true};let produced=0,failed=0;
  const due=db.prepare("SELECT * FROM report_schedules WHERE status='Active' AND next_run<=? ORDER BY next_run LIMIT 50").all(new Date(time).toISOString());
  for(const candidate of due)transaction(()=>{const s=find(candidate.id);if(s.status!=='Active'||s.next_run>new Date(time).toISOString())return;const owner=user(s.owner_id);let result=null,error=null,status='Produced';
   try{if(!owner?.active||!['admin','staff'].includes(owner.role)||!ownerAllowed(owner))fail(403,'Schedule owner no longer has active report-generation access.');result=runReport(s.report_id,owner,{});if(!ownerAllowed(owner))fail(403,'Schedule owner authentication changed during report generation.');if(JSON.stringify(result).length>1000000)fail(413,'Scheduled result exceeds the storage limit. Narrow the report.');}catch(e){status='Failed';error=e.status===403?e.message:'Report could not be produced. Review the current definition and field availability.';result=null;}
   const inserted=db.prepare('INSERT OR IGNORE INTO report_deliveries VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),s.id,s.next_run,new Date(time).toISOString(),status,result?.version??null,result?JSON.stringify(result):null,error);
   const next=new Date(Date.parse(s.next_run)+(Math.floor((time-Date.parse(s.next_run))/intervals[s.cadence])+1)*intervals[s.cadence]).toISOString();db.prepare('UPDATE report_schedules SET next_run=?,version=version+1,updated_at=? WHERE id=?').run(next,new Date(time).toISOString(),s.id);
   if(inserted.changes){audit(owner||{id:s.owner_id},status==='Produced'?'produce_scheduled_report':'fail_scheduled_report',null,s.id,{reportId:s.report_id,reportVersion:result?.version??null,scheduledAt:s.next_run,lateByMs:Math.max(0,time-Date.parse(s.next_run))});if(status==='Produced'&&!ownerAllowed(owner))fail(403,'Schedule owner authentication changed before report persistence.');status==='Produced'?produced++:failed++;}
  });return {produced,failed};
 }
 app.get('/api/report-schedules',(req,res)=>res.json({schedules:db.prepare("SELECT * FROM report_schedules ORDER BY CASE WHEN status IN ('Active','Paused') THEN 0 ELSE 1 END,next_run,id LIMIT 200").all().map(view),delivery:'Internal',timezone:'UTC',worker:'Runs while the workspace server is running; overdue schedules produce one catch-up result.'}));
 app.post('/api/report-schedules',csrf,write,(req,res)=>{const p=scheduleSchema.parse(req.body);getReport(p.reportId,req.user,req);const start=Date.parse(p.startAt);if(start<clock()-60000||start>clock()+366*86400000)fail(400,'Choose a first run from now through the next year.');const schedule=transaction(()=>{if(db.prepare("SELECT count(*) AS n FROM report_schedules WHERE status IN ('Active','Paused')").get().n>=100)fail(409,'This workspace has 100 active or paused schedules. Retire a schedule you no longer need before creating another.');const id=randomUUID(),at=new Date(clock()).toISOString();db.prepare('INSERT INTO report_schedules VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,p.reportId,p.name,req.user.id,p.cadence,new Date(start).toISOString(),'Active',1,at,at);audit(req.user,'create_report_schedule',null,id,{reportId:p.reportId,cadence:p.cadence,firstRun:p.startAt,delivery:'Internal'});return view(find(id));});res.status(201).json({schedule});});
 app.patch('/api/report-schedules/:id',csrf,write,(req,res)=>{const p=scheduleChangeSchema.parse(req.body);const schedule=transaction(()=>{const s=find(req.params.id);canManage(s,req.user);getReport(s.report_id,req.user,req);if(s.status==='Retired')fail(409,'Retired schedules cannot be changed or resumed. Create a new schedule to generate further reports.');if(s.version!==p.version)fail(409,'Schedule changed. Refresh before saving.');db.prepare('UPDATE report_schedules SET status=?,version=version+1,updated_at=? WHERE id=?').run(p.status,new Date(clock()).toISOString(),s.id);audit(req.user,p.status==='Retired'?'retire_report_schedule':'change_report_schedule',null,s.id,{previousStatus:s.status,status:p.status,...(p.status==='Retired'?{reason:p.reason}:{})});return view(find(s.id));});res.json({schedule});});
 app.get('/api/report-deliveries',(req,res)=>res.json({deliveries:db.prepare('SELECT d.id,d.schedule_id,d.scheduled_at,d.executed_at,d.status,d.report_version,d.error,s.name FROM report_deliveries d JOIN report_schedules s ON s.id=d.schedule_id ORDER BY d.executed_at DESC LIMIT 100').all().map(d=>({id:d.id,scheduleId:d.schedule_id,name:d.name,scheduledAt:d.scheduled_at,executedAt:d.executed_at,status:d.status,reportVersion:d.report_version,error:d.error}))}));
 app.get('/api/report-deliveries/:id',(req,res)=>{const r=db.prepare('SELECT * FROM report_deliveries WHERE id=?').get(req.params.id);if(!r)fail(404,'Scheduled report result not found');const s=find(r.schedule_id);getReport(s.report_id,req.user,req);const snapshot=r.result?JSON.parse(r.result):null;if(assertStoredReportAccess)assertStoredReportAccess(snapshot,req.user,req);const protectedSources=new Set(['documents','documentRevisions','identityAliases','migrationBatches','migrationMappings','reportDeliveries','customReportDefinitions']);if(req.user.role!=='admin'&&(snapshot?.requiredRole==='admin'||(!snapshot?.requiredRole&&protectedSources.has(snapshot?.definition?.entity))))fail(403,'This retained report requires administrator access. Run a current report with your own permissions.');audit(req.user,'read_scheduled_report',null,s.id,{deliveryId:r.id});res.json({delivery:{id:r.id,scheduleId:s.id,name:s.name,scheduledAt:r.scheduled_at,executedAt:r.executed_at,status:r.status,reportVersion:r.report_version,error:r.error,result:snapshot}});});
 const interval=worker?setInterval(()=>{try{runDueReports();}catch(e){console.error('Scheduled report worker could not complete its current cycle.');}},30000):null;interval?.unref();return {runDueReports,close:()=>{if(interval)clearInterval(interval);}};
}
