import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {mfaAccountBinding} from './mfa.js';

const id=z.uuid(),version=z.number().int().min(1),fail=(status,message)=>{const e=new Error(message);e.status=status;throw e;};
const iso=time=>new Date(time).toISOString();

// Internal one-shot owner reminders only. Delivery is a durable inbox row, not
// email, push, contact outreach, task completion or an external action.
export function installTaskReminderRoutes(app,{db,get,audit,csrf,write,transaction,isTenantActive=()=>true,ownerAllowed=()=>true,recheckAccess=()=>false,clock=Date.now,worker=true}){
 db.exec(`CREATE TABLE IF NOT EXISTS task_reminders(id TEXT PRIMARY KEY,task_id TEXT NOT NULL,owner_id TEXT NOT NULL REFERENCES users(id),owner_version INTEGER NOT NULL,owner_binding TEXT NOT NULL,task_version INTEGER NOT NULL,remind_at TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('Active','Delivered','Cancelled','Suppressed')),version INTEGER NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,next_attempt TEXT NOT NULL,attempt_count INTEGER NOT NULL DEFAULT 0);
 CREATE UNIQUE INDEX IF NOT EXISTS task_one_active_reminder ON task_reminders(task_id) WHERE status='Active';
 CREATE INDEX IF NOT EXISTS task_reminder_due ON task_reminders(status,next_attempt,remind_at);
 CREATE TABLE IF NOT EXISTS task_reminder_outcomes(id TEXT PRIMARY KEY,reminder_id TEXT NOT NULL REFERENCES task_reminders(id),reminder_version INTEGER NOT NULL,status TEXT NOT NULL,reason TEXT NOT NULL,at TEXT NOT NULL,retry_at TEXT);
 CREATE TABLE IF NOT EXISTS task_reminder_inbox(id TEXT PRIMARY KEY,reminder_id TEXT NOT NULL UNIQUE REFERENCES task_reminders(id),owner_id TEXT NOT NULL REFERENCES users(id),task_id TEXT NOT NULL,task_version INTEGER NOT NULL,delivered_at TEXT NOT NULL);
 CREATE TRIGGER IF NOT EXISTS task_reminder_no_delete BEFORE DELETE ON task_reminders BEGIN SELECT RAISE(ABORT,'Task reminder history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS task_reminder_outcome_no_update BEFORE UPDATE ON task_reminder_outcomes BEGIN SELECT RAISE(ABORT,'Reminder outcomes are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS task_reminder_outcome_no_delete BEFORE DELETE ON task_reminder_outcomes BEGIN SELECT RAISE(ABORT,'Reminder outcomes are retained'); END;
 CREATE TRIGGER IF NOT EXISTS task_reminder_inbox_no_update BEFORE UPDATE ON task_reminder_inbox BEGIN SELECT RAISE(ABORT,'Internal delivery evidence is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS task_reminder_inbox_no_delete BEFORE DELETE ON task_reminder_inbox BEGIN SELECT RAISE(ABORT,'Internal delivery evidence is retained'); END;`);
 const current=req=>{if(!req?.user||!['admin','staff'].includes(req.user.role))fail(403,'Task reminders require active staff access');if(!isTenantActive())fail(403,'Workspace is suspended');if(!recheckAccess(req))fail(401,'Account access changed. Sign in again');};
 const authorized=(req,res,next)=>{try{current(req);next();}catch(e){next(e);}};
 const action=fn=>(req,res,next)=>{try{fn(req,res);}catch(e){next(e);}};
 for(const prefix of ['/api/task-reminders','/api/reminder-inbox'])app.use(prefix,authorized);
 const find=key=>{const row=db.prepare('SELECT * FROM task_reminders WHERE id=?').get(key);if(!row)fail(404,'Task reminder not found');return row;};
 const own=(row,req)=>{if(row.owner_id!==req.user.id)fail(404,'Task reminder not found');};
 const account=key=>db.prepare('SELECT * FROM users WHERE id=?').get(key);
 function source(row){let task;try{task=get('tasks',row.task_id);}catch(e){if(e.status===404)return {reason:'Task unavailable'};throw e;}const owner=account(row.owner_id);if(!owner?.active||!['admin','staff'].includes(owner.role))return {reason:'Owner unavailable'};if(!ownerAllowed(owner))return {reason:'Owner authentication unavailable'};if(owner.version!==row.owner_version||mfaAccountBinding(owner)!==row.owner_binding)return {reason:'Account changed'};if(task.ownerId!==row.owner_id)return {reason:'Task reassigned'};if(task.status==='Completed')return {reason:'Task completed'};if(task.version!==row.task_version)return {reason:'Task changed'};return {task,owner};}
 const outcomes=key=>db.prepare('SELECT * FROM task_reminder_outcomes WHERE reminder_id=? ORDER BY at DESC,rowid DESC LIMIT 100').all(key).map(row=>({id:row.id,status:row.status,reason:row.reason,at:row.at,retryAt:row.retry_at,reminderVersion:row.reminder_version}));
 function view(row){const s=source(row);return {id:row.id,taskId:row.task_id,taskVersion:row.task_version,ownerVersion:row.owner_version,remindAt:row.remind_at,status:row.status,version:row.version,createdAt:row.created_at,updatedAt:row.updated_at,nextAttempt:row.status==='Active'?row.next_attempt:null,attemptCount:row.attempt_count,taskTitle:s.reason?null:s.task.title,sourceCurrent:!s.reason,lastOutcome:outcomes(row.id)[0]||null};}
 function outcome(row,status,reason,time,retryAt=null){db.prepare('INSERT INTO task_reminder_outcomes VALUES(?,?,?,?,?,?,?)').run(randomUUID(),row.id,row.version+1,status,reason,iso(time),retryAt);}
 function suppress(row,reason,time){db.prepare("UPDATE task_reminders SET status='Suppressed',version=version+1,updated_at=? WHERE id=?").run(iso(time),row.id);outcome(row,'Suppressed',reason,time);audit({id:'system'},'suppress_task_reminder','tasks',row.task_id,{reminderId:row.id,reason,delivery:'Internal only'});}
 function suppressPendingForTenant(time=clock()){let suppressed=0;transaction(()=>{for(const row of db.prepare("SELECT * FROM task_reminders WHERE status='Active' ORDER BY id").all()){suppress(row,'Workspace suspended',time);suppressed++;}});return {delivered:0,suppressed,failed:0,suspended:true};}
 function runDueReminders(time=clock()){
  if(!isTenantActive())return suppressPendingForTenant(time);let delivered=0,suppressed=0,failed=0,attempted=0;
  // Reconcile every bounded Active source, including future reminders, so a
  // reassignment/completion cannot strand capacity behind an uneditable binding.
  const due=db.prepare("SELECT id FROM task_reminders WHERE status='Active' ORDER BY next_attempt,id LIMIT 100").all();
  for(const candidate of due){try{const result=transaction(()=>{const row=find(candidate.id);if(row.status!=='Active')return;
    if(!isTenantActive()){suppress(row,'Workspace suspended',time);return 'Suppressed';}const s=source(row);if(s.reason){suppress(row,s.reason,time);return 'Suppressed';}if(row.remind_at>iso(time)||row.next_attempt>iso(time)||attempted>=50)return;attempted++;
    // The unique reminder key and source checks are inside the same write lock.
    db.prepare('INSERT INTO task_reminder_inbox VALUES(?,?,?,?,?,?)').run(randomUUID(),row.id,row.owner_id,row.task_id,row.task_version,iso(time));db.prepare("UPDATE task_reminders SET status='Delivered',version=version+1,updated_at=?,attempt_count=attempt_count+1 WHERE id=?").run(iso(time),row.id);outcome(row,'Delivered','Delivered to the internal owner inbox',time);audit({id:'system'},'deliver_task_reminder','tasks',row.task_id,{reminderId:row.id,ownerId:row.owner_id,taskVersion:row.task_version,scheduledAt:row.remind_at,deliveredAt:iso(time),delivery:'Internal only'});if(!isTenantActive()||source(row).reason)fail(409,'Reminder source changed before delivery');return 'Delivered';
   });if(result==='Delivered')delivered++;if(result==='Suppressed')suppressed++;}catch(e){failed++;try{const recovery=transaction(()=>{const row=find(candidate.id);if(row.status!=='Active')return;if(!isTenantActive()){suppress(row,'Workspace suspended',time);return 'Suppressed';}if(row.attempt_count>=4){db.prepare('UPDATE task_reminders SET attempt_count=attempt_count+1 WHERE id=?').run(row.id);suppress(row,'Retry limit reached; create a new reminder after review',time);return 'Suppressed';}const retryAt=iso(time+60000);db.prepare('UPDATE task_reminders SET version=version+1,updated_at=?,next_attempt=?,attempt_count=attempt_count+1 WHERE id=?').run(iso(time),retryAt,row.id);outcome(row,'Failed','Internal persistence failed; retry scheduled',time,retryAt);audit({id:'system'},'retry_task_reminder','tasks',row.task_id,{reminderId:row.id,retryAt,delivery:'Not delivered'});return 'Retried';});if(recovery==='Suppressed')suppressed++;}catch{console.error('Task reminder persistence is unavailable. Delivery remains unconfirmed; the worker will retry pending reminders.');}}
  }return {delivered,suppressed,failed,suspended:false};
 }
 app.post('/api/tasks/:id/reminders',authorized,csrf,write,action((req,res)=>{id.parse(req.params.id);const p=z.object({taskVersion:version,ownerVersion:version,remindAt:z.iso.datetime()}).strict().parse(req.body),time=clock(),remindAt=Date.parse(p.remindAt);if(remindAt<time-60000||remindAt>time+366*86400000)fail(400,'Choose a UTC reminder from now through the next year');const result=transaction(()=>{current(req);const task=get('tasks',req.params.id),owner=account(req.user.id);if(task.ownerId!==req.user.id)fail(403,'Only the current task owner can set its reminder');if(task.status==='Completed')fail(409,'Completed tasks cannot receive reminders');if(task.version!==p.taskVersion||owner.version!==p.ownerVersion)fail(409,'Task or owner changed. Reload current versions');if(!owner.active||!['admin','staff'].includes(owner.role))fail(403,'Choose an active staff task owner');if(db.prepare("SELECT 1 FROM task_reminders WHERE task_id=? AND status='Active'").get(task.id))fail(409,'This task has an active reminder. Cancel it before creating another');if(db.prepare("SELECT COUNT(*) n FROM task_reminders WHERE status='Active'").get().n>=100)fail(409,'This workspace has 100 active reminders. Cancel an unused reminder first');const key=randomUUID(),at=iso(time);db.prepare('INSERT INTO task_reminders VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(key,task.id,owner.id,owner.version,mfaAccountBinding(owner),task.version,iso(remindAt),'Active',1,at,at,iso(remindAt),0);audit(req.user,'create_task_reminder','tasks',task.id,{reminderId:key,taskVersion:task.version,ownerVersion:owner.version,remindAt:iso(remindAt),delivery:'Internal only'});current(req);const saved=find(key);if(source(saved).reason)fail(409,'Task or account changed before the reminder was saved');return view(saved);});res.status(201).json({reminder:result,delivery:'Internal only',timezone:'UTC'});}));
 app.get('/api/task-reminders',action((req,res)=>{z.object({}).strict().parse(req.query);const rows=db.prepare("SELECT * FROM task_reminders WHERE owner_id=? ORDER BY CASE status WHEN 'Active' THEN 0 ELSE 1 END,created_at DESC,id LIMIT 100").all(req.user.id);res.json({reminders:rows.map(view),limit:100,delivery:'Internal only',timezone:'UTC'});}));
 app.get('/api/task-reminders/:id',action((req,res)=>{id.parse(req.params.id);z.object({}).strict().parse(req.query);const row=find(req.params.id);own(row,req);res.json({reminder:view(row),outcomes:outcomes(row.id),outcomeCount:db.prepare('SELECT COUNT(*) n FROM task_reminder_outcomes WHERE reminder_id=?').get(row.id).n,outcomeLimit:100});}));
 app.post('/api/task-reminders/:id/cancel',csrf,write,action((req,res)=>{id.parse(req.params.id);const p=z.object({version,reason:z.string().trim().min(1).max(500)}).strict().parse(req.body);const result=transaction(()=>{current(req);const row=find(req.params.id);own(row,req);if(row.status!=='Active')fail(409,'This reminder is closed. Create a new reminder if needed');if(row.version!==p.version)fail(409,'Reminder changed. Reload its current version');if(source(row).reason)fail(409,'Task or account changed. The old reminder cannot be edited');const time=clock();db.prepare("UPDATE task_reminders SET status='Cancelled',version=version+1,updated_at=? WHERE id=?").run(iso(time),row.id);outcome(row,'Cancelled',p.reason,time);audit(req.user,'cancel_task_reminder','tasks',row.task_id,{reminderId:row.id,reason:p.reason,delivery:'Not delivered'});current(req);if(source(row).reason)fail(409,'Task or account changed before cancellation');return view(find(row.id));});res.json({reminder:result});}));
 app.get('/api/reminder-inbox',action((req,res)=>{z.object({}).strict().parse(req.query);const selected=[];for(const item of db.prepare('SELECT * FROM task_reminder_inbox WHERE owner_id=? ORDER BY delivered_at DESC,id').iterate(req.user.id)){const row=find(item.reminder_id);if(row.status!=='Delivered')continue;const s=source(row);if(s.reason)continue;selected.push({id:item.id,reminderId:row.id,taskId:row.task_id,taskVersion:row.task_version,taskTitle:s.task.title,deliveredAt:item.delivered_at});if(selected.length===100)break;}res.json({items:selected,limit:100,delivery:'Internal only'});}));
 const timer=worker?setInterval(()=>{try{runDueReminders();}catch{console.error('Task reminder worker could not complete its current cycle.');}},30000):null;timer?.unref();
 return {runDueReminders,suppressPendingForTenant,close:()=>{if(timer)clearInterval(timer);},validateDeletion:(collection,record)=>{if(collection==='tasks'&&db.prepare('SELECT 1 FROM task_reminders WHERE task_id=?').get(record.id))fail(409,'Retained reminder history protects this task from deletion. Complete the task instead');}};
}
