import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';

const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const hash=v=>createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');
const id=z.string().min(1).max(100),version=z.number().int().min(1),optionalId=id.nullable().default(null);
const shape={giftId:id,type:z.enum(['Honor','Memory']),honoreeName:z.string().trim().max(250).default(''),honoreeId:optionalId,notificationRecipientId:optionalId,message:z.string().max(8000).default(''),notes:z.string().max(8000).default(''),visibility:z.enum(['Team','Staff only']).default('Team'),donorDisclosureApproved:z.boolean().default(false)};
const schema=z.object(shape).strict().refine(p=>p.honoreeName||p.honoreeId,'Name or select an honoree');
const financial=['constituentId','softCreditId','amount','type','method','date','allocations','giftKind'];
const today=()=>new Date().toISOString().slice(0,10),now=()=>new Date().toISOString();
const notice='Honor and memorial recognition does not assign donor or soft-credit income. Notifications are reviewed plain text only; nothing is sent or delivered.';

export function installTributeRoutes(app,{db,list,get,getSettings,audit,csrf,write,admin,transaction}){
 db.exec(`CREATE TABLE IF NOT EXISTS tributes(id TEXT PRIMARY KEY,version INTEGER NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS tribute_versions(tribute_id TEXT NOT NULL,version INTEGER NOT NULL,snapshot TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL,PRIMARY KEY(tribute_id,version));
 CREATE TABLE IF NOT EXISTS tribute_notifications(id TEXT PRIMARY KEY,tribute_id TEXT NOT NULL,snapshot TEXT NOT NULL,digest TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS tribute_notification_finalizations(notification_id TEXT PRIMARY KEY,digest TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL);
 CREATE TRIGGER IF NOT EXISTS tribute_version_no_update BEFORE UPDATE ON tribute_versions BEGIN SELECT RAISE(ABORT,'Tribute history is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS tribute_version_no_delete BEFORE DELETE ON tribute_versions BEGIN SELECT RAISE(ABORT,'Tribute history is retained'); END;
 CREATE TRIGGER IF NOT EXISTS tribute_notification_no_update BEFORE UPDATE ON tribute_notifications BEGIN SELECT RAISE(ABORT,'Tribute notification originals are immutable'); END;
 CREATE TRIGGER IF NOT EXISTS tribute_notification_no_delete BEFORE DELETE ON tribute_notifications BEGIN SELECT RAISE(ABORT,'Tribute notification originals are retained'); END;
 CREATE TRIGGER IF NOT EXISTS tribute_final_no_update BEFORE UPDATE ON tribute_notification_finalizations BEGIN SELECT RAISE(ABORT,'Tribute review history is immutable'); END;
 CREATE TRIGGER IF NOT EXISTS tribute_final_no_delete BEFORE DELETE ON tribute_notification_finalizations BEGIN SELECT RAISE(ABORT,'Tribute review history is retained'); END;`);
 const authorized=(req,res,next)=>{if(!req.user)return res.status(401).json({error:'Authentication required'});if(!['admin','staff','viewer'].includes(req.user.role))return res.status(403).json({error:'Your role cannot access tributes'});next();};
 const route=fn=>(req,res,next)=>{try{fn(req,res);}catch(e){next(e);}};
 app.use('/api/tributes',authorized);app.use('/api/tribute-notifications',authorized);
 const read=r=>({id:r.id,version:r.version,...JSON.parse(r.data),createdAt:r.created_at,updatedAt:r.updated_at,notice});
 const find=key=>{const r=db.prepare('SELECT * FROM tributes WHERE id=?').get(key);if(!r)fail(404,'Tribute not found');return read(r);};
 const visible=(record,user)=>user.role!=='viewer'||record.visibility==='Team';
 const findVisible=(key,user)=>{const r=find(key);if(!visible(r,user))fail(404,'Tribute not found');return r;};
 const person=key=>{const p=get('constituents',key);if(p.mergedInto)fail(409,'Select the surviving constituent; merged identities are retained history.');return p;};
 function gift(key){const g=get('gifts',key);if(g.status!=='Posted'||g.type==='Fee payment')fail(409,'Tributes require a posted non-fee gift. Voided sources are retained history.');if(!/^\d{4}-\d{2}-\d{2}$/.test(g.date)||!Number.isFinite(Date.parse(g.date))||new Date(g.date+'T00:00:00Z').toISOString().slice(0,10)!==g.date||g.date>today())fail(409,'Tributes require an actual current or historical gift date.');person(g.constituentId);return g;}
 function sources(p){const g=gift(p.giftId),donor=person(g.constituentId),honoree=p.honoreeId?person(p.honoreeId):null,recipient=p.notificationRecipientId?person(p.notificationRecipientId):null;return {gift:g,donor,honoree,recipient};}
 function save(p,user,old=null){if(old&&old.giftId!==p.giftId)fail(409,'A tribute retains its original gift; create a separate tribute for another gift.');const source=sources(p),key=old?.id||randomUUID(),at=now(),v=(old?.version||0)+1;db.prepare('INSERT INTO tributes VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET version=excluded.version,data=excluded.data,updated_at=excluded.updated_at').run(key,v,JSON.stringify(p),old?.createdAt||at,at);db.prepare('INSERT INTO tribute_versions VALUES(?,?,?,?,?)').run(key,v,JSON.stringify({definition:p,source}),user.id,at);audit(user,old?'update_tribute':'create_tribute','gifts',p.giftId,{tributeId:key,version:v,type:p.type,visibility:p.visibility});return find(key);}
 const refs=s=>[{collection:'gifts',id:s.gift.id,version:s.gift.version,recordDigest:hash(s.gift)},...new Map([s.donor,s.honoree,s.recipient].filter(Boolean).map(p=>[p.id,{collection:'constituents',id:p.id,version:p.version,recordDigest:hash(p)}])).values()];
 function prepare(t,channel){const s=sources(t);if(!t.donorDisclosureApproved)fail(403,'Confirm staff approval to disclose the donor identity in this notification.');if(!s.recipient)fail(400,'Select a notification recipient before preparing a notification.');if(s.donor.preference==='Do not contact'||s.recipient.preference==='Do not contact')fail(403,'Do not contact: donor or recipient consent blocks notification preparation.');if(channel==='Email draft'&&(s.recipient.preference!=='Email'||!z.email().safeParse(s.recipient.email).success))fail(400,'Email drafts require the recipient primary email and Email preference.');if(channel==='Print'&&s.recipient.preference!=='Post')fail(400,'Printed notifications require the recipient Post preference.');const honoreeName=t.honoreeName||s.honoree?.name,organizationName=String(getSettings().organizationName||'Workspace'),subject=`${t.type==='Memory'?'In memory of':'In honor of'} ${honoreeName}`;const body=`Dear ${s.recipient.name},\n\n${organizationName} has recorded a gift from ${s.donor.name} ${t.type==='Memory'?'in memory of':'in honor of'} ${honoreeName}.${t.message?'\n\n'+t.message:''}\n\nThis is a prepared notification, not a donation receipt. No message has been sent.`;return {tributeId:t.id,tributeVersion:t.version,type:t.type,honoreeName,honoreeId:t.honoreeId,visibility:t.visibility,channel,subject,body,recipient:{id:s.recipient.id,name:s.recipient.name,email:channel==='Email draft'?s.recipient.email:'',preference:s.recipient.preference},source:{giftId:s.gift.id,donorId:s.donor.id,donorName:s.donor.name,giftDate:s.gift.date},references:refs(s),request:{tributeId:t.id,version:t.version,channel},delivery:'Not sent',notice};}
 function notification(row,user){const snapshot=JSON.parse(row.snapshot);if(hash(snapshot)!==row.digest)fail(503,'Notification integrity check failed.');const current=find(row.tribute_id),saved=db.prepare('SELECT snapshot FROM tribute_versions WHERE tribute_id=? AND version=?').get(row.tribute_id,snapshot.tributeVersion);if(!visible(snapshot,user)||!visible(current,user)||user.role==='viewer'&&(!current.donorDisclosureApproved||!saved||JSON.parse(saved.snapshot).definition.donorDisclosureApproved!==true))fail(404,'Tribute notification not found');const final=db.prepare('SELECT * FROM tribute_notification_finalizations WHERE notification_id=?').get(row.id);return {id:row.id,version:1,status:final?'Finalized':'Draft',...snapshot,preparationDigest:row.digest,createdBy:row.actor,createdAt:row.at,finalizedBy:final?.actor||null,finalizedAt:final?.at||null};}
 const findNotification=key=>{const r=db.prepare('SELECT * FROM tribute_notifications WHERE id=?').get(key);if(!r)fail(404,'Tribute notification not found');return r;};
 app.get('/api/tributes',route((req,res)=>{const q=z.object({q:z.string().max(200).optional(),giftId:id.optional()}).strict().parse(req.query);const rows=db.prepare('SELECT * FROM tributes ORDER BY updated_at DESC,id').all().map(read).filter(r=>visible(r,req.user)&&(!q.giftId||r.giftId===q.giftId)&&(!q.q||JSON.stringify(r).toLowerCase().includes(q.q.toLowerCase())));res.json({tributes:rows.slice(0,100),notice});}));
 app.get('/api/tributes/:id',route((req,res)=>{const tribute=findVisible(req.params.id,req.user),revisions=db.prepare('SELECT version,snapshot,actor,at FROM tribute_versions WHERE tribute_id=? ORDER BY version').all(tribute.id).map(r=>({...r,...JSON.parse(r.snapshot)})).filter(r=>visible(r.definition,req.user)&&(req.user.role!=='viewer'||tribute.donorDisclosureApproved===true&&r.definition.donorDisclosureApproved===true)).map(({snapshot,...r})=>r);res.json({tribute,revisions});}));
 app.post('/api/tributes',csrf,write,route((req,res)=>{const p=schema.parse(req.body);res.status(201).json({tribute:transaction(()=>{if(db.prepare('SELECT count(*) n FROM tributes').get().n>=10000)fail(413,'Tribute record limit reached.');return save(p,req.user);})});}));
 app.patch('/api/tributes/:id',csrf,write,route((req,res)=>{const old=findVisible(req.params.id,req.user),{version:v,...changes}=z.object({version}).passthrough().parse(req.body);res.json({tribute:transaction(()=>{const current=find(old.id);if(current.version!==v)fail(409,'Tribute changed. Reload its latest version.');const p=schema.parse({...Object.fromEntries(Object.keys(shape).map(k=>[k,current[k]])),...changes});return save(p,req.user,current);})});}));
 app.delete('/api/tributes/:id',csrf,write,route((req,res)=>{findVisible(req.params.id,req.user);fail(403,'Tribute records and notification history are retained; update with an explanatory note.');}));
 app.post('/api/tributes/:id/notifications/prepare',csrf,write,route((req,res)=>{const p=z.object({version,channel:z.enum(['Print','Email draft'])}).strict().parse(req.body);res.status(201).json({notification:transaction(()=>{const t=findVisible(req.params.id,req.user);if(t.version!==p.version)fail(409,'Tribute changed. Reload its latest version.');const snapshot=prepare(t,p.channel),key=randomUUID(),at=now(),digest=hash(snapshot);db.prepare('INSERT INTO tribute_notifications VALUES(?,?,?,?,?,?)').run(key,t.id,JSON.stringify(snapshot),digest,req.user.id,at);audit(req.user,'prepare_tribute_notification','gifts',t.giftId,{tributeId:t.id,notificationId:key,tributeVersion:t.version,digest,delivery:'Not sent'});return notification(findNotification(key),req.user);})});}));
 app.get('/api/tribute-notifications',route((req,res)=>{const q=z.object({tributeId:id.optional()}).strict().parse(req.query),rows=db.prepare('SELECT * FROM tribute_notifications ORDER BY at DESC,id').all().filter(r=>!q.tributeId||r.tribute_id===q.tributeId);const notifications=[];for(const r of rows){try{notifications.push(notification(r,req.user));}catch(e){if(e.status!==404)throw e;}if(notifications.length===100)break;}res.json({notifications,delivery:'Not sent'});}));
 app.get('/api/tribute-notifications/:id',route((req,res)=>res.json({notification:notification(findNotification(req.params.id),req.user)})));
 app.post('/api/tribute-notifications/:id/finalize',csrf,write,route((req,res)=>{const p=z.object({version:z.literal(1),preparationDigest:z.string().regex(/^[a-f0-9]{64}$/),confirmed:z.literal(true)}).strict().parse(req.body);res.json({notification:transaction(()=>{const row=findNotification(req.params.id),old=notification(row,req.user);if(old.status!=='Draft')fail(409,'Notification already finalized.');if(old.preparationDigest!==p.preparationDigest)fail(409,'Notification digest changed. Review the saved draft.');const t=findVisible(old.tributeId,req.user);if(t.version!==old.tributeVersion||hash(prepare(t,old.channel))!==row.digest)fail(409,'Tribute, source records or consent changed. Prepare and review a fresh notification.');db.prepare('INSERT INTO tribute_notification_finalizations VALUES(?,?,?,?)').run(row.id,row.digest,req.user.id,now());audit(req.user,'finalize_tribute_notification','gifts',t.giftId,{tributeId:t.id,notificationId:row.id,digest:row.digest,delivery:'Not sent'});return notification(row,req.user);})});}));
 const histories=()=>db.prepare('SELECT snapshot FROM tribute_versions').all().map(r=>JSON.parse(r.snapshot));
 const hasConstituentReferences=key=>histories().some(s=>[s.source.donor,s.source.honoree,s.source.recipient].some(p=>p?.id===key)||s.source.gift.softCreditId===key);
 function validateDeletion(c,previous){if(c==='constituents'&&hasConstituentReferences(previous.id)||c==='gifts'&&db.prepare('SELECT 1 FROM tributes WHERE json_extract(data,\'$.giftId\')=?').get(previous.id))fail(409,'This record has retained tribute source history and cannot be deleted.');}
 function validateMutation(c,previous,next){if(c==='constituents'&&hasConstituentReferences(previous.id)&&(next.mergedInto||next.type!==previous.type))fail(409,'Tribute identity history is retained; merging or reclassification requires a reviewed historical alias workflow.');if(c==='gifts'){const linked=db.prepare("SELECT id FROM tributes WHERE json_extract(data,'$.giftId')=?").all(previous.id);if(linked.length&&['constituentId','softCreditId'].some(k=>(next[k]??null)!==(previous[k]??null)))fail(409,'Tribute donor and soft-credit source identity are retained.');const finalized=linked.some(t=>db.prepare('SELECT 1 FROM tribute_notifications n JOIN tribute_notification_finalizations f ON f.notification_id=n.id WHERE n.tribute_id=?').get(t.id));if(finalized&&financial.some(k=>hash(previous[k]??null)!==hash(next[k]??null)))fail(409,'Finalized tribute notifications retain their source financial facts; use a reviewed correction workflow.');}}
 // Continue core mutations after the shared validation; route parameters decode once.
 app.patch('/api/records/:collection/:id',csrf,write,(req,res,next)=>{try{const p=get(req.params.collection,req.params.id);validateMutation(req.params.collection,p,{...p,...req.body});next();}catch(e){next(e);}});
 app.delete('/api/records/:collection/:id',csrf,write,(req,res,next)=>{try{validateDeletion(req.params.collection,get(req.params.collection,req.params.id));next();}catch(e){next(e);}});
 for(const endpoint of ['/api/identity/merge/preview','/api/identity/merge'])app.post(endpoint,csrf,admin,(req,res,next)=>{if([req.body?.sourceId,req.body?.targetId].some(hasConstituentReferences))return res.status(409).json({error:'Tribute source identity history is retained; a reviewed historical alias workflow is required.'});next();});
 return {validateMutation,validateDeletion,hasConstituentReferences};
}
