import React,{useState} from 'react';
import {ArrowDown,ArrowUp,ChevronLeft,ChevronRight,ArrowUpRight} from 'lucide-react';
export default function DataTable({columns,rows,onOpen,label='Records',pageSize=20}) {
 const [sort,setSort]=useState(null);const [page,setPage]=useState(0);const [density,setDensity]=useState(()=>{try{return localStorage.getItem('everbright-density')||'compact';}catch{return 'compact';}});
 const content=(c,r)=>{const v=c.render?c.render(r):r[c.key];return v==null||v===''?'—':v;};
 let ordered=[...rows];
 if(sort){const column=columns.find(c=>c.key===sort.key);ordered.sort((a,b)=>{const av=column.sort?column.sort(a):a[column.key],bv=column.sort?column.sort(b):b[column.key];const n=typeof av==='number'&&typeof bv==='number'?av-bv:String(av??'').localeCompare(String(bv??''));return sort.desc?-n:n;});}
 const pages=Math.max(1,Math.ceil(ordered.length/pageSize));const currentPage=Math.min(page,pages-1);const visible=ordered.slice(currentPage*pageSize,(currentPage+1)*pageSize);
 const ranked=[...columns].sort((a,b)=>(a.mobilePriority??columns.indexOf(a)+10)-(b.mobilePriority??columns.indexOf(b)+10)).slice(0,3);
 if(!rows.length)return <div className="empty-state"><h3>No matching records</h3><p>Try a different search or filter, or add the first record.</p></div>;
 function densityChange(value){setDensity(value);try{localStorage.setItem('everbright-density',value);}catch{}}
 return <><div className="table-preferences"><label>Row density<select aria-label={label+' row density'} value={density} onChange={e=>densityChange(e.target.value)}><option value="compact">Compact · 40px</option><option value="default">Default · 48px</option><option value="comfortable">Review · 56px</option></select></label><span className="subtle">{rows.length} records</span></div><div className={'table-wrap desktop-record-table density-'+density}><table aria-label={label}><thead><tr>{columns.map(c=><th className={c.money?'money':''} key={c.key} scope="col" aria-sort={sort?.key===c.key?(sort.desc?'descending':'ascending'):'none'}><button className="table-sort" onClick={()=>{setSort({key:c.key,desc:sort?.key===c.key?!sort.desc:false});setPage(0);}}>{c.label}{sort?.key===c.key&&(sort.desc?<ArrowDown size={12}/>:<ArrowUp size={12}/>)}</button></th>)}{onOpen&&<th scope="col"><span className="sr-only">Open record</span></th>}</tr></thead><tbody>{visible.map(r=><tr key={r.id}>{columns.map((c,i)=>{const value=content(c,r);const title=typeof value==='string'?value:undefined;return <td key={c.key} className={c.money?'money':''}>{onOpen&&i===0?<button className="record-link cell-content" title={title} onClick={()=>onOpen(r)}>{value}</button>:<span className={c.money?'cell-number':'cell-content'} title={title}>{value}</span>}</td>;})}{onOpen&&<td className="row-action"><button className="icon-btn" onClick={()=>onOpen(r)} aria-label={'Open '+(r.name||r.title||r.subject||'record')}><ArrowUpRight size={16}/></button></td>}</tr>)}</tbody></table></div><div className="mobile-records" aria-label={label+' mobile list'}>{visible.map(r=><article key={r.id}><div className="mobile-record-primary">{onOpen?<button className="record-link" onClick={()=>onOpen(r)}>{content(columns[0],r)}<ArrowUpRight size={16}/></button>:<strong>{content(columns[0],r)}</strong>}</div><dl>{ranked.filter(c=>c!==columns[0]).map(c=><div key={c.key}><dt>{c.label}</dt><dd className={c.money?'money':''}>{content(c,r)}</dd></div>)}</dl><details><summary>All record fields</summary><dl>{columns.filter(c=>c!==columns[0]&&!ranked.includes(c)).map(c=><div key={c.key}><dt>{c.label}</dt><dd className={c.money?'money':''}>{content(c,r)}</dd></div>)}</dl></details></article>)}</div><div className="table-footer"><span>{currentPage*pageSize+1}–{Math.min((currentPage+1)*pageSize,rows.length)} of {rows.length} records</span>{pages>1&&<div className="pagination"><button className="icon-btn" aria-label="Previous page" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}><ChevronLeft size={16}/></button><span>Page {currentPage+1} of {pages}</span><button className="icon-btn" aria-label="Next page" disabled={currentPage>=pages-1} onClick={()=>setPage(currentPage+1)}><ChevronRight size={16}/></button></div>}</div></>;
}
