import React,{useState} from 'react';
import {Save,ArrowLeft} from 'lucide-react';
import {MODULES} from '../schema';
import {cents} from '../lib';
import {Field,ContactsEditor} from './Fields';
export default function RecordForm({collection,record,data,onSave,onCancel,onDirty,onReload}) {
 const schema=MODULES[collection];
 const activeFields=schema.fields.filter(f=>!record||!f.createOnly);
 const [values,setValues]=useState(()=>Object.fromEntries(activeFields.map(f=>[f.key,f.type==='money'?((record?.[f.key]??schema.defaults[f.key])/100).toFixed(2):record?.[f.key]??schema.defaults[f.key]??''])));
 const [assignmentReason,setAssignmentReason]=useState('');
 const ownerChanged=collection==='tasks'&&!!record&&(values.ownerId||null)!==(record.ownerId||null);
 const [contacts,setContacts]=useState(record?.contacts||[]);
 const [error,setError]=useState('');const [conflict,setConflict]=useState(false);const [saving,setSaving]=useState(false);
 const change=(key,v)=>{setValues(old=>({...old,[key]:v}));onDirty(true);};
 async function submit(e){e.preventDefault();setError('');setConflict(false);setSaving(true);try{const payload={...values};for(const f of activeFields){if(f.type==='money')payload[f.key]=cents(values[f.key]);if(f.type==='date'&&!values[f.key])payload[f.key]=null;if(f.type==='reference'&&!values[f.key])payload[f.key]=null;}if(collection==='tasks'){payload.owner=values.ownerId?'':(!record?.ownerId&&record?.owner&&!values.ownerId?record.owner:'');if(ownerChanged)payload.assignmentReason=assignmentReason.trim();}if(collection==='constituents')payload.contacts=contacts;await onSave(payload);}catch(err){setError(err.message);setConflict(err.status===409);}finally{setSaving(false);}}
 return <section className="panel inline-editor"><div className="section-title"><div><h2>{record?'Edit':'New'} {schema.singular}</h2><p className="subtle">Fields marked with * are required.</p></div><button type="button" className="btn btn-secondary" onClick={onCancel} disabled={saving}><ArrowLeft size={16}/>Back</button></div><form onSubmit={submit}>{error&&<div className="error-banner" role="alert">{error} Your changes have not been saved.{conflict&&record&&onReload&&<button type="button" className="text-btn" disabled={saving} onClick={async()=>{if(!window.confirm('Discard these unsaved changes and load the latest record?'))return;setSaving(true);try{await onReload();}catch(e){setError(e.message);}finally{setSaving(false);}}}>Load latest record</button>}</div>}<div className="form-grid">{activeFields.map(f=><Field key={f.key} field={f} value={values[f.key]} onChange={v=>change(f.key,v)} data={collection==='tasks'&&record?.ownerId&&!data.taskOwners.some(u=>u.id===record.ownerId)?{...data,taskOwners:[...data.taskOwners,{id:record.ownerId,name:(record.owner||'Recorded owner')+' (needs reassignment)',disabled:true}]}:data} currentId={record?.id}/>)}{collection==='tasks'&&<div className="field field-wide"><p className="subtle">{record?.ownerStatus==='Needs reassignment'?'The recorded owner is no longer active staff. Choose a replacement.':!record?.ownerId&&record?.owner?'Legacy owner label: '+record.owner+'. Select a staff account to establish responsibility.':'Assignments record responsibility; this action does not send a reminder.'}</p></div>}{ownerChanged&&<label className="field field-wide">Reason for responsibility change *<textarea required maxLength={2000} value={assignmentReason} onChange={e=>{setAssignmentReason(e.target.value);onDirty(true);}}/></label>}{collection==='constituents'&&<ContactsEditor contacts={contacts} onChange={v=>{setContacts(v);onDirty(true);}}/>}</div><div className="form-actions"><button className="btn btn-secondary" type="button" onClick={onCancel} disabled={saving}>Cancel</button><button className="btn btn-primary" disabled={saving}><Save size={16}/>{saving?'Saving…':'Save '+schema.singular}<kbd>⌘ / Ctrl ↵</kbd></button></div></form></section>;
}
