import HelpHint from './HelpHint';
export const SCREEN_HELP={
 operations:['Choose the next action, plan a shift, or review connected identities.','Work items open their supporting records. Reserve volunteer places without overbooking; waitlists require an explicit staff promotion. Reservations do not record attendance or hours. Shared email is a review suggestion, never an automatic merge.'],
 dashboard:['Review saved activity, then open a metric’s supporting records.','Contributions include saved posted monetary gifts; commitments and noncash support stay separate. Inspect a month and choose Explore gifts. C records a new gift; Command/Ctrl K focuses search.'],
 constituents:['Open a person or organization to see their connected history.','A constituent connects gifts, pledges, grant funding, interactions, volunteering and events. Add a household or parent organization to support recognition reports. Contact preferences control draft and acknowledgment eligibility.'],
 gifts:['Choose the donor, record the value, and allocate the whole gift.','Every gift needs allocations totaling exactly its value. Use Linked pledge or Linked grant award for reconciled commitments. External references protect against duplicate imports. This records a gift; it does not collect funds.'],
 pledges:['Record a commitment, then connect its received gifts.','An installment schedule is a plan. Only eligible linked posted gifts fulfill it. Voided gifts release fulfillment; future receipts are excluded from today’s received balance.'],
 stewardship:['Review an eligible gift and record an action already completed.','Pending excludes voids, fees and do-not-contact recipients. Recording an acknowledgment saves a linked Logged interaction; it does not send a message or issue a tax receipt.'],
 grants:['Keep the request, recorded award and actual receipts distinct.','Record a named funder, award amount/date and Awarded stage before linking Grant revenue. Only matching-funder receipts fulfill the award. Legacy unknown awards need to be recorded explicitly.'],
 campaigns:['Open a campaign to compare its goal with connected gifts.','Progress derives from linked posted monetary contributions. Planned goals and commitments are not received income. Fiscal-year dashboard and all-time campaign details can show different periods.'],
 volunteers:['Open a volunteer to clock time and inspect the dated ledger.','Clock-out records a completed interval. Historical hours remain undated. Corrections require a reason and retain original dates and hours. Only one active clock per person is allowed.'],
 events:['Open an event to register guests and manage admission.','Registration links to a constituent and respects capacity. Check-in requires registration. Ticket prices and sponsorship goals are recorded plans, not checkout or settlement.'],
 tasks:['Open a task, review its owner and links, then mark it complete.','Tasks can connect to a constituent or event. Completion updates the shared queue and audit history. Owners are recorded staff labels; automatic reminders are not configured.'],
 communications:['Prepare an unsent draft or record a completed interaction.','Drafts are local previews. Logged interactions are staff records. Acknowledgment-linked activities protect their recipient, date, channel and status from inconsistent edits.'],
 designations:['Connect a school, classroom or fund to its parent and account code.','Gift allocations connect to designations. Hierarchies reject cycles and referenced funds cannot be deleted. Use unique account codes for CSV matching.'],
 reports:['Choose a report, set its relevant filters, then save or export.','Saved views store shared filters. Recognition groups can overlap and must not be added as income. Grant/pledge reconciliation uses an as-of date; historical volunteer hours remain separate.'],
 settings:['Review organization settings, access roles and traceable activity.','Administration is restricted to administrators. Board business-record access is read-only. Snapshot exports exclude passwords and sessions; local snapshots do not establish managed recovery or production certification.'],
 testing:['Choose a workflow, try it in the workspace, then record your result.','These are manually observed results, not automated approval. Passed confirms your observation; Needs attention or Blocked requires reproduction details. Board viewers can submit results without editing business records.'],
 guide:['Use the evaluator walkthrough to understand the working scope.','The pilot uses synthetic data. Live integrations, hosting, migration and district approvals remain separate acceptance steps. Client testing records and exports your findings.' ]
};
export default function ScreenGuide({route}){const help=SCREEN_HELP[route]||SCREEN_HELP.dashboard;return <div className="screen-guide"><p>{help[0]}</p><HelpHint label="This screen’s quick guide" text={help[1]}/></div>;}
