export const RELEASE='0.4.0';
export const SCENARIOS=[
 {id:'shifts',title:'Reserve volunteer places safely',view:'operations',time:'6 min',steps:['Open Volunteer shifts. Plan a one-place shift with a venue and local start/end times. Reserve a synthetic person.','Try a second reserved person: confirm full-capacity rejection, then add that person as Waitlisted. Cancel the first reservation and explicitly reserve the available waitlist place.','Reload and inspect preserved Cancelled history, capacity and constituent links. Try overlapping reserved shifts for the same person.'],expected:'No overbooking, duplicate active reservation or overlapping Reserved shift is allowed. Cancellation releases a place and retains history. Waitlist promotion is explicit; reservation does not create attendance, hours or reminders.'},
 {id:'operations',title:'Follow the next action to its source',view:'operations',time:'4 min',steps:['Filter the Work queue by tasks, grant obligations or pledges. Open a row and inspect its source record.','Review the recorded due date and value semantics, then return to Operations. Complete a test task and confirm it leaves the queue.','Open Data quality. Review any shared-email constituent group without assuming those people are the same.'],expected:'Rows lead to real supporting records. Completed tasks leave the queue. Pledge due amounts derive from eligible posted receipts. Reporting dates ask for review because completion is not tracked. No automatic merge or message occurs.'},
 {id:'giving',title:'Trace a gift to its funds',view:'gifts',time:'5 min',steps:['Record a fictional $100 cash gift. Split $60 to STEM and $40 to arts. Use a unique external reference.','Before saving, try a $60/$30 split. Then restore the full $100 allocation and save.','Open the gift and donor history, reload, and compare the Gift ledger export.'],expected:'Incomplete allocations cannot save. The saved gift totals $100, its two allocations total $100, and history survives reload. No funds are collected.'},
 {id:'pledges',title:'Reconcile a pledge commitment',view:'pledges',time:'5 min',steps:['Create a $1,200 monthly pledge with twelve installments for a fictional donor.','Record a $100 monetary gift for that donor with Linked pledge selected.','Inspect the schedule and balance. Try a receipt greater than the remaining commitment; confirm rejection.'],expected:'Twelve $100 installments sum to $1,200. The linked receipt contributes $100 toward fulfillment and leaves $1,100 outstanding. Commitment is separate from received contributions.'},
 {id:'recognition',title:'Recognize supporters without double counting',view:'reports',time:'5 min',steps:['Assign a household or parent organization to fictional constituents.','Record a gift with a different soft-credit constituent.','Compare Soft-credit recognition, Household rollup and Organization rollup using the same date filters.'],expected:'Direct/soft monetary attribution and noncash value remain separate. Each gift counts once within a group. Overlapping recognition groups do not create additional income.'},
 {id:'grants',title:'Separate request, award and receipts',view:'grants',time:'5 min',steps:['Create a $25,000 request with a named synthetic funder. Record a $15,000 award, award date and Awarded stage.','Record a $5,000 Grant revenue gift from that funder and select Linked grant award.','Inspect reconciliation and linked receipt history. Try a wrong-funder or over-award receipt.'],expected:'Requested $25,000, recorded award $15,000, recorded receipts $5,000 and unreceived award $10,000 remain distinct. Invalid linked receipts save nothing.'},
 {id:'volunteers',title:'Review dated volunteer time',view:'volunteers',time:'4 min',steps:['Open a volunteer, clock in and clock out.','Compare the completed dated interval with separately labeled undated historical hours.','Correct the interval hours with a reason and reload.'],expected:'Dated time and historical totals remain distinct. Correction retains original dates/hours and reason; the aggregate reconciles. The same person cannot clock into two records at once.'},
 {id:'events',title:'Register and admit a guest',view:'events',time:'4 min',steps:['Open a synthetic event and register a constituent with a table or seat label.','Check in the registered guest and reload.','Try duplicate registration or adding a guest beyond capacity.'],expected:'Registration, seat and check-in persist. Duplicate registrations and capacity overflow are rejected. Recording a ticket price does not collect payment.'},
 {id:'stewardship',title:'Record a completed thank-you',view:'stewardship',time:'4 min',steps:['Select an eligible unacknowledged gift. Record a fictional completed Phone action with notes.','Inspect Completed stewardship and the linked recorded interaction on the gift.','Confirm do-not-contact recipients are excluded and the same gift cannot be acknowledged twice.'],expected:'The saved action leaves Pending, appears in Completed and links to a Logged interaction. No message is sent and no tax receipt is issued.'},
 {id:'reporting',title:'Reuse a team report view',view:'reports',time:'4 min',steps:['Choose a report and date/year filters. Save a named workspace view.','Change the report, reapply the saved view and reload.','Export the report and compare its totals with the visible rows. For recognition, do not sum overlapping groups.'],expected:'The saved filters survive reload and are readable by the board role. CSV matches the selected report. Saved views are not scheduled deliveries.'},
 {id:'access',title:'Verify board access and keyboard use',view:'dashboard',time:'4 min',steps:['Sign out and use the Board viewer demo role. Browse records and reports.','Confirm business-record creation and Settings are unavailable. Open Client testing and submit a test result.','Use Command/Ctrl K to focus global search; Tab through controls. Return to staff/admin to try C outside an input.'],expected:'Board access is read-only for business records, with permission to submit test feedback. Search shortcut works, focus is visible and C creates only where staff/admin creation is available.'}
];
