import {effectiveSchoolYear,fiscalYear,today} from './lib.js';
const pad=n=>String(n).padStart(2,'0');
const day=value=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&Number.isFinite(Date.parse(value))&&new Date(value+'T00:00:00Z').toISOString().slice(0,10)===value;
const cents=value=>{if(!Number.isSafeInteger(value)||value<0)throw new Error('A monetary source value is not safe nonnegative integer cents. Review the saved record.');return value;};
const total=rows=>{let value=0n;for(const row of rows)value+=BigInt(cents(row.amount));if(value>BigInt(Number.MAX_SAFE_INTEGER))throw new Error('The contribution total exceeds safe integer cents. Narrow the source records.');return Number(value);};
const ids=rows=>({giftIds:rows.map(g=>g.id),donorIds:[...new Set(rows.map(g=>g.constituentId).filter(Boolean))]});
const summarize=rows=>({giftCount:rows.length,donorCount:ids(rows).donorIds.length,amountCents:total(rows),...ids(rows)});
const previousDate=date=>{const year=Number(date.slice(0,4))-1,month=Number(date.slice(5,7)),requested=Number(date.slice(8,10));const last=new Date(Date.UTC(year,month,0)).getUTCDate();return `${year}-${pad(month)}-${pad(Math.min(requested,last))}`;};
const period=(year,startMonth)=>{const start=Number(year.slice(0,4)),endYear=start+(startMonth===1?0:1),endMonth=startMonth===1?12:startMonth-1,last=new Date(Date.UTC(endYear,endMonth,0)).getUTCDate();return {schoolYear:year,startDate:`${start}-${pad(startMonth)}-01`,endDate:`${endYear}-${pad(endMonth)}-${pad(last)}`};};
const yearLabel=(start,month)=>month===1?String(start):`${start}–${start+1}`;
export function computeFundraisingAnalytics(data,{fiscalStartMonth=7,schoolYear,asOf=today()}={}){
 if(!Number.isInteger(fiscalStartMonth)||fiscalStartMonth<1||fiscalStartMonth>12)throw new Error('Choose a fiscal start month from 1 to 12.');
 if(!day(asOf))throw new Error('Choose a valid as-of calendar date.');
 const eligible=(data.gifts||[]).filter(g=>g.status==='Posted'&&!['In-kind','Fee payment'].includes(g.type)&&day(g.date)&&g.date<=asOf);
 const seen=new Set();for(const gift of eligible){cents(gift.amount);if(typeof gift.id!=='string'||seen.has(gift.id))throw new Error('Gift source IDs must be distinct saved records.');seen.add(gift.id);}
 const activeYear=fiscalYear(asOf,fiscalStartMonth),years=[...new Set([activeYear,...eligible.map(g=>effectiveSchoolYear(g,fiscalStartMonth))])].sort((a,b)=>Number(b.slice(0,4))-Number(a.slice(0,4)));
 const selected=schoolYear||activeYear;if(!years.includes(selected))throw new Error('Choose an available school year.');
 const start=Number(selected.slice(0,4)),currentPeriod=period(selected,fiscalStartMonth),priorPeriod=period(yearLabel(start-1,fiscalStartMonth),fiscalStartMonth);
 const currentCutoff=asOf<currentPeriod.endDate?asOf:currentPeriod.endDate,priorCutoff=asOf>=currentPeriod.endDate?priorPeriod.endDate:previousDate(currentCutoff);
 const current=eligible.filter(g=>effectiveSchoolYear(g,fiscalStartMonth)===selected&&g.date<=currentCutoff),prior=eligible.filter(g=>effectiveSchoolYear(g,fiscalStartMonth)===priorPeriod.schoolYear&&g.date<=priorCutoff);
 const currentDonors=new Set(ids(current).donorIds),priorDonors=new Set(ids(prior).donorIds),first=new Map();
 for(const gift of eligible){if(!gift.constituentId)continue;const old=first.get(gift.constituentId);if(!old||gift.date<old.date||gift.date===old.date&&gift.id<old.id)first.set(gift.constituentId,gift);}
 const currentIds=new Set(current.map(g=>g.id)),priorIds=new Set(prior.map(g=>g.id)),firstInCurrent=new Set(current.filter(g=>g.date===first.get(g.constituentId)?.date).map(g=>g.constituentId)),retained=[...currentDonors].filter(id=>priorDonors.has(id)),newDonors=[...currentDonors].filter(id=>!priorDonors.has(id)&&firstInCurrent.has(id)),reactivated=[...currentDonors].filter(id=>!priorDonors.has(id)&&!firstInCurrent.has(id)),lapsed=[...priorDonors].filter(id=>!currentDonors.has(id));
 const byDonor=rows=>{const map=new Map();for(const gift of rows){if(!map.has(gift.constituentId))map.set(gift.constituentId,[]);map.get(gift.constituentId).push(gift);}return map;},currentByDonor=byDonor(current),priorByDonor=byDonor(prior);
 const people=new Map((data.constituents||[]).map(p=>[p.id,p]));
 const cohort=(label,donorIds)=>{const currentRows=donorIds.flatMap(id=>currentByDonor.get(id)||[]),priorRows=donorIds.flatMap(id=>priorByDonor.get(id)||[]);return {label,donorIds,historyGiftIds:donorIds.map(id=>first.get(id)?.id).filter(Boolean),current:summarize(currentRows),prior:summarize(priorRows),donors:donorIds.map(id=>({id,name:people.get(id)?.name||'Unavailable donor',firstGiftDate:first.get(id)?.date,firstGiftId:first.get(id)?.id,current:summarize(currentByDonor.get(id)||[]),prior:summarize(priorByDonor.get(id)||[])}))};};
 const campaigns=new Map((data.campaigns||[]).map(c=>[c.id,c])),campaignGroups=new Map();
 for(const campaign of campaigns.values())campaignGroups.set(campaign.id,{id:campaign.id,label:campaign.name,known:true,goalCents:cents(campaign.goal??0),current:[],prior:[]});
 for(const [kind,rows]of [['current',current],['prior',prior]])for(const gift of rows){const key=gift.campaignId||'none';if(!campaignGroups.has(key))campaignGroups.set(key,{id:gift.campaignId||null,label:gift.campaignId?'Unavailable campaign':'No campaign',known:false,goalCents:null,current:[],prior:[]});campaignGroups.get(key)[kind].push(gift);}
 const campaignPerformance=[...campaignGroups.values()].map(c=>({...c,current:summarize(c.current),prior:summarize(c.prior)})).sort((a,b)=>b.current.amountCents-a.current.amountCents||a.label.localeCompare(b.label));
 const sizeDefinitions=[['Under $100',0,10000],['$100–$499.99',10000,50000],['$500–$999.99',50000,100000],['$1,000–$4,999.99',100000,500000],['$5,000 and above',500000,Infinity]];
 const giftSize=sizeDefinitions.map(([label,min,max])=>({label,minCents:min,maxExclusiveCents:Number.isFinite(max)?max:null,...summarize(current.filter(g=>g.amount>=min&&g.amount<max))}));
 const donorCounts=new Map();for(const gift of current)if(gift.constituentId)donorCounts.set(gift.constituentId,(donorCounts.get(gift.constituentId)||0)+1);
 const frequency=[[1,1,'One gift'],[2,2,'Two gifts'],[3,5,'3–5 gifts'],[6,11,'6–11 gifts'],[12,Infinity,'12+ gifts']].map(([min,max,label])=>{const donorIds=[...donorCounts].filter(([,count])=>count>=min&&count<=max).map(([id])=>id),set=new Set(donorIds);return {label,minGifts:min,maxGifts:Number.isFinite(max)?max:null,...summarize(current.filter(g=>set.has(g.constituentId)))};});
 const offCalendar=rows=>rows.filter(g=>g.date<period(effectiveSchoolYear(g,fiscalStartMonth),fiscalStartMonth).startDate||g.date>period(effectiveSchoolYear(g,fiscalStartMonth),fiscalStartMonth).endDate);
 return {asOf,fiscalStartMonth,schoolYear:selected,years,periods:{current:{...currentPeriod,cutoff:currentCutoff},prior:{...priorPeriod,cutoff:priorCutoff}},current:summarize(current),prior:summarize(prior),retention:{retainedDonors:retained.length,priorDonors:priorDonors.size,ratePercent:priorDonors.size?retained.length/priorDonors.size*100:null},cohorts:{retained:cohort('Returned from prior comparison period',retained),new:cohort('First recorded donors',newDonors),reactivated:cohort('Existing donors outside prior comparison period',reactivated),lapsed:cohort('Prior donors not yet returned',lapsed)},campaignPerformance,giftSize,frequency,offCalendar:{current:summarize(offCalendar(current)),prior:summarize(offCalendar(prior))},unattributed:summarize(current.filter(g=>!g.constituentId)),sourceGifts:[...new Map([...current,...prior,...[...new Set([...currentDonors,...priorDonors])].map(id=>first.get(id)).filter(Boolean)].map(g=>[g.id,{id:g.id,donorId:g.constituentId||null,donorName:people.get(g.constituentId)?.name||'Unavailable donor',date:g.date,schoolYear:effectiveSchoolYear(g,fiscalStartMonth),amountCents:g.amount,type:g.type,campaignId:g.campaignId||null,campaignName:campaigns.get(g.campaignId)?.name||(g.campaignId?'Unavailable campaign':'No campaign'),period:currentIds.has(g.id)?'Current':priorIds.has(g.id)?'Prior':'Historical first gift'}])).values()],scope:'Saved posted monetary contributions only: unposted and voided gifts, in-kind support, fee payments and future-dated gifts are excluded. School-year assignments are respected; original gift dates are unchanged. The prior period ends at the matching calendar cutoff (Feb 29 compares with Feb 28). Donor history is limited to saved records. This is historical analysis, not a forecast.'};
}
