import { today } from './lib';
const field = (key, label, type = 'text', extra = {}) => ({ key, label, type, ...extra });
const pick = (key,label,options) => field(key,label,'select',{options});
const ref = (key,label,collection,required=false) => field(key,label,'reference',{collection,required});
const note = (key='notes',label='Notes') => field(key,label,'textarea');
const value = (key,label,required=false) => field(key,label,'money',{required});
const day = (key,label,required=true) => field(key,label,'date',{required});
export const TYPES = ['Cash','In-kind','Grant','Fee payment','Employee giving','Sponsorship'];
export const METHODS = ['Check','Cash','Credit card','ACH','Payroll','In-kind'];
export const KINDS = ['One-time','Recurring','Pledge fulfillment','Matching gift','Planned gift'];
export const REPORTS = ['Contributions by donor','Gifts by designation','Gift ledger','First-time donors','Donor follow-up','Volunteer hours','Grant pipeline','Soft-credit recognition','Organization rollup','Household rollup','Pledge balances','Volunteer time ledger','Grant reconciliation'];
export const MODULES = {
  constituents: { title:'Constituents', singular:'constituent', description:'People and organizations connected to your foundation.', fields:[field('name','Name','text',{required:true}),field('email','Email','email'),field('phone','Phone','tel'),pick('type','Constituent type',['Individual','Business','Foundation','Alumni','Employee','Staff','Community partner']),field('household','Household'),ref('parentId','Parent organization','constituents'),field('segments','Segments','text',{hint:'Separate segments with commas.'}),pick('preference','Contact preference',['Email','Phone','Post','Do not contact']),note()], defaults:{name:'',email:'',phone:'',type:'Individual',household:'',parentId:null,segments:'',preference:'Email',notes:'',contacts:[]} },
  pledges: { title:'Pledges',singular:'pledge',description:'Plan commitments and reconcile the contributions actually received.',fields:[field('name','Pledge name','text',{required:true}),ref('constituentId','Donor','constituents',true),value('amount','Total commitment',true),day('startDate','First installment date'),field('installments','Number of installments','number',{required:true,min:1,max:120,step:1}),pick('frequency','Installment frequency',['Monthly','Quarterly','Annual']),ref('designationId','Intended designation','designations'),ref('campaignId','Campaign','campaigns'),pick('status','Status',['Active','Paused','Cancelled']),note()],defaults:{name:'',constituentId:'',amount:0,startDate:today(),installments:12,frequency:'Monthly',designationId:null,campaignId:null,status:'Active',notes:''} },
  gifts: { title:'Gifts',singular:'gift',description:'Track contributions and other revenue with a complete allocation history.',fields:[],defaults:{} },
  campaigns: { title:'Campaigns',singular:'campaign',description:'Bring your fundraising goals and giving activity together.',fields:[field('name','Campaign name','text',{required:true}),pick('type','Campaign type',['Annual','Capital','Major gifts','Planned giving','Matching gifts','Peer-to-peer']),value('goal','Goal',true),day('startDate','Start date'),day('endDate','End date'),pick('status','Status',['Active','Planned','Completed']),note('description','Description')],defaults:{name:'',type:'Annual',goal:0,startDate:today(),endDate:today(),status:'Planned',description:''} },
  grants: { title:'Grants',singular:'grant',description:'Keep prospects, proposals, awards and reporting deadlines in view.',fields:[field('name','Grant name','text',{required:true}),ref('funderId','Funder','constituents'),value('amount','Requested amount',true),value('awardedAmount','Recorded award amount'),day('awardDate','Award date',false),pick('stage','Stage',['Prospect','Preparing','Submitted','Awarded','Declined','Closed']),day('deadline','Application deadline'),day('reportDue','Report due',false),note()],defaults:{name:'',funderId:null,amount:0,awardedAmount:0,awardDate:null,stage:'Prospect',deadline:today(),reportDue:null,notes:''} },
  volunteers: { title:'Volunteers',singular:'volunteer',description:'Manage skills, event shifts and time contributed.',fields:[ref('constituentId','Volunteer','constituents',true),field('skills','Skills'),field('shift','Shift'),ref('eventId','Event','events'),field('hours','Initial hours','number',{min:0,step:0.25,createOnly:true,hint:'Clock in and out to add time after this record is created.'}),note()],defaults:{constituentId:'',skills:'',shift:'',eventId:null,hours:0,notes:''} },
  events: { title:'Events',singular:'event',description:'Plan gatherings, register guests and check in attendees.',fields:[field('name','Event name','text',{required:true}),day('date','Event date'),field('location','Location'),field('capacity','Guest capacity','number',{required:true,min:1,step:1}),value('ticketPrice','Ticket price'),value('sponsorGoal','Sponsorship goal'),note()],defaults:{name:'',date:today(),location:'',capacity:50,ticketPrice:0,sponsorGoal:0,notes:''} },
  tasks: { title:'Tasks',singular:'task',description:'A shared work queue for stewardship, deadlines and events.',fields:[field('title','Task','text',{required:true}),day('dueDate','Due date'),ref('ownerId','Assigned staff account','taskOwners'),pick('status','Status',['Open','In progress','Completed']),pick('priority','Priority',['Normal','High']),ref('constituentId','Related constituent','constituents'),ref('eventId','Related event','events'),note()],defaults:{title:'',dueDate:today(),owner:'',ownerId:null,status:'Open',priority:'Normal',constituentId:null,eventId:null,notes:''} },
  communications: { title:'Communications',singular:'interaction',description:'Prepare messages and record conversations in a constituent’s history.',fields:[ref('constituentId','Constituent','constituents'),field('subject','Subject','text',{required:true}),pick('channel','Channel',['Email','Phone','Meeting','Post']),pick('status','Status',['Draft','Logged']),day('date','Date'),note('body','Message / interaction notes'),note()],defaults:{constituentId:null,subject:'',channel:'Email',status:'Draft',date:today(),body:'Dear {{name}},\n\n',notes:''} },
  designations: { title:'Designations',singular:'designation',description:'Organize giving by foundation fund, school, program and classroom.',fields:[field('name','Designation name','text',{required:true}),field('school','School / department'),ref('parentId','Parent designation','designations'),field('accountCode','Account code'),note('description','Description')],defaults:{name:'',school:'',parentId:null,accountCode:'',description:''} }
};
